/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Open AI and AI Model gpt-5-nano

ROOST_METHOD_HASH=beforeAgentCallback_63ff4b595d
ROOST_METHOD_SIG_HASH=beforeAgentCallback_13464ee3af

Scenario 1: beforeAgentCallback_withNonNullCallback_shouldStoreInImmutableList

Details:
  TestName: beforeAgentCallback_withNonNullCallback_shouldStoreInImmutableList
  Description: Verifies that when a non-null BeforeAgentCallback is provided, the Builder stores it in an ImmutableList containing exactly that callback and returns the same Builder instance for chaining.

Execution:
  Arrange: Create a mock or stub instance of BeforeAgentCallback named callbackA. Obtain a LoopAgent.Builder instance via LoopAgent.builder().
  Act: Call builder.beforeAgentCallback(callbackA) and capture the returned Builder reference.
  Assert: Use reflection to access the private field beforeAgentCallback and verify it is an ImmutableList of size 1 containing callbackA. Also verify that the returned Builder reference is the same as the original builder (identity equality).

Validation:
  The assertion confirms that the builder correctly records the single provided callback inside an ImmutableList and supports fluent chaining by returning itself.


*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.common.collect.ImmutableList;
import java.lang.reflect.Field;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

/** Test suite for LoopAgent.Builder.beforeAgentCallback(Callbacks.BeforeAgentCallback) */
public class BuilderBeforeAgentCallbackTest {

  @Test
  @Tag("valid")
  public void test_beforeAgentCallback_withNonNullCallback_shouldStoreInImmutableList()
      throws Exception {
    // Arrange
    LoopAgent.Builder builder = LoopAgent.builder();
    // Mock the external interface
    Callbacks callbacksContainer = new Callbacks(); // if needed to instantiate,
    // otherwise use type directly
    Callbacks.BeforeAgentCallback callbackA = mock(Callbacks.BeforeAgentCallback.class);
    // Act
    LoopAgent.Builder returnedBuilder = builder.beforeAgentCallback(callbackA);
    // Assert fluent API returns the same instance
    assertSame(builder, returnedBuilder);
    // Access private field via reflection
    Field field = LoopAgent.Builder.class.getDeclaredField("beforeAgentCallback");
    field.setAccessible(true);
    Object value = field.get(returnedBuilder);
    assertNotNull(value);
    assertTrue(value instanceof ImmutableList<?>);
    ImmutableList<?> list = (ImmutableList<?>) value;
    assertEquals(1, list.size());
    assertSame(callbackA, list.get(0));
  }
}
