/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Open AI and AI Model gpt-5-nano

ROOST_METHOD_HASH=maxIterations_5c8916c7eb
ROOST_METHOD_SIG_HASH=maxIterations_a41f2ad818

Scenario 1: Positive value is stored and enables chaining in the Builder
Details:
  TestName: testMaxIterationsPositiveValue
  Description: This scenario verifies that calling maxIterations with a positive integer (e.g., 5) stores the value inside the Builder as Optional.of(5) and returns the same Builder instance to allow further chaining of builder methods.
Execution:
  Arrange: Prepare a minimal valid subAgents list with a simple stub implementation of BaseAgent that can be accepted by the Builder.
  Act: Invoke maxIterations(5) on the Builder, then perform a subsequent builder operation (for example, subAgents or name) to confirm chaining still works, and finally call build().
  Assert: Confirm that no exceptions are thrown during chaining and that a LoopAgent instance is produced when build() is called. If possible, run the agent to observe that the loop respects the configured maximum iterations (up to a practical observation limit).
Validation: The test validates that a positive value is accepted by maxIterations, stored within the builder as a concrete Optional value, and does not break the fluent API contract.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import com.google.adk.events.Event;
import io.reactivex.rxjava3.core.Flowable;
import java.util.Collections;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

public class BuilderMaxIterationsTest {

  public static class DummyAgent extends BaseAgent {

    public DummyAgent() {
      super(
          "dummy",
          "desc",
          Collections.emptyList(),
          Collections.emptyList(),
          Collections.emptyList());
    }

    @Override
    protected Flowable<Event> runAsyncImpl(InvocationContext invocationContext) {
      return Flowable.empty();
    }

    @Override
    protected Flowable<Event> runLiveImpl(InvocationContext invocationContext) {
      return Flowable.empty();
    }
  }

  @Test
  @Tag("valid")
  public void testMaxIterationsPositiveValue() {
    DummyAgent dummy = new DummyAgent();
    LoopAgent agent =
        LoopAgent.builder()
            .name("testMaxIterationsPositiveValue")
            .subAgents(dummy)
            .maxIterations(5)
            .build();
    assertNotNull(agent);
    // TODO: Further assertions on behavior can be added once accessible APIs expose
    // internal state or run behavior for verification.
  }

  @Test
  @Tag("boundary")
  public void testMaxIterationsOptionalValueStoresAndChains() {
    DummyAgent dummy = new DummyAgent();
    LoopAgent agent =
        LoopAgent.builder()
            .name("testMaxIterationsOptionalValueStoresAndChains")
            .subAgents(dummy)
            .maxIterations(Optional.of(5))
            .build();
    assertNotNull(agent);
    // TODO: Further assertions on chaining behavior can be added if needed.
  }
}
