/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Open AI and AI Model gpt-5-nano

ROOST_METHOD_HASH=maxIterations_ca0623a6b6
ROOST_METHOD_SIG_HASH=maxIterations_512cc8e3af

Scenario 1: Setting maxIterations with Optional.of(value) should store the value and allow fluent chaining

Details:
  TestName: maxIterationsWithOptionalOfValue
  Description: Verifies that calling maxIterations(Optional.of(n)) on the Builder stores the specified integer n inside the builder and returns the same Builder instance for fluent chaining. This checks both value assignment and fluent API behavior for the Optional-based overload.

Execution:
  Arrange: Create a LoopAgent.Builder instance via LoopAgent.builder(). Prepare a valid list of subAgents (e.g., a minimal list with a single dummy BaseAgent) to satisfy builder requirements.
  Act: Call maxIterations(Optional.of(5)) on the builder and capture the returned Builder reference.
  Assert: Confirm that the returned reference is the same Builder instance (fluent return) and that no exception is thrown during the call.

Validation:
  The test asserts that the Optional-wrapped value is accepted by the builder without altering the fluent contract, ensuring that the Optional-based setter behaves as designed and supports method chaining for further configuration.


*/

// ********RoostGPT********

package com.google.adk.agents;

import com.google.adk.events.Event;
import com.google.common.collect.ImmutableList;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import io.reactivex.rxjava3.core.Flowable;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.junit.jupiter.api.*;

public class BuilderMaxIterations1000Test {

	// Minimal dummy agent to satisfy builder requirements
	public static class DummyAgent extends BaseAgent {

		public DummyAgent() {
			super("dummy", "desc", List.of(), List.of(), List.of());
		}

		@Override
		protected Flowable<Event> runAsyncImpl(InvocationContext invocationContext) {
			return Flowable.empty();
		}

		@Override
		protected Flowable<Event> runLiveImpl(InvocationContext invocationContext) {
			return Flowable.empty();
		}

	}

	@Test
	@Tag("boundary")
	public void testMaxIterationsWithOptionalOfValue() {
		// Arrange: Prepare a valid sub-agent list
		LoopAgent.Builder builder = LoopAgent.builder().subAgents(new DummyAgent());
		// Act: Set maxIterations with Optional.of(value)
		LoopAgent.Builder returned = builder.maxIterations(Optional.of(5));
		// Assert: Ensure fluent chaining returns the same Builder instance
		assertSame(builder, returned);
		// Optional: ensure that a builder is produced and is non-null to satisfy further
		// steps if needed
		assertNotNull(returned);
	}

	@Test
	@Tag("boundary")
	public void testMaxIterationsWithOptionalEmpty() {
		// Arrange: Prepare a valid sub-agent list
		LoopAgent.Builder builder = LoopAgent.builder().subAgents(new DummyAgent());
		// Act: Set maxIterations with Optional.empty()
		LoopAgent.Builder returned = builder.maxIterations(Optional.empty());
		// Assert: Ensure fluent chaining returns the same Builder instance
		assertSame(builder, returned);
		assertNotNull(returned);
	}

}