/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test functional-from-source-code using AI Type Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=subAgents_018349af2f
ROOST_METHOD_SIG_HASH=subAgents_64ea8eae53

Scenario 1: Setting Multiple SubAgents with Varargs

Details:
  TestName: setMultipleSubAgentsWithVarargs
  Description: This test verifies that when multiple BaseAgent instances are passed as arguments to the subAgents(BaseAgent...) method, the Builder's subAgents field is set to an ImmutableList containing all provided agents in the correct order.
Execution:
  Arrange: Create several mock or stub BaseAgent instances.
  Act: Call the subAgents(BaseAgent...) method with these instances as arguments.
  Assert: Check that the subAgents field is an ImmutableList containing all the provided agents in the same order.
Validation:
  This assertion ensures that the method correctly handles multiple arguments and preserves their order, which is important for sequential execution logic in LoopAgent.

Scenario 2: Setting No SubAgents (Empty Varargs)

Details:
  TestName: setNoSubAgentsWithEmptyVarargs
  Description: This test checks the behavior when subAgents(BaseAgent...) is called with no arguments, ensuring the subAgents field is set to an empty ImmutableList.
Execution:
  Arrange: Prepare a Builder instance.
  Act: Invoke subAgents() with no arguments.
  Assert: Verify that the subAgents field is an empty ImmutableList.
Validation:
  This test confirms that the method gracefully handles empty input, which is important for robustness and prevents NullPointerExceptions or unexpected behavior.

Scenario 3: Setting SubAgents with Null Argument

Details:
  TestName: setSubAgentsWithNullArgument
  Description: This test examines the method's behavior when a null value is passed as the only argument to subAgents(BaseAgent...), checking for NullPointerException or correct handling.
Execution:
  Arrange: Prepare a Builder instance.
  Act: Call subAgents((BaseAgent) null).
  Assert: Check whether the method throws a NullPointerException or sets subAgents to an ImmutableList containing a single null element, depending on the implementation of ImmutableList.copyOf.
Validation:
  This test is significant for verifying the method's null-safety and ensuring that the application fails fast or handles nulls as expected.

Scenario 4: Setting SubAgents with a Single Agent

Details:
  TestName: setSingleSubAgentWithVarargs
  Description: This test ensures that when a single BaseAgent is passed to subAgents(BaseAgent...), the subAgents field is set to an ImmutableList containing only that agent.
Execution:
  Arrange: Create a single mock or stub BaseAgent instance.
  Act: Call subAgents(BaseAgent) with this instance.
  Assert: Confirm that subAgents is an ImmutableList with exactly one element, which is the provided agent.
Validation:
  This test validates that the method works correctly for the common case of a single sub-agent, ensuring correct encapsulation in an ImmutableList.

Scenario 5: Overwriting Previous SubAgents Value

Details:
  TestName: overwritePreviousSubAgentsValue
  Description: This test checks that calling subAgents(BaseAgent...) multiple times on the same Builder instance overwrites the previous value of subAgents.
Execution:
  Arrange: Create two sets of BaseAgent instances.
  Act: Call subAgents(BaseAgent...) with the first set, then call subAgents(BaseAgent...) again with the second set.
  Assert: Verify that subAgents contains only the agents from the second call.
Validation:
  This test ensures that the method does not append but replaces the subAgents list, which is important for predictable builder behavior.

Scenario 6: Chaining Method Calls

Details:
  TestName: chainingSubAgentsMethodCall
  Description: This test verifies that subAgents(BaseAgent...) returns the same Builder instance, allowing for method chaining.
Execution:
  Arrange: Prepare a Builder instance.
  Act: Call subAgents(BaseAgent...) and immediately chain another builder method (e.g., name or description).
  Assert: Check that the returned object is the same Builder instance.
Validation:
  This test confirms the builder pattern is implemented correctly, supporting fluent API usage.

Scenario 7: Setting SubAgents with Duplicates

Details:
  TestName: setSubAgentsWithDuplicateAgents
  Description: This test checks that if duplicate BaseAgent instances are passed to subAgents(BaseAgent...), all duplicates are preserved in the resulting ImmutableList.
Execution:
  Arrange: Create a BaseAgent instance and pass it multiple times to subAgents(BaseAgent...).
  Act: Call subAgents(BaseAgent, BaseAgent).
  Assert: Verify that subAgents contains both references, even if they are the same object.
Validation:
  This test ensures that the method does not filter out duplicates, which is important for scenarios where intentional repetition of agents is required.

Scenario 8: Interoperability with List-based subAgents Method

Details:
  TestName: interoperabilityWithListBasedSubAgentsMethod
  Description: This test ensures that calling subAgents(BaseAgent...) after subAgents(List) overwrites the previous list, and vice versa.
Execution:
  Arrange: Call subAgents(List) with one set of agents, then subAgents(BaseAgent...) with another set.
  Act: Observe the final value of subAgents.
  Assert: Confirm that subAgents reflects only the most recent call.
Validation:
  This test is important for verifying that both overloads of subAgents are mutually exclusive and do not merge their inputs, ensuring predictable builder state.

Scenario 9: Passing a Large Number of SubAgents

Details:
  TestName: setLargeNumberOfSubAgents
  Description: This test checks the method's ability to handle a large number of BaseAgent arguments, ensuring no performance or memory issues and correct list population.
Execution:
  Arrange: Create a large array of BaseAgent instances (e.g., 1000).
  Act: Call subAgents(BaseAgent...) with all instances.
  Assert: Verify that subAgents contains all provided agents in order.
Validation:
  This test ensures scalability and correctness for high-volume scenarios, which may be relevant for complex agent orchestration.

Scenario 10: Passing SubAgents of Different Subclasses

Details:
  TestName: setSubAgentsWithDifferentSubclasses
  Description: This test verifies that subAgents(BaseAgent...) accepts and correctly stores agents of different subclasses of BaseAgent.
Execution:
  Arrange: Create several BaseAgent instances of different concrete subclasses.
  Act: Call subAgents(BaseAgent...) with these instances.
  Assert: Check that subAgents contains all agents, preserving their types.
Validation:
  This test ensures type safety and flexibility, allowing heterogeneous agent composition in LoopAgent.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;

import com.google.adk.events.Event;
import com.google.common.collect.ImmutableList;
import io.reactivex.rxjava3.core.Flowable;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

class BuilderSubAgents39Test {

  private LoopAgent.Builder builder;

  @BeforeEach
  void setUp() {
    builder = LoopAgent.builder();
  }

  @Test
  @Tag("valid")
  public void testSetMultipleSubAgentsWithVarargs() {
    BaseAgent agent1 = Mockito.mock(BaseAgent.class);
    BaseAgent agent2 = Mockito.mock(BaseAgent.class);
    BaseAgent agent3 = Mockito.mock(BaseAgent.class);
    LoopAgent.Builder returnedBuilder = builder.subAgents(agent1, agent2, agent3);
    // Reflection to access the private field for assertion
    ImmutableList<? extends BaseAgent> subAgents =
        (ImmutableList<? extends BaseAgent>) getPrivateField(returnedBuilder, "subAgents");
    assertEquals(3, subAgents.size());
    assertSame(agent1, subAgents.get(0));
    assertSame(agent2, subAgents.get(1));
    assertSame(agent3, subAgents.get(2));
  }

  @Test
  @Tag("boundary")
  public void testSetNoSubAgentsWithEmptyVarargs() {
    LoopAgent.Builder returnedBuilder = builder.subAgents();
    ImmutableList<? extends BaseAgent> subAgents =
        (ImmutableList<? extends BaseAgent>) getPrivateField(returnedBuilder, "subAgents");
    assertNotNull(subAgents);
    assertTrue(subAgents.isEmpty());
  }

  @Test
  @Tag("invalid")
  public void testSetSubAgentsWithNullArgument() {
    try {
      builder.subAgents((BaseAgent) null);
      ImmutableList<? extends BaseAgent> subAgents =
          (ImmutableList<? extends BaseAgent>) getPrivateField(builder, "subAgents");
      assertEquals(1, subAgents.size());
      assertNull(subAgents.get(0));
    } catch (NullPointerException e) {
      // Acceptable if ImmutableList.copyOf throws NPE
      assertTrue(e instanceof NullPointerException);
    }
  }

  @Test
  @Tag("valid")
  public void testSetSingleSubAgentWithVarargs() {
    BaseAgent agent = Mockito.mock(BaseAgent.class);
    LoopAgent.Builder returnedBuilder = builder.subAgents(agent);
    ImmutableList<? extends BaseAgent> subAgents =
        (ImmutableList<? extends BaseAgent>) getPrivateField(returnedBuilder, "subAgents");
    assertEquals(1, subAgents.size());
    assertSame(agent, subAgents.get(0));
  }

  @Test
  @Tag("valid")
  public void testOverwritePreviousSubAgentsValue() {
    BaseAgent agent1 = Mockito.mock(BaseAgent.class);
    BaseAgent agent2 = Mockito.mock(BaseAgent.class);
    BaseAgent agent3 = Mockito.mock(BaseAgent.class);
    builder.subAgents(agent1, agent2);
    builder.subAgents(agent3);
    ImmutableList<? extends BaseAgent> subAgents =
        (ImmutableList<? extends BaseAgent>) getPrivateField(builder, "subAgents");
    assertEquals(1, subAgents.size());
    assertSame(agent3, subAgents.get(0));
  }

  @Test
  @Tag("valid")
  public void testChainingSubAgentsMethodCall() {
    BaseAgent agent = Mockito.mock(BaseAgent.class);
    LoopAgent.Builder returnedBuilder = builder.subAgents(agent).name("TestAgent"); // TODO:
    // Change
    // name
    // if
    // needed
    assertSame(builder, returnedBuilder);
    // Additionally, check that the name is set
    String name = (String) getPrivateField(returnedBuilder, "name");
    assertEquals("TestAgent", name);
  }

  @Test
  @Tag("valid")
  public void testSetSubAgentsWithDuplicateAgents() {
    BaseAgent agent = Mockito.mock(BaseAgent.class);
    LoopAgent.Builder returnedBuilder = builder.subAgents(agent, agent);
    ImmutableList<? extends BaseAgent> subAgents =
        (ImmutableList<? extends BaseAgent>) getPrivateField(returnedBuilder, "subAgents");
    assertEquals(2, subAgents.size());
    assertSame(agent, subAgents.get(0));
    assertSame(agent, subAgents.get(1));
  }

  @Test
  @Tag("integration")
  public void testInteroperabilityWithListBasedSubAgentsMethod() {
    BaseAgent agent1 = Mockito.mock(BaseAgent.class);
    BaseAgent agent2 = Mockito.mock(BaseAgent.class);
    BaseAgent agent3 = Mockito.mock(BaseAgent.class);
    builder.subAgents(ImmutableList.of(agent1, agent2));
    builder.subAgents(agent3);
    ImmutableList<? extends BaseAgent> subAgents =
        (ImmutableList<? extends BaseAgent>) getPrivateField(builder, "subAgents");
    assertEquals(1, subAgents.size());
    assertSame(agent3, subAgents.get(0));
    // Now reverse: set varargs, then list
    builder.subAgents(agent1, agent2);
    builder.subAgents(ImmutableList.of(agent3));
    subAgents = (ImmutableList<? extends BaseAgent>) getPrivateField(builder, "subAgents");
    assertEquals(1, subAgents.size());
    assertSame(agent3, subAgents.get(0));
  }

  @Test
  @Tag("boundary")
  public void testSetLargeNumberOfSubAgents() {
    int count = 1000; // TODO: Adjust count if needed
    BaseAgent[] agents = new BaseAgent[count];
    for (int i = 0; i < count; i++) {
      agents[i] = Mockito.mock(BaseAgent.class);
    }
    builder.subAgents(agents);
    ImmutableList<? extends BaseAgent> subAgents =
        (ImmutableList<? extends BaseAgent>) getPrivateField(builder, "subAgents");
    assertEquals(count, subAgents.size());
    for (int i = 0; i < count; i++) {
      assertSame(agents[i], subAgents.get(i));
    }
  }

  @Test
  @Tag("valid")
  public void testSetSubAgentsWithDifferentSubclasses() {
    BaseAgent agentA = Mockito.mock(BaseAgent.class);
    BaseAgent agentB = new CustomAgentB();
    BaseAgent agentC = new CustomAgentC();
    builder.subAgents(agentA, agentB, agentC);
    ImmutableList<? extends BaseAgent> subAgents =
        (ImmutableList<? extends BaseAgent>) getPrivateField(builder, "subAgents");
    assertEquals(3, subAgents.size());
    assertSame(agentA, subAgents.get(0));
    assertSame(agentB, subAgents.get(1));
    assertSame(agentC, subAgents.get(2));
    assertTrue(subAgents.get(1) instanceof CustomAgentB);
    assertTrue(subAgents.get(2) instanceof CustomAgentC);
  }

  // Helper to access private fields for testing purposes
  private Object getPrivateField(Object obj, String fieldName) {
    try {
      java.lang.reflect.Field field = obj.getClass().getDeclaredField(fieldName);
      field.setAccessible(true);
      return field.get(obj);
    } catch (Exception e) {
      throw new RuntimeException(e);
    }
  }

  // Dummy subclasses for testSetSubAgentsWithDifferentSubclasses
  static class CustomAgentB extends BaseAgent {

    CustomAgentB() {
      super("B", "descB", ImmutableList.of(), ImmutableList.of(), ImmutableList.of());
    }

    @Override
    protected Flowable<Event> runAsyncImpl(InvocationContext invocationContext) {
      return Flowable.empty();
    }

    @Override
    protected Flowable<Event> runLiveImpl(InvocationContext invocationContext) {
      return Flowable.empty();
    }
  }

  static class CustomAgentC extends BaseAgent {

    CustomAgentC() {
      super("C", "descC", ImmutableList.of(), ImmutableList.of(), ImmutableList.of());
    }

    @Override
    protected Flowable<Event> runAsyncImpl(InvocationContext invocationContext) {
      return Flowable.empty();
    }

    @Override
    protected Flowable<Event> runLiveImpl(InvocationContext invocationContext) {
      return Flowable.empty();
    }
  }
}
