/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Open AI and AI Model gpt-5-nano

ROOST_METHOD_HASH=afterAgentCallback_2d71a70f91
ROOST_METHOD_SIG_HASH=afterAgentCallback_11f525da2b

Scenario 1: Basic chaining with a single AfterAgentCallbackBase should return the same builder instance

Details:
  TestName: afterAgentCallback_withSingleCallback_shouldReturnThis
  Description: Validate that providing a single AfterAgentCallbackBase in the list results in the Builder being returned (enabling method chaining) without throwing exceptions.
Execution:
  Arrange: Create a mock or stub instance of Callbacks.AfterAgentCallbackBase to pass inside a single-element list.
  Act: Call builder().afterAgentCallback(singleElementList) on a new Builder instance.
  Assert: Verify that the returned object is the same instance as the original Builder (reference equality).
Validation:
  The assertion confirms the contract of a fluent builder by ensuring afterAgentCallback returns the current Builder, enabling subsequent builder method calls in a chain. This preserves the expected builder pattern behavior for a single callback entry.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.assertSame;

import com.google.common.collect.ImmutableList;
import java.util.List;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

public class BuilderAfterAgentCallback179Test {

  @Test
  @Tag("integration")
  public void afterAgentCallback_withSingleCallback_shouldReturnThis() {
    // Arrange
    LoopAgent.Builder builder = LoopAgent.builder();
    Callbacks.AfterAgentCallbackBase mockBase =
        Mockito.mock(Callbacks.AfterAgentCallbackBase.class);
    List<Callbacks.AfterAgentCallbackBase> list = ImmutableList.of(mockBase);
    // Act
    LoopAgent.Builder result = builder.afterAgentCallback(list);
    // Assert
    assertSame(builder, result);
  }
}
