/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test functional-from-source-code using AI Type Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=description_e419c9d57e
ROOST_METHOD_SIG_HASH=description_192aef2aea

Scenario 1: Setting a Non-Null Description Value

Details:
  TestName: setNonNullDescription
  Description: This test checks that when the description(String description) method is called with a non-null string, the Builder's description field is set to that value and the Builder instance is returned for method chaining.
Execution:
  Arrange: Create a new instance of LoopAgent.Builder.
  Act: Call the description method with a non-null string such as "Main loop agent".
  Assert: Verify that the Builder's description field is now "Main loop agent" and that the returned object is the same Builder instance.
Validation:
  The assertion ensures that the description field is correctly assigned and that the method supports fluent chaining, which is essential for builder pattern usability.

Scenario 2: Setting Description to Null

Details:
  TestName: setDescriptionToNull
  Description: This test verifies that calling description(String description) with a null value sets the Builder's description field to null and returns the Builder instance.
Execution:
  Arrange: Create a new instance of LoopAgent.Builder.
  Act: Call the description method with null as the argument.
  Assert: Check that the Builder's description field is now null and that the returned object is the same Builder instance.
Validation:
  This test confirms that the method can handle null inputs gracefully, which is important for robustness and for cases where a description is optional.

Scenario 3: Overwriting Existing Description Value

Details:
  TestName: overwriteExistingDescription
  Description: This test ensures that if the description method is called multiple times with different values, the last provided value overwrites any previous value in the Builder's description field.
Execution:
  Arrange: Create a new instance of LoopAgent.Builder and call description("First description").
  Act: Call description("Second description") on the same Builder instance.
  Assert: Verify that the description field is now "Second description".
Validation:
  The assertion checks that the latest value provided to the description method is the one stored, which is expected behavior for builder setters.

Scenario 4: Chaining Multiple Builder Methods Including Description

Details:
  TestName: chainDescriptionWithOtherBuilderMethods
  Description: This test checks that the description method can be chained with other Builder methods, and that all fields are set as expected.
Execution:
  Arrange: Create a new instance of LoopAgent.Builder.
  Act: Chain calls such as name("Agent1").description("Agent description").maxIterations(5).
  Assert: Verify that the name, description, and maxIterations fields are set to "Agent1", "Agent description", and Optional.of(5) respectively.
Validation:
  This test validates the fluent interface of the Builder, ensuring that method chaining works as intended and that each setter correctly updates its field.

Scenario 5: Setting Description to an Empty String

Details:
  TestName: setDescriptionToEmptyString
  Description: This test verifies that calling description("") sets the Builder's description field to an empty string and returns the Builder instance.
Execution:
  Arrange: Create a new instance of LoopAgent.Builder.
  Act: Call the description method with an empty string ("").
  Assert: Check that the description field is now "" (empty string).
Validation:
  The assertion ensures that the method does not reject or alter empty string inputs, which is important for distinguishing between no description and an intentionally empty one.

Scenario 6: Description Persists After Build

Details:
  TestName: descriptionPersistsAfterBuild
  Description: This test ensures that the value set by the description method is correctly passed to the constructed LoopAgent instance when build() is called.
Execution:
  Arrange: Create a new instance of LoopAgent.Builder and set the description to "Persistent description".
  Act: Call build() to create a LoopAgent instance.
  Assert: Verify that the constructed LoopAgent's description field is "Persistent description".
Validation:
  This test confirms that the Builder correctly transfers the description value to the final LoopAgent object, which is critical for the integrity of the builder pattern.

Scenario 7: Description Field Default Value Before Setting

Details:
  TestName: descriptionDefaultValueBeforeSetting
  Description: This test checks the initial value of the Builder's description field before any call to the description method.
Execution:
  Arrange: Create a new instance of LoopAgent.Builder.
  Act: Do not call the description method.
  Assert: Verify that the description field is null by default.
Validation:
  This test ensures that the description field is not pre-populated, which is important for detecting unset fields and for validation logic in the builder.

Scenario 8: Setting Description with Special Characters

Details:
  TestName: setDescriptionWithSpecialCharacters
  Description: This test verifies that the description method correctly handles strings containing special characters, such as newlines, tabs, or Unicode symbols.
Execution:
  Arrange: Create a new instance of LoopAgent.Builder.
  Act: Call the description method with a string like "Line1\nLine2\t✓".
  Assert: Check that the description field contains the exact string with special characters preserved.
Validation:
  The assertion ensures that the method does not alter or reject special characters, which is important for supporting a wide range of user inputs.

Scenario 9: Setting Description After Other Fields

Details:
  TestName: setDescriptionAfterOtherFields
  Description: This test checks that setting the description after other fields (such as name or subAgents) does not interfere with those fields and that the description is set correctly.
Execution:
  Arrange: Create a new instance of LoopAgent.Builder and set name and subAgents first.
  Act: Call the description method with "Final description".
  Assert: Verify that name and subAgents remain unchanged and description is "Final description".
Validation:
  This test confirms that the description method only affects its own field and does not inadvertently modify other builder state.

Scenario 10: Setting Description to a Very Long String

Details:
  TestName: setDescriptionToVeryLongString
  Description: This test verifies that the description method can handle very long strings without truncation or errors.
Execution:
  Arrange: Create a new instance of LoopAgent.Builder.
  Act: Call the description method with a string of significant length (e.g., 10,000 characters).
  Assert: Check that the description field contains the entire long string.
Validation:
  The assertion ensures that there are no arbitrary length restrictions or buffer overflows, which is important for robustness and scalability.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;

import java.util.Collections;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

class BuilderDescriptionTest {

  private LoopAgent.Builder builder;

  @BeforeEach
  void setUp() {
    builder = LoopAgent.builder();
  }

  @Test
  @Tag("valid")
  public void testSetNonNullDescription() {
    String desc = "Main loop agent";
    LoopAgent.Builder returned = builder.description(desc);
    assertSame(
        (LoopAgent.Builder) builder,
        (LoopAgent.Builder) returned,
        "Builder should return itself for chaining");
    // Reflection to access private field for test validation
    assertEquals(
        (String) desc,
        (String) getDescriptionField(builder),
        "Description should be set to provided value");
  }

  @Test
  @Tag("boundary")
  public void testSetDescriptionToNull() {
    LoopAgent.Builder returned = builder.description(null);
    assertSame(
        (LoopAgent.Builder) builder,
        (LoopAgent.Builder) returned,
        "Builder should return itself for chaining");
    assertNull(
        (String) getDescriptionField(builder), "Description should be null when set to null");
  }

  @Test
  @Tag("valid")
  public void testOverwriteExistingDescription() {
    builder.description("First description");
    builder.description("Second description");
    assertEquals(
        (String) "Second description",
        (String) getDescriptionField(builder),
        "Description should be overwritten by last value");
  }

  @Test
  @Tag("integration")
  public void testChainDescriptionWithOtherBuilderMethods() {
    LoopAgent.Builder chained =
        builder.name("Agent1").description("Agent description").maxIterations(5);
    assertEquals((String) "Agent1", (String) getNameField(chained), "Name should be set correctly");
    assertEquals(
        (String) "Agent description",
        (String) getDescriptionField(chained),
        "Description should be set correctly");
    assertEquals(
        (Optional<Integer>) Optional.of(5),
        (Optional<Integer>) getMaxIterationsField(chained),
        "MaxIterations should be set correctly");
  }

  @Test
  @Tag("boundary")
  public void testSetDescriptionToEmptyString() {
    LoopAgent.Builder returned = builder.description("");
    assertSame(
        (LoopAgent.Builder) builder,
        (LoopAgent.Builder) returned,
        "Builder should return itself for chaining");
    assertEquals(
        (String) "",
        (String) getDescriptionField(builder),
        "Description should be empty string when set to empty string");
  }

  @Test
  @Tag("integration")
  public void testDescriptionPersistsAfterBuild() {
    String desc = "Persistent description";
    builder.description(desc);
    LoopAgent agent = builder.build();
    assertEquals(
        (String) desc, (String) agent.description(), "Description should persist after build");
  }

  @Test
  @Tag("valid")
  public void testDescriptionDefaultValueBeforeSetting() {
    assertNull(
        (String) getDescriptionField(builder),
        "Description should be null by default before setting");
  }

  @Test
  @Tag("boundary")
  public void testSetDescriptionWithSpecialCharacters() {
    String special = "Line1\nLine2\t✓";
    builder.description(special);
    assertEquals(
        (String) special,
        (String) getDescriptionField(builder),
        "Description should preserve special characters");
  }

  @Test
  @Tag("integration")
  public void testSetDescriptionAfterOtherFields() {
    builder.name("AgentX");
    List<BaseAgent> dummySubAgents = Collections.emptyList();
    builder.subAgents(dummySubAgents);
    builder.description("Final description");
    assertEquals((String) "AgentX", (String) getNameField(builder), "Name should remain unchanged");
    assertEquals(
        (List<?>) dummySubAgents,
        (List<?>) getSubAgentsField(builder),
        "SubAgents should remain unchanged");
    assertEquals(
        (String) "Final description",
        (String) getDescriptionField(builder),
        "Description should be set correctly");
  }

  @Test
  @Tag("boundary")
  public void testSetDescriptionToVeryLongString() {
    String longDesc = "a".repeat(10_000); // 10,000 characters
    builder.description(longDesc);
    assertEquals(
        (String) longDesc,
        (String) getDescriptionField(builder),
        "Description should handle very long strings");
  }

  // Helper methods to access private fields for test validation
  private Object getDescriptionField(LoopAgent.Builder builder) {
    try {
      var field = LoopAgent.Builder.class.getDeclaredField("description");
      field.setAccessible(true);
      return field.get(builder);
    } catch (Exception e) {
      fail("Reflection failed: " + e.getMessage());
      return null;
    }
  }

  private Object getNameField(LoopAgent.Builder builder) {
    try {
      var field = LoopAgent.Builder.class.getDeclaredField("name");
      field.setAccessible(true);
      return field.get(builder);
    } catch (Exception e) {
      fail("Reflection failed: " + e.getMessage());
      return null;
    }
  }

  private Object getMaxIterationsField(LoopAgent.Builder builder) {
    try {
      var field = LoopAgent.Builder.class.getDeclaredField("maxIterations");
      field.setAccessible(true);
      return field.get(builder);
    } catch (Exception e) {
      fail("Reflection failed: " + e.getMessage());
      return null;
    }
  }

  private Object getSubAgentsField(LoopAgent.Builder builder) {
    try {
      var field = LoopAgent.Builder.class.getDeclaredField("subAgents");
      field.setAccessible(true);
      return field.get(builder);
    } catch (Exception e) {
      fail("Reflection failed: " + e.getMessage());
      return null;
    }
  }
}
