/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Open AI and AI Model gpt-5-nano

ROOST_METHOD_HASH=afterAgentCallback_2d71a70f91
ROOST_METHOD_SIG_HASH=afterAgentCallback_11f525da2b

Scenario 1: Single element input
Details:
  TestName: afterAgentCallbackSingleElement
  Description: When provided a list containing a single AfterAgentCallbackBase, the builder should convert it to a single AfterAgentCallback inside an ImmutableList and store it in afterAgentCallback.
Execution:
  Arrange: Create one mock or stub instance of AfterAgentCallbackBase.
  Act: new LoopAgent.Builder().afterAgentCallback(List.of(mockBase)).
  Assert: The builder's afterAgentCallback should be non-null, have size 1, and contain an AfterAgentCallback corresponding to the base element.
Validation: The test verifies that a single-element input is correctly transformed by CallbackUtil.getAfterAgentCallbacks and stored in the builder, preserving the intended callback.


*/

// ********RoostGPT********

package com.google.adk.agents;

import com.google.adk.events.Event;
import com.google.common.collect.ImmutableList;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import io.reactivex.rxjava3.core.Flowable;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;

/**
 * Tests for LoopAgent.Builder.afterAgentCallback(List<Callbacks.AfterAgentCallbackBase>
 * afterAgentCallback)
 */
public class BuilderAfterAgentCallback516Test {

	@Test
	@Tag("valid")
	public void testAfterAgentCallbackSingleElement() {
		LoopAgent.Builder builder = LoopAgent.builder();
		LoopAgent.Callbacks.AfterAgentCallbackBase mockBase = mock(LoopAgent.Callbacks.AfterAgentCallbackBase.class);
		LoopAgent.Builder result = builder.afterAgentCallback(List.of(mockBase));
		assertSame(builder, result,
				"afterAgentCallback should return the same builder instance for fluent chaining with a single element");
	}

	@Test
	@Tag("valid")
	public void testAfterAgentCallbackMultipleElements() {
		LoopAgent.Builder builder = LoopAgent.builder();
		LoopAgent.Callbacks.AfterAgentCallbackBase mockBase1 = mock(LoopAgent.Callbacks.AfterAgentCallbackBase.class);
		LoopAgent.Callbacks.AfterAgentCallbackBase mockBase2 = mock(LoopAgent.Callbacks.AfterAgentCallbackBase.class);
		LoopAgent.Builder result = builder.afterAgentCallback(List.of(mockBase1, mockBase2));
		assertSame(builder, result,
				"afterAgentCallback should return the same builder instance for fluent chaining with multiple elements");
	}

	@Test
	@Tag("invalid")
	public void testAfterAgentCallbackNullInput() {
		LoopAgent.Builder builder = LoopAgent.builder();
		assertThrows(NullPointerException.class, () -> builder.afterAgentCallback(null),
				"Passing null to afterAgentCallback should throw NullPointerException");
	}

}