/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Open AI and AI Model gpt-5-nano

ROOST_METHOD_HASH=build_8c66e897c7
ROOST_METHOD_SIG_HASH=build_1ad0a95df7


Scenario 1: Basic build with all fields provided and a single sub-agent
Details:
  TestName: basicBuildWithAllFields
  Description: Verifies that Builder.build() returns a valid LoopAgent when all fields are supplied, including a non-empty name and description, one sub-agent, a defined maxIterations, and both before and after agent callbacks.
Execution:
  Arrange: Create a mock or stub BaseAgent instance named subAgent. Create one BeforeAgentCallback instance and one AfterAgentCallback instance. Prepare a subAgents list containing the single subAgent. Use LoopAgent.builder() with name, description, subAgents, maxIterations set to a concrete value (e.g., 5), beforeAgentCallback, and afterAgentCallback, then call build().
  Act: Execute the build() process to instantiate the LoopAgent.
  Assert: The resulting object is non-null and is an instance of LoopAgent. The internal configuration matches the provided values: name, description, subAgents, maxIterations = Optional.of(5), beforeAgentCallback, and afterAgentCallback are all preserved in the constructed instance (verified via reflection if necessary).
Validation: The test confirms that the Builder correctly transfers all provided configuration into the LoopAgent constructor, ensuring no data is lost or misassigned during object creation.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.common.collect.ImmutableList;
import java.lang.reflect.Field;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class BuilderBuildTest {

  private static final String TEST_NAME = "testName";

  private static final String TEST_DESC = "testDescription";

  @Test
  @Tag("integration")
  public void testBasicBuildWithAllFields() throws Exception {
    // Arrange
    BaseAgent subAgent = mock(BaseAgent.class);
    Callbacks.BeforeAgentCallback beforeCb = mock(Callbacks.BeforeAgentCallback.class);
    Callbacks.AfterAgentCallback afterCb = mock(Callbacks.AfterAgentCallback.class);
    LoopAgent.Builder builder =
        LoopAgent.builder()
            .name(TEST_NAME)
            .description(TEST_DESC)
            .subAgents(Arrays.asList(subAgent))
            .maxIterations(5)
            .beforeAgentCallback(beforeCb)
            .afterAgentCallback(afterCb);
    // Act
    LoopAgent loopAgent = builder.build();
    // Assert
    assertNotNull(loopAgent, "LoopAgent should not be null after build.");
    Field nameField = LoopAgent.class.getDeclaredField("name");
    nameField.setAccessible(true);
    assertEquals(TEST_NAME, nameField.get(loopAgent), "Name should be preserved in LoopAgent.");
    Field descriptionField = LoopAgent.class.getDeclaredField("description");
    descriptionField.setAccessible(true);
    assertEquals(
        TEST_DESC,
        descriptionField.get(loopAgent),
        "Description should be preserved in LoopAgent.");
    Field subAgentsField = LoopAgent.class.getDeclaredField("subAgents");
    subAgentsField.setAccessible(true);
    @SuppressWarnings("unchecked")
    List<? extends BaseAgent> subAgentsValue =
        (List<? extends BaseAgent>) subAgentsField.get(loopAgent);
    assertNotNull(subAgentsValue, "subAgents should not be null.");
    assertEquals(1, subAgentsValue.size(), "subAgents should contain exactly one element.");
    assertEquals(
        subAgent, subAgentsValue.get(0), "subAgents should contain the provided subAgent.");
    Field maxIterationsField = LoopAgent.class.getDeclaredField("maxIterations");
    maxIterationsField.setAccessible(true);
    @SuppressWarnings("unchecked")
    Optional<Integer> maxIterationsValue = (Optional<Integer>) maxIterationsField.get(loopAgent);
    assertTrue(maxIterationsValue.isPresent(), "maxIterations should be present when set.");
    assertEquals(
        Integer.valueOf(5),
        maxIterationsValue.get(),
        "maxIterations should be equal to the provided value.");
    Field beforeCbField = LoopAgent.class.getDeclaredField("beforeAgentCallback");
    beforeCbField.setAccessible(true);
    @SuppressWarnings("unchecked")
    ImmutableList<Callbacks.BeforeAgentCallback> beforeCbValue =
        (ImmutableList<Callbacks.BeforeAgentCallback>) beforeCbField.get(loopAgent);
    assertNotNull(beforeCbValue, "beforeAgentCallback should not be null.");
    assertEquals(
        1, beforeCbValue.size(), "beforeAgentCallback should contain exactly one callback.");
    assertEquals(
        beforeCb,
        beforeCbValue.get(0),
        "beforeAgentCallback should contain the provided callback.");
    Field afterCbField = LoopAgent.class.getDeclaredField("afterAgentCallback");
    afterCbField.setAccessible(true);
    @SuppressWarnings("unchecked")
    ImmutableList<Callbacks.AfterAgentCallback> afterCbValue =
        (ImmutableList<Callbacks.AfterAgentCallback>) afterCbField.get(loopAgent);
    assertNotNull(afterCbValue, "afterAgentCallback should not be null.");
    assertEquals(1, afterCbValue.size(), "afterAgentCallback should contain exactly one callback.");
    assertEquals(
        afterCb, afterCbValue.get(0), "afterAgentCallback should contain the provided callback.");
  }

  @Test
  @Tag("boundary")
  public void testBuildWithSubAgentsVarArgsAndEmptyMaxIterations() throws Exception {
    // Arrange
    BaseAgent sub1 = mock(BaseAgent.class);
    BaseAgent sub2 = mock(BaseAgent.class);
    LoopAgent.Builder builder =
        LoopAgent.builder()
            .name("VarArgsTest")
            .description("VarArgs description")
            .subAgents(sub1, sub2);
    // Act
    LoopAgent loopAgent = builder.build();
    // Assert
    assertNotNull(loopAgent, "LoopAgent should not be null after build.");
    Field nameField = LoopAgent.class.getDeclaredField("name");
    nameField.setAccessible(true);
    assertEquals("VarArgsTest", nameField.get(loopAgent), "Name should match provided value.");
    Field descriptionField = LoopAgent.class.getDeclaredField("description");
    descriptionField.setAccessible(true);
    assertEquals(
        "VarArgs description",
        descriptionField.get(loopAgent),
        "Description should match provided value.");
    Field subAgentsField = LoopAgent.class.getDeclaredField("subAgents");
    subAgentsField.setAccessible(true);
    @SuppressWarnings("unchecked")
    List<? extends BaseAgent> subAgentsValue =
        (List<? extends BaseAgent>) subAgentsField.get(loopAgent);
    assertNotNull(subAgentsValue, "subAgents should not be null.");
    assertEquals(2, subAgentsValue.size(), "subAgents should contain two elements.");
    assertEquals(sub1, subAgentsValue.get(0), "First subAgent should match the provided instance.");
    assertEquals(
        sub2, subAgentsValue.get(1), "Second subAgent should match the provided instance.");
    Field maxIterationsField = LoopAgent.class.getDeclaredField("maxIterations");
    maxIterationsField.setAccessible(true);
    @SuppressWarnings("unchecked")
    Optional<Integer> maxIterationsValue = (Optional<Integer>) maxIterationsField.get(loopAgent);
    assertTrue(
        maxIterationsValue.isEmpty(), "maxIterations should be empty by default when not set.");
  }
}
