/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Open AI and AI Model gpt-5-nano

ROOST_METHOD_HASH=maxIterations_5c8916c7eb
ROOST_METHOD_SIG_HASH=maxIterations_a41f2ad818

Scenario 1: maxIterationsWithPositiveValue

Details:
  TestName: maxIterationsWithPositiveValue
  Description: Validate that setting a positive maxIterations value on the Builder results in the loop performing that exact number of iterations of its sub-agents, assuming no escalation occurs.

Execution:
  Arrange: Prepare a deterministic sub-agent that completes a non-escalating event in a single run. Build a LoopAgent using LoopAgent.builder() with that sub-agent, and call maxIterations(5) on the Builder before building.
  Act: Build the LoopAgent and initiate its execution flow (e.g., by invoking the runAsync path with an appropriate invocation context).
  Assert: The sub-agent should be invoked exactly five times (one full iteration per repeat), and the overall execution should complete without escalation.

Validation:
  Clarify that the explicit maximum iteration of five is respected, ensuring the loop terminates after five complete iterations when there is no escalation. This confirms that maxIterations properly governs the repetition cap in the absence of escalation.


*/

// ********RoostGPT********

package com.google.adk.agents;

import com.google.adk.events.Event;
import com.google.common.collect.ImmutableList;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import io.reactivex.rxjava3.core.Flowable;
import java.util.Collections;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;
import org.junit.jupiter.api.*;

public class BuilderMaxIterationsTest {

	// Simple non-escalating sub-agent for deterministic testing
	static class SimpleNonEscalatingAgent extends BaseAgent {

		public SimpleNonEscalatingAgent(String name) {
			super(name, "desc", Collections.emptyList(), Collections.emptyList(), Collections.emptyList());
		}

		@Override
		protected Flowable<Event> runAsyncImpl(InvocationContext invocationContext) {
			Event event = Event.builder().id(Event.generateEventId()).build();
			return Flowable.just(event);
		}

		@Override
		protected Flowable<Event> runLiveImpl(InvocationContext invocationContext) {
			return Flowable.empty();
		}

	}

	@Test
	@Tag("boundary")
	public void testMaxIterationsWithPositiveValue() {
		SimpleNonEscalatingAgent sub = new SimpleNonEscalatingAgent("sub1");
		LoopAgent loop = LoopAgent.builder().subAgents(sub).maxIterations(5).build();
		BaseSessionService sessionService = mock(BaseSessionService.class);
		BaseArtifactService artifactService = mock(BaseArtifactService.class);
		Session session = mock(Session.class);
		RunConfig runConfig = mock(RunConfig.class);
		InvocationContext parentContext = InvocationContext.create(sessionService, artifactService, "parentInvoc", loop,
				session, null, runConfig);
		List<Event> events = loop.runAsync(parentContext).toList().blockingGet();
		assertEquals(5, events.size(), "Expected exactly 5 events corresponding to 5 iterations");
	}

	@Test
	@Tag("boundary")
	public void testMaxIterationsWithZeroValue() {
		SimpleNonEscalatingAgent sub = new SimpleNonEscalatingAgent("sub2");
		LoopAgent loop = LoopAgent.builder().subAgents(sub).maxIterations(0).build();
		BaseSessionService sessionService = mock(BaseSessionService.class);
		BaseArtifactService artifactService = mock(BaseArtifactService.class);
		Session session = mock(Session.class);
		RunConfig runConfig = mock(RunConfig.class);
		InvocationContext parentContext = InvocationContext.create(sessionService, artifactService, "parentInvocZero",
				loop, session, null, runConfig);
		List<Event> events = loop.runAsync(parentContext).toList().blockingGet();
		assertEquals(0, events.size(), "Expected no events when maxIterations is zero");
	}

}