/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Open AI and AI Model gpt-5-nano

ROOST_METHOD_HASH=subAgents_018349af2f
ROOST_METHOD_SIG_HASH=subAgents_64ea8eae53

Scenario 1: Basic single sub-agent
Details:
  TestName: basicSubAgentsSingleElement
  Description: The subAgents(BaseAgent... subAgents) method should correctly store a single provided sub-agent in an immutable list and return the same Builder instance for chaining.
Execution:
  Arrange: Create a mock or stub implementation of BaseAgent named subAgent1. Prepare a LoopAgent.Builder instance via LoopAgent.builder().
  Act: Call builder.subAgents(subAgent1).
  Assert: The method returns the exact same Builder instance (fluent API). The internal subAgents collection should contain exactly one element, and that element should be subAgent1.
Validation: The assertion verifies that a single provided sub-agent is captured in an immutable copy and that fluent chaining remains possible with the same builder instance. This ensures correct handling of the varargs input and preserves expected builder behavior.


*/

// ********RoostGPT********

package com.google.adk.agents;

import com.google.adk.events.Event;
import com.google.common.collect.ImmutableList;
import io.reactivex.rxjava3.core.Flowable;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import java.util.Optional;

public class BuilderSubAgents811Test {

	@Test
	@Tag("valid")
	public void basicSubAgentsSingleElement() throws Exception {
		// Arrange: create a simple sub-agent
		List<BaseAgent> subAgentsForSubAgent = Collections.<BaseAgent>emptyList();
		List<Callbacks.BeforeAgentCallback> beforeCallbacksForSubAgent = new ArrayList<>();
		List<Callbacks.AfterAgentCallback> afterCallbacksForSubAgent = new ArrayList<>();
		BaseAgent subAgent1 = new BaseAgent("sub1", "desc", subAgentsForSubAgent, beforeCallbacksForSubAgent,
				afterCallbacksForSubAgent) {
			@Override
			protected Flowable<Event> runAsyncImpl(InvocationContext invocationContext) {
				return Flowable.empty();
			}

			@Override
			protected Flowable<Event> runLiveImpl(InvocationContext invocationContext) {
				return Flowable.empty();
			}
		};
		LoopAgent.Builder builder = LoopAgent.builder();
		// Act: add a single sub-agent
		LoopAgent.Builder returned = builder.subAgents(subAgent1);
		// Assert: fluent API returns the same builder instance
		assertSame(builder, returned, "subAgents should return the same Builder instance for chaining.");
		// Reflectively inspect the private subAgents field to ensure it contains exactly
		// one element
		Field field = LoopAgent.Builder.class.getDeclaredField("subAgents");
		field.setAccessible(true);
		Object fieldValue = field.get(builder);
		assertNotNull(fieldValue, "subAgents field should not be null after setting.");
		assertTrue(fieldValue instanceof ImmutableList, "subAgents field should be an ImmutableList.");
		ImmutableList<? extends BaseAgent> list = (ImmutableList<? extends BaseAgent>) fieldValue;
		assertEquals(1, list.size(), "subAgents should contain exactly one element.");
		assertEquals(subAgent1, list.get(0), "The single element should be the provided subAgent1.");
	}

	@Test
	@Tag("valid")
	public void subAgentsNoElements() throws Exception {
		LoopAgent.Builder builder = LoopAgent.builder();
		LoopAgent.Builder returned = builder.subAgents();
		// Assert fluent API returns the same builder
		assertSame(builder, returned, "subAgents() with no args should return the same Builder instance for chaining.");
		// Reflectively inspect the private subAgents field to ensure it is empty
		Field field = LoopAgent.Builder.class.getDeclaredField("subAgents");
		field.setAccessible(true);
		Object fieldValue = field.get(builder);
		assertNotNull(fieldValue, "subAgents field should not be null after setting.");
		assertTrue(fieldValue instanceof ImmutableList, "subAgents field should be an ImmutableList.");
		ImmutableList<? extends BaseAgent> list = (ImmutableList<? extends BaseAgent>) fieldValue;
		assertEquals(0, list.size(), "subAgents should be empty when no arguments are provided.");
	}

	// Minimal stubs to compile against provided types
	// (No additional behavior is required for these tests)
	private static class Callbacks {

		interface BeforeAgentCallback {

		}

		interface AfterAgentCallback {

		}

	}
	// Since this test resides in the same package, we rely on the existing BaseAgent and
	// LoopAgent definitions.
	// The actual Run/Live implementations in BaseAgent are mocked above for test
	// purposes.

}