/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Open AI and AI Model gpt-5-nano

ROOST_METHOD_HASH=subAgents_018349af2f
ROOST_METHOD_SIG_HASH=subAgents_64ea8eae53

Scenario 1: Basic behavior with two elements verifies immutability and builder chaining

Details:
  TestName: subAgentsBasicWithTwoElements
  Description: Verify that calling subAgents(BaseAgent... subAgents) with two non-null agents stores both elements into an immutable copy and returns the same Builder instance for method chaining.

Execution:
  Arrange: Create two simple BaseAgent implementations (agentA and agentB) suitable for test doubles.
  Act: Call LoopAgent.builder().subAgents(agentA, agentB).
  Assert: Ensure the returned object is the same Builder instance (same reference). Then build a LoopAgent and verify, in principle, that running the agent would process agentA followed by agentB in sequence.
Validation: The assertion confirms that the builder supports fluent chaining and that the internal subAgents collection preserves the provided order and contents as an immutable copy.


*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.common.collect.ImmutableList;
import java.util.List;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

public class BuilderSubAgents460Test {

  @Test
  @Tag("valid")
  public void subAgentsBasicWithTwoElements() {
    // Arrange: create two simple BaseAgent implementations (as mocks)
    BaseAgent agentA = mock(BaseAgent.class);
    BaseAgent agentB = mock(BaseAgent.class);
    // Act: use the Builder to set two subAgents and ensure fluent chaining
    LoopAgent.Builder builder = LoopAgent.builder();
    LoopAgent.Builder chained = builder.subAgents(agentA, agentB);
    // Assert: chaining returns the same Builder instance
    assertSame(builder, chained);
    // Act: build the LoopAgent and verify subAgents order
    LoopAgent loopAgent = chained.build();
    List<? extends BaseAgent> subs = loopAgent.subAgents();
    // Assert: correct size and order
    assertNotNull(subs);
    assertEquals(2, subs.size());
    assertEquals(agentA, subs.get(0));
    assertEquals(agentB, subs.get(1));
    // Additional assertion: internal storage is immutable
    assertTrue(subs instanceof ImmutableList);
    ImmutableList<BaseAgent> imm = (ImmutableList<BaseAgent>) subs;
    BaseAgent dummy = mock(BaseAgent.class);
    assertThrows(UnsupportedOperationException.class, () -> imm.add(dummy));
    // TODO: If needed in future, verify imm.containsAll(...) or imm.get(index)
    // semantics
  }
}
