/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Open AI and AI Model gpt-5-nano

ROOST_METHOD_HASH=subAgents_b6c24fb403
ROOST_METHOD_SIG_HASH=subAgents_c4c486c855

Scenario 1: subAgentsWithValidListReturnsThisBuilder

Details:
  TestName: subAgentsWithValidListReturnsThisBuilder
  Description: This scenario validates that when a valid, non-empty List of subAgents is provided to subAgents, the Builder returns itself to allow fluent method chaining and stores the reference to the provided list for later use when building the LoopAgent.

Execution:
  Arrange: Create two or more concrete BaseAgent instances (or suitable stubs) and assemble them into a non-empty List<? extends BaseAgent>.
  Act: Call the method subAgents with the prepared list on a LoopAgent.Builder instance.
  Assert: The returned object should be the same LoopAgent.Builder instance (reference equality).

Validation:
  Confirm that the fluent API behavior is preserved by ensuring the same builder instance is returned, enabling subsequent chained calls without creating a new builder.


*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;

import com.google.adk.events.Event;
import io.reactivex.rxjava3.core.Flowable;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

public class BuilderSubAgentsTest {

  static class TestAgent extends BaseAgent {

    public TestAgent(String name) {
      super(name, "desc", Collections.<BaseAgent>emptyList(), null, null);
    }

    @Override
    protected Flowable<Event> runAsyncImpl(InvocationContext invocationContext) {
      return Flowable.empty();
    }

    @Override
    protected Flowable<Event> runLiveImpl(InvocationContext invocationContext) {
      return Flowable.empty();
    }
  }

  @Test
  @Tag("valid")
  public void subAgentsWithValidListReturnsThisBuilder() {
    // Arrange
    TestAgent agentA = new TestAgent("AgentA");
    TestAgent agentB = new TestAgent("AgentB");
    List<? extends BaseAgent> subAgents = Arrays.asList(agentA, agentB);
    // TODO: Replace with real concrete agents if needed in integration tests
    // Act
    LoopAgent.Builder builder = LoopAgent.builder();
    LoopAgent.Builder returned = builder.subAgents(subAgents);
    // Assert: fluent API should return the same builder instance
    assertSame(
        builder, returned, "subAgents should return the same builder instance for fluent chaining");
    // Build the LoopAgent and verify it stored the provided subAgents
    LoopAgent builtAgent = returned.build();
    List<? extends BaseAgent> builtSubAgents = builtAgent.subAgents(); // public
    // method from
    // BaseAgent
    // Validate that the stored subAgents match the provided list
    assertEquals(
        subAgents,
        builtSubAgents,
        "The LoopAgent built should expose the same subAgents list as provided");
  }
}
