/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Open AI and AI Model gpt-5-nano

ROOST_METHOD_HASH=beforeAgentCallback_529d272ee9
ROOST_METHOD_SIG_HASH=beforeAgentCallback_99ae68fa16

Scenario 1: setBeforeAgentCallback_withSingleItem
Details:
  TestName: setBeforeAgentCallback_withSingleItem
  Description: Verifies that supplying a list containing a single BeforeAgentCallbackBase item to the beforeAgentCallback method returns the same Builder instance (enabling chaining) and configures the builder to include exactly one callback after building a LoopAgent.
Execution:
  Arrange: Prepare a List<Callbacks.BeforeAgentCallbackBase> containing one dummy BeforeAgentCallbackBase instance.
  Act: Invoke LoopAgent.builder().beforeAgentCallback(theOneItemList).
  Assert: The returned object is the same Builder instance; chaining remains possible; when built with required fields, the resulting LoopAgent contains one configured BeforeAgentCallback (as produced by CallbackUtil).
Validation: Confirms that a single input item is accepted, does not throw, and preserves chainability, ensuring the conversion path via CallbackUtil handles a single element as expected.

Scenario 2: setBeforeAgentCallback_withEmptyList
Details:
  TestName: setBeforeAgentCallback_withEmptyList
  Description: Ensures that providing an empty list to beforeAgentCallback results in a successful call that returns the same Builder instance and configures the builder with zero BeforeAgentCallback entries when the LoopAgent is built.
Execution:
  Arrange: Prepare an empty List<Callbacks.BeforeAgentCallbackBase>.
  Act: Call LoopAgent.builder().beforeAgentCallback(emptyList).
  Assert: The call returns the same Builder instance; building a LoopAgent proceeds without any BeforeAgentCallback configured.
Validation: Verifies that an empty input does not cause errors and results in no before-agent callbacks being registered, as expected.

Scenario 3: setBeforeAgentCallback_withNullInput
Details:
  TestName: setBeforeAgentCallback_withNullInput
  Description: Tests the behavior when null is passed as the beforeAgentCallback parameter to the builder method, ensuring no unexpected exceptions are thrown and that chaining remains possible.
Execution:
  Arrange: Prepare a null List<Callbacks.BeforeAgentCallbackBase>.
  Act: Invoke LoopAgent.builder().beforeAgentCallback(null).
  Assert: The method returns the same Builder instance; subsequent build should not fail due to missing callbacks (assuming CallbackUtil handles null gracefully).
Validation: Confirms robustness against null input and preserves fluent builder usage.

Scenario 4: setBeforeAgentCallback_overwritesPreviousValue
Details:
  TestName: setBeforeAgentCallback_overwritesPreviousValue
  Description: Validates that calling beforeAgentCallback more than once on the same Builder instance results in the most recent input taking effect, enabling an overwrite of prior callbacks.
Execution:
  Arrange: Create two lists: firstList with one item, secondList with two items.
  Act: Call builder.beforeAgentCallback(firstList).beforeAgentCallback(secondList).
  Assert: The final configuration reflects the secondList (the last write wins) and the Builder remains chainable.
Validation: Ensures predictable override semantics when multiple calls are made, preventing residual earlier configurations.

Scenario 5: setBeforeAgentCallback_withMultipleItems
Details:
  TestName: setBeforeAgentCallback_withMultipleItems
  Description: Ensures that a list containing multiple distinct BeforeAgentCallbackBase items is accepted, converted via CallbackUtil, and results in a builder configuration that supports multiple pre-agent callbacks.
Execution:
  Arrange: Prepare a List with several BeforeAgentCallbackBase instances (e.g., itemA, itemB, itemC).
  Act: Call LoopAgent.builder().beforeAgentCallback(theMultiItemList).
  Assert: The Builder instance is returned for chaining; when built, the resulting LoopAgent should reflect multiple configured callbacks (as produced by CallbackUtil).
Validation: Verifies handling of multi-element inputs and proper delegation to CallbackUtil for conversion to ImmutableList.

Scenario 6: setBeforeAgentCallback_withMixedSubtypes
Details:
  TestName: setBeforeAgentCallback_withMixedSubtypes
  Description: Tests that a list containing multiple concrete subclasses of BeforeAgentCallbackBase is accepted, ensuring the method correctly handles diverse implementations and forwards them through CallbackUtil.
Execution:
  Arrange: Create a List<Callbacks.BeforeAgentCallbackBase> with instances of different concrete subclasses.
  Act: Call LoopAgent.builder().beforeAgentCallback(theMixedList).
  Assert: The call returns the same Builder instance; building a LoopAgent should reflect the mixed callbacks as configured.
Validation: Confirms that various concrete callback implementations can be supplied and are properly processed by the builder.

Scenario 7: setBeforeAgentCallback_chainabilityWithOtherFields
Details:
  TestName: setBeforeAgentCallback_chainabilityWithOtherFields
  Description: Verifies that after setting beforeAgentCallback, subsequent builder methods (e.g., name, description, subAgents) remain chainable and can be combined in a single fluent sequence.
Execution:
  Arrange: Prepare a valid subAgents list and other fields; prepare a single-item BeforeAgentCallback list.
  Act: Chain builder.beforeAgentCallback(list).name("Agent").description("Description").subAgents(subAgents).
  Assert: Each method call returns the same Builder instance to allow full chaining.
Validation: Ensures fluent API behavior remains intact when combining beforeAgentCallback with other configuration steps.

Scenario 8: setBeforeAgentCallback_buildImpactOnLaterLoopAgent
Details:
  TestName: setBeforeAgentCallback_buildImpactOnLaterLoopAgent
  Description: Assesses that configuring beforeAgentCallback via the builder influences the eventual LoopAgent behavior when incorporated into a full build (mocked subAgents and lifecycle context assumed).
Execution:
  Arrange: Create a minimal subAgents list with a mock or dummy BaseAgent, and a one-item BeforeAgentCallback list.
  Act: Build a LoopAgent with the configured builder (name, description, subAgents, maxIterations, beforeAgentCallback, and optional others).
  Assert: The resulting LoopAgent is constructible and, in a broader test, would execute the before-agent callbacks in the expected lifecycle (as per the surrounding system).
Validation: Validates that the builder pathway for beforeAgentCallback integrates correctly into the object graph and supports the expected lifecycle integration.

Scenario 9: setBeforeAgentCallback_noEffectWhenCallbackBaseListIsNull
Details:
  TestName: setBeforeAgentCallback_noEffectWhenCallbackBaseListIsNull
  Description: Ensures that if CallbackUtil.getBeforeAgentCallbacks returns an empty list or no callbacks when provided null, the Builder remains functional and the resulting LoopAgent proceeds without callbacks.
Execution:
  Arrange: Provide null or a null-derived list and observe the outcome via the builder chain.
  Act: Call LoopAgent.builder().beforeAgentCallback(nullList).
  Assert: The chain remains intact; building proceeds without error and without configured callbacks.
Validation: Confirms graceful degradation when the input callbacks list is effectively absent.

Scenario 10: setBeforeAgentCallback_withNullElementsWithinList
Details:
  TestName: setBeforeAgentCallback_withNullElementsWithinList
  Description: Verifies that a list containing null elements among valid BeforeAgentCallbackBase instances is handled gracefully by CallbackUtil and does not disrupt the builder chain.
Execution:
  Arrange: Prepare a List containing a mix of a valid BeforeAgentCallbackBase instance and null entries.
  Act: Call LoopAgent.builder().beforeAgentCallback(theMixedListWithNulls).
  Assert: The method returns the same Builder instance; no exception is thrown; the resulting configuration reflects only the non-null callbacks.
Validation: Ensures resilience to nulls inside the input collection and consistent builder behavior.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.common.collect.ImmutableList;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

public class BuilderBeforeAgentCallback428Test {

  private int getBeforeAgentCallbackSize(LoopAgent agent) {
    try {
      Field field = LoopAgent.class.getDeclaredField("beforeAgentCallback");
      field.setAccessible(true);
      ImmutableList<?> list = (ImmutableList<?>) field.get(agent);
      return list.size();
    } catch (Exception e) {
      throw new RuntimeException(e);
    }
  }

  @Test
  @Tag("valid")
  public void testSetBeforeAgentCallback_withSingleItem() {
    LoopAgent.Builder builder = LoopAgent.builder();
    Callbacks.BeforeAgentCallbackBase mockItem = mock(Callbacks.BeforeAgentCallbackBase.class);
    List<Callbacks.BeforeAgentCallbackBase> input = new ArrayList<>();
    input.add(mockItem);
    LoopAgent.Builder returned = builder.beforeAgentCallback(input);
    assertSame(builder, returned);
    LoopAgent agent = returned.build();
    int size = getBeforeAgentCallbackSize(agent);
    assertEquals(1, size);
  }

  @Test
  @Tag("valid")
  public void testSetBeforeAgentCallback_withEmptyList() {
    LoopAgent.Builder builder = LoopAgent.builder();
    List<Callbacks.BeforeAgentCallbackBase> input = new ArrayList<>();
    LoopAgent.Builder returned = builder.beforeAgentCallback(input);
    assertSame(builder, returned);
    LoopAgent agent = returned.build();
    int size = getBeforeAgentCallbackSize(agent);
    assertEquals(0, size);
  }

  @Test
  @Tag("boundary")
  public void testSetBeforeAgentCallback_withNullInput() {
    LoopAgent.Builder builder = LoopAgent.builder();
    LoopAgent.Builder returned = builder.beforeAgentCallback(null);
    assertSame(builder, returned);
    LoopAgent agent = returned.build();
    int size = getBeforeAgentCallbackSize(agent);
    assertEquals(0, size);
  }

  @Test
  @Tag("integration")
  public void testSetBeforeAgentCallback_overwritesPreviousValue() {
    LoopAgent.Builder builder = LoopAgent.builder();
    List<Callbacks.BeforeAgentCallbackBase> firstList = new ArrayList<>();
    firstList.add(mock(Callbacks.BeforeAgentCallbackBase.class));
    List<Callbacks.BeforeAgentCallbackBase> secondList = new ArrayList<>();
    secondList.add(mock(Callbacks.BeforeAgentCallbackBase.class));
    secondList.add(mock(Callbacks.BeforeAgentCallbackBase.class));
    LoopAgent.Builder b1 = builder.beforeAgentCallback(firstList);
    LoopAgent.Builder b2 = b1.beforeAgentCallback(secondList);
    assertSame(b1, b2);
    LoopAgent agent = b2.build();
    int size = getBeforeAgentCallbackSize(agent);
    assertEquals(2, size);
  }

  @Test
  @Tag("valid")
  public void testSetBeforeAgentCallback_withMultipleItems() {
    LoopAgent.Builder builder = LoopAgent.builder();
    List<Callbacks.BeforeAgentCallbackBase> list = new ArrayList<>();
    list.add(mock(Callbacks.BeforeAgentCallbackBase.class));
    list.add(mock(Callbacks.BeforeAgentCallbackBase.class));
    list.add(mock(Callbacks.BeforeAgentCallbackBase.class));
    LoopAgent.Builder returned = builder.beforeAgentCallback(list);
    assertSame(builder, returned);
    LoopAgent agent = returned.build();
    int size = getBeforeAgentCallbackSize(agent);
    assertEquals(3, size);
  }

  @Test
  @Tag("integration")
  public void testSetBeforeAgentCallback_withMixedSubtypes() {
    LoopAgent.Builder builder = LoopAgent.builder();
    List<Callbacks.BeforeAgentCallbackBase> list = new ArrayList<>();
    list.add(mock(Callbacks.BeforeAgentCallbackBase.class));
    list.add(mock(Callbacks.BeforeAgentCallbackBase.class));
    LoopAgent.Builder returned = builder.beforeAgentCallback(list);
    assertSame(builder, returned);
    LoopAgent agent = returned.build();
    int size = getBeforeAgentCallbackSize(agent);
    assertEquals(2, size);
  }

  @Test
  @Tag("integration")
  public void testSetBeforeAgentCallback_chainabilityWithOtherFields() {
    LoopAgent.Builder builder = LoopAgent.builder();
    List<Callbacks.BeforeAgentCallbackBase> list = new ArrayList<>();
    list.add(mock(Callbacks.BeforeAgentCallbackBase.class));
    LoopAgent.Builder b1 = builder.beforeAgentCallback(list);
    LoopAgent.Builder b2 = b1.name("AgentName");
    LoopAgent.Builder b3 = b2.description("Description");
    LoopAgent.Builder b4 = b3.subAgents(Collections.emptyList());
    assertSame(builder, b1);
    assertSame(b1, b2);
    assertSame(b2, b3);
    assertSame(b3, b4);
    LoopAgent agent = b4.build();
    int size = getBeforeAgentCallbackSize(agent);
    assertEquals(1, size);
  }

  @Test
  @Tag("integration")
  public void testSetBeforeAgentCallback_buildImpactOnLaterLoopAgent() {
    LoopAgent.Builder builder = LoopAgent.builder();
    List<Callbacks.BeforeAgentCallbackBase> list = new ArrayList<>();
    list.add(mock(Callbacks.BeforeAgentCallbackBase.class));
    LoopAgent agent =
        builder.name("Agent").subAgents(Collections.emptyList()).beforeAgentCallback(list).build();
    assertNotNull(agent);
  }

  @Test
  @Tag("boundary")
  public void testSetBeforeAgentCallback_noEffectWhenCallbackBaseListIsNull() {
    LoopAgent.Builder builder = LoopAgent.builder();
    LoopAgent.Builder ret = builder.beforeAgentCallback(null);
    assertSame(builder, ret);
    LoopAgent agent = ret.build();
    int size = getBeforeAgentCallbackSize(agent);
    assertEquals(0, size);
  }

  @Test
  @Tag("boundary")
  public void testSetBeforeAgentCallback_withNullElementsWithinList() {
    LoopAgent.Builder builder = LoopAgent.builder();
    Callbacks.BeforeAgentCallbackBase a = mock(Callbacks.BeforeAgentCallbackBase.class);
    Callbacks.BeforeAgentCallbackBase b = mock(Callbacks.BeforeAgentCallbackBase.class);
    List<Callbacks.BeforeAgentCallbackBase> list = new ArrayList<>();
    list.add(a);
    list.add(null);
    list.add(b);
    LoopAgent.Builder ret = builder.beforeAgentCallback(list);
    assertSame(builder, ret);
    LoopAgent agent = ret.build();
    int size = getBeforeAgentCallbackSize(agent);
    assertEquals(2, size);
  }
}
