/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test functional-from-source-code using AI Type Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=name_2c4b6e6b0b
ROOST_METHOD_SIG_HASH=name_d9b24fa545

Scenario 1: Setting a valid non-null name

Details:
  TestName: setValidNonNullName
  Description: This test checks that when the name(String name) method is called with a valid, non-null string, the Builder's name field is set to the provided value and the Builder instance is returned for method chaining.
Execution:
  Arrange: Create a new instance of LoopAgent.Builder.
  Act: Call the name method with a non-null string such as "AgentAlpha".
  Assert: Verify that the Builder's name field is set to "AgentAlpha" and that the returned object is the same Builder instance.
Validation:
  This assertion ensures that the method correctly assigns the provided name and supports fluent interface usage. It is significant for ensuring that the builder pattern works as intended and that the agent can be named as required by business logic.

Scenario 2: Setting the name to null

Details:
  TestName: setNameToNull
  Description: This test checks the behavior when the name(String name) method is called with a null value, ensuring that the Builder's name field is set to null and that the method still returns the Builder instance.
Execution:
  Arrange: Create a new instance of LoopAgent.Builder.
  Act: Call the name method with null as the argument.
  Assert: Verify that the Builder's name field is null and that the returned object is the same Builder instance.
Validation:
  This assertion verifies that the method does not throw an exception or fail when provided with a null value, which is important for robustness and for handling optional or missing names in business scenarios.

Scenario 3: Overwriting the name field with multiple calls

Details:
  TestName: overwriteNameWithMultipleCalls
  Description: This test checks that calling the name(String name) method multiple times on the same Builder instance overwrites the previous value of the name field with the most recent value provided.
Execution:
  Arrange: Create a new instance of LoopAgent.Builder.
  Act: Call the name method first with "FirstName", then with "SecondName".
  Assert: Verify that the Builder's name field is set to "SecondName" after the second call.
Validation:
  This assertion ensures that the builder allows for updating the name field and that the last value provided is the one used, which is essential for flexibility in builder usage and correcting mistakes during object construction.

Scenario 4: Chaining name with other builder methods

Details:
  TestName: chainNameWithOtherBuilderMethods
  Description: This test checks that the name(String name) method can be chained with other builder methods, confirming that the fluent interface is preserved.
Execution:
  Arrange: Create a new instance of LoopAgent.Builder.
  Act: Call the name method followed by another builder method (e.g., description).
  Assert: Verify that both fields (name and description) are set correctly and that the returned object is the same Builder instance.
Validation:
  This assertion confirms the usability of the builder pattern, ensuring that method chaining works as expected and that multiple properties can be set in a single statement, which is important for developer experience and code readability.

Scenario 5: Setting an empty string as the name

Details:
  TestName: setEmptyStringAsName
  Description: This test checks the behavior when the name(String name) method is called with an empty string, ensuring that the Builder's name field is set to the empty string and the Builder instance is returned.
Execution:
  Arrange: Create a new instance of LoopAgent.Builder.
  Act: Call the name method with "" (empty string) as the argument.
  Assert: Verify that the Builder's name field is set to "" and that the returned object is the same Builder instance.
Validation:
  This assertion ensures that the method can handle empty strings without error, which may be relevant for scenarios where the name is optional or intentionally left blank.

Scenario 6: Verifying that name does not affect other fields

Details:
  TestName: nameDoesNotAffectOtherFields
  Description: This test checks that calling the name(String name) method only changes the name field and does not inadvertently modify other fields in the Builder.
Execution:
  Arrange: Create a new instance of LoopAgent.Builder and set other fields (e.g., description, subAgents) to known values.
  Act: Call the name method with a valid string.
  Assert: Verify that only the name field is changed and all other fields retain their previously set values.
Validation:
  This assertion ensures that the method is side-effect free with respect to other fields, which is crucial for predictable and safe builder usage.

Scenario 7: Using name method after setting name via constructor (if applicable)

Details:
  TestName: setNameAfterInitialValue
  Description: This test checks the behavior when the name(String name) method is called after the Builder's name field has already been set (e.g., via constructor or previous method call), ensuring the new value replaces the old one.
Execution:
  Arrange: Create a new instance of LoopAgent.Builder, set the name field to an initial value.
  Act: Call the name method with a new value.
  Assert: Verify that the name field reflects the new value.
Validation:
  This assertion confirms that the builder allows updating the name at any point before build, which is important for flexibility and correcting earlier inputs.

Scenario 8: Confirming method returns Builder for fluent chaining

Details:
  TestName: nameMethodReturnsBuilderInstance
  Description: This test checks that the name(String name) method always returns the same Builder instance, enabling fluent method chaining.
Execution:
  Arrange: Create a new instance of LoopAgent.Builder.
  Act: Call the name method and capture the returned object.
  Assert: Verify that the returned object is the same instance as the original Builder.
Validation:
  This assertion ensures that the builder pattern is implemented correctly, allowing for chained calls and improving code readability and maintainability.

Scenario 9: Setting a name with special characters

Details:
  TestName: setNameWithSpecialCharacters
  Description: This test checks that the name(String name) method correctly handles names containing special characters, such as spaces, punctuation, or unicode symbols.
Execution:
  Arrange: Create a new instance of LoopAgent.Builder.
  Act: Call the name method with a string containing special characters (e.g., "Agent_#42!@").
  Assert: Verify that the name field is set to the exact string provided.
Validation:
  This assertion ensures that the method does not restrict or alter valid string inputs, supporting a wide range of agent names as required by diverse business needs.

Scenario 10: Setting a very long string as the name

Details:
  TestName: setVeryLongStringAsName
  Description: This test checks the behavior when the name(String name) method is called with a very long string, ensuring that the Builder's name field can handle large input sizes.
Execution:
  Arrange: Create a new instance of LoopAgent.Builder.
  Act: Call the name method with a string of significant length (e.g., 10,000 characters).
  Assert: Verify that the name field is set to the long string without truncation or error.
Validation:
  This assertion ensures that the method can handle large input values, which is important for robustness and for supporting edge cases in user input or integration scenarios.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;

import com.google.common.collect.ImmutableList;
import java.util.List;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

class BuilderNameTest {

  // Helper method to access the Builder (since it's a static nested class)
  private LoopAgent.Builder newBuilder() {
    return LoopAgent.builder();
  }

  @Test
  @Tag("valid")
  public void testSetValidNonNullName() {
    LoopAgent.Builder builder = newBuilder();
    String expectedName = "AgentAlpha";
    LoopAgent.Builder returnedBuilder = builder.name(expectedName);
    assertSame(
        (LoopAgent.Builder) builder,
        (LoopAgent.Builder) returnedBuilder,
        "Returned builder should be the same instance");
    // Reflection is used here only for test verification as there is no getter for
    // name
    String actualName = getBuilderNameField(builder);
    assertEquals(
        (String) expectedName,
        (String) actualName,
        "Builder's name should be set to the provided value");
  }

  @Test
  @Tag("boundary")
  public void testSetNameToNull() {
    LoopAgent.Builder builder = newBuilder();
    LoopAgent.Builder returnedBuilder = builder.name(null);
    assertSame(
        (LoopAgent.Builder) builder,
        (LoopAgent.Builder) returnedBuilder,
        "Returned builder should be the same instance");
    String actualName = getBuilderNameField(builder);
    assertNull((String) actualName, "Builder's name should be set to null");
  }

  @Test
  @Tag("valid")
  public void testOverwriteNameWithMultipleCalls() {
    LoopAgent.Builder builder = newBuilder();
    builder.name("FirstName");
    builder.name("SecondName");
    String actualName = getBuilderNameField(builder);
    assertEquals(
        (String) "SecondName",
        (String) actualName,
        "Builder's name should be overwritten with the most recent value");
  }

  @Test
  @Tag("integration")
  public void testChainNameWithOtherBuilderMethods() {
    LoopAgent.Builder builder = newBuilder();
    String expectedName = "ChainedAgent";
    String expectedDescription = "Chained description";
    LoopAgent.Builder returnedBuilder = builder.name(expectedName).description(expectedDescription);
    assertSame(
        (LoopAgent.Builder) builder,
        (LoopAgent.Builder) returnedBuilder,
        "Returned builder should be the same instance");
    String actualName = getBuilderNameField(builder);
    String actualDescription = getBuilderDescriptionField(builder);
    assertEquals(
        (String) expectedName, (String) actualName, "Builder's name should be set correctly");
    assertEquals(
        (String) expectedDescription,
        (String) actualDescription,
        "Builder's description should be set correctly");
  }

  @Test
  @Tag("boundary")
  public void testSetEmptyStringAsName() {
    LoopAgent.Builder builder = newBuilder();
    String expectedName = "";
    LoopAgent.Builder returnedBuilder = builder.name(expectedName);
    assertSame(
        (LoopAgent.Builder) builder,
        (LoopAgent.Builder) returnedBuilder,
        "Returned builder should be the same instance");
    String actualName = getBuilderNameField(builder);
    assertEquals(
        (String) expectedName, (String) actualName, "Builder's name should be set to empty string");
  }

  @Test
  @Tag("valid")
  public void testNameDoesNotAffectOtherFields() {
    LoopAgent.Builder builder = newBuilder();
    String initialDescription = "Initial description";
    List<? extends BaseAgent> initialSubAgents = ImmutableList.of(); // TODO: Add
    // actual
    // subAgents
    // if needed
    builder.description(initialDescription);
    builder.subAgents(initialSubAgents);
    builder.name("IsolatedName");
    String actualDescription = getBuilderDescriptionField(builder);
    List<?> actualSubAgents = getBuilderSubAgentsField(builder);
    assertEquals(
        (String) initialDescription,
        (String) actualDescription,
        "Description should remain unchanged");
    assertEquals(
        (List<?>) initialSubAgents, (List<?>) actualSubAgents, "SubAgents should remain unchanged");
  }

  @Test
  @Tag("valid")
  public void testSetNameAfterInitialValue() {
    LoopAgent.Builder builder = newBuilder();
    builder.name("InitialName");
    builder.name("UpdatedName");
    String actualName = getBuilderNameField(builder);
    assertEquals(
        (String) "UpdatedName", (String) actualName, "Builder's name should reflect the new value");
  }

  @Test
  @Tag("valid")
  public void testNameMethodReturnsBuilderInstance() {
    LoopAgent.Builder builder = newBuilder();
    LoopAgent.Builder returnedBuilder = builder.name("FluentName");
    assertSame(
        (LoopAgent.Builder) builder,
        (LoopAgent.Builder) returnedBuilder,
        "Returned builder should be the same instance for fluent chaining");
  }

  @Test
  @Tag("valid")
  public void testSetNameWithSpecialCharacters() {
    LoopAgent.Builder builder = newBuilder();
    String specialName = "Agent_#42!@";
    builder.name(specialName);
    String actualName = getBuilderNameField(builder);
    assertEquals(
        (String) specialName,
        (String) actualName,
        "Builder's name should be set to the exact string with special characters");
  }

  @Test
  @Tag("boundary")
  public void testSetVeryLongStringAsName() {
    LoopAgent.Builder builder = newBuilder();
    String longName = "A".repeat(10000); // 10,000 characters
    builder.name(longName);
    String actualName = getBuilderNameField(builder);
    assertEquals(
        (String) longName, (String) actualName, "Builder's name should handle very long strings");
  }

  // Reflection helpers to access private fields for test verification
  private String getBuilderNameField(LoopAgent.Builder builder) {
    try {
      java.lang.reflect.Field nameField = builder.getClass().getDeclaredField("name");
      nameField.setAccessible(true);
      return (String) nameField.get(builder);
    } catch (Exception e) {
      fail("Unable to access 'name' field via reflection: " + e.getMessage());
      return null;
    }
  }

  private String getBuilderDescriptionField(LoopAgent.Builder builder) {
    try {
      java.lang.reflect.Field descField = builder.getClass().getDeclaredField("description");
      descField.setAccessible(true);
      return (String) descField.get(builder);
    } catch (Exception e) {
      fail("Unable to access 'description' field via reflection: " + e.getMessage());
      return null;
    }
  }

  private List<?> getBuilderSubAgentsField(LoopAgent.Builder builder) {
    try {
      java.lang.reflect.Field subAgentsField = builder.getClass().getDeclaredField("subAgents");
      subAgentsField.setAccessible(true);
      return (List<?>) subAgentsField.get(builder);
    } catch (Exception e) {
      fail("Unable to access 'subAgents' field via reflection: " + e.getMessage());
      return null;
    }
  }
}
