/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Open AI and AI Model gpt-5-nano

ROOST_METHOD_HASH=name_2c4b6e6b0b
ROOST_METHOD_SIG_HASH=name_d9b24fa545

Scenario 1: Valid non-null name is assigned and builder remains fluent

Details:
  TestName: nameSetsNameFluent
  Description: This scenario verifies that invoking name("Alpha") on the LoopAgent.Builder returns the same Builder instance (enabling fluent chaining) and that subsequent builder calls can continue to set additional fields.

Execution:
  Arrange: Create a new LoopAgent.Builder via LoopAgent.builder().
  Act: Call the builder.name("Alpha").
  Assert: The returned reference is the same object as the original builder (builder == returned), demonstrating fluent API behavior.

Validation: The assertion confirms fluent chaining; ensures no new Builder instance is created and that further configuration calls can be chained without error.

*/

// ********RoostGPT********

package com.google.adk.agents;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.assertSame;
import org.junit.jupiter.api.*;
import com.google.adk.events.Event;
import com.google.common.collect.ImmutableList;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import io.reactivex.rxjava3.core.Flowable;
import java.util.List;
import java.util.Optional;

public class BuilderNameTest {

	@Test
	@Tag("valid")
	public void testNameSetsNameFluent() {
		LoopAgent.Builder builder = LoopAgent.builder();
		LoopAgent.Builder returned = builder.name("Alpha");
		assertSame(builder, returned,
				"Builder.name(...) should return the same Builder instance to support fluent chaining");
		// Additional fluent chaining should also return the same instance
		LoopAgent.Builder chained = builder.description("Test description");
		assertSame(builder, chained, "Fluent chaining should return the same Builder instance");
		// TODO: If needed, further configure and call build() in future tests
		// LoopAgent agent = builder.build();
		// assertNotNull(agent);
	}

}