/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Open AI and AI Model gpt-5-nano

ROOST_METHOD_HASH=description_e419c9d57e
ROOST_METHOD_SIG_HASH=description_192aef2aea

Scenario 1: basicDescriptionSetsValueAndIsChainable

Details:
  TestName: basicDescriptionSetsValueAndIsChainable
  Description: The test validates that invoking description with a normal non-null string on a fresh Builder stores that value and returns the same Builder instance to allow chaining. Since there is no public getter, verification relies on identity of returned builder and the ability to continue chaining with subsequent methods.
Execution:
  Arrange: Create a new Builder via LoopAgent.builder() and keep a reference to the originalBuilder.
  Act: Call description("A sample description") and capture the returned reference as resultBuilder.
  Assert: Assert that resultBuilder == originalBuilder.
Validation: The assertion confirms the API contract that description is chainable and updates internal state as intended, ensuring fluent API usage.


*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

public class BuilderDescriptionTest {

  @Test
  @Tag("valid")
  public void basicDescriptionSetsValueAndIsChainable() {
    LoopAgent.Builder originalBuilder = LoopAgent.builder();
    LoopAgent.Builder resultBuilder = originalBuilder.description("Test Description");
    assertSame(
        originalBuilder,
        resultBuilder,
        "description() should return the same builder instance to allow chaining");
  }

  @Test
  @Tag("boundary")
  public void descriptionAllowsNullAndIsChainable() {
    LoopAgent.Builder originalBuilder = LoopAgent.builder();
    LoopAgent.Builder resultBuilder = originalBuilder.description(null);
    assertSame(
        originalBuilder,
        resultBuilder,
        "description(null) should return the same builder instance for chaining");
    // Further chain to ensure usability
    LoopAgent.Builder afterChain = resultBuilder.name("Name");
    assertNotNull(afterChain);
    assertSame(
        originalBuilder,
        afterChain,
        "Builder should remain the same instance after chaining further methods");
  }
}
