/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Open AI and AI Model gpt-5-nano

ROOST_METHOD_HASH=description_e419c9d57e
ROOST_METHOD_SIG_HASH=description_192aef2aea

Scenario 1: Verify basic description setting returns the same builder instance for method chaining
Details:
  TestName: setDescriptionBasicChaining
  Description: This scenario checks that calling description with a normal string returns the same Builder instance, enabling subsequent method chaining in a fluent style.
Execution:
  Arrange: Create a new LoopAgent.Builder instance.
  Act: Call description("A simple description") on the builder.
  Assert: Confirm that the object returned by description(...) is the same Builder instance (i.e., the reference is identical to the original).
Validation:
  The assertion demonstrates that the description method preserves fluent API semantics, allowing further builder configuration without requiring intermediate variables. This is important for ergonomic construction of LoopAgent configurations in user code.

*/

// ********RoostGPT********

package com.google.adk.agents;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.assertSame;
import com.google.adk.events.Event;
import com.google.common.collect.ImmutableList;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import io.reactivex.rxjava3.core.Flowable;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.*;

public class BuilderDescriptionTest {

	@Test
	@Tag("valid")
	public void testSetDescriptionBasicChaining() {
		// Arrange
		LoopAgent.Builder builder = LoopAgent.builder();
		// Act
		LoopAgent.Builder result = builder.description("Test Description");
		// Assert
		assertSame(builder, result,
				"description(...) should return the same Builder instance to support method chaining");
		// TODO: You can modify the description value here for additional scenarios
	}

}