/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=create_6e6963ca78
ROOST_METHOD_SIG_HASH=create_ac1179ff57

Scenario 1: Create InvocationContext with all valid non-null parameters

Details:
  TestName: createWithAllValidNonNullParameters
  Description: Verifies that the `create` method successfully builds and returns a valid
               `InvocationContext` instance when all parameters, including a non-null
               `LiveRequestQueue`, are provided with valid values.

Execution:
  Arrange:
    - Create a mock of `BaseSessionService`.
    - Create a mock of `BaseArtifactService`.
    - Create a mock of `BaseAgent`.
    - Create a mock of `Session`.
    - Create a mock of `LiveRequestQueue`.
    - Create a `RunConfig` instance using `RunConfig.builder().build()`.

  Act:
    - Call `InvocationContext.create(sessionService, artifactService, agent, session, liveRequestQueue, runConfig)`.

  Assert:
    - Assert that the returned `InvocationContext` instance is not null.
    - Assert that `context.sessionService()` equals the mocked `sessionService`.
    - Assert that `context.artifactService()` equals the mocked `artifactService`.
    - Assert that `context.agent()` equals the mocked `agent`.
    - Assert that `context.session()` equals the mocked `session`.
    - Assert that `context.liveRequestQueue()` is present (i.e., `isPresent()` returns true).
    - Assert that `context.liveRequestQueue().get()` equals the mocked `liveRequestQueue`.
    - Assert that `context.runConfig()` equals the provided `runConfig`.

Validation:
  This test confirms that the factory method correctly delegates all provided parameters
  to the builder and produces a fully populated `InvocationContext`. It is the happy-path
  baseline for the method and ensures that no parameter is silently dropped during
  construction.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class InvocationContextCreate98Test {

	@Mock
	private BaseSessionService mockSessionService;

	@Mock
	private BaseArtifactService mockArtifactService;

	@Mock
	private BaseAgent mockAgent;

	@Mock
	private Session mockSession;

	@Mock
	private LiveRequestQueue mockLiveRequestQueue;

	private RunConfig runConfig;

	@BeforeEach
	void setUp() {
		runConfig = RunConfig.builder().build();
	}

	@Test
	@Tag("valid")
	void createWithAllValidNonNullParameters() {
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, mockLiveRequestQueue, runConfig);
		assertNotNull(context);
		assertEquals(mockSessionService, context.sessionService());
		assertEquals(mockArtifactService, context.artifactService());
		assertEquals(mockAgent, context.agent());
		assertEquals(mockSession, context.session());
		assertTrue(context.liveRequestQueue().isPresent());
		assertEquals(mockLiveRequestQueue, context.liveRequestQueue().get());
		assertEquals(runConfig, context.runConfig());
	}

	@Test
	@Tag("valid")
	void createWithNullLiveRequestQueueProducesEmptyOptional() {
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, null, runConfig);
		assertNotNull(context);
		assertFalse(context.liveRequestQueue().isPresent());
		assertEquals(mockSessionService, context.sessionService());
		assertEquals(mockArtifactService, context.artifactService());
		assertEquals(mockAgent, context.agent());
		assertEquals(mockSession, context.session());
		assertEquals(runConfig, context.runConfig());
	}

	@Test
	@Tag("valid")
	void createWithNullSessionServiceAllowsBuild() {
		InvocationContext context = InvocationContext.create(null, mockArtifactService, mockAgent, mockSession,
				mockLiveRequestQueue, runConfig);
		assertNotNull(context);
		assertNull(context.sessionService());
		assertEquals(mockArtifactService, context.artifactService());
		assertEquals(mockAgent, context.agent());
		assertEquals(mockSession, context.session());
		assertTrue(context.liveRequestQueue().isPresent());
		assertEquals(runConfig, context.runConfig());
	}

	@Test
	@Tag("valid")
	void createWithNullArtifactServiceAllowsBuild() {
		InvocationContext context = InvocationContext.create(mockSessionService, null, mockAgent, mockSession,
				mockLiveRequestQueue, runConfig);
		assertNotNull(context);
		assertEquals(mockSessionService, context.sessionService());
		assertNull(context.artifactService());
		assertEquals(mockAgent, context.agent());
		assertEquals(mockSession, context.session());
		assertTrue(context.liveRequestQueue().isPresent());
		assertEquals(runConfig, context.runConfig());
	}

	@Test
	@Tag("valid")
	void createWithNullAgentAllowsBuild() {
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, null, mockSession,
				mockLiveRequestQueue, runConfig);
		assertNotNull(context);
		assertEquals(mockSessionService, context.sessionService());
		assertEquals(mockArtifactService, context.artifactService());
		assertNull(context.agent());
		assertEquals(mockSession, context.session());
		assertTrue(context.liveRequestQueue().isPresent());
		assertEquals(runConfig, context.runConfig());
	}

	@Test
	@Tag("valid")
	void createWithNullSessionAllowsBuild() {
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent, null,
				mockLiveRequestQueue, runConfig);
		assertNotNull(context);
		assertEquals(mockSessionService, context.sessionService());
		assertEquals(mockArtifactService, context.artifactService());
		assertEquals(mockAgent, context.agent());
		assertNull(context.session());
		assertTrue(context.liveRequestQueue().isPresent());
		assertEquals(runConfig, context.runConfig());
	}

	@Test
	@Tag("valid")
	void createWithNullRunConfigAllowsBuild() {
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, mockLiveRequestQueue, null);
		assertNotNull(context);
		assertEquals(mockSessionService, context.sessionService());
		assertEquals(mockArtifactService, context.artifactService());
		assertEquals(mockAgent, context.agent());
		assertEquals(mockSession, context.session());
		assertTrue(context.liveRequestQueue().isPresent());
		assertNull(context.runConfig());
	}

	@Test
	@Tag("invalid")
	void createWithAllNullParametersAllowsBuild() {
		InvocationContext context = InvocationContext.create(null, null, null, null, null, null);
		assertNotNull(context);
		assertNull(context.sessionService());
		assertNull(context.artifactService());
		assertNull(context.agent());
		assertNull(context.session());
		assertFalse(context.liveRequestQueue().isPresent());
		assertNull(context.runConfig());
	}

	@Test
	@Tag("valid")
	void createReturnsNewInstanceEachTime() {
		InvocationContext context1 = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, mockLiveRequestQueue, runConfig);
		InvocationContext context2 = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, mockLiveRequestQueue, runConfig);
		assertNotNull(context1);
		assertNotNull(context2);
		assertNotSame(context1, context2);
	}

	@Test
	@Tag("valid")
	void createDoesNotSetInvocationId() {
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, mockLiveRequestQueue, runConfig);
		assertNotNull(context);
		assertNull(context.invocationId());
	}

	@Test
	@Tag("valid")
	void createDoesNotSetUserContent() {
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, mockLiveRequestQueue, runConfig);
		assertNotNull(context);
		assertFalse(context.userContent().isPresent());
	}

	@Test
	@Tag("valid")
	void createEndInvocationDefaultsFalse() {
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, mockLiveRequestQueue, runConfig);
		assertNotNull(context);
		assertFalse(context.endInvocation());
	}

	@Test
	@Tag("valid")
	void createMemoryServiceDefaultsNull() {
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, mockLiveRequestQueue, runConfig);
		assertNotNull(context);
		assertNull(context.memoryService());
	}

	@Test
	@Tag("valid")
	void createBranchDefaultsEmpty() {
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, mockLiveRequestQueue, runConfig);
		assertNotNull(context);
		assertFalse(context.branch().isPresent());
	}

	@Test
	@Tag("valid")
	void createActiveStreamingToolsDefaultsEmpty() {
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, mockLiveRequestQueue, runConfig);
		assertNotNull(context);
		assertNotNull(context.activeStreamingTools());
		assertTrue(context.activeStreamingTools().isEmpty());
	}

	@Test
	@Tag("valid")
	void createPluginManagerDefaultsNull() {
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, mockLiveRequestQueue, runConfig);
		assertNotNull(context);
		assertNull(context.pluginManager());
	}

	@Test
	@Tag("integration")
	void createWithMaxLlmCallsRunConfigSetsCorrectly() {
		RunConfig customRunConfig = RunConfig.builder().setMaxLlmCalls(100).build();
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, mockLiveRequestQueue, customRunConfig);
		assertNotNull(context);
		assertEquals(customRunConfig, context.runConfig());
		assertEquals(100, context.runConfig().maxLlmCalls());
	}

	@Test
	@Tag("integration")
	void createContextCanBeUsedForCopyOf() {
		InvocationContext original = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, mockLiveRequestQueue, runConfig);
		InvocationContext copy = InvocationContext.copyOf(original);
		assertNotNull(copy);
		assertEquals(original.sessionService(), copy.sessionService());
		assertEquals(original.artifactService(), copy.artifactService());
		assertEquals(original.agent(), copy.agent());
		assertEquals(original.session(), copy.session());
		assertEquals(original.liveRequestQueue(), copy.liveRequestQueue());
		assertEquals(original.runConfig(), copy.runConfig());
	}

	@Test
	@Tag("valid")
	void createWithDifferentSessionServiceProducesDifferentContext() {
		BaseSessionService anotherSessionService = mock(BaseSessionService.class);
		InvocationContext context1 = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, mockLiveRequestQueue, runConfig);
		InvocationContext context2 = InvocationContext.create(anotherSessionService, mockArtifactService, mockAgent,
				mockSession, mockLiveRequestQueue, runConfig);
		assertNotEquals(context1.sessionService(), context2.sessionService());
		assertEquals(mockSessionService, context1.sessionService());
		assertEquals(anotherSessionService, context2.sessionService());
	}

	@Test
	@Tag("boundary")
	void createWithNullLiveRequestQueueHasEmptyOptionalNotNull() {
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, null, runConfig);
		assertNotNull(context);
		Optional<LiveRequestQueue> queueOptional = context.liveRequestQueue();
		assertNotNull(queueOptional);
		assertFalse(queueOptional.isPresent());
	}

	@Test
	@Tag("boundary")
	void createWithNonNullLiveRequestQueueHasPresentOptional() {
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, mockLiveRequestQueue, runConfig);
		assertNotNull(context);
		Optional<LiveRequestQueue> queueOptional = context.liveRequestQueue();
		assertNotNull(queueOptional);
		assertTrue(queueOptional.isPresent());
		assertSame(mockLiveRequestQueue, queueOptional.get());
	}

	@Test
	@Tag("valid")
	void createWithLiveRequestQueueWrapsItInOptional() {
		LiveRequestQueue liveRequestQueue = new LiveRequestQueue();
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, liveRequestQueue, runConfig);
		assertNotNull(context);
		assertTrue(context.liveRequestQueue().isPresent());
		assertSame(liveRequestQueue, context.liveRequestQueue().get());
	}

	@Test
	@Tag("integration")
	void createContextEqualsAnotherContextWithSameParameters() {
		InvocationContext context1 = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, mockLiveRequestQueue, runConfig);
		InvocationContext context2 = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, mockLiveRequestQueue, runConfig);
		assertEquals(context1, context2);
	}

	@Test
	@Tag("integration")
	void createContextHashCodeConsistentWithEquals() {
		InvocationContext context1 = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, mockLiveRequestQueue, runConfig);
		InvocationContext context2 = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, mockLiveRequestQueue, runConfig);
		assertEquals(context1.hashCode(), context2.hashCode());
	}

}
