/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=liveRequestQueue_752dd14d55
ROOST_METHOD_SIG_HASH=liveRequestQueue_66d4c7a2b5

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/june-java-unit/1782282926/source/adk-java/core/src/test/java/com/google/adk/agents/InvocationContextTest.java
Tests:
    "@Test
public void testCreateWithUserContent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).isEmpty();
    assertThat(context.invocationId()).isEqualTo(testInvocationId);
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).hasValue(userContent);
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testCreateWithLiveRequestQueue() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).liveRequestQueue(liveRequestQueue).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).hasValue(liveRequestQueue);

    assertThat(context.invocationId()).startsWith("e-");
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).isEmpty();
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testCopyOf() {
    InvocationContext originalContext = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    originalContext.activeStreamingTools().putAll(activeStreamingTools);
    InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
    assertThat(copiedContext).isNotNull();
    assertThat(copiedContext).isNotSameInstanceAs(originalContext);
    assertThat(copiedContext.sessionService()).isEqualTo(originalContext.sessionService());
    assertThat(copiedContext.artifactService()).isEqualTo(originalContext.artifactService());
    assertThat(copiedContext.memoryService()).isEqualTo(originalContext.memoryService());
    assertThat(copiedContext.liveRequestQueue()).isEqualTo(originalContext.liveRequestQueue());
    assertThat(copiedContext.invocationId()).isEqualTo(originalContext.invocationId());
    assertThat(copiedContext.agent()).isEqualTo(originalContext.agent());
    assertThat(copiedContext.session()).isEqualTo(originalContext.session());
    assertThat(copiedContext.userContent()).isEqualTo(originalContext.userContent());
    assertThat(copiedContext.runConfig()).isEqualTo(originalContext.runConfig());
    assertThat(copiedContext.endInvocation()).isEqualTo(originalContext.endInvocation());
    assertThat(copiedContext.activeStreamingTools()).isEqualTo(originalContext.activeStreamingTools());
}
"
    "@Test
public void testGetters() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).isEmpty();
    assertThat(context.invocationId()).isEqualTo(testInvocationId);
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).hasValue(userContent);
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testEquals_differentValues() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext contextWithDiffSessionService = InvocationContext.builder().sessionService(
    mock(BaseSessionService.class)).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffInvocationId = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(
    "another-id").agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffAgent = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(
    mock(BaseAgent.class)).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithUserContentEmpty = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithLiveQueuePresent = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).liveRequestQueue(liveRequestQueue).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(contextWithDiffSessionService)).isFalse();
    assertThat(context.equals(contextWithDiffInvocationId)).isFalse();
    assertThat(context.equals(contextWithDiffAgent)).isFalse();
    assertThat(context.equals(contextWithUserContentEmpty)).isFalse();
    assertThat(context.equals(contextWithLiveQueuePresent)).isFalse();
}
"Scenario 1: liveRequestQueue Returns Empty Optional When Not Set During Build

Details:
  TestName: liveRequestQueueReturnsEmptyOptionalWhenNotProvided
  Description: Verifies that when an InvocationContext is built without explicitly setting a
               liveRequestQueue, the liveRequestQueue() method returns an empty Optional.
               This is the default behavior per the Builder class default field initialization.
Execution:
  Arrange: Build an InvocationContext using the builder without calling liveRequestQueue(...),
           providing only the mandatory fields (sessionService, artifactService, agent, session,
           userContent, runConfig).
  Act: Call liveRequestQueue() on the built InvocationContext instance.
  Assert: assertThat(context.liveRequestQueue()).isEmpty();
Validation:
  The assertion confirms that the default value of liveRequestQueue in the builder is
  Optional.empty(), and the getter faithfully returns that value. This is important because
  non-live (standard) invocations must not expose a queue, ensuring the application logic
  can safely distinguish between live and non-live modes.

*/

// ********RoostGPT********

```java
package com.google.adk.agents;

import static com.google.common.truth.Truth.assertThat;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.events.Event;
import com.google.adk.flows.llmflows.ResumabilityConfig;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.models.LlmCallsLimitExceededException;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.genai.types.Content;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.junit.jupiter.api.*;
import com.google.common.collect.ImmutableSet;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import com.google.errorprone.annotations.InlineMe;
import com.google.genai.types.FunctionCall;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import javax.annotation.Nullable;

@ExtendWith(MockitoExtension.class)
public class InvocationContextLiveRequestQueueTest {

	@Mock
	private BaseSessionService mockSessionService;

	@Mock
	private BaseArtifactService mockArtifactService;

	@Mock
	private BaseMemoryService mockMemoryService;

	@Mock
	private PluginManager mockPluginManager;

	@Mock
	private BaseAgent mockAgent;

	@Mock
	private Session mockSession;

	@Mock
	private RunConfig mockRunConfig;

	@Mock
	private Content mockContent;

	@BeforeEach
    void setUp() {
        when(mockSession.appName()).thenReturn("testApp");
        when(mockSession.userId()).thenReturn("testUser");
    }

	// -------------------------------------------------------------------------
	// Scenario 1: liveRequestQueue returns empty Optional when not set during build
	// -------------------------------------------------------------------------
	@Test
	@Tag("valid")
	void liveRequestQueueReturnsEmptyOptionalWhenNotProvided() {
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.ofNullable(mockContent))
			.runConfig(mockRunConfig)
			.build();
		assertThat(context.liveRequestQueue()).isEmpty();
	}

	// -------------------------------------------------------------------------
	// Scenario 2: liveRequestQueue returns present Optional when set via builder
	// -------------------------------------------------------------------------
	@Test
	@Tag("valid")
	void liveRequestQueueReturnsPresentOptionalWhenProvided() {
		LiveRequestQueue queue = new LiveRequestQueue();
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(mockRunConfig)
			.liveRequestQueue(Optional.of(queue))
			.build();
		assertThat(context.liveRequestQueue()).isPresent();
		assertThat(context.liveRequestQueue().get()).isSameInstanceAs(queue);
	}

	// -------------------------------------------------------------------------
	// Scenario 3: liveRequestQueue returns present Optional when set directly
	// via builder overload accepting LiveRequestQueue (not Optional)
	// -------------------------------------------------------------------------
	@Test
	@Tag("valid")
	void liveRequestQueueReturnsPresentOptionalWhenProvidedDirectly() {
		LiveRequestQueue queue = new LiveRequestQueue();
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(mockRunConfig)
			.liveRequestQueue(queue)
			.build();
		assertThat(context.liveRequestQueue()).isPresent();
		assertThat(context.liveRequestQueue().get()).isSameInstanceAs(queue);
	}

	// -------------------------------------------------------------------------
	// Scenario 4: liveRequestQueue returns empty Optional when created via
	// the static create(...) factory that accepts Content
	// -------------------------------------------------------------------------
	@Test
	@Tag("valid")
	void liveRequestQueueReturnsEmptyOptionalWhenCreatedViaContentFactory() {
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService,
				"test-invocation-id", mockAgent, mockSession, mockContent, mockRunConfig);
		assertThat(context.liveRequestQueue()).isEmpty();
	}

	// -------------------------------------------------------------------------
	// Scenario 5: liveRequestQueue returns present Optional when created via
	// the static create(...) factory that accepts LiveRequestQueue
	// -------------------------------------------------------------------------
	@Test
	@Tag("valid")
	void liveRequestQueueReturnsPresentOptionalWhenCreatedViaLiveFactory() {
		LiveRequestQueue queue = new LiveRequestQueue();
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, queue, mockRunConfig);
		assertThat(context.liveRequestQueue()).isPresent();
		assertThat(context.liveRequestQueue().get()).isSameInstanceAs(queue);
	}

	// -------------------------------------------------------------------------
	// Scenario 6: liveRequestQueue returns empty Optional when null is passed
	// to the live factory (liveRequestQueue is Optional.ofNullable)
	// -------------------------------------------------------------------------
	@Test
	@Tag("boundary")
	void liveRequestQueueReturnsEmptyOptionalWhenNullPassedToLiveFactory() {
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, null, mockRunConfig);
		assertThat(context.liveRequestQueue()).isEmpty();
	}

	// -------------------------------------------------------------------------
	// Scenario 7: liveRequestQueue is preserved after copyOf
	// -------------------------------------------------------------------------
	@Test
	@Tag("valid")
	void liveRequestQueueIsPreservedAfterCopyOf() {
		LiveRequestQueue queue = new LiveRequestQueue();
		InvocationContext original = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(mockRunConfig)
			.liveRequestQueue(queue)
			.build();
		InvocationContext copy = InvocationContext.copyOf(original);
		assertThat(copy.liveRequestQueue()).isPresent();
		assertThat(copy.liveRequestQueue().get()).isSameInstanceAs(queue);
	}

	// -------------------------------------------------------------------------
	// Scenario 8: liveRequestQueue empty Optional is preserved after copyOf
	// -------------------------------------------------------------------------
	@Test
	@Tag("valid")
	void liveRequestQueueEmptyIsPreservedAfterCopyOf() {
		InvocationContext original = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(mockRunConfig)
			.build();
		InvocationContext copy = InvocationContext.copyOf(original);
		assertThat(copy.liveRequestQueue()).isEmpty();
	}

	// -------------------------------------------------------------------------
	// Scenario 9: liveRequestQueue getter returns consistent value on repeated calls
	// -------------------------------------------------------------------------
	@Test
	@Tag("valid")
	void liveRequestQueueReturnsSameValueOnRepeatedCalls() {
		LiveRequestQueue queue = new LiveRequestQueue();
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(mockRunConfig)
			.liveRequestQueue(queue)
			.build();
		Optional<LiveRequestQueue> first = context.liveRequestQueue();
		Optional<LiveRequestQueue> second = context.liveRequestQueue();
		assertThat(first).isEqualTo(second);
		assertThat(first.get()).isSameInstanceAs(second.get());
	}

	// -------------------------------------------------------------------------
	// Scenario 10: liveRequestQueue is empty Optional when set to Optional.empty()
	// explicitly in builder
	// -------------------------------------------------------------------------
	@Test
	@Tag("boundary")
	void liveRequestQueueReturnsEmptyWhenBuilderSetToEmptyOptional() {
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(mockRunConfig)
			.liveRequestQueue(Optional.empty())
			.build();
		assertThat(context.liveRequestQueue()).isEmpty();
	}

	// -------------------------------------------------------------------------
	// Scenario 11: equals() respects liveRequestQueue presence
	// -------------------------------------------------------------------------
	@Test
	@Tag("valid")
	void equalsReturnsTrueWhenBothContextsHaveSameLiveRequestQueue() {
		LiveRequestQueue queue = new LiveRequestQueue();
		InvocationContext context1 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("inv-id")
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(mockRunConfig)
			.liveRequestQueue(Optional.of(queue))
			.build();
		InvocationContext context2 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("inv-id")
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(mockRunConfig)
			.liveRequestQueue(Optional.of(queue))
			.build();
		assertThat(context1).isEqualTo(context2);
	}

	// -------------------------------------------------------------------------
	// Scenario 12: equals() distinguishes contexts with and without liveRequestQueue
	// -------------------------------------------------------------------------
	@Test
	@Tag("valid")
	void equalsReturnsFalseWhenOnlyOneContextHasLiveRequestQueue() {
		LiveRequestQueue queue = new LiveRequestQueue();
		InvocationContext contextWithQueue = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("inv-id")
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(mockRunConfig)
			.liveRequestQueue(Optional.of(queue))
			.build();
		InvocationContext contextWithoutQueue = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("inv-id")
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(mockRunConfig)
			.build();
		assertThat(contextWithQueue).isNotEqualTo(contextWithoutQueue);
	}

	// -------------------------------------------------------------------------
	// Scenario 13: hashCode is consistent between contexts with same liveRequestQueue
	// -------------------------------------------------------------------------
	@Test
	@Tag("valid")
	void hashCodeIsConsistentForContextsWithSameLiveRequestQueue() {
		LiveRequestQueue queue = new LiveRequestQueue();
		InvocationContext context1 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("inv-id")
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(mockRunConfig)
			.liveRequestQueue(Optional.of(queue))
			.build();
		InvocationContext context2 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("inv-id")
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(mockRunConfig)
			.liveRequestQueue(Optional.of(queue))
			.build();
		assertThat(context1.hashCode()).isEqualTo(context2.hashCode());
	}

	// -------------------------------------------------------------------------
	// Scenario 14: liveRequestQueue is not null (always returns Optional, never null)
	// -------------------------------------------------------------------------
	@Test
	@Tag("boundary")
	void liveRequestQueueGetterNeverReturnsNull() {
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(mockRunConfig)
			.build();
		assertThat(context.liveRequestQueue()).isNotNull();
	}

	// -------------------------------------------------------------------------
	// Scenario 15: liveRequestQueue with queue can send content
	// -------------------------------------------------------------------------
	@Test
	@Tag("integration")
	void liveRequestQueueCanSendContentWhenPresent() {
		LiveRequestQueue queue = new LiveRequestQueue();
		Content dummyContent = Content.newBuilder().build();
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(mockRunConfig)
			.liveRequestQueue(queue)
			.build();
		assertThat(context.liveRequestQueue()).isPresent();
		LiveRequestQueue retrievedQueue = context.liveRequestQueue().get();
		assertDoesNotThrow(() -> retrievedQueue.content(dummyContent));
		assertThat(retrievedQueue).isNotNull();
	}

	// -------------------------------------------------------------------------
	// Scenario 16: liveRequestQueue built via deprecated constructor reflects value
	// -------------------------------------------------------------------------
	@Test
    @Tag("valid")
    @SuppressWarnings("deprecation")
    void liveRequestQueueReturnsPresentOptionalWhenCreatedViaDeprecatedConstructor() {
        LiveRequestQueue queue = new LiveRequestQueue();
        InvocationContext context = new InvocationContext(
                mockSessionService,
                mockArtifactService,
                mockMemoryService,
                mockPluginManager,
                Optional.of(queue),
                Optional.of("branch"),
                "invocation-id",
                mockAgent,
                mockSession,
                Optional.of(mockContent),
                mockRunConfig,
                false);
        assertThat(context.liveRequestQueue()).isPresent();
        assertThat(context.liveRequestQueue().get()).isSameInstanceAs(queue);
    }

// -------------------------------------------------------------------------
// Scenario 17: liveRequestQueue empty Optional when deprecated constructor
// receives empty Optional
// -------------------------------------------------------------------------
@Test
    @Tag("boundary")
    @SuppressWarnings("deprecation")
    void liveRequestQueueReturnsEmptyOptionalWhenDeprecatedConstructorReceivesEmptyOptional() {
        InvocationContext context = new InvocationContext(
                mockSessionService,
                mockArtifactService,