/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=create_6e6963ca78
ROOST_METHOD_SIG_HASH=create_ac1179ff57

public static InvocationContext create(BaseSessionService sessionService, BaseArtifactService artifactService, BaseAgent agent, Session session, LiveRequestQueue liveRequestQueue, RunConfig runConfig)

*/

// ********RoostGPT********

```java
package com.google.adk.agents;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.events.Event;
import com.google.adk.flows.llmflows.ResumabilityConfig;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.models.LlmCallsLimitExceededException;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.genai.types.Content;
import java.util.Optional;
import java.util.UUID;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.junit.jupiter.api.*;
import com.google.common.collect.ImmutableSet;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import com.google.errorprone.annotations.InlineMe;
import com.google.genai.types.FunctionCall;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;
import javax.annotation.Nullable;

@ExtendWith(MockitoExtension.class)
class InvocationContextCreate563Test {
    @Mock
    private BaseSessionService mockSessionService;
    @Mock
    private BaseArtifactService mockArtifactService;
    @Mock
    private BaseAgent mockAgent;
    @Mock
    private Session mockSession;
    @Mock
    private LiveRequestQueue mockLiveRequestQueue;
    @Mock
    private RunConfig mockRunConfig;
    private static final String TEST_APP_NAME = "testApp";
    private static final String TEST_USER_ID = "testUser";
    @BeforeEach
    void setUp() {
        when(mockSession.appName()).thenReturn(TEST_APP_NAME);
        when(mockSession.userId()).thenReturn(TEST_USER_ID);
    }
    @Test
    @Tag("valid")
    void create_withAllValidParameters_returnsNonNullContext() {
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                mockAgent,
                mockSession,
                mockLiveRequestQueue,
                mockRunConfig
        );
        assertNotNull(context);
    }
    @Test
    @Tag("valid")
    void create_withAllValidParameters_sessionServiceIsSet() {
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                mockAgent,
                mockSession,
                mockLiveRequestQueue,
                mockRunConfig
        );
        assertSame(mockSessionService, context.sessionService());
    }
    @Test
    @Tag("valid")
    void create_withAllValidParameters_artifactServiceIsSet() {
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                mockAgent,
                mockSession,
                mockLiveRequestQueue,
                mockRunConfig
        );
        assertSame(mockArtifactService, context.artifactService());
    }
    @Test
    @Tag("valid")
    void create_withAllValidParameters_agentIsSet() {
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                mockAgent,
                mockSession,
                mockLiveRequestQueue,
                mockRunConfig
        );
        assertSame(mockAgent, context.agent());
    }
    @Test
    @Tag("valid")
    void create_withAllValidParameters_sessionIsSet() {
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                mockAgent,
                mockSession,
                mockLiveRequestQueue,
                mockRunConfig
        );
        assertSame(mockSession, context.session());
    }
    @Test
    @Tag("valid")
    void create_withAllValidParameters_liveRequestQueueIsPresent() {
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                mockAgent,
                mockSession,
                mockLiveRequestQueue,
                mockRunConfig
        );
        assertTrue(context.liveRequestQueue().isPresent());
        assertSame(mockLiveRequestQueue, context.liveRequestQueue().get());
    }
    @Test
    @Tag("valid")
    void create_withAllValidParameters_runConfigIsSet() {
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                mockAgent,
                mockSession,
                mockLiveRequestQueue,
                mockRunConfig
        );
        assertSame(mockRunConfig, context.runConfig());
    }
    @Test
    @Tag("valid")
    void create_withNullLiveRequestQueue_liveRequestQueueIsEmpty() {
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                mockAgent,
                mockSession,
                null,
                mockRunConfig
        );
        assertNotNull(context);
        assertFalse(context.liveRequestQueue().isPresent());
    }
    @Test
    @Tag("valid")
    void create_withNullLiveRequestQueue_otherFieldsAreSet() {
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                mockAgent,
                mockSession,
                null,
                mockRunConfig
        );
        assertSame(mockSessionService, context.sessionService());
        assertSame(mockArtifactService, context.artifactService());
        assertSame(mockAgent, context.agent());
        assertSame(mockSession, context.session());
        assertSame(mockRunConfig, context.runConfig());
    }
    @Test
    @Tag("valid")
    void create_withNullSessionService_returnsContextWithNullSessionService() {
        InvocationContext context = InvocationContext.create(
                null,
                mockArtifactService,
                mockAgent,
                mockSession,
                mockLiveRequestQueue,
                mockRunConfig
        );
        assertNotNull(context);
        assertNull(context.sessionService());
    }
    @Test
    @Tag("valid")
    void create_withNullArtifactService_returnsContextWithNullArtifactService() {
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                null,
                mockAgent,
                mockSession,
                mockLiveRequestQueue,
                mockRunConfig
        );
        assertNotNull(context);
        assertNull(context.artifactService());
    }
    @Test
    @Tag("valid")
    void create_withNullRunConfig_returnsContextWithNullRunConfig() {
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                mockAgent,
                mockSession,
                mockLiveRequestQueue,
                null
        );
        assertNotNull(context);
        assertNull(context.runConfig());
    }
    @Test
    @Tag("valid")
    void create_invocationIdIsNotSetByThisOverload_invocationIdIsNull() {
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                mockAgent,
                mockSession,
                mockLiveRequestQueue,
                mockRunConfig
        );
        assertNotNull(context);
        assertNull(context.invocationId());
    }
    @Test
    @Tag("valid")
    void create_userContentIsNotSetByThisOverload_userContentIsEmpty() {
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                mockAgent,
                mockSession,
                mockLiveRequestQueue,
                mockRunConfig
        );
        assertNotNull(context);
        assertFalse(context.userContent().isPresent());
    }
    @Test
    @Tag("valid")
    void create_branchIsNotSet_branchIsEmpty() {
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                mockAgent,
                mockSession,
                mockLiveRequestQueue,
                mockRunConfig
        );
        assertNotNull(context);
        assertFalse(context.branch().isPresent());
    }
    @Test
    @Tag("valid")
    void create_endInvocationDefaultIsFalse() {
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                mockAgent,
                mockSession,
                mockLiveRequestQueue,
                mockRunConfig
        );
        assertNotNull(context);
        assertFalse(context.endInvocation());
    }
    @Test
    @Tag("valid")
    void create_appNameDelegatesFromSession() {
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                mockAgent,
                mockSession,
                mockLiveRequestQueue,
                mockRunConfig
        );
        assertEquals(TEST_APP_NAME, context.appName());
    }
    @Test
    @Tag("valid")
    void create_userIdDelegatesFromSession() {
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                mockAgent,
                mockSession,
                mockLiveRequestQueue,
                mockRunConfig
        );
        assertEquals(TEST_USER_ID, context.userId());
    }
    @Test
    @Tag("valid")
    void create_activeStreamingToolsIsEmpty() {
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                mockAgent,
                mockSession,
                mockLiveRequestQueue,
                mockRunConfig
        );
        assertNotNull(context.activeStreamingTools());
        assertTrue(context.activeStreamingTools().isEmpty());
    }
    @Test
    @Tag("valid")
    void create_memoryServiceIsNullByDefault() {
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                mockAgent,
                mockSession,
                mockLiveRequestQueue,
                mockRunConfig
        );
        assertNull(context.memoryService());
    }
    @Test
    @Tag("valid")
    void create_pluginManagerIsNullByDefault() {
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                mockAgent,
                mockSession,
                mockLiveRequestQueue,
                mockRunConfig
        );
        assertNull(context.pluginManager());
    }
    @Test
    @Tag("valid")
    void create_withLiveRequestQueue_liveRequestQueueWrappedInOptional() {
        LiveRequestQueue queue = new LiveRequestQueue();
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                mockAgent,
                mockSession,
                queue,
                mockRunConfig
        );
        assertTrue(context.liveRequestQueue().isPresent());
        assertSame(queue, context.liveRequestQueue().get());
    }
    @Test
    @Tag("valid")
    void create_calledMultipleTimes_returnsDistinctInstances() {
        InvocationContext context1 = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                mockAgent,
                mockSession,
                mockLiveRequestQueue,
                mockRunConfig
        );
        InvocationContext context2 = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                mockAgent,
                mockSession,
                mockLiveRequestQueue,
                mockRunConfig
        );
        assertNotSame(context1, context2);
    }
    @Test
    @Tag("valid")
    void create_withRealRunConfig_setsRunConfigCorrectly() {
        RunConfig runConfig = RunConfig.builder().build();
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                mockAgent,
                mockSession,
                mockLiveRequestQueue,
                runConfig
        );
        assertNotNull(context);
        assertSame(runConfig, context.runConfig());
    }
    @Test
    @Tag("boundary")
    void create_withAllNullParameters_doesNotThrowException() {
        assertDoesNotThrow(() -> InvocationContext.create(
                null,
                null,
                null,
                null,
                null,
                null
        ));
    }
    @Test
    @Tag("boundary")
    void create_withAllNullExceptSession_returnsNonNullContext() {
        InvocationContext context = InvocationContext.create(
                null,
                null,
                null,
                mockSession,
                null,
                null
        );
        assertNotNull(context);
        assertSame(mockSession, context.session());
        assertFalse(context.liveRequestQueue().isPresent());
    }
    @Test
    @Tag("integration")
    void create_returnedContext_canBeUsedWithCopyOf() {
        InvocationContext original = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                mockAgent,
                mockSession,
                mockLiveRequestQueue,
                mockRunConfig
        );
        InvocationContext copy = InvocationContext.copyOf(original);
        assertNotNull(copy);
        assertSame(original.sessionService(), copy.sessionService());
        assertSame(original.artifactService(), copy.artifactService());
        assertSame(original.agent(), copy.agent());
        assertSame(original.session(), copy.session());
        assertEquals(original.liveRequestQueue(), copy.liveRequestQueue());
        assertSame(original.runConfig(), copy.runConfig());
    }
    @Test
    @Tag("integration")
    void create_returnedContext_canSetAndGetBranch() {
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                mockAgent,
                mockSession,
                mockLiveRequestQueue,
                mockRunConfig
        );
        context.branch("agentA.agentB");
        assertTrue(context.branch().isPresent());
        assertEquals("agentA.agentB", context.branch().get());
    }
    @Test
    @Tag("integration")
    void create_returnedContext_canSetEndInvocation() {
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                mockAgent,
                mockSession,
                mockLiveRequestQueue,
                mockRunConfig
        );
        context.setEndInvocation(true);
        assertTrue(context.endInvocation());
    }
    @Test
    @Tag("integration")
    void create_returnedContext_incrementLlmCallsCountThrowsWhenLimitExceeded() {
        RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(1).build();
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                mockAgent,
                mockSession,
                mockLiveRequestQueue,
                runConfig
        );
        assertDoesNotThrow(() -> context.incrementLlmCallsCount());
        assertThrows(LlmCallsLimitExceededException.class, () -> context.incrementLlmCallsCount());
    }
    @Test
    @Tag("integration")
    void create_returnedContext_equalsWithCopyOf() {
        InvocationContext original = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                mockAgent,
                mockSession,
                mockLiveRequestQueue,
                mockRunConfig
        );
        InvocationContext copy = InvocationContext.