/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=artifactService_d673c8a05b
ROOST_METHOD_SIG_HASH=artifactService_769a3f8842

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/june-java-unit/1782282457/source/adk-java/core/src/test/java/com/google/adk/agents/InvocationContextTest.java
Tests:
    "@Test
public void testCreateWithUserContent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).isEmpty();
    assertThat(context.invocationId()).isEqualTo(testInvocationId);
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).hasValue(userContent);
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testCreateWithNullUserContent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.userContent()).isEmpty();
}
"
    "@Test
public void testCreateWithLiveRequestQueue() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).liveRequestQueue(liveRequestQueue).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).hasValue(liveRequestQueue);

    assertThat(context.invocationId()).startsWith("e-");
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).isEmpty();
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testCopyOf() {
    InvocationContext originalContext = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    originalContext.activeStreamingTools().putAll(activeStreamingTools);
    InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
    assertThat(copiedContext).isNotNull();
    assertThat(copiedContext).isNotSameInstanceAs(originalContext);
    assertThat(copiedContext.sessionService()).isEqualTo(originalContext.sessionService());
    assertThat(copiedContext.artifactService()).isEqualTo(originalContext.artifactService());
    assertThat(copiedContext.memoryService()).isEqualTo(originalContext.memoryService());
    assertThat(copiedContext.liveRequestQueue()).isEqualTo(originalContext.liveRequestQueue());
    assertThat(copiedContext.invocationId()).isEqualTo(originalContext.invocationId());
    assertThat(copiedContext.agent()).isEqualTo(originalContext.agent());
    assertThat(copiedContext.session()).isEqualTo(originalContext.session());
    assertThat(copiedContext.userContent()).isEqualTo(originalContext.userContent());
    assertThat(copiedContext.runConfig()).isEqualTo(originalContext.runConfig());
    assertThat(copiedContext.endInvocation()).isEqualTo(originalContext.endInvocation());
    assertThat(copiedContext.activeStreamingTools()).isEqualTo(originalContext.activeStreamingTools());
}
"
    "@Test
public void testGetters() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).isEmpty();
    assertThat(context.invocationId()).isEqualTo(testInvocationId);
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).hasValue(userContent);
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testSetAgent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    BaseAgent newMockAgent = mock(BaseAgent.class);
    context.agent(newMockAgent);
    assertThat(context.agent()).isEqualTo(newMockAgent);
}
"
    "@Test
public void testEquals_sameObject() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(context)).isTrue();
}
"
    "@Test
public void testEquals_null() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(null)).isFalse();
}
"
    "@Test
public void testEquals_sameValues() {
    InvocationContext context1 = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext context2 = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context1.equals(context2)).isTrue();

    assertThat(context2.equals(context1)).isTrue();
}
"
    "@Test
public void testEquals_differentValues() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext contextWithDiffSessionService = InvocationContext.builder().sessionService(
    mock(BaseSessionService.class)).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffInvocationId = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(
    "another-id").agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffAgent = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(
    mock(BaseAgent.class)).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithUserContentEmpty = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithLiveQueuePresent = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).liveRequestQueue(liveRequestQueue).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(contextWithDiffSessionService)).isFalse();
    assertThat(context.equals(contextWithDiffInvocationId)).isFalse();
    assertThat(context.equals(contextWithDiffAgent)).isFalse();
    assertThat(context.equals(contextWithUserContentEmpty)).isFalse();
    assertThat(context.equals(contextWithLiveQueuePresent)).isFalse();
}
"
    "@Test
public void testHashCode_differentValues() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext contextWithDiffSessionService = InvocationContext.builder().sessionService(
    mock(BaseSessionService.class)).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffInvocationId = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(
    "another-id").agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotEqualTo(contextWithDiffSessionService);
    assertThat(context).isNotEqualTo(contextWithDiffInvocationId);
}
"
    "@Test
public void isResumable_whenResumabilityConfigIsNotResumable_isFalse() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(false)).build();
    assertThat(context.isResumable()).isFalse();
}
"
    "@Test
public void isResumable_whenResumabilityConfigIsResumable_isTrue() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(true)).build();
    assertThat(context.isResumable()).isTrue();
}
"
    "@Test
public void shouldPauseInvocation_whenNotResumable_isFalse() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(false)).build();
    Event event = Event.builder().longRunningToolIds(Optional.of(ImmutableSet.of("fc1"))).content(Content.builder().parts(ImmutableList.of(Part.builder().functionCall(FunctionCall.builder().name("tool1").id("fc1").build()).build())).build()).build();
    assertThat(context.shouldPauseInvocation(event)).isFalse();
}
"
    "@Test
public void shouldPauseInvocation_whenResumableAndNoLongRunningToolIds_isFalse() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(true)).build();
    Event event = Event.builder().content(Content.builder().parts(ImmutableList.of(Part.builder().functionCall(FunctionCall.builder().name("tool1").id("fc1").build()).build())).build()).build();
    assertThat(context.shouldPauseInvocation(event)).isFalse();
}
"
    "@Test
public void shouldPauseInvocation_whenResumableAndNoFunctionCalls_isFalse() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(true)).build();
    Event event = Event.builder().longRunningToolIds(Optional.of(ImmutableSet.of("fc1"))).build();
    assertThat(context.shouldPauseInvocation(event)).isFalse();
}
"
    "@Test
public void shouldPauseInvocation_whenResumableAndNoMatchingFunctionCallId_isFalse() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(true)).build();
    Event event = Event.builder().longRunningToolIds(Optional.of(ImmutableSet.of("fc2"))).content(Content.builder().parts(ImmutableList.of(Part.builder().functionCall(FunctionCall.builder().name("tool1").id("fc1").build()).build())).build()).build();
    assertThat(context.shouldPauseInvocation(event)).isFalse();
}
"
    "@Test
public void shouldPauseInvocation_whenResumableAndMatchingFunctionCallId_isTrue() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(true)).build();
    Event event = Event.builder().longRunningToolIds(Optional.of(ImmutableSet.of("fc1"))).content(Content.builder().parts(ImmutableList.of(Part.builder().functionCall(FunctionCall.builder().name("tool1").id("fc1").build()).build())).build()).build();
    assertThat(context.shouldPauseInvocation(event)).isTrue();
}
"Scenario 1: Verify artifactService Returns the Correctly Assigned BaseArtifactService Instance

Details:
  TestName: artifactServiceReturnsAssignedInstance
  Description: Verifies that the artifactService() method returns the exact BaseArtifactService instance that was provided during the construction of InvocationContext via the builder. This is the primary happy-path scenario for the getter method.

Execution:
  Arrange:
    - Create a mock instance of BaseArtifactService (mockArtifactService).
    - Create a mock instance of BaseSessionService (mockSessionService).
    - Create a mock instance of BaseMemoryService (mockMemoryService).
    - Create a mock instance of BaseAgent (mockAgent).
    - Create a mock instance of Session (session).
    - Build an InvocationContext using InvocationContext.builder() and provide the mockArtifactService via .artifactService(mockArtifactService), along with the other required fields (sessionService, memoryService, agent, session).
  Act:
    - Call context.artifactService() on the built InvocationContext instance.
  Assert:
    - Assert that the returned value is the same instance as mockArtifactService using assertThat(context.artifactService()).isEqualTo(mockArtifactService).

Validation:
  This assertion confirms that the artifactService() getter faithfully returns the field value set during construction. It ensures the builder correctly assigns the artifactService field and the getter does not introduce any transformation or substitution. This is fundamental to the correct functioning of any component that depends on the artifact service being available through the invocation context.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static com.google.common.truth.Truth.assertThat;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.flows.llmflows.ResumabilityConfig;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.genai.types.Content;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class InvocationContextArtifactServiceTest {

	@Mock
	private BaseArtifactService mockArtifactService;

	@Mock
	private BaseSessionService mockSessionService;

	@Mock
	private BaseMemoryService mockMemoryService;

	@Mock
	private BaseAgent mockAgent;

	@Mock
	private Session mockSession;

	@Mock
	private PluginManager mockPluginManager;

	@Mock
	private RunConfig mockRunConfig;

	@Mock
	private ResumabilityConfig mockResumabilityConfig;

	@BeforeEach
  void setUp() {
    when(mockSession.appName()).thenReturn("testApp");
    when(mockSession.userId()).thenReturn("testUser");
  }

	@Test
	@Tag("valid")
	void artifactServiceReturnsAssignedInstance() {
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("test-invocation-id")
			.runConfig(mockRunConfig)
			.build();
		BaseArtifactService result = context.artifactService();
		assertThat(result).isEqualTo(mockArtifactService);
	}

	@Test
	@Tag("valid")
	void artifactServiceReturnsSameReferenceAsProvided() {
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("test-invocation-id")
			.runConfig(mockRunConfig)
			.build();
		assertThat(context.artifactService()).isSameInstanceAs(mockArtifactService);
	}

	@Test
	@Tag("invalid")
	void artifactServiceReturnsNullWhenNotSet() {
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.memoryService(mockMemoryService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("test-invocation-id")
			.runConfig(mockRunConfig)
			.build();
		assertThat(context.artifactService()).isNull();
	}

	@Test
	@Tag("valid")
	void artifactServiceReturnedAfterCopyOfPreservesInstance() {
		InvocationContext original = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("test-invocation-id")
			.runConfig(mockRunConfig)
			.build();
		InvocationContext copy = InvocationContext.copyOf(original);
		assertThat(copy.artifactService()).isEqualTo(mockArtifactService);
		assertThat(copy.artifactService()).isSameInstanceAs(mockArtifactService);
	}

	@Test
	@Tag("valid")
	void artifactServiceIsConsistentAcrossMultipleCalls() {
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("test-invocation-id")
			.runConfig(mockRunConfig)
			.build();
		BaseArtifactService firstCall = context.artifactService();
		BaseArtifactService secondCall = context.artifactService();
		BaseArtifactService thirdCall = context.artifactService();
		assertThat(firstCall).isSameInstanceAs(secondCall);
		assertThat(secondCall).isSameInstanceAs(thirdCall);
	}

	@Test
	@Tag("valid")
	void artifactServiceReturnedViaCreateFactoryMethod() {
		Content userContent = Content.newBuilder().build();
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService,
				"test-invocation-id", mockAgent, mockSession, userContent, mockRunConfig);
		assertThat(context.artifactService()).isEqualTo(mockArtifactService);
		assertThat(context.artifactService()).isSameInstanceAs(mockArtifactService);
	}

	@Test
	@Tag("valid")
	void artifactServiceReturnedViaLiveCreateFactoryMethod() {
		LiveRequestQueue liveRequestQueue = new LiveRequestQueue();
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, liveRequestQueue, mockRunConfig);
		assertThat(context.artifactService()).isEqualTo(mockArtifactService);
		assertThat(context.artifactService()).isSameInstanceAs(mockArtifactService);
	}

	@Test
	@Tag("integration")
	void artifactServiceIsIndependentBetweenTwoContextInstances() {
		BaseArtifactService anotherMockArtifactService = mock(BaseArtifactService.class);
		InvocationContext context1 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("invocation-id-1")
			.runConfig(mockRunConfig)
			.build();
		InvocationContext context2 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(anotherMockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("invocation-id-2")
			.runConfig(mockRunConfig)
			.build();
		assertThat(context1.artifactService()).isSameInstanceAs(mockArtifactService);
		assertThat(context2.artifactService()).isSameInstanceAs(anotherMockArtifactService);
		assertThat(context1.artifactService()).isNotSameInstanceAs(context2.artifactService());
	}

	@Test
	@Tag("valid")
	void artifactServiceReturnedIsNotNullWhenSet() {
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("test-invocation-id")
			.runConfig(mockRunConfig)
			.build();
		assertThat(context.artifactService()).isNotNull();
	}

	@Test
	@Tag("integration")
	void artifactServiceRemainsUnchangedAfterMutatingOtherFields() {
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("test-invocation-id")
			.runConfig(mockRunConfig)
			.build();
		context.setEndInvocation(true);
		context.branch("new-branch");
		context.agent(mock(BaseAgent.class));
		assertThat(context.artifactService()).isSameInstanceAs(mockArtifactService);
	}

	@Test
	@Tag("valid")
	void artifactServiceEqualsAcrossEqualContextInstances() {
		InvocationContext context1 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("same-invocation-id")
			.runConfig(mockRunConfig)
			.build();
		InvocationContext context2 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("same-invocation-id")
			.runConfig(mockRunConfig)
			.build();
		assertThat(context1.artifactService()).isEqualTo(context2.artifactService());
	}

	@Test
	@Tag("boundary")
	void artifactServiceNullDoesNotThrowWhenAccessed() {
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(null)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("test-invocation-id")
			.runConfig(mockRunConfig)
			.build();
		assertDoesNotThrow(() -> context.artifactService());
		assertThat(context.artifactService()).isNull();
	}

	@Test
	@Tag("integration")
	void artifactServicePreservedAfterCopyOfWithActiveStreamingTools() {
		InvocationContext original = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.pluginManager(mockPluginManager)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("original-invocation-id")
			.runConfig(mockRunConfig)
			.build();
		InvocationContext copied = InvocationContext.copyOf(original);
		assertThat(copied.artifactService()).isSameInstanceAs(mockArtifactService);
		assertThat(copied.artifactService()).isSameInstanceAs(original.artifactService());
	}

	@Test
	@Tag("valid")
	void artifactServiceBuilderWithAllFields() {
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.pluginManager(mockPluginManager)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("full-invocation-id")
			.branch("test-branch")
			.runConfig(mockRunConfig)
			.endInvocation(false)
			.build();
		assertThat(context.artifactService()).isEqualTo(mockArtifactService);
		assertThat(context.artifactService()).isNotNull();
	}

	@Test
	@Tag("valid")
	void artifactServiceReturnedMatchesTypeBaseArtifactService() {
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("test-invocation-id")
			.runConfig(mockRunConfig)
			.build();
		BaseArtifactService result = context.artifactService();
		assertThat(result).isInstanceOf(BaseArtifactService.class);
	}

	@Test
	@Tag("boundary")
	void artifactServiceCanBeReplacedInNewBuilderFromExistingConfig() {
		BaseArtifactService secondArtifactService = mock(BaseArtifactService.class);
		InvocationContext originalContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("original-invocation-id")
			.runConfig(mockRunConfig)
			.build();
		InvocationContext updatedContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(secondArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("updated-invocation-id")
			.runConfig(mockRunConfig)
			.build();
		assertThat(originalContext.artifactService()).isSameInstanceAs(mockArtifactService);
		assertThat(updatedContext.artifactService()).isSameInstanceAs(secondArtifactService);
		assertThat(originalContext.artifactService()).isNotSameInstanceAs(updatedContext.artifactService());
	}

}
