/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=userContent_84fbf4a756
ROOST_METHOD_SIG_HASH=userContent_7428a149e0

Scenario 1: Return Present Optional When User Content Is Set With a Content Object

Details:
  TestName: userContentReturnsPresentOptionalWhenContentIsProvided
  Description: Verifies that when an `InvocationContext` is built with a non-null `Content` object
               passed via `userContent(Content)`, the `userContent()` method returns an
               `Optional` that is present and contains the exact same `Content` instance.

Execution:
  Arrange:
    - Create a mock or concrete `Content` object (e.g., `Content content = Content.newBuilder().build()`).
    - Build an `InvocationContext` using `InvocationContext.builder()` and call
      `.userContent(content)` during construction.
  Act:
    - Call `invocationContext.userContent()` on the built instance.
  Assert:
    - Assert that the returned `Optional<Content>` is not empty (`assertTrue(result.isPresent())`).
    - Assert that `result.get()` equals the `Content` object provided during construction.

Validation:
  This test confirms that the builder correctly stores a non-null `Content` object and
  that the `userContent()` accessor faithfully returns it wrapped in a present `Optional`.
  This is essential for downstream agent processing logic that depends on having access
  to the triggering user message content.

*/

// ********RoostGPT********

```java
package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.events.Event;
import com.google.adk.flows.llmflows.ResumabilityConfig;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.models.LlmCallsLimitExceededException;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.common.collect.ImmutableSet;
import com.google.genai.types.Content;
import com.google.genai.types.FunctionCall;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import javax.annotation.Nullable;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.junit.jupiter.api.*;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import com.google.errorprone.annotations.InlineMe;

@ExtendWith(MockitoExtension.class)
public class InvocationContextUserContentTest {

	@Mock
	private BaseSessionService mockSessionService;

	@Mock
	private BaseArtifactService mockArtifactService;

	@Mock
	private BaseMemoryService mockMemoryService;

	@Mock
	private PluginManager mockPluginManager;

	@Mock
	private Session mockSession;

	@Mock
	private BaseAgent mockAgent;

	@Mock
	private RunConfig mockRunConfig;

	@BeforeEach
    void setUp() {
        when(mockSession.appName()).thenReturn("testApp");
        when(mockSession.userId()).thenReturn("testUser");
    }

	@Test
	@Tag("valid")
	void userContentReturnsPresentOptionalWhenContentIsProvided() {
		// Arrange
		Content content = Content.newBuilder().setRole("user").build();
		InvocationContext invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(content)
			.runConfig(mockRunConfig)
			.build();
		// Act
		Optional<Content> result = invocationContext.userContent();
		// Assert
		assertTrue(result.isPresent(), "userContent() should return a present Optional when Content is provided");
		assertEquals(content, result.get(), "userContent() should return the exact Content object provided");
	}

	@Test
	@Tag("valid")
	void userContentReturnsPresentOptionalWhenContentIsSetViaOptional() {
		// Arrange
		Content content = Content.newBuilder().setRole("user").build();
		InvocationContext invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.of(content))
			.runConfig(mockRunConfig)
			.build();
		// Act
		Optional<Content> result = invocationContext.userContent();
		// Assert
		assertTrue(result.isPresent(),
				"userContent() should return a present Optional when Content is set via Optional.of()");
		assertEquals(content, result.get(),
				"userContent() should return the exact Content object provided via Optional");
	}

	@Test
	@Tag("valid")
	void userContentReturnsEmptyOptionalWhenNotSet() {
		// Arrange
		InvocationContext invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(mockRunConfig)
			.build();
		// Act
		Optional<Content> result = invocationContext.userContent();
		// Assert
		assertFalse(result.isPresent(), "userContent() should return an empty Optional when not set");
	}

	@Test
	@Tag("valid")
	void userContentReturnsEmptyOptionalWhenSetWithEmptyOptional() {
		// Arrange
		InvocationContext invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		// Act
		Optional<Content> result = invocationContext.userContent();
		// Assert
		assertFalse(result.isPresent(), "userContent() should return an empty Optional when set with Optional.empty()");
	}

	@Test
	@Tag("valid")
	void userContentReturnsEmptyOptionalWhenNullContentPassedViaCreate() {
		// Arrange
		InvocationContext invocationContext = InvocationContext.create(mockSessionService, mockArtifactService,
				"test-invocation-id", mockAgent, mockSession, null, mockRunConfig);
		// Act
		Optional<Content> result = invocationContext.userContent();
		// Assert
		assertFalse(result.isPresent(),
				"userContent() should return empty Optional when null Content is passed via create()");
	}

	@Test
	@Tag("valid")
	void userContentReturnsPresentOptionalWhenContentPassedViaCreate() {
		// Arrange
		Content content = Content.newBuilder().setRole("user").build();
		InvocationContext invocationContext = InvocationContext.create(mockSessionService, mockArtifactService,
				"test-invocation-id", mockAgent, mockSession, content, mockRunConfig);
		// Act
		Optional<Content> result = invocationContext.userContent();
		// Assert
		assertTrue(result.isPresent(),
				"userContent() should return a present Optional when Content is passed via create()");
		assertEquals(content, result.get(), "userContent() should return the exact Content passed via create()");
	}

	@Test
	@Tag("valid")
	void userContentIsPreservedAfterCopyOf() {
		// Arrange
		Content content = Content.newBuilder().setRole("user").build();
		InvocationContext original = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(content)
			.runConfig(mockRunConfig)
			.build();
		// Act
		InvocationContext copy = InvocationContext.copyOf(original);
		Optional<Content> result = copy.userContent();
		// Assert
		assertTrue(result.isPresent(), "userContent() should be present after copyOf()");
		assertEquals(content, result.get(), "userContent() should preserve the same Content after copyOf()");
	}

	@Test
	@Tag("valid")
	void userContentEmptyIsPreservedAfterCopyOf() {
		// Arrange
		InvocationContext original = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		// Act
		InvocationContext copy = InvocationContext.copyOf(original);
		Optional<Content> result = copy.userContent();
		// Assert
		assertFalse(result.isPresent(),
				"userContent() should remain empty after copyOf() when original had empty content");
	}

	@Test
	@Tag("valid")
	void userContentReturnsSameReferenceAcrossMultipleCalls() {
		// Arrange
		Content content = Content.newBuilder().setRole("user").build();
		InvocationContext invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(content)
			.runConfig(mockRunConfig)
			.build();
		// Act
		Optional<Content> firstCall = invocationContext.userContent();
		Optional<Content> secondCall = invocationContext.userContent();
		// Assert
		assertEquals(firstCall, secondCall, "userContent() should return equal values across multiple calls");
		assertTrue(firstCall.isPresent(), "userContent() should be present on first call");
		assertTrue(secondCall.isPresent(), "userContent() should be present on second call");
		assertSame(firstCall.get(), secondCall.get(),
				"userContent() should return the same Content instance on repeated calls");
	}

	@Test
	@Tag("valid")
	void userContentReturnsCorrectContentWithRole() {
		// Arrange
		Content content = Content.newBuilder().setRole("model").build();
		InvocationContext invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(content)
			.runConfig(mockRunConfig)
			.build();
		// Act
		Optional<Content> result = invocationContext.userContent();
		// Assert
		assertTrue(result.isPresent(), "userContent() should be present");
		assertEquals("model", result.get().role().orElse(""), "userContent() should preserve the role of the Content");
	}

	@Test
	@Tag("boundary")
	void userContentNotNullWhenBuiltWithoutExplicitUserContent() {
		// Arrange
		InvocationContext invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(mockRunConfig)
			.build();
		// Act
		Optional<Content> result = invocationContext.userContent();
		// Assert
		assertNotNull(result, "userContent() should never return null, only Optional.empty()");
	}

	@Test
	@Tag("boundary")
	void userContentNotNullWhenExplicitlySetToEmptyOptional() {
		// Arrange
		InvocationContext invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.<Content>empty())
			.runConfig(mockRunConfig)
			.build();
		// Act
		Optional<Content> result = invocationContext.userContent();
		// Assert
		assertNotNull(result, "userContent() should never return null even when set to Optional.empty()");
		assertFalse(result.isPresent(), "userContent() should return empty Optional when set to Optional.empty()");
	}

	@Test
	@Tag("integration")
	void userContentIsAccessibleAfterFullBuilderConstruction() {
		// Arrange
		Content content = Content.newBuilder().setRole("user").build();
		String invocationId = InvocationContext.newInvocationContextId();
		InvocationContext invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.pluginManager(mockPluginManager)
			.invocationId(invocationId)
			.agent(mockAgent)
			.session(mockSession)
			.userContent(content)
			.runConfig(mockRunConfig)
			.build();
		// Act
		Optional<Content> result = invocationContext.userContent();
		// Assert
		assertNotNull(result, "userContent() should not be null");
		assertTrue(result.isPresent(), "userContent() should be present after full builder construction");
		assertEquals(content, result.get(), "userContent() should match the Content provided during construction");
	}

	@Test
	@Tag("integration")
	void userContentIsIndependentOfOtherContextProperties() {
		// Arrange
		Content contentForFirst = Content.newBuilder().setRole("user").build();
		Content contentForSecond = Content.newBuilder().setRole("model").build();
		InvocationContext firstContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("invocation-1")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(contentForFirst)
			.runConfig(mockRunConfig)
			.build();
		InvocationContext secondContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("invocation-2")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(contentForSecond)
			.runConfig(mockRunConfig)
			.build();
		// Act
		Optional<Content> firstResult = firstContext.userContent();
		Optional<Content> secondResult = secondContext.userContent();
		// Assert
		assertTrue(firstResult.isPresent(), "First context userContent() should be present");
		assertTrue(secondResult.isPresent(), "Second context userContent() should be present");
		assertEquals(contentForFirst, firstResult.get(), "First context userContent() should match its own Content");
		assertEquals(contentForSecond, secondResult.get(), "Second context userContent() should match its own Content");
		assertNotEquals(firstResult.get(), secondResult.get(),
				"Two different contexts should have different userContent");
	}

	@Test
    @Tag("valid")
    void userContentReturnsOptionalTypeCorrectly() {
        // Arrange
        Content content = Content.newBuilder().setRole("user").build();
        InvocationContext invocationContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("test-invocation-id")
                .agent(mockAgent)
                .session(mockSession)
                .userContent(content)
                .runConfig(mockRunConfig)
                .build();
        // Act
        Optional<Content> result = invocationContext.userContent();
        // Assert
        assertNotNull(result, "userContent() must not return null");
        assertInstanceOf(Optional.class, result, "userContent() must return an Optional type");
    }

@Test
    @Tag("valid")
    void userContentIsNotAffectedByChangingOtherFields() {
        // Arrange
        Content content = Content.newBuilder().setRole("user").build();
        InvocationContext invocationContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("test-invocation-id")
                .agent(mockAgent)
                .session(mockSession)
                .userContent(content)
                .runConfig(mockRunConfig)
                .build();
        // Modify other properties on the context
        invocationContext.branch("test-branch");
        invocationContext.setEndInvocation(true);