/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=liveRequestQueue_752dd14d55
ROOST_METHOD_SIG_HASH=liveRequestQueue_66d4c7a2b5

Scenario 1: Return Present LiveRequestQueue When It Is Explicitly Set via Builder

Details:
  TestName: liveRequestQueueReturnsPresentOptionalWhenSetViaBuilder
  Description: Verifies that when a LiveRequestQueue instance is provided through the builder's
               liveRequestQueue(LiveRequestQueue) method, the liveRequestQueue() accessor returns
               an Optional containing that queue instance.

Execution:
  Arrange:
    - Create a mock or concrete LiveRequestQueue instance.
    - Build an InvocationContext using InvocationContext.builder() with the liveRequestQueue set
      to the created LiveRequestQueue instance.
  Act:
    - Call liveRequestQueue() on the constructed InvocationContext.
  Assert:
    - Assert that the returned Optional is present (isPresent() returns true).
    - Assert that the value inside the Optional is the same instance as the one provided to the builder.

Validation:
  This test confirms that when a live request queue is supplied during construction via the
  non-deprecated builder method, the accessor correctly wraps it in a non-empty Optional and
  returns the exact reference. This is critical for live/streaming agent invocations that rely
  on the queue to process incoming messages.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.genai.types.Content;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class InvocationContextLiveRequestQueueTest {

	@Mock
	private BaseSessionService mockSessionService;

	@Mock
	private BaseArtifactService mockArtifactService;

	@Mock
	private BaseMemoryService mockMemoryService;

	@Mock
	private PluginManager mockPluginManager;

	@Mock
	private BaseAgent mockAgent;

	private Session session;

	private RunConfig runConfig;

	@BeforeEach
	void setUp() {
		session = Session.builder("test-session-id").appName("test-app").userId("test-user").build();
		runConfig = RunConfig.builder().build();
	}

	@Test
	@Tag("valid")
	void liveRequestQueueReturnsPresentOptionalWhenSetViaBuilder() {
		// Arrange
		LiveRequestQueue liveRequestQueue = new LiveRequestQueue();
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(session)
			.liveRequestQueue(liveRequestQueue)
			.runConfig(runConfig)
			.build();
		// Act
		Optional<LiveRequestQueue> result = context.liveRequestQueue();
		// Assert
		assertTrue(result.isPresent(), "LiveRequestQueue Optional should be present");
		assertSame(liveRequestQueue, result.get(),
				"The LiveRequestQueue instance should be the same as the one provided to the builder");
	}

	@Test
	@Tag("valid")
	void liveRequestQueueReturnsEmptyOptionalWhenNotSet() {
		// Arrange
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(session)
			.runConfig(runConfig)
			.build();
		// Act
		Optional<LiveRequestQueue> result = context.liveRequestQueue();
		// Assert
		assertFalse(result.isPresent(), "LiveRequestQueue Optional should be empty when not set");
	}

	@Test
	@Tag("valid")
	void liveRequestQueueReturnsEmptyOptionalWhenExplicitlySetToEmpty() {
		// Arrange
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(session)
			.liveRequestQueue(Optional.empty())
			.runConfig(runConfig)
			.build();
		// Act
		Optional<LiveRequestQueue> result = context.liveRequestQueue();
		// Assert
		assertFalse(result.isPresent(),
				"LiveRequestQueue Optional should be empty when explicitly set to Optional.empty()");
	}

	@Test
	@Tag("valid")
	void liveRequestQueueReturnsPresentOptionalWhenSetViaOptionalBuilder() {
		// Arrange
		LiveRequestQueue liveRequestQueue = new LiveRequestQueue();
		Optional<LiveRequestQueue> optionalQueue = Optional.of(liveRequestQueue);
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(session)
			.liveRequestQueue(optionalQueue)
			.runConfig(runConfig)
			.build();
		// Act
		Optional<LiveRequestQueue> result = context.liveRequestQueue();
		// Assert
		assertTrue(result.isPresent(),
				"LiveRequestQueue Optional should be present when set via Optional builder method");
		assertSame(liveRequestQueue, result.get(), "The returned LiveRequestQueue should be the same instance");
	}

	@Test
	@Tag("valid")
	void liveRequestQueueReturnsConsistentResultOnMultipleCalls() {
		// Arrange
		LiveRequestQueue liveRequestQueue = new LiveRequestQueue();
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(session)
			.liveRequestQueue(liveRequestQueue)
			.runConfig(runConfig)
			.build();
		// Act
		Optional<LiveRequestQueue> firstResult = context.liveRequestQueue();
		Optional<LiveRequestQueue> secondResult = context.liveRequestQueue();
		// Assert
		assertTrue(firstResult.isPresent(), "First call should return present Optional");
		assertTrue(secondResult.isPresent(), "Second call should return present Optional");
		assertSame(firstResult.get(), secondResult.get(),
				"Multiple calls should return the same LiveRequestQueue instance");
	}

	@Test
	@Tag("valid")
	void liveRequestQueuePreservedInCopyOf() {
		// Arrange
		LiveRequestQueue liveRequestQueue = new LiveRequestQueue();
		InvocationContext original = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(session)
			.liveRequestQueue(liveRequestQueue)
			.runConfig(runConfig)
			.build();
		// Act
		InvocationContext copy = InvocationContext.copyOf(original);
		// Assert
		assertTrue(copy.liveRequestQueue().isPresent(), "Copied context should have present LiveRequestQueue");
		assertSame(original.liveRequestQueue().get(), copy.liveRequestQueue().get(),
				"Copied context should have the same LiveRequestQueue instance");
	}

	@Test
	@Tag("valid")
	void liveRequestQueueAbsentInCopyOfWhenOriginalHasNone() {
		// Arrange
		InvocationContext original = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(session)
			.runConfig(runConfig)
			.build();
		// Act
		InvocationContext copy = InvocationContext.copyOf(original);
		// Assert
		assertFalse(copy.liveRequestQueue().isPresent(),
				"Copied context should have absent LiveRequestQueue when original has none");
	}

	@Test
	@Tag("valid")
	void liveRequestQueueReturnsPresentWhenUsingStaticCreateWithLiveRequestQueue() {
		// Arrange
		LiveRequestQueue liveRequestQueue = new LiveRequestQueue();
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				session, liveRequestQueue, runConfig);
		// Act
		Optional<LiveRequestQueue> result = context.liveRequestQueue();
		// Assert
		assertTrue(result.isPresent(),
				"LiveRequestQueue should be present when using static create with LiveRequestQueue");
		assertSame(liveRequestQueue, result.get(), "The LiveRequestQueue should be the same instance");
	}

	@Test
	@Tag("valid")
	void liveRequestQueueIsAbsentWhenCreatedViaStaticCreateWithoutLiveRequestQueue() {
		// Arrange
		Content userContent = Content.fromParts();
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService,
				"test-invocation-id", mockAgent, session, userContent, runConfig);
		// Act
		Optional<LiveRequestQueue> result = context.liveRequestQueue();
		// Assert
		assertFalse(result.isPresent(), "LiveRequestQueue should be absent when created without a live request queue");
	}

	@Test
	@Tag("boundary")
	void liveRequestQueueReturnsPresentWhenStaticCreateReceivesNullLiveRequestQueue() {
		// Arrange - null is passed, should result in empty Optional
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				session, (LiveRequestQueue) null, runConfig);
		// Act
		Optional<LiveRequestQueue> result = context.liveRequestQueue();
		// Assert
		assertNotNull(result, "Result should not be null itself, should be an Optional");
		assertFalse(result.isPresent(),
				"LiveRequestQueue Optional should be empty when null is passed to static create");
	}

	@Test
	@Tag("valid")
	void liveRequestQueueGetReturnsCorrectInstance() {
		// Arrange
		LiveRequestQueue liveRequestQueue = new LiveRequestQueue();
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(session)
			.liveRequestQueue(liveRequestQueue)
			.runConfig(runConfig)
			.build();
		// Act
		Optional<LiveRequestQueue> result = context.liveRequestQueue();
		// Assert
		assertTrue(result.isPresent());
		LiveRequestQueue retrieved = result.get();
		assertNotNull(retrieved, "Retrieved LiveRequestQueue should not be null");
		assertEquals(liveRequestQueue, retrieved, "Retrieved LiveRequestQueue should equal the one provided");
	}

	@Test
	@Tag("valid")
	void liveRequestQueueIsIndependentFromOtherContextFields() {
		// Arrange
		LiveRequestQueue liveRequestQueue = new LiveRequestQueue();
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.pluginManager(mockPluginManager)
			.agent(mockAgent)
			.session(session)
			.invocationId("test-id")
			.liveRequestQueue(liveRequestQueue)
			.runConfig(runConfig)
			.build();
		// Act
		Optional<LiveRequestQueue> result = context.liveRequestQueue();
		// Assert
		assertTrue(result.isPresent(), "LiveRequestQueue should be present");
		assertSame(liveRequestQueue, result.get(), "Should return the exact instance");
		// Verify other fields are not affected
		assertNotNull(context.sessionService(), "Session service should still be set");
		assertNotNull(context.session(), "Session should still be set");
		assertEquals("test-id", context.invocationId(), "Invocation ID should still be set");
	}

	@Test
	@Tag("integration")
	void liveRequestQueueCanReceiveContentAfterRetrieval() {
		// Arrange
		LiveRequestQueue liveRequestQueue = new LiveRequestQueue();
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(session)
			.liveRequestQueue(liveRequestQueue)
			.runConfig(runConfig)
			.build();
		// Act
		Optional<LiveRequestQueue> result = context.liveRequestQueue();
		// Assert
		assertTrue(result.isPresent());
		LiveRequestQueue retrievedQueue = result.get();
		// Verify that we can subscribe to the queue (integration-style check)
		assertNotNull(retrievedQueue.get(), "The Flowable from queue should not be null");
	}

	@Test
	@Tag("valid")
	void liveRequestQueueNotPresentWhenOnlyBranchAndInvocationIdAreSet() {
		// Arrange
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(session)
			.branch("agent.subAgent")
			.invocationId("some-invocation-id")
			.runConfig(runConfig)
			.build();
		// Act
		Optional<LiveRequestQueue> result = context.liveRequestQueue();
		// Assert
		assertFalse(result.isPresent(),
				"LiveRequestQueue should not be present when only branch and invocationId are set");
	}

	@Test
	@Tag("boundary")
	void liveRequestQueueResultIsImmutableAfterContextCreation() {
		// Arrange
		LiveRequestQueue liveRequestQueue = new LiveRequestQueue();
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(session)
			.liveRequestQueue(liveRequestQueue)
			.runConfig(runConfig)
			.build();
		// Act - get the queue multiple times and verify it's the same wrapped optional
		// behavior
		Optional<LiveRequestQueue> result1 = context.liveRequestQueue();
		Optional<LiveRequestQueue> result2 = context.liveRequestQueue();
		// Assert
		assertEquals(result1.isPresent(), result2.isPresent(), "Both calls should return Optional with same presence");
		assertSame(result1.get(), result2.get(), "Both calls should return the same LiveRequestQueue reference");
	}

	@Test
	@Tag("valid")
	void twoContextsWithDifferentLiveRequestQueuesReturnDifferentInstances() {
		// Arrange
		LiveRequestQueue queue1 = new LiveRequestQueue();
		LiveRequestQueue queue2 = new LiveRequestQueue();
		InvocationContext context1 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(session)
			.liveRequestQueue(queue1)
			.runConfig(runConfig)
			.build();
		InvocationContext context2 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(session)
			.liveRequestQueue(queue2)
			.runConfig(runConfig)
			.build();
		// Act
		Optional<LiveRequestQueue> result1 = context1.liveRequestQueue();
		Optional<LiveRequestQueue> result2 = context2.liveRequestQueue();
		// Assert
		assertTrue(result1.isPresent(), "First context's queue should be present");
		assertTrue(result2.isPresent(), "Second context's queue should be present");
		assertNotSame(result1.get(), result2.get(),
				"Two different contexts should return different LiveRequestQueue instances");
	}

}
