/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=runConfig_09ff6f346f
ROOST_METHOD_SIG_HASH=runConfig_dbfa69ec19

Scenario 1: Verify that runConfig() returns the exact RunConfig instance set via the builder

Details:
  TestName: runConfigReturnsExactInstanceSetViaBuilder
  Description: Verifies that when an InvocationContext is constructed using the Builder with a specific
               RunConfig instance, the runConfig() method returns the exact same instance that was provided.

Execution:
  Arrange: Create a RunConfig instance using RunConfig.builder().build(). Then build an InvocationContext
           using InvocationContext.builder() with the created RunConfig set via .runConfig(runConfig).
  Act: Call runConfig() on the constructed InvocationContext.
  Assert: Use assertSame() or assertEquals() to confirm the returned RunConfig is identical to the one
          provided during construction.

Validation:
  The assertion confirms that the runConfig field is stored and returned without any transformation or
  wrapping. This is critical to ensure that the configuration controlling agent run behavior (e.g., LLM
  call limits) is faithfully preserved and accessible throughout the invocation lifecycle.

*/

// ********RoostGPT********

```java
package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.events.Event;
import com.google.adk.flows.llmflows.ResumabilityConfig;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.models.LlmCallsLimitExceededException;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.common.collect.ImmutableSet;
import com.google.genai.types.Content;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import javax.annotation.Nullable;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.junit.jupiter.api.*;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import com.google.errorprone.annotations.InlineMe;
import com.google.genai.types.FunctionCall;

@ExtendWith(MockitoExtension.class)
public class InvocationContextRunConfigTest {

	@Mock
	private BaseSessionService mockSessionService;

	@Mock
	private BaseArtifactService mockArtifactService;

	@Mock
	private BaseMemoryService mockMemoryService;

	@Mock
	private PluginManager mockPluginManager;

	@Mock
	private BaseAgent mockAgent;

	private Session mockSession;

	private RunConfig defaultRunConfig;

	private static final String TEST_INVOCATION_ID = "test-invocation-id";

	private static final String TEST_SESSION_ID = "test-session-id";

	private static final String TEST_APP_NAME = "test-app";

	private static final String TEST_USER_ID = "test-user";

	@BeforeEach
	void setUp() {
		mockSession = Session.builder(TEST_SESSION_ID).appName(TEST_APP_NAME).userId(TEST_USER_ID).build();
		defaultRunConfig = RunConfig.builder().build();
	}

	@Test
	@Tag("valid")
	void runConfigReturnsExactInstanceSetViaBuilder() {
		// Arrange
		RunConfig runConfig = RunConfig.builder().build();
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId(TEST_INVOCATION_ID)
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(runConfig)
			.build();
		// Act
		RunConfig result = context.runConfig();
		// Assert
		assertSame(runConfig, result);
	}

	@Test
	@Tag("valid")
	void runConfigReturnsNullWhenNotSet() {
		// Arrange
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId(TEST_INVOCATION_ID)
			.agent(mockAgent)
			.session(mockSession)
			.build();
		// Act
		RunConfig result = context.runConfig();
		// Assert
		assertNull(result);
	}

	@Test
	@Tag("valid")
	void runConfigReturnsCorrectConfigWithMaxLlmCallsSet() {
		// Arrange
		int maxCalls = 100;
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(maxCalls).build();
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId(TEST_INVOCATION_ID)
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(runConfig)
			.build();
		// Act
		RunConfig result = context.runConfig();
		// Assert
		assertNotNull(result);
		assertSame(runConfig, result);
		assertEquals(maxCalls, result.maxLlmCalls());
	}

	@Test
	@Tag("valid")
	void runConfigReturnsSameInstanceAfterCopyOf() {
		// Arrange
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(200).build();
		InvocationContext original = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId(TEST_INVOCATION_ID)
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(runConfig)
			.build();
		// Act
		InvocationContext copied = InvocationContext.copyOf(original);
		RunConfig result = copied.runConfig();
		// Assert
		assertNotNull(result);
		assertSame(runConfig, result);
		assertEquals(original.runConfig(), copied.runConfig());
	}

	@Test
	@Tag("valid")
	void runConfigReturnsCorrectConfigCreatedViaStaticCreateMethod() {
		// Arrange
		RunConfig runConfig = RunConfig.builder().build();
		Content userContent = Content.newBuilder().build();
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService,
				TEST_INVOCATION_ID, mockAgent, mockSession, userContent, runConfig);
		// Act
		RunConfig result = context.runConfig();
		// Assert
		assertNotNull(result);
		assertSame(runConfig, result);
	}

	@Test
	@Tag("valid")
	void runConfigReturnsDefaultRunConfigWithDefaultValues() {
		// Arrange
		RunConfig runConfig = RunConfig.builder().build();
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId(TEST_INVOCATION_ID)
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(runConfig)
			.build();
		// Act
		RunConfig result = context.runConfig();
		// Assert
		assertNotNull(result);
		assertEquals(500, result.maxLlmCalls());
		assertFalse(result.saveInputBlobsAsArtifacts());
	}

	@Test
	@Tag("valid")
	void runConfigReturnsSameReferenceOnMultipleCalls() {
		// Arrange
		RunConfig runConfig = RunConfig.builder().build();
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId(TEST_INVOCATION_ID)
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(runConfig)
			.build();
		// Act
		RunConfig firstCall = context.runConfig();
		RunConfig secondCall = context.runConfig();
		// Assert
		assertSame(firstCall, secondCall);
	}

	@Test
	@Tag("valid")
	void runConfigReturnsCorrectConfigWithMemoryAndPluginManager() {
		// Arrange
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(50).build();
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.pluginManager(mockPluginManager)
			.invocationId(TEST_INVOCATION_ID)
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(runConfig)
			.build();
		// Act
		RunConfig result = context.runConfig();
		// Assert
		assertNotNull(result);
		assertSame(runConfig, result);
		assertEquals(50, result.maxLlmCalls());
	}

	@Test
	@Tag("boundary")
	void runConfigReturnsConfigWithMaxLlmCallsSetToOne() {
		// Arrange
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(1).build();
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId(TEST_INVOCATION_ID)
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(runConfig)
			.build();
		// Act
		RunConfig result = context.runConfig();
		// Assert
		assertNotNull(result);
		assertSame(runConfig, result);
		assertEquals(1, result.maxLlmCalls());
	}

	@Test
	@Tag("boundary")
	void runConfigReturnsConfigWithMaxLlmCallsSetToZero() {
		// Arrange
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(0).build();
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId(TEST_INVOCATION_ID)
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(runConfig)
			.build();
		// Act
		RunConfig result = context.runConfig();
		// Assert
		assertNotNull(result);
		assertSame(runConfig, result);
		assertEquals(0, result.maxLlmCalls());
	}

	@Test
	@Tag("boundary")
	void runConfigReturnsConfigWithMaxLlmCallsSetToIntegerMaxValue() {
		// Arrange
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(Integer.MAX_VALUE).build();
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId(TEST_INVOCATION_ID)
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(runConfig)
			.build();
		// Act
		RunConfig result = context.runConfig();
		// Assert
		assertNotNull(result);
		assertSame(runConfig, result);
		assertEquals(Integer.MAX_VALUE, result.maxLlmCalls());
	}

	@Test
	@Tag("valid")
	void runConfigPreservedAfterBranchUpdate() {
		// Arrange
		RunConfig runConfig = RunConfig.builder().build();
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId(TEST_INVOCATION_ID)
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(runConfig)
			.build();
		// Act
		context.branch("agent1.agent2");
		RunConfig result = context.runConfig();
		// Assert
		assertNotNull(result);
		assertSame(runConfig, result);
	}

	@Test
	@Tag("valid")
	void runConfigPreservedAfterEndInvocationUpdate() {
		// Arrange
		RunConfig runConfig = RunConfig.builder().build();
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId(TEST_INVOCATION_ID)
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(runConfig)
			.build();
		// Act
		context.setEndInvocation(true);
		RunConfig result = context.runConfig();
		// Assert
		assertNotNull(result);
		assertSame(runConfig, result);
	}

	@Test
	@Tag("integration")
	void runConfigIsConsistentAcrossOriginalAndCopiedContext() {
		// Arrange
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(300).build();
		InvocationContext original = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.pluginManager(mockPluginManager)
			.invocationId(TEST_INVOCATION_ID)
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(runConfig)
			.build();
		InvocationContext copied = InvocationContext.copyOf(original);
		// Act
		RunConfig originalRunConfig = original.runConfig();
		RunConfig copiedRunConfig = copied.runConfig();
		// Assert
		assertNotNull(originalRunConfig);
		assertNotNull(copiedRunConfig);
		assertSame(originalRunConfig, copiedRunConfig);
		assertEquals(300, originalRunConfig.maxLlmCalls());
		assertEquals(300, copiedRunConfig.maxLlmCalls());
	}

	@Test
	@Tag("integration")
	void runConfigIsUsedCorrectlyByIncrementLlmCallsCount() throws LlmCallsLimitExceededException {
		// Arrange
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(2).build();
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId(TEST_INVOCATION_ID)
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(runConfig)
			.build();
		// Act & Assert
		assertSame(runConfig, context.runConfig());
		assertDoesNotThrow(() -> context.incrementLlmCallsCount());
		assertDoesNotThrow(() -> context.incrementLlmCallsCount());
		assertThrows(LlmCallsLimitExceededException.class, () -> context.incrementLlmCallsCount());
	}

	@Test
    @Tag("valid")
    void runConfigNotAffectedByAgentChange() {
        // Arrange
        RunConfig runConfig = RunConfig.builder().build();
        InvocationContext context = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId(TEST_INVOCATION_ID)
                .agent(mockAgent)
                .session(mockSession)
                .runConfig(runConfig)
                .build();
        // Act
        BaseAgent anotherAgent = mock(BaseAgent.class);
        context.agent(anotherAgent);
        RunConfig result = context.runConfig();
        // Assert
        assertNotNull(result);
        assertSame(runConfig, result);
    }

@Test
    @Tag("valid")
    void runConfigEqualityCheckWithSameValues() {
        // Arrange
        RunConfig runConfig1 = RunConfig.builder().setMaxLlmCalls(100).build();
        RunConfig runConfig2 = RunConfig.builder().setMaxLlmCalls(100).build();
        InvocationContext context1 = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId(TEST_INVOCATION_ID)
                .agent(mockAgent)
                .session(mockSession)
                .runConfig(runConfig1)
                .build();
        InvocationContext context2 = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId(TEST_INVOCATION_ID)
                .agent(mockAgent)
                .session(mockSession)
                .runConfig(runConfig2)
                .build();
        // Act
        RunConfig result1