/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=pluginManager_009a0b1a05
ROOST_METHOD_SIG_HASH=pluginManager_3452d016c7

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/june-java-unit/1782282926/source/adk-java/core/src/test/java/com/google/adk/agents/InvocationContextTest.java
Tests:
    "@Test
public void testCreateWithUserContent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).isEmpty();
    assertThat(context.invocationId()).isEqualTo(testInvocationId);
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).hasValue(userContent);
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testCreateWithNullUserContent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.userContent()).isEmpty();
}
"
    "@Test
public void testCreateWithLiveRequestQueue() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).liveRequestQueue(liveRequestQueue).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).hasValue(liveRequestQueue);

    assertThat(context.invocationId()).startsWith("e-");
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).isEmpty();
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testCopyOf() {
    InvocationContext originalContext = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    originalContext.activeStreamingTools().putAll(activeStreamingTools);
    InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
    assertThat(copiedContext).isNotNull();
    assertThat(copiedContext).isNotSameInstanceAs(originalContext);
    assertThat(copiedContext.sessionService()).isEqualTo(originalContext.sessionService());
    assertThat(copiedContext.artifactService()).isEqualTo(originalContext.artifactService());
    assertThat(copiedContext.memoryService()).isEqualTo(originalContext.memoryService());
    assertThat(copiedContext.liveRequestQueue()).isEqualTo(originalContext.liveRequestQueue());
    assertThat(copiedContext.invocationId()).isEqualTo(originalContext.invocationId());
    assertThat(copiedContext.agent()).isEqualTo(originalContext.agent());
    assertThat(copiedContext.session()).isEqualTo(originalContext.session());
    assertThat(copiedContext.userContent()).isEqualTo(originalContext.userContent());
    assertThat(copiedContext.runConfig()).isEqualTo(originalContext.runConfig());
    assertThat(copiedContext.endInvocation()).isEqualTo(originalContext.endInvocation());
    assertThat(copiedContext.activeStreamingTools()).isEqualTo(originalContext.activeStreamingTools());
}
"
    "@Test
public void testGetters() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).isEmpty();
    assertThat(context.invocationId()).isEqualTo(testInvocationId);
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).hasValue(userContent);
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testSetAgent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    BaseAgent newMockAgent = mock(BaseAgent.class);
    context.agent(newMockAgent);
    assertThat(context.agent()).isEqualTo(newMockAgent);
}
"
    "@Test
public void testEquals_sameObject() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(context)).isTrue();
}
"
    "@Test
public void testEquals_null() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(null)).isFalse();
}
"
    "@Test
public void testEquals_sameValues() {
    InvocationContext context1 = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext context2 = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context1.equals(context2)).isTrue();

    assertThat(context2.equals(context1)).isTrue();
}
"
    "@Test
public void testEquals_differentValues() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext contextWithDiffSessionService = InvocationContext.builder().sessionService(
    mock(BaseSessionService.class)).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffInvocationId = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(
    "another-id").agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffAgent = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(
    mock(BaseAgent.class)).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithUserContentEmpty = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithLiveQueuePresent = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).liveRequestQueue(liveRequestQueue).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(contextWithDiffSessionService)).isFalse();
    assertThat(context.equals(contextWithDiffInvocationId)).isFalse();
    assertThat(context.equals(contextWithDiffAgent)).isFalse();
    assertThat(context.equals(contextWithUserContentEmpty)).isFalse();
    assertThat(context.equals(contextWithLiveQueuePresent)).isFalse();
}
"
    "@Test
public void testHashCode_differentValues() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext contextWithDiffSessionService = InvocationContext.builder().sessionService(
    mock(BaseSessionService.class)).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffInvocationId = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(
    "another-id").agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotEqualTo(contextWithDiffSessionService);
    assertThat(context).isNotEqualTo(contextWithDiffInvocationId);
}
"Scenario 1: Verify that pluginManager() returns the exact PluginManager instance set during construction via builder

Details:
  TestName: pluginManagerReturnsExplicitlySetPluginManagerInstance
  Description: This test verifies that when an explicit PluginManager instance is provided to the builder, the pluginManager() method returns that exact same instance without any modification or wrapping.

Execution:
  Arrange:
    - Create a new PluginManager instance (e.g., explicitPluginManager = new PluginManager()).
    - Build an InvocationContext using the builder, supplying all required fields (sessionService, artifactService, memoryService, agent, session, runConfig) and set pluginManager to explicitPluginManager.
  Act:
    - Call context.pluginManager() on the constructed InvocationContext.
  Assert:
    - Assert that the returned value is the same instance as explicitPluginManager using assertThat(context.pluginManager()).isSameInstanceAs(explicitPluginManager).

Validation:
  This assertion confirms that pluginManager() is a straightforward accessor returning the stored reference without any transformation. This is critical because consumers of the plugin system expect to operate on the same PluginManager instance they configured, ensuring consistent behavior across the invocation lifecycle.


Scenario 2: Verify that pluginManager() returns the default PluginManager when none is explicitly provided to the builder

Details:
  TestName: pluginManagerReturnsDefaultPluginManagerWhenNotExplicitlySet
  Description: This test verifies that when no pluginManager is explicitly supplied to the builder, the builder uses a default-constructed PluginManager and the pluginManager() method returns a non-null instance.

Execution:
  Arrange:
    - Build an InvocationContext using the builder without calling .pluginManager(...), providing only the minimum required fields (sessionService, artifactService, agent, session, userContent, runConfig).
  Act:
    - Call context.pluginManager() on the constructed InvocationContext.
  Assert:
    - Assert that the returned PluginManager is not null using assertThat(context.pluginManager()).isNotNull().

Validation:
  The builder initializes pluginManager to new PluginManager() by default. This scenario confirms that the default initialization works correctly and that pluginManager() never returns null even when the caller does not explicitly configure one, preventing NullPointerExceptions in downstream plugin-dependent logic.


Scenario 3: Verify that pluginManager() returns a non-null value when a custom PluginManager is set

Details:
  TestName: pluginManagerIsNotNullWhenCustomInstanceIsProvided
  Description: This test verifies that the result of pluginManager() is always non-null when a valid PluginManager is passed through the builder.

Execution:
  Arrange:
    - Instantiate a PluginManager (e.g., customPluginManager = new PluginManager()).
    - Build an InvocationContext supplying all required fields and .pluginManager(customPluginManager).
  Act:
    - Call context.pluginManager().
  Assert:
    - Assert that the returned value is not null: assertThat(context.pluginManager()).isNotNull().

Validation:
  This ensures a basic contract: any explicitly set PluginManager is preserved and accessible. Non-null guarantees are fundamental for any code that relies on pluginManager() to register or query plugins during an agent invocation.


Scenario 4: Verify that pluginManager() returns the correct PluginManager after a copyOf operation

Details:
  TestName: pluginManagerIsPreservedAfterCopyOf
  Description: This test verifies that after creating a shallow copy of an InvocationContext using InvocationContext.copyOf(), the pluginManager() on the copied context returns the same PluginManager instance as the original.

Execution:
  Arrange:
    - Create a PluginManager instance (e.g., originalPluginManager = new PluginManager()).
    - Build an original InvocationContext with the above PluginManager and all required fields.
    - Call InvocationContext.copyOf(originalContext) to produce a copiedContext.
  Act:
    - Call copiedContext.pluginManager().
  Assert:
    - Assert that copiedContext.pluginManager() returns the same instance as originalContext.pluginManager() using assertThat(copiedContext.pluginManager()).isSameInstanceAs(originalContext.pluginManager()).

Validation:
  The copyOf() method performs a shallow copy, meaning the PluginManager reference should not be duplicated. This test confirms that plugin state is shared correctly between original and copied contexts, which is important in agent delegation and sub-agent invocation scenarios where the same plugin registry should be accessible.


Scenario 5: Verify that two independently built InvocationContext instances with different PluginManager instances return their respective PluginManager objects

Details:
  TestName: pluginManagerReturnsDifferentInstancesForDifferentContexts
  Description: This test verifies that two separate InvocationContext instances built with different PluginManager instances each independently return their own PluginManager through pluginManager(), with no cross-contamination.

Execution:
  Arrange:
    - Create two distinct PluginManager instances: pluginManager1 = new PluginManager() and pluginManager2 = new PluginManager().
    - Build context1 with pluginManager1 and all required fields.
    - Build context2 with pluginManager2 and all required fields (same other parameters).
  Act:
    - Call context1.pluginManager() and context2.pluginManager().
  Assert:
    - Assert that context1.pluginManager() is the same instance as pluginManager1.
    - Assert that context2.pluginManager() is the same instance as pluginManager2.
    - Assert that context1.pluginManager() is not the same instance as context2.pluginManager().

Validation:
  This scenario ensures that PluginManager instances are correctly scoped to their owning InvocationContext. If two invocations share or bleed plugin state, it could lead to interference between different agent runs. Confirming isolation here is important for correctness in multi-invocation or concurrent scenarios.


Scenario 6: Verify that pluginManager() participates correctly in equals() comparison when PluginManagers are different

Details:
  TestName: pluginManagerInequalityReflectedInContextEquality
  Description: This test verifies that two InvocationContext instances built with different PluginManager instances are not considered equal, demonstrating that pluginManager() value participates in the equals() logic of InvocationContext.

Execution:
  Arrange:
    - Create two distinct PluginManager instances: pluginManagerA = new PluginManager() and pluginManagerB = new PluginManager().
    - Build contextA using pluginManagerA with all identical required fields.
    - Build contextB using pluginManagerB with all identical required fields.
  Act:
    - Call contextA.equals(contextB).
  Assert:
    - Assert that contextA.equals(contextB) is false: assertThat(contextA.equals(contextB)).isFalse().

Validation:
  The equals() method of InvocationContext includes pluginManager in its comparison. This test confirms that differing PluginManager instances cause two otherwise identical contexts to be unequal, ensuring that the field is properly considered in identity and comparison operations used throughout the framework.


Scenario 7: Verify that pluginManager() participates correctly in equals() when the same PluginManager instance is shared

Details:
  TestName: pluginManagerEqualityReflectedInContextEquality
  Description: This test verifies that two InvocationContext instances built with the same PluginManager instance (and all other identical fields) are considered equal, demonstrating consistent pluginManager equality behavior.

Execution:
  Arrange:
    - Create a single PluginManager instance: sharedPluginManager = new PluginManager().
    - Build contextX with sharedPluginManager and all required fields (specific, fixed invocationId).
    - Build contextY with the same sharedPluginManager and the same required fields.
  Act:
    - Call contextX.equals(contextY).
  Assert:
    - Assert that contextX.equals(contextY) is true: assertThat(contextX.equals(contextY)).isTrue().

Validation:
  This ensures that the pluginManager field does not introduce spurious inequality when the same instance is shared. This is significant in scenarios where a single PluginManager is used across multiple contexts (e.g., in sub-agent delegation), and correct equality checks depend on this consistency.


Scenario 8: Verify that pluginManager() is consistent across multiple successive calls on the same InvocationContext

Details:
  TestName: pluginManagerReturnsSameInstanceOnRepeatedCalls
  Description: This test verifies that calling pluginManager() multiple times on the same InvocationContext always returns the exact same PluginManager instance, confirming the method is idempotent and referentially stable.

Execution:
  Arrange:
    - Create a PluginManager instance: stablePluginManager = new PluginManager().
    - Build an InvocationContext with stablePluginManager and all required fields.
  Act:
    - Call context.pluginManager() three times, storing each result (result1, result2, result3).
  Assert:
    - Assert that result1, result2, and result3 are all the same instance as stablePluginManager.
    - Assert that result1 == result2 == result3 using isSameInstanceAs().

Validation:
  Idempotency of accessor methods is a fundamental contract in Java. Since pluginManager is a final field with no mutation path, successive calls must return the same reference. This test guards against accidental wrapping, lazy initialization errors, or any future refactoring that could break referential stability.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static com.google.common.truth.Truth.assertThat;

import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.genai.types.Content;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class InvocationContextPluginManagerTest {

	@Mock
	private BaseSessionService mockSessionService;

	@Mock
	private BaseArtifactService mockArtifactService;

	@Mock
	private BaseMemoryService mockMemoryService;

	@Mock
	private BaseAgent mockAgent;

	@Mock
	private Session mockSession;

	private RunConfig defaultRunConfig;

	private static final String FIXED_INVOCATION_ID = "e-test-invocation-id";

	@BeforeEach
	void setUp() {
		defaultRunConfig = RunConfig.builder().build();
	}

	private InvocationContext.Builder buildBaseContext() {
		return InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId(FIXED_INVOCATION_ID)
			.runConfig(defaultRunConfig);
	}

	@Test
	@Tag("valid")
	void pluginManagerReturnsExplicitlySetPluginManagerInstance() {
		// Arrange
		PluginManager explicitPluginManager = new PluginManager();
		InvocationContext context = buildBaseContext().pluginManager(explicitPluginManager).build();
		// Act
		PluginManager result = context.pluginManager();
		// Assert
		assertThat(result).isSameInstanceAs(explicitPluginManager);
	}

	@Test
	@Tag("valid")
	void pluginManagerReturnsDefaultPluginManagerWhenNotExplicitlySet() {
		// Arrange
		InvocationContext context = buildBaseContext().build();
		// Act
		PluginManager result = context.pluginManager();
		// Assert
		assertThat(result).isNotNull();
	}

	@Test
	@Tag("valid")
	void pluginManagerIsNotNullWhenCustomInstanceIsProvided() {
		// Arrange
		PluginManager customPluginManager = new PluginManager();
		InvocationContext context = buildBaseContext().pluginManager(customPluginManager).build();
		// Act
		PluginManager result = context.pluginManager();
		// Assert
		assertThat(result).isNotNull();
	}

	@Test
	@Tag("integration")
	void pluginManagerIsPreservedAfterCopyOf() {
		// Arrange
		PluginManager originalPluginManager = new PluginManager();
		InvocationContext originalContext = buildBaseContext().pluginManager(originalPluginManager).build();
		// Act
		InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
		// Assert
		assertThat(copiedContext.pluginManager()).isSameInstanceAs(originalContext.pluginManager());
	}

	@Test
	@Tag("valid")
	void pluginManagerReturnsDifferentInstancesForDifferentContexts() {
		// Arrange
		PluginManager pluginManager1 = new PluginManager();
		PluginManager pluginManager2 = new PluginManager();
		InvocationContext context1 = buildBaseContext().pluginManager(pluginManager1)
			.invocationId("e-invocation-1")
			.build();
		InvocationContext context2 = buildBaseContext().pluginManager(pluginManager2)
			.invocationId("e-invocation-2")
			.build();
		// Act
		PluginManager result1 = context1.pluginManager();
		PluginManager result2 = context2.pluginManager();
		// Assert
		assertThat(result1).isSameInstanceAs(pluginManager1);
		assertThat(result2).isSameInstanceAs(pluginManager2);
		assertThat(result1).isNotSameInstanceAs(result2);
	}

	@Test
	@Tag("invalid")
	void pluginManagerInequalityReflectedInContextEquality() {
		// Arrange
		PluginManager pluginManagerA = new PluginManager();
		PluginManager pluginManagerB = new PluginManager();
		InvocationContext contextA = buildBaseContext().pluginManager(pluginManagerA).build();
		InvocationContext contextB = buildBaseContext().pluginManager(pluginManagerB).build();
		// Act & Assert
		assertThat(contextA.equals(contextB)).isFalse();
	}

	@Test
	@Tag("valid")
	void pluginManagerEqualityReflectedInContextEquality() {
		// Arrange
		PluginManager sharedPluginManager = new PluginManager();
		InvocationContext contextX = buildBaseContext().pluginManager(sharedPluginManager)
			.invocationId(FIXED_INVOCATION_ID)
			.build();
		InvocationContext contextY = buildBaseContext().pluginManager(sharedPluginManager)
			.invocationId(FIXED_INVOCATION_ID)
			.build();
		// Act & Assert
		assertThat(contextX.equals(contextY)).isTrue();
	}

	@Test
	@Tag("valid")
	void pluginManagerReturnsSameInstanceOnRepeatedCalls() {
		// Arrange
		PluginManager stablePluginManager = new PluginManager();
		InvocationContext context = buildBaseContext().pluginManager(stablePluginManager).build();
		// Act
		PluginManager result1 = context.pluginManager();
		PluginManager result2 = context.pluginManager();
		PluginManager result3 = context.pluginManager();
		// Assert
		assertThat(result1).isSameInstanceAs(stablePluginManager);
		assertThat(result2).isSameInstanceAs(stablePluginManager);
		assertThat(result3).isSameInstanceAs(stablePluginManager);
		assertThat(result1).isSameInstanceAs(result2);
		assertThat(result2).isSameInstanceAs(result3);
	}

	@Test
	@Tag("boundary")
	void pluginManagerIsNotNullWhenContextCreatedWithStaticCreateMethod() {
		// Arrange
		Content userContent = Content.newBuilder().build();
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService,
				FIXED_INVOCATION_ID, mockAgent, mockSession, userContent, defaultRunConfig);
		// Act
		PluginManager result = context.pluginManager();
		// Assert
		assertThat(result).isNotNull();
	}

	@Test
	@Tag("boundary")
	void pluginManagerIsNotNullWhenContextCreatedWithLiveRequestQueue() {
		// Arrange
		LiveRequestQueue liveRequestQueue = new LiveRequestQueue();
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, liveRequestQueue, defaultRunConfig);
		// Act
		PluginManager result = context.pluginManager();
		// Assert
		assertThat(result).isNotNull();
	}

	@Test
	@Tag("integration")
	void pluginManagerIsPreservedAfterCopyOfWithNullUserContent() {
		// Arrange
		PluginManager originalPluginManager = new PluginManager();
		InvocationContext originalContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.pluginManager(originalPluginManager)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId(FIXED_INVOCATION_ID)
			.userContent(Optional.empty())
			.runConfig(defaultRunConfig)
			.build();
		// Act
		InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
		PluginManager result = copiedContext.pluginManager();
		// Assert
		assertThat(result).isSameInstanceAs(originalPluginManager);
	}

	@Test
	@Tag("valid")
	void pluginManagerHashCodeIsConsistentWithSameInstance() {
		// Arrange
		PluginManager sharedPluginManager = new PluginManager();
		InvocationContext contextA = buildBaseContext().pluginManager(sharedPluginManager)
			.invocationId(FIXED_INVOCATION_ID)
			.build();
		InvocationContext contextB = buildBaseContext().pluginManager(sharedPluginManager)
			.invocationId(FIXED_INVOCATION_ID)
			.build();
		// Act & Assert
		assertThat(contextA.hashCode()).isEqualTo(contextB.hashCode());
	}

	@Test
	@Tag("valid")
	void pluginManagerInstanceIsIndependentFromMemoryAndArtifactServices() {
		// Arrange
		PluginManager explicitPluginManager = new PluginManager();
		InvocationContext context = buildBaseContext().pluginManager(explicitPluginManager).build();
		// Act
		PluginManager pluginManagerResult = context.pluginManager();
		BaseMemoryService memoryServiceResult = context.memoryService();
		BaseArtifactService artifactServiceResult = context.artifactService();
		// Assert
		assertThat(pluginManagerResult).isSameInstanceAs(explicitPluginManager);
		assertThat(pluginManagerResult).isNotSameInstanceAs(memoryServiceResult);
		assertThat(pluginManagerResult).isNotSameInstanceAs(artifactServiceResult);
	}

	@Test
	@Tag("boundary")
	void pluginManagerDefaultInstanceIsCreatedWhenBuilderHasNoPluginManagerSet() {
		// Arrange
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId(FIXED_INVOCATION_ID)
			.runConfig(defaultRunConfig)
			.build();
		// Act
		PluginManager result = context.pluginManager();
		// Assert
		assertThat(result).isNotNull();
		assertThat(result).isInstanceOf(PluginManager.class);
	}

}
