/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=newInvocationContextId_87a927076b
ROOST_METHOD_SIG_HASH=newInvocationContextId_db44e2dbb1

Scenario 1: Verify that the returned ID starts with the expected prefix "e-"

Details:
  TestName: newInvocationContextIdStartsWithExpectedPrefix
  Description: Verifies that the string returned by newInvocationContextId() always begins
               with the literal prefix "e-", which is the defined convention for invocation
               context identifiers in the system.
Execution:
  Arrange: No setup is required since newInvocationContextId() is a static method with no
           parameters or dependencies.
  Act: Call InvocationContext.newInvocationContextId() and store the result in a String variable.
  Assert: Use assertTrue or assertThat to confirm that the returned string starts with "e-".
Validation:
  The assertion verifies that the prefix "e-" is consistently applied to all generated IDs.
  This is significant because other parts of the system (e.g., InvocationContext.Builder which
  uses newInvocationContextId() to set the default invocationId) may depend on this prefix
  format for routing, logging, or identification purposes.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;

import java.util.HashSet;
import java.util.Set;
import java.util.UUID;
import java.util.regex.Pattern;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.RepeatedTest;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

public class InvocationContextNewInvocationContextIdTest {
  private static final String EXPECTED_PREFIX = "e-";
  private static final Pattern UUID_PATTERN =
      Pattern.compile("^e-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$");

  @Test
  @Tag("valid")
  void newInvocationContextIdStartsWithExpectedPrefix() {
    String result = InvocationContext.newInvocationContextId();
    assertNotNull(result, "Generated ID should not be null");
    assertTrue(
        result.startsWith(EXPECTED_PREFIX),
        "Generated ID should start with 'e-' but was: " + result);
  }

  @Test
  @Tag("valid")
  void newInvocationContextIdIsNotNull() {
    String result = InvocationContext.newInvocationContextId();
    assertNotNull(result, "Generated ID must not be null");
  }

  @Test
  @Tag("valid")
  void newInvocationContextIdIsNotEmpty() {
    String result = InvocationContext.newInvocationContextId();
    assertFalse(result.isEmpty(), "Generated ID must not be empty");
  }

  @Test
  @Tag("valid")
  void newInvocationContextIdMatchesExpectedPattern() {
    String result = InvocationContext.newInvocationContextId();
    assertTrue(
        UUID_PATTERN.matcher(result).matches(),
        "Generated ID should match pattern 'e-<UUID>' but was: " + result);
  }

  @Test
  @Tag("valid")
  void newInvocationContextIdHasCorrectPrefixLength() {
    String result = InvocationContext.newInvocationContextId();
    assertTrue(
        result.length() > EXPECTED_PREFIX.length(),
        "Generated ID should have content after the prefix 'e-'");
  }

  @Test
  @Tag("valid")
  void newInvocationContextIdContainsValidUuidAfterPrefix() {
    String result = InvocationContext.newInvocationContextId();
    String uuidPart = result.substring(EXPECTED_PREFIX.length());
    assertDoesNotThrow(
        () -> UUID.fromString(uuidPart),
        "The part after 'e-' should be a valid UUID but was: " + uuidPart);
  }

  @Test
  @Tag("valid")
  void newInvocationContextIdUuidPartIsVersion4() {
    String result = InvocationContext.newInvocationContextId();
    String uuidPart = result.substring(EXPECTED_PREFIX.length());
    UUID uuid = UUID.fromString(uuidPart);
    assertEquals(4, uuid.version(), "The UUID in the generated ID should be version 4 (random)");
  }

  @Test
  @Tag("valid")
  void newInvocationContextIdHasExpectedTotalLength() {
    // "e-" (2 chars) + UUID standard representation (36 chars) = 38 chars
    int expectedLength = 2 + 36;
    String result = InvocationContext.newInvocationContextId();
    assertEquals(
        expectedLength,
        result.length(),
        "Generated ID should have length " + expectedLength + " but was: " + result.length());
  }

  @Test
  @Tag("valid")
  void newInvocationContextIdPrefixExactlyTwoChars() {
    String result = InvocationContext.newInvocationContextId();
    assertEquals("e-", result.substring(0, 2), "Prefix should be exactly 'e-'");
  }

  @RepeatedTest(10)
  @Tag("valid")
  void newInvocationContextIdAlwaysStartsWithPrefix() {
    String result = InvocationContext.newInvocationContextId();
    assertTrue(
        result.startsWith("e-"),
        "Every generated ID should always start with 'e-' but got: " + result);
  }

  @Test
  @Tag("valid")
  void newInvocationContextIdGeneratesTwoUniqueIds() {
    String id1 = InvocationContext.newInvocationContextId();
    String id2 = InvocationContext.newInvocationContextId();
    assertNotEquals(id1, id2, "Two consecutively generated IDs should be unique");
  }

  @Test
  @Tag("valid")
  void newInvocationContextIdGeneratesMultipleUniqueIds() {
    int count = 100;
    Set<String> generatedIds = new HashSet<>();
    for (int i = 0; i < count; i++) {
      generatedIds.add(InvocationContext.newInvocationContextId());
    }
    assertEquals(count, generatedIds.size(), "All " + count + " generated IDs should be unique");
  }

  @Test
  @Tag("valid")
  void newInvocationContextIdAllGeneratedIdsHaveCorrectPrefix() {
    int count = 50;
    for (int i = 0; i < count; i++) {
      String id = InvocationContext.newInvocationContextId();
      assertTrue(
          id.startsWith("e-"), "ID at iteration " + i + " should start with 'e-' but was: " + id);
    }
  }

  @Test
  @Tag("valid")
  void newInvocationContextIdAllGeneratedIdsMatchPattern() {
    int count = 50;
    for (int i = 0; i < count; i++) {
      String id = InvocationContext.newInvocationContextId();
      assertTrue(
          UUID_PATTERN.matcher(id).matches(),
          "ID at iteration " + i + " should match UUID pattern but was: " + id);
    }
  }

  @Test
  @Tag("boundary")
  void newInvocationContextIdFirstCharIsE() {
    String result = InvocationContext.newInvocationContextId();
    assertEquals('e', result.charAt(0), "First character of generated ID should be 'e'");
  }

  @Test
  @Tag("boundary")
  void newInvocationContextIdSecondCharIsDash() {
    String result = InvocationContext.newInvocationContextId();
    assertEquals('-', result.charAt(1), "Second character of generated ID should be '-'");
  }

  @Test
  @Tag("boundary")
  void newInvocationContextIdMinimumLength() {
    String result = InvocationContext.newInvocationContextId();
    assertTrue(
        result.length() >= 38,
        "Generated ID should have at least 38 characters (prefix + UUID) but had: "
            + result.length());
  }

  @Test
  @Tag("boundary")
  void newInvocationContextIdMaximumLength() {
    String result = InvocationContext.newInvocationContextId();
    assertEquals(
        38,
        result.length(),
        "Generated ID should have exactly 38 characters but had: " + result.length());
  }

  @Test
  @Tag("boundary")
  void newInvocationContextIdPrefixDoesNotContainUppercase() {
    String result = InvocationContext.newInvocationContextId();
    assertEquals(
        "e-",
        result.substring(0, 2),
        "Prefix should be lowercase 'e-' and not 'E-' or any uppercase variant");
  }

  @Test
  @Tag("boundary")
  void newInvocationContextIdUuidPartContainsHyphensAtCorrectPositions() {
    String result = InvocationContext.newInvocationContextId();
    // UUID format: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    // After "e-" prefix, hyphens should be at positions: 10, 15, 20, 25 (0-indexed in result)
    assertEquals('-', result.charAt(10), "Hyphen expected at position 10");
    assertEquals('-', result.charAt(15), "Hyphen expected at position 15");
    assertEquals('-', result.charAt(20), "Hyphen expected at position 20");
    assertEquals('-', result.charAt(25), "Hyphen expected at position 25");
  }

  @Test
  @Tag("boundary")
  void newInvocationContextIdDoesNotStartWithUppercaseE() {
    String result = InvocationContext.newInvocationContextId();
    assertFalse(result.startsWith("E-"), "Generated ID should not start with uppercase 'E-'");
  }

  @Test
  @Tag("boundary")
  void newInvocationContextIdIsNotBlank() {
    String result = InvocationContext.newInvocationContextId();
    assertFalse(result.isBlank(), "Generated ID should not be blank");
  }

  @Test
  @Tag("integration")
  void newInvocationContextIdCanBeUsedAsInvocationIdInBuilder() {
    String newId = InvocationContext.newInvocationContextId();
    assertNotNull(newId);
    assertTrue(newId.startsWith("e-"), "ID used in builder should start with 'e-'");
    // Verifies the generated ID is a valid string that can be used as an invocationId
    String uuidPart = newId.substring(2);
    assertDoesNotThrow(
        () -> UUID.fromString(uuidPart), "UUID part of the ID should be parseable as a UUID");
  }

  @Test
  @Tag("integration")
  void newInvocationContextIdIsConsistentlyFormattedAcrossMultipleCalls() {
    int count = 20;
    for (int i = 0; i < count; i++) {
      String id = InvocationContext.newInvocationContextId();
      assertNotNull(id, "ID should not be null at iteration " + i);
      assertTrue(id.startsWith("e-"), "ID should start with 'e-' at iteration " + i);
      assertEquals(38, id.length(), "ID should have length 38 at iteration " + i);
      assertTrue(
          UUID_PATTERN.matcher(id).matches(), "ID should match UUID pattern at iteration " + i);
    }
  }

  @Test
  @Tag("integration")
  void newInvocationContextIdAllUniqueAcrossLargeSet() {
    int count = 1000;
    Set<String> ids = new HashSet<>();
    for (int i = 0; i < count; i++) {
      ids.add(InvocationContext.newInvocationContextId());
    }
    assertEquals(count, ids.size(), "All 1000 generated IDs should be unique (no collisions)");
  }

  @Test
  @Tag("valid")
  void newInvocationContextIdUuidPartIsLowercase() {
    String result = InvocationContext.newInvocationContextId();
    String uuidPart = result.substring(EXPECTED_PREFIX.length());
    // UUID.randomUUID().toString() produces lowercase hex
    assertEquals(
        uuidPart.toLowerCase(), uuidPart, "UUID part of the generated ID should be lowercase");
  }

  @Test
  @Tag("valid")
  void newInvocationContextIdDoesNotContainWhitespace() {
    String result = InvocationContext.newInvocationContextId();
    assertFalse(result.contains(" "), "Generated ID should not contain spaces");
    assertFalse(result.contains("\t"), "Generated ID should not contain tabs");
    assertFalse(result.contains("\n"), "Generated ID should not contain newlines");
  }

  @Test
  @Tag("valid")
  void newInvocationContextIdPrefixNotRepeated() {
    String result = InvocationContext.newInvocationContextId();
    // Make sure the prefix "e-" only appears once at the start
    String withoutPrefix = result.substring(EXPECTED_PREFIX.length());
    assertFalse(
        withoutPrefix.startsWith("e-"),
        "The prefix 'e-' should not be repeated in the generated ID");
  }
}
