/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=incrementLlmCallsCount_728a2657e3
ROOST_METHOD_SIG_HASH=incrementLlmCallsCount_ccbe51a785

Scenario 1: Successful LLM Call Increment Without a Limit Configured

Details:
  TestName: incrementLlmCallsCountSucceedsWhenNoLimitConfigured
  Description: Verifies that calling incrementLlmCallsCount() succeeds without throwing any exception
               when the RunConfig has no maxLlmCalls limit set (i.e., maxLlmCalls is 0 or not configured).
               This tests the happy path where the invocation cost manager increments the call count freely.

Execution:
  Arrange:
    - Create a RunConfig using RunConfig.builder().build() (default configuration, no maxLlmCalls limit).
    - Build an InvocationContext using InvocationContext.builder() with the required fields:
        sessionService (mocked BaseSessionService),
        artifactService (mocked BaseArtifactService),
        session (mocked Session),
        agent (mocked BaseAgent),
        runConfig (the default RunConfig built above).
  Act:
    - Call invocationContext.incrementLlmCallsCount().
  Assert:
    - No exception is thrown.
    - The method completes normally.

Validation:
  This test confirms that when no LLM calls limit is enforced via RunConfig, the incrementLlmCallsCount()
  method does not throw LlmCallsLimitExceededException. It ensures the default behavior allows unrestricted
  LLM calls, which is critical for use cases where no rate limiting is required.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.models.LlmCallsLimitExceededException;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class InvocationContextIncrementLlmCallsCountTest {

	@Mock
	private BaseSessionService mockSessionService;

	@Mock
	private BaseArtifactService mockArtifactService;

	@Mock
	private BaseMemoryService mockMemoryService;

	@Mock
	private PluginManager mockPluginManager;

	@Mock
	private Session mockSession;

	@Mock
	private BaseAgent mockAgent;

	@BeforeEach
  void setUp() {
    when(mockSession.appName()).thenReturn("testApp");
    when(mockSession.userId()).thenReturn("testUser");
    when(mockSession.id()).thenReturn("testSessionId");
    when(mockAgent.name()).thenReturn("testAgent");
  }

	private InvocationContext buildInvocationContext(RunConfig runConfig) {
		return InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(runConfig)
			.build();
	}

	@Test
	@Tag("valid")
	void incrementLlmCallsCountSucceedsWhenNoLimitConfigured() {
		RunConfig runConfig = RunConfig.builder().build();
		InvocationContext invocationContext = buildInvocationContext(runConfig);
		assertDoesNotThrow(() -> invocationContext.incrementLlmCallsCount());
	}

	@Test
	@Tag("valid")
	void incrementLlmCallsCountSucceedsOnFirstCallWithLimit() {
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(5).build();
		InvocationContext invocationContext = buildInvocationContext(runConfig);
		assertDoesNotThrow(() -> invocationContext.incrementLlmCallsCount());
	}

	@Test
	@Tag("valid")
	void incrementLlmCallsCountSucceedsMultipleTimesWithinLimit() throws LlmCallsLimitExceededException {
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(5).build();
		InvocationContext invocationContext = buildInvocationContext(runConfig);
		for (int i = 0; i < 5; i++) {
			assertDoesNotThrow(() -> invocationContext.incrementLlmCallsCount());
		}
	}

	@Test
	@Tag("invalid")
	void incrementLlmCallsCountThrowsExceptionWhenLimitExceeded() throws LlmCallsLimitExceededException {
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(3).build();
		InvocationContext invocationContext = buildInvocationContext(runConfig);
		invocationContext.incrementLlmCallsCount();
		invocationContext.incrementLlmCallsCount();
		invocationContext.incrementLlmCallsCount();
		assertThrows(LlmCallsLimitExceededException.class, () -> invocationContext.incrementLlmCallsCount());
	}

	@Test
	@Tag("boundary")
	void incrementLlmCallsCountSucceedsExactlyAtLimit() throws LlmCallsLimitExceededException {
		int maxLlmCalls = 3;
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(maxLlmCalls).build();
		InvocationContext invocationContext = buildInvocationContext(runConfig);
		for (int i = 0; i < maxLlmCalls; i++) {
			final int callNum = i;
			assertDoesNotThrow(() -> invocationContext.incrementLlmCallsCount(),
					"Call " + (callNum + 1) + " should not throw");
		}
	}

	@Test
	@Tag("boundary")
	void incrementLlmCallsCountThrowsOnFirstCallBeyondLimit() throws LlmCallsLimitExceededException {
		int maxLlmCalls = 3;
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(maxLlmCalls).build();
		InvocationContext invocationContext = buildInvocationContext(runConfig);
		for (int i = 0; i < maxLlmCalls; i++) {
			invocationContext.incrementLlmCallsCount();
		}
		assertThrows(LlmCallsLimitExceededException.class, () -> invocationContext.incrementLlmCallsCount());
	}

	@Test
	@Tag("boundary")
	void incrementLlmCallsCountWithLimitOfOne() throws LlmCallsLimitExceededException {
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(1).build();
		InvocationContext invocationContext = buildInvocationContext(runConfig);
		assertDoesNotThrow(() -> invocationContext.incrementLlmCallsCount());
		assertThrows(LlmCallsLimitExceededException.class, () -> invocationContext.incrementLlmCallsCount());
	}

	@Test
	@Tag("valid")
	void incrementLlmCallsCountSucceedsWithNullRunConfig() {
		InvocationContext invocationContext = buildInvocationContext(null);
		assertDoesNotThrow(() -> invocationContext.incrementLlmCallsCount());
	}

	@Test
	@Tag("valid")
	void incrementLlmCallsCountSucceedsMultipleTimesWhenNoLimitConfigured() {
		RunConfig runConfig = RunConfig.builder().build();
		InvocationContext invocationContext = buildInvocationContext(runConfig);
		for (int i = 0; i < 100; i++) {
			assertDoesNotThrow(() -> invocationContext.incrementLlmCallsCount());
		}
	}

	@Test
	@Tag("boundary")
	void incrementLlmCallsCountWithMaxLlmCallsZeroAllowsUnlimitedCalls() {
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(0).build();
		InvocationContext invocationContext = buildInvocationContext(runConfig);
		for (int i = 0; i < 50; i++) {
			assertDoesNotThrow(() -> invocationContext.incrementLlmCallsCount());
		}
	}

	@Test
	@Tag("invalid")
	void incrementLlmCallsCountExceptionMessageContainsLimit() throws LlmCallsLimitExceededException {
		int maxLlmCalls = 2;
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(maxLlmCalls).build();
		InvocationContext invocationContext = buildInvocationContext(runConfig);
		invocationContext.incrementLlmCallsCount();
		invocationContext.incrementLlmCallsCount();
		LlmCallsLimitExceededException exception = assertThrows(LlmCallsLimitExceededException.class,
				() -> invocationContext.incrementLlmCallsCount());
		assertNotNull(exception.getMessage());
		assertTrue(exception.getMessage().contains(String.valueOf(maxLlmCalls)));
	}

	@Test
	@Tag("integration")
	void incrementLlmCallsCountWithCopiedContextTracksIndependently() throws LlmCallsLimitExceededException {
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(3).build();
		InvocationContext originalContext = buildInvocationContext(runConfig);
		originalContext.incrementLlmCallsCount();
		originalContext.incrementLlmCallsCount();
		InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
		assertDoesNotThrow(() -> copiedContext.incrementLlmCallsCount());
	}

	@Test
	@Tag("integration")
	void incrementLlmCallsCountIsIsolatedBetweenContextInstances() throws LlmCallsLimitExceededException {
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(2).build();
		InvocationContext context1 = buildInvocationContext(runConfig);
		InvocationContext context2 = buildInvocationContext(runConfig);
		context1.incrementLlmCallsCount();
		context1.incrementLlmCallsCount();
		assertThrows(LlmCallsLimitExceededException.class, () -> context1.incrementLlmCallsCount());
		assertDoesNotThrow(() -> context2.incrementLlmCallsCount());
	}

	@Test
	@Tag("valid")
	void incrementLlmCallsCountWithDefaultRunConfigBuilderAllowsMultipleCalls() {
		RunConfig runConfig = RunConfig.builder().build();
		InvocationContext invocationContext = buildInvocationContext(runConfig);
		for (int i = 0; i < 10; i++) {
			assertDoesNotThrow(() -> invocationContext.incrementLlmCallsCount());
		}
	}

	@Test
	@Tag("boundary")
	void incrementLlmCallsCountWithLargeLimit() throws LlmCallsLimitExceededException {
		int maxLlmCalls = 1000;
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(maxLlmCalls).build();
		InvocationContext invocationContext = buildInvocationContext(runConfig);
		for (int i = 0; i < maxLlmCalls; i++) {
			invocationContext.incrementLlmCallsCount();
		}
		assertThrows(LlmCallsLimitExceededException.class, () -> invocationContext.incrementLlmCallsCount());
	}

	@Test
	@Tag("invalid")
	void incrementLlmCallsCountContinuouslyThrowsAfterLimitExceeded() throws LlmCallsLimitExceededException {
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(1).build();
		InvocationContext invocationContext = buildInvocationContext(runConfig);
		invocationContext.incrementLlmCallsCount();
		assertThrows(LlmCallsLimitExceededException.class, () -> invocationContext.incrementLlmCallsCount());
		assertThrows(LlmCallsLimitExceededException.class, () -> invocationContext.incrementLlmCallsCount());
		assertThrows(LlmCallsLimitExceededException.class, () -> invocationContext.incrementLlmCallsCount());
	}

	@Test
	@Tag("valid")
	void incrementLlmCallsCountWithDefaultMaxLlmCallsIs500() throws LlmCallsLimitExceededException {
		RunConfig runConfig = RunConfig.builder().build();
		assertEquals(500, runConfig.maxLlmCalls());
		InvocationContext invocationContext = buildInvocationContext(runConfig);
		for (int i = 0; i < 500; i++) {
			invocationContext.incrementLlmCallsCount();
		}
		assertThrows(LlmCallsLimitExceededException.class, () -> invocationContext.incrementLlmCallsCount());
	}

	@Test
	@Tag("integration")
	void incrementLlmCallsCountWithFullyBuiltInvocationContext() throws LlmCallsLimitExceededException {
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(5).build();
		InvocationContext invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.pluginManager(mockPluginManager)
			.invocationId("full-context-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(runConfig)
			.endInvocation(false)
			.build();
		for (int i = 0; i < 5; i++) {
			assertDoesNotThrow(() -> invocationContext.incrementLlmCallsCount());
		}
		assertThrows(LlmCallsLimitExceededException.class, () -> invocationContext.incrementLlmCallsCount());
	}

}
