/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=hashCode_c3a2d500cd
ROOST_METHOD_SIG_HASH=hashCode_5a2657087a

Scenario 1: Hash Code Consistency for the Same Object

Details:
  TestName: hashCodeIsConsistentForSameObject
  Description: Verifies that calling hashCode() multiple times on the same InvocationContext instance
               returns the same value on every invocation, confirming the contract of consistent hashing.

Execution:
  Arrange:
    - Create mock instances of BaseSessionService, BaseArtifactService, BaseMemoryService, PluginManager,
      Session, RunConfig, and ResumabilityConfig using Mockito.
    - Build an InvocationContext using InvocationContext.builder() with all mocked dependencies,
      a specific invocationId (e.g., "inv-001"), a branch value, userContent as Optional.empty(),
      and endInvocation set to false.
  Act:
    - Call context.hashCode() three separate times and store each result.
  Assert:
    - Assert that all three returned hash code values are equal to each other.

Validation:
  This confirms the immutability contract of hashCode(): for a given object whose state does not change,
  the hash code must remain the same across multiple calls within the same execution. This is critical
  for correct behavior when InvocationContext instances are stored in hash-based collections like
  HashMap or HashSet.

*/

// ********RoostGPT********

```java
package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.flows.llmflows.ResumabilityConfig;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.genai.types.Content;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.junit.jupiter.api.*;
import com.google.adk.events.Event;
import com.google.adk.models.LlmCallsLimitExceededException;
import com.google.common.collect.ImmutableSet;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import com.google.errorprone.annotations.InlineMe;
import com.google.genai.types.FunctionCall;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import javax.annotation.Nullable;

@ExtendWith(MockitoExtension.class)
public class InvocationContextHashCodeTest {

	@Mock
	private BaseSessionService mockSessionService;

	@Mock
	private BaseArtifactService mockArtifactService;

	@Mock
	private BaseMemoryService mockMemoryService;

	@Mock
	private PluginManager mockPluginManager;

	@Mock
	private Session mockSession;

	@Mock
	private RunConfig mockRunConfig;

	@Mock
	private ResumabilityConfig mockResumabilityConfig;

	@Mock
	private BaseAgent mockAgent;

	@Mock
	private Content mockContent;

	private InvocationContext baseContext;

	@BeforeEach
	void setUp() {
		baseContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.pluginManager(mockPluginManager)
			.invocationId("inv-001")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.branch("main-branch")
			.endInvocation(false)
			.resumabilityConfig(mockResumabilityConfig)
			.build();
	}

	@Test
	@Tag("valid")
	void hashCodeIsConsistentForSameObject() {
		int hashCode1 = baseContext.hashCode();
		int hashCode2 = baseContext.hashCode();
		int hashCode3 = baseContext.hashCode();
		assertEquals(hashCode1, hashCode2);
		assertEquals(hashCode2, hashCode3);
		assertEquals(hashCode1, hashCode3);
	}

	@Test
	@Tag("valid")
	void hashCodeIsEqualForEqualObjects() {
		InvocationContext context1 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.pluginManager(mockPluginManager)
			.invocationId("inv-equal")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.branch("branch-equal")
			.endInvocation(false)
			.resumabilityConfig(mockResumabilityConfig)
			.build();
		InvocationContext context2 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.pluginManager(mockPluginManager)
			.invocationId("inv-equal")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.branch("branch-equal")
			.endInvocation(false)
			.resumabilityConfig(mockResumabilityConfig)
			.build();
		assertEquals(context1.hashCode(), context2.hashCode());
	}

	@Test
	@Tag("valid")
	void hashCodeDiffersWhenInvocationIdDiffers() {
		InvocationContext contextA = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("inv-AAA")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		InvocationContext contextB = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("inv-BBB")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		assertNotEquals(contextA.hashCode(), contextB.hashCode());
	}

	@Test
	@Tag("valid")
	void hashCodeDiffersWhenSessionServiceDiffers() {
		BaseSessionService anotherSessionService = mock(BaseSessionService.class);
		InvocationContext contextA = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("inv-001")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		InvocationContext contextB = InvocationContext.builder()
			.sessionService(anotherSessionService)
			.artifactService(mockArtifactService)
			.invocationId("inv-001")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		assertNotEquals(contextA.hashCode(), contextB.hashCode());
	}

	@Test
	@Tag("valid")
	void hashCodeDiffersWhenArtifactServiceDiffers() {
		BaseArtifactService anotherArtifactService = mock(BaseArtifactService.class);
		InvocationContext contextA = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("inv-001")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		InvocationContext contextB = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(anotherArtifactService)
			.invocationId("inv-001")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		assertNotEquals(contextA.hashCode(), contextB.hashCode());
	}

	@Test
	@Tag("valid")
	void hashCodeDiffersWhenMemoryServiceDiffers() {
		BaseMemoryService anotherMemoryService = mock(BaseMemoryService.class);
		InvocationContext contextA = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.invocationId("inv-001")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		InvocationContext contextB = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(anotherMemoryService)
			.invocationId("inv-001")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		assertNotEquals(contextA.hashCode(), contextB.hashCode());
	}

	@Test
	@Tag("valid")
	void hashCodeDiffersWhenPluginManagerDiffers() {
		PluginManager anotherPluginManager = mock(PluginManager.class);
		InvocationContext contextA = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.pluginManager(mockPluginManager)
			.invocationId("inv-001")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		InvocationContext contextB = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.pluginManager(anotherPluginManager)
			.invocationId("inv-001")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		assertNotEquals(contextA.hashCode(), contextB.hashCode());
	}

	@Test
	@Tag("valid")
	void hashCodeDiffersWhenAgentDiffers() {
		BaseAgent anotherAgent = mock(BaseAgent.class);
		InvocationContext contextA = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("inv-001")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		InvocationContext contextB = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("inv-001")
			.agent(anotherAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		assertNotEquals(contextA.hashCode(), contextB.hashCode());
	}

	@Test
	@Tag("valid")
	void hashCodeDiffersWhenSessionDiffers() {
		Session anotherSession = mock(Session.class);
		InvocationContext contextA = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("inv-001")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		InvocationContext contextB = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("inv-001")
			.agent(mockAgent)
			.session(anotherSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		assertNotEquals(contextA.hashCode(), contextB.hashCode());
	}

	@Test
	@Tag("valid")
	void hashCodeDiffersWhenUserContentDiffers() {
		InvocationContext contextA = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("inv-001")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		InvocationContext contextB = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("inv-001")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.of(mockContent))
			.runConfig(mockRunConfig)
			.build();
		assertNotEquals(contextA.hashCode(), contextB.hashCode());
	}

	@Test
	@Tag("valid")
	void hashCodeDiffersWhenRunConfigDiffers() {
		RunConfig anotherRunConfig = mock(RunConfig.class);
		InvocationContext contextA = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("inv-001")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		InvocationContext contextB = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("inv-001")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(anotherRunConfig)
			.build();
		assertNotEquals(contextA.hashCode(), contextB.hashCode());
	}

	@Test
	@Tag("valid")
	void hashCodeDiffersWhenEndInvocationDiffers() {
		InvocationContext contextA = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("inv-001")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.endInvocation(false)
			.build();
		InvocationContext contextB = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("inv-001")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.endInvocation(true)
			.build();
		assertNotEquals(contextA.hashCode(), contextB.hashCode());
	}

	@Test
    @Tag("valid")
    void hashCodeDiffersWhenBranchDiffers() {
        InvocationContext contextA = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("inv-001")
                .agent(mockAgent)
                .session(mockSession)
                .userContent(Optional.empty())
                .runConfig(mockRunConfig)
                .branch("branch-A")
                .build();
        InvocationContext contextB = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("inv-001")
                .agent(mockAgent)
                .session(mockSession)
                .userContent(Optional.empty())
                .runConfig(mockRunConfig)
                .branch("branch-B")
                .build();
        assertNotEquals(contextA.hashCode(), contextB.hashCode());
    }

@Test
    @Tag("valid")
    void hashCodeDiffersWhenResumabilityConfigDiffers() {
        ResumabilityConfig anotherResumabilityConfig = mock(ResumabilityConfig.class);
        InvocationContext contextA = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("inv-001")
                .agent(mockAgent)
                .session(mockSession)
                .userContent(Optional.empty())
                .runConfig(mockRunConfig)
                .resumabilityConfig(mockResumabilityConfig)
                .build();
        InvocationContext contextB = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("inv-001")
                .agent(mockAgent)
                .session(mockSession)
                .userContent(Optional.empty())
                .runConfig(mockRunConfig)
                .resumabilityConfig(anotherResumabilityConfig)
                .build();
        assertNot