/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=create_a8299eaa31
ROOST_METHOD_SIG_HASH=create_95f62994c3

Scenario 1: Create InvocationContext with All Valid Parameters Including Non-Null User Content

Details:
  TestName: createWithAllValidParametersAndNonNullUserContent
  Description: Verifies that the `create` method successfully builds and returns an `InvocationContext`
               instance when all parameters are valid and `userContent` is non-null. Confirms that
               each field is correctly set on the returned object.

Execution:
  Arrange:
    - Create a mock of `BaseSessionService`.
    - Create a mock of `BaseArtifactService`.
    - Define a non-null `invocationId` string (e.g., "test-invocation-001").
    - Create a mock of `BaseAgent`.
    - Create a mock of `Session`.
    - Create a non-null `Content` object as `userContent`.
    - Create a `RunConfig` instance using `RunConfig.builder().build()`.
  Act:
    - Call `InvocationContext.create(sessionService, artifactService, invocationId, agent, session, userContent, runConfig)`.
  Assert:
    - Assert that the returned `InvocationContext` is not null.
    - Assert that `result.sessionService()` equals the provided `sessionService` mock.
    - Assert that `result.artifactService()` equals the provided `artifactService` mock.
    - Assert that `result.invocationId()` equals `"test-invocation-001"`.
    - Assert that `result.agent()` equals the provided `agent` mock.
    - Assert that `result.session()` equals the provided `session` mock.
    - Assert that `result.userContent()` is present and equals the provided `Content` object.
    - Assert that `result.runConfig()` equals the provided `runConfig`.

Validation:
  This test confirms that when all valid parameters are supplied, the factory method correctly
  delegates to the builder and produces an `InvocationContext` where each field is populated
  as expected. This is the primary happy-path test, ensuring the core construction logic works
  end-to-end.

*/

// ********RoostGPT********

```java
package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.events.Event;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.models.LlmCallsLimitExceededException;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.genai.types.Content;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.junit.jupiter.api.*;
import com.google.adk.flows.llmflows.ResumabilityConfig;
import com.google.common.collect.ImmutableSet;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import com.google.errorprone.annotations.InlineMe;
import com.google.genai.types.FunctionCall;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import javax.annotation.Nullable;

@ExtendWith(MockitoExtension.class)
public class InvocationContextCreateTest {

	@Mock
	private BaseSessionService mockSessionService;

	@Mock
	private BaseArtifactService mockArtifactService;

	@Mock
	private BaseAgent mockAgent;

	@Mock
	private Session mockSession;

	@Mock
	private Content mockUserContent;

	private RunConfig runConfig;

	@BeforeEach
	void setUp() {
		runConfig = RunConfig.builder().build();
	}

	// -----------------------------------------------------------------------
	// Scenario 1: All valid parameters with non-null userContent
	// -----------------------------------------------------------------------
	@Test
	@Tag("valid")
	void createWithAllValidParametersAndNonNullUserContent() {
		String invocationId = "test-invocation-001";
		InvocationContext result = InvocationContext.create(mockSessionService, mockArtifactService, invocationId,
				mockAgent, mockSession, mockUserContent, runConfig);
		assertNotNull(result);
		assertEquals(mockSessionService, result.sessionService());
		assertEquals(mockArtifactService, result.artifactService());
		assertEquals(invocationId, result.invocationId());
		assertEquals(mockAgent, result.agent());
		assertEquals(mockSession, result.session());
		assertTrue(result.userContent().isPresent());
		assertEquals(mockUserContent, result.userContent().get());
		assertEquals(runConfig, result.runConfig());
	}

	// -----------------------------------------------------------------------
	// Null userContent wraps to Optional.empty()
	// -----------------------------------------------------------------------
	@Test
	@Tag("valid")
	void createWithNullUserContentWrapsToOptionalEmpty() {
		String invocationId = "test-invocation-002";
		InvocationContext result = InvocationContext.create(mockSessionService, mockArtifactService, invocationId,
				mockAgent, mockSession, null, runConfig);
		assertNotNull(result);
		assertFalse(result.userContent().isPresent());
	}

	// -----------------------------------------------------------------------
	// Session service is correctly stored
	// -----------------------------------------------------------------------
	@Test
	@Tag("valid")
	void createSetsSessionServiceCorrectly() {
		InvocationContext result = InvocationContext.create(mockSessionService, mockArtifactService, "inv-003",
				mockAgent, mockSession, mockUserContent, runConfig);
		assertSame(mockSessionService, result.sessionService());
	}

	// -----------------------------------------------------------------------
	// Artifact service is correctly stored
	// -----------------------------------------------------------------------
	@Test
	@Tag("valid")
	void createSetsArtifactServiceCorrectly() {
		InvocationContext result = InvocationContext.create(mockSessionService, mockArtifactService, "inv-004",
				mockAgent, mockSession, mockUserContent, runConfig);
		assertSame(mockArtifactService, result.artifactService());
	}

	// -----------------------------------------------------------------------
	// Invocation ID is correctly stored
	// -----------------------------------------------------------------------
	@Test
	@Tag("valid")
	void createSetsInvocationIdCorrectly() {
		String expectedId = "specific-invocation-id-xyz";
		InvocationContext result = InvocationContext.create(mockSessionService, mockArtifactService, expectedId,
				mockAgent, mockSession, mockUserContent, runConfig);
		assertEquals(expectedId, result.invocationId());
	}

	// -----------------------------------------------------------------------
	// Agent is correctly stored
	// -----------------------------------------------------------------------
	@Test
	@Tag("valid")
	void createSetsAgentCorrectly() {
		InvocationContext result = InvocationContext.create(mockSessionService, mockArtifactService, "inv-005",
				mockAgent, mockSession, mockUserContent, runConfig);
		assertSame(mockAgent, result.agent());
	}

	// -----------------------------------------------------------------------
	// Session is correctly stored
	// -----------------------------------------------------------------------
	@Test
	@Tag("valid")
	void createSetsSessionCorrectly() {
		InvocationContext result = InvocationContext.create(mockSessionService, mockArtifactService, "inv-006",
				mockAgent, mockSession, mockUserContent, runConfig);
		assertSame(mockSession, result.session());
	}

	// -----------------------------------------------------------------------
	// RunConfig is correctly stored
	// -----------------------------------------------------------------------
	@Test
	@Tag("valid")
	void createSetsRunConfigCorrectly() {
		RunConfig specificRunConfig = RunConfig.builder().setMaxLlmCalls(100).build();
		InvocationContext result = InvocationContext.create(mockSessionService, mockArtifactService, "inv-007",
				mockAgent, mockSession, mockUserContent, specificRunConfig);
		assertSame(specificRunConfig, result.runConfig());
	}

	// -----------------------------------------------------------------------
	// Null session service is accepted without throwing
	// -----------------------------------------------------------------------
	@Test
	@Tag("boundary")
	void createWithNullSessionServiceDoesNotThrow() {
		assertDoesNotThrow(() -> InvocationContext.create(null, mockArtifactService, "inv-008", mockAgent, mockSession,
				mockUserContent, runConfig));
	}

	// -----------------------------------------------------------------------
	// Null artifact service is accepted without throwing
	// -----------------------------------------------------------------------
	@Test
	@Tag("boundary")
	void createWithNullArtifactServiceDoesNotThrow() {
		assertDoesNotThrow(() -> InvocationContext.create(mockSessionService, null, "inv-009", mockAgent, mockSession,
				mockUserContent, runConfig));
	}

	// -----------------------------------------------------------------------
	// Null agent is accepted without throwing
	// -----------------------------------------------------------------------
	@Test
	@Tag("boundary")
	void createWithNullAgentDoesNotThrow() {
		assertDoesNotThrow(() -> InvocationContext.create(mockSessionService, mockArtifactService, "inv-010", null,
				mockSession, mockUserContent, runConfig));
	}

	// -----------------------------------------------------------------------
	// Null invocation ID is accepted without throwing
	// -----------------------------------------------------------------------
	@Test
	@Tag("boundary")
	void createWithNullInvocationIdDoesNotThrow() {
		assertDoesNotThrow(() -> InvocationContext.create(mockSessionService, mockArtifactService, null, mockAgent,
				mockSession, mockUserContent, runConfig));
	}

	// -----------------------------------------------------------------------
	// Null session is accepted without throwing
	// -----------------------------------------------------------------------
	@Test
	@Tag("boundary")
	void createWithNullSessionDoesNotThrow() {
		assertDoesNotThrow(() -> InvocationContext.create(mockSessionService, mockArtifactService, "inv-011", mockAgent,
				null, mockUserContent, runConfig));
	}

	// -----------------------------------------------------------------------
	// Null RunConfig is accepted without throwing
	// -----------------------------------------------------------------------
	@Test
	@Tag("boundary")
	void createWithNullRunConfigDoesNotThrow() {
		assertDoesNotThrow(() -> InvocationContext.create(mockSessionService, mockArtifactService, "inv-012", mockAgent,
				mockSession, mockUserContent, null));
	}

	// -----------------------------------------------------------------------
	// All-null parameters do not throw
	// -----------------------------------------------------------------------
	@Test
	@Tag("boundary")
	void createWithAllNullParametersDoesNotThrow() {
		assertDoesNotThrow(() -> InvocationContext.create(null, null, null, null, null, null, null));
	}

	// -----------------------------------------------------------------------
	// Empty string invocation ID is stored as-is
	// -----------------------------------------------------------------------
	@Test
	@Tag("boundary")
	void createWithEmptyStringInvocationId() {
		InvocationContext result = InvocationContext.create(mockSessionService, mockArtifactService, "", mockAgent,
				mockSession, mockUserContent, runConfig);
		assertNotNull(result);
		assertEquals("", result.invocationId());
	}

	// -----------------------------------------------------------------------
	// Very long invocation ID is stored correctly
	// -----------------------------------------------------------------------
	@Test
	@Tag("boundary")
	void createWithVeryLongInvocationId() {
		String longId = "a".repeat(10_000);
		InvocationContext result = InvocationContext.create(mockSessionService, mockArtifactService, longId, mockAgent,
				mockSession, mockUserContent, runConfig);
		assertNotNull(result);
		assertEquals(longId, result.invocationId());
	}

	// -----------------------------------------------------------------------
	// memoryService defaults to null when not provided via this factory
	// -----------------------------------------------------------------------
	@Test
	@Tag("valid")
	void createReturnsContextWithNullMemoryServiceByDefault() {
		InvocationContext result = InvocationContext.create(mockSessionService, mockArtifactService, "inv-013",
				mockAgent, mockSession, mockUserContent, runConfig);
		assertNull(result.memoryService());
	}

	// -----------------------------------------------------------------------
	// pluginManager defaults to null when not provided via this factory
	// -----------------------------------------------------------------------
	@Test
	@Tag("valid")
	void createReturnsContextWithNullPluginManagerByDefault() {
		InvocationContext result = InvocationContext.create(mockSessionService, mockArtifactService, "inv-014",
				mockAgent, mockSession, mockUserContent, runConfig);
		assertNull(result.pluginManager());
	}

	// -----------------------------------------------------------------------
	// liveRequestQueue defaults to Optional.empty() when not provided
	// -----------------------------------------------------------------------
	@Test
	@Tag("valid")
	void createReturnsContextWithEmptyLiveRequestQueueByDefault() {
		InvocationContext result = InvocationContext.create(mockSessionService, mockArtifactService, "inv-015",
				mockAgent, mockSession, mockUserContent, runConfig);
		assertNotNull(result.liveRequestQueue());
		assertFalse(result.liveRequestQueue().isPresent());
	}

	// -----------------------------------------------------------------------
	// branch defaults to Optional.empty() when not provided
	// -----------------------------------------------------------------------
	@Test
	@Tag("valid")
	void createReturnsContextWithEmptyBranchByDefault() {
		InvocationContext result = InvocationContext.create(mockSessionService, mockArtifactService, "inv-016",
				mockAgent, mockSession, mockUserContent, runConfig);
		assertNotNull(result.branch());
		assertFalse(result.branch().isPresent());
	}

	// -----------------------------------------------------------------------
	// endInvocation defaults to false
	// -----------------------------------------------------------------------
	@Test
	@Tag("valid")
	void createReturnsContextWithEndInvocationFalseByDefault() {
		InvocationContext result = InvocationContext.create(mockSessionService, mockArtifactService, "inv-017",
				mockAgent, mockSession, mockUserContent, runConfig);
		assertFalse(result.endInvocation());
	}

	// -----------------------------------------------------------------------
	// Two calls with same parameters produce equal but distinct instances
	// -----------------------------------------------------------------------
	@Test
	@Tag("integration")
	void createTwiceWithSameParametersProducesEqualInstances() {
		String invocationId = "inv-018";
		InvocationContext first = InvocationContext.create(mockSessionService, mockArtifactService, invocationId,
				mockAgent, mockSession, mockUserContent, runConfig);
		InvocationContext second = InvocationContext.create(mockSessionService, mockArtifactService, invocationId,
				mockAgent, mockSession, mockUserContent, runConfig);
		assertNotNull(first);
		assertNotNull(second);
		assertNotSame(first, second);
		assertEquals(first, second);
	}

	// -----------------------------------------------------------------------
	// Two calls with different invocation IDs produce unequal instances
	// -----------------------------------------------------------------------
	@Test
	@Tag("valid")
	void createWithDifferentInvocationIdsProducesUnequalInstances() {
		InvocationContext first = InvocationContext.create(mockSessionService, mockArtifactService, "id-A", mockAgent,
				mockSession, mockUserContent, runConfig);
		InvocationContext second = InvocationContext.create(mockSessionService, mockArtifactService, "id-B", mockAgent,
				mockSession, mockUserContent, runConfig);
		assertNotEquals(first, second);
	}

	// -----------------------------------------------------------------------
	// activeStreamingTools is non-null and empty by default
	// -----------------------------------------------------------------------
	@Test
	@Tag("valid")
	void createReturnsContextWithEmptyActiveStreamingToolsByDefault() {
		InvocationContext result = InvocationContext.create(mockSessionService, mockArtifactService, "inv-019",
				mockAgent, mockSession, mockUserContent, runConfig);
		assertNotNull(result.activeStreamingTools());
		assertTrue(result.activeStreamingTools().isEmpty());
	}

	// -----------------------------------------------------------------------
	// maxLlmCalls is reflected in runConfig correctly
	// -----------------------------------------------------------------------
	@Test
    @Tag("integration")
    void createWithCustomMaxLlmCallsRunConfigReflectsCorrectly() {
        RunConfig customRunConfig = RunConfig.builder().setMaxLlmCalls(10).build();
        InvocationContext result = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                "inv-020",
                mockAgent,
                mockSession,
                mockUserContent,
                customRunConfig);
        assertNotNull(result);
        assertEquals(10, result.runConfig().maxLlmCalls());
    }

// -----------------------------------------------------------------------
// Verifying that incrementLlmCallsCount throws when limit exceeded
// -----------------------------------------------------------------------
@Test
    @Tag("integration")
    void incrementLlmCallsCountThrowsWhenMaxExceeded() {
        RunConfig limitedConfig = RunConfig.builder().setMaxLlmCalls(1).build();
        InvocationContext ctx = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                "inv-021",
                mockAgent,
                mockSession,
                mockUserContent,
                limitedConfig);
        assertDoesNotThrow(ctx::incrementLlmCallsCount