/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=endInvocation_306878eff5
ROOST_METHOD_SIG_HASH=endInvocation_b038f3ac95

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/june-java-unit/1782282457/source/adk-java/core/src/test/java/com/google/adk/agents/InvocationContextTest.java
Tests:
    "@Test
public void testCreateWithUserContent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).isEmpty();
    assertThat(context.invocationId()).isEqualTo(testInvocationId);
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).hasValue(userContent);
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testCreateWithNullUserContent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.userContent()).isEmpty();
}
"
    "@Test
public void testCreateWithLiveRequestQueue() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).liveRequestQueue(liveRequestQueue).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).hasValue(liveRequestQueue);

    assertThat(context.invocationId()).startsWith("e-");
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).isEmpty();
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testCopyOf() {
    InvocationContext originalContext = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    originalContext.activeStreamingTools().putAll(activeStreamingTools);
    InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
    assertThat(copiedContext).isNotNull();
    assertThat(copiedContext).isNotSameInstanceAs(originalContext);
    assertThat(copiedContext.sessionService()).isEqualTo(originalContext.sessionService());
    assertThat(copiedContext.artifactService()).isEqualTo(originalContext.artifactService());
    assertThat(copiedContext.memoryService()).isEqualTo(originalContext.memoryService());
    assertThat(copiedContext.liveRequestQueue()).isEqualTo(originalContext.liveRequestQueue());
    assertThat(copiedContext.invocationId()).isEqualTo(originalContext.invocationId());
    assertThat(copiedContext.agent()).isEqualTo(originalContext.agent());
    assertThat(copiedContext.session()).isEqualTo(originalContext.session());
    assertThat(copiedContext.userContent()).isEqualTo(originalContext.userContent());
    assertThat(copiedContext.runConfig()).isEqualTo(originalContext.runConfig());
    assertThat(copiedContext.endInvocation()).isEqualTo(originalContext.endInvocation());
    assertThat(copiedContext.activeStreamingTools()).isEqualTo(originalContext.activeStreamingTools());
}
"
    "@Test
public void testGetters() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).isEmpty();
    assertThat(context.invocationId()).isEqualTo(testInvocationId);
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).hasValue(userContent);
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testSetAgent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    BaseAgent newMockAgent = mock(BaseAgent.class);
    context.agent(newMockAgent);
    assertThat(context.agent()).isEqualTo(newMockAgent);
}
"
    "@Test
public void testEquals_sameObject() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(context)).isTrue();
}
"
    "@Test
public void testEquals_null() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(null)).isFalse();
}
"
    "@Test
public void testEquals_sameValues() {
    InvocationContext context1 = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext context2 = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context1.equals(context2)).isTrue();

    assertThat(context2.equals(context1)).isTrue();
}
"
    "@Test
public void testEquals_differentValues() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext contextWithDiffSessionService = InvocationContext.builder().sessionService(
    mock(BaseSessionService.class)).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffInvocationId = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(
    "another-id").agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffAgent = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(
    mock(BaseAgent.class)).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithUserContentEmpty = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithLiveQueuePresent = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).liveRequestQueue(liveRequestQueue).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(contextWithDiffSessionService)).isFalse();
    assertThat(context.equals(contextWithDiffInvocationId)).isFalse();
    assertThat(context.equals(contextWithDiffAgent)).isFalse();
    assertThat(context.equals(contextWithUserContentEmpty)).isFalse();
    assertThat(context.equals(contextWithLiveQueuePresent)).isFalse();
}
"
    "@Test
public void testHashCode_differentValues() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext contextWithDiffSessionService = InvocationContext.builder().sessionService(
    mock(BaseSessionService.class)).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffInvocationId = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(
    "another-id").agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotEqualTo(contextWithDiffSessionService);
    assertThat(context).isNotEqualTo(contextWithDiffInvocationId);
}
"Scenario 1: Verify endInvocation Returns False When Built with endInvocation Set to False

Details:
  TestName: endInvocationReturnsFalseWhenSetToFalse
  Description: Verifies that the endInvocation() method returns false when the InvocationContext
               is constructed using the builder with endInvocation explicitly set to false.
Execution:
  Arrange: Build an InvocationContext using the builder, providing all required fields
           (sessionService, artifactService, memoryService, pluginManager, invocationId,
           agent, session, userContent, runConfig) and setting endInvocation(false).
  Act: Call endInvocation() on the constructed InvocationContext instance.
  Assert: Assert that the return value of endInvocation() is false.
Validation:
  The assertion confirms that when the builder explicitly sets endInvocation to false,
  the getter correctly reflects that value. This is critical for ensuring the invocation
  lifecycle is not prematurely terminated under normal operating conditions.

*/

// ********RoostGPT********

```java
package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.events.Event;
import com.google.adk.flows.llmflows.ResumabilityConfig;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.models.LlmCallsLimitExceededException;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.genai.types.Content;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.junit.jupiter.api.*;
import com.google.common.collect.ImmutableSet;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import com.google.errorprone.annotations.InlineMe;
import com.google.genai.types.FunctionCall;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import javax.annotation.Nullable;

@ExtendWith(MockitoExtension.class)
public class InvocationContextEndInvocationTest {

	@Mock
	private BaseSessionService mockSessionService;

	@Mock
	private BaseArtifactService mockArtifactService;

	@Mock
	private BaseMemoryService mockMemoryService;

	@Mock
	private PluginManager mockPluginManager;

	@Mock
	private Session mockSession;

	@Mock
	private BaseAgent mockAgent;

	@Mock
	private RunConfig mockRunConfig;

	@Mock
	private ResumabilityConfig mockResumabilityConfig;

	@BeforeEach
    void setUp() {
        when(mockSession.appName()).thenReturn("testApp");
        when(mockSession.userId()).thenReturn("testUser");
    }

	private InvocationContext buildBaseContext(boolean endInvocation) {
		return InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.pluginManager(mockPluginManager)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.endInvocation(endInvocation)
			.build();
	}

	@Test
	@Tag("valid")
	void endInvocationReturnsFalseWhenSetToFalse() {
		// Arrange
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.pluginManager(mockPluginManager)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.endInvocation(false)
			.build();
		// Act
		boolean result = context.endInvocation();
		// Assert
		assertFalse(result, "endInvocation() should return false when set to false in builder");
	}

	@Test
	@Tag("valid")
	void endInvocationReturnsTrueWhenSetToTrue() {
		// Arrange
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.pluginManager(mockPluginManager)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.endInvocation(true)
			.build();
		// Act
		boolean result = context.endInvocation();
		// Assert
		assertTrue(result, "endInvocation() should return true when set to true in builder");
	}

	@Test
	@Tag("valid")
	void endInvocationDefaultsToFalseWhenNotExplicitlySet() {
		// Arrange
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(mockRunConfig)
			.build();
		// Act
		boolean result = context.endInvocation();
		// Assert
		assertFalse(result, "endInvocation() should default to false when not explicitly set");
	}

	@Test
	@Tag("valid")
	void endInvocationReturnsFalseAfterSetEndInvocationCalledWithFalse() {
		// Arrange
		InvocationContext context = buildBaseContext(false);
		// Act
		context.setEndInvocation(false);
		boolean result = context.endInvocation();
		// Assert
		assertFalse(result, "endInvocation() should return false after setEndInvocation(false) is called");
	}

	@Test
	@Tag("valid")
	void endInvocationReturnsTrueAfterSetEndInvocationCalledWithTrue() {
		// Arrange
		InvocationContext context = buildBaseContext(false);
		// Act
		context.setEndInvocation(true);
		boolean result = context.endInvocation();
		// Assert
		assertTrue(result, "endInvocation() should return true after setEndInvocation(true) is called");
	}

	@Test
	@Tag("valid")
	void endInvocationReflectsUpdatedValueAfterMultipleSetCalls() {
		// Arrange
		InvocationContext context = buildBaseContext(false);
		// Act & Assert - toggle between true and false
		context.setEndInvocation(true);
		assertTrue(context.endInvocation(), "endInvocation() should return true after first setEndInvocation(true)");
		context.setEndInvocation(false);
		assertFalse(context.endInvocation(), "endInvocation() should return false after setEndInvocation(false)");
		context.setEndInvocation(true);
		assertTrue(context.endInvocation(), "endInvocation() should return true after second setEndInvocation(true)");
	}

	@Test
	@Tag("valid")
	void endInvocationIsCopiedCorrectlyWhenContextIsCopied() {
		// Arrange
		InvocationContext original = buildBaseContext(true);
		// Act
		InvocationContext copy = InvocationContext.copyOf(original);
		// Assert
		assertTrue(copy.endInvocation(), "Copied context should preserve endInvocation=true from original");
	}

	@Test
	@Tag("valid")
	void endInvocationFalseIsCopiedCorrectlyWhenContextIsCopied() {
		// Arrange
		InvocationContext original = buildBaseContext(false);
		// Act
		InvocationContext copy = InvocationContext.copyOf(original);
		// Assert
		assertFalse(copy.endInvocation(), "Copied context should preserve endInvocation=false from original");
	}

	@Test
	@Tag("valid")
	void endInvocationOfCopyIsIndependentOfOriginal() {
		// Arrange
		InvocationContext original = buildBaseContext(false);
		InvocationContext copy = InvocationContext.copyOf(original);
		// Act - modify the copy's endInvocation
		copy.setEndInvocation(true);
		// Assert
		assertFalse(original.endInvocation(),
				"Original context's endInvocation should remain unaffected when copy is modified");
		assertTrue(copy.endInvocation(), "Copied context should reflect updated endInvocation=true");
	}

	@Test
	@Tag("valid")
	void endInvocationOfOriginalIsIndependentOfCopy() {
		// Arrange
		InvocationContext original = buildBaseContext(false);
		InvocationContext copy = InvocationContext.copyOf(original);
		// Act - modify the original's endInvocation
		original.setEndInvocation(true);
		// Assert
		assertTrue(original.endInvocation(), "Original context's endInvocation should return true after being set");
		assertFalse(copy.endInvocation(), "Copied context's endInvocation should remain false");
	}

	@Test
	@Tag("boundary")
	void endInvocationInitiallyFalseBeforeAnyMutation() {
		// Arrange
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("boundary-test-id")
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(mockRunConfig)
			.build();
		// Act
		boolean result = context.endInvocation();
		// Assert
		assertFalse(result, "endInvocation() should be false initially before any mutation");
	}

	@Test
	@Tag("boundary")
	void endInvocationRemainsConsistentAfterRepeatedReads() {
		// Arrange
		InvocationContext context = buildBaseContext(true);
		// Act & Assert - read multiple times to ensure consistency
		for (int i = 0; i < 5; i++) {
			assertTrue(context.endInvocation(),
					"endInvocation() should consistently return true on repeated reads, iteration: " + i);
		}
	}

	@Test
	@Tag("boundary")
	void endInvocationFalseRemainsConsistentAfterRepeatedReads() {
		// Arrange
		InvocationContext context = buildBaseContext(false);
		// Act & Assert - read multiple times to ensure consistency
		for (int i = 0; i < 5; i++) {
			assertFalse(context.endInvocation(),
					"endInvocation() should consistently return false on repeated reads, iteration: " + i);
		}
	}

	@Test
	@Tag("valid")
	void endInvocationUsedInCreateFactoryMethodDefaultsToFalse() {
		// Arrange
		Content userContent = mock(Content.class);
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService,
				"factory-invocation-id", mockAgent, mockSession, userContent, mockRunConfig);
		// Act
		boolean result = context.endInvocation();
		// Assert
		assertFalse(result, "endInvocation() should default to false when created via create() factory method");
	}

	@Test
	@Tag("valid")
	void endInvocationFalseIncludedInEqualsComparison() {
		// Arrange
		InvocationContext context1 = buildBaseContext(false);
		InvocationContext context2 = buildBaseContext(false);
		// Act & Assert
		assertEquals(context1, context2,
				"Two InvocationContexts with same parameters and endInvocation=false should be equal");
	}

	@Test
	@Tag("valid")
	void endInvocationTrueIncludedInEqualsComparison() {
		// Arrange
		InvocationContext context1 = buildBaseContext(true);
		InvocationContext context2 = buildBaseContext(true);
		// Act & Assert
		assertEquals(context1, context2,
				"Two InvocationContexts with same parameters and endInvocation=true should be equal");
	}

	@Test
	@Tag("valid")
	void endInvocationDifferenceBreaksEquality() {
		// Arrange
		InvocationContext contextFalse = buildBaseContext(false);
		InvocationContext contextTrue = buildBaseContext(true);
		// Act & Assert
		assertNotEquals(contextFalse, contextTrue,
				"Two InvocationContexts differing only in endInvocation value should not be equal");
	}

	@Test
	@Tag("valid")
	void endInvocationDifferenceAffectsHashCode() {
		// Arrange
		InvocationContext contextFalse = buildBaseContext(false);
		InvocationContext contextTrue = buildBaseContext(true);
		// Act & Assert
		assertNotEquals(contextFalse.hashCode(), contextTrue.hashCode(),
				"Two InvocationContexts differing in endInvocation should (typically) have different hash codes");
	}

	@Test
	@Tag("integration")
	void endInvocationWorksCorrectlyWithAllFieldsProvided() {
		// Arrange
		Content userContent = mock(Content.class);
		LiveRequestQueue liveRequestQueue = new LiveRequestQueue();
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.pluginManager(mockPluginManager)
			.liveRequestQueue(Optional.of(liveRequestQueue))
			.branch("test-branch")
			.invocationId("full-context-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.of(userContent))
			.runConfig(mockRunConfig)
			.endInvocation(false)
			.build();
		// Act
		boolean result = context.endInvocation();
		// Assert
		assertFalse(result, "endInvocation() should return false even when all optional fields are provided");
	}

	@Test
	@Tag("integration")
	void endInvocationTrueWorksCorrectlyWithAllFieldsProvided() {
		// Arrange
		Content userContent = mock(Content.class);
		LiveRequestQueue liveRequestQueue = new LiveRequestQueue();
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.pluginManager(mockPluginManager)
			.liveRequestQueue(Optional.of(liveRequestQueue))
			.branch("test-branch")
			.invocationId("full-context-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.of(userContent))
			.runConfig(mockRunConfig)
			.endInvocation(true)
			.build();
		// Act
		boolean result = context.endInvocation();
		// Assert
		assertTrue(result,
				"endInvocation() should return true when set to true even with all optional fields provided");
	}

	@ParameterizedTest
    @Tag("valid")
    @ValueSource(booleans = {true, false})
    void endInvocationReturnsSameValueAsSetInBuilder(boolean endInvocationValue) {
        // Arrange
        InvocationContext context = buildBaseContext(endInvocationValue);
        // Act
        boolean result = context.endInvocation();
        // Assert
        assertEquals(endInvocationValue, result,
                "endInvocation() should return the same value as was set in the builder");
    }

@Test
    @Tag("integration")
    void endInvocationTransitionsFromFalseToTrueAndBackToFalse() {
        // Arrange
        InvocationContext context = buildBaseContext(false);
        // Assert initial state
        assertFalse(context.endInvocation(), "Initial endInvocation should be false");
        // Act - transition to true
        context.setEndInvocation(true);
        // Assert transitioned state
        assertTrue(context.endInvocation(), "endInvocation should be true after setEndInvocation(true)");
        // Act - transition back to false
        context.setEndInvocation(false);
        // Assert final state
        assertFalse(context.endInv