/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=branch_25309d7017
ROOST_METHOD_SIG_HASH=branch_5237016f3f

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/june-java-unit/1782282926/source/adk-java/core/src/test/java/com/google/adk/agents/ParallelAgentTest.java
Tests:
    "@Test
public void runAsync_subAgentsExecuteInParallel_eventsOrderedByCompletion() {
    String agent1Name = "test_agent_1_delayed";
    String agent2Name = "test_agent_2_fast";
    String parallelAgentName = "test_parallel_agent";
    TestingAgent agent1 = new TestingAgent(agent1Name, "Delayed Agent", 500);
    TestingAgent agent2 = new TestingAgent(agent2Name, "Fast Agent", 0);
    ParallelAgent parallelAgent = ParallelAgent.builder().name(parallelAgentName).subAgents(agent1, agent2).build();
    InvocationContext invocationContext = createInvocationContext(parallelAgent);
    List<Event> events = parallelAgent.runAsync(invocationContext).toList().blockingGet();
    assertThat(events).hasSize(2);

    Event firstEvent = events.get(0);
    assertThat(firstEvent.author()).isEqualTo(agent2Name);
    assertThat(firstEvent.content().get().parts().get().get(0).text()).hasValue("Hello, async " + agent2Name + "!");
    assertThat(firstEvent.branch().get()).endsWith(agent2Name);

    Event secondEvent = events.get(1);
    assertThat(secondEvent.author()).isEqualTo(agent1Name);
    assertThat(secondEvent.content().get().parts().get().get(0).text()).hasValue("Hello, async " + agent1Name + "!");
    assertThat(secondEvent.branch().get()).endsWith(agent1Name);
}
"Scenario 1: Setting a Valid Non-Null Branch String

Details:
  TestName: branchIsSetToNonNullValue
  Description: Verifies that calling branch() with a valid non-null string correctly stores the value
               as a non-empty Optional in the InvocationContext's branch field.

Execution:
  Arrange: Build an InvocationContext using InvocationContext.builder() with required fields
           (sessionService, artifactService, session, agent). Do not set a branch during construction.
  Act: Call invocationContext.branch("feature-branch-1") on the constructed context.
  Assert: Call invocationContext.branch() and assert that the returned Optional is present and
          contains the value "feature-branch-1".

Validation:
  Verifies that a non-null branch string is wrapped in Optional.of() and stored correctly.
  This is essential to correctly track conversation branch forks during agent invocation routing.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.events.Event;
import com.google.adk.flows.llmflows.ResumabilityConfig;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.models.LlmCallsLimitExceededException;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.genai.types.Content;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.junit.jupiter.api.*;
import com.google.common.collect.ImmutableSet;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import com.google.errorprone.annotations.InlineMe;
import com.google.genai.types.FunctionCall;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import javax.annotation.Nullable;

@ExtendWith(MockitoExtension.class)
public class InvocationContextBranchTest {

	@Mock
	private BaseSessionService mockSessionService;

	@Mock
	private BaseArtifactService mockArtifactService;

	@Mock
	private BaseMemoryService mockMemoryService;

	@Mock
	private PluginManager mockPluginManager;

	@Mock
	private Session mockSession;

	@Mock
	private BaseAgent mockAgent;

	private RunConfig defaultRunConfig;

	@BeforeEach
	void setUp() {
		defaultRunConfig = RunConfig.builder().build();
		when(mockSession.appName()).thenReturn("testApp");
		when(mockSession.userId()).thenReturn("testUser");
	}

	private InvocationContext buildDefaultContext() {
		return InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(defaultRunConfig)
			.build();
	}

	// Scenario 1: Setting a Valid Non-Null Branch String
	@Test
	@Tag("valid")
	void branchIsSetToNonNullValue() {
		// Arrange
		InvocationContext invocationContext = buildDefaultContext();
		// Act
		invocationContext.branch("feature-branch-1");
		// Assert
		Optional<String> branch = invocationContext.branch();
		assertTrue(branch.isPresent(), "Branch should be present");
		assertEquals("feature-branch-1", branch.get(), "Branch value should match");
	}

	@Test
	@Tag("valid")
	void branchIsSetToNullValue() {
		// Arrange
		InvocationContext invocationContext = buildDefaultContext();
		// Act
		invocationContext.branch(null);
		// Assert
		Optional<String> branch = invocationContext.branch();
		assertFalse(branch.isPresent(), "Branch should be empty when null is set");
	}

	@Test
	@Tag("valid")
	void branchIsSetToEmptyString() {
		// Arrange
		InvocationContext invocationContext = buildDefaultContext();
		// Act
		invocationContext.branch("");
		// Assert
		Optional<String> branch = invocationContext.branch();
		assertTrue(branch.isPresent(), "Branch should be present even for empty string");
		assertEquals("", branch.get(), "Branch value should be empty string");
	}

	@Test
	@Tag("valid")
	void branchOverwritesPreviousBranchValue() {
		// Arrange
		InvocationContext invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(defaultRunConfig)
			.branch("initial-branch")
			.build();
		// Act
		invocationContext.branch("updated-branch");
		// Assert
		Optional<String> branch = invocationContext.branch();
		assertTrue(branch.isPresent(), "Branch should be present");
		assertEquals("updated-branch", branch.get(), "Branch should be updated to new value");
	}

	@Test
	@Tag("valid")
	void branchOverwritesWithNull() {
		// Arrange
		InvocationContext invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(defaultRunConfig)
			.branch("initial-branch")
			.build();
		// Act
		invocationContext.branch(null);
		// Assert
		Optional<String> branch = invocationContext.branch();
		assertFalse(branch.isPresent(), "Branch should be empty after setting null");
	}

	@Test
	@Tag("valid")
	void branchWithDotSeparatedPath() {
		// Arrange
		InvocationContext invocationContext = buildDefaultContext();
		// Act
		invocationContext.branch("parent.child.grandchild");
		// Assert
		Optional<String> branch = invocationContext.branch();
		assertTrue(branch.isPresent(), "Branch should be present");
		assertEquals("parent.child.grandchild", branch.get(), "Branch should support dot-separated paths");
	}

	@Test
	@Tag("valid")
	void branchWithSpecialCharacters() {
		// Arrange
		InvocationContext invocationContext = buildDefaultContext();
		String specialBranch = "branch-with_special.chars/test";
		// Act
		invocationContext.branch(specialBranch);
		// Assert
		Optional<String> branch = invocationContext.branch();
		assertTrue(branch.isPresent(), "Branch should be present");
		assertEquals(specialBranch, branch.get(), "Branch should preserve special characters");
	}

	@Test
	@Tag("boundary")
	void branchWithVeryLongString() {
		// Arrange
		InvocationContext invocationContext = buildDefaultContext();
		String longBranch = "a".repeat(1000);
		// Act
		invocationContext.branch(longBranch);
		// Assert
		Optional<String> branch = invocationContext.branch();
		assertTrue(branch.isPresent(), "Branch should be present");
		assertEquals(longBranch, branch.get(), "Branch should store long strings correctly");
		assertEquals(1000, branch.get().length(), "Branch length should be 1000");
	}

	@Test
	@Tag("boundary")
	void branchWithSingleCharacter() {
		// Arrange
		InvocationContext invocationContext = buildDefaultContext();
		// Act
		invocationContext.branch("a");
		// Assert
		Optional<String> branch = invocationContext.branch();
		assertTrue(branch.isPresent(), "Branch should be present");
		assertEquals("a", branch.get(), "Branch should store single character");
	}

	@Test
	@Tag("valid")
	void branchGetReturnsOptionalNotNull() {
		// Arrange
		InvocationContext invocationContext = buildDefaultContext();
		// Act
		invocationContext.branch("test-branch");
		// Assert
		assertNotNull(invocationContext.branch(), "Branch Optional itself should never be null");
	}

	@Test
	@Tag("valid")
	void branchGetReturnsOptionalEmptyWhenNotSet() {
		// Arrange
		InvocationContext invocationContext = buildDefaultContext();
		// Assert
		Optional<String> branch = invocationContext.branch();
		assertNotNull(branch, "Branch Optional should not be null even when not set");
		assertFalse(branch.isPresent(), "Branch should be empty when not explicitly set");
	}

	@Test
	@Tag("valid")
	void branchSetMultipleTimesRetainsLastValue() {
		// Arrange
		InvocationContext invocationContext = buildDefaultContext();
		// Act
		invocationContext.branch("first-branch");
		invocationContext.branch("second-branch");
		invocationContext.branch("third-branch");
		// Assert
		Optional<String> branch = invocationContext.branch();
		assertTrue(branch.isPresent(), "Branch should be present");
		assertEquals("third-branch", branch.get(), "Branch should retain the last set value");
	}

	@Test
	@Tag("valid")
	void branchSetThenNullThenNewValue() {
		// Arrange
		InvocationContext invocationContext = buildDefaultContext();
		// Act
		invocationContext.branch("first-branch");
		invocationContext.branch(null);
		invocationContext.branch("new-branch");
		// Assert
		Optional<String> branch = invocationContext.branch();
		assertTrue(branch.isPresent(), "Branch should be present");
		assertEquals("new-branch", branch.get(), "Branch should have the latest non-null value");
	}

	@Test
	@Tag("integration")
	void branchIsPreservedAfterCopyOf() {
		// Arrange
		InvocationContext original = buildDefaultContext();
		original.branch("original-branch");
		// Act
		InvocationContext copy = InvocationContext.copyOf(original);
		// Assert
		assertTrue(copy.branch().isPresent(), "Copied context should have branch present");
		assertEquals("original-branch", copy.branch().get(), "Copied context should preserve branch value");
	}

	@Test
	@Tag("integration")
	void branchChangeInCopyDoesNotAffectOriginal() {
		// Arrange
		InvocationContext original = buildDefaultContext();
		original.branch("original-branch");
		InvocationContext copy = InvocationContext.copyOf(original);
		// Act
		copy.branch("modified-branch");
		// Assert
		assertTrue(original.branch().isPresent(), "Original branch should still be present");
		assertEquals("original-branch", original.branch().get(), "Original branch should not be modified");
		assertEquals("modified-branch", copy.branch().get(), "Copy branch should reflect updated value");
	}

	@Test
	@Tag("integration")
	void branchNullPreservedAfterCopyOf() {
		// Arrange
		InvocationContext original = buildDefaultContext();
		original.branch(null);
		// Act
		InvocationContext copy = InvocationContext.copyOf(original);
		// Assert
		assertFalse(copy.branch().isPresent(), "Copied context with null branch should have empty Optional");
	}

	@Test
	@Tag("valid")
	void branchBuilderSetAndThenBranchMethodOverrides() {
		// Arrange
		InvocationContext invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(defaultRunConfig)
			.branch("builder-branch")
			.build();
		// Act
		invocationContext.branch("method-branch");
		// Assert
		Optional<String> branch = invocationContext.branch();
		assertTrue(branch.isPresent(), "Branch should be present");
		assertEquals("method-branch", branch.get(), "Branch set via method should override builder branch");
	}

	@Test
	@Tag("valid")
	void branchReturnsOptionalOfNullableSemantics() {
		// Arrange
		InvocationContext invocationContext = buildDefaultContext();
		// Act - set non-null, then verify Optional semantics
		invocationContext.branch("some-branch");
		Optional<String> presentBranch = invocationContext.branch();
		// Act - set null, then verify Optional.empty semantics
		invocationContext.branch(null);
		Optional<String> emptyBranch = invocationContext.branch();
		// Assert
		assertTrue(presentBranch.isPresent(), "Non-null branch should produce present Optional");
		assertFalse(emptyBranch.isPresent(), "Null branch should produce empty Optional");
	}

	@Test
	@Tag("valid")
	void branchWithWhitespaceString() {
		// Arrange
		InvocationContext invocationContext = buildDefaultContext();
		// Act
		invocationContext.branch("   ");
		// Assert
		Optional<String> branch = invocationContext.branch();
		assertTrue(branch.isPresent(), "Branch should be present for whitespace string");
		assertEquals("   ", branch.get(), "Branch should preserve whitespace string as-is");
	}

	@Test
	@Tag("valid")
	void branchWithNumericString() {
		// Arrange
		InvocationContext invocationContext = buildDefaultContext();
		// Act
		invocationContext.branch("12345");
		// Assert
		Optional<String> branch = invocationContext.branch();
		assertTrue(branch.isPresent(), "Branch should be present for numeric string");
		assertEquals("12345", branch.get(), "Branch should store numeric string correctly");
	}

}