/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=activeStreamingTools_c4cc5030aa
ROOST_METHOD_SIG_HASH=activeStreamingTools_398f84db97

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/june-java-unit/1782282926/source/adk-java/core/src/test/java/com/google/adk/agents/InvocationContextTest.java
Tests:
    "@Test
public void testCopyOf() {
    InvocationContext originalContext = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    originalContext.activeStreamingTools().putAll(activeStreamingTools);
    InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
    assertThat(copiedContext).isNotNull();
    assertThat(copiedContext).isNotSameInstanceAs(originalContext);
    assertThat(copiedContext.sessionService()).isEqualTo(originalContext.sessionService());
    assertThat(copiedContext.artifactService()).isEqualTo(originalContext.artifactService());
    assertThat(copiedContext.memoryService()).isEqualTo(originalContext.memoryService());
    assertThat(copiedContext.liveRequestQueue()).isEqualTo(originalContext.liveRequestQueue());
    assertThat(copiedContext.invocationId()).isEqualTo(originalContext.invocationId());
    assertThat(copiedContext.agent()).isEqualTo(originalContext.agent());
    assertThat(copiedContext.session()).isEqualTo(originalContext.session());
    assertThat(copiedContext.userContent()).isEqualTo(originalContext.userContent());
    assertThat(copiedContext.runConfig()).isEqualTo(originalContext.runConfig());
    assertThat(copiedContext.endInvocation()).isEqualTo(originalContext.endInvocation());
    assertThat(copiedContext.activeStreamingTools()).isEqualTo(originalContext.activeStreamingTools());
}
"Scenario 1: Return Empty Map When No Active Streaming Tools Have Been Added

Details:
  TestName: activeStreamingToolsReturnsEmptyMapOnNewContext
  Description: Verifies that a newly built InvocationContext returns an empty (but non-null) map
               from activeStreamingTools() when no tools have been added to it. This confirms
               that the underlying ConcurrentHashMap is initialized as empty by default.

Execution:
  Arrange: Build an InvocationContext using InvocationContext.builder() with the required fields
           (sessionService, artifactService, memoryService, pluginManager, invocationId, agent,
           session, userContent, runConfig, endInvocation) without adding any entries to
           activeStreamingTools.
  Act: Call activeStreamingTools() on the newly created InvocationContext instance.
  Assert: Assert that the returned map is not null.
          Assert that the returned map is empty (size == 0).

Validation:
  The assertion confirms that the ConcurrentHashMap backing activeStreamingTools is properly
  initialized at construction time and defaults to an empty state. This is critical for ensuring
  that code consuming the map does not encounter a NullPointerException and can safely check
  for active streaming tools without error on a fresh invocation context.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.genai.types.Content;
import java.util.Map;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
class InvocationContextActiveStreamingToolsTest {

	@Mock
	private BaseSessionService mockSessionService;

	@Mock
	private BaseArtifactService mockArtifactService;

	@Mock
	private BaseMemoryService mockMemoryService;

	@Mock
	private PluginManager mockPluginManager;

	@Mock
	private Session mockSession;

	@Mock
	private BaseAgent mockAgent;

	@Mock
	private RunConfig mockRunConfig;

	@Mock
	private ActiveStreamingTool mockActiveTool1;

	@Mock
	private ActiveStreamingTool mockActiveTool2;

	private InvocationContext invocationContext;

	@BeforeEach
  void setUp() {
    when(mockSession.appName()).thenReturn("testApp");
    when(mockSession.userId()).thenReturn("testUser");
    invocationContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .memoryService(mockMemoryService)
            .pluginManager(mockPluginManager)
            .invocationId("test-invocation-id")
            .agent(mockAgent)
            .session(mockSession)
            .userContent(Optional.empty())
            .runConfig(mockRunConfig)
            .endInvocation(false)
            .build();
  }

	@Test
	@Tag("valid")
	void activeStreamingToolsReturnsEmptyMapOnNewContext() {
		// Arrange
		InvocationContext freshContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.pluginManager(mockPluginManager)
			.invocationId("fresh-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.endInvocation(false)
			.build();
		// Act
		Map<String, ActiveStreamingTool> result = freshContext.activeStreamingTools();
		// Assert
		assertNotNull(result, "activeStreamingTools map should not be null");
		assertTrue(result.isEmpty(), "activeStreamingTools map should be empty on a new context");
		assertEquals(0, result.size(), "activeStreamingTools map size should be 0");
	}

	@Test
	@Tag("valid")
	void activeStreamingToolsReturnsNonNullMap() {
		// Act
		Map<String, ActiveStreamingTool> result = invocationContext.activeStreamingTools();
		// Assert
		assertNotNull(result, "activeStreamingTools() should never return null");
	}

	@Test
	@Tag("valid")
	void activeStreamingToolsReturnsMapWithAddedEntries() {
		// Arrange
		invocationContext.activeStreamingTools().put("tool1", mockActiveTool1);
		// Act
		Map<String, ActiveStreamingTool> result = invocationContext.activeStreamingTools();
		// Assert
		assertNotNull(result);
		assertEquals(1, result.size());
		assertTrue(result.containsKey("tool1"));
		assertEquals(mockActiveTool1, result.get("tool1"));
	}

	@Test
	@Tag("valid")
	void activeStreamingToolsReturnsLiveReferenceAllowingMutations() {
		// Arrange
		Map<String, ActiveStreamingTool> result = invocationContext.activeStreamingTools();
		assertTrue(result.isEmpty());
		// Act - mutate through the returned reference
		result.put("tool1", mockActiveTool1);
		// Assert - re-fetch and check mutation is reflected
		Map<String, ActiveStreamingTool> resultAfterMutation = invocationContext.activeStreamingTools();
		assertEquals(1, resultAfterMutation.size());
		assertTrue(resultAfterMutation.containsKey("tool1"));
	}

	@Test
	@Tag("valid")
	void activeStreamingToolsReturnsSameReferenceOnMultipleCalls() {
		// Act
		Map<String, ActiveStreamingTool> firstCall = invocationContext.activeStreamingTools();
		Map<String, ActiveStreamingTool> secondCall = invocationContext.activeStreamingTools();
		// Assert
		assertSame(firstCall, secondCall,
				"Multiple calls to activeStreamingTools() should return the same map instance");
	}

	@Test
	@Tag("valid")
	void activeStreamingToolsSupportsMultipleEntries() {
		// Arrange
		invocationContext.activeStreamingTools().put("tool1", mockActiveTool1);
		invocationContext.activeStreamingTools().put("tool2", mockActiveTool2);
		// Act
		Map<String, ActiveStreamingTool> result = invocationContext.activeStreamingTools();
		// Assert
		assertEquals(2, result.size());
		assertTrue(result.containsKey("tool1"));
		assertTrue(result.containsKey("tool2"));
		assertEquals(mockActiveTool1, result.get("tool1"));
		assertEquals(mockActiveTool2, result.get("tool2"));
	}

	@Test
	@Tag("valid")
	void activeStreamingToolsSupportsRemoveEntry() {
		// Arrange
		invocationContext.activeStreamingTools().put("tool1", mockActiveTool1);
		invocationContext.activeStreamingTools().put("tool2", mockActiveTool2);
		assertEquals(2, invocationContext.activeStreamingTools().size());
		// Act
		invocationContext.activeStreamingTools().remove("tool1");
		// Assert
		Map<String, ActiveStreamingTool> result = invocationContext.activeStreamingTools();
		assertEquals(1, result.size());
		assertFalse(result.containsKey("tool1"));
		assertTrue(result.containsKey("tool2"));
	}

	@Test
	@Tag("valid")
	void activeStreamingToolsIsCopiedCorrectlyViaCopyOf() {
		// Arrange
		invocationContext.activeStreamingTools().put("tool1", mockActiveTool1);
		// Act
		InvocationContext copiedContext = InvocationContext.copyOf(invocationContext);
		Map<String, ActiveStreamingTool> copiedTools = copiedContext.activeStreamingTools();
		// Assert
		assertNotNull(copiedTools);
		assertEquals(1, copiedTools.size());
		assertTrue(copiedTools.containsKey("tool1"));
		assertEquals(mockActiveTool1, copiedTools.get("tool1"));
	}

	@Test
	@Tag("valid")
	void activeStreamingToolsInCopiedContextIsIndependentFromOriginal() {
		// Arrange
		invocationContext.activeStreamingTools().put("tool1", mockActiveTool1);
		InvocationContext copiedContext = InvocationContext.copyOf(invocationContext);
		// Act - mutate the copy's map
		copiedContext.activeStreamingTools().put("tool2", mockActiveTool2);
		// Assert - original should not have tool2
		Map<String, ActiveStreamingTool> originalTools = invocationContext.activeStreamingTools();
		Map<String, ActiveStreamingTool> copiedTools = copiedContext.activeStreamingTools();
		assertEquals(1, originalTools.size());
		assertFalse(originalTools.containsKey("tool2"));
		assertEquals(2, copiedTools.size());
		assertTrue(copiedTools.containsKey("tool1"));
		assertTrue(copiedTools.containsKey("tool2"));
	}

	@Test
	@Tag("boundary")
	void activeStreamingToolsOnContextWithEmptyCopyOfOriginalEmpty() {
		// Arrange - original has no streaming tools
		InvocationContext originalContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("original-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		// Act
		InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
		Map<String, ActiveStreamingTool> result = copiedContext.activeStreamingTools();
		// Assert
		assertNotNull(result);
		assertTrue(result.isEmpty());
	}

	@Test
	@Tag("boundary")
	void activeStreamingToolsMapSupportsOverwriteOfExistingKey() {
		// Arrange
		invocationContext.activeStreamingTools().put("tool1", mockActiveTool1);
		assertEquals(mockActiveTool1, invocationContext.activeStreamingTools().get("tool1"));
		// Act - overwrite the key with a new tool
		invocationContext.activeStreamingTools().put("tool1", mockActiveTool2);
		// Assert
		Map<String, ActiveStreamingTool> result = invocationContext.activeStreamingTools();
		assertEquals(1, result.size());
		assertEquals(mockActiveTool2, result.get("tool1"), "Overwritten key should map to the new value");
	}

	@Test
	@Tag("boundary")
	void activeStreamingToolsMapClearsAllEntries() {
		// Arrange
		invocationContext.activeStreamingTools().put("tool1", mockActiveTool1);
		invocationContext.activeStreamingTools().put("tool2", mockActiveTool2);
		assertEquals(2, invocationContext.activeStreamingTools().size());
		// Act
		invocationContext.activeStreamingTools().clear();
		// Assert
		Map<String, ActiveStreamingTool> result = invocationContext.activeStreamingTools();
		assertNotNull(result);
		assertTrue(result.isEmpty());
		assertEquals(0, result.size());
	}

	@Test
	@Tag("valid")
	void activeStreamingToolsReturnedMapContainsKeyCheck() {
		// Arrange
		invocationContext.activeStreamingTools().put("existingTool", mockActiveTool1);
		// Act
		Map<String, ActiveStreamingTool> result = invocationContext.activeStreamingTools();
		// Assert
		assertTrue(result.containsKey("existingTool"));
		assertFalse(result.containsKey("nonExistentTool"));
	}

	@Test
	@Tag("valid")
	void activeStreamingToolsMapContainsValueCheck() {
		// Arrange
		invocationContext.activeStreamingTools().put("tool1", mockActiveTool1);
		// Act
		Map<String, ActiveStreamingTool> result = invocationContext.activeStreamingTools();
		// Assert
		assertTrue(result.containsValue(mockActiveTool1));
		assertFalse(result.containsValue(mockActiveTool2));
	}

	@Test
	@Tag("valid")
	void activeStreamingToolsWithLiveRequestQueueContext() {
		// Arrange
		LiveRequestQueue liveRequestQueue = new LiveRequestQueue();
		InvocationContext liveContext = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, liveRequestQueue, mockRunConfig);
		// Act
		Map<String, ActiveStreamingTool> result = liveContext.activeStreamingTools();
		// Assert
		assertNotNull(result);
		assertTrue(result.isEmpty());
	}

	@Test
	@Tag("valid")
	void activeStreamingToolsWithCreateStaticMethod() {
		// Arrange
		Content userContent = Content.fromParts();
		InvocationContext createdContext = InvocationContext.create(mockSessionService, mockArtifactService,
				"static-create-invocation-id", mockAgent, mockSession, userContent, mockRunConfig);
		// Act
		Map<String, ActiveStreamingTool> result = createdContext.activeStreamingTools();
		// Assert
		assertNotNull(result);
		assertTrue(result.isEmpty());
		assertEquals(0, result.size());
	}

	@Test
	@Tag("integration")
	void activeStreamingToolsIntegrationWithCopyAndMutate() {
		// Arrange - setup original context with tools
		invocationContext.activeStreamingTools().put("tool1", mockActiveTool1);
		invocationContext.activeStreamingTools().put("tool2", mockActiveTool2);
		// Act - copy the context
		InvocationContext copiedContext = InvocationContext.copyOf(invocationContext);
		// Mutate original after copying
		invocationContext.activeStreamingTools().remove("tool1");
		// Assert original reflects mutation
		assertEquals(1, invocationContext.activeStreamingTools().size());
		assertFalse(invocationContext.activeStreamingTools().containsKey("tool1"));
		// Assert copy is unchanged from when it was copied
		assertEquals(2, copiedContext.activeStreamingTools().size());
		assertTrue(copiedContext.activeStreamingTools().containsKey("tool1"));
		assertTrue(copiedContext.activeStreamingTools().containsKey("tool2"));
	}

	@Test
	@Tag("integration")
	void activeStreamingToolsEqualsConsidersMapContents() {
		// Arrange
		InvocationContext context1 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("same-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		InvocationContext context2 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("same-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		// Act - both contexts have empty activeStreamingTools initially
		boolean equalsBeforeModification = context1.equals(context2);
		// Modify context1's activeStreamingTools
		context1.activeStreamingTools().put("tool1", mockActiveTool1);
		boolean equalsAfterModification = context1.equals(context2);
		// Assert
		assertTrue(equalsBeforeModification, "Contexts with empty streaming tools maps should be equal");
		assertFalse(equalsAfterModification, "Contexts with different streaming tools maps should not be equal");
	}

}
