/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=shouldPauseInvocation_16da4698a8
ROOST_METHOD_SIG_HASH=shouldPauseInvocation_4abf425c41

Scenario 1: Non-Resumable Invocation Context Always Returns False

Details:
  TestName: shouldReturnFalseWhenInvocationContextIsNotResumable
  Description: Verifies that when the InvocationContext is configured with a non-resumable ResumabilityConfig,
               the method returns false immediately, regardless of whether the event contains long-running tool IDs
               or matching function calls. This tests the first guard condition in the method.
Execution:
  Arrange:
    - Create a mock Event object.
    - Create a ResumabilityConfig configured so that isResumable() returns false.
    - Build an InvocationContext using InvocationContext.builder() with the non-resumable ResumabilityConfig.
    - Configure the mock Event to return an Optional containing a non-empty ImmutableSet of long-running tool IDs.
    - Configure the mock Event to return a list with at least one FunctionCall whose id matches one of the long-running tool IDs.
  Act:
    - Call invocationContext.shouldPauseInvocation(event).
  Assert:
    - Assert that the returned value is false using assertFalse().
Validation:
  This assertion confirms that the non-resumable guard is the first and highest priority check.
  When the invocation is not resumable, pausing has no meaning, so the method correctly short-circuits
  and returns false. This is critical to prevent incorrect pause states in non-resumable invocations.

*/

// ********RoostGPT********

```java
package com.google.adk.agents;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;
import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.events.Event;
import com.google.adk.flows.llmflows.ResumabilityConfig;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableSet;
import com.google.genai.types.Content;
import com.google.genai.types.FunctionCall;
import java.util.Optional;
import java.util.Set;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.junit.jupiter.api.*;
import com.google.adk.models.LlmCallsLimitExceededException;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import com.google.errorprone.annotations.InlineMe;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import javax.annotation.Nullable;

@ExtendWith(MockitoExtension.class)
public class InvocationContextShouldPauseInvocationTest {
    @Mock
    private BaseSessionService mockSessionService;
    @Mock
    private BaseArtifactService mockArtifactService;
    @Mock
    private BaseMemoryService mockMemoryService;
    @Mock
    private PluginManager mockPluginManager;
    @Mock
    private BaseAgent mockAgent;
    @Mock
    private Session mockSession;
    @Mock
    private ResumabilityConfig mockResumabilityConfig;
    @Mock
    private RunConfig mockRunConfig;
    @Mock
    private Event mockEvent;
    @BeforeEach
    void setUp() {
        when(mockSession.appName()).thenReturn("testApp");
        when(mockSession.userId()).thenReturn("testUser");
        when(mockSession.id()).thenReturn("testSession");
    }
    private InvocationContext buildInvocationContext(ResumabilityConfig resumabilityConfig) {
        return InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .memoryService(mockMemoryService)
                .pluginManager(mockPluginManager)
                .invocationId("test-invocation-id")
                .agent(mockAgent)
                .session(mockSession)
                .userContent(Optional.empty())
                .runConfig(mockRunConfig)
                .resumabilityConfig(resumabilityConfig)
                .build();
    }
    @Test
    @Tag("invalid")
    void shouldReturnFalseWhenInvocationContextIsNotResumable() {
        // Arrange
        when(mockResumabilityConfig.isResumable()).thenReturn(false);
        InvocationContext invocationContext = buildInvocationContext(mockResumabilityConfig);
        Set<String> longRunningToolIds = ImmutableSet.of("tool-id-1", "tool-id-2");
        when(mockEvent.longRunningToolIds()).thenReturn(Optional.of(longRunningToolIds));
        FunctionCall mockFunctionCall = mock(FunctionCall.class);
        when(mockFunctionCall.id()).thenReturn(Optional.of("tool-id-1"));
        when(mockEvent.functionCalls()).thenReturn(ImmutableList.of(mockFunctionCall));
        // Act
        boolean result = invocationContext.shouldPauseInvocation(mockEvent);
        // Assert
        assertFalse(result, "Expected shouldPauseInvocation to return false when the context is not resumable");
    }
    @Test
    @Tag("invalid")
    void shouldReturnFalseWhenLongRunningToolIdsIsEmpty() {
        // Arrange
        when(mockResumabilityConfig.isResumable()).thenReturn(true);
        InvocationContext invocationContext = buildInvocationContext(mockResumabilityConfig);
        when(mockEvent.longRunningToolIds()).thenReturn(Optional.of(ImmutableSet.of()));
        // Act
        boolean result = invocationContext.shouldPauseInvocation(mockEvent);
        // Assert
        assertFalse(result, "Expected shouldPauseInvocation to return false when longRunningToolIds is empty");
    }
    @Test
    @Tag("invalid")
    void shouldReturnFalseWhenLongRunningToolIdsIsAbsent() {
        // Arrange
        when(mockResumabilityConfig.isResumable()).thenReturn(true);
        InvocationContext invocationContext = buildInvocationContext(mockResumabilityConfig);
        when(mockEvent.longRunningToolIds()).thenReturn(Optional.empty());
        // Act
        boolean result = invocationContext.shouldPauseInvocation(mockEvent);
        // Assert
        assertFalse(result, "Expected shouldPauseInvocation to return false when longRunningToolIds is absent");
    }
    @Test
    @Tag("valid")
    void shouldReturnTrueWhenResumableAndFunctionCallIdMatchesLongRunningToolId() {
        // Arrange
        when(mockResumabilityConfig.isResumable()).thenReturn(true);
        InvocationContext invocationContext = buildInvocationContext(mockResumabilityConfig);
        String matchingToolId = "long-running-tool-id";
        Set<String> longRunningToolIds = ImmutableSet.of(matchingToolId);
        when(mockEvent.longRunningToolIds()).thenReturn(Optional.of(longRunningToolIds));
        FunctionCall mockFunctionCall = mock(FunctionCall.class);
        when(mockFunctionCall.id()).thenReturn(Optional.of(matchingToolId));
        when(mockEvent.functionCalls()).thenReturn(ImmutableList.of(mockFunctionCall));
        // Act
        boolean result = invocationContext.shouldPauseInvocation(mockEvent);
        // Assert
        assertTrue(result, "Expected shouldPauseInvocation to return true when function call ID matches a long-running tool ID");
    }
    @Test
    @Tag("invalid")
    void shouldReturnFalseWhenNoFunctionCallIdMatchesLongRunningToolId() {
        // Arrange
        when(mockResumabilityConfig.isResumable()).thenReturn(true);
        InvocationContext invocationContext = buildInvocationContext(mockResumabilityConfig);
        Set<String> longRunningToolIds = ImmutableSet.of("long-running-tool-id");
        when(mockEvent.longRunningToolIds()).thenReturn(Optional.of(longRunningToolIds));
        FunctionCall mockFunctionCall = mock(FunctionCall.class);
        when(mockFunctionCall.id()).thenReturn(Optional.of("non-matching-tool-id"));
        when(mockEvent.functionCalls()).thenReturn(ImmutableList.of(mockFunctionCall));
        // Act
        boolean result = invocationContext.shouldPauseInvocation(mockEvent);
        // Assert
        assertFalse(result, "Expected shouldPauseInvocation to return false when no function call ID matches a long-running tool ID");
    }
    @Test
    @Tag("invalid")
    void shouldReturnFalseWhenFunctionCallsListIsEmpty() {
        // Arrange
        when(mockResumabilityConfig.isResumable()).thenReturn(true);
        InvocationContext invocationContext = buildInvocationContext(mockResumabilityConfig);
        Set<String> longRunningToolIds = ImmutableSet.of("long-running-tool-id");
        when(mockEvent.longRunningToolIds()).thenReturn(Optional.of(longRunningToolIds));
        when(mockEvent.functionCalls()).thenReturn(ImmutableList.of());
        // Act
        boolean result = invocationContext.shouldPauseInvocation(mockEvent);
        // Assert
        assertFalse(result, "Expected shouldPauseInvocation to return false when function calls list is empty");
    }
    @Test
    @Tag("invalid")
    void shouldReturnFalseWhenFunctionCallHasNoId() {
        // Arrange
        when(mockResumabilityConfig.isResumable()).thenReturn(true);
        InvocationContext invocationContext = buildInvocationContext(mockResumabilityConfig);
        Set<String> longRunningToolIds = ImmutableSet.of("long-running-tool-id");
        when(mockEvent.longRunningToolIds()).thenReturn(Optional.of(longRunningToolIds));
        FunctionCall mockFunctionCall = mock(FunctionCall.class);
        when(mockFunctionCall.id()).thenReturn(Optional.empty());
        when(mockEvent.functionCalls()).thenReturn(ImmutableList.of(mockFunctionCall));
        // Act
        boolean result = invocationContext.shouldPauseInvocation(mockEvent);
        // Assert
        assertFalse(result, "Expected shouldPauseInvocation to return false when function call has no ID");
    }
    @Test
    @Tag("valid")
    void shouldReturnTrueWhenOnlyOneFunctionCallIdMatchesAmongMultiple() {
        // Arrange
        when(mockResumabilityConfig.isResumable()).thenReturn(true);
        InvocationContext invocationContext = buildInvocationContext(mockResumabilityConfig);
        String matchingToolId = "long-running-tool-id";
        Set<String> longRunningToolIds = ImmutableSet.of(matchingToolId);
        when(mockEvent.longRunningToolIds()).thenReturn(Optional.of(longRunningToolIds));
        FunctionCall nonMatchingCall = mock(FunctionCall.class);
        when(nonMatchingCall.id()).thenReturn(Optional.of("non-matching-id"));
        FunctionCall matchingCall = mock(FunctionCall.class);
        when(matchingCall.id()).thenReturn(Optional.of(matchingToolId));
        when(mockEvent.functionCalls()).thenReturn(ImmutableList.of(nonMatchingCall, matchingCall));
        // Act
        boolean result = invocationContext.shouldPauseInvocation(mockEvent);
        // Assert
        assertTrue(result, "Expected shouldPauseInvocation to return true when at least one function call ID matches a long-running tool ID");
    }
    @Test
    @Tag("boundary")
    void shouldReturnFalseWhenNonResumableEvenIfAllConditionsWouldOtherwiseMatch() {
        // Arrange
        when(mockResumabilityConfig.isResumable()).thenReturn(false);
        InvocationContext invocationContext = buildInvocationContext(mockResumabilityConfig);
        // Even though we set up matching long running tools and function calls, it should return false
        // because isResumable() is false. We don't even stub the event in this case to
        // verify the short circuit.
        // Act
        boolean result = invocationContext.shouldPauseInvocation(mockEvent);
        // Assert
        assertFalse(result, "Expected shouldPauseInvocation to return false for a non-resumable context, regardless of event content");
    }
    @Test
    @Tag("valid")
    void shouldReturnTrueWhenMultipleLongRunningToolIdsAndOneFunctionCallMatches() {
        // Arrange
        when(mockResumabilityConfig.isResumable()).thenReturn(true);
        InvocationContext invocationContext = buildInvocationContext(mockResumabilityConfig);
        String matchingToolId = "tool-id-2";
        Set<String> longRunningToolIds = ImmutableSet.of("tool-id-1", matchingToolId, "tool-id-3");
        when(mockEvent.longRunningToolIds()).thenReturn(Optional.of(longRunningToolIds));
        FunctionCall mockFunctionCall = mock(FunctionCall.class);
        when(mockFunctionCall.id()).thenReturn(Optional.of(matchingToolId));
        when(mockEvent.functionCalls()).thenReturn(ImmutableList.of(mockFunctionCall));
        // Act
        boolean result = invocationContext.shouldPauseInvocation(mockEvent);
        // Assert
        assertTrue(result, "Expected shouldPauseInvocation to return true when function call ID matches one of multiple long-running tool IDs");
    }
    @Test
    @Tag("boundary")
    void shouldReturnFalseWhenLongRunningToolIdsExistsButAllFunctionCallsHaveNoId() {
        // Arrange
        when(mockResumabilityConfig.isResumable()).thenReturn(true);
        InvocationContext invocationContext = buildInvocationContext(mockResumabilityConfig);
        Set<String> longRunningToolIds = ImmutableSet.of("tool-id-1");
        when(mockEvent.longRunningToolIds()).thenReturn(Optional.of(longRunningToolIds));
        FunctionCall callWithNoId1 = mock(FunctionCall.class);
        when(callWithNoId1.id()).thenReturn(Optional.empty());
        FunctionCall callWithNoId2 = mock(FunctionCall.class);
        when(callWithNoId2.id()).thenReturn(Optional.empty());
        when(mockEvent.functionCalls()).thenReturn(ImmutableList.of(callWithNoId1, callWithNoId2));
        // Act
        boolean result = invocationContext.shouldPauseInvocation(mockEvent);
        // Assert
        assertFalse(result, "Expected shouldPauseInvocation to return false when all function calls have no ID");
    }
    @Test
    @Tag("boundary")
    void shouldReturnFalseWhenAllFunctionCallsNonMatchingAndNoIdMixed() {
        // Arrange
        when(mockResumabilityConfig.isResumable()).thenReturn(true);
        InvocationContext invocationContext = buildInvocationContext(mockResumabilityConfig);
        Set<String> longRunningToolIds = ImmutableSet.of("tool-id-1");
        when(mockEvent.longRunningToolIds()).thenReturn(Optional.of(longRunningToolIds));
        FunctionCall callWithNoId = mock(FunctionCall.class);
        when(callWithNoId.id()).thenReturn(Optional.empty());
        FunctionCall callWithNonMatchingId = mock(FunctionCall.class);
        when(callWithNonMatchingId.id()).thenReturn(Optional.of("tool-id-99"));
        when(mockEvent.functionCalls()).thenReturn(ImmutableList.of(callWithNoId, callWithNonMatchingId));
        // Act
        boolean result = invocationContext.shouldPauseInvocation(mockEvent);
        // Assert
        assertFalse(result, "Expected shouldPauseInvocation to return false when no function call ID matches");
    }
    @Test
    @Tag("integration")
    void shouldCorrectlyHandleResumableContextWithMatchingFunctionCall() {
        // Arrange
        when(mockResumabilityConfig.isResumable()).thenReturn(true);
        InvocationContext invocationContext = buildInvocationContext(mockResumabilityConfig);
        String toolId = "integration-tool-id";
        Set<String> longRunningToolIds = ImmutableSet.of(toolId);
        when(mockEvent.longRunningToolIds()).thenReturn(Optional.of(longRunningToolIds));
        FunctionCall matchingFunctionCall = mock(FunctionCall.class);
        when(matchingFunctionCall.id()).thenReturn(Optional.of(toolId));
        when(mockEvent.functionCalls()).thenReturn(ImmutableList.of(matchingFunctionCall));
        // Act
        boolean result = invocationContext.shouldPauseInvocation(mock