/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=sessionService_c04b1de6f8
ROOST_METHOD_SIG_HASH=sessionService_1fa67a6550

Scenario 1: Verify that sessionService() returns the exact instance set via the builder

Details:
  TestName: sessionServiceReturnsInstanceSetViaBuilder
  Description: Verifies that the sessionService() method returns the exact same BaseSessionService
               instance that was provided during construction of InvocationContext via the Builder.

Execution:
  Arrange: Create a mock or concrete implementation of BaseSessionService. Use InvocationContext.builder()
           and set the mocked sessionService, along with any other minimally required fields
           (such as session, agent, etc.) to construct a valid InvocationContext.
  Act: Call invocationContext.sessionService() on the constructed instance.
  Assert: Use assertSame() to verify that the returned object is the exact same instance as the one
          passed to the builder.

Validation:
  This assertion confirms that the method performs a simple field retrieval without modification,
  wrapping, or copying. Since sessionService is declared as a private final field, it must be
  initialized once and returned as-is. This test is critical for ensuring that the session service
  dependency is correctly wired and accessible throughout the invocation lifecycle.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.flows.llmflows.ResumabilityConfig;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.genai.types.Content;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class InvocationContextSessionServiceTest {
  @Mock private BaseSessionService mockSessionService;
  @Mock private BaseArtifactService mockArtifactService;
  @Mock private BaseMemoryService mockMemoryService;
  @Mock private PluginManager mockPluginManager;
  @Mock private BaseAgent mockAgent;
  @Mock private Session mockSession;
  @Mock private RunConfig mockRunConfig;
  @Mock private ResumabilityConfig mockResumabilityConfig;

  @BeforeEach
  void setUp() {
    when(mockSession.appName()).thenReturn("testApp");
    when(mockSession.userId()).thenReturn("testUser");
    when(mockSession.id()).thenReturn("testSessionId");
    when(mockAgent.name()).thenReturn("testAgent");
  }

  private InvocationContext buildBasicContext(BaseSessionService sessionService) {
    return InvocationContext.builder()
        .sessionService(sessionService)
        .artifactService(mockArtifactService)
        .agent(mockAgent)
        .session(mockSession)
        .invocationId("test-invocation-id")
        .runConfig(mockRunConfig)
        .build();
  }

  @Test
  @Tag("valid")
  void sessionServiceReturnsInstanceSetViaBuilder() {
    // Arrange
    InvocationContext context = buildBasicContext(mockSessionService);
    // Act
    BaseSessionService result = context.sessionService();
    // Assert
    assertSame(
        mockSessionService,
        result,
        "sessionService() should return the exact same instance set via the builder");
  }

  @Test
  @Tag("valid")
  void sessionServiceReturnsCorrectInstanceWhenMultipleServicesExist() {
    // Arrange
    BaseSessionService anotherSessionService = mock(BaseSessionService.class);
    InvocationContext context1 = buildBasicContext(mockSessionService);
    InvocationContext context2 = buildBasicContext(anotherSessionService);
    // Act
    BaseSessionService result1 = context1.sessionService();
    BaseSessionService result2 = context2.sessionService();
    // Assert
    assertSame(
        mockSessionService,
        result1,
        "First context should return the first session service instance");
    assertSame(
        anotherSessionService,
        result2,
        "Second context should return the second session service instance");
    assertNotSame(
        result1,
        result2,
        "Two different contexts should return different session service instances");
  }

  @Test
  @Tag("valid")
  void sessionServiceIsNotNullWhenSetViaBuilder() {
    // Arrange
    InvocationContext context = buildBasicContext(mockSessionService);
    // Act
    BaseSessionService result = context.sessionService();
    // Assert
    assertNotNull(result, "sessionService() should not return null when set via builder");
  }

  @Test
  @Tag("valid")
  void sessionServiceReturnsSameInstanceAfterMultipleCalls() {
    // Arrange
    InvocationContext context = buildBasicContext(mockSessionService);
    // Act
    BaseSessionService firstCall = context.sessionService();
    BaseSessionService secondCall = context.sessionService();
    BaseSessionService thirdCall = context.sessionService();
    // Assert
    assertSame(
        firstCall,
        secondCall,
        "sessionService() should return the same instance on repeated calls");
    assertSame(
        secondCall,
        thirdCall,
        "sessionService() should return the same instance on repeated calls");
    assertSame(mockSessionService, firstCall, "All calls should return the original instance");
  }

  @Test
  @Tag("valid")
  void sessionServiceReturnedViaCreateFactoryMethod() {
    // Arrange
    Content userContent = mock(Content.class);
    InvocationContext context =
        InvocationContext.create(
            mockSessionService,
            mockArtifactService,
            "test-invocation-id",
            mockAgent,
            mockSession,
            userContent,
            mockRunConfig);
    // Act
    BaseSessionService result = context.sessionService();
    // Assert
    assertSame(
        mockSessionService,
        result,
        "sessionService() should return the same instance when created via static factory method");
  }

  @Test
  @Tag("valid")
  void sessionServiceReturnedViaCreateFactoryMethodWithLiveQueue() {
    // Arrange
    LiveRequestQueue liveRequestQueue = new LiveRequestQueue();
    InvocationContext context =
        InvocationContext.create(
            mockSessionService,
            mockArtifactService,
            mockAgent,
            mockSession,
            liveRequestQueue,
            mockRunConfig);
    // Act
    BaseSessionService result = context.sessionService();
    // Assert
    assertSame(
        mockSessionService,
        result,
        "sessionService() should return the same instance when created via live queue factory method");
  }

  @Test
  @Tag("valid")
  void sessionServiceReturnedViaCopyOf() {
    // Arrange
    InvocationContext original = buildBasicContext(mockSessionService);
    InvocationContext copy = InvocationContext.copyOf(original);
    // Act
    BaseSessionService originalResult = original.sessionService();
    BaseSessionService copyResult = copy.sessionService();
    // Assert
    assertSame(
        mockSessionService,
        originalResult,
        "Original context should return the mock session service");
    assertSame(
        mockSessionService,
        copyResult,
        "Copied context should return the same session service instance as original");
    assertSame(
        originalResult,
        copyResult,
        "Both original and copy should share the same session service instance");
  }

  @Test
  @Tag("valid")
  void sessionServiceIsNullWhenNotSet() {
    // Arrange
    InvocationContext context =
        InvocationContext.builder()
            .artifactService(mockArtifactService)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("test-invocation-id")
            .runConfig(mockRunConfig)
            .build();
    // Act
    BaseSessionService result = context.sessionService();
    // Assert
    assertNull(result, "sessionService() should return null when not set via builder");
  }

  @Test
  @Tag("valid")
  void sessionServiceReturnedViaDeprecatedConstructorWithPluginManager() {
    // Arrange
    String invocationId = "test-invocation-id";
    Optional<LiveRequestQueue> liveRequestQueue = Optional.empty();
    Optional<String> branch = Optional.of("testBranch");
    Optional<Content> userContent = Optional.empty();
    @SuppressWarnings("deprecation")
    InvocationContext context =
        new InvocationContext(
            mockSessionService,
            mockArtifactService,
            mockMemoryService,
            mockPluginManager,
            liveRequestQueue,
            branch,
            invocationId,
            mockAgent,
            mockSession,
            userContent,
            mockRunConfig,
            false);
    // Act
    BaseSessionService result = context.sessionService();
    // Assert
    assertSame(
        mockSessionService,
        result,
        "sessionService() should return same instance set via deprecated constructor");
  }

  @Test
  @Tag("valid")
  void sessionServiceReturnedViaDeprecatedConstructorWithoutPluginManager() {
    // Arrange
    String invocationId = "test-invocation-id";
    Optional<LiveRequestQueue> liveRequestQueue = Optional.empty();
    Optional<String> branch = Optional.empty();
    Optional<Content> userContent = Optional.empty();
    @SuppressWarnings("deprecation")
    InvocationContext context =
        new InvocationContext(
            mockSessionService,
            mockArtifactService,
            mockMemoryService,
            liveRequestQueue,
            branch,
            invocationId,
            mockAgent,
            mockSession,
            userContent,
            mockRunConfig,
            false);
    // Act
    BaseSessionService result = context.sessionService();
    // Assert
    assertSame(
        mockSessionService,
        result,
        "sessionService() should return same instance set via deprecated constructor without plugin manager");
  }

  @Test
  @Tag("integration")
  void sessionServiceIsConsistentWithOtherContextProperties() {
    // Arrange
    String invocationId = "integration-invocation-id";
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .memoryService(mockMemoryService)
            .pluginManager(mockPluginManager)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId(invocationId)
            .runConfig(mockRunConfig)
            .build();
    // Act
    BaseSessionService sessionService = context.sessionService();
    BaseArtifactService artifactService = context.artifactService();
    BaseMemoryService memoryService = context.memoryService();
    PluginManager pluginManager = context.pluginManager();
    String returnedInvocationId = context.invocationId();
    // Assert
    assertSame(mockSessionService, sessionService, "Session service should match");
    assertSame(mockArtifactService, artifactService, "Artifact service should match");
    assertSame(mockMemoryService, memoryService, "Memory service should match");
    assertSame(mockPluginManager, pluginManager, "Plugin manager should match");
    assertEquals(invocationId, returnedInvocationId, "Invocation ID should match");
  }

  @Test
  @Tag("integration")
  void sessionServiceAccessibleAfterBuilderModifications() {
    // Arrange
    BaseSessionService anotherSessionService = mock(BaseSessionService.class);
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("test-invocation-id")
            .runConfig(mockRunConfig)
            .build();
    InvocationContext anotherContext =
        InvocationContext.builder()
            .sessionService(anotherSessionService)
            .artifactService(mockArtifactService)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("another-invocation-id")
            .runConfig(mockRunConfig)
            .build();
    // Act & Assert
    assertSame(
        mockSessionService,
        context.sessionService(),
        "First context session service should be original mock");
    assertSame(
        anotherSessionService,
        anotherContext.sessionService(),
        "Second context session service should be another mock");
    assertNotSame(
        context.sessionService(),
        anotherContext.sessionService(),
        "Two different context instances should have different session services");
  }

  @Test
  @Tag("boundary")
  void sessionServiceDoesNotInteractWithSessionWhenAccessed() {
    // Arrange
    InvocationContext context = buildBasicContext(mockSessionService);
    // Act
    context.sessionService();
    // Assert - verify that accessing sessionService does not trigger any interaction with session
    // mock
    verify(mockSession, never()).id();
    verify(mockSession, never()).events();
    verify(mockSession, never()).state();
    assertSame(mockSessionService, context.sessionService());
  }

  @Test
  @Tag("boundary")
  void sessionServiceDoesNotChangeAfterBranchModification() {
    // Arrange
    InvocationContext context = buildBasicContext(mockSessionService);
    BaseSessionService beforeBranchChange = context.sessionService();
    // Act
    context.branch("newBranch");
    BaseSessionService afterBranchChange = context.sessionService();
    // Assert
    assertSame(
        beforeBranchChange,
        afterBranchChange,
        "sessionService() should return same instance after branch modification");
    assertSame(
        mockSessionService,
        afterBranchChange,
        "sessionService() should still return the original mock after branch change");
  }

  @Test
  @Tag("boundary")
  void sessionServiceDoesNotChangeAfterEndInvocationModification() {
    // Arrange
    InvocationContext context = buildBasicContext(mockSessionService);
    BaseSessionService beforeModification = context.sessionService();
    // Act
    context.setEndInvocation(true);
    BaseSessionService afterModification = context.sessionService();
    // Assert
    assertSame(
        beforeModification,
        afterModification,
        "sessionService() should return same instance after endInvocation flag change");
    assertSame(
        mockSessionService,
        afterModification,
        "sessionService() should still return original mock after endInvocation modification");
  }

  @Test
  @Tag("boundary")
  void sessionServiceDoesNotChangeAfterAgentModification() {
    // Arrange
    InvocationContext context = buildBasicContext(mockSessionService);
    BaseSessionService beforeModification = context.sessionService();
    BaseAgent anotherAgent = mock(BaseAgent.class);
    when(anotherAgent.name()).thenReturn("anotherAgent");
    // Act
    context.agent(anotherAgent);
    BaseSessionService afterModification = context.sessionService();
    // Assert
    assertSame(
        beforeModification,
        afterModification,
        "sessionService() should return same instance after agent change");
    assertSame(
        mockSessionService,
        afterModification,
        "sessionService() should still return original mock after agent modification");
  }

  @Test
  @Tag("valid")
  void sessionServiceEqualsCheckForTwoContextsWithSameService() {
    // Arrange
    InvocationContext context1 =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("same-invocation-id")
            .runConfig(mockRunConfig)
            .build();
    InvocationContext context2 =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("same-invocation-id")
            .runConfig(mockRunConfig)
            .build();
    // Act
    BaseSessionService service1 = context1.sessionService();
    BaseSessionService service2 = context2.sessionService();
    // Assert
    assertSame(
        service1,
        service2,
        "Both contexts with same session service should return the identical instance");
  }
}
