/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=builder_2187989d2f
ROOST_METHOD_SIG_HASH=builder_80041265ae

Scenario 1: Verify That builder() Returns a Non-Null Builder Instance

Details:
  TestName: builderReturnsNonNullInstance
  Description: Verifies that the static builder() method returns a non-null instance of InvocationContext.Builder,
               confirming that the factory method is correctly implemented and usable.
Execution:
  Arrange: No special setup is required since builder() is a static factory method with no dependencies.
  Act: Call InvocationContext.builder() and capture the returned object.
  Assert: Use assertNotNull to confirm the returned Builder instance is not null.
Validation:
  The assertion confirms that calling builder() always produces a valid, non-null Builder object.
  This is fundamental to the Builder pattern; if the factory method returned null, all subsequent
  chaining calls would throw a NullPointerException, making the entire construction API unusable.


Scenario 2: Verify That builder() Returns an Instance of the Correct Type

Details:
  TestName: builderReturnsCorrectBuilderType
  Description: Verifies that the object returned by builder() is specifically an instance of
               InvocationContext.Builder, ensuring the return type is correct and not some other class.
Execution:
  Arrange: No special setup is required.
  Act: Call InvocationContext.builder() and capture the returned object.
  Assert: Use assertInstanceOf (or assertTrue with instanceof) to verify the returned object
          is an instance of InvocationContext.Builder.
Validation:
  This test ensures type safety: the method contract states it returns a Builder, so the runtime
  type must match. Returning an incorrect type would break all downstream usages that rely on
  Builder-specific methods.


Scenario 3: Verify That Each Call to builder() Returns a New, Distinct Builder Instance

Details:
  TestName: builderReturnsNewInstanceOnEachCall
  Description: Verifies that multiple successive calls to builder() return different (non-identical)
               Builder instances, confirming that no singleton or cached object is being returned.
Execution:
  Arrange: No special setup is required.
  Act: Call InvocationContext.builder() twice, capturing the result of each call as builder1 and builder2.
  Assert: Use assertNotSame to confirm builder1 and builder2 are not the same object reference.
Validation:
  Builder instances must be independent to prevent shared mutable state between different
  InvocationContext construction flows. If both calls returned the same object, concurrent or
  sequential builds could interfere with each other, leading to incorrect InvocationContext
  configurations.


Scenario 4: Verify That the Builder Produced by builder() Can Successfully Build an InvocationContext

Details:
  TestName: builderCanBuildInvocationContextSuccessfully
  Description: Verifies that the Builder returned by builder() is fully functional and can produce
               a valid InvocationContext instance when build() is called after configuring required fields.
Execution:
  Arrange: Create mock or stub implementations of BaseSessionService, BaseArtifactService, BaseAgent,
           Session, and RunConfig. Prepare an invocationId string.
  Act: Call InvocationContext.builder(), chain the necessary setter methods
       (sessionService, artifactService, agent, session, runConfig, invocationId), and call build().
  Assert: Use assertNotNull to verify the returned InvocationContext instance is not null.
Validation:
  This end-to-end test confirms that builder() provides a Builder that is fully operational.
  A Builder returned by the factory method that cannot complete a build would render the entire
  construction API broken, directly impacting the ability to create InvocationContext objects
  throughout the application.


Scenario 5: Verify That the Builder Returned by builder() Has Default endInvocation Value of False

Details:
  TestName: builderDefaultEndInvocationIsFalse
  Description: Verifies that the Builder created by builder() initializes the endInvocation field
               to false by default, so that a built InvocationContext reflects this default state.
Execution:
  Arrange: Create the minimum required mocks/stubs for BaseSessionService, BaseArtifactService,
           BaseAgent, and Session to allow a valid build.
  Act: Call InvocationContext.builder(), set required fields, and call build() without explicitly
       setting endInvocation. Capture the resulting InvocationContext.
  Assert: Call endInvocation() on the resulting context and assert it equals false.
Validation:
  The Builder class defines endInvocation with a default value of false. This test confirms that
  the default is correctly propagated from builder() through the build process. An incorrect default
  could cause invocations to terminate prematurely without any explicit instruction to do so.


Scenario 6: Verify That the Builder Returned by builder() Has a Default Non-Null invocationId

Details:
  TestName: builderDefaultInvocationIdIsNotNull
  Description: Verifies that the Builder created by builder() automatically generates a non-null,
               non-empty invocationId by default (using newInvocationContextId()), so the built
               InvocationContext has a valid ID without requiring explicit setting.
Execution:
  Arrange: Create the minimum required mocks/stubs for BaseSessionService, BaseArtifactService,
           BaseAgent, and Session.
  Act: Call InvocationContext.builder(), set the required fields without calling invocationId(),
       and call build(). Capture the resulting InvocationContext.
  Assert: Call invocationId() on the resulting context and assert it is not null and not empty.
Validation:
  The Builder's invocationId field is pre-initialized with newInvocationContextId(), which generates
  a UUID-based string. This guarantees every InvocationContext has a unique ID by default, which is
  critical for tracking and correlating invocations across the system.


Scenario 7: Verify That the Builder Returned by builder() Has a Default Empty liveRequestQueue

Details:
  TestName: builderDefaultLiveRequestQueueIsEmpty
  Description: Verifies that the Builder created by builder() initializes the liveRequestQueue
               field to Optional.empty() by default, so a built InvocationContext reflects this
               when no live queue is set.
Execution:
  Arrange: Create the minimum required mocks/stubs for BaseSessionService, BaseArtifactService,
           BaseAgent, and Session.
  Act: Call InvocationContext.builder(), set required fields without calling liveRequestQueue(),
       and call build(). Capture the resulting InvocationContext.
  Assert: Call liveRequestQueue() on the resulting context and assert it equals Optional.empty().
Validation:
  The default empty Optional for liveRequestQueue reflects the common case where no live
  streaming queue is needed. This test ensures that the builder() factory method produces a
  Builder that correctly defaults this optional field, preventing unexpected non-empty values
  for standard (non-live) invocations.


Scenario 8: Verify That the Builder Returned by builder() Has a Default Empty branch

Details:
  TestName: builderDefaultBranchIsEmpty
  Description: Verifies that the Builder created by builder() initializes the branch field
               to Optional.empty() by default, so a built InvocationContext has no branch
               unless explicitly set.
Execution:
  Arrange: Create the minimum required mocks/stubs for BaseSessionService, BaseArtifactService,
           BaseAgent, and Session.
  Act: Call InvocationContext.builder(), set required fields without calling branch(),
       and call build(). Capture the resulting InvocationContext.
  Assert: Call branch() on the resulting context and assert it equals Optional.empty().
Validation:
  The branch field represents a fork in conversation history and defaults to empty when no
  specific branch is needed. This test confirms the factory method produces a correctly
  defaulted Builder for this field, ensuring that uninitiated invocations do not carry
  spurious branch identifiers.


Scenario 9: Verify That the Builder Returned by builder() Has a Default Empty userContent

Details:
  TestName: builderDefaultUserContentIsEmpty
  Description: Verifies that the Builder created by builder() initializes the userContent field
               to Optional.empty() by default, so a built InvocationContext has no user content
               unless explicitly set.
Execution:
  Arrange: Create the minimum required mocks/stubs for BaseSessionService, BaseArtifactService,
           BaseAgent, and Session.
  Act: Call InvocationContext.builder(), set required fields without calling userContent(),
       and call build(). Capture the resulting InvocationContext.
  Assert: Call userContent() on the resulting context and assert it equals Optional.empty().
Validation:
  Not all invocations are triggered by explicit user content (e.g., programmatic or scheduled
  invocations). The empty default ensures that the absence of user input is clearly represented
  as Optional.empty() rather than null, promoting safer Optional-based handling downstream.


Scenario 10: Verify That the Builder Returned by builder() Supports Method Chaining

Details:
  TestName: builderSupportsMethodChaining
  Description: Verifies that the Builder returned by builder() supports fluent method chaining,
               i.e., each setter method returns the same Builder instance, enabling all fields
               to be set in a single chained expression.
Execution:
  Arrange: Create mock or stub implementations of BaseSessionService, BaseArtifactService,
           BaseAgent, and Session.
  Act: Call InvocationContext.builder() and chain multiple setter calls (sessionService,
       artifactService, agent, session), capturing the builder reference returned from each call.
  Assert: Use assertSame to confirm the Builder returned after each setter call is the same object
          as the one returned by builder().
Validation:
  Fluent method chaining is a core feature of the Builder pattern. If any setter returned a
  different object or null, the chain would break, forcing users to call each setter separately
  on a stored reference. This test ensures the Builder API is ergonomic and consistent.


Scenario 11: Verify That Two Builders From builder() Are Independent (State Isolation)

Details:
  TestName: twoBuilderInstancesAreStateIndependent
  Description: Verifies that configuring one Builder instance returned by builder() does not
               affect another Builder instance returned by a separate call to builder(), confirming
               full state isolation between the two.
Execution:
  Arrange: Create mock/stub implementations for BaseSessionService, BaseArtifactService,
           BaseAgent, and Session. Prepare two distinct invocationId strings: "invocation-1"
           and "invocation-2".
  Act: Call InvocationContext.builder() twice to get builder1 and builder2. Set invocationId
       to "invocation-1" on builder1 and invocationId to "invocation-2" on builder2.
       Build both to get context1 and context2.
  Assert: Assert that context1.invocationId() equals "invocation-1" and context2.invocationId()
          equals "invocation-2", confirming no cross-contamination.
Validation:
  Independent Builder instances are essential for creating multiple distinct InvocationContext
  objects within the same execution scope. If builders shared state (e.g., via static fields),
  configurations from one build would corrupt another, causing incorrect behavior in concurrent
  or sequential invocation scenarios.


Scenario 12: Verify That the Builder Returned by builder() Has a Non-Null Default PluginManager

Details:
  TestName: builderDefaultPluginManagerIsNotNull
  Description: Verifies that the Builder created by builder() initializes pluginManager to a
               non-null default instance (new PluginManager()), so a built InvocationContext
               always has a valid plugin manager even if none is explicitly provided.
Execution:
  Arrange: Create the minimum required mocks/stubs for BaseSessionService, BaseArtifactService,
           BaseAgent, and Session.
  Act: Call InvocationContext.builder(), set required fields without calling pluginManager(),
       and call build(). Capture the resulting InvocationContext.
  Assert: Call pluginManager() on the resulting context and assert it is not null.
Validation:
  A null PluginManager would cause NullPointerExceptions anywhere the agent attempts to
  access tools or plugins. By defaulting to a new PluginManager(), the builder() factory
  ensures a safe, non-null baseline configuration for every InvocationContext without
  requiring explicit initialization by the caller.


Scenario 13: Verify That the Builder Returned by builder() Has a Non-Null Default RunConfig

Details:
  TestName: builderDefaultRunConfigIsNotNull
  Description: Verifies that the Builder created by builder() initializes runConfig to a
               non-null default instance (RunConfig.builder().build()), so a built InvocationContext
               always has a valid run configuration even if none is explicitly provided.
Execution:
  Arrange: Create the minimum required mocks/stubs for BaseSessionService, BaseArtifactService,
           BaseAgent, and Session.
  Act: Call InvocationContext.builder(), set required fields without calling runConfig(),
       and call build(). Capture the resulting InvocationContext.
  Assert: Call runConfig() on the resulting context and assert it is not null.
Validation:
  RunConfig controls critical runtime parameters like maxLlmCalls. A null RunConfig would
  cause NullPointerExceptions in incrementLlmCallsCount() and other config-dependent logic.
  The non-null default ensures that every InvocationContext is safely operational out of the box.


Scenario 14: Verify That the Default invocationId Generated by builder() Starts With the Expected Prefix

Details:
  TestName: builderDefaultInvocationIdStartsWithExpectedPrefix
  Description: Verifies that the default invocationId generated in a new Builder (via
               newInvocationContextId()) starts with the "e-" prefix, conforming to the
               defined ID format.
Execution:
  Arrange: Create the minimum required mocks/stubs for BaseSessionService, BaseArtifactService,
           BaseAgent, and Session.
  Act: Call InvocationContext.builder(), set required fields without calling invocationId(),
       and call build(). Retrieve the invocationId from the resulting InvocationContext.
  Assert: Use assertTrue with String.startsWith("e-") to verify the generated ID conforms to
          the expected format.
Validation:
  The newInvocationContextId() method produces IDs in the format "e-<UUID>". Verifying the
  prefix ensures the ID generation logic is correctly invoked by the Builder when builder()
  is called, maintaining consistency in invocation ID formats used across logging, tracing,
  and event correlation.

*/

// ********RoostGPT********

```java
package com.google.adk.agents;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.events.Event;
import com.google.adk.flows.llmflows.ResumabilityConfig;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.models.LlmCallsLimitExceededException;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.genai.types.Content;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.junit.jupiter.api.*;
import com.google.common.collect.ImmutableSet;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import com.google.errorprone.annotations.InlineMe;
import com.google.genai.types.FunctionCall;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import javax.annotation.Nullable;

@ExtendWith(MockitoExtension.class)
class InvocationContextBuilderTest {
    @Mock
    private BaseSessionService mockSessionService;
    @Mock
    private BaseArtifactService mockArtifactService;
    @Mock
    private BaseMemoryService mockMemoryService;
    @Mock
    private BaseAgent mockAgent;
    @Mock
    private Session mockSession;
    @BeforeEach
    void setUp() {
        when(mockSession.appName()).thenReturn("testApp");
        when(mockSession.userId()).thenReturn("testUser");
    }
    @Test
    @Tag("valid")
    void builderReturnsNonNullInstance() {
        // Act
        InvocationContext.Builder builder = InvocationContext.builder();
        // Assert
        assertNotNull(builder, "builder() should return a non-null Builder instance");
    }
    @Test
    @Tag("valid")
    void builderReturnsCorrectBuilderType() {
        // Act
        Object builder = InvocationContext.builder();
        // Assert
        assertInstanceOf(
                InvocationContext.Builder.class,
                builder,
                "builder() should return an instance of InvocationContext.Builder");
    }
    @Test
    @Tag("valid")
    void builderReturnsNewInstanceOnEachCall() {
        // Act
        InvocationContext.Builder builder1 = InvocationContext.builder();
        InvocationContext.Builder builder2 = InvocationContext.builder();
        // Assert
        assertNotSame(
                builder1,
                builder2,
                "Each call to builder() should return a distinct Builder instance");
    }
    @Test
    @Tag("integration")
    void builderCanBuildInvocationContextSuccessfully() {
        // Arrange
        String invocationId = "e-test-invocation-id";
        // Act
        InvocationContext context =
                InvocationContext.builder()
                        .sessionService(mockSessionService)
                        .artifactService(mockArtifactService)
                        .invocationId(invocationId)
                        .agent(mockAgent)
                        .session(mockSession)
                        .build();
        // Assert
        assertNotNull(context, "build() should return a non-null InvocationContext instance");
    }
    @Test
    @Tag("valid")
    void builderDefaultEndInvocationIsFalse() {
        // Arrange & Act
        InvocationContext context =
                InvocationContext.builder()
                        .sessionService(mockSessionService)
                        .artifactService(mockArtifactService)
                        .agent(mockAgent)
                        .session(mockSession)
                        .build();
        // Assert
        assertFalse(
                context.endInvocation(),
                "Default endInvocation should be false in a freshly built InvocationContext");
    }
    @Test
    @Tag("valid")
    void builderDefaultInvocationIdIsNotNull() {
        // Arrange & Act
        InvocationContext context =
                InvocationContext.builder()
                        .sessionService(mockSessionService)
                        .artifactService(mockArtifactService)
                        .agent(mockAgent)
                        .session(mockSession)
                        .build();
        // Assert
        assertNotNull(
                context.invocationId(),
                "Default invocationId should be non-null");
        assertFalse(
                context.invocationId().isEmpty(),
                "Default invocationId should be non-empty");
    }
    @Test
    @Tag("valid")
    void builderDefaultLiveRequestQueueIsEmpty() {
        // Arrange & Act
        InvocationContext context =
                InvocationContext.builder()
                        .sessionService(mockSessionService)
                        .artifactService(mockArtifactService)
                        .agent(mockAgent)
                        .session(mockSession)
                        .build();
        // Assert
        assertEquals(
                Optional.empty(),
                context.liveRequestQueue(),
                "Default liveRequestQueue should be Optional.empty()");
    }
    @Test
    @Tag("valid")
    void builderDefaultBranchIsEmpty() {
        // Arrange & Act
        InvocationContext context =
                InvocationContext.builder()
                        .sessionService(mockSessionService)
                        .artifactService(mockArtifactService)
                        .agent(mockAgent)
                        .session(mockSession)
                        .build();
        // Assert
        assertEquals(
                Optional.empty(),
                context.branch(),
                "Default branch should be Optional.empty()");
    }
    @Test
    @Tag("valid")
    void builderDefaultUserContentIsEmpty() {
        // Arrange & Act
        InvocationContext context =
                InvocationContext.builder()
                        .sessionService(mockSessionService)
                        .artifactService(mockArtifactService)
                        .agent(mockAgent)
                        .session(mockSession)
                        .build();
        // Assert
        assertEquals(
                Optional.empty(),
                context.userContent(),
                "Default userContent should be Optional.empty()");
    }
    @Test
    @Tag("valid")
    void builderSupportsMethodChaining() {
        // Arrange
        InvocationContext.Builder builder = InvocationContext.builder();
        // Act
        InvocationContext.Builder afterSessionService = builder.sessionService(mockSessionService);
        InvocationContext.Builder afterArtifactService =
                afterSessionService.artifactService(mockArtifactService);
        InvocationContext.Builder afterAgent = afterArtifactService.agent(mockAgent);
        InvocationContext.Builder afterSession = afterAgent.session(mockSession);
        // Assert
        assertSame(
                builder,
                afterSessionService,
                "sessionService() should return the same Builder instance");
        assertSame(
                builder,
                afterArtifactService,
                "artifactService() should return the same Builder instance");
        assertSame(builder, afterAgent, "agent() should return the same Builder instance");
        assertSame(builder, afterSession, "session() should return the same Builder instance");
    }
    @Test
    @Tag("valid")
    void twoBuilderInstancesAreStateIndependent() {
        // Arrange
        String invocationId1 = "invocation-1";
        String invocationId2 = "invocation-2";
        // Act
        InvocationContext.Builder builder1 = InvocationContext.builder();
        InvocationContext.Builder builder2 = InvocationContext.builder();
        InvocationContext context1 =
                builder1
                        .sessionService(mockSessionService)
                        .artifactService(mockArtifactService)
                        .agent(mockAgent)
                        .session(mockSession)
                        .invocationId(invocationId1)
                        .build();
        InvocationContext context2 =
                builder2
                        .sessionService(mockSessionService)
                        .artifactService(mockArtifactService)
                        .agent(mockAgent)
                        .session(mockSession)
                        .invocationId(invocationId2)
                        .build();
        // Assert
        assertEquals(
                invocationId1,
                context1.invocationId(),
                "context1 should have invocationId 'invocation-1'");
        assertEquals(
                invocationId2,
                context2.invocationId(),
                "context2 should have invocationId 'invocation-2'");
        assertNotEquals(
                context1.invocationId(),
                context2.invocationId(),
                "Two separately built contexts should have different invocationIds");
    }
    @Test
    @Tag("valid")
    void builderDefaultPluginManagerIsNotNull() {
        // Arrange & Act
        InvocationContext context =
                InvocationContext.builder()
                        .sessionService(mockSessionService)
                        .artifactService(mockArtifactService)
                        .agent(mockAgent)
                        .session(mockSession)
                        .build();
        // Assert
        assertNotNull(
                context.pluginManager(),
                "Default pluginManager should be non-null");
    }
    @Test
    @Tag("valid")
    void builderDefaultRunConfigIsNotNull() {
        // Arrange & Act
        InvocationContext context =
                InvocationContext.builder()
                        .sessionService(mockSessionService)
                        .artifactService(mockArtifactService)
                        .agent(mockAgent)
                        .session(mockSession)
                        .build();
        // Assert
        assertNotNull(
                context.runConfig(),
                "Default runConfig should be non-null");
    }
    @Test
    @Tag("valid")
    void builderDefaultInvocationIdStartsWithExpectedPrefix() {
        // Arrange & Act
        InvocationContext context =
                InvocationContext.builder()
                        .sessionService(mockSessionService)
                        .artifactService(mockArtifactService)
                        .agent(mockAgent)
                        .session(mockSession)
                        .build();
        String invocationId = context.invocationId();
        // Assert
        assertNotNull(invocationId, "Default invocationId should not be null");
        assertTrue(
                invocationId.startsWith("e-"),
                "Default invocationId should start with 'e-', but was: " + invocationId);
    }
    @Test
    @Tag("boundary")
    void builderWithExplicitlySetInvocationIdOverridesDefault() {
        // Arrange
        String customInvocationId = "custom-invocation-id-123";
        // Act
        InvocationContext context =
                InvocationContext.builder()
                        .sessionService(mockSessionService)
                        .artifactService(mockArtifactService)
                        .agent(mockAgent)
                        .session(mockSession)
                        .invocationId(customInvocationId)
                        .build();
        // Assert
        assertEquals(
                customInvocationId,
                context.invocationId(),
                "Explicitly set invocationId should override the default");
    }
    @Test
    @Tag("valid")
    void builderWithAllFieldsSetBuildsCorrectly() {
        // Arrange
        String invocationId = "e-full-context-id";
        String branch = "agentA.agentB";
        PluginManager pluginManager = new PluginManager(java.util.List.of());
        // Act
        InvocationContext context =
                InvocationContext.builder()
                        .sessionService(mockSessionService)
                        .artifactService(mockArtifactService)
                        .memoryService(mockMemoryService)
                        .pluginManager(pluginManager)
                        .agent(mockAgent)
                        .session(mockSession)
                        .invocationId(invocationId)
                        .branch(branch)
                        .endInvocation(false)
                        .build();
        // Assert
        assertNotNull(context);
        assertEquals(invocationId, context.invocationId());
        assertEquals(Optional.of(branch), context.branch());
        assertFalse(context.endInvocation());
        assertEquals(mockSessionService, context.sessionService());
        assertEquals(mockArtifactService, context.artifactService());
        assertEquals(mockMemoryService, context.memoryService());
        assertEquals(pluginManager, context.pluginManager());
        assertEquals(mockAgent, context.agent());
        assertEquals(mockSession, context.session());
    }
    @Test
    @Tag("valid")
    void builderWithEndInvocationSetToTrue() {
        // Arrange & Act
        InvocationContext context =
                InvocationContext.builder()
                        .sessionService(mockSessionService)
                        .artifactService(mockArtifactService)
                        .agent(mockAgent)
                        .session(mockSession)
                        .endInvocation(true)
                        .build();
        // Assert
        assertTrue(
                context.endInvocation(),
                "endInvocation should be true when explicitly set to true");
    }
    @Test
    @Tag("integration")
    void builderCanCreateMultipleDistinctContextsSequentially() {
        // Arrange
        String invocationId1 = "e-context-one";
        String invocationId2 = "e-context-two";
        // Act
        InvocationContext context1 =
                InvocationContext.builder()
                        .sessionService(mockSessionService)
                        .artifactService(mockArtifactService)
                        .agent(mockAgent)
                        .session(mockSession)
                        .invocationId(invocationId1)
                        .build();
        InvocationContext context2 =
                InvocationContext.builder()
                        .sessionService(mockSessionService)
                        .artifactService(mockArtifactService)
                        .agent(mockAgent)
                        .session(mockSession)
                        .invocationId(invocationId2)
                        .build();
        // Assert
        assertNotNull(context1);
        assertNotNull(context2);
        assertNotSame(context1, context2, "Each build() call should produce a distinct object");
        assertEquals(invocationId1, context1.invocationId());
        assertEquals(invocationId2, context2.invocationId());
    }
    @Test
    @Tag("valid")
    void builderDefaultInvocationIdIsUniqueAcrossTwoCalls() {
        // Arrange & Act
        InvocationContext context1 =
                InvocationContext.builder()
                        .sessionService(mockSessionService)
                        .artifactService(mockArtifactService)
                        .agent(mockAgent)
                        .session(mockSession)
                        .build();
        InvocationContext context2 =
                InvocationContext.builder()
                        .sessionService(mockSessionService)
                        .artifactService(mockArtifactService)
                        .agent(mockAgent)
                        .session(mockSession)
                        .build();
        // Assert
        assertNotEquals(
                context1.invocationId(),
                context2.invocationId(),
                "Each Builder should generate a unique default invocationId");
    }
    @Test
    @Tag("valid")
    void builderWithBranchSetAsOptional() {
        // Arrange
        Optional<String> branchOpt = Optional.of("agentRoot.agentChild");
        // Act
        InvocationContext context =
                InvocationContext.builder()
                        .sessionService(mockSessionService)
                        .artifactService(mockArtifactService)
                        .agent(mockAgent)
                        .session(mockSession)
                        .branch(branchOpt)
                        .build();
        // Assert
        assertEquals(branchOpt, context.branch(), "Branch should match the provided Optional<String>");
    }
    @Test
    @Tag("boundary")
    void builderWithEmptyBranchOptional() {
        // Arrange & Act
        InvocationContext context =
                InvocationContext.builder()
                        .session