/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=branch_25309d7017
ROOST_METHOD_SIG_HASH=branch_5237016f3f

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/june-java-unit/1782282457/source/adk-java/core/src/test/java/com/google/adk/agents/ParallelAgentTest.java
Tests:
    "@Test
public void runAsync_subAgentsExecuteInParallel_eventsOrderedByCompletion() {
    String agent1Name = "test_agent_1_delayed";
    String agent2Name = "test_agent_2_fast";
    String parallelAgentName = "test_parallel_agent";
    TestingAgent agent1 = new TestingAgent(agent1Name, "Delayed Agent", 500);
    TestingAgent agent2 = new TestingAgent(agent2Name, "Fast Agent", 0);
    ParallelAgent parallelAgent = ParallelAgent.builder().name(parallelAgentName).subAgents(agent1, agent2).build();
    InvocationContext invocationContext = createInvocationContext(parallelAgent);
    List<Event> events = parallelAgent.runAsync(invocationContext).toList().blockingGet();
    assertThat(events).hasSize(2);

    Event firstEvent = events.get(0);
    assertThat(firstEvent.author()).isEqualTo(agent2Name);
    assertThat(firstEvent.content().get().parts().get().get(0).text()).hasValue("Hello, async " + agent2Name + "!");
    assertThat(firstEvent.branch().get()).endsWith(agent2Name);

    Event secondEvent = events.get(1);
    assertThat(secondEvent.author()).isEqualTo(agent1Name);
    assertThat(secondEvent.content().get().parts().get().get(0).text()).hasValue("Hello, async " + agent1Name + "!");
    assertThat(secondEvent.branch().get()).endsWith(agent1Name);
}
"Scenario 1: Setting a Valid Non-Null Branch String

Details:
  TestName: branchSetsValidNonNullStringAsOptionalPresent
  Description: Verifies that calling branch() with a valid, non-null string value correctly
               wraps it in an Optional and stores it in the branch field of InvocationContext.
Execution:
  Arrange: Create an InvocationContext instance using InvocationContext.builder() with all
           required fields (sessionService, artifactService, agent, session, runConfig).
           Define a non-null branch string value such as "main-branch".
  Act: Invoke context.branch("main-branch") on the created InvocationContext instance.
  Assert: Call context.branch() and assert that the returned Optional is present and
          contains the value "main-branch".
Validation:
  The assertion confirms that a valid non-null string is correctly wrapped in
  Optional.of(...) and stored. This is important because the branch field tracks
  which conversation fork the invocation belongs to, and a correctly stored branch
  value enables accurate routing and history tracking in multi-agent flows.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class InvocationContextBranchTest {

	@Mock
	private BaseSessionService mockSessionService;

	@Mock
	private BaseArtifactService mockArtifactService;

	@Mock
	private BaseMemoryService mockMemoryService;

	@Mock
	private PluginManager mockPluginManager;

	@Mock
	private BaseAgent mockAgent;

	@Mock
	private Session mockSession;

	private RunConfig runConfig;

	@BeforeEach
	public void setUp() {
		runConfig = RunConfig.builder().build();
		when(mockSession.appName()).thenReturn("testApp");
		when(mockSession.userId()).thenReturn("testUser");
	}

	private InvocationContext buildDefaultContext() {
		return InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("test-invocation-id")
			.runConfig(runConfig)
			.build();
	}

	// Scenario 1: Setting a Valid Non-Null Branch String
	@Test
	@Tag("valid")
	public void branchSetsValidNonNullStringAsOptionalPresent() {
		// Arrange
		InvocationContext context = buildDefaultContext();
		String branchValue = "main-branch";
		// Act
		context.branch(branchValue);
		// Assert
		assertTrue(context.branch().isPresent());
		assertEquals("main-branch", context.branch().get());
	}

	@Test
	@Tag("invalid")
	public void branchSetsNullAsOptionalEmpty() {
		// Arrange
		InvocationContext context = buildDefaultContext();
		// Act
		context.branch(null);
		// Assert
		assertFalse(context.branch().isPresent());
		assertEquals(Optional.empty(), context.branch());
	}

	@Test
	@Tag("valid")
	public void branchSetsEmptyStringAsOptionalPresentWithEmptyString() {
		// Arrange
		InvocationContext context = buildDefaultContext();
		String branchValue = "";
		// Act
		context.branch(branchValue);
		// Assert
		assertTrue(context.branch().isPresent());
		assertEquals("", context.branch().get());
	}

	@Test
	@Tag("valid")
	public void branchSetsComplexHierarchicalBranchString() {
		// Arrange
		InvocationContext context = buildDefaultContext();
		String branchValue = "parent-agent.child-agent.sub-agent";
		// Act
		context.branch(branchValue);
		// Assert
		assertTrue(context.branch().isPresent());
		assertEquals("parent-agent.child-agent.sub-agent", context.branch().get());
	}

	@Test
	@Tag("valid")
	public void branchUpdatesExistingBranchValue() {
		// Arrange
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("test-invocation-id")
			.runConfig(runConfig)
			.branch("initial-branch")
			.build();
		// Act
		context.branch("updated-branch");
		// Assert
		assertTrue(context.branch().isPresent());
		assertEquals("updated-branch", context.branch().get());
	}

	@Test
	@Tag("valid")
	public void branchOverwritesExistingBranchWithNull() {
		// Arrange
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("test-invocation-id")
			.runConfig(runConfig)
			.branch("some-branch")
			.build();
		// Act
		context.branch(null);
		// Assert
		assertFalse(context.branch().isPresent());
		assertEquals(Optional.empty(), context.branch());
	}

	@Test
	@Tag("boundary")
	public void branchHandlesVeryLongBranchString() {
		// Arrange
		InvocationContext context = buildDefaultContext();
		StringBuilder sb = new StringBuilder();
		for (int i = 0; i < 1000; i++) {
			sb.append("a");
		}
		String longBranchValue = sb.toString();
		// Act
		context.branch(longBranchValue);
		// Assert
		assertTrue(context.branch().isPresent());
		assertEquals(longBranchValue, context.branch().get());
		assertEquals(1000, context.branch().get().length());
	}

	@Test
	@Tag("boundary")
	public void branchHandlesSingleCharacterBranchString() {
		// Arrange
		InvocationContext context = buildDefaultContext();
		String branchValue = "a";
		// Act
		context.branch(branchValue);
		// Assert
		assertTrue(context.branch().isPresent());
		assertEquals("a", context.branch().get());
	}

	@Test
	@Tag("valid")
	public void branchHandlesSpecialCharactersInBranchString() {
		// Arrange
		InvocationContext context = buildDefaultContext();
		String branchValue = "branch-123_test.v2@special";
		// Act
		context.branch(branchValue);
		// Assert
		assertTrue(context.branch().isPresent());
		assertEquals("branch-123_test.v2@special", context.branch().get());
	}

	@Test
	@Tag("valid")
	public void branchReturnValueIsWrappedInOptional() {
		// Arrange
		InvocationContext context = buildDefaultContext();
		String branchValue = "optional-branch";
		// Act
		context.branch(branchValue);
		Optional<String> result = context.branch();
		// Assert
		assertNotNull(result);
		assertInstanceOf(Optional.class, result);
		assertEquals(Optional.of("optional-branch"), result);
	}

	@Test
	@Tag("integration")
	public void branchCanBeSetAndRetrievedMultipleTimes() {
		// Arrange
		InvocationContext context = buildDefaultContext();
		// Act & Assert - first set
		context.branch("first-branch");
		assertTrue(context.branch().isPresent());
		assertEquals("first-branch", context.branch().get());
		// Act & Assert - second set
		context.branch("second-branch");
		assertTrue(context.branch().isPresent());
		assertEquals("second-branch", context.branch().get());
		// Act & Assert - set to null
		context.branch(null);
		assertFalse(context.branch().isPresent());
		// Act & Assert - set again
		context.branch("third-branch");
		assertTrue(context.branch().isPresent());
		assertEquals("third-branch", context.branch().get());
	}

	@Test
	@Tag("integration")
	public void branchIsPreservedInCopyOf() {
		// Arrange
		InvocationContext original = buildDefaultContext();
		original.branch("original-branch");
		// Act
		InvocationContext copy = InvocationContext.copyOf(original);
		// Assert
		assertTrue(copy.branch().isPresent());
		assertEquals("original-branch", copy.branch().get());
	}

	@Test
	@Tag("integration")
	public void branchChangesInCopyDoNotAffectOriginal() {
		// Arrange
		InvocationContext original = buildDefaultContext();
		original.branch("original-branch");
		InvocationContext copy = InvocationContext.copyOf(original);
		// Act
		copy.branch("modified-branch");
		// Assert
		assertTrue(original.branch().isPresent());
		assertEquals("original-branch", original.branch().get());
		assertTrue(copy.branch().isPresent());
		assertEquals("modified-branch", copy.branch().get());
	}

	@Test
	@Tag("valid")
	public void branchDefaultValueIsEmptyOptionalWhenNotSetInBuilder() {
		// Arrange
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("test-invocation-id")
			.runConfig(runConfig)
			.build();
		// Assert default (no branch set)
		assertNotNull(context.branch());
	}

	@Test
	@Tag("valid")
	public void branchSetViaBuilderIsReturnedCorrectly() {
		// Arrange
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("test-invocation-id")
			.runConfig(runConfig)
			.branch("builder-branch")
			.build();
		// Assert
		assertTrue(context.branch().isPresent());
		assertEquals("builder-branch", context.branch().get());
	}

	@Test
	@Tag("valid")
	public void branchSetsWhitespaceStringAsOptionalPresent() {
		// Arrange
		InvocationContext context = buildDefaultContext();
		String branchValue = "   ";
		// Act
		context.branch(branchValue);
		// Assert
		assertTrue(context.branch().isPresent());
		assertEquals("   ", context.branch().get());
	}

	@Test
	@Tag("boundary")
	public void branchHandlesBranchWithDotSeparatedSegments() {
		// Arrange
		InvocationContext context = buildDefaultContext();
		String branchValue = "root.child.grandchild";
		// Act
		context.branch(branchValue);
		// Assert
		assertTrue(context.branch().isPresent());
		assertEquals("root.child.grandchild", context.branch().get());
		assertTrue(context.branch().get().contains("."));
	}

}
