/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=agent_9b91251448
ROOST_METHOD_SIG_HASH=agent_877597f15f

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/june-java-unit/1782282457/source/adk-java/core/src/test/java/com/google/adk/agents/InvocationContextTest.java
Tests:
    "@Test
public void testCreateWithUserContent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).isEmpty();
    assertThat(context.invocationId()).isEqualTo(testInvocationId);
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).hasValue(userContent);
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testCreateWithNullUserContent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.userContent()).isEmpty();
}
"
    "@Test
public void testCreateWithLiveRequestQueue() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).liveRequestQueue(liveRequestQueue).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).hasValue(liveRequestQueue);

    assertThat(context.invocationId()).startsWith("e-");
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).isEmpty();
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testCopyOf() {
    InvocationContext originalContext = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    originalContext.activeStreamingTools().putAll(activeStreamingTools);
    InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
    assertThat(copiedContext).isNotNull();
    assertThat(copiedContext).isNotSameInstanceAs(originalContext);
    assertThat(copiedContext.sessionService()).isEqualTo(originalContext.sessionService());
    assertThat(copiedContext.artifactService()).isEqualTo(originalContext.artifactService());
    assertThat(copiedContext.memoryService()).isEqualTo(originalContext.memoryService());
    assertThat(copiedContext.liveRequestQueue()).isEqualTo(originalContext.liveRequestQueue());
    assertThat(copiedContext.invocationId()).isEqualTo(originalContext.invocationId());
    assertThat(copiedContext.agent()).isEqualTo(originalContext.agent());
    assertThat(copiedContext.session()).isEqualTo(originalContext.session());
    assertThat(copiedContext.userContent()).isEqualTo(originalContext.userContent());
    assertThat(copiedContext.runConfig()).isEqualTo(originalContext.runConfig());
    assertThat(copiedContext.endInvocation()).isEqualTo(originalContext.endInvocation());
    assertThat(copiedContext.activeStreamingTools()).isEqualTo(originalContext.activeStreamingTools());
}
"
    "@Test
public void testGetters() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).isEmpty();
    assertThat(context.invocationId()).isEqualTo(testInvocationId);
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).hasValue(userContent);
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testSetAgent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    BaseAgent newMockAgent = mock(BaseAgent.class);
    context.agent(newMockAgent);
    assertThat(context.agent()).isEqualTo(newMockAgent);
}
"
    "@Test
public void testEquals_sameObject() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(context)).isTrue();
}
"
    "@Test
public void testEquals_null() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(null)).isFalse();
}
"
    "@Test
public void testEquals_sameValues() {
    InvocationContext context1 = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext context2 = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context1.equals(context2)).isTrue();

    assertThat(context2.equals(context1)).isTrue();
}
"
    "@Test
public void testEquals_differentValues() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext contextWithDiffSessionService = InvocationContext.builder().sessionService(
    mock(BaseSessionService.class)).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffInvocationId = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(
    "another-id").agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffAgent = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(
    mock(BaseAgent.class)).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithUserContentEmpty = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithLiveQueuePresent = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).liveRequestQueue(liveRequestQueue).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(contextWithDiffSessionService)).isFalse();
    assertThat(context.equals(contextWithDiffInvocationId)).isFalse();
    assertThat(context.equals(contextWithDiffAgent)).isFalse();
    assertThat(context.equals(contextWithUserContentEmpty)).isFalse();
    assertThat(context.equals(contextWithLiveQueuePresent)).isFalse();
}
"
    "@Test
public void testHashCode_differentValues() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext contextWithDiffSessionService = InvocationContext.builder().sessionService(
    mock(BaseSessionService.class)).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffInvocationId = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(
    "another-id").agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotEqualTo(contextWithDiffSessionService);
    assertThat(context).isNotEqualTo(contextWithDiffInvocationId);
}
"
    "@Test
public void isResumable_whenResumabilityConfigIsNotResumable_isFalse() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(false)).build();
    assertThat(context.isResumable()).isFalse();
}
"
    "@Test
public void isResumable_whenResumabilityConfigIsResumable_isTrue() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(true)).build();
    assertThat(context.isResumable()).isTrue();
}
"
    "@Test
public void shouldPauseInvocation_whenNotResumable_isFalse() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(false)).build();
    Event event = Event.builder().longRunningToolIds(Optional.of(ImmutableSet.of("fc1"))).content(Content.builder().parts(ImmutableList.of(Part.builder().functionCall(FunctionCall.builder().name("tool1").id("fc1").build()).build())).build()).build();
    assertThat(context.shouldPauseInvocation(event)).isFalse();
}
"
    "@Test
public void shouldPauseInvocation_whenResumableAndNoLongRunningToolIds_isFalse() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(true)).build();
    Event event = Event.builder().content(Content.builder().parts(ImmutableList.of(Part.builder().functionCall(FunctionCall.builder().name("tool1").id("fc1").build()).build())).build()).build();
    assertThat(context.shouldPauseInvocation(event)).isFalse();
}
"
    "@Test
public void shouldPauseInvocation_whenResumableAndNoFunctionCalls_isFalse() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(true)).build();
    Event event = Event.builder().longRunningToolIds(Optional.of(ImmutableSet.of("fc1"))).build();
    assertThat(context.shouldPauseInvocation(event)).isFalse();
}
"
    "@Test
public void shouldPauseInvocation_whenResumableAndNoMatchingFunctionCallId_isFalse() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(true)).build();
    Event event = Event.builder().longRunningToolIds(Optional.of(ImmutableSet.of("fc2"))).content(Content.builder().parts(ImmutableList.of(Part.builder().functionCall(FunctionCall.builder().name("tool1").id("fc1").build()).build())).build()).build();
    assertThat(context.shouldPauseInvocation(event)).isFalse();
}
"
    "@Test
public void shouldPauseInvocation_whenResumableAndMatchingFunctionCallId_isTrue() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(true)).build();
    Event event = Event.builder().longRunningToolIds(Optional.of(ImmutableSet.of("fc1"))).content(Content.builder().parts(ImmutableList.of(Part.builder().functionCall(FunctionCall.builder().name("tool1").id("fc1").build()).build())).build()).build();
    assertThat(context.shouldPauseInvocation(event)).isTrue();
}
"

File Path: /var/tmp/Roost/RoostGPT/june-java-unit/1782282457/source/adk-java/core/src/test/java/com/google/adk/agents/SequentialAgentTest.java
Tests:
    "@Test
public void runAsync_propagatesInvocationContextToSubAgents() {
    TestBaseAgent subAgent = createSubAgent("subAgent");
    SequentialAgent sequentialAgent = SequentialAgent.builder().name("seqAgent").subAgents(ImmutableList.of(subAgent)).build();
    InvocationContext parentContext = createInvocationContext(sequentialAgent);
    List<Event> unused = sequentialAgent.runAsync(parentContext).toList().blockingGet();
    InvocationContext capturedContext = subAgent.getLastInvocationContext();
    assertThat(capturedContext).isNotNull();
    assertThat(capturedContext.invocationId()).isEqualTo(parentContext.invocationId());
    assertThat(capturedContext.session()).isEqualTo(parentContext.session());
    assertThat(capturedContext.agent()).isEqualTo(subAgent);
    assertThat(subAgent.getInvocationCount()).isEqualTo(1);
}
"
    "@Test
public void runLive_propagatesInvocationContextToSubAgents() {
    TestBaseAgent subAgent = createSubAgent("subAgent_live");
    SequentialAgent sequentialAgent = SequentialAgent.builder().name("seqAgentLive").subAgents(ImmutableList.of(subAgent)).build();
    InvocationContext parentContext = createInvocationContext(sequentialAgent);
    List<Event> unused = sequentialAgent.runLive(parentContext).toList().blockingGet();
    InvocationContext capturedContext = subAgent.getLastInvocationContext();
    assertThat(capturedContext).isNotNull();
    assertThat(capturedContext.invocationId()).isEqualTo(parentContext.invocationId());
    assertThat(capturedContext.session()).isEqualTo(parentContext.session());
    assertThat(capturedContext.agent()).isEqualTo(subAgent);
    assertThat(subAgent.getInvocationCount()).isEqualTo(1);
}
"Scenario 1: Verify agent() Returns the Initially Set Agent

Details:
  TestName: agentReturnsInitiallySetAgent
  Description: Verifies that the agent() method returns the exact BaseAgent instance that was set during the construction of the InvocationContext via the builder.

Execution:
  Arrange:
    - Create a mock of BaseAgent (mockAgent).
    - Build an InvocationContext using the builder, setting mockAgent as the agent along with other required fields (sessionService, artifactService, memoryService, session).
  Act:
    - Call context.agent() on the constructed InvocationContext.
  Assert:
    - Assert that the returned value from context.agent() is equal to mockAgent.

Validation:
  The assertion confirms that the agent() getter faithfully returns the BaseAgent reference stored during construction. This is critical because the invocation context's agent field determines which agent handles the current invocation, and an incorrect return value would cause delegation failures.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.flows.llmflows.ResumabilityConfig;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.genai.types.Content;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
class InvocationContextAgentTest {

	@Mock
	private BaseSessionService mockSessionService;

	@Mock
	private BaseArtifactService mockArtifactService;

	@Mock
	private BaseMemoryService mockMemoryService;

	@Mock
	private PluginManager mockPluginManager;

	@Mock
	private Session mockSession;

	@Mock
	private BaseAgent mockAgent;

	@Mock
	private BaseAgent mockAgent2;

	@Mock
	private RunConfig mockRunConfig;

	@Mock
	private ResumabilityConfig mockResumabilityConfig;

	private InvocationContext invocationContext;

	@BeforeEach
  void setUp() {
    when(mockSession.appName()).thenReturn("testApp");
    when(mockSession.userId()).thenReturn("testUser");
  }

	@Test
	@Tag("valid")
	void agentReturnsInitiallySetAgent() {
		// Arrange
		invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("test-invocation-id")
			.runConfig(mockRunConfig)
			.build();
		// Act
		BaseAgent result = invocationContext.agent();
		// Assert
		assertNotNull(result);
		assertEquals(mockAgent, result);
	}

	@Test
	@Tag("valid")
	void agentReturnsCorrectAgentAfterBuilderConstruction() {
		// Arrange
		invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("inv-001")
			.runConfig(mockRunConfig)
			.build();
		// Act
		BaseAgent returnedAgent = invocationContext.agent();
		// Assert
		assertSame(mockAgent, returnedAgent,
				"agent() should return the same instance that was set during construction");
	}

	@Test
	@Tag("valid")
	void agentReturnsSameReferenceNotACopy() {
		// Arrange
		invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("inv-ref-test")
			.runConfig(mockRunConfig)
			.build();
		// Act
		BaseAgent firstCall = invocationContext.agent();
		BaseAgent secondCall = invocationContext.agent();
		// Assert
		assertSame(firstCall, secondCall, "Multiple calls to agent() should return the same reference");
	}

	@Test
	@Tag("valid")
	void agentReturnsUpdatedAgentAfterSetterCall() {
		// Arrange
		invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("inv-update-test")
			.runConfig(mockRunConfig)
			.build();
		// Act
		invocationContext.agent(mockAgent2);
		BaseAgent result = invocationContext.agent();
		// Assert
		assertNotNull(result);
		assertEquals(mockAgent2, result);
		assertNotEquals(mockAgent, result);
	}

	@Test
	@Tag("valid")
	void agentReturnsPreviousAgentBeforeUpdate() {
		// Arrange
		invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("inv-before-update")
			.runConfig(mockRunConfig)
			.build();
		// Act
		BaseAgent beforeUpdate = invocationContext.agent();
		invocationContext.agent(mockAgent2);
		BaseAgent afterUpdate = invocationContext.agent();
		// Assert
		assertSame(mockAgent, beforeUpdate);
		assertSame(mockAgent2, afterUpdate);
		assertNotSame(beforeUpdate, afterUpdate);
	}

	@Test
	@Tag("valid")
	void agentReturnsCorrectAgentWhenCreatedWithStaticCreateMethod() {
		// Arrange
		Content userContent = mock(Content.class);
		invocationContext = InvocationContext.create(mockSessionService, mockArtifactService, "inv-static-create",
				mockAgent, mockSession, userContent, mockRunConfig);
		// Act
		BaseAgent result = invocationContext.agent();
		// Assert
		assertNotNull(result);
		assertEquals(mockAgent, result);
	}

	@Test
	@Tag("valid")
	void agentReturnsCorrectAgentWhenCreatedWithLiveRequestQueueStaticCreateMethod() {
		// Arrange
		LiveRequestQueue liveRequestQueue = new LiveRequestQueue();
		invocationContext = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent, mockSession,
				liveRequestQueue, mockRunConfig);
		// Act
		BaseAgent result = invocationContext.agent();
		// Assert
		assertNotNull(result);
		assertEquals(mockAgent, result);
	}

	@Test
	@Tag("valid")
	void agentReturnsSameAgentFromCopiedContext() {
		// Arrange
		InvocationContext original = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("inv-copy-test")
			.runConfig(mockRunConfig)
			.build();
		InvocationContext copied = InvocationContext.copyOf(original);
		// Act
		BaseAgent originalAgent = original.agent();
		BaseAgent copiedAgent = copied.agent();
		// Assert
		assertNotNull(copiedAgent);
		assertSame(originalAgent, copiedAgent, "Copied context should have the same agent reference");
	}

	@Test
	@Tag("valid")
	void agentChangeInCopiedContextDoesNotAffectOriginal() {
		// Arrange
		InvocationContext original = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("inv-independence-test")
			.runConfig(mockRunConfig)
			.build();
		InvocationContext copied = InvocationContext.copyOf(original);
		// Act
		copied.agent(mockAgent2);
		// Assert
		assertSame(mockAgent, original.agent(), "Changing agent in copied context should not affect original");
		assertSame(mockAgent2, copied.agent(), "Copied context should have the updated agent");
	}

	@Test
  @Tag("valid")
  void agentReturnsMockAgentWithCorrectName() {
    // Arrange
    when(mockAgent.name()).thenReturn("testAgentName");
    invocationContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("inv-name-check")
            .runConfig(mockRunConfig)
            .build();
    // Act
    BaseAgent result = invocationContext.agent();
    // Assert
    assertNotNull(result);
    assertEquals("testAgentName", result.name());
  }

	@Test
	@Tag("boundary")
	void agentReturnsNullWhenSetToNull() {
		// Arrange
		invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.session(mockSession)
			.invocationId("inv-null-agent")
			.runConfig(mockRunConfig)
			.build();
		// Act
		BaseAgent result = invocationContext.agent();
		// Assert
		assertNull(result, "agent() should return null when no agent was set during construction");
	}

	@Test
	@Tag("boundary")
	void agentReturnsNullAfterExplicitlySetToNull() {
		// Arrange
		invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("inv-set-null-agent")
			.runConfig(mockRunConfig)
			.build();
		// Act
		invocationContext.agent(null);
		BaseAgent result = invocationContext.agent();
		// Assert
		assertNull(result, "agent() should return null after explicitly setting agent to null");
	}

	@Test
  @Tag("integration")
  void agentIsCorrectlySetAndRetrievedInFullContextWithAllFields() {
    // Arrange
    when(mockAgent.name()).thenReturn("fullContextAgent");
    when(mockAgent.description()).thenReturn("Full context agent description");
    invocationContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .memoryService(mockMemoryService)
            .pluginManager(mockPluginManager)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("inv-full-context")
            .userContent(Optional.empty())
            .runConfig(mockRunConfig)
            .branch(Optional.of("test-branch"))
            .endInvocation(false)
            .build();
    // Act
    BaseAgent result = invocationContext.agent();
    // Assert
    assertNotNull(result);
    assertSame(mockAgent, result);
    assertEquals("fullContextAgent", result.name());
    assertEquals("Full context agent description", result.description());
  }

	@Test
	@Tag("integration")
	void agentIsConsistentWithOtherContextFieldsAfterConstruction() {
		// Arrange
		String invocationId = "inv-consistency-test";
		when(mockAgent.name()).thenReturn("consistencyAgent");
		invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId(invocationId)
			.runConfig(mockRunConfig)
			.build();
		// Act
		BaseAgent result = invocationContext.agent();
		// Assert
		assertNotNull(result);
		assertSame(mockAgent, result);
		assertEquals(invocationId, invocationContext.invocationId());
		assertSame(mockSession, invocationContext.session());
		assertSame(mockSessionService, invocationContext.sessionService());
	}

	@Test
	@Tag("integration")
	void agentFieldParticipatesInEquality() {
		// Arrange
		InvocationContext context1 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("inv-equality-test")
			.runConfig(mockRunConfig)
			.build();
		InvocationContext context2 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("inv-equality-test")
			.runConfig(mockRunConfig)
			.build();
		InvocationContext context3 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent2)
			.session(mockSession)
			.invocationId("inv-equality-test")
			.runConfig(mockRunConfig)
			.build();
		// Act & Assert
		assertSame(mockAgent, context1.agent());
		assertSame(mockAgent, context2.agent());
		assertSame(mockAgent2, context3.agent());
		assertEquals(context1, context2, "Contexts with same fields including agent should be equal");
		assertNotEquals(context1, context3, "Contexts with different agents should not be equal");
	}

	@Test
	@Tag("valid")
	void agentSetViaSetterOverridesBuilderValue() {
		// Arrange
		invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("inv-override-test")
			.runConfig(mockRunConfig)
			.build();
		// Verify initial state
		assertSame(mockAgent, invocationContext.agent());
		// Act
		invocationContext.agent(mockAgent2);
		// Assert
		assertSame(mockAgent2, invocationContext.agent());
		assertNotSame(mockAgent, invocationContext.agent());
	}

	@Test
	@Tag("valid")
	void agentCanBeUpdatedMultipleTimes() {
		// Arrange
		BaseAgent mockAgent3 = mock(BaseAgent.class);
		invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("inv-multiple-updates")
			.runConfig(mockRunConfig)
			.build();
		// Act & Assert - Multiple updates
		assertSame(mockAgent, invocationContext.agent());
		invocationContext.agent(mockAgent2);
		assertSame(mockAgent2, invocationContext.agent());
		invocationContext.agent(mockAgent3);
		assertSame(mockAgent3, invocationContext.agent());
		invocationContext.agent(mockAgent);
		assertSame(mockAgent, invocationContext.agent());
	}

}
