/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=appName_a8fa25d446
ROOST_METHOD_SIG_HASH=appName_e2ea244c93

Scenario 1: Return Application Name from Session When App Name Is a Standard Non-Empty String

Details:
  TestName: appNameReturnsSessionAppName
  Description: Verifies that the appName() method correctly delegates to the session's appName() method and returns the exact string value provided during session setup. This is the primary happy-path scenario confirming the delegation chain works correctly.

Execution:
  Arrange:
    - Create a mock of Session.
    - Configure the mock Session to return a known non-empty string (e.g., "myApplication") when appName() is called.
    - Build an InvocationContext using InvocationContext.builder(), setting the mocked session via .session(mockSession).
    - Supply any other minimally required builder fields (e.g., sessionService, artifactService, agent) as mocks or stubs.
  Act:
    - Call invocationContext.appName() on the constructed InvocationContext instance.
  Assert:
    - Use assertEquals("myApplication", result) to confirm the returned value matches the value configured on the mock session.

Validation:
  This assertion confirms that InvocationContext.appName() faithfully delegates to session.appName() and returns whatever string the session reports as the application name. This is critical because the InvocationContext is the primary API surface used by agents and flows; any discrepancy between the stored session's app name and what InvocationContext reports would cause misrouting of requests.


---

Scenario 2: Return Application Name Containing Special Characters

Details:
  TestName: appNameReturnsSessionAppNameWithSpecialCharacters
  Description: Verifies that the appName() method correctly returns an application name that contains special characters, spaces, hyphens, underscores, and other non-alphanumeric characters without any transformation or truncation.

Execution:
  Arrange:
    - Create a mock of Session.
    - Configure the mock Session to return a string with special characters (e.g., "my-app_v2.0 (beta)") when appName() is called.
    - Build an InvocationContext using InvocationContext.builder() with the mocked session and other required mocked dependencies.
  Act:
    - Call invocationContext.appName() on the built InvocationContext instance.
  Assert:
    - Use assertEquals("my-app_v2.0 (beta)", result) to confirm the full special-character string is returned unchanged.

Validation:
  This scenario ensures that no string manipulation, trimming, or encoding is applied inside appName(). Since application names in enterprise environments can include version tags, environment markers, and other special characters, it is important that the method acts as a pure pass-through to the underlying session.


---

Scenario 3: Return Application Name When It Is a Single Character

Details:
  TestName: appNameReturnsSingleCharacterAppName
  Description: Verifies that appName() correctly handles and returns a minimally valid application name consisting of exactly one character, confirming there is no minimum-length enforcement inside the method.

Execution:
  Arrange:
    - Create a mock of Session.
    - Configure the mock Session to return a single-character string (e.g., "A") when appName() is called.
    - Build an InvocationContext using InvocationContext.builder() with the mocked session and other required mocked dependencies.
  Act:
    - Call invocationContext.appName() on the built InvocationContext instance.
  Assert:
    - Use assertEquals("A", result) to verify the single character is returned without modification.

Validation:
  This test guards against any accidental length validation or padding logic inside appName(). Even if a single-character name is unusual, the method must reflect whatever the session reports faithfully.


---

Scenario 4: Return Application Name When It Is a Very Long String

Details:
  TestName: appNameReturnsLongAppName
  Description: Verifies that appName() returns a very long application name string without truncation or any form of capping, confirming that no length limit is enforced within the method itself.

Execution:
  Arrange:
    - Create a mock of Session.
    - Generate a long string of, for example, 1000 characters (e.g., "a".repeat(1000)).
    - Configure the mock Session to return this long string when appName() is called.
    - Build an InvocationContext using InvocationContext.builder() with the mocked session.
  Act:
    - Call invocationContext.appName() on the built InvocationContext instance.
  Assert:
    - Use assertEquals("a".repeat(1000), result) to confirm the full length is preserved.

Validation:
  This test ensures that the appName() method contains no implicit string truncation. If a consuming system relies on the full application name for routing or authorization, even a single character truncation could introduce subtle bugs.


---

Scenario 5: Return Application Name Consistently on Multiple Invocations

Details:
  TestName: appNameReturnsSameValueOnMultipleCalls
  Description: Verifies that calling appName() multiple times on the same InvocationContext instance returns the same consistent value each time, confirming there is no stateful mutation or random behavior inside the method.

Execution:
  Arrange:
    - Create a mock of Session.
    - Configure the mock Session to return "consistentApp" when appName() is called.
    - Build an InvocationContext using InvocationContext.builder() with the mocked session.
  Act:
    - Call invocationContext.appName() three separate times, storing each result.
  Assert:
    - Use assertEquals on all three results against "consistentApp" to confirm consistency.
    - Optionally use assertEquals(firstResult, secondResult) and assertEquals(secondResult, thirdResult).

Validation:
  Idempotency of the appName() method is essential for thread safety and predictability. Since InvocationContext is used across multiple processing steps in a single invocation, all components must observe the same application name throughout the lifecycle.


---

Scenario 6: Return Application Name When InvocationContext Is a Copy Created via copyOf

Details:
  TestName: appNameReturnedFromCopiedContext
  Description: Verifies that when an InvocationContext is duplicated using the static copyOf() method, the resulting copy also returns the same application name as the original, because the session reference is shared in the shallow copy.

Execution:
  Arrange:
    - Create a mock of Session.
    - Configure the mock Session to return "originalApp" when appName() is called.
    - Build an original InvocationContext using InvocationContext.builder() with the mocked session and all required dependencies.
    - Call InvocationContext.copyOf(originalContext) to obtain a copy.
  Act:
    - Call appName() on both the original and the copied InvocationContext instances.
  Assert:
    - Use assertEquals("originalApp", originalResult) and assertEquals("originalApp", copiedResult) to confirm both contexts report the same application name.

Validation:
  The copyOf() method performs a shallow copy, meaning the session reference is shared. This test confirms that the application name is accessible through both the original and any derived contexts, which is important when sub-agents or delegated flows create child contexts from a parent context.


---

Scenario 7: Return Application Name with a Numeric-Only String

Details:
  TestName: appNameReturnsNumericOnlyString
  Description: Verifies that appName() correctly returns an application name that consists entirely of numeric characters, confirming that no type conversion or parsing is applied to the session's returned string.

Execution:
  Arrange:
    - Create a mock of Session.
    - Configure the mock Session to return a numeric string (e.g., "123456") when appName() is called.
    - Build an InvocationContext using InvocationContext.builder() with the mocked session and required dependencies.
  Act:
    - Call invocationContext.appName() on the built InvocationContext instance.
  Assert:
    - Use assertEquals("123456", result) to verify the numeric string is returned as-is.

Validation:
  Some application naming conventions use numeric identifiers. This test ensures the appName() method treats the return value as a plain string without any implicit numeric conversion, which could result in loss of leading zeros or unexpected formatting.


---

Scenario 8: Return Application Name When Session Is Provided via Deprecated Constructor

Details:
  TestName: appNameReturnedWhenContextBuiltWithDeprecatedConstructor
  Description: Verifies that when an InvocationContext is constructed using one of the deprecated constructors, the appName() method still correctly returns the application name from the session, confirming backward compatibility.

Execution:
  Arrange:
    - Create mocks for BaseSessionService, BaseArtifactService, BaseMemoryService, PluginManager, BaseAgent, and Session.
    - Configure the mock Session to return "legacyApp" when appName() is called.
    - Construct an InvocationContext using the deprecated constructor that accepts BaseSessionService, BaseArtifactService, BaseMemoryService, PluginManager, Optional<LiveRequestQueue>, Optional<String> branch, String invocationId, BaseAgent, Session, Optional<Content>, RunConfig, and boolean endInvocation.
  Act:
    - Call invocationContext.appName() on the constructed InvocationContext instance.
  Assert:
    - Use assertEquals("legacyApp", result) to confirm the application name is correctly returned.

Validation:
  Even though the deprecated constructors are marked for removal, they are still in active use in existing codebases. This test ensures that migration paths and legacy integrations continue to function correctly and that appName() behaves identically regardless of how the InvocationContext was instantiated.


---

Scenario 9: Verify appName() Calls Session's appName() Exactly Once Per Invocation

Details:
  TestName: appNameDelegatesExactlyOnceToSession
  Description: Verifies that for a single call to InvocationContext.appName(), the underlying session.appName() method is called exactly once, confirming there is no caching layer, no extra calls, and no skipping of the delegation.

Execution:
  Arrange:
    - Create a mock of Session using a mocking framework such as Mockito.
    - Configure the mock Session to return "delegationApp" when appName() is called.
    - Build an InvocationContext using InvocationContext.builder() with the mocked session and other required dependencies.
  Act:
    - Call invocationContext.appName() exactly once.
  Assert:
    - Use Mockito.verify(mockSession, times(1)).appName() to confirm session.appName() was called exactly once.
    - Additionally use assertEquals("delegationApp", result) to confirm the correct value was returned.

Validation:
  This test validates the delegation contract between InvocationContext and Session. If multiple calls were made internally, it could indicate unintended behavior such as logging, auditing side effects, or retry logic. Exactly one delegation call confirms the method is a pure, lightweight wrapper.


---

Scenario 10: Return Application Name When InvocationContext Is Built Using the Static create() Method

Details:
  TestName: appNameReturnedWhenContextCreatedViaStaticCreateMethod
  Description: Verifies that when an InvocationContext is created using the deprecated static create() factory method that accepts sessionService, artifactService, invocationId, agent, session, userContent, and runConfig, the appName() method still correctly returns the application name from the session.

Execution:
  Arrange:
    - Create mocks for BaseSessionService, BaseArtifactService, BaseAgent, and Session.
    - Configure the mock Session to return "staticFactoryApp" when appName() is called.
    - Call InvocationContext.create(mockSessionService, mockArtifactService, "inv-001", mockAgent, mockSession, null, RunConfig.builder().build()) to obtain an InvocationContext instance.
  Act:
    - Call invocationContext.appName() on the resulting InvocationContext instance.
  Assert:
    - Use assertEquals("staticFactoryApp", result) to verify the returned value matches the session's app name.

Validation:
  The static create() factory methods were the primary construction mechanism before the builder pattern was introduced. Verifying that appName() works correctly with these factory-created instances ensures that any legacy calling code continues to receive accurate application name information without requiring migration to the builder pattern.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class InvocationContextAppNameTest {

	@Mock
	private BaseSessionService mockSessionService;

	@Mock
	private BaseArtifactService mockArtifactService;

	@Mock
	private BaseMemoryService mockMemoryService;

	@Mock
	private PluginManager mockPluginManager;

	@Mock
	private BaseAgent mockAgent;

	@Mock
	private Session mockSession;

	private RunConfig defaultRunConfig;

	@BeforeEach
	void setUp() {
		defaultRunConfig = RunConfig.builder().build();
	}

	private InvocationContext buildDefaultContext(Session session) {
		return InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(session)
			.userContent(Optional.empty())
			.runConfig(defaultRunConfig)
			.build();
	}

	@Test
  @Tag("valid")
  void appNameReturnsSessionAppName() {
    when(mockSession.appName()).thenReturn("myApplication");
    InvocationContext invocationContext = buildDefaultContext(mockSession);
    String result = invocationContext.appName();
    assertEquals("myApplication", result);
  }

	@Test
  @Tag("valid")
  void appNameReturnsSessionAppNameWithSpecialCharacters() {
    when(mockSession.appName()).thenReturn("my-app_v2.0 (beta)");
    InvocationContext invocationContext = buildDefaultContext(mockSession);
    String result = invocationContext.appName();
    assertEquals("my-app_v2.0 (beta)", result);
  }

	@Test
  @Tag("boundary")
  void appNameReturnsSingleCharacterAppName() {
    when(mockSession.appName()).thenReturn("A");
    InvocationContext invocationContext = buildDefaultContext(mockSession);
    String result = invocationContext.appName();
    assertEquals("A", result);
  }

	@Test
	@Tag("boundary")
	void appNameReturnsLongAppName() {
		String longAppName = "a".repeat(1000);
		when(mockSession.appName()).thenReturn(longAppName);
		InvocationContext invocationContext = buildDefaultContext(mockSession);
		String result = invocationContext.appName();
		assertEquals(longAppName, result);
		assertEquals(1000, result.length());
	}

	@Test
  @Tag("valid")
  void appNameReturnsSameValueOnMultipleCalls() {
    when(mockSession.appName()).thenReturn("consistentApp");
    InvocationContext invocationContext = buildDefaultContext(mockSession);
    String firstResult = invocationContext.appName();
    String secondResult = invocationContext.appName();
    String thirdResult = invocationContext.appName();
    assertEquals("consistentApp", firstResult);
    assertEquals("consistentApp", secondResult);
    assertEquals("consistentApp", thirdResult);
    assertEquals(firstResult, secondResult);
    assertEquals(secondResult, thirdResult);
  }

	@Test
  @Tag("integration")
  void appNameReturnedFromCopiedContext() {
    when(mockSession.appName()).thenReturn("originalApp");
    InvocationContext originalContext = buildDefaultContext(mockSession);
    InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
    String originalResult = originalContext.appName();
    String copiedResult = copiedContext.appName();
    assertEquals("originalApp", originalResult);
    assertEquals("originalApp", copiedResult);
    assertEquals(originalResult, copiedResult);
  }

	@Test
  @Tag("valid")
  void appNameReturnsNumericOnlyString() {
    when(mockSession.appName()).thenReturn("123456");
    InvocationContext invocationContext = buildDefaultContext(mockSession);
    String result = invocationContext.appName();
    assertEquals("123456", result);
  }

	@Test
  @Tag("valid")
  @SuppressWarnings("deprecation")
  void appNameReturnedWhenContextBuiltWithDeprecatedConstructor() {
    when(mockSession.appName()).thenReturn("legacyApp");
    InvocationContext invocationContext =
        new InvocationContext(
            mockSessionService,
            mockArtifactService,
            mockMemoryService,
            mockPluginManager,
            Optional.empty(),
            Optional.empty(),
            "legacy-invocation-id",
            mockAgent,
            mockSession,
            Optional.empty(),
            defaultRunConfig,
            false);
    String result = invocationContext.appName();
    assertEquals("legacyApp", result);
  }

	@Test
  @Tag("valid")
  void appNameDelegatesExactlyOnceToSession() {
    when(mockSession.appName()).thenReturn("delegationApp");
    InvocationContext invocationContext = buildDefaultContext(mockSession);
    String result = invocationContext.appName();
    assertEquals("delegationApp", result);
    verify(mockSession, times(1)).appName();
  }

	@Test
  @Tag("integration")
  void appNameReturnedWhenContextCreatedViaStaticCreateMethod() {
    when(mockSession.appName()).thenReturn("staticFactoryApp");
    InvocationContext invocationContext =
        InvocationContext.create(
            mockSessionService,
            mockArtifactService,
            "inv-001",
            mockAgent,
            mockSession,
            null,
            defaultRunConfig);
    String result = invocationContext.appName();
    assertEquals("staticFactoryApp", result);
  }

	@Test
  @Tag("valid")
  void appNameReturnedFromBuilderWithAllFieldsSet() {
    when(mockSession.appName()).thenReturn("fullBuilderApp");
    InvocationContext invocationContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .memoryService(mockMemoryService)
            .pluginManager(mockPluginManager)
            .liveRequestQueue(Optional.empty())
            .branch(Optional.empty())
            .invocationId("full-invocation-id")
            .agent(mockAgent)
            .session(mockSession)
            .userContent(Optional.empty())
            .runConfig(defaultRunConfig)
            .endInvocation(false)
            .build();
    String result = invocationContext.appName();
    assertEquals("fullBuilderApp", result);
  }

	@Test
  @Tag("valid")
  void appNameReturnedFromContextWithBranchSet() {
    when(mockSession.appName()).thenReturn("branchedApp");
    InvocationContext invocationContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId("branched-invocation-id")
            .agent(mockAgent)
            .session(mockSession)
            .userContent(Optional.empty())
            .runConfig(defaultRunConfig)
            .branch("parentAgent.childAgent")
            .build();
    String result = invocationContext.appName();
    assertEquals("branchedApp", result);
  }

	@Test
  @Tag("valid")
  void appNameReturnedWhenContextCreatedViaSecondStaticCreateMethod() {
    when(mockSession.appName()).thenReturn("liveContextApp");
    LiveRequestQueue liveRequestQueue = new LiveRequestQueue();
    InvocationContext invocationContext =
        InvocationContext.create(
            mockSessionService,
            mockArtifactService,
            mockAgent,
            mockSession,
            liveRequestQueue,
            defaultRunConfig);
    String result = invocationContext.appName();
    assertEquals("liveContextApp", result);
  }

	@Test
  @Tag("boundary")
  void appNameReturnsEmptyStringWhenSessionReturnsEmptyString() {
    when(mockSession.appName()).thenReturn("");
    InvocationContext invocationContext = buildDefaultContext(mockSession);
    String result = invocationContext.appName();
    assertEquals("", result);
  }

	@Test
	@Tag("valid")
	void appNameReturnsDifferentValuesForDifferentSessions() {
		Session anotherMockSession = mock(Session.class);
		when(mockSession.appName()).thenReturn("appOne");
		when(anotherMockSession.appName()).thenReturn("appTwo");
		InvocationContext contextOne = buildDefaultContext(mockSession);
		InvocationContext contextTwo = buildDefaultContext(anotherMockSession);
		String resultOne = contextOne.appName();
		String resultTwo = contextTwo.appName();
		assertEquals("appOne", resultOne);
		assertEquals("appTwo", resultTwo);
	}

	@Test
  @Tag("valid")
  void appNameReturnedWithUnicodeCharacters() {
    when(mockSession.appName()).thenReturn("アプリケーション名");
    InvocationContext invocationContext = buildDefaultContext(mockSession);
    String result = invocationContext.appName();
    assertEquals("アプリケーション名", result);
  }

	@Test
  @Tag("valid")
  void appNameVerifySessionInteractionOnMultipleCalls() {
    when(mockSession.appName()).thenReturn("multiCallApp");
    InvocationContext invocationContext = buildDefaultContext(mockSession);
    invocationContext.appName();
    invocationContext.appName();
    invocationContext.appName();
    verify(mockSession, times(3)).appName();
  }

}
