/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=branch_5cdb3cf131
ROOST_METHOD_SIG_HASH=branch_38b042f6d4

Scenario 1: Verify that branch() returns an empty Optional when no branch is set during construction

Details:
  TestName: branchReturnsEmptyOptionalWhenNotSet
  Description: Verifies that when an InvocationContext is built without explicitly setting a branch value,
               the branch() method returns an empty Optional, confirming the default state is Optional.empty().

Execution:
  Arrange: Build an InvocationContext using InvocationContext.builder() without calling .branch(...),
           providing only the minimum required fields (e.g., sessionService, artifactService, session, agent).
  Act: Call branch() on the constructed InvocationContext instance.
  Assert: Assert that the returned Optional is empty using assertTrue(context.branch().isEmpty()).

Validation:
  This test ensures that the default value of the branch field is Optional.empty() as initialized
  in the Builder. It is important for application behavior because callers depending on branch()
  must correctly handle the absent case to avoid NullPointerExceptions or incorrect routing logic.

*/

// ********RoostGPT********

```java
package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.events.Event;
import com.google.adk.flows.llmflows.ResumabilityConfig;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.models.LlmCallsLimitExceededException;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.genai.types.Content;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.junit.jupiter.api.*;
import com.google.common.collect.ImmutableSet;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import com.google.errorprone.annotations.InlineMe;
import com.google.genai.types.FunctionCall;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import javax.annotation.Nullable;

@ExtendWith(MockitoExtension.class)
public class InvocationContextBranch941Test {

	@Mock
	private BaseSessionService mockSessionService;

	@Mock
	private BaseArtifactService mockArtifactService;

	@Mock
	private BaseMemoryService mockMemoryService;

	@Mock
	private PluginManager mockPluginManager;

	@Mock
	private BaseAgent mockAgent;

	@Mock
	private Session mockSession;

	@Mock
	private RunConfig mockRunConfig;

	@BeforeEach
    void setUp() {
        when(mockSession.appName()).thenReturn("testApp");
        when(mockSession.userId()).thenReturn("testUser");
        when(mockSession.id()).thenReturn("testSessionId");
    }

	@Test
	@Tag("valid")
	void branchReturnsEmptyOptionalWhenNotSet() {
		// Arrange
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		// Act
		Optional<String> result = context.branch();
		// Assert
		assertTrue(result.isEmpty(), "Branch should be empty when not set during construction");
	}

	@Test
	@Tag("valid")
	void branchReturnsCorrectValueWhenSetAsString() {
		// Arrange
		String expectedBranch = "agentA.agentB.agentC";
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.branch(expectedBranch)
			.build();
		// Act
		Optional<String> result = context.branch();
		// Assert
		assertTrue(result.isPresent(), "Branch should be present when set");
		assertEquals(expectedBranch, result.get(), "Branch value should match what was set");
	}

	@Test
	@Tag("valid")
	void branchReturnsCorrectValueWhenSetAsOptional() {
		// Arrange
		String expectedBranch = "agentA.agentB";
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.branch(Optional.of(expectedBranch))
			.build();
		// Act
		Optional<String> result = context.branch();
		// Assert
		assertTrue(result.isPresent(), "Branch should be present when set as Optional");
		assertEquals(expectedBranch, result.get(), "Branch value should match what was set");
	}

	@Test
	@Tag("valid")
	void branchReturnsEmptyOptionalWhenSetAsEmptyOptional() {
		// Arrange
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.branch(Optional.empty())
			.build();
		// Act
		Optional<String> result = context.branch();
		// Assert
		assertTrue(result.isEmpty(), "Branch should be empty when set as Optional.empty()");
	}

	@Test
	@Tag("valid")
	void branchReturnsUpdatedValueAfterMutation() {
		// Arrange
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		// Act
		context.branch("newBranch.subBranch");
		Optional<String> result = context.branch();
		// Assert
		assertTrue(result.isPresent(), "Branch should be present after mutation");
		assertEquals("newBranch.subBranch", result.get(), "Branch value should match the updated value");
	}

	@Test
	@Tag("valid")
	void branchReturnsEmptyAfterSettingNullViaSetterMethod() {
		// Arrange
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.branch("initialBranch")
			.build();
		// Act
		context.branch((String) null);
		Optional<String> result = context.branch();
		// Assert
		assertTrue(result.isEmpty(), "Branch should be empty after setting null via setter");
	}

	@Test
	@Tag("boundary")
	void branchReturnsOptionalWithEmptyStringWhenSetToEmptyString() {
		// Arrange
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.branch("")
			.build();
		// Act
		Optional<String> result = context.branch();
		// Assert
		assertTrue(result.isPresent(), "Branch should be present when set to an empty string");
		assertEquals("", result.get(), "Branch value should be an empty string");
	}

	@Test
	@Tag("boundary")
	void branchReturnsOptionalWithSingleAgentName() {
		// Arrange
		String singleAgent = "agentA";
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.branch(singleAgent)
			.build();
		// Act
		Optional<String> result = context.branch();
		// Assert
		assertTrue(result.isPresent(), "Branch should be present for single agent");
		assertEquals(singleAgent, result.get(), "Branch value should match single agent name");
	}

	@Test
	@Tag("boundary")
	void branchReturnsOptionalWithLongHierarchicalName() {
		// Arrange
		String longBranch = "agentA.agentB.agentC.agentD.agentE.agentF";
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.branch(longBranch)
			.build();
		// Act
		Optional<String> result = context.branch();
		// Assert
		assertTrue(result.isPresent(), "Branch should be present for long hierarchical name");
		assertEquals(longBranch, result.get(), "Branch value should match the long hierarchical name");
	}

	@Test
	@Tag("valid")
	void branchPreservedInCopyOf() {
		// Arrange
		String branchValue = "parentAgent.childAgent";
		InvocationContext original = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.branch(branchValue)
			.build();
		// Act
		InvocationContext copy = InvocationContext.copyOf(original);
		Optional<String> result = copy.branch();
		// Assert
		assertTrue(result.isPresent(), "Branch should be present in copied context");
		assertEquals(branchValue, result.get(), "Branch value should be preserved in copy");
	}

	@Test
	@Tag("valid")
	void branchEmptyPreservedInCopyOf() {
		// Arrange
		InvocationContext original = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		// Act
		InvocationContext copy = InvocationContext.copyOf(original);
		Optional<String> result = copy.branch();
		// Assert
		assertTrue(result.isEmpty(), "Branch should remain empty in copied context when not originally set");
	}

	@Test
	@Tag("valid")
	void branchMutationOnCopyDoesNotAffectOriginal() {
		// Arrange
		String originalBranch = "originalAgent";
		InvocationContext original = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.branch(originalBranch)
			.build();
		InvocationContext copy = InvocationContext.copyOf(original);
		// Act
		copy.branch("newBranch.newChild");
		// Assert
		Optional<String> originalResult = original.branch();
		Optional<String> copyResult = copy.branch();
		assertTrue(originalResult.isPresent(), "Original branch should still be present");
		assertEquals(originalBranch, originalResult.get(), "Original branch should not change when copy is mutated");
		assertTrue(copyResult.isPresent(), "Copy branch should be present after mutation");
		assertEquals("newBranch.newChild", copyResult.get(), "Copy branch should have new value");
	}

	@Test
	@Tag("valid")
	void branchReturnTypeIsOptional() {
		// Arrange
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		// Act
		Object result = context.branch();
		// Assert
		assertNotNull(result, "branch() should not return null, it should return Optional.empty()");
		assertInstanceOf(Optional.class, result, "branch() should return an Optional type");
	}

	@Test
	@Tag("valid")
	void branchUsedInCreateStaticFactory() {
		// Arrange
		Content userContent = mock(Content.class);
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService,
				"test-invocation-id", mockAgent, mockSession, userContent, mockRunConfig);
		// Act
		Optional<String> result = context.branch();
		// Assert
		assertNotNull(result, "branch() should not return null when created via static factory");
		assertTrue(result.isEmpty(), "Branch should be empty when created via static factory without branch");
	}

	@Test
	@Tag("integration")
	void branchConsistentAcrossMultipleCallsOnSameContext() {
		// Arrange
		String branchValue = "agent1.agent2.agent3";
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.branch(branchValue)
			.build();
		// Act
		Optional<String> result1 = context.branch();
		Optional<String> result2 = context.branch();
		Optional<String> result3 = context.branch();
		// Assert
		assertEquals(result1, result2, "branch() should return same value on repeated calls");
		assertEquals(result2, result3, "branch() should return same value on repeated calls");
		assertTrue(result1.isPresent(), "Branch should be consistently present");
		assertEquals(branchValue, result1.get(), "Branch value should be consistently correct");
	}

	@Test
    @Tag("integration")
    void branchUpdatesReflectedInSubsequentCalls() {
        // Arrange
        InvocationContext context = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("test-invocation-id")
                .agent(mockAgent)
                .session(mockSession)
                .userContent(Optional.empty())
                .runConfig(mockRunConfig)
                .build();
        // Act & Assert - Initial state
        assertTrue(context.branch().isEmpty(), "Initially branch should be empty");
        // Mutate branch
        context.branch("firstBranch");
        assertTrue(context.branch().isPresent(), "Branch should be present after first update");
        assertEquals("firstBranch", context.branch().get(), "Branch should reflect first update");
        // Mutate branch again
        context.branch("firstBranch.secondBranch");
        assertTrue(context.branch().isPresent(), "Branch should be present after second update");
        assertEquals("firstBranch.secondBranch", context.branch().get(), "Branch should reflect second update");
    }

@Test
    @Tag("valid")
    void branchWithSpecialCharactersInName() {
        // Arrange
        String specialBranch = "agent-1.agent_2.agent3";
        InvocationContext context = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocation