/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=activeStreamingTools_c4cc5030aa
ROOST_METHOD_SIG_HASH=activeStreamingTools_398f84db97

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/june-java-unit/1782282457/source/adk-java/core/src/test/java/com/google/adk/agents/InvocationContextTest.java
Tests:
    "@Test
public void testCopyOf() {
    InvocationContext originalContext = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    originalContext.activeStreamingTools().putAll(activeStreamingTools);
    InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
    assertThat(copiedContext).isNotNull();
    assertThat(copiedContext).isNotSameInstanceAs(originalContext);
    assertThat(copiedContext.sessionService()).isEqualTo(originalContext.sessionService());
    assertThat(copiedContext.artifactService()).isEqualTo(originalContext.artifactService());
    assertThat(copiedContext.memoryService()).isEqualTo(originalContext.memoryService());
    assertThat(copiedContext.liveRequestQueue()).isEqualTo(originalContext.liveRequestQueue());
    assertThat(copiedContext.invocationId()).isEqualTo(originalContext.invocationId());
    assertThat(copiedContext.agent()).isEqualTo(originalContext.agent());
    assertThat(copiedContext.session()).isEqualTo(originalContext.session());
    assertThat(copiedContext.userContent()).isEqualTo(originalContext.userContent());
    assertThat(copiedContext.runConfig()).isEqualTo(originalContext.runConfig());
    assertThat(copiedContext.endInvocation()).isEqualTo(originalContext.endInvocation());
    assertThat(copiedContext.activeStreamingTools()).isEqualTo(originalContext.activeStreamingTools());
}
"Scenario 1: Verify activeStreamingTools Returns an Empty Map on Freshly Built InvocationContext

Details:
  TestName: activeStreamingToolsReturnsEmptyMapOnFreshContext
  Description: Verifies that when a new InvocationContext is built using the builder with no streaming tools added,
               the activeStreamingTools() method returns an empty (but non-null) map. This confirms the field is
               properly initialized as an empty ConcurrentHashMap.

Execution:
  Arrange: Build an InvocationContext using InvocationContext.builder() with the required fields
           (sessionService, artifactService, memoryService, pluginManager, invocationId, agent, session,
           userContent, runConfig, endInvocation) without adding any active streaming tools.
  Act: Call activeStreamingTools() on the newly built InvocationContext instance.
  Assert: Assert that the returned map is not null.
          Assert that the returned map is empty (size == 0).

Validation:
  The assertion verifies that the ConcurrentHashMap backing activeStreamingTools is initialized to an empty state
  by default. This is important to ensure that no stale or unexpected tool entries exist at the start of a new
  invocation, preventing incorrect behavior in streaming tool management.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.genai.types.Content;
import java.util.Map;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class InvocationContextActiveStreamingToolsTest {

	@Mock
	private BaseSessionService mockSessionService;

	@Mock
	private BaseArtifactService mockArtifactService;

	@Mock
	private BaseMemoryService mockMemoryService;

	@Mock
	private PluginManager mockPluginManager;

	@Mock
	private Session mockSession;

	@Mock
	private BaseAgent mockAgent;

	@Mock
	private RunConfig mockRunConfig;

	@Mock
	private ActiveStreamingTool mockActiveTool1;

	@Mock
	private ActiveStreamingTool mockActiveTool2;

	private InvocationContext invocationContext;

	@BeforeEach
  void setUp() {
    when(mockSession.appName()).thenReturn("testApp");
    when(mockSession.userId()).thenReturn("testUser");
    invocationContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .memoryService(mockMemoryService)
            .pluginManager(mockPluginManager)
            .invocationId("test-invocation-id")
            .agent(mockAgent)
            .session(mockSession)
            .userContent(Optional.empty())
            .runConfig(mockRunConfig)
            .endInvocation(false)
            .build();
  }

	@Test
	@Tag("valid")
	void activeStreamingToolsReturnsEmptyMapOnFreshContext() {
		// Act
		Map<String, ActiveStreamingTool> result = invocationContext.activeStreamingTools();
		// Assert
		assertNotNull(result, "activeStreamingTools map should not be null");
		assertTrue(result.isEmpty(), "activeStreamingTools map should be empty on a freshly built context");
		assertEquals(0, result.size(), "activeStreamingTools map size should be 0 on a freshly built context");
	}

	@Test
	@Tag("valid")
	void activeStreamingToolsReturnsSameMapInstance() {
		// Act
		Map<String, ActiveStreamingTool> result1 = invocationContext.activeStreamingTools();
		Map<String, ActiveStreamingTool> result2 = invocationContext.activeStreamingTools();
		// Assert
		assertSame(result1, result2, "activeStreamingTools should return the same map instance on repeated calls");
	}

	@Test
	@Tag("valid")
	void activeStreamingToolsReturnsMapWithAddedTool() {
		// Arrange
		Map<String, ActiveStreamingTool> tools = invocationContext.activeStreamingTools();
		tools.put("tool1", mockActiveTool1);
		// Act
		Map<String, ActiveStreamingTool> result = invocationContext.activeStreamingTools();
		// Assert
		assertNotNull(result);
		assertEquals(1, result.size());
		assertTrue(result.containsKey("tool1"));
		assertEquals(mockActiveTool1, result.get("tool1"));
	}

	@Test
	@Tag("valid")
	void activeStreamingToolsReturnsMapWithMultipleTools() {
		// Arrange
		Map<String, ActiveStreamingTool> tools = invocationContext.activeStreamingTools();
		tools.put("tool1", mockActiveTool1);
		tools.put("tool2", mockActiveTool2);
		// Act
		Map<String, ActiveStreamingTool> result = invocationContext.activeStreamingTools();
		// Assert
		assertNotNull(result);
		assertEquals(2, result.size());
		assertTrue(result.containsKey("tool1"));
		assertTrue(result.containsKey("tool2"));
		assertEquals(mockActiveTool1, result.get("tool1"));
		assertEquals(mockActiveTool2, result.get("tool2"));
	}

	@Test
	@Tag("valid")
	void activeStreamingToolsMapIsMutableAndReflectsRemovals() {
		// Arrange
		Map<String, ActiveStreamingTool> tools = invocationContext.activeStreamingTools();
		tools.put("tool1", mockActiveTool1);
		tools.put("tool2", mockActiveTool2);
		// Act
		tools.remove("tool1");
		Map<String, ActiveStreamingTool> result = invocationContext.activeStreamingTools();
		// Assert
		assertNotNull(result);
		assertEquals(1, result.size());
		assertFalse(result.containsKey("tool1"));
		assertTrue(result.containsKey("tool2"));
	}

	@Test
	@Tag("valid")
	void activeStreamingToolsIsNotNullWhenBuiltWithMinimalFields() {
		// Arrange
		InvocationContext minimalContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.session(mockSession)
			.agent(mockAgent)
			.runConfig(mockRunConfig)
			.build();
		// Act
		Map<String, ActiveStreamingTool> result = minimalContext.activeStreamingTools();
		// Assert
		assertNotNull(result, "activeStreamingTools should not be null even with minimal builder setup");
		assertTrue(result.isEmpty(), "activeStreamingTools should be empty on minimal context");
	}

	@Test
	@Tag("valid")
	void activeStreamingToolsCopiedCorrectlyViaCopyOf() {
		// Arrange
		Map<String, ActiveStreamingTool> tools = invocationContext.activeStreamingTools();
		tools.put("tool1", mockActiveTool1);
		// Act
		InvocationContext copiedContext = InvocationContext.copyOf(invocationContext);
		Map<String, ActiveStreamingTool> copiedTools = copiedContext.activeStreamingTools();
		// Assert
		assertNotNull(copiedTools);
		assertEquals(1, copiedTools.size());
		assertTrue(copiedTools.containsKey("tool1"));
		assertEquals(mockActiveTool1, copiedTools.get("tool1"));
	}

	@Test
	@Tag("valid")
	void activeStreamingToolsCopyIsIndependentFromOriginal() {
		// Arrange
		Map<String, ActiveStreamingTool> tools = invocationContext.activeStreamingTools();
		tools.put("tool1", mockActiveTool1);
		InvocationContext copiedContext = InvocationContext.copyOf(invocationContext);
		// Act - modify the copy
		copiedContext.activeStreamingTools().put("tool2", mockActiveTool2);
		// Assert - original should still have only tool1
		assertEquals(1, invocationContext.activeStreamingTools().size());
		assertEquals(2, copiedContext.activeStreamingTools().size());
	}

	@Test
	@Tag("valid")
	void activeStreamingToolsEmptyOnCopyOfFreshContext() {
		// Arrange
		InvocationContext freshContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.session(mockSession)
			.agent(mockAgent)
			.runConfig(mockRunConfig)
			.build();
		// Act
		InvocationContext copiedContext = InvocationContext.copyOf(freshContext);
		Map<String, ActiveStreamingTool> result = copiedContext.activeStreamingTools();
		// Assert
		assertNotNull(result);
		assertTrue(result.isEmpty());
	}

	@Test
	@Tag("valid")
	void activeStreamingToolsMapKeySet() {
		// Arrange
		Map<String, ActiveStreamingTool> tools = invocationContext.activeStreamingTools();
		tools.put("toolAlpha", mockActiveTool1);
		tools.put("toolBeta", mockActiveTool2);
		// Act
		Map<String, ActiveStreamingTool> result = invocationContext.activeStreamingTools();
		// Assert
		assertNotNull(result);
		assertTrue(result.keySet().contains("toolAlpha"));
		assertTrue(result.keySet().contains("toolBeta"));
		assertEquals(2, result.keySet().size());
	}

	@Test
	@Tag("valid")
	void activeStreamingToolsMapValuesContainExpectedTools() {
		// Arrange
		Map<String, ActiveStreamingTool> tools = invocationContext.activeStreamingTools();
		tools.put("tool1", mockActiveTool1);
		tools.put("tool2", mockActiveTool2);
		// Act
		Map<String, ActiveStreamingTool> result = invocationContext.activeStreamingTools();
		// Assert
		assertNotNull(result);
		assertTrue(result.values().contains(mockActiveTool1));
		assertTrue(result.values().contains(mockActiveTool2));
	}

	@Test
	@Tag("boundary")
	void activeStreamingToolsMapReturnsNullForMissingKey() {
		// Arrange
		Map<String, ActiveStreamingTool> tools = invocationContext.activeStreamingTools();
		tools.put("tool1", mockActiveTool1);
		// Act
		ActiveStreamingTool result = invocationContext.activeStreamingTools().get("nonExistentTool");
		// Assert
		assertNull(result, "Getting a non-existent key should return null");
	}

	@Test
	@Tag("boundary")
	void activeStreamingToolsMapHandlesClearOperation() {
		// Arrange
		Map<String, ActiveStreamingTool> tools = invocationContext.activeStreamingTools();
		tools.put("tool1", mockActiveTool1);
		tools.put("tool2", mockActiveTool2);
		// Act
		tools.clear();
		Map<String, ActiveStreamingTool> result = invocationContext.activeStreamingTools();
		// Assert
		assertNotNull(result);
		assertTrue(result.isEmpty());
		assertEquals(0, result.size());
	}

	@Test
	@Tag("boundary")
	void activeStreamingToolsMapOverwritesExistingKey() {
		// Arrange
		Map<String, ActiveStreamingTool> tools = invocationContext.activeStreamingTools();
		tools.put("tool1", mockActiveTool1);
		// Act
		tools.put("tool1", mockActiveTool2);
		Map<String, ActiveStreamingTool> result = invocationContext.activeStreamingTools();
		// Assert
		assertNotNull(result);
		assertEquals(1, result.size());
		assertEquals(mockActiveTool2, result.get("tool1"), "Value should be updated when same key is inserted");
	}

	@Test
	@Tag("integration")
	void activeStreamingToolsIntegratesWithCreateFactory() {
		// Arrange
		Content userContent = mock(Content.class);
		InvocationContext contextFromFactory = InvocationContext.create(mockSessionService, mockArtifactService,
				"integration-invocation-id", mockAgent, mockSession, userContent, mockRunConfig);
		// Act
		Map<String, ActiveStreamingTool> result = contextFromFactory.activeStreamingTools();
		// Assert
		assertNotNull(result, "activeStreamingTools should not be null from create factory");
		assertTrue(result.isEmpty(), "activeStreamingTools should be empty from create factory");
	}

	@Test
	@Tag("integration")
	void activeStreamingToolsIntegratesWithLiveCreateFactory() {
		// Arrange
		LiveRequestQueue liveRequestQueue = new LiveRequestQueue();
		InvocationContext contextFromFactory = InvocationContext.create(mockSessionService, mockArtifactService,
				mockAgent, mockSession, liveRequestQueue, mockRunConfig);
		// Act
		Map<String, ActiveStreamingTool> result = contextFromFactory.activeStreamingTools();
		// Assert
		assertNotNull(result, "activeStreamingTools should not be null from live create factory");
		assertTrue(result.isEmpty(), "activeStreamingTools should be empty from live create factory");
	}

	@Test
	@Tag("integration")
	void activeStreamingToolsUsedInEqualsComparison() {
		// Arrange
		InvocationContext context1 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.session(mockSession)
			.agent(mockAgent)
			.runConfig(mockRunConfig)
			.invocationId("same-id")
			.build();
		InvocationContext context2 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.session(mockSession)
			.agent(mockAgent)
			.runConfig(mockRunConfig)
			.invocationId("same-id")
			.build();
		// Both have empty activeStreamingTools
		// Act
		Map<String, ActiveStreamingTool> tools1 = context1.activeStreamingTools();
		Map<String, ActiveStreamingTool> tools2 = context2.activeStreamingTools();
		// Assert
		assertEquals(tools1, tools2, "Two fresh contexts should have equal (empty) activeStreamingTools maps");
		assertTrue(context1.equals(context2), "Two contexts with same fields should be equal");
	}

	@Test
	@Tag("integration")
	void activeStreamingToolsMutationAffectsEqualityCheck() {
		// Arrange
		InvocationContext context1 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.session(mockSession)
			.agent(mockAgent)
			.runConfig(mockRunConfig)
			.invocationId("same-id")
			.build();
		InvocationContext context2 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.session(mockSession)
			.agent(mockAgent)
			.runConfig(mockRunConfig)
			.invocationId("same-id")
			.build();
		// Act - modify one context's streaming tools
		context1.activeStreamingTools().put("tool1", mockActiveTool1);
		// Assert
		assertNotEquals(context1.activeStreamingTools(), context2.activeStreamingTools(),
				"After mutation, activeStreamingTools maps should differ");
		assertFalse(context1.equals(context2), "Contexts with different activeStreamingTools should not be equal");
	}

}
