/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=appName_a8fa25d446
ROOST_METHOD_SIG_HASH=appName_e2ea244c93

Scenario 1: Return Application Name from a Valid Session

Details:
  TestName: appNameReturnsSessionAppName
  Description: Verifies that the `appName()` method correctly delegates to the underlying
               `Session` object and returns the application name stored in the session.
               This is the primary happy-path scenario.
Execution:
  Arrange: - Create a mock `Session` object.
           - Configure the mock `Session` to return a specific, non-null string (e.g., "MyTestApp")
             when `appName()` is called on it.
           - Build an `InvocationContext` using `InvocationContext.builder()`, setting the
             mocked `Session` via `.session(mockSession)`, and providing any other required
             builder parameters (e.g., `sessionService`, `artifactService`, `agent`).
  Act:     - Call `invocationContext.appName()` on the constructed `InvocationContext` instance.
  Assert:  - Use `assertEquals("MyTestApp", invocationContext.appName())` to verify the
             return value matches the expected application name.
Validation:
  This assertion confirms that `appName()` correctly propagates the return value from
  `session.appName()` without any modification or transformation. It validates the
  delegation behavior that is fundamental to how `InvocationContext` exposes session data.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.flows.llmflows.ResumabilityConfig;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class InvocationContextAppNameTest {

	@Mock
	private BaseSessionService mockSessionService;

	@Mock
	private BaseArtifactService mockArtifactService;

	@Mock
	private BaseMemoryService mockMemoryService;

	@Mock
	private PluginManager mockPluginManager;

	@Mock
	private Session mockSession;

	@Mock
	private BaseAgent mockAgent;

	@Mock
	private ResumabilityConfig mockResumabilityConfig;

	private RunConfig defaultRunConfig;

	@BeforeEach
	void setUp() {
		defaultRunConfig = RunConfig.builder().build();
	}

	private InvocationContext buildContext(Session session) {
		return InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(session)
			.runConfig(defaultRunConfig)
			.invocationId("test-invocation-id")
			.build();
	}

	@Test
  @Tag("valid")
  void appNameReturnsSessionAppName() {
    when(mockSession.appName()).thenReturn("MyTestApp");
    InvocationContext invocationContext = buildContext(mockSession);
    String result = invocationContext.appName();
    assertEquals("MyTestApp", result);
    verify(mockSession, times(1)).appName();
  }

	@Test
  @Tag("valid")
  void appNameReturnsCorrectValueWhenSessionHasTypicalAppName() {
    when(mockSession.appName()).thenReturn("ProductionApp");
    InvocationContext invocationContext = buildContext(mockSession);
    String result = invocationContext.appName();
    assertEquals("ProductionApp", result);
    assertNotNull(result);
  }

	@Test
  @Tag("valid")
  void appNameDelegatesCallToUnderlyingSession() {
    when(mockSession.appName()).thenReturn("DelegationTestApp");
    InvocationContext invocationContext = buildContext(mockSession);
    invocationContext.appName();
    verify(mockSession).appName();
  }

	@Test
  @Tag("valid")
  void appNameReturnsSameValueOnMultipleCalls() {
    when(mockSession.appName()).thenReturn("StableApp");
    InvocationContext invocationContext = buildContext(mockSession);
    String firstCall = invocationContext.appName();
    String secondCall = invocationContext.appName();
    String thirdCall = invocationContext.appName();
    assertEquals("StableApp", firstCall);
    assertEquals("StableApp", secondCall);
    assertEquals("StableApp", thirdCall);
    assertEquals(firstCall, secondCall);
    assertEquals(secondCall, thirdCall);
    verify(mockSession, times(3)).appName();
  }

	@Test
  @Tag("valid")
  void appNameReturnsAppNameFromCreateStaticMethod() {
    when(mockSession.appName()).thenReturn("StaticCreateApp");
    InvocationContext invocationContext =
        InvocationContext.create(
            mockSessionService,
            mockArtifactService,
            "static-invocation-id",
            mockAgent,
            mockSession,
            null,
            defaultRunConfig);
    String result = invocationContext.appName();
    assertEquals("StaticCreateApp", result);
  }

	@Test
  @Tag("valid")
  void appNameReturnedFromCopiedContext() {
    when(mockSession.appName()).thenReturn("CopiedContextApp");
    InvocationContext originalContext = buildContext(mockSession);
    InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
    String result = copiedContext.appName();
    assertEquals("CopiedContextApp", result);
  }

	@Test
  @Tag("boundary")
  void appNameReturnsEmptyStringWhenSessionAppNameIsEmpty() {
    when(mockSession.appName()).thenReturn("");
    InvocationContext invocationContext = buildContext(mockSession);
    String result = invocationContext.appName();
    assertNotNull(result);
    assertEquals("", result);
  }

	@Test
  @Tag("boundary")
  void appNameReturnsSingleCharacterAppName() {
    when(mockSession.appName()).thenReturn("A");
    InvocationContext invocationContext = buildContext(mockSession);
    String result = invocationContext.appName();
    assertEquals("A", result);
    assertNotNull(result);
  }

	@Test
	@Tag("boundary")
	void appNameReturnsVeryLongAppName() {
		String longAppName = "A".repeat(1000);
		when(mockSession.appName()).thenReturn(longAppName);
		InvocationContext invocationContext = buildContext(mockSession);
		String result = invocationContext.appName();
		assertEquals(longAppName, result);
		assertNotNull(result);
		assertEquals(1000, result.length());
	}

	@Test
	@Tag("boundary")
	void appNameReturnsAppNameWithSpecialCharacters() {
		String specialAppName = "App-Name_With.Special@Characters#123";
		when(mockSession.appName()).thenReturn(specialAppName);
		InvocationContext invocationContext = buildContext(mockSession);
		String result = invocationContext.appName();
		assertEquals(specialAppName, result);
		assertNotNull(result);
	}

	@Test
  @Tag("boundary")
  void appNameReturnsAppNameWithWhitespace() {
    when(mockSession.appName()).thenReturn("  App With Spaces  ");
    InvocationContext invocationContext = buildContext(mockSession);
    String result = invocationContext.appName();
    assertEquals("  App With Spaces  ", result);
    assertNotNull(result);
  }

	@Test
  @Tag("boundary")
  void appNameReturnsNullWhenSessionAppNameIsNull() {
    when(mockSession.appName()).thenReturn(null);
    InvocationContext invocationContext = buildContext(mockSession);
    String result = invocationContext.appName();
    assertNull(result);
  }

	@Test
  @Tag("integration")
  void appNameWorksWithFullyConfiguredContext() {
    when(mockSession.appName()).thenReturn("FullyConfiguredApp");
    InvocationContext invocationContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .memoryService(mockMemoryService)
            .pluginManager(mockPluginManager)
            .agent(mockAgent)
            .session(mockSession)
            .runConfig(defaultRunConfig)
            .invocationId("full-invocation-id")
            .branch("main-branch")
            .userContent(Optional.empty())
            .build();
    String result = invocationContext.appName();
    assertEquals("FullyConfiguredApp", result);
    assertNotNull(result);
  }

	@Test
  @Tag("integration")
  void appNameConsistentBetweenOriginalAndCopiedContext() {
    when(mockSession.appName()).thenReturn("ConsistencyApp");
    InvocationContext originalContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .agent(mockAgent)
            .session(mockSession)
            .runConfig(defaultRunConfig)
            .invocationId("original-id")
            .build();
    InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
    assertEquals(originalContext.appName(), copiedContext.appName());
    assertEquals("ConsistencyApp", originalContext.appName());
    assertEquals("ConsistencyApp", copiedContext.appName());
  }

	@Test
  @Tag("integration")
  void appNameAndUserIdBothDelegateToSession() {
    when(mockSession.appName()).thenReturn("IntegrationApp");
    when(mockSession.userId()).thenReturn("user-123");
    InvocationContext invocationContext = buildContext(mockSession);
    String appName = invocationContext.appName();
    String userId = invocationContext.userId();
    assertEquals("IntegrationApp", appName);
    assertEquals("user-123", userId);
    verify(mockSession, times(1)).appName();
    verify(mockSession, times(1)).userId();
  }

	@Test
  @Tag("valid")
  void appNameWithNumericOnlyName() {
    when(mockSession.appName()).thenReturn("123456");
    InvocationContext invocationContext = buildContext(mockSession);
    String result = invocationContext.appName();
    assertEquals("123456", result);
    assertNotNull(result);
  }

	@Test
  @Tag("valid")
  void appNameWithUnicodeCharacters() {
    when(mockSession.appName()).thenReturn("应用程序");
    InvocationContext invocationContext = buildContext(mockSession);
    String result = invocationContext.appName();
    assertEquals("应用程序", result);
    assertNotNull(result);
  }

	@Test
  @Tag("integration")
  void appNameNotAffectedByAgentChange() {
    when(mockSession.appName()).thenReturn("AgentChangeApp");
    BaseAgent anotherMockAgent = mock(BaseAgent.class);
    InvocationContext invocationContext = buildContext(mockSession);
    String appNameBefore = invocationContext.appName();
    invocationContext.agent(anotherMockAgent);
    String appNameAfter = invocationContext.appName();
    assertEquals(appNameBefore, appNameAfter);
    assertEquals("AgentChangeApp", appNameBefore);
    assertEquals("AgentChangeApp", appNameAfter);
  }

	@Test
  @Tag("integration")
  void appNameNotAffectedByEndInvocationChange() {
    when(mockSession.appName()).thenReturn("EndInvocationApp");
    InvocationContext invocationContext = buildContext(mockSession);
    String appNameBefore = invocationContext.appName();
    invocationContext.setEndInvocation(true);
    String appNameAfter = invocationContext.appName();
    assertEquals(appNameBefore, appNameAfter);
    assertEquals("EndInvocationApp", appNameBefore);
    assertEquals("EndInvocationApp", appNameAfter);
  }

}
