/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=sessionService_c04b1de6f8
ROOST_METHOD_SIG_HASH=sessionService_1fa67a6550

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/june-java-unit/1782282926/source/adk-java/core/src/test/java/com/google/adk/agents/AgentWithMemoryTest.java
Tests:
    "@Test
public void agentRemembersUserNameWithMemoryTool() throws Exception {
    String userId = "test-user";
    String agentName = "test-agent";
    Part functionCall = Part.builder().functionCall(FunctionCall.builder().name("loadMemory").args(ImmutableMap.of("query", "what is my name?")).build()).build();
    TestLlm testLlm = new TestLlm(ImmutableList.of(LlmResponse.builder().content(Content.builder().parts(Part.fromText("OK, I'll remember that.")).role("model").build()).build(), LlmResponse.builder().content(Content.builder().role("model").parts(ImmutableList.of(functionCall)).build()).build(), LlmResponse.builder().content(Content.builder().

    parts(Part.fromText("Your name is James.")).role("model").build()).build()));
    LlmAgent agent = LlmAgent.builder().name(agentName).model(testLlm).tools(ImmutableList.of(new LoadMemoryTool())).build();
    InMemoryRunner runner = new InMemoryRunner(agent);
    String sessionId = runner.sessionService().createSession(agentName, userId).blockingGet().id();
    Content firstMessage = Content.fromParts(Part.fromText("My name is James"));
    var unused = runner.runAsync(userId, sessionId, firstMessage, RunConfig.builder().build()).toList().blockingGet();

    Session updatedSession = runner.sessionService().getSession("test-agent", userId, sessionId, Optional.empty()).blockingGet();

    runner.memoryService().addSessionToMemory(updatedSession).blockingAwait();
    Content secondMessage = Content.fromParts(Part.fromText("what is my name?"));
    unused = runner.runAsync(userId, updatedSession.id(), secondMessage, RunConfig.builder().build()).toList().blockingGet();

    LlmRequest lastRequest = testLlm.getLastRequest();
    Content functionResponseContent = Iterables.getLast(lastRequest.contents());
    Optional<Part> functionResponsePart = functionResponseContent.parts().get().stream().filter(p -> p.functionResponse().isPresent()).findFirst();
    assertThat(functionResponsePart).isPresent();
    FunctionResponse functionResponse = functionResponsePart.get().functionResponse().get();
    assertThat(functionResponse.name()).hasValue("loadMemory");
    assertThat(functionResponse.response().get().toString()).contains("My name is James");
}
"

File Path: /var/tmp/Roost/RoostGPT/june-java-unit/1782282926/source/adk-java/core/src/test/java/com/google/adk/agents/InvocationContextTest.java
Tests:
    "@Test
public void testCreateWithUserContent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).isEmpty();
    assertThat(context.invocationId()).isEqualTo(testInvocationId);
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).hasValue(userContent);
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testCreateWithNullUserContent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.userContent()).isEmpty();
}
"
    "@Test
public void testCreateWithLiveRequestQueue() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).liveRequestQueue(liveRequestQueue).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).hasValue(liveRequestQueue);

    assertThat(context.invocationId()).startsWith("e-");
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).isEmpty();
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testCopyOf() {
    InvocationContext originalContext = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    originalContext.activeStreamingTools().putAll(activeStreamingTools);
    InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
    assertThat(copiedContext).isNotNull();
    assertThat(copiedContext).isNotSameInstanceAs(originalContext);
    assertThat(copiedContext.sessionService()).isEqualTo(originalContext.sessionService());
    assertThat(copiedContext.artifactService()).isEqualTo(originalContext.artifactService());
    assertThat(copiedContext.memoryService()).isEqualTo(originalContext.memoryService());
    assertThat(copiedContext.liveRequestQueue()).isEqualTo(originalContext.liveRequestQueue());
    assertThat(copiedContext.invocationId()).isEqualTo(originalContext.invocationId());
    assertThat(copiedContext.agent()).isEqualTo(originalContext.agent());
    assertThat(copiedContext.session()).isEqualTo(originalContext.session());
    assertThat(copiedContext.userContent()).isEqualTo(originalContext.userContent());
    assertThat(copiedContext.runConfig()).isEqualTo(originalContext.runConfig());
    assertThat(copiedContext.endInvocation()).isEqualTo(originalContext.endInvocation());
    assertThat(copiedContext.activeStreamingTools()).isEqualTo(originalContext.activeStreamingTools());
}
"
    "@Test
public void testGetters() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).isEmpty();
    assertThat(context.invocationId()).isEqualTo(testInvocationId);
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).hasValue(userContent);
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testSetAgent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    BaseAgent newMockAgent = mock(BaseAgent.class);
    context.agent(newMockAgent);
    assertThat(context.agent()).isEqualTo(newMockAgent);
}
"
    "@Test
public void testEquals_sameObject() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(context)).isTrue();
}
"
    "@Test
public void testEquals_null() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(null)).isFalse();
}
"
    "@Test
public void testEquals_sameValues() {
    InvocationContext context1 = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext context2 = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context1.equals(context2)).isTrue();

    assertThat(context2.equals(context1)).isTrue();
}
"
    "@Test
public void testEquals_differentValues() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext contextWithDiffSessionService = InvocationContext.builder().sessionService(
    mock(BaseSessionService.class)).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffInvocationId = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(
    "another-id").agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffAgent = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(
    mock(BaseAgent.class)).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithUserContentEmpty = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithLiveQueuePresent = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).liveRequestQueue(liveRequestQueue).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(contextWithDiffSessionService)).isFalse();
    assertThat(context.equals(contextWithDiffInvocationId)).isFalse();
    assertThat(context.equals(contextWithDiffAgent)).isFalse();
    assertThat(context.equals(contextWithUserContentEmpty)).isFalse();
    assertThat(context.equals(contextWithLiveQueuePresent)).isFalse();
}
"
    "@Test
public void testHashCode_differentValues() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext contextWithDiffSessionService = InvocationContext.builder().sessionService(
    mock(BaseSessionService.class)).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffInvocationId = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(
    "another-id").agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotEqualTo(contextWithDiffSessionService);
    assertThat(context).isNotEqualTo(contextWithDiffInvocationId);
}
"
    "@Test
public void isResumable_whenResumabilityConfigIsNotResumable_isFalse() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(false)).build();
    assertThat(context.isResumable()).isFalse();
}
"
    "@Test
public void isResumable_whenResumabilityConfigIsResumable_isTrue() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(true)).build();
    assertThat(context.isResumable()).isTrue();
}
"
    "@Test
public void shouldPauseInvocation_whenNotResumable_isFalse() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(false)).build();
    Event event = Event.builder().longRunningToolIds(Optional.of(ImmutableSet.of("fc1"))).content(Content.builder().parts(ImmutableList.of(Part.builder().functionCall(FunctionCall.builder().name("tool1").id("fc1").build()).build())).build()).build();
    assertThat(context.shouldPauseInvocation(event)).isFalse();
}
"
    "@Test
public void shouldPauseInvocation_whenResumableAndNoLongRunningToolIds_isFalse() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(true)).build();
    Event event = Event.builder().content(Content.builder().parts(ImmutableList.of(Part.builder().functionCall(FunctionCall.builder().name("tool1").id("fc1").build()).build())).build()).build();
    assertThat(context.shouldPauseInvocation(event)).isFalse();
}
"
    "@Test
public void shouldPauseInvocation_whenResumableAndNoFunctionCalls_isFalse() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(true)).build();
    Event event = Event.builder().longRunningToolIds(Optional.of(ImmutableSet.of("fc1"))).build();
    assertThat(context.shouldPauseInvocation(event)).isFalse();
}
"
    "@Test
public void shouldPauseInvocation_whenResumableAndNoMatchingFunctionCallId_isFalse() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(true)).build();
    Event event = Event.builder().longRunningToolIds(Optional.of(ImmutableSet.of("fc2"))).content(Content.builder().parts(ImmutableList.of(Part.builder().functionCall(FunctionCall.builder().name("tool1").id("fc1").build()).build())).build()).build();
    assertThat(context.shouldPauseInvocation(event)).isFalse();
}
"
    "@Test
public void shouldPauseInvocation_whenResumableAndMatchingFunctionCallId_isTrue() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(true)).build();
    Event event = Event.builder().longRunningToolIds(Optional.of(ImmutableSet.of("fc1"))).content(Content.builder().parts(ImmutableList.of(Part.builder().functionCall(FunctionCall.builder().name("tool1").id("fc1").build()).build())).build()).build();
    assertThat(context.shouldPauseInvocation(event)).isTrue();
}
"Scenario 1: Session Service Returns the Correctly Injected Instance

Details:
  TestName: sessionServiceReturnsInjectedInstance
  Description: Verifies that the sessionService() method returns the exact same BaseSessionService
               instance that was provided during the construction of InvocationContext via the builder.
               This validates that the internal field is properly assigned and retrieved without
               modification.
Execution:
  Arrange: Create a mock of BaseSessionService. Build an InvocationContext using the builder,
           providing the mock as the sessionService, along with the other required fields
           (artifactService, memoryService, agent, session).
  Act: Call sessionService() on the constructed InvocationContext instance.
  Assert: Assert that the returned value is the same instance (reference equality) as the mock
          BaseSessionService provided during construction.
Validation:
  The assertion verifies that sessionService() performs a direct field return without any
  transformation or wrapping. This is critical because other components (e.g., memory tools,
  artifact handlers) depend on receiving the exact service instance to perform operations like
  session creation, retrieval, and update.

*/

// ********RoostGPT********

```java
package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.events.Event;
import com.google.adk.flows.llmflows.ResumabilityConfig;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.models.LlmCallsLimitExceededException;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.common.collect.ImmutableSet;
import com.google.genai.types.Content;
import com.google.genai.types.FunctionCall;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.junit.jupiter.api.*;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import com.google.errorprone.annotations.InlineMe;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;
import javax.annotation.Nullable;

@ExtendWith(MockitoExtension.class)
public class InvocationContextSessionServiceTest {

	@Mock
	private BaseSessionService mockSessionService;

	@Mock
	private BaseArtifactService mockArtifactService;

	@Mock
	private BaseMemoryService mockMemoryService;

	@Mock
	private BaseAgent mockAgent;

	@Mock
	private Session mockSession;

	@Mock
	private PluginManager mockPluginManager;

	@Mock
	private RunConfig mockRunConfig;

	private static final String DUMMY_INVOCATION_ID = "e-test-invocation-id-12345";

	private static final String DUMMY_APP_NAME = "testApp";

	private static final String DUMMY_USER_ID = "testUser";

	private static final String DUMMY_SESSION_ID = "testSession";

	@BeforeEach
	void setUp() {
		lenient().when(mockSession.appName()).thenReturn(DUMMY_APP_NAME);
		lenient().when(mockSession.userId()).thenReturn(DUMMY_USER_ID);
	}

	@Test
	@Tag("valid")
	void sessionServiceReturnsInjectedInstance() {
		// Arrange
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId(DUMMY_INVOCATION_ID)
			.runConfig(mockRunConfig)
			.build();
		// Act
		BaseSessionService result = context.sessionService();
		// Assert
		assertSame(mockSessionService, result,
				"sessionService() should return the exact same instance provided during construction");
	}

	@Test
	@Tag("valid")
	void sessionServiceReturnsNullWhenNotSet() {
		// Arrange
		InvocationContext context = InvocationContext.builder()
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId(DUMMY_INVOCATION_ID)
			.runConfig(mockRunConfig)
			.build();
		// Act
		BaseSessionService result = context.sessionService();
		// Assert
		assertNull(result, "sessionService() should return null when no sessionService was provided");
	}

	@Test
	@Tag("valid")
	void sessionServiceReturnsSameReferenceAfterCopyOf() {
		// Arrange
		InvocationContext original = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId(DUMMY_INVOCATION_ID)
			.runConfig(mockRunConfig)
			.build();
		// Act
		InvocationContext copy = InvocationContext.copyOf(original);
		BaseSessionService result = copy.sessionService();
		// Assert
		assertSame(mockSessionService, result, "copyOf() should preserve the same sessionService reference");
	}

	@Test
	@Tag("valid")
	void sessionServiceReturnsSameInstanceViaStaticCreateWithUserContent() {
		// Arrange
		Content dummyContent = Content.builder().build();
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService,
				DUMMY_INVOCATION_ID, mockAgent, mockSession, dummyContent, mockRunConfig);
		// Act
		BaseSessionService result = context.sessionService();
		// Assert
		assertSame(mockSessionService, result, "create() with userContent should assign the correct sessionService");
	}

	@Test
	@Tag("valid")
	void sessionServiceReturnsSameInstanceViaStaticCreateWithLiveRequestQueue() {
		// Arrange
		LiveRequestQueue liveRequestQueue = new LiveRequestQueue();
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, liveRequestQueue, mockRunConfig);
		// Act
		BaseSessionService result = context.sessionService();
		// Assert
		assertSame(mockSessionService, result,
				"create() with liveRequestQueue should assign the correct sessionService");
	}

	@Test
	@Tag("valid")
	void sessionServiceReturnedIsNotNull_WhenProvided() {
		// Arrange
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId(DUMMY_INVOCATION_ID)
			.runConfig(mockRunConfig)
			.build();
		// Act
		BaseSessionService result = context.sessionService();
		// Assert
		assertNotNull(result, "sessionService() should not return null when sessionService was provided");
	}

	@Test
	@Tag("valid")
	void sessionServiceReturnsSameInstanceAcrossMultipleCalls() {
		// Arrange
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId(DUMMY_INVOCATION_ID)
			.runConfig(mockRunConfig)
			.build();
		// Act
		BaseSessionService firstCall = context.sessionService();
		BaseSessionService secondCall = context.sessionService();
		BaseSessionService thirdCall = context.sessionService();
		// Assert
		assertSame(firstCall, secondCall, "Repeated calls should return the same instance");
		assertSame(secondCall, thirdCall, "Repeated calls should return the same instance");
		assertSame(mockSessionService, firstCall, "Should be the same as the mock provided");
	}

	@Test
	@Tag("valid")
	void sessionServiceIsIndependentAcrossDifferentContextInstances() {
		// Arrange
		BaseSessionService mockSessionService1 = mock(BaseSessionService.class);
		BaseSessionService mockSessionService2 = mock(BaseSessionService.class);
		InvocationContext context1 = InvocationContext.builder()
			.sessionService(mockSessionService1)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId(DUMMY_INVOCATION_ID)
			.runConfig(mockRunConfig)
			.build();
		InvocationContext context2 = InvocationContext.builder()
			.sessionService(mockSessionService2)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("e-other-invocation-id")
			.runConfig(mockRunConfig)
			.build();
		// Act
		BaseSessionService result1 = context1.sessionService();
		BaseSessionService result2 = context2.sessionService();
		// Assert
		assertSame(mockSessionService1, result1, "context1 should return its own sessionService");
		assertSame(mockSessionService2, result2, "context2 should return its own sessionService");
		assertNotSame(result1, result2, "Two different contexts should return different sessionService instances");
	}

	@Test
	@Tag("integration")
	void sessionServiceReturnedCanBeUsedForFurtherOperations() {
		// Arrange
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId(DUMMY_INVOCATION_ID)
			.runConfig(mockRunConfig)
			.build();
		// Act
		BaseSessionService returnedService = context.sessionService();
		// Assert
		assertNotNull(returnedService, "Returned service should not be null");
		assertSame(mockSessionService, returnedService, "Returned service should be the same mock instance");
		// Verifies the returned service is usable (not wrapped or proxied unexpectedly)
		assertInstanceOf(BaseSessionService.class, returnedService, "Returned service should be a BaseSessionService");
	}

	@Test
	@Tag("valid")
	void sessionServicePreservedWithAllOptionalFieldsSet() {
		// Arrange
		LiveRequestQueue liveRequestQueue = new LiveRequestQueue();
		ResumabilityConfig resumabilityConfig = mock(ResumabilityConfig.class);
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.pluginManager(mockPluginManager)
			.liveRequestQueue(Optional.of(liveRequestQueue))
			.branch(Optional.of("testBranch"))
			.invocationId(DUMMY_INVOCATION_ID)
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.endInvocation(false)
			.resumabilityConfig(resumabilityConfig)
			.build();
		// Act
		BaseSessionService result = context.sessionService();
		// Assert
		assertSame(mockSessionService, result,
				"sessionService should be correctly set even when all optional fields are provided");
	}

	@Test
	@Tag("integration")
	void sessionServicePreservedAfterCopyOfWithModifiedBranch() {
		// Arrange
		InvocationContext original = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId(DUMMY_INVOCATION_ID)
			.runConfig(mockRunConfig)
			.build();
		InvocationContext copy = InvocationContext.copyOf(original);
		copy.branch("modifiedBranch");
		// Act
		BaseSessionService resultFromCopy = copy.sessionService();
		BaseSessionService resultFromOriginal = original.sessionService();
		// Assert
		assertSame(mockSessionService, resultFromCopy,
				"Copy should return the same sessionService after branch modification");
		assertSame(mockSessionService, resultFromOriginal, "Original should still return the same sessionService");
		assertSame(resultFromOriginal, resultFromCopy,
				"Both original and copy should return the same sessionService instance");
	}

	@Test
	@Tag("boundary")
	void sessionServiceWithOnlyRequiredFieldsProvided() {
		// Arrange
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.session(mockSession)
			.build();
		// Act
		BaseSessionService result = context.sessionService();
		// Assert
		assertSame(mockSessionService, result,
				"sessionService should be correctly returned even when built with only required fields");
	}

	@Test
	@Tag("valid")
	void sessionServiceEqualsCheckIncludesSessionService() {
		// Arrange
		InvocationContext context1 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId(DUMMY_INVOCATION_ID)
			.runConfig(mockRunConfig)
			.build();
		InvocationContext context2 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId(DUMMY_INVOCATION_ID)
			.runConfig(mockRunConfig)
			.build();
		// Act
		BaseSessionService result1 = context1.sessionService();
		BaseSessionService result2 = context2.sessionService();
		// Assert
		assertSame(result1, result2, "Both contexts with same sessionService should return the same service instance");
		assertEquals(context1, context2, "Contexts with same fields including sessionService should be equal");
	}

	@Test
	@Tag("valid")
	void sessionServiceDifferenceBreaksEquality() {
		// Arrange
		BaseSessionService anotherMockSessionService = mock(BaseSessionService.class);
		InvocationContext context1 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId(DUMMY_INVOCATION_ID)
			.runConfig(mockRunConfig)
			.build();
		InvocationContext context2 = InvocationContext.builder()
			.sessionService(anotherMockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId(DUMMY_INVOCATION_ID)
			.runConfig(mockRunConfig)
			.build();
		// Act & Assert
		assertNotSame(context1.sessionService(), context2.sessionService(),
				"Different sessionServices should not be same instance");
		assertNotEquals(context1, context2, "Contexts with different sessionServices should not be equal");
	}

	@Test
    @Tag("boundary")
    void sessionServiceNotAlteredBySettingOtherFields() {
        // Arrange
        InvocationContext context = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .agent(mockAgent)
                .session(mockSession)
                .invocationId(DUMMY_INVOCATION_ID)
                .runConfig(mockRunConfig)
                .build();
        // Act - modify mutable fields
        context.setEndInvocation(true);
        context.branch("newBranch");
        context.agent(mock(BaseAgent.class));
        BaseSessionService result = context.sessionService();
        // Assert
        assertSame(mockSessionService, result,
                "sessionService should remain unchanged after modifying other mutable fields");
    }

@Test
    @Tag("valid")
    void sessionServiceReturnedFromDeprecatedConstructor() {
        // Arrange
        @SuppressWarnings("deprecation")
        InvocationContext context = new InvocationContext(
                mockSessionService,
                mockArtifactService,
                mockMem