/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=invocationId_b0959abc16
ROOST_METHOD_SIG_HASH=invocationId_6cd6fb05e4

Scenario 1: Retrieve an Explicitly Set Invocation ID

Details:
  TestName: invocationIdReturnsExplicitlySetValue
  Description: Verifies that when an invocationId is explicitly provided via the Builder,
               the invocationId() method returns exactly that same value without any
               modification or transformation.

Execution:
  Arrange: Use InvocationContext.Builder to construct an InvocationContext instance,
           setting invocationId to a specific known string value such as "test-invocation-123".
           Provide all other required fields (sessionService, artifactService, agent, session)
           with valid mock or stub objects.
  Act: Call invocationId() on the constructed InvocationContext instance.
  Assert: Assert that the returned String equals "test-invocation-123" using assertEquals.

Validation:
  The assertion verifies that the invocationId field is correctly stored and returned
  by the accessor method without alteration. This is critical because downstream
  components use the invocationId to correlate logs, events, and results to a specific
  agent invocation lifecycle.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.genai.types.Content;
import java.util.Optional;
import java.util.UUID;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class InvocationContextInvocationIdTest {

	@Mock
	private BaseSessionService mockSessionService;

	@Mock
	private BaseArtifactService mockArtifactService;

	@Mock
	private BaseMemoryService mockMemoryService;

	@Mock
	private PluginManager mockPluginManager;

	@Mock
	private BaseAgent mockAgent;

	@Mock
	private Session mockSession;

	@Mock
	private RunConfig mockRunConfig;

	@BeforeEach
  void setUp() {
    when(mockSession.appName()).thenReturn("testApp");
    when(mockSession.userId()).thenReturn("testUser");
  }

	@Test
	@Tag("valid")
	void invocationIdReturnsExplicitlySetValue() {
		String expectedInvocationId = "test-invocation-123";
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId(expectedInvocationId)
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		String actualInvocationId = context.invocationId();
		assertEquals(expectedInvocationId, actualInvocationId);
	}

	@Test
	@Tag("valid")
	void invocationIdReturnsCorrectValueWhenSetWithUUID() {
		String expectedInvocationId = UUID.randomUUID().toString();
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId(expectedInvocationId)
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		String actualInvocationId = context.invocationId();
		assertNotNull(actualInvocationId);
		assertEquals(expectedInvocationId, actualInvocationId);
	}

	@Test
	@Tag("valid")
	void invocationIdReturnsNullWhenNotSet() {
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		String actualInvocationId = context.invocationId();
		assertNull(actualInvocationId);
	}

	@Test
	@Tag("valid")
	void invocationIdDoesNotModifyStoredValue() {
		String expectedInvocationId = "e-abc-123-xyz";
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId(expectedInvocationId)
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		String firstCall = context.invocationId();
		String secondCall = context.invocationId();
		assertEquals(firstCall, secondCall);
		assertEquals(expectedInvocationId, firstCall);
	}

	@Test
	@Tag("boundary")
	void invocationIdReturnsEmptyString() {
		String expectedInvocationId = "";
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId(expectedInvocationId)
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		String actualInvocationId = context.invocationId();
		assertEquals(expectedInvocationId, actualInvocationId);
		assertTrue(actualInvocationId.isEmpty());
	}

	@Test
	@Tag("boundary")
	void invocationIdReturnsValueWithSpecialCharacters() {
		String expectedInvocationId = "e-!@#$%^&*()-invocation_ID.123";
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId(expectedInvocationId)
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		String actualInvocationId = context.invocationId();
		assertEquals(expectedInvocationId, actualInvocationId);
	}

	@Test
	@Tag("boundary")
	void invocationIdReturnsVeryLongString() {
		StringBuilder sb = new StringBuilder();
		for (int i = 0; i < 1000; i++) {
			sb.append("a");
		}
		String expectedInvocationId = sb.toString();
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId(expectedInvocationId)
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		String actualInvocationId = context.invocationId();
		assertEquals(expectedInvocationId, actualInvocationId);
		assertEquals(1000, actualInvocationId.length());
	}

	@Test
	@Tag("valid")
	void invocationIdIsConsistentAcrossMultipleCalls() {
		String expectedInvocationId = "consistent-invocation-id";
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId(expectedInvocationId)
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		for (int i = 0; i < 10; i++) {
			assertEquals(expectedInvocationId, context.invocationId());
		}
	}

	@Test
	@Tag("valid")
	void invocationIdReturnedByCreateFactoryMethod() {
		String expectedInvocationId = "factory-created-id-456";
		Content mockContent = mock(Content.class);
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService,
				expectedInvocationId, mockAgent, mockSession, mockContent, mockRunConfig);
		String actualInvocationId = context.invocationId();
		assertEquals(expectedInvocationId, actualInvocationId);
	}

	@Test
	@Tag("valid")
	void invocationIdReturnedFromCopiedContext() {
		String expectedInvocationId = "original-invocation-id-789";
		InvocationContext originalContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId(expectedInvocationId)
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
		assertEquals(expectedInvocationId, copiedContext.invocationId());
	}

	@Test
	@Tag("integration")
	void invocationIdIsPreservedAfterCopyOf() {
		String expectedInvocationId = "invocation-to-copy-001";
		InvocationContext originalContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.pluginManager(mockPluginManager)
			.invocationId(expectedInvocationId)
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
		assertEquals(originalContext.invocationId(), copiedContext.invocationId());
		assertEquals(expectedInvocationId, copiedContext.invocationId());
	}

	@Test
	@Tag("valid")
	void invocationIdReturnsNewInvocationContextIdFormat() {
		String generatedId = InvocationContext.newInvocationContextId();
		assertNotNull(generatedId);
		assertTrue(generatedId.startsWith("e-"));
	}

	@Test
	@Tag("valid")
	void invocationIdStoredWithNewInvocationContextIdIsReturned() {
		String generatedId = InvocationContext.newInvocationContextId();
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId(generatedId)
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		String actualInvocationId = context.invocationId();
		assertNotNull(actualInvocationId);
		assertEquals(generatedId, actualInvocationId);
		assertTrue(actualInvocationId.startsWith("e-"));
	}

	@Test
	@Tag("valid")
	void invocationIdWithNumericOnlyString() {
		String expectedInvocationId = "1234567890";
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId(expectedInvocationId)
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		String actualInvocationId = context.invocationId();
		assertEquals(expectedInvocationId, actualInvocationId);
	}

	@Test
	@Tag("valid")
	void invocationIdDoesNotAffectOtherFields() {
		String expectedInvocationId = "id-for-field-isolation";
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId(expectedInvocationId)
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		assertEquals(expectedInvocationId, context.invocationId());
		assertNotNull(context.sessionService());
		assertNotNull(context.artifactService());
		assertNotNull(context.session());
		assertNotNull(context.agent());
	}

	@Test
	@Tag("valid")
	void invocationIdInDeprecatedConstructorIsRetained() {
		String expectedInvocationId = "deprecated-constructor-id";
		InvocationContext context = new InvocationContext(mockSessionService, mockArtifactService, mockMemoryService,
				mockPluginManager, Optional.empty(), Optional.empty(), expectedInvocationId, mockAgent, mockSession,
				Optional.empty(), mockRunConfig, false);
		assertEquals(expectedInvocationId, context.invocationId());
	}

	@Test
	@Tag("boundary")
	void invocationIdWithWhitespaceIsRetainedAsIs() {
		String expectedInvocationId = "   invocation with spaces   ";
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId(expectedInvocationId)
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		String actualInvocationId = context.invocationId();
		assertEquals(expectedInvocationId, actualInvocationId);
	}

	@Test
	@Tag("valid")
	void invocationIdIsIncludedInEqualsComparison() {
		String invocationId1 = "id-one";
		String invocationId2 = "id-two";
		InvocationContext context1 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId(invocationId1)
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		InvocationContext context2 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId(invocationId2)
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		assertNotEquals(context1.invocationId(), context2.invocationId());
		assertNotEquals(context1, context2);
	}

	@Test
	@Tag("integration")
	void invocationIdIsRetainedAcrossBuilderChain() {
		String expectedInvocationId = "builder-chain-id-999";
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.pluginManager(mockPluginManager)
			.invocationId(expectedInvocationId)
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.endInvocation(false)
			.build();
		assertEquals(expectedInvocationId, context.invocationId());
	}

}
