/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=endInvocation_306878eff5
ROOST_METHOD_SIG_HASH=endInvocation_b038f3ac95

Scenario 1: Default Value of endInvocation Returns False

Details:
  TestName: endInvocationReturnsFalseByDefault
  Description: Verifies that when an InvocationContext is built using the builder without explicitly
               setting the endInvocation flag, the endInvocation() method returns false, which is
               the documented default value in the Builder class.
Execution:
  Arrange: Create an InvocationContext using InvocationContext.builder() without calling
           .endInvocation(true), providing only the minimum required fields (sessionService,
           artifactService, invocationId, agent, session).
  Act: Call endInvocation() on the constructed InvocationContext instance.
  Assert: Use assertFalse() to confirm that endInvocation() returns false.
Validation:
  The assertion confirms that the default value for the endInvocation field is false, as defined
  in the Builder. This is significant because when an invocation is created, it should not be
  in a terminated state by default; the system should only mark it as ended when explicitly
  requested.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.flows.llmflows.ResumabilityConfig;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.genai.types.Content;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class InvocationContextEndInvocationTest {
  @Mock private BaseSessionService mockSessionService;
  @Mock private BaseArtifactService mockArtifactService;
  @Mock private BaseMemoryService mockMemoryService;
  @Mock private PluginManager mockPluginManager;
  @Mock private BaseAgent mockAgent;
  @Mock private Session mockSession;
  @Mock private ResumabilityConfig mockResumabilityConfig;
  private static final String TEST_INVOCATION_ID = "test-invocation-id-001";
  private static final String TEST_APP_NAME = "testApp";
  private static final String TEST_USER_ID = "testUser";
  private static final String TEST_SESSION_ID = "testSession";

  @BeforeEach
  void setUp() {
    when(mockSession.appName()).thenReturn(TEST_APP_NAME);
    when(mockSession.userId()).thenReturn(TEST_USER_ID);
    when(mockSession.id()).thenReturn(TEST_SESSION_ID);
  }

  @Test
  @Tag("valid")
  void endInvocationReturnsFalseByDefault() {
    // Arrange
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId(TEST_INVOCATION_ID)
            .agent(mockAgent)
            .session(mockSession)
            .build();
    // Act
    boolean result = context.endInvocation();
    // Assert
    assertFalse(result, "endInvocation() should return false by default when not explicitly set");
  }

  @Test
  @Tag("valid")
  void endInvocationReturnsTrueWhenSetToTrue() {
    // Arrange
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId(TEST_INVOCATION_ID)
            .agent(mockAgent)
            .session(mockSession)
            .endInvocation(true)
            .build();
    // Act
    boolean result = context.endInvocation();
    // Assert
    assertTrue(
        result, "endInvocation() should return true when explicitly set to true via builder");
  }

  @Test
  @Tag("valid")
  void endInvocationReturnsFalseWhenExplicitlySetToFalse() {
    // Arrange
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId(TEST_INVOCATION_ID)
            .agent(mockAgent)
            .session(mockSession)
            .endInvocation(false)
            .build();
    // Act
    boolean result = context.endInvocation();
    // Assert
    assertFalse(
        result, "endInvocation() should return false when explicitly set to false via builder");
  }

  @Test
  @Tag("valid")
  void endInvocationReturnsTrueAfterSetEndInvocationCalledWithTrue() {
    // Arrange
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId(TEST_INVOCATION_ID)
            .agent(mockAgent)
            .session(mockSession)
            .build();
    // Act
    context.setEndInvocation(true);
    boolean result = context.endInvocation();
    // Assert
    assertTrue(result, "endInvocation() should return true after setEndInvocation(true) is called");
  }

  @Test
  @Tag("valid")
  void endInvocationReturnsFalseAfterSetEndInvocationCalledWithFalse() {
    // Arrange
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId(TEST_INVOCATION_ID)
            .agent(mockAgent)
            .session(mockSession)
            .endInvocation(true)
            .build();
    // Act
    context.setEndInvocation(false);
    boolean result = context.endInvocation();
    // Assert
    assertFalse(
        result, "endInvocation() should return false after setEndInvocation(false) is called");
  }

  @Test
  @Tag("valid")
  void endInvocationDefaultFalseWithAllFieldsSet() {
    // Arrange
    Content mockUserContent = mock(Content.class);
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .memoryService(mockMemoryService)
            .pluginManager(mockPluginManager)
            .invocationId(TEST_INVOCATION_ID)
            .agent(mockAgent)
            .session(mockSession)
            .userContent(Optional.of(mockUserContent))
            .build();
    // Act
    boolean result = context.endInvocation();
    // Assert
    assertFalse(
        result,
        "endInvocation() should return false by default even when all other fields are set");
  }

  @Test
  @Tag("valid")
  void endInvocationTruePreservedAfterCopyOf() {
    // Arrange
    InvocationContext original =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId(TEST_INVOCATION_ID)
            .agent(mockAgent)
            .session(mockSession)
            .endInvocation(true)
            .build();
    // Act
    InvocationContext copy = InvocationContext.copyOf(original);
    boolean result = copy.endInvocation();
    // Assert
    assertTrue(
        result,
        "endInvocation() should return true in a copy when the original had endInvocation set to true");
  }

  @Test
  @Tag("valid")
  void endInvocationFalsePreservedAfterCopyOf() {
    // Arrange
    InvocationContext original =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId(TEST_INVOCATION_ID)
            .agent(mockAgent)
            .session(mockSession)
            .endInvocation(false)
            .build();
    // Act
    InvocationContext copy = InvocationContext.copyOf(original);
    boolean result = copy.endInvocation();
    // Assert
    assertFalse(
        result,
        "endInvocation() should return false in a copy when the original had endInvocation set to false");
  }

  @Test
  @Tag("valid")
  void endInvocationMutationDoesNotAffectCopiedContext() {
    // Arrange
    InvocationContext original =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId(TEST_INVOCATION_ID)
            .agent(mockAgent)
            .session(mockSession)
            .endInvocation(false)
            .build();
    InvocationContext copy = InvocationContext.copyOf(original);
    // Act
    original.setEndInvocation(true);
    boolean originalResult = original.endInvocation();
    boolean copyResult = copy.endInvocation();
    // Assert
    assertTrue(originalResult, "Original context should have endInvocation as true after mutation");
    assertFalse(copyResult, "Copied context should remain false after the original is mutated");
  }

  @Test
  @Tag("boundary")
  void endInvocationToggleFromFalseToTrue() {
    // Arrange
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId(TEST_INVOCATION_ID)
            .agent(mockAgent)
            .session(mockSession)
            .build();
    // Assert initial state
    assertFalse(context.endInvocation(), "Initial endInvocation() should be false");
    // Act
    context.setEndInvocation(true);
    // Assert toggled state
    assertTrue(context.endInvocation(), "After toggling, endInvocation() should return true");
  }

  @Test
  @Tag("boundary")
  void endInvocationToggleFromTrueToFalse() {
    // Arrange
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId(TEST_INVOCATION_ID)
            .agent(mockAgent)
            .session(mockSession)
            .endInvocation(true)
            .build();
    // Assert initial state
    assertTrue(context.endInvocation(), "Initial endInvocation() should be true");
    // Act
    context.setEndInvocation(false);
    // Assert toggled state
    assertFalse(
        context.endInvocation(), "After toggling back, endInvocation() should return false");
  }

  @Test
  @Tag("boundary")
  void endInvocationMultipleSetCalls() {
    // Arrange
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId(TEST_INVOCATION_ID)
            .agent(mockAgent)
            .session(mockSession)
            .build();
    // Act and Assert multiple mutations
    assertFalse(context.endInvocation(), "Initial state should be false");
    context.setEndInvocation(true);
    assertTrue(context.endInvocation(), "After setting to true, should return true");
    context.setEndInvocation(true);
    assertTrue(context.endInvocation(), "After setting to true again, should still return true");
    context.setEndInvocation(false);
    assertFalse(context.endInvocation(), "After setting to false, should return false");
    context.setEndInvocation(false);
    assertFalse(context.endInvocation(), "After setting to false again, should still return false");
  }

  @Test
  @Tag("valid")
  void endInvocationCreatedViaStaticFactoryMethodDefaultsFalse() {
    // Arrange
    Content mockUserContent = mock(Content.class);
    InvocationContext context =
        InvocationContext.create(
            mockSessionService,
            mockArtifactService,
            TEST_INVOCATION_ID,
            mockAgent,
            mockSession,
            mockUserContent,
            null);
    // Act
    boolean result = context.endInvocation();
    // Assert
    assertFalse(
        result, "endInvocation() should return false when created via static factory method");
  }

  @Test
  @Tag("integration")
  void endInvocationConsistentWithEqualsAfterMutation() {
    // Arrange
    InvocationContext context1 =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId(TEST_INVOCATION_ID)
            .agent(mockAgent)
            .session(mockSession)
            .endInvocation(false)
            .build();
    InvocationContext context2 =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId(TEST_INVOCATION_ID)
            .agent(mockAgent)
            .session(mockSession)
            .endInvocation(false)
            .build();
    // Assert initial equality check on endInvocation
    assertFalse(context1.endInvocation());
    assertFalse(context2.endInvocation());
    // Act - mutate context1
    context1.setEndInvocation(true);
    // Assert after mutation
    assertTrue(context1.endInvocation(), "context1.endInvocation() should be true after mutation");
    assertFalse(
        context2.endInvocation(),
        "context2.endInvocation() should remain false after mutating context1");
  }

  @Test
  @Tag("valid")
  void endInvocationWithBranchSetStillDefaultsFalse() {
    // Arrange
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId(TEST_INVOCATION_ID)
            .agent(mockAgent)
            .session(mockSession)
            .branch("agentA.agentB")
            .build();
    // Act
    boolean result = context.endInvocation();
    // Assert
    assertFalse(result, "endInvocation() should default to false regardless of branch being set");
  }

  @Test
  @Tag("valid")
  void endInvocationBranchMethodDoesNotAffectEndInvocationFlag() {
    // Arrange
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId(TEST_INVOCATION_ID)
            .agent(mockAgent)
            .session(mockSession)
            .build();
    // Act
    context.branch("someNewBranch");
    boolean result = context.endInvocation();
    // Assert
    assertFalse(result, "Calling branch() setter should not affect endInvocation() value");
  }

  @Test
  @Tag("valid")
  void endInvocationAgentSetterDoesNotAffectEndInvocationFlag() {
    // Arrange
    BaseAgent anotherMockAgent = mock(BaseAgent.class);
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId(TEST_INVOCATION_ID)
            .agent(mockAgent)
            .session(mockSession)
            .build();
    // Act
    context.agent(anotherMockAgent);
    boolean result = context.endInvocation();
    // Assert
    assertFalse(result, "Calling agent() setter should not affect endInvocation() value");
  }
}
