/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=isResumable_2397941e46
ROOST_METHOD_SIG_HASH=isResumable_6fb85ad5c9

Scenario 1: Default ResumabilityConfig Returns Expected Resumable Value

Details:
  TestName: isResumableWithDefaultResumabilityConfig
  Description: Verifies that when an InvocationContext is built using the default ResumabilityConfig
               (i.e., no explicit resumabilityConfig is set via the builder), the isResumable()
               method returns the value dictated by the default ResumabilityConfig instance.

Execution:
  Arrange:
    - Create a mock or stub for BaseSessionService, BaseArtifactService, Session.
    - Build an InvocationContext using InvocationContext.builder() without explicitly setting
      a ResumabilityConfig (allowing the builder to use its default: new ResumabilityConfig()).
    - Note the expected value returned by the default ResumabilityConfig.isResumable().
  Act:
    - Call invocationContext.isResumable() on the built InvocationContext.
  Assert:
    - Assert that the returned boolean matches the value returned by the default
      ResumabilityConfig().isResumable().

Validation:
  This test confirms that the builder's default ResumabilityConfig is correctly wired
  into the InvocationContext and that isResumable() properly delegates to it without
  any alteration. This is foundational to ensure that users who do not customize
  resumability get a predictable default behavior.

*/

// ********RoostGPT********

```java
package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.events.Event;
import com.google.adk.flows.llmflows.ResumabilityConfig;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.models.LlmCallsLimitExceededException;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.common.collect.ImmutableSet;
import com.google.genai.types.Content;
import com.google.genai.types.FunctionCall;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import javax.annotation.Nullable;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.junit.jupiter.api.*;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import com.google.errorprone.annotations.InlineMe;

@ExtendWith(MockitoExtension.class)
public class InvocationContextIsResumableTest {

	@Mock
	private BaseSessionService mockSessionService;

	@Mock
	private BaseArtifactService mockArtifactService;

	@Mock
	private BaseMemoryService mockMemoryService;

	@Mock
	private PluginManager mockPluginManager;

	@Mock
	private Session mockSession;

	@Mock
	private ResumabilityConfig mockResumabilityConfig;

	@Mock
	private RunConfig mockRunConfig;

	@BeforeEach
    void setUp() {
        when(mockSession.appName()).thenReturn("testApp");
        when(mockSession.userId()).thenReturn("testUser");
        when(mockSession.id()).thenReturn("testSessionId");
    }

	@Test
	@Tag("valid")
	void isResumableWithDefaultResumabilityConfig() {
		// Arrange
		InvocationContext invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		ResumabilityConfig defaultConfig = new ResumabilityConfig();
		boolean expectedResumable = defaultConfig.isResumable();
		// Act
		boolean result = invocationContext.isResumable();
		// Assert
		assertEquals(expectedResumable, result);
	}

	@Test
    @Tag("valid")
    void isResumableReturnsTrueWhenResumabilityConfigReturnsTrue() {
        // Arrange
        when(mockResumabilityConfig.isResumable()).thenReturn(true);
        InvocationContext invocationContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("test-invocation-id")
                .session(mockSession)
                .userContent(Optional.empty())
                .runConfig(mockRunConfig)
                .resumabilityConfig(mockResumabilityConfig)
                .build();
        // Act
        boolean result = invocationContext.isResumable();
        // Assert
        assertTrue(result);
        verify(mockResumabilityConfig, times(1)).isResumable();
    }

	@Test
    @Tag("valid")
    void isResumableReturnsFalseWhenResumabilityConfigReturnsFalse() {
        // Arrange
        when(mockResumabilityConfig.isResumable()).thenReturn(false);
        InvocationContext invocationContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("test-invocation-id")
                .session(mockSession)
                .userContent(Optional.empty())
                .runConfig(mockRunConfig)
                .resumabilityConfig(mockResumabilityConfig)
                .build();
        // Act
        boolean result = invocationContext.isResumable();
        // Assert
        assertFalse(result);
        verify(mockResumabilityConfig, times(1)).isResumable();
    }

	@Test
    @Tag("valid")
    void isResumableDelegatesToResumabilityConfig() {
        // Arrange
        when(mockResumabilityConfig.isResumable()).thenReturn(true);
        InvocationContext invocationContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("test-invocation-id")
                .session(mockSession)
                .userContent(Optional.empty())
                .runConfig(mockRunConfig)
                .resumabilityConfig(mockResumabilityConfig)
                .build();
        // Act
        invocationContext.isResumable();
        // Assert - verify delegation happens exactly once
        verify(mockResumabilityConfig).isResumable();
    }

	@Test
	@Tag("valid")
	void isResumableReturnsTrueWithExplicitResumableConfig() {
		// Arrange
		ResumabilityConfig resumabilityConfig = mock(ResumabilityConfig.class);
		when(resumabilityConfig.isResumable()).thenReturn(true);
		InvocationContext invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id-explicit")
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.resumabilityConfig(resumabilityConfig)
			.build();
		// Act
		boolean result = invocationContext.isResumable();
		// Assert
		assertTrue(result);
	}

	@Test
	@Tag("valid")
	void isResumableReturnsFalseWithExplicitNonResumableConfig() {
		// Arrange
		ResumabilityConfig resumabilityConfig = mock(ResumabilityConfig.class);
		when(resumabilityConfig.isResumable()).thenReturn(false);
		InvocationContext invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id-non-resumable")
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.resumabilityConfig(resumabilityConfig)
			.build();
		// Act
		boolean result = invocationContext.isResumable();
		// Assert
		assertFalse(result);
	}

	@Test
    @Tag("valid")
    void isResumableIsConsistentAcrossMultipleCalls() {
        // Arrange
        when(mockResumabilityConfig.isResumable()).thenReturn(true);
        InvocationContext invocationContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("test-invocation-id-multiple-calls")
                .session(mockSession)
                .userContent(Optional.empty())
                .runConfig(mockRunConfig)
                .resumabilityConfig(mockResumabilityConfig)
                .build();
        // Act
        boolean firstCall = invocationContext.isResumable();
        boolean secondCall = invocationContext.isResumable();
        boolean thirdCall = invocationContext.isResumable();
        // Assert
        assertEquals(firstCall, secondCall);
        assertEquals(secondCall, thirdCall);
        assertTrue(firstCall);
    }

	@Test
    @Tag("integration")
    void isResumableWithCopyOfContextPreservesResumabilityConfig() {
        // Arrange
        when(mockResumabilityConfig.isResumable()).thenReturn(true);
        InvocationContext originalContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("test-invocation-id-copy")
                .session(mockSession)
                .userContent(Optional.empty())
                .runConfig(mockRunConfig)
                .resumabilityConfig(mockResumabilityConfig)
                .build();
        // Act
        InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
        boolean originalResult = originalContext.isResumable();
        boolean copiedResult = copiedContext.isResumable();
        // Assert
        assertEquals(originalResult, copiedResult);
        assertTrue(copiedResult);
    }

	@Test
    @Tag("integration")
    void isResumableWithCopyOfContextPreservesNonResumabilityConfig() {
        // Arrange
        when(mockResumabilityConfig.isResumable()).thenReturn(false);
        InvocationContext originalContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("test-invocation-id-copy-false")
                .session(mockSession)
                .userContent(Optional.empty())
                .runConfig(mockRunConfig)
                .resumabilityConfig(mockResumabilityConfig)
                .build();
        // Act
        InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
        boolean originalResult = originalContext.isResumable();
        boolean copiedResult = copiedContext.isResumable();
        // Assert
        assertEquals(originalResult, copiedResult);
        assertFalse(copiedResult);
    }

	@Test
	@Tag("boundary")
	void isResumableWithDefaultBuilderUsesDefaultResumabilityConfig() {
		// Arrange - build without explicitly setting resumabilityConfig
		InvocationContext invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-default-resumability")
			.session(mockSession)
			.runConfig(mockRunConfig)
			.build();
		// Act
		boolean result = invocationContext.isResumable();
		// Assert - should not throw, result should be valid boolean
		assertNotNull(result);
		// The result is a primitive boolean so just checking it returns without exception
		// Default ResumabilityConfig behavior is tested
		boolean defaultExpected = new ResumabilityConfig().isResumable();
		assertEquals(defaultExpected, result);
	}

	@Test
    @Tag("valid")
    void isResumableWithFullyPopulatedContextReturnsCorrectValue() {
        // Arrange
        when(mockResumabilityConfig.isResumable()).thenReturn(true);
        InvocationContext invocationContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .memoryService(mockMemoryService)
                .pluginManager(mockPluginManager)
                .invocationId("test-full-context")
                .session(mockSession)
                .runConfig(mockRunConfig)
                .resumabilityConfig(mockResumabilityConfig)
                .endInvocation(false)
                .branch(Optional.of("agentA.agentB"))
                .build();
        // Act
        boolean result = invocationContext.isResumable();
        // Assert
        assertTrue(result);
        verify(mockResumabilityConfig).isResumable();
    }

	@Test
	@Tag("valid")
	void isResumableWithCreateFactoryMethodDefaultsToDefaultResumabilityConfig() {
		// Arrange
		Content userContent = mock(Content.class);
		InvocationContext invocationContext = InvocationContext.create(mockSessionService, mockArtifactService,
				"test-invocation-id-factory", null, mockSession, userContent, mockRunConfig);
		// Act
		boolean result = invocationContext.isResumable();
		// Assert
		boolean defaultExpected = new ResumabilityConfig().isResumable();
		assertEquals(defaultExpected, result);
	}

	@Test
    @Tag("boundary")
    void isResumableReturnsBooleanPrimitive() {
        // Arrange
        when(mockResumabilityConfig.isResumable()).thenReturn(true);
        InvocationContext invocationContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("test-primitive-boolean")
                .session(mockSession)
                .runConfig(mockRunConfig)
                .resumabilityConfig(mockResumabilityConfig)
                .build();
        // Act
        boolean result = invocationContext.isResumable();
        // Assert - verify it is indeed a primitive boolean (no null)
        assertNotNull(Boolean.valueOf(result));
        assertTrue(result);
    }

	@Test
    @Tag("valid")
    void isResumableInvocationContextWithNullUserContent() {
        // Arrange
        when(mockResumabilityConfig.isResumable()).thenReturn(false);
        InvocationContext invocationContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("test-null-user-content")
                .session(mockSession)
                .userContent(Optional.empty())
                .runConfig(mockRunConfig)
                .resumabilityConfig(mockResumabilityConfig)
                .build();
        // Act
        boolean result = invocationContext.isResumable();
        // Assert
        assertFalse(result);
    }

	@Test
    @Tag("valid")
    void isResumableAfterSettingEndInvocationTrue() {
        // Arrange
        when(mockResumabilityConfig.isResumable()).thenReturn(true);
        InvocationContext invocationContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("test-end-invocation")
                .session(mockSession)
                .runConfig(mockRunConfig)
                .resumabilityConfig(mockResumabilityConfig)
                .endInvocation(true)
                .build();
        // Act
        boolean result = invocationContext.isResumable();
        // Assert - endInvocation should not affect resumability
        assertTrue(result);
        verify(mockResumabilityConfig).isResumable();
    }

	@Test
    @Tag("integration")
    void isResumableWithMockedResumabilityConfigChangingValues() {
        // Arrange
        when(mockResumabilityConfig.isResumable())
                .thenReturn(false)
                .thenReturn(true);
        InvocationContext invocationContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("test-changing-values")
                .session(mockSession)
                .runConfig(mockRunConfig)
                .resumabilityConfig(mockResumabilityConfig)
                .build();
        // Act
        boolean firstResult = invocationContext.isResumable();
        boolean secondResult = invocationContext.isResumable();
        // Assert - reflects the underlying config's behavior
        assertFalse(firstResult);
        assertTrue(secondResult);
    }

@Test
    @Tag("valid")
    void isResumableWithNewInvocationContextIdGeneratedCorrectly() {
        // Arrange
        when(mockResumabil