/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=create_a8299eaa31
ROOST_METHOD_SIG_HASH=create_95f62994c3

Scenario 1: Successfully Create InvocationContext With All Valid Parameters

Details:
  TestName: createWithAllValidParametersReturnsCorrectInvocationContext
  Description: Verifies that the `create` method successfully builds and returns a valid
               `InvocationContext` instance when all parameters are provided with valid,
               non-null values. This is the primary happy-path scenario.

Execution:
  Arrange:
    - Create a mock instance of `BaseSessionService`.
    - Create a mock instance of `BaseArtifactService`.
    - Create a specific invocation ID string (e.g., "test-invocation-id-001").
    - Create a mock instance of `BaseAgent`.
    - Create a mock instance of `Session`.
    - Create a non-null `Content` object representing user content.
    - Create a `RunConfig` instance using `RunConfig.builder().build()`.

  Act:
    - Call `InvocationContext.create(sessionService, artifactService, invocationId,
      agent, session, userContent, runConfig)`.

  Assert:
    - Assert that the returned `InvocationContext` object is not null.
    - Assert that `context.invocationId()` equals the provided invocation ID string.
    - Assert that `context.sessionService()` is the same reference as the mock sessionService.
    - Assert that `context.artifactService()` is the same reference as the mock artifactService.
    - Assert that `context.agent()` is the same reference as the mock agent.
    - Assert that `context.session()` is the same reference as the mock session.
    - Assert that `context.userContent()` is present (i.e., `Optional.isPresent()` is true).
    - Assert that `context.userContent().get()` is the same reference as the provided `Content` object.
    - Assert that `context.runConfig()` is the same reference as the provided `runConfig`.

Validation:
  This test validates the core contract of the `create` factory method — that all provided
  parameters are correctly passed through to the underlying builder and reflected in the
  constructed `InvocationContext` object. It confirms the method is functioning as a
  correct delegation to the builder pattern.

*/

// ********RoostGPT********

```java
package com.google.adk.agents;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.events.Event;
import com.google.adk.flows.llmflows.ResumabilityConfig;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.models.LlmCallsLimitExceededException;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.common.collect.ImmutableSet;
import com.google.genai.types.Content;
import com.google.genai.types.Part;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import javax.annotation.Nullable;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.junit.jupiter.api.*;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import com.google.errorprone.annotations.InlineMe;
import com.google.genai.types.FunctionCall;

@ExtendWith(MockitoExtension.class)
public class InvocationContextCreateTest {
    @Mock
    private BaseSessionService mockSessionService;
    @Mock
    private BaseArtifactService mockArtifactService;
    @Mock
    private BaseAgent mockAgent;
    @Mock
    private Session mockSession;
    private RunConfig runConfig;
    private String invocationId;
    private Content userContent;
    @BeforeEach
    void setUp() {
        invocationId = "test-invocation-id-001";
        runConfig = RunConfig.builder().build();
        userContent = Content.fromParts(Part.fromText("Hello, world!"));
    }
    @Test
    @Tag("valid")
    void createWithAllValidParametersReturnsCorrectInvocationContext() {
        // Act
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                invocationId,
                mockAgent,
                mockSession,
                userContent,
                runConfig
        );
        // Assert
        assertNotNull(context, "Created InvocationContext should not be null");
        assertEquals(invocationId, context.invocationId(), "Invocation ID should match");
        assertSame(mockSessionService, context.sessionService(), "Session service should be the same reference");
        assertSame(mockArtifactService, context.artifactService(), "Artifact service should be the same reference");
        assertSame(mockAgent, context.agent(), "Agent should be the same reference");
        assertSame(mockSession, context.session(), "Session should be the same reference");
        assertTrue(context.userContent().isPresent(), "User content should be present");
        assertSame(userContent, context.userContent().get(), "User content should be the same reference");
        assertSame(runConfig, context.runConfig(), "RunConfig should be the same reference");
    }
    @Test
    @Tag("valid")
    void createWithNullUserContentReturnsContextWithEmptyUserContent() {
        // Act
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                invocationId,
                mockAgent,
                mockSession,
                null,
                runConfig
        );
        // Assert
        assertNotNull(context, "Created InvocationContext should not be null");
        assertFalse(context.userContent().isPresent(), "User content should be empty when null is passed");
        assertEquals(Optional.empty(), context.userContent(), "User content should be Optional.empty()");
    }
    @Test
    @Tag("valid")
    void createWithValidInvocationIdStoresInvocationIdCorrectly() {
        // Arrange
        String specificInvocationId = "e-" + UUID.randomUUID();
        // Act
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                specificInvocationId,
                mockAgent,
                mockSession,
                userContent,
                runConfig
        );
        // Assert
        assertNotNull(context);
        assertEquals(specificInvocationId, context.invocationId(), "Invocation ID should match exactly");
    }
    @Test
    @Tag("valid")
    void createWithNullArtifactServiceReturnsContextWithNullArtifactService() {
        // Act
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                null,
                invocationId,
                mockAgent,
                mockSession,
                userContent,
                runConfig
        );
        // Assert
        assertNotNull(context, "Context should still be created even with null artifactService");
        assertNull(context.artifactService(), "Artifact service should be null");
    }
    @Test
    @Tag("valid")
    void createWithNullSessionServiceReturnsContextWithNullSessionService() {
        // Act
        InvocationContext context = InvocationContext.create(
                null,
                mockArtifactService,
                invocationId,
                mockAgent,
                mockSession,
                userContent,
                runConfig
        );
        // Assert
        assertNotNull(context, "Context should be created even with null sessionService");
        assertNull(context.sessionService(), "Session service should be null");
    }
    @Test
    @Tag("valid")
    void createWithNullRunConfigReturnsContextWithNullRunConfig() {
        // Act
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                invocationId,
                mockAgent,
                mockSession,
                userContent,
                null
        );
        // Assert
        assertNotNull(context, "Context should be created even with null runConfig");
        assertNull(context.runConfig(), "RunConfig should be null");
    }
    @Test
    @Tag("valid")
    void createSetsDefaultEndInvocationToFalse() {
        // Act
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                invocationId,
                mockAgent,
                mockSession,
                userContent,
                runConfig
        );
        // Assert
        assertFalse(context.endInvocation(), "endInvocation should default to false");
    }
    @Test
    @Tag("valid")
    void createReturnsBranchAsEmptyByDefault() {
        // Act
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                invocationId,
                mockAgent,
                mockSession,
                userContent,
                runConfig
        );
        // Assert
        assertNotNull(context.branch(), "branch Optional should not be null");
        assertFalse(context.branch().isPresent(), "branch should be empty by default");
    }
    @Test
    @Tag("valid")
    void createReturnsNullMemoryServiceByDefault() {
        // Act
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                invocationId,
                mockAgent,
                mockSession,
                userContent,
                runConfig
        );
        // Assert
        assertNull(context.memoryService(), "Memory service should be null by default");
    }
    @Test
    @Tag("valid")
    void createReturnsNullPluginManagerByDefault() {
        // Act
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                invocationId,
                mockAgent,
                mockSession,
                userContent,
                runConfig
        );
        // Assert
        assertNull(context.pluginManager(), "Plugin manager should be null by default");
    }
    @Test
    @Tag("valid")
    void createReturnsEmptyActiveStreamingToolsByDefault() {
        // Act
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                invocationId,
                mockAgent,
                mockSession,
                userContent,
                runConfig
        );
        // Assert
        assertNotNull(context.activeStreamingTools(), "Active streaming tools map should not be null");
        assertTrue(context.activeStreamingTools().isEmpty(), "Active streaming tools map should be empty by default");
    }
    @Test
    @Tag("valid")
    void createReturnsLiveRequestQueueAsEmptyByDefault() {
        // Act
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                invocationId,
                mockAgent,
                mockSession,
                userContent,
                runConfig
        );
        // Assert
        assertNotNull(context.liveRequestQueue(), "liveRequestQueue Optional should not be null");
        assertFalse(context.liveRequestQueue().isPresent(), "liveRequestQueue should be empty by default");
    }
    @Test
    @Tag("boundary")
    void createWithEmptyStringInvocationIdStoresEmptyString() {
        // Arrange
        String emptyInvocationId = "";
        // Act
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                emptyInvocationId,
                mockAgent,
                mockSession,
                userContent,
                runConfig
        );
        // Assert
        assertNotNull(context);
        assertEquals("", context.invocationId(), "Invocation ID should be empty string");
    }
    @Test
    @Tag("boundary")
    void createWithNullInvocationIdStoresNullInvocationId() {
        // Act
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                null,
                mockAgent,
                mockSession,
                userContent,
                runConfig
        );
        // Assert
        assertNotNull(context);
        assertNull(context.invocationId(), "Invocation ID should be null");
    }
    @Test
    @Tag("boundary")
    void createWithNullAgentStoresNullAgent() {
        // Act
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                invocationId,
                null,
                mockSession,
                userContent,
                runConfig
        );
        // Assert
        assertNotNull(context);
        assertNull(context.agent(), "Agent should be null");
    }
    @Test
    @Tag("boundary")
    void createWithNullSessionStoresNullSession() {
        // Act
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                invocationId,
                mockAgent,
                null,
                userContent,
                runConfig
        );
        // Assert
        assertNotNull(context);
        assertNull(context.session(), "Session should be null");
    }
    @Test
    @Tag("boundary")
    void createWithAllNullParametersDoesNotThrowAndReturnsContext() {
        // Act & Assert - should not throw
        InvocationContext context = assertDoesNotThrow(() ->
                InvocationContext.create(null, null, null, null, null, null, null)
        );
        assertNotNull(context, "Context should not be null even with all null parameters");
        assertNull(context.sessionService());
        assertNull(context.artifactService());
        assertNull(context.invocationId());
        assertNull(context.agent());
        assertNull(context.session());
        assertFalse(context.userContent().isPresent());
        assertNull(context.runConfig());
    }
    @Test
    @Tag("valid")
    void createWithRunConfigHavingMaxLlmCallsSetsRunConfigCorrectly() {
        // Arrange
        RunConfig configWithLlmLimit = RunConfig.builder().setMaxLlmCalls(100).build();
        // Act
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                invocationId,
                mockAgent,
                mockSession,
                userContent,
                configWithLlmLimit
        );
        // Assert
        assertNotNull(context);
        assertNotNull(context.runConfig());
        assertEquals(100, context.runConfig().maxLlmCalls(), "RunConfig max LLM calls should be 100");
    }
    @Test
    @Tag("valid")
    void createMultipleTimesReturnsDifferentInstances() {
        // Act
        InvocationContext context1 = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                "invocation-id-1",
                mockAgent,
                mockSession,
                userContent,
                runConfig
        );
        InvocationContext context2 = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                "invocation-id-2",
                mockAgent,
                mockSession,
                userContent,
                runConfig
        );
        // Assert
        assertNotNull(context1);
        assertNotNull(context2);
        assertNotSame(context1, context2, "Each call to create should return a new instance");
        assertNotEquals(context1.invocationId(), context2.invocationId(), "Invocation IDs should differ");
    }
    @Test
    @Tag("valid")
    void createWrapsUserContentInOptional() {
        // Arrange
        Content nonNullContent = Content.fromParts(Part.fromText("test message"));
        // Act
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                invocationId,
                mockAgent,
                mockSession,
                nonNullContent,
                runConfig
        );
        // Assert
        assertNotNull(context);
        assertEquals(Optional.of(nonNullContent), context.userContent(),
                "userContent should be wrapped in Optional.of()");
    }
    @Test
    @Tag("valid")
    void createWrapsNullUserContentInOptionalEmpty() {
        // Act
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                invocationId,
                mockAgent,
                mockSession,
                null,
                runConfig
        );
        // Assert
        assertNotNull(context);
        assertEquals(Optional.empty(), context.userContent(),
                "null userContent should be wrapped in Optional.empty()");
    }
    @Test
    @Tag("integration")
    void createAndVerifyContextIsUsableWithSessionMethods() {
        // Arrange
        Session realSession = Session.builder("session-id-001")
                .appName("testApp")
                .userId("testUser")
                .build();
        // Act
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                invocationId,
                mockAgent,
                realSession,
                userContent,
                runConfig
        );
        // Assert
        assertNotNull(context);
        assertEquals("session-id-001", context.session().id());
        assertEquals("testApp", context.appName());
        assertEquals("testUser", context.userId());
    }
    @Test
    @Tag("integration")
    void createThenSetEndInvocationChangesState() {
        // Act
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                invocationId,
                mockAgent,
                mockSession,
                userContent,
                runConfig
        );
        assertFalse(context.endInvocation(), "endInvocation should be false initially");
        context.setEndInvocation(true);
        // Assert
        assertTrue(context.endInvocation(), "endInv