/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=create_6e6963ca78
ROOST_METHOD_SIG_HASH=create_ac1179ff57

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/june-java-unit/1782282457/source/adk-java/core/src/test/java/com/google/adk/agents/ToolResolverTest.java
Tests:
    "@Test
public void testResolveToolInstance_fromRegistry() throws Exception {
    FunctionTool testTool = FunctionTool.create(TestToolWithMethods.class, "method1");
    testRegistry.register("test.tool.instance", testTool);
    BaseTool resolved = ToolResolver.resolveToolInstance("test.tool.instance");
    assertThat(resolved).isEqualTo(testTool);
}
"
    "@Test
public void testResolveTools_mixedTypes() throws Exception {

    FunctionTool registeredTool = FunctionTool.create(TestToolWithMethods.class, "method1");
    testRegistry.register("registered.tool", registeredTool);
    ImmutableList<BaseTool.ToolConfig> toolConfigs = ImmutableList.of(
    createToolConfig("registered.tool", null),
    createToolConfig(TestToolWithDefaultConstructor.class.getName(), null), createToolConfig(TestToolWithStaticField.class.getName() + ".INSTANCE",
    null));
    ImmutableList<BaseTool> resolved = ToolResolver.resolveTools(toolConfigs, "/test/path");
    assertThat(resolved).hasSize(3);
    assertThat(resolved.get(0)).isEqualTo(registeredTool);
    assertThat(resolved.get(1)).isInstanceOf(TestToolWithDefaultConstructor.class);
    assertThat(resolved.get(2)).isInstanceOf(TestToolWithStaticField.class);
}
"Scenario 1: Create InvocationContext with All Valid Non-Null Parameters

Details:
  TestName: createWithAllValidNonNullParameters
  Description: Verifies that calling the create method with all valid, non-null parameters produces a fully populated InvocationContext instance where each field is correctly assigned.

Execution:
  Arrange:
    - Create a mock or stub instance of BaseSessionService.
    - Create a mock or stub instance of BaseArtifactService.
    - Create a mock or stub instance of BaseAgent.
    - Create a mock or stub instance of Session.
    - Create a mock or stub instance of LiveRequestQueue.
    - Create a RunConfig instance using RunConfig.builder().build().
  Act:
    - Call InvocationContext.create(sessionService, artifactService, agent, session, liveRequestQueue, runConfig).
  Assert:
    - Assert that the returned InvocationContext is not null.
    - Assert that context.sessionService() equals the provided sessionService.
    - Assert that context.artifactService() equals the provided artifactService.
    - Assert that context.agent() equals the provided agent.
    - Assert that context.session() equals the provided session.
    - Assert that context.liveRequestQueue() is equal to Optional.of(liveRequestQueue).
    - Assert that context.runConfig() equals the provided runConfig.

Validation:
  This test ensures that when all parameters are provided and non-null, the factory method correctly delegates to the builder and produces an InvocationContext with every field set to the expected value. It validates the fundamental happy-path behavior of the create method.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class InvocationContextCreate573Test {

	@Mock
	private BaseSessionService mockSessionService;

	@Mock
	private BaseArtifactService mockArtifactService;

	@Mock
	private BaseAgent mockAgent;

	@Mock
	private Session mockSession;

	private LiveRequestQueue liveRequestQueue;

	private RunConfig runConfig;

	@BeforeEach
	void setUp() {
		liveRequestQueue = new LiveRequestQueue();
		runConfig = RunConfig.builder().build();
	}

	@Test
	@Tag("valid")
	void createWithAllValidNonNullParameters() {
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, liveRequestQueue, runConfig);
		assertNotNull(context);
		assertEquals(mockSessionService, context.sessionService());
		assertEquals(mockArtifactService, context.artifactService());
		assertEquals(mockAgent, context.agent());
		assertEquals(mockSession, context.session());
		assertEquals(Optional.of(liveRequestQueue), context.liveRequestQueue());
		assertEquals(runConfig, context.runConfig());
	}

	@Test
	@Tag("valid")
	void createWithNullLiveRequestQueue() {
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, null, runConfig);
		assertNotNull(context);
		assertEquals(Optional.empty(), context.liveRequestQueue());
		assertEquals(mockSessionService, context.sessionService());
		assertEquals(mockArtifactService, context.artifactService());
		assertEquals(mockAgent, context.agent());
		assertEquals(mockSession, context.session());
		assertEquals(runConfig, context.runConfig());
	}

	@Test
	@Tag("valid")
	void createWithNullSessionService() {
		InvocationContext context = InvocationContext.create(null, mockArtifactService, mockAgent, mockSession,
				liveRequestQueue, runConfig);
		assertNotNull(context);
		assertNull(context.sessionService());
		assertEquals(mockArtifactService, context.artifactService());
		assertEquals(mockAgent, context.agent());
		assertEquals(mockSession, context.session());
		assertEquals(Optional.of(liveRequestQueue), context.liveRequestQueue());
	}

	@Test
	@Tag("valid")
	void createWithNullArtifactService() {
		InvocationContext context = InvocationContext.create(mockSessionService, null, mockAgent, mockSession,
				liveRequestQueue, runConfig);
		assertNotNull(context);
		assertNull(context.artifactService());
		assertEquals(mockSessionService, context.sessionService());
		assertEquals(mockAgent, context.agent());
		assertEquals(mockSession, context.session());
		assertEquals(Optional.of(liveRequestQueue), context.liveRequestQueue());
	}

	@Test
	@Tag("valid")
	void createWithNullAgent() {
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, null, mockSession,
				liveRequestQueue, runConfig);
		assertNotNull(context);
		assertNull(context.agent());
		assertEquals(mockSessionService, context.sessionService());
		assertEquals(mockArtifactService, context.artifactService());
		assertEquals(mockSession, context.session());
		assertEquals(Optional.of(liveRequestQueue), context.liveRequestQueue());
	}

	@Test
	@Tag("valid")
	void createWithNullSession() {
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent, null,
				liveRequestQueue, runConfig);
		assertNotNull(context);
		assertNull(context.session());
		assertEquals(mockSessionService, context.sessionService());
		assertEquals(mockArtifactService, context.artifactService());
		assertEquals(mockAgent, context.agent());
		assertEquals(Optional.of(liveRequestQueue), context.liveRequestQueue());
	}

	@Test
	@Tag("valid")
	void createWithNullRunConfig() {
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, liveRequestQueue, null);
		assertNotNull(context);
		assertNull(context.runConfig());
		assertEquals(mockSessionService, context.sessionService());
		assertEquals(mockArtifactService, context.artifactService());
		assertEquals(mockAgent, context.agent());
		assertEquals(mockSession, context.session());
		assertEquals(Optional.of(liveRequestQueue), context.liveRequestQueue());
	}

	@Test
	@Tag("boundary")
	void createWithAllNullParameters() {
		InvocationContext context = InvocationContext.create(null, null, null, null, null, null);
		assertNotNull(context);
		assertNull(context.sessionService());
		assertNull(context.artifactService());
		assertNull(context.agent());
		assertNull(context.session());
		assertEquals(Optional.empty(), context.liveRequestQueue());
		assertNull(context.runConfig());
	}

	@Test
	@Tag("valid")
	void createReturnsContextWithEmptyInvocationId() {
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, liveRequestQueue, runConfig);
		assertNotNull(context);
		assertNull(context.invocationId());
	}

	@Test
	@Tag("valid")
	void createReturnsContextWithEmptyUserContent() {
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, liveRequestQueue, runConfig);
		assertNotNull(context);
		assertNotNull(context.userContent());
		assertFalse(context.userContent().isPresent());
	}

	@Test
	@Tag("valid")
	void createReturnsContextWithEndInvocationFalse() {
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, liveRequestQueue, runConfig);
		assertNotNull(context);
		assertFalse(context.endInvocation());
	}

	@Test
	@Tag("valid")
	void createReturnsContextWithEmptyBranch() {
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, liveRequestQueue, runConfig);
		assertNotNull(context);
		assertNotNull(context.branch());
		assertFalse(context.branch().isPresent());
	}

	@Test
	@Tag("valid")
	void createReturnsContextWithEmptyActiveStreamingTools() {
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, liveRequestQueue, runConfig);
		assertNotNull(context);
		assertNotNull(context.activeStreamingTools());
		assertTrue(context.activeStreamingTools().isEmpty());
	}

	@Test
	@Tag("valid")
	void createWithLiveRequestQueuePresent() {
		LiveRequestQueue queue = new LiveRequestQueue();
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, queue, runConfig);
		assertNotNull(context);
		assertTrue(context.liveRequestQueue().isPresent());
		assertEquals(queue, context.liveRequestQueue().get());
	}

	@Test
	@Tag("integration")
	void createWithRunConfigMaxLlmCallsCustomValue() {
		RunConfig customRunConfig = RunConfig.builder().setMaxLlmCalls(100).build();
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, liveRequestQueue, customRunConfig);
		assertNotNull(context);
		assertEquals(100, context.runConfig().maxLlmCalls());
	}

	@Test
	@Tag("integration")
	void createReturnsDistinctInstancesOnMultipleCalls() {
		InvocationContext context1 = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, liveRequestQueue, runConfig);
		InvocationContext context2 = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, liveRequestQueue, runConfig);
		assertNotNull(context1);
		assertNotNull(context2);
		assertNotSame(context1, context2);
	}

	@Test
	@Tag("integration")
	void createContextCanBeUsedWithCopyOf() {
		InvocationContext original = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, liveRequestQueue, runConfig);
		InvocationContext copy = InvocationContext.copyOf(original);
		assertNotNull(copy);
		assertEquals(original.sessionService(), copy.sessionService());
		assertEquals(original.artifactService(), copy.artifactService());
		assertEquals(original.agent(), copy.agent());
		assertEquals(original.session(), copy.session());
		assertEquals(original.liveRequestQueue(), copy.liveRequestQueue());
		assertEquals(original.runConfig(), copy.runConfig());
		assertEquals(original.endInvocation(), copy.endInvocation());
	}

	@Test
	@Tag("valid")
	void createWithDifferentSessionServicesReturnsDifferentContexts() {
		BaseSessionService anotherSessionService = mock(BaseSessionService.class);
		InvocationContext context1 = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, liveRequestQueue, runConfig);
		InvocationContext context2 = InvocationContext.create(anotherSessionService, mockArtifactService, mockAgent,
				mockSession, liveRequestQueue, runConfig);
		assertNotNull(context1);
		assertNotNull(context2);
		assertNotEquals(context1.sessionService(), context2.sessionService());
	}

	@Test
	@Tag("valid")
	void createContextMemoryServiceIsNull() {
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, liveRequestQueue, runConfig);
		assertNotNull(context);
		assertNull(context.memoryService());
	}

	@Test
	@Tag("valid")
	void createContextPluginManagerIsNull() {
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, liveRequestQueue, runConfig);
		assertNotNull(context);
		assertNull(context.pluginManager());
	}

	@Test
	@Tag("integration")
	void createContextEqualsAnotherContextWithSameParameters() {
		InvocationContext context1 = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, liveRequestQueue, runConfig);
		InvocationContext context2 = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, liveRequestQueue, runConfig);
		assertNotNull(context1);
		assertNotNull(context2);
		assertEquals(context1, context2);
	}

	@Test
	@Tag("boundary")
	void createWithNewLiveRequestQueueHasCorrectOptionalWrapping() {
		LiveRequestQueue queue = new LiveRequestQueue();
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, queue, runConfig);
		assertNotNull(context);
		Optional<LiveRequestQueue> liveQueueOpt = context.liveRequestQueue();
		assertNotNull(liveQueueOpt);
		assertTrue(liveQueueOpt.isPresent());
		assertSame(queue, liveQueueOpt.get());
	}

}
