/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=memoryService_1115878a43
ROOST_METHOD_SIG_HASH=memoryService_b8500b83f5

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/june-java-unit/1782282926/source/adk-java/core/src/test/java/com/google/adk/agents/AgentWithMemoryTest.java
Tests:
    "@Test
public void agentRemembersUserNameWithMemoryTool() throws Exception {
    String userId = "test-user";
    String agentName = "test-agent";
    Part functionCall = Part.builder().functionCall(FunctionCall.builder().name("loadMemory").args(ImmutableMap.of("query", "what is my name?")).build()).build();
    TestLlm testLlm = new TestLlm(ImmutableList.of(LlmResponse.builder().content(Content.builder().parts(Part.fromText("OK, I'll remember that.")).role("model").build()).build(), LlmResponse.builder().content(Content.builder().role("model").parts(ImmutableList.of(functionCall)).build()).build(), LlmResponse.builder().content(Content.builder().

    parts(Part.fromText("Your name is James.")).role("model").build()).build()));
    LlmAgent agent = LlmAgent.builder().name(agentName).model(testLlm).tools(ImmutableList.of(new LoadMemoryTool())).build();
    InMemoryRunner runner = new InMemoryRunner(agent);
    String sessionId = runner.sessionService().createSession(agentName, userId).blockingGet().id();
    Content firstMessage = Content.fromParts(Part.fromText("My name is James"));
    var unused = runner.runAsync(userId, sessionId, firstMessage, RunConfig.builder().build()).toList().blockingGet();

    Session updatedSession = runner.sessionService().getSession("test-agent", userId, sessionId, Optional.empty()).blockingGet();

    runner.memoryService().addSessionToMemory(updatedSession).blockingAwait();
    Content secondMessage = Content.fromParts(Part.fromText("what is my name?"));
    unused = runner.runAsync(userId, updatedSession.id(), secondMessage, RunConfig.builder().build()).toList().blockingGet();

    LlmRequest lastRequest = testLlm.getLastRequest();
    Content functionResponseContent = Iterables.getLast(lastRequest.contents());
    Optional<Part> functionResponsePart = functionResponseContent.parts().get().stream().filter(p -> p.functionResponse().isPresent()).findFirst();
    assertThat(functionResponsePart).isPresent();
    FunctionResponse functionResponse = functionResponsePart.get().functionResponse().get();
    assertThat(functionResponse.name()).hasValue("loadMemory");
    assertThat(functionResponse.response().get().toString()).contains("My name is James");
}
"

File Path: /var/tmp/Roost/RoostGPT/june-java-unit/1782282926/source/adk-java/core/src/test/java/com/google/adk/agents/InvocationContextTest.java
Tests:
    "@Test
public void testCreateWithUserContent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).isEmpty();
    assertThat(context.invocationId()).isEqualTo(testInvocationId);
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).hasValue(userContent);
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testCreateWithNullUserContent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.userContent()).isEmpty();
}
"
    "@Test
public void testCreateWithLiveRequestQueue() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).liveRequestQueue(liveRequestQueue).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).hasValue(liveRequestQueue);

    assertThat(context.invocationId()).startsWith("e-");
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).isEmpty();
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testCopyOf() {
    InvocationContext originalContext = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    originalContext.activeStreamingTools().putAll(activeStreamingTools);
    InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
    assertThat(copiedContext).isNotNull();
    assertThat(copiedContext).isNotSameInstanceAs(originalContext);
    assertThat(copiedContext.sessionService()).isEqualTo(originalContext.sessionService());
    assertThat(copiedContext.artifactService()).isEqualTo(originalContext.artifactService());
    assertThat(copiedContext.memoryService()).isEqualTo(originalContext.memoryService());
    assertThat(copiedContext.liveRequestQueue()).isEqualTo(originalContext.liveRequestQueue());
    assertThat(copiedContext.invocationId()).isEqualTo(originalContext.invocationId());
    assertThat(copiedContext.agent()).isEqualTo(originalContext.agent());
    assertThat(copiedContext.session()).isEqualTo(originalContext.session());
    assertThat(copiedContext.userContent()).isEqualTo(originalContext.userContent());
    assertThat(copiedContext.runConfig()).isEqualTo(originalContext.runConfig());
    assertThat(copiedContext.endInvocation()).isEqualTo(originalContext.endInvocation());
    assertThat(copiedContext.activeStreamingTools()).isEqualTo(originalContext.activeStreamingTools());
}
"
    "@Test
public void testGetters() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).isEmpty();
    assertThat(context.invocationId()).isEqualTo(testInvocationId);
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).hasValue(userContent);
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testSetAgent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    BaseAgent newMockAgent = mock(BaseAgent.class);
    context.agent(newMockAgent);
    assertThat(context.agent()).isEqualTo(newMockAgent);
}
"
    "@Test
public void testEquals_sameObject() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(context)).isTrue();
}
"
    "@Test
public void testEquals_null() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(null)).isFalse();
}
"
    "@Test
public void testEquals_sameValues() {
    InvocationContext context1 = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext context2 = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context1.equals(context2)).isTrue();

    assertThat(context2.equals(context1)).isTrue();
}
"
    "@Test
public void testEquals_differentValues() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext contextWithDiffSessionService = InvocationContext.builder().sessionService(
    mock(BaseSessionService.class)).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffInvocationId = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(
    "another-id").agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffAgent = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(
    mock(BaseAgent.class)).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithUserContentEmpty = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithLiveQueuePresent = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).liveRequestQueue(liveRequestQueue).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(contextWithDiffSessionService)).isFalse();
    assertThat(context.equals(contextWithDiffInvocationId)).isFalse();
    assertThat(context.equals(contextWithDiffAgent)).isFalse();
    assertThat(context.equals(contextWithUserContentEmpty)).isFalse();
    assertThat(context.equals(contextWithLiveQueuePresent)).isFalse();
}
"
    "@Test
public void testHashCode_differentValues() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext contextWithDiffSessionService = InvocationContext.builder().sessionService(
    mock(BaseSessionService.class)).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffInvocationId = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(
    "another-id").agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotEqualTo(contextWithDiffSessionService);
    assertThat(context).isNotEqualTo(contextWithDiffInvocationId);
}
"
    "@Test
public void isResumable_whenResumabilityConfigIsNotResumable_isFalse() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(false)).build();
    assertThat(context.isResumable()).isFalse();
}
"
    "@Test
public void isResumable_whenResumabilityConfigIsResumable_isTrue() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(true)).build();
    assertThat(context.isResumable()).isTrue();
}
"
    "@Test
public void shouldPauseInvocation_whenNotResumable_isFalse() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(false)).build();
    Event event = Event.builder().longRunningToolIds(Optional.of(ImmutableSet.of("fc1"))).content(Content.builder().parts(ImmutableList.of(Part.builder().functionCall(FunctionCall.builder().name("tool1").id("fc1").build()).build())).build()).build();
    assertThat(context.shouldPauseInvocation(event)).isFalse();
}
"
    "@Test
public void shouldPauseInvocation_whenResumableAndNoLongRunningToolIds_isFalse() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(true)).build();
    Event event = Event.builder().content(Content.builder().parts(ImmutableList.of(Part.builder().functionCall(FunctionCall.builder().name("tool1").id("fc1").build()).build())).build()).build();
    assertThat(context.shouldPauseInvocation(event)).isFalse();
}
"
    "@Test
public void shouldPauseInvocation_whenResumableAndNoFunctionCalls_isFalse() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(true)).build();
    Event event = Event.builder().longRunningToolIds(Optional.of(ImmutableSet.of("fc1"))).build();
    assertThat(context.shouldPauseInvocation(event)).isFalse();
}
"
    "@Test
public void shouldPauseInvocation_whenResumableAndNoMatchingFunctionCallId_isFalse() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(true)).build();
    Event event = Event.builder().longRunningToolIds(Optional.of(ImmutableSet.of("fc2"))).content(Content.builder().parts(ImmutableList.of(Part.builder().functionCall(FunctionCall.builder().name("tool1").id("fc1").build()).build())).build()).build();
    assertThat(context.shouldPauseInvocation(event)).isFalse();
}
"
    "@Test
public void shouldPauseInvocation_whenResumableAndMatchingFunctionCallId_isTrue() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(true)).build();
    Event event = Event.builder().longRunningToolIds(Optional.of(ImmutableSet.of("fc1"))).content(Content.builder().parts(ImmutableList.of(Part.builder().functionCall(FunctionCall.builder().name("tool1").id("fc1").build()).build())).build()).build();
    assertThat(context.shouldPauseInvocation(event)).isTrue();
}
"Scenario 1: Return the Memory Service Instance When Set with a Valid Mock

Details:
  TestName: memoryServiceReturnsCorrectInstanceWhenSetWithMock
  Description: Verifies that the memoryService() method returns the exact same BaseMemoryService instance
               that was provided during the construction of the InvocationContext via the builder.
Execution:
  Arrange: Create a mock instance of BaseMemoryService. Build an InvocationContext using the builder,
           providing the mock memory service, along with the required sessionService, artifactService,
           agent, and session fields.
  Act: Call memoryService() on the built InvocationContext instance.
  Assert: Assert that the returned value is equal to (and the same instance as) the mock
          BaseMemoryService that was set during construction.
Validation:
  This test ensures that the getter correctly returns the field value set at construction time without
  any transformation or modification. It is fundamental to confirm that the internal field assignment
  in the constructor works correctly and the getter exposes it properly.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.flows.llmflows.ResumabilityConfig;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.genai.types.Content;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class InvocationContextMemoryServiceTest {

	@Mock
	private BaseSessionService mockSessionService;

	@Mock
	private BaseArtifactService mockArtifactService;

	@Mock
	private BaseMemoryService mockMemoryService;

	@Mock
	private BaseAgent mockAgent;

	@Mock
	private Session mockSession;

	@Mock
	private RunConfig mockRunConfig;

	@Mock
	private PluginManager mockPluginManager;

	@Mock
	private ResumabilityConfig mockResumabilityConfig;

	@BeforeEach
  void setUp() {
    when(mockSession.appName()).thenReturn("testApp");
    when(mockSession.userId()).thenReturn("testUser");
  }

	@Test
	@Tag("valid")
	void memoryServiceReturnsCorrectInstanceWhenSetWithMock() {
		// Arrange
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("test-invocation-id")
			.runConfig(mockRunConfig)
			.build();
		// Act
		BaseMemoryService result = context.memoryService();
		// Assert
		assertSame(mockMemoryService, result);
		assertEquals(mockMemoryService, result);
	}

	@Test
	@Tag("valid")
	void memoryServiceReturnsNullWhenNotSet() {
		// Arrange
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("test-invocation-id")
			.runConfig(mockRunConfig)
			.build();
		// Act
		BaseMemoryService result = context.memoryService();
		// Assert
		assertNull(result);
	}

	@Test
	@Tag("valid")
	void memoryServiceReturnsSameReferenceAfterMultipleCalls() {
		// Arrange
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("test-invocation-id")
			.runConfig(mockRunConfig)
			.build();
		// Act
		BaseMemoryService firstCall = context.memoryService();
		BaseMemoryService secondCall = context.memoryService();
		BaseMemoryService thirdCall = context.memoryService();
		// Assert
		assertSame(firstCall, secondCall);
		assertSame(secondCall, thirdCall);
		assertSame(mockMemoryService, firstCall);
	}

	@Test
	@Tag("valid")
	void memoryServiceReturnsDifferentInstancesForDifferentContexts() {
		// Arrange
		BaseMemoryService mockMemoryService1 = mock(BaseMemoryService.class);
		BaseMemoryService mockMemoryService2 = mock(BaseMemoryService.class);
		InvocationContext context1 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService1)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("invocation-id-1")
			.runConfig(mockRunConfig)
			.build();
		InvocationContext context2 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService2)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("invocation-id-2")
			.runConfig(mockRunConfig)
			.build();
		// Act
		BaseMemoryService result1 = context1.memoryService();
		BaseMemoryService result2 = context2.memoryService();
		// Assert
		assertSame(mockMemoryService1, result1);
		assertSame(mockMemoryService2, result2);
		assertNotSame(result1, result2);
	}

	@Test
	@Tag("integration")
	void memoryServicePreservedAfterCopyOf() {
		// Arrange
		InvocationContext originalContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("test-invocation-id")
			.runConfig(mockRunConfig)
			.build();
		// Act
		InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
		// Assert
		assertSame(mockMemoryService, copiedContext.memoryService());
		assertEquals(originalContext.memoryService(), copiedContext.memoryService());
	}

	@Test
	@Tag("valid")
	void memoryServiceReturnedFromContextCreatedViaStaticFactory() {
		// Arrange
		Content userContent = Content.fromParts();
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService,
				"test-invocation-id", mockAgent, mockSession, userContent, mockRunConfig);
		// Act
		BaseMemoryService result = context.memoryService();
		// Assert
		// When using the static factory create(), memoryService is not set, so it should
		// be null
		assertNull(result);
	}

	@Test
	@Tag("valid")
	void memoryServiceSetViaBuilderReturnedCorrectly() {
		// Arrange
		BaseMemoryService specificMemoryService = mock(BaseMemoryService.class);
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(specificMemoryService)
			.pluginManager(mockPluginManager)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("detailed-invocation-id")
			.runConfig(mockRunConfig)
			.build();
		// Act
		BaseMemoryService result = context.memoryService();
		// Assert
		assertNotNull(result);
		assertSame(specificMemoryService, result);
	}

	@Test
	@Tag("boundary")
	void memoryServiceNullWhenCopyOfContextWithNoMemoryService() {
		// Arrange
		InvocationContext originalContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("test-invocation-id")
			.runConfig(mockRunConfig)
			.build();
		// Act
		InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
		// Assert
		assertNull(originalContext.memoryService());
		assertNull(copiedContext.memoryService());
	}

	@Test
	@Tag("valid")
	void memoryServiceReturnedCorrectlyWithAllFieldsSet() {
		// Arrange
		LiveRequestQueue liveRequestQueue = new LiveRequestQueue();
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.pluginManager(mockPluginManager)
			.liveRequestQueue(Optional.of(liveRequestQueue))
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("full-invocation-id")
			.runConfig(mockRunConfig)
			.branch("test-branch")
			.build();
		// Act
		BaseMemoryService result = context.memoryService();
		// Assert
		assertNotNull(result);
		assertSame(mockMemoryService, result);
	}

	@Test
	@Tag("integration")
	void memoryServiceUnchangedAfterModifyingOtherFields() {
		// Arrange
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("test-invocation-id")
			.runConfig(mockRunConfig)
			.build();
		// Act: Modify other fields that have setters
		context.branch("new-branch");
		context.setEndInvocation(true);
		BaseAgent anotherAgent = mock(BaseAgent.class);
		context.agent(anotherAgent);
		BaseMemoryService result = context.memoryService();
		// Assert
		assertSame(mockMemoryService, result);
	}

	@Test
	@Tag("valid")
	void memoryServiceNotInteractedWithDuringRetrieval() {
		// Arrange
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("test-invocation-id")
			.runConfig(mockRunConfig)
			.build();
		// Act
		context.memoryService();
		// Assert: The memory service mock should have had no interactions when just
		// retrieved
		verifyNoInteractions(mockMemoryService);
	}

	@Test
	@Tag("integration")
	void memoryServiceConsistentBetweenOriginalAndCopiedContext() {
		// Arrange
		InvocationContext originalContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("test-invocation-id")
			.runConfig(mockRunConfig)
			.build();
		InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
		// Act
		BaseMemoryService originalMemoryService = originalContext.memoryService();
		BaseMemoryService copiedMemoryService = copiedContext.memoryService();
		// Assert
		assertSame(originalMemoryService, copiedMemoryService);
		assertSame(mockMemoryService, originalMemoryService);
		assertSame(mockMemoryService, copiedMemoryService);
	}

	@Test
	@Tag("boundary")
	void memoryServiceWithDeprecatedConstructorReturnsCorrectInstance() {
		// Arrange
		String invocationId = "deprecated-constructor-invocation-id";
		@SuppressWarnings("deprecation")
		InvocationContext context = new InvocationContext(mockSessionService, mockArtifactService, mockMemoryService,
				mockPluginManager, Optional.empty(), Optional.empty(), invocationId, mockAgent, mockSession,
				Optional.empty(), mockRunConfig, false);
		// Act
		BaseMemoryService result = context.memoryService();
		// Assert
		assertNotNull(result);
		assertSame(mockMemoryService, result);
	}

}
