/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=newInvocationContextId_87a927076b
ROOST_METHOD_SIG_HASH=newInvocationContextId_db44e2dbb1

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/june-java-unit/1782282457/source/adk-java/core/src/test/java/com/google/adk/agents/InvocationContextTest.java
Tests:
    "@Test
public void testNewInvocationContextId() {
    String id = InvocationContext.newInvocationContextId();
    assertThat(id).isNotNull();
    assertThat(id).isNotEmpty();
    assertThat(id).startsWith("e-");

    assertThat(id.substring(2)).matches("^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$");
}
"Scenario 1: Verify That Two Consecutive Invocation IDs Are Unique

Details:
  TestName: newInvocationContextIdGeneratesUniqueIdsOnConsecutiveCalls
  Description: Verifies that calling newInvocationContextId() multiple times in sequence
               produces different ID values each time, ensuring the UUID-based generation
               provides proper uniqueness for each invocation context.
Execution:
  Arrange: No special setup is required since newInvocationContextId() is a static method
           with no dependencies or parameters.
  Act: Call InvocationContext.newInvocationContextId() twice in succession, storing
       each result in separate String variables (firstId and secondId).
  Assert: Use assertThat(firstId).isNotEqualTo(secondId) to confirm the two IDs differ.
Validation:
  This assertion confirms that the UUID.randomUUID() component ensures each call yields
  a distinct identifier. In the context of the InvocationContext lifecycle, the invocationId
  field must be unique per context instance, so repeated calls must never produce collisions
  under normal operating conditions.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static com.google.common.truth.Truth.assertThat;
import static org.junit.jupiter.api.Assertions.*;

import java.util.HashSet;
import java.util.Set;
import java.util.regex.Pattern;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

class InvocationContextNewInvocationContextIdTest {

	private static final Pattern UUID_PATTERN = Pattern
		.compile("^e-[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$");

	@Test
	@Tag("valid")
	void newInvocationContextIdGeneratesUniqueIdsOnConsecutiveCalls() {
		String firstId = InvocationContext.newInvocationContextId();
		String secondId = InvocationContext.newInvocationContextId();
		assertThat(firstId).isNotEqualTo(secondId);
	}

	@Test
	@Tag("valid")
	void newInvocationContextIdReturnsNonNullValue() {
		String id = InvocationContext.newInvocationContextId();
		assertThat(id).isNotNull();
	}

	@Test
	@Tag("valid")
	void newInvocationContextIdStartsWithExpectedPrefix() {
		String id = InvocationContext.newInvocationContextId();
		assertThat(id).startsWith("e-");
	}

	@Test
	@Tag("valid")
	void newInvocationContextIdMatchesExpectedFormat() {
		String id = InvocationContext.newInvocationContextId();
		assertThat(UUID_PATTERN.matcher(id).matches()).isTrue();
	}

	@Test
	@Tag("valid")
	void newInvocationContextIdHasCorrectLength() {
		String id = InvocationContext.newInvocationContextId();
		// "e-" (2 chars) + UUID (36 chars) = 38 chars
		assertThat(id).hasLength(38);
	}

	@Test
	@Tag("valid")
	void newInvocationContextIdContainsUuidAfterPrefix() {
		String id = InvocationContext.newInvocationContextId();
		String uuidPart = id.substring(2);
		assertThat(uuidPart).isNotEmpty();
		Pattern uuidOnlyPattern = Pattern
			.compile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$");
		assertThat(uuidOnlyPattern.matcher(uuidPart).matches()).isTrue();
	}

	@Test
	@Tag("valid")
	void newInvocationContextIdGeneratesUniqueIdsInLargeBatch() {
		int batchSize = 1000;
		Set<String> ids = new HashSet<>();
		for (int i = 0; i < batchSize; i++) {
			ids.add(InvocationContext.newInvocationContextId());
		}
		assertThat(ids).hasSize(batchSize);
	}

	@Test
	@Tag("valid")
	void newInvocationContextIdReturnsDifferentIdsOnThreeConsecutiveCalls() {
		String firstId = InvocationContext.newInvocationContextId();
		String secondId = InvocationContext.newInvocationContextId();
		String thirdId = InvocationContext.newInvocationContextId();
		assertThat(firstId).isNotEqualTo(secondId);
		assertThat(secondId).isNotEqualTo(thirdId);
		assertThat(firstId).isNotEqualTo(thirdId);
	}

	@Test
	@Tag("valid")
	void newInvocationContextIdPrefixIsExactlyEDash() {
		String id = InvocationContext.newInvocationContextId();
		assertThat(id.substring(0, 2)).isEqualTo("e-");
	}

	@Test
	@Tag("valid")
	void newInvocationContextIdDoesNotReturnEmptyString() {
		String id = InvocationContext.newInvocationContextId();
		assertThat(id).isNotEmpty();
	}

	@Test
	@Tag("valid")
	void newInvocationContextIdUuidPartContainsFourHyphens() {
		String id = InvocationContext.newInvocationContextId();
		String uuidPart = id.substring(2);
		long hyphenCount = uuidPart.chars().filter(c -> c == '-').count();
		assertThat(hyphenCount).isEqualTo(4);
	}

	@Test
	@Tag("boundary")
	void newInvocationContextIdNeverReturnsNullAcrossMultipleCalls() {
		for (int i = 0; i < 100; i++) {
			String id = InvocationContext.newInvocationContextId();
			assertThat(id).isNotNull();
		}
	}

	@Test
	@Tag("boundary")
	void newInvocationContextIdAlwaysStartsWithPrefixAcrossMultipleCalls() {
		for (int i = 0; i < 100; i++) {
			String id = InvocationContext.newInvocationContextId();
			assertThat(id).startsWith("e-");
		}
	}

	@Test
	@Tag("boundary")
	void newInvocationContextIdAlwaysHasCorrectLengthAcrossMultipleCalls() {
		for (int i = 0; i < 100; i++) {
			String id = InvocationContext.newInvocationContextId();
			assertThat(id).hasLength(38);
		}
	}

	@Test
	@Tag("boundary")
	void newInvocationContextIdGeneratesUniqueIdsInSmallBatch() {
		int batchSize = 10;
		Set<String> ids = new HashSet<>();
		for (int i = 0; i < batchSize; i++) {
			ids.add(InvocationContext.newInvocationContextId());
		}
		assertThat(ids).hasSize(batchSize);
	}

	@Test
	@Tag("integration")
	void newInvocationContextIdCanBeUsedAsInvocationIdInBuilder() {
		String generatedId = InvocationContext.newInvocationContextId();
		assertThat(generatedId).isNotNull();
		assertThat(UUID_PATTERN.matcher(generatedId).matches()).isTrue();
		assertThat(generatedId).startsWith("e-");
	}

	@Test
	@Tag("integration")
	void newInvocationContextIdIsThreadSafeAndProducesUniqueValuesFromMultipleThreads() throws InterruptedException {
		int threadCount = 10;
		int idsPerThread = 50;
		Set<String> allIds = java.util.Collections.synchronizedSet(new HashSet<>());
		Thread[] threads = new Thread[threadCount];
		for (int i = 0; i < threadCount; i++) {
			threads[i] = new Thread(() -> {
				for (int j = 0; j < idsPerThread; j++) {
					allIds.add(InvocationContext.newInvocationContextId());
				}
			});
		}
		for (Thread thread : threads) {
			thread.start();
		}
		for (Thread thread : threads) {
			thread.join();
		}
		assertThat(allIds).hasSize(threadCount * idsPerThread);
	}

	@Test
	@Tag("valid")
	void newInvocationContextIdUuidPartHasCorrectSegmentLengths() {
		String id = InvocationContext.newInvocationContextId();
		String uuidPart = id.substring(2);
		String[] segments = uuidPart.split("-");
		assertThat(segments).hasLength(5);
		assertThat(segments[0]).hasLength(8);
		assertThat(segments[1]).hasLength(4);
		assertThat(segments[2]).hasLength(4);
		assertThat(segments[3]).hasLength(4);
		assertThat(segments[4]).hasLength(12);
	}

	@Test
	@Tag("valid")
	void newInvocationContextIdUuidPartContainsOnlyHexCharactersAndHyphens() {
		String id = InvocationContext.newInvocationContextId();
		String uuidPart = id.substring(2);
		assertThat(uuidPart).matches("[0-9a-fA-F\\-]+");
	}

	@Test
	@Tag("valid")
	void newInvocationContextIdReturnValueIsImmutableString() {
		String id = InvocationContext.newInvocationContextId();
		assertThat(id).isInstanceOf(String.class);
		assertThat(id).isNotNull();
	}

}
