/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=artifactService_d673c8a05b
ROOST_METHOD_SIG_HASH=artifactService_769a3f8842

Scenario 1: Verify That artifactService Returns the Correct Non-Null Artifact Service Instance

Details:
  TestName: artifactServiceReturnsConfiguredInstance
  Description: Verifies that the artifactService() method returns the exact BaseArtifactService instance
               that was provided during the construction of InvocationContext via the builder.

Execution:
  Arrange:
    - Create a mock or concrete implementation of BaseArtifactService.
    - Create a mock or concrete implementation of BaseSessionService.
    - Create a mock or concrete implementation of Session.
    - Create a mock or concrete implementation of BaseAgent.
    - Build an InvocationContext using InvocationContext.builder()
        .sessionService(mockSessionService)
        .artifactService(mockArtifactService)
        .agent(mockAgent)
        .session(mockSession)
        .build().
  Act:
    - Call invocationContext.artifactService().
  Assert:
    - Assert that the returned value is not null.
    - Assert that the returned value is the same instance (reference equality) as the mockArtifactService
      provided to the builder.

Validation:
  This assertion confirms that the artifactService() method correctly surfaces the injected
  BaseArtifactService dependency without modification or wrapping. In the context of the
  InvocationContext, the artifact service is a critical dependency used for persisting artifacts
  during agent execution; returning the wrong instance would cause silent failures in artifact management.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.flows.llmflows.ResumabilityConfig;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.genai.types.Content;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class InvocationContextArtifactServiceTest {
  @Mock private BaseArtifactService mockArtifactService;
  @Mock private BaseSessionService mockSessionService;
  @Mock private BaseMemoryService mockMemoryService;
  @Mock private PluginManager mockPluginManager;
  @Mock private Session mockSession;
  @Mock private BaseAgent mockAgent;
  @Mock private RunConfig mockRunConfig;

  @BeforeEach
  void setUp() {
    when(mockSession.appName()).thenReturn("testApp");
    when(mockSession.userId()).thenReturn("testUser");
    when(mockSession.id()).thenReturn("testSession");
  }

  @Test
  @Tag("valid")
  void artifactServiceReturnsConfiguredInstance() {
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("test-invocation-id")
            .build();
    BaseArtifactService result = context.artifactService();
    assertNotNull(result, "artifactService() should not return null");
    assertSame(
        mockArtifactService,
        result,
        "artifactService() should return the exact same instance provided to builder");
  }

  @Test
  @Tag("valid")
  void artifactServiceReturnsSameReferenceAfterMultipleCalls() {
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("test-invocation-id")
            .build();
    BaseArtifactService firstCall = context.artifactService();
    BaseArtifactService secondCall = context.artifactService();
    assertSame(
        firstCall,
        secondCall,
        "artifactService() should return the same instance on repeated calls");
  }

  @Test
  @Tag("invalid")
  void artifactServiceReturnsNullWhenNotConfigured() {
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("test-invocation-id")
            .build();
    BaseArtifactService result = context.artifactService();
    assertNull(result, "artifactService() should return null when not configured");
  }

  @Test
  @Tag("valid")
  void artifactServiceReturnedIsNotMemoryService() {
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .memoryService(mockMemoryService)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("test-invocation-id")
            .build();
    BaseArtifactService result = context.artifactService();
    assertNotNull(result);
    assertSame(mockArtifactService, result);
    assertNotSame(
        mockMemoryService,
        result,
        "artifactService() should not return the memory service instance");
  }

  @Test
  @Tag("valid")
  void artifactServiceReturnedIsNotSessionService() {
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("test-invocation-id")
            .build();
    BaseArtifactService result = context.artifactService();
    assertNotNull(result);
    assertSame(mockArtifactService, result);
    assertNotSame(
        mockSessionService,
        result,
        "artifactService() should not return the session service instance");
  }

  @Test
  @Tag("valid")
  void artifactServiceIsReturnedCorrectlyWithAllDependencies() {
    BaseArtifactService anotherMockArtifactService = mock(BaseArtifactService.class);
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(anotherMockArtifactService)
            .memoryService(mockMemoryService)
            .pluginManager(mockPluginManager)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("test-invocation-id")
            .branch(Optional.of("testBranch"))
            .userContent(Optional.empty())
            .runConfig(mockRunConfig)
            .build();
    BaseArtifactService result = context.artifactService();
    assertNotNull(result);
    assertSame(
        anotherMockArtifactService,
        result,
        "artifactService() should return the specific artifact service instance used in builder");
  }

  @Test
  @Tag("valid")
  void artifactServiceIsIndependentAcrossTwoContexts() {
    BaseArtifactService firstArtifactService = mock(BaseArtifactService.class);
    BaseArtifactService secondArtifactService = mock(BaseArtifactService.class);
    InvocationContext firstContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(firstArtifactService)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("invocation-1")
            .build();
    InvocationContext secondContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(secondArtifactService)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("invocation-2")
            .build();
    assertSame(
        firstArtifactService,
        firstContext.artifactService(),
        "First context should return its own artifact service");
    assertSame(
        secondArtifactService,
        secondContext.artifactService(),
        "Second context should return its own artifact service");
    assertNotSame(
        firstContext.artifactService(),
        secondContext.artifactService(),
        "Each context should have its own distinct artifact service");
  }

  @Test
  @Tag("integration")
  void artifactServiceIsPreservedAfterCopyOf() {
    InvocationContext originalContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("original-invocation-id")
            .build();
    InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
    assertNotNull(
        copiedContext.artifactService(), "Copied context should have non-null artifact service");
    assertSame(
        mockArtifactService,
        copiedContext.artifactService(),
        "Copied context should retain the same artifact service reference");
  }

  @Test
  @Tag("integration")
  void artifactServiceIsPreservedAfterCopyOfWithAllFields() {
    ResumabilityConfig resumabilityConfig = mock(ResumabilityConfig.class);
    when(resumabilityConfig.isResumable()).thenReturn(false);
    InvocationContext originalContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .memoryService(mockMemoryService)
            .pluginManager(mockPluginManager)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("original-id")
            .branch(Optional.of("main"))
            .userContent(Optional.empty())
            .runConfig(mockRunConfig)
            .resumabilityConfig(resumabilityConfig)
            .build();
    InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
    assertSame(
        mockArtifactService,
        copiedContext.artifactService(),
        "CopyOf should preserve artifact service reference");
  }

  @Test
  @Tag("valid")
  void artifactServiceReturnedFromStaticCreateMethod() {
    Content userContent = mock(Content.class);
    InvocationContext context =
        InvocationContext.create(
            mockSessionService,
            mockArtifactService,
            "test-invocation-id",
            mockAgent,
            mockSession,
            userContent,
            mockRunConfig);
    assertNotNull(
        context.artifactService(),
        "artifactService() should not be null when using static create method");
    assertSame(
        mockArtifactService,
        context.artifactService(),
        "artifactService() should return the exact instance passed to static create method");
  }

  @Test
  @Tag("valid")
  void artifactServiceReturnedFromStaticCreateMethodWithLiveRequestQueue() {
    LiveRequestQueue liveRequestQueue = new LiveRequestQueue();
    InvocationContext context =
        InvocationContext.create(
            mockSessionService,
            mockArtifactService,
            mockAgent,
            mockSession,
            liveRequestQueue,
            mockRunConfig);
    assertNotNull(
        context.artifactService(),
        "artifactService() should not be null when created with live request queue");
    assertSame(
        mockArtifactService,
        context.artifactService(),
        "artifactService() should return the exact instance used in static create with live queue");
  }

  @Test
  @Tag("boundary")
  void artifactServiceIsNullWhenNullExplicitlyPassedToBuilder() {
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(null)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("test-invocation-id")
            .build();
    assertNull(
        context.artifactService(),
        "artifactService() should return null when explicitly set to null in builder");
  }

  @Test
  @Tag("valid")
  void artifactServiceDoesNotReturnPluginManager() {
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .pluginManager(mockPluginManager)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("test-invocation-id")
            .build();
    BaseArtifactService result = context.artifactService();
    assertNotNull(result);
    assertSame(mockArtifactService, result);
    assertNotSame(
        mockPluginManager,
        result,
        "artifactService() should not return the plugin manager instance");
  }

  @Test
  @Tag("valid")
  void artifactServiceIsDistinctFromSession() {
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("test-invocation-id")
            .build();
    BaseArtifactService result = context.artifactService();
    assertNotNull(result);
    assertNotSame(mockSession, result, "artifactService() should not return the session instance");
  }

  @Test
  @Tag("valid")
  void artifactServiceIsDistinctFromAgent() {
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("test-invocation-id")
            .build();
    BaseArtifactService result = context.artifactService();
    assertNotNull(result);
    assertNotSame(mockAgent, result, "artifactService() should not return the agent instance");
  }

  @Test
  @Tag("valid")
  void artifactServiceWithInvocationIdSetCorrectly() {
    String invocationId = "specific-invocation-" + java.util.UUID.randomUUID();
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId(invocationId)
            .build();
    assertNotNull(
        context.artifactService(),
        "artifactService() should not return null with a specific invocationId");
    assertSame(
        mockArtifactService,
        context.artifactService(),
        "artifactService() should return the same instance even with specific invocationId");
    assertEquals(invocationId, context.invocationId(), "invocationId should be correctly set");
  }

  @Test
  @Tag("boundary")
  void artifactServiceRemainsConsistentWhenEndInvocationIsTrue() {
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("test-invocation-id")
            .endInvocation(true)
            .build();
    assertNotNull(
        context.artifactService(),
        "artifactService() should not be null even when endInvocation is true");
    assertSame(
        mockArtifactService,
        context.artifactService(),
        "artifactService() should return the correct instance even when endInvocation is true");
    assertTrue(context.endInvocation(), "endInvocation should be true");
  }
}
