/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=invocationId_b0959abc16
ROOST_METHOD_SIG_HASH=invocationId_6cd6fb05e4

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/june-java-unit/1782282457/source/adk-java/core/src/test/java/com/google/adk/agents/InvocationContextTest.java
Tests:
    "@Test
public void testCreateWithUserContent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).isEmpty();
    assertThat(context.invocationId()).isEqualTo(testInvocationId);
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).hasValue(userContent);
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testCreateWithNullUserContent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.userContent()).isEmpty();
}
"
    "@Test
public void testCreateWithLiveRequestQueue() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).liveRequestQueue(liveRequestQueue).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).hasValue(liveRequestQueue);

    assertThat(context.invocationId()).startsWith("e-");
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).isEmpty();
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testCopyOf() {
    InvocationContext originalContext = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    originalContext.activeStreamingTools().putAll(activeStreamingTools);
    InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
    assertThat(copiedContext).isNotNull();
    assertThat(copiedContext).isNotSameInstanceAs(originalContext);
    assertThat(copiedContext.sessionService()).isEqualTo(originalContext.sessionService());
    assertThat(copiedContext.artifactService()).isEqualTo(originalContext.artifactService());
    assertThat(copiedContext.memoryService()).isEqualTo(originalContext.memoryService());
    assertThat(copiedContext.liveRequestQueue()).isEqualTo(originalContext.liveRequestQueue());
    assertThat(copiedContext.invocationId()).isEqualTo(originalContext.invocationId());
    assertThat(copiedContext.agent()).isEqualTo(originalContext.agent());
    assertThat(copiedContext.session()).isEqualTo(originalContext.session());
    assertThat(copiedContext.userContent()).isEqualTo(originalContext.userContent());
    assertThat(copiedContext.runConfig()).isEqualTo(originalContext.runConfig());
    assertThat(copiedContext.endInvocation()).isEqualTo(originalContext.endInvocation());
    assertThat(copiedContext.activeStreamingTools()).isEqualTo(originalContext.activeStreamingTools());
}
"
    "@Test
public void testGetters() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).isEmpty();
    assertThat(context.invocationId()).isEqualTo(testInvocationId);
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).hasValue(userContent);
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testSetAgent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    BaseAgent newMockAgent = mock(BaseAgent.class);
    context.agent(newMockAgent);
    assertThat(context.agent()).isEqualTo(newMockAgent);
}
"
    "@Test
public void testEquals_sameObject() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(context)).isTrue();
}
"
    "@Test
public void testEquals_null() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(null)).isFalse();
}
"
    "@Test
public void testEquals_sameValues() {
    InvocationContext context1 = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext context2 = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context1.equals(context2)).isTrue();

    assertThat(context2.equals(context1)).isTrue();
}
"
    "@Test
public void testEquals_differentValues() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext contextWithDiffSessionService = InvocationContext.builder().sessionService(
    mock(BaseSessionService.class)).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffInvocationId = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(
    "another-id").agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffAgent = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(
    mock(BaseAgent.class)).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithUserContentEmpty = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithLiveQueuePresent = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).liveRequestQueue(liveRequestQueue).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(contextWithDiffSessionService)).isFalse();
    assertThat(context.equals(contextWithDiffInvocationId)).isFalse();
    assertThat(context.equals(contextWithDiffAgent)).isFalse();
    assertThat(context.equals(contextWithUserContentEmpty)).isFalse();
    assertThat(context.equals(contextWithLiveQueuePresent)).isFalse();
}
"
    "@Test
public void testHashCode_differentValues() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext contextWithDiffSessionService = InvocationContext.builder().sessionService(
    mock(BaseSessionService.class)).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffInvocationId = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(
    "another-id").agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotEqualTo(contextWithDiffSessionService);
    assertThat(context).isNotEqualTo(contextWithDiffInvocationId);
}
"

File Path: /var/tmp/Roost/RoostGPT/june-java-unit/1782282457/source/adk-java/core/src/test/java/com/google/adk/agents/CallbacksTest.java
Tests:
    "@Test
public void testRun_withModelCallbacks_receivesCorrectContext() {
    Content realContent = Content.fromParts(Part.fromText("Real LLM response"));
    TestLlm testLlm = createTestLlm(createLlmResponse(realContent));
    LlmAgent agent = createTestAgentBuilder(testLlm).beforeModelCallback((callbackContext, request) -> {
        assertThat(callbackContext.invocationId()).isNotEmpty();
        assertThat(callbackContext.agentName()).isEqualTo("test agent");
        return Maybe.empty();
    }).afterModelCallback((callbackContext, response) -> {
        assertThat(callbackContext.invocationId()).isNotEmpty();
        assertThat(callbackContext.agentName()).isEqualTo("test agent");
        assertThat(response.content()).hasValue(realContent);
        return Maybe.empty();
    }).build();
    InvocationContext invocationContext = createInvocationContext(agent);
    List<Event> events = agent.runAsync(invocationContext).toList().blockingGet();
    assertThat(events).hasSize(1);
    assertThat(getOnlyElement(events).content()).hasValue(realContent);
}
"

File Path: /var/tmp/Roost/RoostGPT/june-java-unit/1782282457/source/adk-java/core/src/test/java/com/google/adk/agents/LlmAgentTest.java
Tests:
    "@Test
public void testCanonicalInstruction_providerInstructionInjectsContext() {
    String instruction = "Test provider instruction for invocation: ";
    LlmAgent agent = createTestAgentBuilder(createTestLlm(LlmResponse.builder().build())).instruction(new Instruction.Provider(context -> Single.just(instruction + context.invocationId()))).build();
    ReadonlyContext invocationContext = new ReadonlyContext(createInvocationContext(agent));
    String canonicalInstruction = agent.canonicalInstruction(invocationContext).blockingGet().getKey();
    assertThat(canonicalInstruction).isEqualTo(instruction + invocationContext.invocationId());
}
"
    "@Test
public void testCanonicalGlobalInstruction_providerInstructionInjectsContext() {
    String instruction = "Test provider global instruction for invocation: ";
    LlmAgent agent = createTestAgentBuilder(createTestLlm(LlmResponse.builder().build())).globalInstruction(new Instruction.Provider(context -> Single.just(instruction + context.invocationId()))).build();
    ReadonlyContext invocationContext = new ReadonlyContext(createInvocationContext(agent));
    String canonicalInstruction = agent.canonicalGlobalInstruction(invocationContext).blockingGet().getKey();
    assertThat(canonicalInstruction).isEqualTo(instruction + invocationContext.invocationId());
}
"

File Path: /var/tmp/Roost/RoostGPT/june-java-unit/1782282457/source/adk-java/core/src/test/java/com/google/adk/agents/InstructionTest.java
Tests:
    "@Test
public void testCanonicalInstruction_providerInstructionInjectsContext() {
    String instruction = "Test provider instruction for invocation: ";
    LlmAgent agent = createTestAgentBuilder(createTestLlm(LlmResponse.builder().build())).instruction(new Instruction.Provider(context -> Single.just(instruction + context.invocationId()))).build();
    ReadonlyContext invocationContext = new ReadonlyContext(createInvocationContext(agent));
    String canonicalInstruction = agent.canonicalInstruction(invocationContext).blockingGet().getKey();
    assertThat(canonicalInstruction).isEqualTo(instruction + invocationContext.invocationId());
}
"
    "@Test
public void testCanonicalGlobalInstruction_providerInstructionInjectsContext() {
    String instruction = "Test provider global instruction for invocation: ";
    LlmAgent agent = createTestAgentBuilder(createTestLlm(LlmResponse.builder().build())).globalInstruction(new Instruction.Provider(context -> Single.just(instruction + context.invocationId()))).build();
    ReadonlyContext invocationContext = new ReadonlyContext(createInvocationContext(agent));
    String canonicalInstruction = agent.canonicalGlobalInstruction(invocationContext).blockingGet().getKey();
    assertThat(canonicalInstruction).isEqualTo(instruction + invocationContext.invocationId());
}
"

File Path: /var/tmp/Roost/RoostGPT/june-java-unit/1782282457/source/adk-java/core/src/test/java/com/google/adk/agents/SequentialAgentTest.java
Tests:
    "@Test
public void runAsync_propagatesInvocationContextToSubAgents() {
    TestBaseAgent subAgent = createSubAgent("subAgent");
    SequentialAgent sequentialAgent = SequentialAgent.builder().name("seqAgent").subAgents(ImmutableList.of(subAgent)).build();
    InvocationContext parentContext = createInvocationContext(sequentialAgent);
    List<Event> unused = sequentialAgent.runAsync(parentContext).toList().blockingGet();
    InvocationContext capturedContext = subAgent.getLastInvocationContext();
    assertThat(capturedContext).isNotNull();
    assertThat(capturedContext.invocationId()).isEqualTo(parentContext.invocationId());
    assertThat(capturedContext.session()).isEqualTo(parentContext.session());
    assertThat(capturedContext.agent()).isEqualTo(subAgent);
    assertThat(subAgent.getInvocationCount()).isEqualTo(1);
}
"
    "@Test
public void runLive_propagatesInvocationContextToSubAgents() {
    TestBaseAgent subAgent = createSubAgent("subAgent_live");
    SequentialAgent sequentialAgent = SequentialAgent.builder().name("seqAgentLive").subAgents(ImmutableList.of(subAgent)).build();
    InvocationContext parentContext = createInvocationContext(sequentialAgent);
    List<Event> unused = sequentialAgent.runLive(parentContext).toList().blockingGet();
    InvocationContext capturedContext = subAgent.getLastInvocationContext();
    assertThat(capturedContext).isNotNull();
    assertThat(capturedContext.invocationId()).isEqualTo(parentContext.invocationId());
    assertThat(capturedContext.session()).isEqualTo(parentContext.session());
    assertThat(capturedContext.agent()).isEqualTo(subAgent);
    assertThat(subAgent.getInvocationCount()).isEqualTo(1);
}
"Scenario 1: Verify invocationId Returns the Exact Value Set via Builder

Details:
  TestName: invocationIdReturnsExactValueSetViaBuilder
  Description: Verifies that the invocationId() method returns the exact string value that was explicitly set through the builder's invocationId() method. This confirms that the field is properly stored and retrieved without any transformation.

Execution:
  Arrange: Build an InvocationContext using the builder, providing a specific known invocationId string (e.g., "test-invocation-123") along with all other required fields (sessionService, artifactService, memoryService, pluginManager, agent, session, userContent, runConfig).
  Act: Call invocationId() on the constructed InvocationContext instance.
  Assert: Assert that the returned value is equal to the exact string "test-invocation-123" that was passed to the builder.

Validation:
  The assertion confirms that the invocationId field is faithfully stored and returned by the getter without modification. This is critical because invocationId is used to correlate events, callbacks, and sub-agent executions back to a single invocation lifecycle.


Scenario 2: Verify invocationId Returns Auto-Generated Value When Not Explicitly Set

Details:
  TestName: invocationIdReturnsAutoGeneratedValueWhenNotExplicitlySet
  Description: Verifies that when no invocationId is explicitly provided to the builder, the invocationId() method returns a non-null, non-empty auto-generated value that follows the expected "e-" prefix format produced by newInvocationContextId().

Execution:
  Arrange: Build an InvocationContext using the builder without calling invocationId() on the builder — relying on the default value. Provide all other required fields (sessionService, artifactService, memoryService, pluginManager, agent, session, userContent, runConfig).
  Act: Call invocationId() on the constructed InvocationContext instance.
  Assert: Assert that the returned value is not null, not empty, and starts with the prefix "e-".

Validation:
  The assertion confirms that the default invocationId generation mechanism (newInvocationContextId()) works correctly and produces a valid identifier. This is important to guarantee that every invocation has a unique identity even when the caller does not supply one.


Scenario 3: Verify invocationId Returns a Non-Null Value

Details:
  TestName: invocationIdReturnsNonNullValue
  Description: Verifies that the invocationId() method never returns null when an invocationId has been explicitly set through the builder.

Execution:
  Arrange: Build an InvocationContext using the builder with a non-null invocationId string (e.g., "non-null-id-456"). Provide all other required fields (sessionService, artifactService, memoryService, pluginManager, agent, session, userContent, runConfig).
  Act: Call invocationId() on the constructed InvocationContext instance.
  Assert: Assert that the returned value is not null.

Validation:
  The assertion ensures the getter does not introduce unexpected null returns. Since other parts of the system (such as callbacks and sub-agent propagation) rely on invocationId() to be a valid non-null string, this check is essential for downstream correctness.


Scenario 4: Verify invocationId Is Consistent Across Multiple Calls

Details:
  TestName: invocationIdIsConsistentAcrossMultipleCalls
  Description: Verifies that calling invocationId() multiple times on the same InvocationContext instance always returns the same immutable value, confirming the field is final and does not change between calls.

Execution:
  Arrange: Build an InvocationContext using the builder with a specific invocationId string (e.g., "stable-invocation-id"). Provide all other required fields (sessionService, artifactService, memoryService, pluginManager, agent, session, userContent, runConfig).
  Act: Call invocationId() on the constructed InvocationContext instance three times and store each result.
  Assert: Assert that all three returned values are equal to each other and equal to "stable-invocation-id".

Validation:
  The assertion confirms the immutability of the invocationId field. Because invocationId is declared as a private final String, it must be stable throughout the lifetime of the object. This stability is required so that the invocation ID remains consistent when used across multiple components, callbacks, and sub-agents.


Scenario 5: Verify invocationId Is Preserved by copyOf

Details:
  TestName: invocationIdIsPreservedByCopyOf
  Description: Verifies that when InvocationContext.copyOf() is used to create a shallow copy of an existing context, the invocationId() of the copied context is equal to the original context's invocationId().

Execution:
  Arrange: Build an InvocationContext using the builder with a specific invocationId string (e.g., "original-invocation-id"). Provide all other required fields. Then call InvocationContext.copyOf() with the original context.
  Act: Call invocationId() on the copied InvocationContext instance.
  Assert: Assert that the invocationId() of the copied context equals the invocationId() of the original context ("original-invocation-id").

Validation:
  The assertion confirms that the copyOf operation correctly propagates the invocationId to the new context. This is significant because sub-agents and delegated executions that use copied contexts must share the same invocationId to maintain traceability within a single invocation lifecycle.


Scenario 6: Verify invocationId Returns a Non-Empty String

Details:
  TestName: invocationIdReturnsNonEmptyString
  Description: Verifies that the invocationId() method returns a non-empty string when a valid non-empty invocationId is provided through the builder.

Execution:
  Arrange: Build an InvocationContext using the builder with a non-empty invocationId string (e.g., "valid-id-789"). Provide all other required fields (sessionService, artifactService, memoryService, pluginManager, agent, session, userContent, runConfig).
  Act: Call invocationId() on the constructed InvocationContext instance.
  Assert: Assert that the returned string is not empty.

Validation:
  The assertion ensures that the stored invocationId is not inadvertently cleared or emptied during construction. An empty invocationId would break correlation logic in callbacks and agent propagation, making this a critical validation.


Scenario 7: Verify Two Distinct InvocationContext Instances Have Different Auto-Generated invocationIds

Details:
  TestName: twoDistinctContextsHaveDifferentAutoGeneratedInvocationIds
  Description: Verifies that two InvocationContext instances built without an explicit invocationId each receive a different auto-generated invocationId, confirming the uniqueness guarantee of the default ID generation.

Execution:
  Arrange: Build two separate InvocationContext instances using the builder, neither of which has an explicitly set invocationId. Provide all other required fields to both builders (sessionService, artifactService, memoryService, pluginManager, agent, session, userContent, runConfig).
  Act: Call invocationId() on both instances and store the results.
  Assert: Assert that the two invocationId values are not equal to each other.

Validation:
  The assertion confirms that the UUID-based generation in newInvocationContextId() produces unique values for different instances. Uniqueness is a foundational requirement for tracking and differentiating concurrent or sequential invocations in a multi-agent system.


Scenario 8: Verify invocationId Matches the Value Used in Auto-Generated Format

Details:
  TestName: invocationIdMatchesAutoGeneratedFormat
  Description: Verifies that an auto-generated invocationId (when not explicitly set) matches the expected format produced by newInvocationContextId(), i.e., it starts with "e-" followed by a UUID string.

Execution:
  Arrange: Build an InvocationContext using the builder without calling invocationId() explicitly. Provide all other required fields (sessionService, artifactService, memoryService, pluginManager, agent, session, userContent, runConfig).
  Act: Call invocationId() on the constructed InvocationContext instance.
  Assert: Assert that the returned value starts with "e-" and has a total length consistent with the "e-" prefix plus a standard UUID string (e.g., length greater than 2).

Validation:
  The assertion confirms adherence to the naming convention enforced by newInvocationContextId(). This format is important because other parts of the system (such as sub-agent context propagation tests) expect invocationIds to conform to this pattern for identification and debugging purposes.


Scenario 9: Verify invocationId Is Independent of Other Field Mutations

Details:
  TestName: invocationIdRemainsUnchangedAfterAgentMutation
  Description: Verifies that calling the mutable setter agent() on an InvocationContext does not affect the value returned by invocationId(), confirming that the final invocationId field is fully isolated from mutable state changes.

Execution:
  Arrange: Build an InvocationContext using the builder with a specific invocationId (e.g., "immutable-id-001") and a mock agent. Provide all other required fields. Create a second mock agent object.
  Act: Call agent() on the context to replace the agent with the second mock agent. Then call invocationId() on the same context.
  Assert: Assert that the value returned by invocationId() is still equal to "immutable-id-001".

Validation:
  The assertion confirms that mutating mutable fields (like agent) does not corrupt or change the invocationId field. Since invocationId is declared final, this test serves as a safeguard against accidental misuse or future refactoring that might inadvertently break field isolation.


Scenario 10: Verify invocationId With an Explicit UUID-Format String

Details:
  TestName: invocationIdWithExplicitUuidFormatString
  Description: Verifies that the invocationId() method correctly stores and returns an explicitly provided UUID-format string (e.g., a value resembling "e-" followed by a UUID), just as it would be stored by the builder.

Execution:
  Arrange: Generate a UUID-format invocationId string using InvocationContext.newInvocationContextId() or by constructing a string in the format "e-" + UUID.randomUUID().toString(). Build an InvocationContext using the builder, passing this generated string as the invocationId. Provide all other required fields.
  Act: Call invocationId() on the constructed InvocationContext instance.
  Assert: Assert that the returned value equals the UUID-format string that was set.

Validation:
  The assertion ensures that the builder correctly stores and the getter correctly retrieves a UUID-format invocationId. This scenario mirrors real-world usage patterns where the caller may pre-generate an invocationId using the provided utility method before constructing the context.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.flows.llmflows.ResumabilityConfig;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.genai.types.Content;
import java.util.Optional;
import java.util.UUID;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class InvocationContextInvocationIdTest {

	@Mock
	private BaseSessionService mockSessionService;

	@Mock
	private BaseArtifactService mockArtifactService;

	@Mock
	private BaseMemoryService mockMemoryService;

	@Mock
	private PluginManager mockPluginManager;

	@Mock
	private BaseAgent mockAgent;

	@Mock
	private BaseAgent mockAgent2;

	@Mock
	private Session mockSession;

	@Mock
	private RunConfig mockRunConfig;

	@Mock
	private ResumabilityConfig mockResumabilityConfig;

	@Mock
	private Content mockContent;

	@BeforeEach
  void setUp() {
    when(mockSession.appName()).thenReturn("testApp");
    when(mockSession.userId()).thenReturn("testUser");
  }

	private InvocationContext.Builder baseBuilder() {
		return InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.pluginManager(mockPluginManager)
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.ofNullable(mockContent))
			.runConfig(mockRunConfig)
			.resumabilityConfig(mockResumabilityConfig);
	}

	@Test
	@Tag("valid")
	void invocationIdReturnsExactValueSetViaBuilder() {
		String expectedId = "test-invocation-123";
		InvocationContext context = baseBuilder().invocationId(expectedId).build();
		String actualId = context.invocationId();
		assertEquals(expectedId, actualId);
	}

	@Test
	@Tag("valid")
	void invocationIdReturnsAutoGeneratedValueWhenNotExplicitlySet() {
		InvocationContext context = baseBuilder().build();
		String actualId = context.invocationId();
		assertNotNull(actualId);
		assertFalse(actualId.isEmpty());
		assertTrue(actualId.startsWith("e-"),
				"Auto-generated invocationId should start with 'e-' but was: " + actualId);
	}

	@Test
	@Tag("valid")
	void invocationIdReturnsNonNullValue() {
		String inputId = "non-null-id-456";
		InvocationContext context = baseBuilder().invocationId(inputId).build();
		String actualId = context.invocationId();
		assertNotNull(actualId);
	}

	@Test
	@Tag("valid")
	void invocationIdIsConsistentAcrossMultipleCalls() {
		String expectedId = "stable-invocation-id";
		InvocationContext context = baseBuilder().invocationId(expectedId).build();
		String firstCall = context.invocationId();
		String secondCall = context.invocationId();
		String thirdCall = context.invocationId();
		assertEquals(expectedId, firstCall);
		assertEquals(expectedId, secondCall);
		assertEquals(expectedId, thirdCall);
		assertEquals(firstCall, secondCall);
		assertEquals(secondCall, thirdCall);
	}

	@Test
	@Tag("integration")
	void invocationIdIsPreservedByCopyOf() {
		String expectedId = "original-invocation-id";
		InvocationContext originalContext = baseBuilder().invocationId(expectedId).build();
		InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
		assertEquals(expectedId, copiedContext.invocationId());
		assertEquals(originalContext.invocationId(), copiedContext.invocationId());
	}

	@Test
	@Tag("valid")
	void invocationIdReturnsNonEmptyString() {
		String inputId = "valid-id-789";
		InvocationContext context = baseBuilder().invocationId(inputId).build();
		String actualId = context.invocationId();
		assertNotNull(actualId);
		assertFalse(actualId.isEmpty());
	}

	@Test
	@Tag("valid")
	void twoDistinctContextsHaveDifferentAutoGeneratedInvocationIds() {
		InvocationContext context1 = baseBuilder().build();
		InvocationContext context2 = baseBuilder().build();
		String id1 = context1.invocationId();
		String id2 = context2.invocationId();
		assertNotNull(id1);
		assertNotNull(id2);
		assertNotEquals(id1, id2,
				"Two independently created InvocationContext instances should have different invocationIds");
	}

	@Test
	@Tag("valid")
	void invocationIdMatchesAutoGeneratedFormat() {
		InvocationContext context = baseBuilder().build();
		String actualId = context.invocationId();
		assertNotNull(actualId);
		assertTrue(actualId.startsWith("e-"),
				"Auto-generated invocationId should start with 'e-' but was: " + actualId);
		assertTrue(actualId.length() > 2,
				"Auto-generated invocationId should have content after 'e-' prefix, but was: " + actualId);
		// "e-" prefix (2 chars) + UUID standard length (36 chars) = 38 chars total
		assertEquals(38, actualId.length(),
				"Auto-generated invocationId should be 38 characters (2 for 'e-' + 36 for UUID) but was: " + actualId);
	}

	@Test
	@Tag("valid")
	void invocationIdRemainsUnchangedAfterAgentMutation() {
		String expectedId = "immutable-id-001";
		InvocationContext context = baseBuilder().invocationId(expectedId).agent(mockAgent).build();
		context.agent(mockAgent2);
		String actualId = context.invocationId();
		assertEquals(expectedId, actualId, "invocationId should remain unchanged after mutating the agent field");
	}

	@Test
	@Tag("valid")
	void invocationIdWithExplicitUuidFormatString() {
		String generatedId = InvocationContext.newInvocationContextId();
		InvocationContext context = baseBuilder().invocationId(generatedId).build();
		String actualId = context.invocationId();
		assertEquals(generatedId, actualId);
		assertNotNull(actualId);
		assertTrue(actualId.startsWith("e-"));
	}

	@Test
	@Tag("valid")
	void invocationIdWithCustomUuidFormatString() {
		String customId = "e-" + UUID.randomUUID().toString();
		InvocationContext context = baseBuilder().invocationId(customId).build();
		String actualId = context.invocationId();
		assertEquals(customId, actualId);
		assertTrue(actualId.startsWith("e-"));
		assertEquals(38, actualId.length());
	}

	@Test
	@Tag("boundary")
	void invocationIdWithVeryLongString() {
		String longId = "e-" + "a".repeat(1000);
		InvocationContext context = baseBuilder().invocationId(longId).build();
		String actualId = context.invocationId();
		assertEquals(longId, actualId);
		assertNotNull(actualId);
		assertFalse(actualId.isEmpty());
	}

	@Test
	@Tag("boundary")
	void invocationIdWithSingleCharacterString() {
		String singleCharId = "x";
		InvocationContext context = baseBuilder().invocationId(singleCharId).build();
		String actualId = context.invocationId();
		assertEquals(singleCharId, actualId);
		assertNotNull(actualId);
		assertFalse(actualId.isEmpty());
	}

	@Test
	@Tag("boundary")
	void invocationIdWithSpecialCharacters() {
		String specialId = "e-special!@#$%^&*()-id_001";
		InvocationContext context = baseBuilder().invocationId(specialId).build();
		String actualId = context.invocationId();
		assertEquals(specialId, actualId);
		assertNotNull(actualId);
	}

	@Test
	@Tag("integration")
	void invocationIdRemainsUnchangedAfterBranchMutation() {
		String expectedId = "branch-immutable-id";
		InvocationContext context = baseBuilder().invocationId(expectedId).build();
		context.branch("new-branch");
		String actualId = context.invocationId();
		assertEquals(expectedId, actualId, "invocationId should remain unchanged after mutating the branch field");
	}

	@Test
	@Tag("integration")
	void invocationIdRemainsUnchangedAfterEndInvocationMutation() {
		String expectedId = "end-invocation-immutable-id";
		InvocationContext context = baseBuilder().invocationId(expectedId).build();
		context.setEndInvocation(true);
		String actualId = context.invocationId();
		assertEquals(expectedId, actualId, "invocationId should remain unchanged after setting endInvocation to true");
	}

	@Test
	@Tag("valid")
	void newInvocationContextIdGeneratesUniqueIds() {
		String id1 = InvocationContext.newInvocationContextId();
		String id2 = InvocationContext.newInvocationContextId();
		String id3 = InvocationContext.newInvocationContextId();
		assertNotNull(id1);
		assertNotNull(id2);
		assertNotNull(id3);
		assertNotEquals(id1, id2);
		assertNotEquals(id2, id3);
		assertNotEquals(id1, id3);
		assertTrue(id1.startsWith("e-"));
		assertTrue(id2.startsWith("e-"));
		assertTrue(id3.startsWith("e-"));
	}

	@Test
	@Tag("integration")
	void invocationIdIsConsistentBetweenOriginalAndCopiedContext() {
		String expectedId = "copy-consistency-id";
		InvocationContext original = baseBuilder().invocationId(expectedId).build();
		InvocationContext copy = InvocationContext.copyOf(original);
		String originalId = original.invocationId();
		String copiedId = copy.invocationId();
		assertEquals(originalId, copiedId);
		assertEquals(expectedId, originalId);
		assertEquals(expectedId, copiedId);
	}

	@Test
	@Tag("valid")
	void invocationIdFromCreateFactoryMethodWithExplicitId() {
		String expectedId = "factory-create-id";
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, expectedId,
				mockAgent, mockSession, mockContent, mockRunConfig);
		String actualId = context.invocationId();
		assertEquals(expectedId, actualId);
		assertNotNull(actualId);
	}

}
