/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=userId_f2e833fd39
ROOST_METHOD_SIG_HASH=userId_5053f72666

Scenario 1: Retrieve a Standard Alphanumeric User ID from the Session

Details:
  TestName: userIdReturnsValueFromSession
  Description: Verifies that the `userId()` method correctly delegates to and returns
               the user ID from the underlying `Session` object when a standard
               alphanumeric user ID is set.

Execution:
  Arrange: - Create a mock of the `Session` class.
           - Stub `session.userId()` to return a standard alphanumeric string, e.g., "user123".
           - Build an `InvocationContext` instance using `InvocationContext.builder()`
             and supply the mocked session via `.session(mockSession)`.
  Act:     - Call `invocationContext.userId()` on the built context.
  Assert:  - Use `assertEquals("user123", invocationContext.userId())` to verify the
             returned value matches the stubbed session user ID.

Validation:
  The assertion confirms that `userId()` acts as a pure delegation to `session.userId()`,
  returning whatever the session provides without any modification. This is critical
  to ensure the `InvocationContext` correctly exposes session-level identity data
  to any component that depends on it for authorization or personalization purposes.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.genai.types.Content;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class InvocationContextUserIdTest {

	@Mock
	private Session mockSession;

	@Mock
	private BaseSessionService mockSessionService;

	@Mock
	private BaseArtifactService mockArtifactService;

	@Mock
	private BaseMemoryService mockMemoryService;

	@Mock
	private PluginManager mockPluginManager;

	@Mock
	private BaseAgent mockAgent;

	private RunConfig defaultRunConfig;

	@BeforeEach
	void setUp() {
		defaultRunConfig = RunConfig.builder().build();
	}

	private InvocationContext buildContext(Session session) {
		return InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(session)
			.runConfig(defaultRunConfig)
			.build();
	}

	@Test
  @Tag("valid")
  void userIdReturnsValueFromSession() {
    when(mockSession.userId()).thenReturn("user123");
    InvocationContext invocationContext = buildContext(mockSession);
    assertEquals("user123", invocationContext.userId());
  }

	@Test
  @Tag("valid")
  void userIdReturnsAlphanumericUserId() {
    when(mockSession.userId()).thenReturn("abc123XYZ");
    InvocationContext invocationContext = buildContext(mockSession);
    assertEquals("abc123XYZ", invocationContext.userId());
  }

	@Test
  @Tag("valid")
  void userIdReturnsNumericOnlyUserId() {
    when(mockSession.userId()).thenReturn("9876543210");
    InvocationContext invocationContext = buildContext(mockSession);
    assertEquals("9876543210", invocationContext.userId());
  }

	@Test
	@Tag("valid")
	void userIdReturnsUuidFormattedUserId() {
		String uuidUserId = "550e8400-e29b-41d4-a716-446655440000";
		when(mockSession.userId()).thenReturn(uuidUserId);
		InvocationContext invocationContext = buildContext(mockSession);
		assertEquals(uuidUserId, invocationContext.userId());
	}

	@Test
	@Tag("valid")
	void userIdReturnsDelegatesExactlyToSession() {
		String expectedUserId = "delegated_user_id";
		when(mockSession.userId()).thenReturn(expectedUserId);
		InvocationContext invocationContext = buildContext(mockSession);
		String actualUserId = invocationContext.userId();
		verify(mockSession, times(1)).userId();
		assertEquals(expectedUserId, actualUserId);
	}

	@Test
	@Tag("valid")
	void userIdReturnsEmailFormattedUserId() {
		String emailUserId = "user@example.com";
		when(mockSession.userId()).thenReturn(emailUserId);
		InvocationContext invocationContext = buildContext(mockSession);
		assertEquals(emailUserId, invocationContext.userId());
	}

	@Test
	@Tag("valid")
	void userIdReturnsUserIdWithSpecialCharacters() {
		String specialCharUserId = "user-name_123.test";
		when(mockSession.userId()).thenReturn(specialCharUserId);
		InvocationContext invocationContext = buildContext(mockSession);
		assertEquals(specialCharUserId, invocationContext.userId());
	}

	@Test
  @Tag("boundary")
  void userIdReturnsSingleCharacterUserId() {
    when(mockSession.userId()).thenReturn("u");
    InvocationContext invocationContext = buildContext(mockSession);
    assertEquals("u", invocationContext.userId());
  }

	@Test
	@Tag("boundary")
	void userIdReturnsVeryLongUserId() {
		String longUserId = "u".repeat(1000);
		when(mockSession.userId()).thenReturn(longUserId);
		InvocationContext invocationContext = buildContext(mockSession);
		assertNotNull(invocationContext.userId());
		assertEquals(1000, invocationContext.userId().length());
		assertEquals(longUserId, invocationContext.userId());
	}

	@Test
  @Tag("boundary")
  void userIdReturnsEmptyStringUserId() {
    when(mockSession.userId()).thenReturn("");
    InvocationContext invocationContext = buildContext(mockSession);
    assertNotNull(invocationContext.userId());
    assertEquals("", invocationContext.userId());
  }

	@Test
  @Tag("invalid")
  void userIdReturnsNullWhenSessionReturnsNull() {
    when(mockSession.userId()).thenReturn(null);
    InvocationContext invocationContext = buildContext(mockSession);
    assertNull(invocationContext.userId());
  }

	@Test
  @Tag("valid")
  void userIdIsConsistentAcrossMultipleCalls() {
    when(mockSession.userId()).thenReturn("consistentUser");
    InvocationContext invocationContext = buildContext(mockSession);
    String firstCall = invocationContext.userId();
    String secondCall = invocationContext.userId();
    String thirdCall = invocationContext.userId();
    assertEquals(firstCall, secondCall);
    assertEquals(secondCall, thirdCall);
    assertEquals("consistentUser", firstCall);
  }

	@Test
  @Tag("integration")
  void userIdIsAccessibleAfterCopyOf() {
    when(mockSession.userId()).thenReturn("copiedUser");
    when(mockSession.appName()).thenReturn("testApp");
    InvocationContext originalContext = buildContext(mockSession);
    InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
    assertEquals("copiedUser", copiedContext.userId());
  }

	@Test
  @Tag("integration")
  void userIdReturnsCorrectValueAfterAgentChange() {
    when(mockSession.userId()).thenReturn("user_with_agent_change");
    InvocationContext invocationContext = buildContext(mockSession);
    invocationContext.agent(mockAgent);
    assertEquals("user_with_agent_change", invocationContext.userId());
  }

	@Test
  @Tag("integration")
  void userIdReturnsCorrectValueAfterBranchSet() {
    when(mockSession.userId()).thenReturn("user_with_branch");
    InvocationContext invocationContext = buildContext(mockSession);
    invocationContext.branch("some-branch");
    assertEquals("user_with_branch", invocationContext.userId());
  }

	@Test
  @Tag("integration")
  void userIdReturnsCorrectValueWithMemoryService() {
    when(mockSession.userId()).thenReturn("userWithMemory");
    InvocationContext invocationContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .memoryService(mockMemoryService)
            .invocationId("test-invocation-id")
            .agent(mockAgent)
            .session(mockSession)
            .runConfig(defaultRunConfig)
            .build();
    assertEquals("userWithMemory", invocationContext.userId());
  }

	@Test
  @Tag("integration")
  void userIdReturnsCorrectValueWithPluginManager() {
    when(mockSession.userId()).thenReturn("userWithPlugin");
    InvocationContext invocationContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .pluginManager(mockPluginManager)
            .invocationId("test-invocation-id")
            .agent(mockAgent)
            .session(mockSession)
            .runConfig(defaultRunConfig)
            .build();
    assertEquals("userWithPlugin", invocationContext.userId());
  }

	@Test
  @Tag("integration")
  void userIdReturnsCorrectValueWithLiveRequestQueue() {
    when(mockSession.userId()).thenReturn("liveUser");
    LiveRequestQueue liveRequestQueue = new LiveRequestQueue();
    InvocationContext invocationContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .agent(mockAgent)
            .session(mockSession)
            .liveRequestQueue(Optional.of(liveRequestQueue))
            .runConfig(defaultRunConfig)
            .build();
    assertEquals("liveUser", invocationContext.userId());
  }

	@Test
  @Tag("valid")
  void userIdReturnsCorrectValueWithUserContent() {
    when(mockSession.userId()).thenReturn("userWithContent");
    Content userContent = Content.builder().build();
    InvocationContext invocationContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId("test-invocation-id")
            .agent(mockAgent)
            .session(mockSession)
            .userContent(Optional.of(userContent))
            .runConfig(defaultRunConfig)
            .build();
    assertEquals("userWithContent", invocationContext.userId());
  }

	@Test
  @Tag("valid")
  void userIdOnlyCallsSessionUserIdMethod() {
    when(mockSession.userId()).thenReturn("verifyDelegation");
    InvocationContext invocationContext = buildContext(mockSession);
    invocationContext.userId();
    verify(mockSession).userId();
    verifyNoMoreInteractions(mockSession);
  }

	@Test
  @Tag("boundary")
  void userIdReturnsWhitespaceOnlyUserId() {
    when(mockSession.userId()).thenReturn("   ");
    InvocationContext invocationContext = buildContext(mockSession);
    assertNotNull(invocationContext.userId());
    assertEquals("   ", invocationContext.userId());
  }

	@Test
	@Tag("valid")
	void userIdMatchesSessionUserIdDirectly() {
		String expectedUserId = "directUser42";
		when(mockSession.userId()).thenReturn(expectedUserId);
		InvocationContext invocationContext = buildContext(mockSession);
		assertEquals(mockSession.userId(), invocationContext.userId());
	}

	@Test
  @Tag("valid")
  void userIdReturnsUserIdWithUnderscores() {
    when(mockSession.userId()).thenReturn("user_name_123");
    InvocationContext invocationContext = buildContext(mockSession);
    assertEquals("user_name_123", invocationContext.userId());
  }

	@Test
  @Tag("valid")
  void userIdReturnsUpperCaseUserId() {
    when(mockSession.userId()).thenReturn("UPPERCASE_USER");
    InvocationContext invocationContext = buildContext(mockSession);
    assertEquals("UPPERCASE_USER", invocationContext.userId());
  }

	@Test
  @Tag("integration")
  void userIdReturnsSameValueForCopiedContextAndOriginal() {
    when(mockSession.userId()).thenReturn("sharedUser");
    when(mockSession.appName()).thenReturn("testApp");
    InvocationContext originalContext = buildContext(mockSession);
    InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
    assertEquals(originalContext.userId(), copiedContext.userId());
  }

}
