/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=runConfig_09ff6f346f
ROOST_METHOD_SIG_HASH=runConfig_dbfa69ec19

Scenario 1: Return RunConfig When Explicitly Set via Builder

Details:
  TestName: runConfigReturnsExplicitlySetRunConfig
  Description: Verifies that the `runConfig()` method returns the exact `RunConfig` instance
               that was provided to the builder when constructing the `InvocationContext`.
               This ensures the field is correctly stored and returned without modification.
Execution:
  Arrange: Create a `RunConfig` instance using `RunConfig.builder().build()` with specific
           settings. Build an `InvocationContext` using `InvocationContext.builder()`
           and supply the `RunConfig` instance via `.runConfig(runConfig)`.
  Act:     Call `invocationContext.runConfig()` on the constructed context.
  Assert:  Use `assertSame()` or `assertEquals()` to verify that the returned `RunConfig`
           is the same instance as the one supplied to the builder.
Validation:
  The assertion verifies referential equality between the input and returned `RunConfig`,
  confirming that the getter faithfully returns exactly what was set — no defensive copying
  or transformation occurs. This is important for predictable configuration behavior
  throughout an agent invocation lifecycle.

*/

// ********RoostGPT********

```java
package com.google.adk.agents;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.events.Event;
import com.google.adk.flows.llmflows.ResumabilityConfig;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.models.LlmCallsLimitExceededException;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.common.collect.ImmutableSet;
import com.google.genai.types.Content;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import javax.annotation.Nullable;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.junit.jupiter.api.*;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import com.google.errorprone.annotations.InlineMe;
import com.google.genai.types.FunctionCall;

@ExtendWith(MockitoExtension.class)
public class InvocationContextRunConfigTest {
    @Mock
    private BaseSessionService mockSessionService;
    @Mock
    private BaseArtifactService mockArtifactService;
    @Mock
    private BaseMemoryService mockMemoryService;
    @Mock
    private PluginManager mockPluginManager;
    @Mock
    private BaseAgent mockAgent;
    private Session session;
    @BeforeEach
    void setUp() {
        session = Session.builder("test-session-id")
                .appName("test-app")
                .userId("test-user")
                .build();
    }
    // -------------------------------------------------------------------------
    // Scenario 1: Return RunConfig When Explicitly Set via Builder
    // -------------------------------------------------------------------------
    @Test
    @Tag("valid")
    void runConfigReturnsExplicitlySetRunConfig() {
        // Arrange
        RunConfig runConfig = RunConfig.builder().build();
        InvocationContext context = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("inv-001")
                .agent(mockAgent)
                .session(session)
                .userContent(Optional.empty())
                .runConfig(runConfig)
                .build();
        // Act
        RunConfig returnedRunConfig = context.runConfig();
        // Assert
        assertSame(runConfig, returnedRunConfig,
                "runConfig() should return the exact same RunConfig instance provided to the builder");
    }
    // -------------------------------------------------------------------------
    // Additional valid scenarios
    // -------------------------------------------------------------------------
    @Test
    @Tag("valid")
    void runConfigReturnsNullWhenNotSet() {
        // Arrange
        InvocationContext context = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("inv-002")
                .agent(mockAgent)
                .session(session)
                .userContent(Optional.empty())
                .runConfig(null)
                .build();
        // Act
        RunConfig returnedRunConfig = context.runConfig();
        // Assert
        assertNull(returnedRunConfig,
                "runConfig() should return null when no RunConfig was provided");
    }
    @Test
    @Tag("valid")
    void runConfigReturnsDefaultRunConfig() {
        // Arrange
        RunConfig defaultRunConfig = RunConfig.builder().build();
        InvocationContext context = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("inv-003")
                .agent(mockAgent)
                .session(session)
                .userContent(Optional.empty())
                .runConfig(defaultRunConfig)
                .build();
        // Act
        RunConfig returnedRunConfig = context.runConfig();
        // Assert
        assertNotNull(returnedRunConfig, "runConfig() should not return null for a default RunConfig");
        assertEquals(defaultRunConfig, returnedRunConfig,
                "runConfig() should equal the default RunConfig provided");
    }
    @Test
    @Tag("valid")
    void runConfigWithMaxLlmCallsIsReturnedCorrectly() {
        // Arrange
        RunConfig runConfig = RunConfig.builder()
                .setMaxLlmCalls(100)
                .build();
        InvocationContext context = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("inv-004")
                .agent(mockAgent)
                .session(session)
                .userContent(Optional.empty())
                .runConfig(runConfig)
                .build();
        // Act
        RunConfig returnedRunConfig = context.runConfig();
        // Assert
        assertNotNull(returnedRunConfig, "runConfig() should not be null");
        assertEquals(100, returnedRunConfig.maxLlmCalls(),
                "runConfig() should return the RunConfig with the correct maxLlmCalls");
    }
    @Test
    @Tag("valid")
    void runConfigReturnsSameInstanceAfterMultipleCalls() {
        // Arrange
        RunConfig runConfig = RunConfig.builder().build();
        InvocationContext context = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("inv-005")
                .agent(mockAgent)
                .session(session)
                .userContent(Optional.empty())
                .runConfig(runConfig)
                .build();
        // Act
        RunConfig firstCall = context.runConfig();
        RunConfig secondCall = context.runConfig();
        // Assert
        assertSame(firstCall, secondCall,
                "runConfig() should return the same instance across multiple calls (immutable field)");
    }
    @Test
    @Tag("valid")
    void runConfigIsRetainedAfterCopyOf() {
        // Arrange
        RunConfig runConfig = RunConfig.builder()
                .setMaxLlmCalls(200)
                .build();
        InvocationContext original = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("inv-006")
                .agent(mockAgent)
                .session(session)
                .userContent(Optional.empty())
                .runConfig(runConfig)
                .build();
        // Act
        InvocationContext copy = InvocationContext.copyOf(original);
        RunConfig returnedRunConfig = copy.runConfig();
        // Assert
        assertSame(runConfig, returnedRunConfig,
                "copyOf() should preserve the same RunConfig instance");
        assertEquals(200, returnedRunConfig.maxLlmCalls(),
                "Copied context should have the same maxLlmCalls as the original");
    }
    @Test
    @Tag("valid")
    void runConfigIsRetainedInStaticCreateMethod() {
        // Arrange
        RunConfig runConfig = RunConfig.builder().build();
        Content userContent = Content.fromParts();
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                "inv-007",
                mockAgent,
                session,
                userContent,
                runConfig
        );
        // Act
        RunConfig returnedRunConfig = context.runConfig();
        // Assert
        assertSame(runConfig, returnedRunConfig,
                "static create() should store and return the same RunConfig instance");
    }
    @Test
    @Tag("valid")
    void runConfigWithStreamingModeIsReturnedCorrectly() {
        // Arrange
        RunConfig runConfig = RunConfig.builder()
                .setStreamingMode(RunConfig.StreamingMode.SSE)
                .build();
        InvocationContext context = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("inv-008")
                .agent(mockAgent)
                .session(session)
                .userContent(Optional.empty())
                .runConfig(runConfig)
                .build();
        // Act
        RunConfig returnedRunConfig = context.runConfig();
        // Assert
        assertNotNull(returnedRunConfig);
        assertEquals(RunConfig.StreamingMode.SSE, returnedRunConfig.streamingMode(),
                "runConfig() should return the RunConfig with SSE streaming mode");
    }
    @Test
    @Tag("valid")
    void runConfigWithSaveInputBlobsAsArtifactsSetToTrue() {
        // Arrange
        RunConfig runConfig = RunConfig.builder()
                .setSaveInputBlobsAsArtifacts(true)
                .build();
        InvocationContext context = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("inv-009")
                .agent(mockAgent)
                .session(session)
                .userContent(Optional.empty())
                .runConfig(runConfig)
                .build();
        // Act
        RunConfig returnedRunConfig = context.runConfig();
        // Assert
        assertNotNull(returnedRunConfig);
        assertTrue(returnedRunConfig.saveInputBlobsAsArtifacts(),
                "runConfig() should return the RunConfig with saveInputBlobsAsArtifacts=true");
    }
    @Test
    @Tag("boundary")
    void runConfigWithMaxLlmCallsOfZero() {
        // Arrange
        RunConfig runConfig = RunConfig.builder()
                .setMaxLlmCalls(0)
                .build();
        InvocationContext context = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("inv-010")
                .agent(mockAgent)
                .session(session)
                .userContent(Optional.empty())
                .runConfig(runConfig)
                .build();
        // Act
        RunConfig returnedRunConfig = context.runConfig();
        // Assert
        assertNotNull(returnedRunConfig);
        assertEquals(0, returnedRunConfig.maxLlmCalls(),
                "runConfig() should return the RunConfig with maxLlmCalls=0 (boundary value)");
    }
    @Test
    @Tag("boundary")
    void runConfigWithMaxLlmCallsOfOne() {
        // Arrange
        RunConfig runConfig = RunConfig.builder()
                .setMaxLlmCalls(1)
                .build();
        InvocationContext context = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("inv-011")
                .agent(mockAgent)
                .session(session)
                .userContent(Optional.empty())
                .runConfig(runConfig)
                .build();
        // Act
        RunConfig returnedRunConfig = context.runConfig();
        // Assert
        assertNotNull(returnedRunConfig);
        assertEquals(1, returnedRunConfig.maxLlmCalls(),
                "runConfig() should return the RunConfig with maxLlmCalls=1 (lower boundary value)");
    }
    @Test
    @Tag("boundary")
    void runConfigWithMaxLlmCallsOfIntegerMaxValue() {
        // Arrange
        RunConfig runConfig = RunConfig.builder()
                .setMaxLlmCalls(Integer.MAX_VALUE)
                .build();
        InvocationContext context = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("inv-012")
                .agent(mockAgent)
                .session(session)
                .userContent(Optional.empty())
                .runConfig(runConfig)
                .build();
        // Act
        RunConfig returnedRunConfig = context.runConfig();
        // Assert
        assertNotNull(returnedRunConfig);
        assertEquals(Integer.MAX_VALUE, returnedRunConfig.maxLlmCalls(),
                "runConfig() should return the RunConfig with maxLlmCalls=Integer.MAX_VALUE (upper boundary)");
    }
    @Test
    @Tag("integration")
    void runConfigIsConsistentWithIncrementLlmCallsCount() throws LlmCallsLimitExceededException {
        // Arrange
        RunConfig runConfig = RunConfig.builder()
                .setMaxLlmCalls(3)
                .build();
        InvocationContext context = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("inv-013")
                .agent(mockAgent)
                .session(session)
                .userContent(Optional.empty())
                .runConfig(runConfig)
                .build();
        // Act
        RunConfig returnedRunConfig = context.runConfig();
        // Assert: RunConfig is correctly returned
        assertNotNull(returnedRunConfig);
        assertEquals(3, returnedRunConfig.maxLlmCalls());
        // Verify incrementLlmCallsCount uses the same RunConfig (integration)
        assertDoesNotThrow(() -> context.incrementLlmCallsCount(),
                "First increment should not throw");
        assertDoesNotThrow(() -> context.incrementLlmCallsCount(),
                "Second increment should not throw");
        assertDoesNotThrow(() -> context.incrementLlmCallsCount(),
                "Third increment should not throw");
        assertThrows(LlmCallsLimitExceededException.class, () -> context.incrementLlmCallsCount(),
                "Fourth increment should throw LlmCallsLimitExceededException");
    }
    @Test
    @Tag("integration")
    void runConfigRemainsUnchangedAfterAgentAndBranchModification() {
        // Arrange
        RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(50).build();
        InvocationContext context = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("inv-014")
                .agent(mockAgent)
                .session(session)
                .userContent(Optional.empty())
                .runConfig(runConfig)
                .build();
        // Act: Modify mutable fields
        BaseAgent anotherAgent = mock(BaseAgent.class);
        context.agent(anotherAgent);
        context.branch("agent1.agent2");
        RunConfig returnedRunConfig = context.runConfig();
        // Assert: RunConfig is still the same original instance
        assertSame(runConfig, returnedRunConfig,
                "runConfig() should not be affected by changes to mutable fields like agent or branch");
        assertEquals(50, returnedRunConfig.maxLlmCalls());
    }
    @Test
    @Tag("integration")
    void runConfigEqualsVerificationBetweenTwoContextsWithSameRunConfig() {
        // Arrange
        RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(10).build();
        InvocationContext context1 = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("inv-015a")
                .agent(mockAgent)
                .session(session)
                .userContent(Optional.empty())
                .runConfig(runConfig)
                .build();
        InvocationContext context2 = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("inv-015a")
                .agent(mockAgent)
                .session(session)
                .userContent(Optional.empty())
                .runConfig(