/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=equals_271e2b6b9b
ROOST_METHOD_SIG_HASH=equals_f2d574000d

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/june-java-unit/1782282457/source/adk-java/core/src/test/java/com/google/adk/agents/InvocationContextTest.java
Tests:
    "@Test
public void testEquals_sameObject() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(context)).isTrue();
}
"
    "@Test
public void testEquals_null() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(null)).isFalse();
}
"
    "@Test
public void testEquals_sameValues() {
    InvocationContext context1 = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext context2 = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context1.equals(context2)).isTrue();

    assertThat(context2.equals(context1)).isTrue();
}
"
    "@Test
public void testEquals_differentValues() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext contextWithDiffSessionService = InvocationContext.builder().sessionService(
    mock(BaseSessionService.class)).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffInvocationId = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(
    "another-id").agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffAgent = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(
    mock(BaseAgent.class)).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithUserContentEmpty = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithLiveQueuePresent = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).liveRequestQueue(liveRequestQueue).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(contextWithDiffSessionService)).isFalse();
    assertThat(context.equals(contextWithDiffInvocationId)).isFalse();
    assertThat(context.equals(contextWithDiffAgent)).isFalse();
    assertThat(context.equals(contextWithUserContentEmpty)).isFalse();
    assertThat(context.equals(contextWithLiveQueuePresent)).isFalse();
}
"Scenario 1: Comparing Two Objects with Different endInvocation Flag Values

Details:
  TestName: equalsDifferentEndInvocationFlag
  Description: Verifies that two InvocationContext instances with identical field values except for the
               endInvocation boolean flag are not considered equal. This tests the primitive boolean
               comparison within the equals method.
Execution:
  Arrange: Create two InvocationContext instances with all identical fields, but set endInvocation=false
           for the first and endInvocation=true for the second, using the same sessionService,
           artifactService, memoryService, pluginManager, invocationId, agent, session, userContent,
           and runConfig.
  Act: Call context1.equals(context2) and context2.equals(context1).
  Assert: Assert that both comparisons return false.
Validation:
  This test confirms that the endInvocation boolean field is evaluated in the equality check.
  Since it is the first field compared after the type check, a mismatch here should immediately
  cause the method to return false. This is significant because the invocation termination state
  is a critical part of the invocation lifecycle.

*/

// ********RoostGPT********

```java
package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.mock;
import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.flows.llmflows.ResumabilityConfig;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.genai.types.Content;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.junit.jupiter.api.*;
import com.google.adk.events.Event;
import com.google.adk.models.LlmCallsLimitExceededException;
import com.google.common.collect.ImmutableSet;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import com.google.errorprone.annotations.InlineMe;
import com.google.genai.types.FunctionCall;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import javax.annotation.Nullable;

@ExtendWith(MockitoExtension.class)
public class InvocationContextEqualsTest {

	@Mock
	private BaseSessionService sessionService;

	@Mock
	private BaseArtifactService artifactService;

	@Mock
	private BaseMemoryService memoryService;

	@Mock
	private PluginManager pluginManager;

	@Mock
	private BaseAgent agent;

	@Mock
	private Session session;

	@Mock
	private Content userContent;

	@Mock
	private RunConfig runConfig;

	@Mock
	private ResumabilityConfig resumabilityConfig;

	private InvocationContext.Builder baseBuilder;

	@BeforeEach
	void setUp() {
		baseBuilder = InvocationContext.builder()
			.sessionService(sessionService)
			.artifactService(artifactService)
			.memoryService(memoryService)
			.pluginManager(pluginManager)
			.invocationId("test-invocation-id")
			.agent(agent)
			.session(session)
			.userContent(Optional.of(userContent))
			.runConfig(runConfig)
			.resumabilityConfig(resumabilityConfig)
			.endInvocation(false);
	}

	@Test
	@Tag("valid")
	void equalsReturnsTrueForSameInstance() {
		InvocationContext context = baseBuilder.build();
		assertTrue(context.equals(context));
	}

	@Test
	@Tag("valid")
	void equalsReturnsTrueForTwoIdenticalInstances() {
		InvocationContext context1 = baseBuilder.build();
		InvocationContext context2 = InvocationContext.builder()
			.sessionService(sessionService)
			.artifactService(artifactService)
			.memoryService(memoryService)
			.pluginManager(pluginManager)
			.invocationId("test-invocation-id")
			.agent(agent)
			.session(session)
			.userContent(Optional.of(userContent))
			.runConfig(runConfig)
			.resumabilityConfig(resumabilityConfig)
			.endInvocation(false)
			.build();
		assertTrue(context1.equals(context2));
		assertTrue(context2.equals(context1));
	}

	@Test
	@Tag("invalid")
	void equalsReturnsFalseForNull() {
		InvocationContext context = baseBuilder.build();
		assertFalse(context.equals(null));
	}

	@Test
	@Tag("invalid")
	void equalsReturnsFalseForDifferentObjectType() {
		InvocationContext context = baseBuilder.build();
		assertFalse(context.equals("some string"));
		assertFalse(context.equals(42));
		assertFalse(context.equals(new Object()));
	}

	@Test
	@Tag("invalid")
	void equalsDifferentEndInvocationFlag() {
		InvocationContext context1 = baseBuilder.endInvocation(false).build();
		InvocationContext context2 = InvocationContext.builder()
			.sessionService(sessionService)
			.artifactService(artifactService)
			.memoryService(memoryService)
			.pluginManager(pluginManager)
			.invocationId("test-invocation-id")
			.agent(agent)
			.session(session)
			.userContent(Optional.of(userContent))
			.runConfig(runConfig)
			.resumabilityConfig(resumabilityConfig)
			.endInvocation(true)
			.build();
		assertFalse(context1.equals(context2));
		assertFalse(context2.equals(context1));
	}

	@Test
	@Tag("invalid")
	void equalsReturnsFalseForDifferentSessionService() {
		InvocationContext context1 = baseBuilder.build();
		BaseSessionService differentSessionService = mock(BaseSessionService.class);
		InvocationContext context2 = InvocationContext.builder()
			.sessionService(differentSessionService)
			.artifactService(artifactService)
			.memoryService(memoryService)
			.pluginManager(pluginManager)
			.invocationId("test-invocation-id")
			.agent(agent)
			.session(session)
			.userContent(Optional.of(userContent))
			.runConfig(runConfig)
			.resumabilityConfig(resumabilityConfig)
			.endInvocation(false)
			.build();
		assertFalse(context1.equals(context2));
		assertFalse(context2.equals(context1));
	}

	@Test
	@Tag("invalid")
	void equalsReturnsFalseForDifferentArtifactService() {
		InvocationContext context1 = baseBuilder.build();
		BaseArtifactService differentArtifactService = mock(BaseArtifactService.class);
		InvocationContext context2 = InvocationContext.builder()
			.sessionService(sessionService)
			.artifactService(differentArtifactService)
			.memoryService(memoryService)
			.pluginManager(pluginManager)
			.invocationId("test-invocation-id")
			.agent(agent)
			.session(session)
			.userContent(Optional.of(userContent))
			.runConfig(runConfig)
			.resumabilityConfig(resumabilityConfig)
			.endInvocation(false)
			.build();
		assertFalse(context1.equals(context2));
		assertFalse(context2.equals(context1));
	}

	@Test
	@Tag("invalid")
	void equalsReturnsFalseForDifferentMemoryService() {
		InvocationContext context1 = baseBuilder.build();
		BaseMemoryService differentMemoryService = mock(BaseMemoryService.class);
		InvocationContext context2 = InvocationContext.builder()
			.sessionService(sessionService)
			.artifactService(artifactService)
			.memoryService(differentMemoryService)
			.pluginManager(pluginManager)
			.invocationId("test-invocation-id")
			.agent(agent)
			.session(session)
			.userContent(Optional.of(userContent))
			.runConfig(runConfig)
			.resumabilityConfig(resumabilityConfig)
			.endInvocation(false)
			.build();
		assertFalse(context1.equals(context2));
		assertFalse(context2.equals(context1));
	}

	@Test
	@Tag("invalid")
	void equalsReturnsFalseForDifferentPluginManager() {
		InvocationContext context1 = baseBuilder.build();
		PluginManager differentPluginManager = mock(PluginManager.class);
		InvocationContext context2 = InvocationContext.builder()
			.sessionService(sessionService)
			.artifactService(artifactService)
			.memoryService(memoryService)
			.pluginManager(differentPluginManager)
			.invocationId("test-invocation-id")
			.agent(agent)
			.session(session)
			.userContent(Optional.of(userContent))
			.runConfig(runConfig)
			.resumabilityConfig(resumabilityConfig)
			.endInvocation(false)
			.build();
		assertFalse(context1.equals(context2));
		assertFalse(context2.equals(context1));
	}

	@Test
	@Tag("invalid")
	void equalsReturnsFalseForDifferentInvocationId() {
		InvocationContext context1 = baseBuilder.invocationId("id-one").build();
		InvocationContext context2 = InvocationContext.builder()
			.sessionService(sessionService)
			.artifactService(artifactService)
			.memoryService(memoryService)
			.pluginManager(pluginManager)
			.invocationId("id-two")
			.agent(agent)
			.session(session)
			.userContent(Optional.of(userContent))
			.runConfig(runConfig)
			.resumabilityConfig(resumabilityConfig)
			.endInvocation(false)
			.build();
		assertFalse(context1.equals(context2));
		assertFalse(context2.equals(context1));
	}

	@Test
	@Tag("invalid")
	void equalsReturnsFalseForDifferentAgent() {
		InvocationContext context1 = baseBuilder.build();
		BaseAgent differentAgent = mock(BaseAgent.class);
		InvocationContext context2 = InvocationContext.builder()
			.sessionService(sessionService)
			.artifactService(artifactService)
			.memoryService(memoryService)
			.pluginManager(pluginManager)
			.invocationId("test-invocation-id")
			.agent(differentAgent)
			.session(session)
			.userContent(Optional.of(userContent))
			.runConfig(runConfig)
			.resumabilityConfig(resumabilityConfig)
			.endInvocation(false)
			.build();
		assertFalse(context1.equals(context2));
		assertFalse(context2.equals(context1));
	}

	@Test
	@Tag("invalid")
	void equalsReturnsFalseForDifferentSession() {
		InvocationContext context1 = baseBuilder.build();
		Session differentSession = mock(Session.class);
		InvocationContext context2 = InvocationContext.builder()
			.sessionService(sessionService)
			.artifactService(artifactService)
			.memoryService(memoryService)
			.pluginManager(pluginManager)
			.invocationId("test-invocation-id")
			.agent(agent)
			.session(differentSession)
			.userContent(Optional.of(userContent))
			.runConfig(runConfig)
			.resumabilityConfig(resumabilityConfig)
			.endInvocation(false)
			.build();
		assertFalse(context1.equals(context2));
		assertFalse(context2.equals(context1));
	}

	@Test
	@Tag("invalid")
	void equalsReturnsFalseForDifferentUserContent() {
		InvocationContext context1 = baseBuilder.build();
		Content differentUserContent = mock(Content.class);
		InvocationContext context2 = InvocationContext.builder()
			.sessionService(sessionService)
			.artifactService(artifactService)
			.memoryService(memoryService)
			.pluginManager(pluginManager)
			.invocationId("test-invocation-id")
			.agent(agent)
			.session(session)
			.userContent(Optional.of(differentUserContent))
			.runConfig(runConfig)
			.resumabilityConfig(resumabilityConfig)
			.endInvocation(false)
			.build();
		assertFalse(context1.equals(context2));
		assertFalse(context2.equals(context1));
	}

	@Test
	@Tag("invalid")
	void equalsReturnsFalseForDifferentRunConfig() {
		InvocationContext context1 = baseBuilder.build();
		RunConfig differentRunConfig = mock(RunConfig.class);
		InvocationContext context2 = InvocationContext.builder()
			.sessionService(sessionService)
			.artifactService(artifactService)
			.memoryService(memoryService)
			.pluginManager(pluginManager)
			.invocationId("test-invocation-id")
			.agent(agent)
			.session(session)
			.userContent(Optional.of(userContent))
			.runConfig(differentRunConfig)
			.resumabilityConfig(resumabilityConfig)
			.endInvocation(false)
			.build();
		assertFalse(context1.equals(context2));
		assertFalse(context2.equals(context1));
	}

	@Test
	@Tag("invalid")
	void equalsReturnsFalseForDifferentResumabilityConfig() {
		InvocationContext context1 = baseBuilder.build();
		ResumabilityConfig differentResumabilityConfig = mock(ResumabilityConfig.class);
		InvocationContext context2 = InvocationContext.builder()
			.sessionService(sessionService)
			.artifactService(artifactService)
			.memoryService(memoryService)
			.pluginManager(pluginManager)
			.invocationId("test-invocation-id")
			.agent(agent)
			.session(session)
			.userContent(Optional.of(userContent))
			.runConfig(runConfig)
			.resumabilityConfig(differentResumabilityConfig)
			.endInvocation(false)
			.build();
		assertFalse(context1.equals(context2));
		assertFalse(context2.equals(context1));
	}

	@Test
	@Tag("valid")
	void equalsReturnsTrueWhenAllNullableFieldsAreNull() {
		InvocationContext context1 = InvocationContext.builder()
			.sessionService(null)
			.artifactService(null)
			.memoryService(null)
			.pluginManager(null)
			.invocationId(null)
			.agent(null)
			.session(null)
			.userContent(Optional.empty())
			.runConfig(null)
			.resumabilityConfig(null)
			.endInvocation(false)
			.build();
		InvocationContext context2 = InvocationContext.builder()
			.sessionService(null)
			.artifactService(null)
			.memoryService(null)
			.pluginManager(null)
			.invocationId(null)
			.agent(null)
			.session(null)
			.userContent(Optional.empty())
			.runConfig(null)
			.resumabilityConfig(null)
			.endInvocation(false)
			.build();
		assertTrue(context1.equals(context2));
		assertTrue(context2.equals(context1));
	}

	@Test
    @Tag("boundary")
    void equalsReturnsFalseWhenOneSessionServiceIsNullAndOtherIsNot() {
        InvocationContext context1 = InvocationContext.builder()
                .sessionService(null)
                .artifactService(artifactService)
                .memoryService(memoryService)
                .pluginManager(pluginManager)
                .invocationId("test-invocation-id")
                .agent(agent)
                .session(session)
                .userContent(Optional.of(userContent))
                .runConfig(runConfig)
                .resumabilityConfig(resumabilityConfig)
                .endInvocation(false)
                .build();
        InvocationContext context2 = baseBuilder.build();
        assertFalse(context1.equals(context2));
        assertFalse(context2.equals(context1));
    }

@Test
    @Tag("boundary")
    void equalsReturnsFalseWhenUserContentPresentVsEmpty() {
        InvocationContext context1 = baseBuilder.userContent(Optional.of(