/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=activeStreamingTools_c4cc5030aa
ROOST_METHOD_SIG_HASH=activeStreamingTools_398f84db97

Scenario 1: Verify activeStreamingTools Returns an Empty Map on Fresh InvocationContext

Details:
  TestName: activeStreamingToolsReturnsEmptyMapOnFreshContext
  Description: Verify that when a new InvocationContext is created using the builder without adding any streaming tools, the activeStreamingTools() method returns an empty (non-null) map. This checks the default initialization state of the internal ConcurrentHashMap.

Execution:
  Arrange:
    - Create a mock or stub for BaseSessionService, BaseArtifactService, and Session.
    - Build an InvocationContext using InvocationContext.builder() providing the minimum required fields (sessionService, artifactService, session).
  Act:
    - Call invocationContext.activeStreamingTools().
  Assert:
    - Assert that the returned map is not null.
    - Assert that the returned map is empty (size == 0).

Validation:
  The test confirms that the internal ConcurrentHashMap is properly initialized to an empty state on object construction. This is critical to ensure no stale or default data leaks into a fresh invocation context, maintaining data isolation between invocations.

*/

// ********RoostGPT********

```java
package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.events.Event;
import com.google.adk.flows.llmflows.ResumabilityConfig;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.models.LlmCallsLimitExceededException;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import com.google.genai.types.Content;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import javax.annotation.Nullable;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.junit.jupiter.api.*;
import com.google.common.collect.ImmutableSet;
import com.google.errorprone.annotations.InlineMe;
import com.google.genai.types.FunctionCall;

@ExtendWith(MockitoExtension.class)
public class InvocationContextActiveStreamingToolsTest {

	@Mock
	private BaseSessionService mockSessionService;

	@Mock
	private BaseArtifactService mockArtifactService;

	@Mock
	private BaseMemoryService mockMemoryService;

	@Mock
	private PluginManager mockPluginManager;

	@Mock
	private Session mockSession;

	@Mock
	private BaseAgent mockAgent;

	@Mock
	private RunConfig mockRunConfig;

	@Mock
	private ActiveStreamingTool mockActiveStreamingTool;

	@BeforeEach
    void setUp() {
        when(mockSession.appName()).thenReturn("testApp");
        when(mockSession.userId()).thenReturn("testUser");
        when(mockSession.id()).thenReturn("testSession");
    }

	private InvocationContext buildMinimalInvocationContext() {
		return InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("test-invocation-id")
			.runConfig(mockRunConfig)
			.build();
	}

	@Test
	@Tag("valid")
	void activeStreamingToolsReturnsEmptyMapOnFreshContext() {
		// Arrange
		InvocationContext invocationContext = buildMinimalInvocationContext();
		// Act
		Map<String, ActiveStreamingTool> result = invocationContext.activeStreamingTools();
		// Assert
		assertNotNull(result, "activeStreamingTools map should not be null");
		assertTrue(result.isEmpty(), "activeStreamingTools map should be empty on fresh context");
		assertEquals(0, result.size(), "activeStreamingTools map size should be 0 on fresh context");
	}

	@Test
	@Tag("valid")
	void activeStreamingToolsReturnsSameMapInstanceAcrossCalls() {
		// Arrange
		InvocationContext invocationContext = buildMinimalInvocationContext();
		// Act
		Map<String, ActiveStreamingTool> firstCall = invocationContext.activeStreamingTools();
		Map<String, ActiveStreamingTool> secondCall = invocationContext.activeStreamingTools();
		// Assert
		assertNotNull(firstCall, "First call should not be null");
		assertNotNull(secondCall, "Second call should not be null");
		assertSame(firstCall, secondCall, "Both calls should return the same map instance");
	}

	@Test
	@Tag("valid")
	void activeStreamingToolsReturnsNonNullMap() {
		// Arrange
		InvocationContext invocationContext = buildMinimalInvocationContext();
		// Act
		Map<String, ActiveStreamingTool> result = invocationContext.activeStreamingTools();
		// Assert
		assertNotNull(result, "activeStreamingTools should never return null");
	}

	@Test
	@Tag("valid")
	void activeStreamingToolsReflectsAddedToolsAfterPuttingInMap() {
		// Arrange
		InvocationContext invocationContext = buildMinimalInvocationContext();
		String toolId = "tool-123";
		// Act
		invocationContext.activeStreamingTools().put(toolId, mockActiveStreamingTool);
		Map<String, ActiveStreamingTool> result = invocationContext.activeStreamingTools();
		// Assert
		assertNotNull(result, "Map should not be null");
		assertFalse(result.isEmpty(), "Map should not be empty after adding a tool");
		assertEquals(1, result.size(), "Map should have exactly one entry");
		assertTrue(result.containsKey(toolId), "Map should contain the added tool key");
		assertEquals(mockActiveStreamingTool, result.get(toolId), "Map should return the correct tool for the key");
	}

	@Test
	@Tag("valid")
	void activeStreamingToolsSupportsMultipleToolsAddedToMap() {
		// Arrange
		InvocationContext invocationContext = buildMinimalInvocationContext();
		ActiveStreamingTool mockTool1 = mock(ActiveStreamingTool.class);
		ActiveStreamingTool mockTool2 = mock(ActiveStreamingTool.class);
		ActiveStreamingTool mockTool3 = mock(ActiveStreamingTool.class);
		// Act
		invocationContext.activeStreamingTools().put("tool-1", mockTool1);
		invocationContext.activeStreamingTools().put("tool-2", mockTool2);
		invocationContext.activeStreamingTools().put("tool-3", mockTool3);
		Map<String, ActiveStreamingTool> result = invocationContext.activeStreamingTools();
		// Assert
		assertNotNull(result, "Map should not be null");
		assertEquals(3, result.size(), "Map should contain exactly 3 tools");
		assertTrue(result.containsKey("tool-1"), "Map should contain tool-1");
		assertTrue(result.containsKey("tool-2"), "Map should contain tool-2");
		assertTrue(result.containsKey("tool-3"), "Map should contain tool-3");
		assertEquals(mockTool1, result.get("tool-1"), "Map should return the correct tool for tool-1");
		assertEquals(mockTool2, result.get("tool-2"), "Map should return the correct tool for tool-2");
		assertEquals(mockTool3, result.get("tool-3"), "Map should return the correct tool for tool-3");
	}

	@Test
	@Tag("valid")
	void activeStreamingToolsReflectsRemovalOfTool() {
		// Arrange
		InvocationContext invocationContext = buildMinimalInvocationContext();
		String toolId = "tool-to-remove";
		invocationContext.activeStreamingTools().put(toolId, mockActiveStreamingTool);
		// Act
		invocationContext.activeStreamingTools().remove(toolId);
		Map<String, ActiveStreamingTool> result = invocationContext.activeStreamingTools();
		// Assert
		assertNotNull(result, "Map should not be null after removal");
		assertTrue(result.isEmpty(), "Map should be empty after removing the only tool");
		assertFalse(result.containsKey(toolId), "Map should not contain the removed tool key");
	}

	@Test
	@Tag("valid")
	void activeStreamingToolsReturnsMutableMap() {
		// Arrange
		InvocationContext invocationContext = buildMinimalInvocationContext();
		// Act & Assert - verify the map is mutable by putting and removing entries
		Map<String, ActiveStreamingTool> result = invocationContext.activeStreamingTools();
		assertNotNull(result, "Map should not be null");
		assertDoesNotThrow(() -> result.put("test-key", mockActiveStreamingTool),
				"Should be able to put entries into the map");
		assertDoesNotThrow(() -> result.remove("test-key"), "Should be able to remove entries from the map");
	}

	@Test
	@Tag("integration")
	void activeStreamingToolsIsPreservedInCopyOf() {
		// Arrange
		InvocationContext original = buildMinimalInvocationContext();
		String toolId = "tool-original";
		original.activeStreamingTools().put(toolId, mockActiveStreamingTool);
		// Act
		InvocationContext copy = InvocationContext.copyOf(original);
		Map<String, ActiveStreamingTool> copiedTools = copy.activeStreamingTools();
		// Assert
		assertNotNull(copiedTools, "Copied map should not be null");
		assertFalse(copiedTools.isEmpty(), "Copied map should not be empty");
		assertEquals(1, copiedTools.size(), "Copied map should have 1 entry");
		assertTrue(copiedTools.containsKey(toolId), "Copied map should contain the original tool key");
		assertEquals(mockActiveStreamingTool, copiedTools.get(toolId), "Copied map should have the same tool instance");
	}

	@Test
	@Tag("integration")
	void activeStreamingToolsModificationOnCopyDoesNotAffectOriginal() {
		// Arrange
		InvocationContext original = buildMinimalInvocationContext();
		String originalToolId = "original-tool";
		original.activeStreamingTools().put(originalToolId, mockActiveStreamingTool);
		InvocationContext copy = InvocationContext.copyOf(original);
		// Act - modify the copy's map
		ActiveStreamingTool newTool = mock(ActiveStreamingTool.class);
		copy.activeStreamingTools().put("new-tool-in-copy", newTool);
		copy.activeStreamingTools().remove(originalToolId);
		// Assert - original should still have its original tool
		Map<String, ActiveStreamingTool> originalTools = original.activeStreamingTools();
		assertNotNull(originalTools, "Original map should not be null");
		assertEquals(1, originalTools.size(), "Original map should still have 1 entry");
		assertTrue(originalTools.containsKey(originalToolId), "Original map should still contain the original tool");
	}

	@Test
	@Tag("integration")
	void activeStreamingToolsIsEmptyOnFreshContextCreatedWithCreateMethod() {
		// Arrange
		Content userContent = mock(Content.class);
		InvocationContext ctx = InvocationContext.create(mockSessionService, mockArtifactService, "invocation-id-1",
				mockAgent, mockSession, userContent, mockRunConfig);
		// Act
		Map<String, ActiveStreamingTool> result = ctx.activeStreamingTools();
		// Assert
		assertNotNull(result, "activeStreamingTools map should not be null");
		assertTrue(result.isEmpty(), "activeStreamingTools map should be empty for freshly created context");
	}

	@Test
	@Tag("boundary")
	void activeStreamingToolsCanHandleNullValueForKey() {
		// Arrange
		InvocationContext invocationContext = buildMinimalInvocationContext();
		String toolId = "null-value-tool";
		// Act
		Map<String, ActiveStreamingTool> map = invocationContext.activeStreamingTools();
		// Assert - ConcurrentHashMap does not allow null values, verify behavior
		assertNotNull(map, "Map should not be null");
		assertThrows(NullPointerException.class, () -> map.put(toolId, null),
				"ConcurrentHashMap should throw NullPointerException for null values");
	}

	@Test
	@Tag("boundary")
	void activeStreamingToolsCanHandleEmptyStringKey() {
		// Arrange
		InvocationContext invocationContext = buildMinimalInvocationContext();
		String emptyKey = "";
		// Act
		invocationContext.activeStreamingTools().put(emptyKey, mockActiveStreamingTool);
		Map<String, ActiveStreamingTool> result = invocationContext.activeStreamingTools();
		// Assert
		assertNotNull(result, "Map should not be null");
		assertEquals(1, result.size(), "Map should have 1 entry with empty string key");
		assertTrue(result.containsKey(emptyKey), "Map should contain the empty string key");
		assertEquals(mockActiveStreamingTool, result.get(emptyKey),
				"Map should return the correct tool for the empty string key");
	}

	@Test
	@Tag("boundary")
	void activeStreamingToolsCanHandleVeryLongKeyString() {
		// Arrange
		InvocationContext invocationContext = buildMinimalInvocationContext();
		String longKey = "a".repeat(10000);
		// Act
		invocationContext.activeStreamingTools().put(longKey, mockActiveStreamingTool);
		Map<String, ActiveStreamingTool> result = invocationContext.activeStreamingTools();
		// Assert
		assertNotNull(result, "Map should not be null");
		assertEquals(1, result.size(), "Map should have 1 entry with long key");
		assertTrue(result.containsKey(longKey), "Map should contain the long key");
		assertEquals(mockActiveStreamingTool, result.get(longKey),
				"Map should return the correct tool for the long key");
	}

	@Test
	@Tag("boundary")
	void activeStreamingToolsClearingMapResultsInEmptyState() {
		// Arrange
		InvocationContext invocationContext = buildMinimalInvocationContext();
		invocationContext.activeStreamingTools().put("tool-a", mock(ActiveStreamingTool.class));
		invocationContext.activeStreamingTools().put("tool-b", mock(ActiveStreamingTool.class));
		invocationContext.activeStreamingTools().put("tool-c", mock(ActiveStreamingTool.class));
		assertEquals(3, invocationContext.activeStreamingTools().size(), "Map should have 3 entries before clear");
		// Act
		invocationContext.activeStreamingTools().clear();
		Map<String, ActiveStreamingTool> result = invocationContext.activeStreamingTools();
		// Assert
		assertNotNull(result, "Map should not be null after clear");
		assertTrue(result.isEmpty(), "Map should be empty after clear");
		assertEquals(0, result.size(), "Map size should be 0 after clear");
	}

	@Test
    @Tag("valid")
    void activeStreamingToolsReturnedMapContainsSameReferenceAfterUpdate() {
        // Arrange
        InvocationContext invocationContext = buildMinimalInvocationContext();
        Map<String, ActiveStreamingTool> mapBeforeUpdate = invocationContext.activeStreamingTools();
        // Act
        invocationContext.activeStreamingTools().put("tool-new", mockActiveStreamingTool);
        Map<String, ActiveStreamingTool> mapAfterUpdate = invocationContext.activeStreamingTools();
        // Assert
        assertSame(mapBeforeUpdate, mapAfterUpdate,
                "The map reference should be the same before and after update");
        assertTrue(mapAfterUpdate.containsKey("tool-new"),
                "Updated map should contain the newly added key");
    }

@Test
    @Tag("valid")
    void activeStreamingToolsWithBuilderIncludingAllOptionalFields() {
        // Arrange
        ResumabilityConfig resumabilityConfig = mock(ResumabilityConfig.class);
        InvocationContext invocationContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .memoryService(mockMemoryService)
                .pluginManager(mockPluginManager)
                .agent(mockAgent)
                .session(mockSession)
                .invocationId("full-builder-invocation-id")
                .runConfig(mockRunConfig)
                .branch("agentA.agentB")
                .resumabilityConfig(resumabilityConfig)
                .build();
        // Act