/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=hashCode_c3a2d500cd
ROOST_METHOD_SIG_HASH=hashCode_5a2657087a

Scenario 1: Hash Code Consistency for the Same Object Instance

Details:
  TestName: hashCodeIsConsistentForSameInstance
  Description: Verifies that calling hashCode() multiple times on the same InvocationContext instance
               returns the same integer value each time, satisfying the Java hashCode contract
               of consistency within a single execution.

Execution:
  Arrange:
    - Create a mock BaseSessionService (mockSessionService).
    - Create a mock BaseArtifactService (mockArtifactService).
    - Create a mock Session (mockSession).
    - Build an InvocationContext using InvocationContext.builder()
        .sessionService(mockSessionService)
        .artifactService(mockArtifactService)
        .session(mockSession)
        .build().
  Act:
    - Call context.hashCode() and store result as firstHash.
    - Call context.hashCode() again and store result as secondHash.
    - Call context.hashCode() a third time and store result as thirdHash.
  Assert:
    - assertEquals(firstHash, secondHash)
    - assertEquals(secondHash, thirdHash)

Validation:
  This test ensures the fundamental Java hashCode contract: "whenever hashCode is invoked on the same
  object more than once during an execution, it must consistently return the same integer." This is
  critical for the correct behavior of hash-based collections like HashMap and HashSet where
  InvocationContext instances may be used as keys.

*/

// ********RoostGPT********

```java
package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.events.Event;
import com.google.adk.flows.llmflows.ResumabilityConfig;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.models.LlmCallsLimitExceededException;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.genai.types.Content;
import java.util.Objects;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.junit.jupiter.api.*;
import com.google.common.collect.ImmutableSet;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import com.google.errorprone.annotations.InlineMe;
import com.google.genai.types.FunctionCall;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import javax.annotation.Nullable;

@ExtendWith(MockitoExtension.class)
public class InvocationContextHashCodeTest {

	@Mock
	private BaseSessionService mockSessionService;

	@Mock
	private BaseArtifactService mockArtifactService;

	@Mock
	private BaseMemoryService mockMemoryService;

	@Mock
	private PluginManager mockPluginManager;

	@Mock
	private Session mockSession;

	@Mock
	private BaseAgent mockAgent;

	@Mock
	private RunConfig mockRunConfig;

	@Mock
	private ResumabilityConfig mockResumabilityConfig;

	@Mock
	private Content mockContent;

	@BeforeEach
	void setUp() {
		lenient().when(mockSession.appName()).thenReturn("testApp");
		lenient().when(mockSession.userId()).thenReturn("testUser");
	}

	// -------------------------------------------------------------------------
	// Scenario 1: Hash Code Consistency for the Same Object Instance
	// -------------------------------------------------------------------------
	@Test
	@Tag("valid")
	void hashCodeIsConsistentForSameInstance() {
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.session(mockSession)
			.build();
		int firstHash = context.hashCode();
		int secondHash = context.hashCode();
		int thirdHash = context.hashCode();
		assertEquals(firstHash, secondHash);
		assertEquals(secondHash, thirdHash);
	}

	// -------------------------------------------------------------------------
	// Hash Code Equality: Two equal objects must have the same hash code
	// -------------------------------------------------------------------------
	@Test
	@Tag("valid")
	void hashCodeEqualForTwoEqualContexts() {
		String invocationId = "inv-001";
		InvocationContext context1 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.pluginManager(mockPluginManager)
			.invocationId(invocationId)
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.of(mockContent))
			.runConfig(mockRunConfig)
			.endInvocation(false)
			.build();
		InvocationContext context2 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.pluginManager(mockPluginManager)
			.invocationId(invocationId)
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.of(mockContent))
			.runConfig(mockRunConfig)
			.endInvocation(false)
			.build();
		assertEquals(context1, context2, "Two contexts with same fields should be equal");
		assertEquals(context1.hashCode(), context2.hashCode(), "Equal objects must have the same hashCode");
	}

	// -------------------------------------------------------------------------
	// Hash Code Difference: Different invocationId should likely differ
	// -------------------------------------------------------------------------
	@Test
	@Tag("valid")
	void hashCodeDiffersForDifferentInvocationIds() {
		InvocationContext context1 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.session(mockSession)
			.invocationId("inv-AAA")
			.build();
		InvocationContext context2 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.session(mockSession)
			.invocationId("inv-BBB")
			.build();
		// Not strictly guaranteed, but highly likely for distinct strings
		assertNotEquals(context1.hashCode(), context2.hashCode(),
				"Different invocationIds should produce different hashCodes");
	}

	// -------------------------------------------------------------------------
	// Hash Code with All Null Optional / Null Fields
	// -------------------------------------------------------------------------
	@Test
	@Tag("boundary")
	void hashCodeWithAllNullFieldsDoesNotThrow() {
		InvocationContext context = InvocationContext.builder().build();
		assertDoesNotThrow(context::hashCode, "hashCode() must not throw when fields are null");
	}

	@Test
	@Tag("boundary")
	void hashCodeIsConsistentWithAllNullFields() {
		InvocationContext context = InvocationContext.builder().build();
		int first = context.hashCode();
		int second = context.hashCode();
		assertEquals(first, second, "hashCode() must be consistent even when all fields are null");
	}

	// -------------------------------------------------------------------------
	// Hash Code with Only Session Set
	// -------------------------------------------------------------------------
	@Test
	@Tag("valid")
	void hashCodeConsistentWithOnlySessionSet() {
		InvocationContext context = InvocationContext.builder().session(mockSession).build();
		int first = context.hashCode();
		int second = context.hashCode();
		assertEquals(first, second);
	}

	// -------------------------------------------------------------------------
	// Hash Code changes when endInvocation flag differs
	// -------------------------------------------------------------------------
	@Test
	@Tag("valid")
	void hashCodeDiffersWhenEndInvocationDiffers() {
		InvocationContext contextFalse = InvocationContext.builder()
			.sessionService(mockSessionService)
			.session(mockSession)
			.invocationId("inv-001")
			.endInvocation(false)
			.build();
		InvocationContext contextTrue = InvocationContext.builder()
			.sessionService(mockSessionService)
			.session(mockSession)
			.invocationId("inv-001")
			.endInvocation(true)
			.build();
		assertNotEquals(contextFalse.hashCode(), contextTrue.hashCode(),
				"Different endInvocation values should produce different hashCodes");
	}

	// -------------------------------------------------------------------------
	// Hash Code changes when branch differs
	// -------------------------------------------------------------------------
	@Test
	@Tag("valid")
	void hashCodeDiffersWhenBranchDiffers() {
		InvocationContext contextNoBranch = InvocationContext.builder()
			.sessionService(mockSessionService)
			.session(mockSession)
			.invocationId("inv-001")
			.build();
		InvocationContext contextWithBranch = InvocationContext.builder()
			.sessionService(mockSessionService)
			.session(mockSession)
			.invocationId("inv-001")
			.branch("agentA.agentB")
			.build();
		assertNotEquals(contextNoBranch.hashCode(), contextWithBranch.hashCode(),
				"Different branch values should produce different hashCodes");
	}

	// -------------------------------------------------------------------------
	// Hash Code changes when agent differs
	// -------------------------------------------------------------------------
	@Test
	@Tag("valid")
	void hashCodeDiffersWhenAgentDiffers() {
		BaseAgent anotherAgent = mock(BaseAgent.class);
		InvocationContext context1 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.session(mockSession)
			.invocationId("inv-001")
			.agent(mockAgent)
			.build();
		InvocationContext context2 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.session(mockSession)
			.invocationId("inv-001")
			.agent(anotherAgent)
			.build();
		assertNotEquals(context1.hashCode(), context2.hashCode(),
				"Different agent instances should produce different hashCodes");
	}

	// -------------------------------------------------------------------------
	// Hash Code changes when session differs
	// -------------------------------------------------------------------------
	@Test
	@Tag("valid")
	void hashCodeDiffersWhenSessionDiffers() {
		Session anotherSession = mock(Session.class);
		InvocationContext context1 = InvocationContext.builder().session(mockSession).invocationId("inv-001").build();
		InvocationContext context2 = InvocationContext.builder()
			.session(anotherSession)
			.invocationId("inv-001")
			.build();
		assertNotEquals(context1.hashCode(), context2.hashCode(),
				"Different session instances should produce different hashCodes");
	}

	// -------------------------------------------------------------------------
	// Hash Code changes when memoryService differs
	// -------------------------------------------------------------------------
	@Test
	@Tag("valid")
	void hashCodeDiffersWhenMemoryServiceDiffers() {
		BaseMemoryService anotherMemoryService = mock(BaseMemoryService.class);
		InvocationContext context1 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.memoryService(mockMemoryService)
			.session(mockSession)
			.invocationId("inv-001")
			.build();
		InvocationContext context2 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.memoryService(anotherMemoryService)
			.session(mockSession)
			.invocationId("inv-001")
			.build();
		assertNotEquals(context1.hashCode(), context2.hashCode(),
				"Different memoryService instances should produce different hashCodes");
	}

	// -------------------------------------------------------------------------
	// Hash Code changes when pluginManager differs
	// -------------------------------------------------------------------------
	@Test
	@Tag("valid")
	void hashCodeDiffersWhenPluginManagerDiffers() {
		PluginManager anotherPluginManager = mock(PluginManager.class);
		InvocationContext context1 = InvocationContext.builder()
			.session(mockSession)
			.invocationId("inv-001")
			.pluginManager(mockPluginManager)
			.build();
		InvocationContext context2 = InvocationContext.builder()
			.session(mockSession)
			.invocationId("inv-001")
			.pluginManager(anotherPluginManager)
			.build();
		assertNotEquals(context1.hashCode(), context2.hashCode(),
				"Different pluginManager instances should produce different hashCodes");
	}

	// -------------------------------------------------------------------------
	// Hash Code changes when userContent differs
	// -------------------------------------------------------------------------
	@Test
	@Tag("valid")
	void hashCodeDiffersWhenUserContentDiffers() {
		Content anotherContent = mock(Content.class);
		InvocationContext context1 = InvocationContext.builder()
			.session(mockSession)
			.invocationId("inv-001")
			.userContent(Optional.of(mockContent))
			.build();
		InvocationContext context2 = InvocationContext.builder()
			.session(mockSession)
			.invocationId("inv-001")
			.userContent(Optional.of(anotherContent))
			.build();
		assertNotEquals(context1.hashCode(), context2.hashCode(),
				"Different userContent values should produce different hashCodes");
	}

	// -------------------------------------------------------------------------
	// Hash Code changes when runConfig differs
	// -------------------------------------------------------------------------
	@Test
	@Tag("valid")
	void hashCodeDiffersWhenRunConfigDiffers() {
		RunConfig anotherRunConfig = mock(RunConfig.class);
		InvocationContext context1 = InvocationContext.builder()
			.session(mockSession)
			.invocationId("inv-001")
			.runConfig(mockRunConfig)
			.build();
		InvocationContext context2 = InvocationContext.builder()
			.session(mockSession)
			.invocationId("inv-001")
			.runConfig(anotherRunConfig)
			.build();
		assertNotEquals(context1.hashCode(), context2.hashCode(),
				"Different runConfig instances should produce different hashCodes");
	}

	// -------------------------------------------------------------------------
	// Hash Code with liveRequestQueue set vs not set
	// -------------------------------------------------------------------------
	@Test
	@Tag("valid")
	void hashCodeDiffersWhenLiveRequestQueueDiffers() {
		LiveRequestQueue liveRequestQueue = new LiveRequestQueue();
		InvocationContext contextWithQueue = InvocationContext.builder()
			.session(mockSession)
			.invocationId("inv-001")
			.liveRequestQueue(Optional.of(liveRequestQueue))
			.build();
		InvocationContext contextWithoutQueue = InvocationContext.builder()
			.session(mockSession)
			.invocationId("inv-001")
			.liveRequestQueue(Optional.empty())
			.build();
		assertNotEquals(contextWithQueue.hashCode(), contextWithoutQueue.hashCode(),
				"Different liveRequestQueue values should produce different hashCodes");
	}

	// -------------------------------------------------------------------------
	// Hash Code with resumabilityConfig set vs not set
	// -------------------------------------------------------------------------
	@Test
	@Tag("valid")
	void hashCodeDiffersWhenResumabilityConfigDiffers() {
		ResumabilityConfig anotherConfig = mock(ResumabilityConfig.class);
		InvocationContext context1 = InvocationContext.builder()
			.session(mockSession)
			.invocationId("inv-001")
			.resumabilityConfig(mockResumabilityConfig)
			.build();
		InvocationContext context2 = InvocationContext.builder()
			.session(mockSession)
			.invocationId("inv-001")
			.resumabilityConfig(anotherConfig)
			.build();
		assertNotEquals(context1.hashCode(), context2.hashCode(),
				"Different resumabilityConfig instances should produce different hashCodes");
	}

	// -------------------------------------------------------------------------
	// Hash Code returns an int (not zero, for typical non-null inputs)
	// -------------------------------------------------------------------------
	@Test
    @Tag("valid")
    void hashCodeReturnsNonZeroForTypicalContext() {
        InvocationContext context = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .memoryService(mockMemoryService)
                .pluginManager(mockPluginManager)
                .invocationId("inv-unique-123")
                .agent(mockAgent)
                .session(mockSession)
                .userContent(Optional.of(mockContent))
                .runConfig(mockRunConfig)
                .endInvocation(false)
                .build();
        // hashCode() should return a valid integer (not necessarily non-zero, but
        // we verify it does not throw and returns a deterministic value)
        assertDoesNotThrow(context::hashCode);
        int hash = context.hashCode();
        assertEquals(hash, context.hashCode(), "hashCode must be deterministic");
    }

// -------------------------------------------------------------------------
// Hash Code matches Objects.hash computation
// -------------------------------------------------------------------------
@Test
    @Tag("valid")
    void hashCodeMatchesExpectedObjectsHashComputation() {
        String invocationId = "inv-match-test";
        InvocationContext context = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtif