/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=isResumable_2397941e46
ROOST_METHOD_SIG_HASH=isResumable_6fb85ad5c9

Scenario 1: Verify isResumable() Returns True When ResumabilityConfig Is Configured as Resumable

Details:
  TestName: isResumableReturnsTrueWhenResumabilityConfigIsResumable
  Description: Verifies that the isResumable() method returns true when the ResumabilityConfig
               instance injected into the InvocationContext is configured to indicate a resumable state.
               This tests the direct delegation behavior from InvocationContext to ResumabilityConfig.

Execution:
  Arrange:
    - Create a mock of ResumabilityConfig using Mockito.
    - Stub the mock so that resumabilityConfig.isResumable() returns true.
    - Build an InvocationContext using InvocationContext.builder()
      with all required fields (sessionService, artifactService, session, agent)
      and set the resumabilityConfig to the mocked instance via .resumabilityConfig(mockResumabilityConfig).
    - Call .build() to instantiate the InvocationContext.
  Act:
    - Call invocationContext.isResumable().
  Assert:
    - Use assertTrue(invocationContext.isResumable()) to confirm the result is true.

Validation:
  The assertion confirms that isResumable() faithfully delegates to and returns the value from
  ResumabilityConfig.isResumable() when it returns true. This is critical to ensure the
  InvocationContext correctly reflects the resumability state as configured, allowing downstream
  logic (e.g., shouldPauseInvocation) to make correct decisions based on resumability.

*/

// ********RoostGPT********

```java
package com.google.adk.agents;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.events.Event;
import com.google.adk.flows.llmflows.ResumabilityConfig;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.models.LlmCallsLimitExceededException;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.common.collect.ImmutableSet;
import com.google.genai.types.Content;
import com.google.genai.types.FunctionCall;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import javax.annotation.Nullable;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.junit.jupiter.api.*;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import com.google.errorprone.annotations.InlineMe;

@ExtendWith(MockitoExtension.class)
public class InvocationContextIsResumableTest {
    @Mock
    private BaseSessionService mockSessionService;
    @Mock
    private BaseArtifactService mockArtifactService;
    @Mock
    private BaseMemoryService mockMemoryService;
    @Mock
    private PluginManager mockPluginManager;
    @Mock
    private BaseAgent mockAgent;
    @Mock
    private ResumabilityConfig mockResumabilityConfig;
    private Session mockSession;
    @BeforeEach
    void setUp() {
        mockSession = Session.builder("test-session-id")
                .appName("test-app")
                .userId("test-user")
                .build();
    }
    @Test
    @Tag("valid")
    void isResumableReturnsTrueWhenResumabilityConfigIsResumable() {
        when(mockResumabilityConfig.isResumable()).thenReturn(true);
        InvocationContext invocationContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("test-invocation-id")
                .agent(mockAgent)
                .session(mockSession)
                .userContent(Optional.empty())
                .resumabilityConfig(mockResumabilityConfig)
                .build();
        assertTrue(invocationContext.isResumable());
    }
    @Test
    @Tag("valid")
    void isResumableReturnsFalseWhenResumabilityConfigIsNotResumable() {
        when(mockResumabilityConfig.isResumable()).thenReturn(false);
        InvocationContext invocationContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("test-invocation-id")
                .agent(mockAgent)
                .session(mockSession)
                .userContent(Optional.empty())
                .resumabilityConfig(mockResumabilityConfig)
                .build();
        assertFalse(invocationContext.isResumable());
    }
    @Test
    @Tag("valid")
    void isResumableDelegatesToResumabilityConfigIsResumable() {
        when(mockResumabilityConfig.isResumable()).thenReturn(true);
        InvocationContext invocationContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("test-invocation-id")
                .agent(mockAgent)
                .session(mockSession)
                .userContent(Optional.empty())
                .resumabilityConfig(mockResumabilityConfig)
                .build();
        invocationContext.isResumable();
        verify(mockResumabilityConfig, times(1)).isResumable();
    }
    @Test
    @Tag("valid")
    void isResumableReturnsTrueConsistentlyForMultipleCalls() {
        when(mockResumabilityConfig.isResumable()).thenReturn(true);
        InvocationContext invocationContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("test-invocation-id")
                .agent(mockAgent)
                .session(mockSession)
                .userContent(Optional.empty())
                .resumabilityConfig(mockResumabilityConfig)
                .build();
        assertTrue(invocationContext.isResumable());
        assertTrue(invocationContext.isResumable());
        assertTrue(invocationContext.isResumable());
        verify(mockResumabilityConfig, times(3)).isResumable();
    }
    @Test
    @Tag("valid")
    void isResumableReturnsFalseConsistentlyForMultipleCalls() {
        when(mockResumabilityConfig.isResumable()).thenReturn(false);
        InvocationContext invocationContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("test-invocation-id")
                .agent(mockAgent)
                .session(mockSession)
                .userContent(Optional.empty())
                .resumabilityConfig(mockResumabilityConfig)
                .build();
        assertFalse(invocationContext.isResumable());
        assertFalse(invocationContext.isResumable());
        assertFalse(invocationContext.isResumable());
        verify(mockResumabilityConfig, times(3)).isResumable();
    }
    @Test
    @Tag("valid")
    void isResumableWithAllOptionalFieldsSet() {
        when(mockResumabilityConfig.isResumable()).thenReturn(true);
        InvocationContext invocationContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .memoryService(mockMemoryService)
                .pluginManager(mockPluginManager)
                .invocationId("full-invocation-id")
                .agent(mockAgent)
                .session(mockSession)
                .userContent(Optional.empty())
                .branch(Optional.of("agent1.agent2"))
                .endInvocation(false)
                .resumabilityConfig(mockResumabilityConfig)
                .build();
        assertTrue(invocationContext.isResumable());
    }
    @Test
    @Tag("valid")
    void isResumableWithOnlyRequiredFieldsSet() {
        when(mockResumabilityConfig.isResumable()).thenReturn(true);
        InvocationContext invocationContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("minimal-invocation-id")
                .agent(mockAgent)
                .session(mockSession)
                .resumabilityConfig(mockResumabilityConfig)
                .build();
        assertTrue(invocationContext.isResumable());
    }
    @Test
    @Tag("integration")
    void isResumableWithCopiedContextPreservesResumabilityConfig() {
        when(mockResumabilityConfig.isResumable()).thenReturn(true);
        InvocationContext originalContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("original-invocation-id")
                .agent(mockAgent)
                .session(mockSession)
                .userContent(Optional.empty())
                .resumabilityConfig(mockResumabilityConfig)
                .build();
        InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
        assertTrue(copiedContext.isResumable());
        verify(mockResumabilityConfig, times(2)).isResumable();
    }
    @Test
    @Tag("integration")
    void isResumableWithCopiedContextPreservesNonResumableConfig() {
        when(mockResumabilityConfig.isResumable()).thenReturn(false);
        InvocationContext originalContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("original-invocation-id")
                .agent(mockAgent)
                .session(mockSession)
                .userContent(Optional.empty())
                .resumabilityConfig(mockResumabilityConfig)
                .build();
        InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
        assertFalse(copiedContext.isResumable());
        verify(mockResumabilityConfig, times(2)).isResumable();
    }
    @Test
    @Tag("valid")
    void isResumableWithTrueDoesNotAffectEndInvocationState() {
        when(mockResumabilityConfig.isResumable()).thenReturn(true);
        InvocationContext invocationContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("test-invocation-id")
                .agent(mockAgent)
                .session(mockSession)
                .userContent(Optional.empty())
                .endInvocation(false)
                .resumabilityConfig(mockResumabilityConfig)
                .build();
        assertTrue(invocationContext.isResumable());
        assertFalse(invocationContext.endInvocation());
    }
    @Test
    @Tag("valid")
    void isResumableWithFalseDoesNotAffectEndInvocationState() {
        when(mockResumabilityConfig.isResumable()).thenReturn(false);
        InvocationContext invocationContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("test-invocation-id")
                .agent(mockAgent)
                .session(mockSession)
                .userContent(Optional.empty())
                .endInvocation(false)
                .resumabilityConfig(mockResumabilityConfig)
                .build();
        assertFalse(invocationContext.isResumable());
        assertFalse(invocationContext.endInvocation());
    }
    @Test
    @Tag("valid")
    void isResumableReturnsTrueWithBranchSet() {
        when(mockResumabilityConfig.isResumable()).thenReturn(true);
        InvocationContext invocationContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("test-invocation-id")
                .agent(mockAgent)
                .session(mockSession)
                .userContent(Optional.empty())
                .branch("parentAgent.childAgent")
                .resumabilityConfig(mockResumabilityConfig)
                .build();
        assertTrue(invocationContext.isResumable());
        assertTrue(invocationContext.branch().isPresent());
    }
    @Test
    @Tag("valid")
    void isResumableReturnsFalseWithBranchSet() {
        when(mockResumabilityConfig.isResumable()).thenReturn(false);
        InvocationContext invocationContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("test-invocation-id")
                .agent(mockAgent)
                .session(mockSession)
                .userContent(Optional.empty())
                .branch("parentAgent.childAgent")
                .resumabilityConfig(mockResumabilityConfig)
                .build();
        assertFalse(invocationContext.isResumable());
    }
    @Test
    @Tag("integration")
    void isResumableInteractionWithShouldPauseInvocationWhenNotResumable() {
        when(mockResumabilityConfig.isResumable()).thenReturn(false);
        InvocationContext invocationContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("test-invocation-id")
                .agent(mockAgent)
                .session(mockSession)
                .userContent(Optional.empty())
                .resumabilityConfig(mockResumabilityConfig)
                .build();
        assertFalse(invocationContext.isResumable());
        Event mockEvent = mock(Event.class);
        assertFalse(invocationContext.shouldPauseInvocation(mockEvent));
    }
    @Test
    @Tag("boundary")
    void isResumableWithNewInvocationContextIdUsedAsInvocationId() {
        when(mockResumabilityConfig.isResumable()).thenReturn(true);
        String newId = InvocationContext.newInvocationContextId();
        InvocationContext invocationContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId(newId)
                .agent(mockAgent)
                .session(mockSession)
                .userContent(Optional.empty())
                .resumabilityConfig(mockResumabilityConfig)
                .build();
        assertTrue(invocationContext.isResumable());
        assertTrue(newId.startsWith("e-"));
    }
    @Test
    @Tag("valid")
    void isResumableDoesNotMutateContextState() {
        when(mockResumabilityConfig.isResumable()).thenReturn(true);
        InvocationContext invocationContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("test-invocation-id")
                .agent(mockAgent)
                .session(mockSession)
                .userContent(Optional.empty())
                .endInvocation(false)
                .branch(Optional.of("test-branch"))
                .resumabilityConfig(mockResumabilityConfig)
                .build();
        boolean resultBefore = invocationContext.isResumable();
        boolean endInvocationBefore = invocationContext.endInvocation();
        Optional<String> branchBefore = invocationContext.branch();
        invocationContext.isResumable();
        assertTrue(resultBefore);
        assertFalse(endInvocationBefore);
        assertTrue(branchBefore.isPresent());
        assertFalse(invocationContext.endInvocation());
        assertTrue(invocationContext.branch().isPresent());
    }
    @Test
    @Tag("valid")
    void isResumableReflectsResumabilityConfigTrueReturnValue() {
        ResumabilityConfig spyResumabilityConfig = mock(ResumabilityConfig.class);
        when(spyResumabilityConfig.isResumable()).thenReturn(true);
        InvocationContext invocationContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("test-invocation-id")
                .agent(mockAgent)
                .session(mockSession)
                .resumabilityConfig(spyResumabilityConfig)
                .build();
        boolean result = invocationContext.isResumable();
        assertTrue(result);
        verify(spyRes