/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=userContent_84fbf4a756
ROOST_METHOD_SIG_HASH=userContent_7428a149e0

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/june-java-unit/1782282457/source/adk-java/core/src/test/java/com/google/adk/agents/InvocationContextTest.java
Tests:
    "@Test
public void testCreateWithUserContent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).isEmpty();
    assertThat(context.invocationId()).isEqualTo(testInvocationId);
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).hasValue(userContent);
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testCreateWithNullUserContent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.userContent()).isEmpty();
}
"
    "@Test
public void testCreateWithLiveRequestQueue() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).liveRequestQueue(liveRequestQueue).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).hasValue(liveRequestQueue);

    assertThat(context.invocationId()).startsWith("e-");
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).isEmpty();
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testCopyOf() {
    InvocationContext originalContext = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    originalContext.activeStreamingTools().putAll(activeStreamingTools);
    InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
    assertThat(copiedContext).isNotNull();
    assertThat(copiedContext).isNotSameInstanceAs(originalContext);
    assertThat(copiedContext.sessionService()).isEqualTo(originalContext.sessionService());
    assertThat(copiedContext.artifactService()).isEqualTo(originalContext.artifactService());
    assertThat(copiedContext.memoryService()).isEqualTo(originalContext.memoryService());
    assertThat(copiedContext.liveRequestQueue()).isEqualTo(originalContext.liveRequestQueue());
    assertThat(copiedContext.invocationId()).isEqualTo(originalContext.invocationId());
    assertThat(copiedContext.agent()).isEqualTo(originalContext.agent());
    assertThat(copiedContext.session()).isEqualTo(originalContext.session());
    assertThat(copiedContext.userContent()).isEqualTo(originalContext.userContent());
    assertThat(copiedContext.runConfig()).isEqualTo(originalContext.runConfig());
    assertThat(copiedContext.endInvocation()).isEqualTo(originalContext.endInvocation());
    assertThat(copiedContext.activeStreamingTools()).isEqualTo(originalContext.activeStreamingTools());
}
"
    "@Test
public void testGetters() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).isEmpty();
    assertThat(context.invocationId()).isEqualTo(testInvocationId);
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).hasValue(userContent);
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testSetAgent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    BaseAgent newMockAgent = mock(BaseAgent.class);
    context.agent(newMockAgent);
    assertThat(context.agent()).isEqualTo(newMockAgent);
}
"
    "@Test
public void testEquals_sameObject() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(context)).isTrue();
}
"
    "@Test
public void testEquals_null() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(null)).isFalse();
}
"
    "@Test
public void testEquals_sameValues() {
    InvocationContext context1 = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext context2 = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context1.equals(context2)).isTrue();

    assertThat(context2.equals(context1)).isTrue();
}
"
    "@Test
public void testEquals_differentValues() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext contextWithDiffSessionService = InvocationContext.builder().sessionService(
    mock(BaseSessionService.class)).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffInvocationId = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(
    "another-id").agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffAgent = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(
    mock(BaseAgent.class)).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithUserContentEmpty = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithLiveQueuePresent = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).liveRequestQueue(liveRequestQueue).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(contextWithDiffSessionService)).isFalse();
    assertThat(context.equals(contextWithDiffInvocationId)).isFalse();
    assertThat(context.equals(contextWithDiffAgent)).isFalse();
    assertThat(context.equals(contextWithUserContentEmpty)).isFalse();
    assertThat(context.equals(contextWithLiveQueuePresent)).isFalse();
}
"
    "@Test
public void testHashCode_differentValues() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext contextWithDiffSessionService = InvocationContext.builder().sessionService(
    mock(BaseSessionService.class)).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffInvocationId = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(
    "another-id").agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotEqualTo(contextWithDiffSessionService);
    assertThat(context).isNotEqualTo(contextWithDiffInvocationId);
}
"Scenario 1: Verify that userContent() Returns a Present Optional When Content Is Set

Details:
  TestName: userContentReturnsPresentOptionalWhenContentIsSet
  Description: Verifies that the userContent() method returns an Optional containing the Content object
               when the InvocationContext is built with a non-null Content value supplied via
               Optional.of(userContent).
Execution:
  Arrange: Create a Content object (userContent). Build an InvocationContext using the builder,
           supplying sessionService, artifactService, memoryService, pluginManager, invocationId,
           agent, session, runConfig, endInvocation(false), and userContent(Optional.of(userContent)).
  Act: Call context.userContent() on the built InvocationContext.
  Assert: Assert that the returned Optional is not empty and that its value equals the original
          Content object used during construction.
Validation:
  This assertion confirms that when a valid Content object is provided during construction,
  the userContent() accessor faithfully wraps and returns it inside a present Optional.
  This is critical for downstream components that rely on the presence of user-supplied content
  to drive agent behavior.


Scenario 2: Verify that userContent() Returns an Empty Optional When No Content Is Provided

Details:
  TestName: userContentReturnsEmptyOptionalWhenNotSet
  Description: Verifies that the userContent() method returns Optional.empty() when the
               InvocationContext is constructed with Optional.empty() as the user content.
Execution:
  Arrange: Build an InvocationContext using the builder with all required fields and
           userContent(Optional.empty()).
  Act: Call context.userContent() on the built InvocationContext.
  Assert: Assert that the returned Optional isEmpty().
Validation:
  Confirms that when no user content is provided, the accessor correctly returns an empty
  Optional rather than null or a present Optional. This prevents NullPointerExceptions in
  callers that use Optional.isPresent() or Optional.ifPresent() patterns.


Scenario 3: Verify that userContent() Does Not Return Null

Details:
  TestName: userContentNeverReturnsNull
  Description: Verifies that the userContent() method never returns a null reference,
               regardless of whether content was set or not, ensuring safe Optional usage.
Execution:
  Arrange: Build an InvocationContext using the builder with userContent(Optional.empty()).
  Act: Call context.userContent() on the built InvocationContext.
  Assert: Assert that the result of context.userContent() is not null.
Validation:
  Ensures the method contract — returning Optional rather than a raw nullable reference — is
  respected. Callers should always receive a non-null Optional, which is the fundamental promise
  of this return type.


Scenario 4: Verify that userContent() Returns the Same Content Instance That Was Provided

Details:
  TestName: userContentReturnsSameContentInstance
  Description: Verifies that the Content instance returned inside the Optional from userContent()
               is the same object reference that was supplied to the builder.
Execution:
  Arrange: Create a specific Content object. Build an InvocationContext with
           userContent(Optional.of(thatContentObject)).
  Act: Call context.userContent() and extract the value via .get().
  Assert: Assert that the extracted Content instance is the same reference (using isSameInstanceAs
          or assertEquals) as the original Content object provided at construction time.
Validation:
  Confirms no defensive copying or transformation occurs during storage or retrieval of the
  userContent field. The method should return the exact same object, ensuring identity integrity
  for downstream processing pipelines.


Scenario 5: Verify that userContent() Is Consistent Across Multiple Calls (Idempotency)

Details:
  TestName: userContentIsIdempotentAcrossMultipleCalls
  Description: Verifies that calling userContent() multiple times on the same InvocationContext
               instance always returns the same Optional value, demonstrating that the field
               is immutable and the accessor is side-effect free.
Execution:
  Arrange: Build an InvocationContext with a non-null Content object supplied as userContent.
  Act: Call context.userContent() three times and store each result.
  Assert: Assert that all three returned Optionals are equal to each other, and each contains
          a value equal to the original Content object.
Validation:
  Since userContent is declared as private final, repeated calls must return the same result.
  This test guards against any accidental mutation or lazy-initialization logic that could cause
  inconsistent behavior across multiple reads.


Scenario 6: Verify that userContent() Returns Present Optional When Built Using Content Directly (Non-Optional Builder Method)

Details:
  TestName: userContentReturnsPresentOptionalWhenBuiltWithContentDirectly
  Description: Verifies that the userContent() method returns a present Optional when the
               InvocationContext is built using the builder's userContent(Content) overload
               (which wraps the content in Optional.of internally) instead of the
               userContent(Optional<Content>) overload.
Execution:
  Arrange: Create a Content object. Build an InvocationContext using
           builder().userContent(contentObject) (the non-Optional overload).
  Act: Call context.userContent() on the built context.
  Assert: Assert that the returned Optional hasValue(contentObject) and is not empty.
Validation:
  Confirms that both builder overloads — userContent(Content) and userContent(Optional<Content>) —
  produce an equivalent and consistent state accessible via userContent(). This ensures API
  usability and prevents silent differences between the two construction paths.


Scenario 7: Verify that userContent() Reflects the Default Empty State When Builder Sets No User Content

Details:
  TestName: userContentDefaultsToEmptyOptionalWhenNotSetOnBuilder
  Description: Verifies that when the builder does not explicitly call userContent(...), the
               resulting InvocationContext has an empty Optional returned by userContent(),
               confirming the builder's default value is Optional.empty().
Execution:
  Arrange: Build an InvocationContext using the builder but intentionally omit any call to
           userContent(...), supplying only the other required fields (sessionService,
           artifactService, agent, session, etc.).
  Act: Call context.userContent() on the built InvocationContext.
  Assert: Assert that the returned Optional isEmpty().
Validation:
  Validates the default initialization contract of the Builder class, where userContent defaults
  to Optional.empty(). This protects against regressions where the default might accidentally
  be changed, which could cause NullPointerExceptions or incorrect behavior in agents that check
  for the absence of user content.


Scenario 8: Verify that userContent() from a Copied Context Returns the Same Value as the Original

Details:
  TestName: userContentInCopiedContextMatchesOriginal
  Description: Verifies that after using InvocationContext.copyOf(), the copied context's
               userContent() method returns a value equal to that of the original context.
Execution:
  Arrange: Build an original InvocationContext with a specific Content object as userContent.
           Create a copy using InvocationContext.copyOf(originalContext).
  Act: Call userContent() on both the original and the copied context.
  Assert: Assert that copiedContext.userContent() equals originalContext.userContent(), and
          that the Optional in the copy contains the same Content value.
Validation:
  Ensures that the shallow copy operation preserves the userContent field correctly. This is
  important for sub-agent delegation scenarios, where a copied context must carry the original
  user's input without alteration.


Scenario 9: Verify that userContent() Is Independent Between Two Separately Built Contexts

Details:
  TestName: userContentIsIndependentBetweenTwoContextInstances
  Description: Verifies that two InvocationContext instances built with different userContent
               values each independently return their own respective user content without
               interference.
Execution:
  Arrange: Create two distinct Content objects (contentA and contentB). Build contextA with
           userContent(Optional.of(contentA)) and contextB with userContent(Optional.of(contentB)).
  Act: Call userContent() on contextA and contextB separately.
  Assert: Assert that contextA.userContent() contains contentA and contextB.userContent()
          contains contentB. Assert they are not equal to each other.
Validation:
  Confirms that InvocationContext instances are independent and do not share state for the
  userContent field. This is essential in concurrent or multi-agent scenarios where different
  invocations must not bleed user content into one another.


Scenario 10: Verify that userContent() Returns Present Optional When One Context Has Content and Another Does Not

Details:
  TestName: userContentPresentInOneContextAndEmptyInAnother
  Description: Verifies that two contexts built differently — one with user content and one
               without — each return the correct Optional state from userContent(), confirming
               no shared mutable state exists between instances.
Execution:
  Arrange: Build contextWithContent using userContent(Optional.of(someContent)).
           Build contextWithoutContent using userContent(Optional.empty()).
  Act: Call userContent() on both contexts.
  Assert: Assert that contextWithContent.userContent() isPresent() and
          contextWithoutContent.userContent() isEmpty().
Validation:
  This scenario reinforces isolation between InvocationContext instances and validates that the
  presence or absence of user content is a property strictly tied to how each individual context
  was initialized, with no cross-contamination between instances.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.genai.types.Content;
import com.google.genai.types.Part;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class InvocationContextUserContentTest {

	@Mock
	private BaseSessionService mockSessionService;

	@Mock
	private BaseArtifactService mockArtifactService;

	@Mock
	private BaseMemoryService mockMemoryService;

	@Mock
	private PluginManager mockPluginManager;

	@Mock
	private Session mockSession;

	@Mock
	private BaseAgent mockAgent;

	private RunConfig runConfig;

	private Content sampleContent;

	@BeforeEach
	void setUp() {
		runConfig = RunConfig.builder().build();
		sampleContent = Content.builder().role("user").parts(List.of(Part.fromText("Hello, world!"))).build();
	}

	private InvocationContext.Builder baseBuilder() {
		return InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.pluginManager(mockPluginManager)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(runConfig)
			.endInvocation(false);
	}

	@Test
	@Tag("valid")
	void userContentReturnsPresentOptionalWhenContentIsSet() {
		// Arrange
		InvocationContext context = baseBuilder().userContent(Optional.of(sampleContent)).build();
		// Act
		Optional<Content> result = context.userContent();
		// Assert
		assertTrue(result.isPresent(), "Expected userContent Optional to be present");
		assertEquals(sampleContent, result.get(), "Expected userContent to equal the provided Content object");
	}

	@Test
	@Tag("valid")
	void userContentReturnsEmptyOptionalWhenNotSet() {
		// Arrange
		InvocationContext context = baseBuilder().userContent(Optional.empty()).build();
		// Act
		Optional<Content> result = context.userContent();
		// Assert
		assertTrue(result.isEmpty(), "Expected userContent Optional to be empty when no content is provided");
	}

	@Test
	@Tag("boundary")
	void userContentNeverReturnsNull() {
		// Arrange
		InvocationContext context = baseBuilder().userContent(Optional.empty()).build();
		// Act
		Optional<Content> result = context.userContent();
		// Assert
		assertNotNull(result, "userContent() must never return null; it should return Optional.empty() instead");
	}

	@Test
	@Tag("valid")
	void userContentReturnsSameContentInstance() {
		// Arrange
		Content specificContent = Content.builder()
			.role("user")
			.parts(List.of(Part.fromText("Specific content for identity check")))
			.build();
		InvocationContext context = baseBuilder().userContent(Optional.of(specificContent)).build();
		// Act
		Content retrievedContent = context.userContent().get();
		// Assert
		assertSame(specificContent, retrievedContent,
				"userContent() should return the exact same Content instance that was provided at construction");
	}

	@Test
	@Tag("valid")
	void userContentIsIdempotentAcrossMultipleCalls() {
		// Arrange
		InvocationContext context = baseBuilder().userContent(Optional.of(sampleContent)).build();
		// Act
		Optional<Content> result1 = context.userContent();
		Optional<Content> result2 = context.userContent();
		Optional<Content> result3 = context.userContent();
		// Assert
		assertEquals(result1, result2, "First and second calls to userContent() should return equal Optionals");
		assertEquals(result2, result3, "Second and third calls to userContent() should return equal Optionals");
		assertTrue(result1.isPresent(), "All calls should return a present Optional");
		assertEquals(sampleContent, result1.get(), "All calls should contain the original Content object");
		assertEquals(sampleContent, result2.get(), "All calls should contain the original Content object");
		assertEquals(sampleContent, result3.get(), "All calls should contain the original Content object");
	}

	@Test
	@Tag("valid")
	void userContentReturnsPresentOptionalWhenBuiltWithContentDirectly() {
		// Arrange
		Content contentObject = Content.builder().role("user").parts(List.of(Part.fromText("Direct content"))).build();
		InvocationContext context = baseBuilder().userContent(contentObject).build();
		// Act
		Optional<Content> result = context.userContent();
		// Assert
		assertTrue(result.isPresent(),
				"Expected userContent to be present when built using the Content (non-Optional) builder overload");
		assertEquals(contentObject, result.get(),
				"Expected retrieved content to equal the content object passed directly to builder");
	}

	@Test
	@Tag("boundary")
	void userContentDefaultsToEmptyOptionalWhenNotSetOnBuilder() {
		// Arrange - intentionally omit userContent call on builder
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.pluginManager(mockPluginManager)
			.invocationId("test-invocation-no-content")
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(runConfig)
			.endInvocation(false)
			.build();
		// Act
		Optional<Content> result = context.userContent();
		// Assert
		assertTrue(result.isEmpty(),
				"When no userContent is set on builder, userContent() should return Optional.empty()");
	}

	@Test
	@Tag("integration")
	void userContentInCopiedContextMatchesOriginal() {
		// Arrange
		Content originalContent = Content.builder()
			.role("user")
			.parts(List.of(Part.fromText("Original user content")))
			.build();
		InvocationContext originalContext = baseBuilder().userContent(Optional.of(originalContent)).build();
		// Act
		InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
		// Assert
		assertEquals(originalContext.userContent(), copiedContext.userContent(),
				"Copied context's userContent should equal the original context's userContent");
		assertTrue(copiedContext.userContent().isPresent(), "Copied context's userContent should be present");
		assertEquals(originalContent, copiedContext.userContent().get(),
				"Copied context's userContent value should equal the original Content object");
	}

	@Test
	@Tag("valid")
	void userContentIsIndependentBetweenTwoContextInstances() {
		// Arrange
		Content contentA = Content.builder().role("user").parts(List.of(Part.fromText("Content A"))).build();
		Content contentB = Content.builder().role("model").parts(List.of(Part.fromText("Content B"))).build();
		InvocationContext contextA = baseBuilder().invocationId("invocation-a")
			.userContent(Optional.of(contentA))
			.build();
		InvocationContext contextB = baseBuilder().invocationId("invocation-b")
			.userContent(Optional.of(contentB))
			.build();
		// Act
		Optional<Content> resultA = contextA.userContent();
		Optional<Content> resultB = contextB.userContent();
		// Assert
		assertTrue(resultA.isPresent(), "contextA's userContent should be present");
		assertTrue(resultB.isPresent(), "contextB's userContent should be present");
		assertEquals(contentA, resultA.get(), "contextA should contain contentA");
		assertEquals(contentB, resultB.get(), "contextB should contain contentB");
		assertNotEquals(resultA, resultB,
				"The two contexts should return different userContent values, confirming independence");
	}

	@Test
	@Tag("valid")
	void userContentPresentInOneContextAndEmptyInAnother() {
		// Arrange
		Content someContent = Content.builder()
			.role("user")
			.parts(List.of(Part.fromText("Some content for context with content")))
			.build();
		InvocationContext contextWithContent = baseBuilder().invocationId("context-with-content")
			.userContent(Optional.of(someContent))
			.build();
		InvocationContext contextWithoutContent = baseBuilder().invocationId("context-without-content")
			.userContent(Optional.empty())
			.build();
		// Act
		Optional<Content> resultWithContent = contextWithContent.userContent();
		Optional<Content> resultWithoutContent = contextWithoutContent.userContent();
		// Assert
		assertTrue(resultWithContent.isPresent(), "contextWithContent should have a present userContent Optional");
		assertTrue(resultWithoutContent.isEmpty(), "contextWithoutContent should have an empty userContent Optional");
		assertEquals(someContent, resultWithContent.get(),
				"contextWithContent should contain the provided someContent");
	}

	@Test
	@Tag("valid")
	void userContentReturnedFromStaticCreateMethod() {
		// Arrange
		Content contentForCreate = Content.builder()
			.role("user")
			.parts(List.of(Part.fromText("Content via static create")))
			.build();
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService,
				"static-create-invocation-id", mockAgent, mockSession, contentForCreate, runConfig);
		// Act
		Optional<Content> result = context.userContent();
		// Assert
		assertTrue(result.isPresent(),
				"userContent should be present when created via static create method with non-null content");
		assertEquals(contentForCreate, result.get(),
				"userContent should equal the Content provided to the static create method");
	}

	@Test
	@Tag("boundary")
	void userContentReturnsEmptyOptionalWhenNullPassedToStaticCreateMethod() {
		// Arrange
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService,
				"invocation-null-content", mockAgent, mockSession, null, runConfig);
		// Act
		Optional<Content> result = context.userContent();
		// Assert
		assertNotNull(result, "userContent() must not return null even when null was passed to create()");
		assertTrue(result.isEmpty(), "userContent should be empty when null content is passed to static create method");
	}

	@Test
	@Tag("integration")
	void userContentPreservedAfterCopyOfWithEmptyContent() {
		// Arrange
		InvocationContext originalContext = baseBuilder().userContent(Optional.empty()).build();
		// Act
		InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
		// Assert
		assertNotNull(copiedContext.userContent(), "Copied context's userContent() must not return null");
		assertTrue(copiedContext.userContent().isEmpty(),
				"Copied context should also have empty userContent when original had empty userContent");
		assertEquals(originalContext.userContent(), copiedContext.userContent(),
				"Copied context's userContent should equal the original's empty Optional");
	}

}
