/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=session_a0f90dafba
ROOST_METHOD_SIG_HASH=session_a2fc7a867d

Scenario 1: Return the Session Object That Was Set During Construction via Builder

Details:
  TestName: sessionReturnsSessionSetViaBuilder
  Description: Verifies that the `session()` method returns the exact same `Session` object
               that was provided to the `InvocationContext` builder during construction.
               This is the primary happy-path scenario confirming correct field assignment
               and retrieval.
Execution:
  Arrange: Create a mock or concrete `Session` object. Use `InvocationContext.builder()`
           and call `.session(mockSession)` along with other minimally required fields
           (e.g., `sessionService`, `artifactService`, `agent`, `invocationId`).
           Call `.build()` to create the `InvocationContext` instance.
  Act: Invoke `invocationContext.session()` on the constructed instance.
  Assert: Use `assertSame(mockSession, invocationContext.session())` to confirm that
          the returned object is the identical reference that was set.
Validation:
  The assertion confirms that `session()` returns the exact reference stored in the
  private final `session` field. Since the field is final and set only in the constructor,
  the return value must always match what was provided at build time. This is fundamental
  to ensuring that the invocation context correctly carries session state throughout an
  agent's lifecycle.

---

Scenario 2: Session Returned Is Not Null When a Valid Session Is Provided

Details:
  TestName: sessionReturnsNonNullWhenValidSessionProvided
  Description: Verifies that calling `session()` on an `InvocationContext` built with a
               valid (non-null) `Session` object returns a non-null value. This guards
               against accidental null returns due to misconfigured construction logic.
Execution:
  Arrange: Create a mock `Session` object. Build an `InvocationContext` via
           `InvocationContext.builder().session(mockSession)...build()`.
  Act: Call `invocationContext.session()`.
  Assert: Use `assertNotNull(invocationContext.session())` to confirm the result is
          not null.
Validation:
  Ensures that a validly constructed `InvocationContext` never returns a null session.
  Since `Session` is a required component for agent invocations (e.g., `appName()` and
  `userId()` delegate to it), a null session would cause NullPointerExceptions throughout
  the system. This test confirms the basic contract of the accessor method.

---

Scenario 3: Session Returned Is Consistent Across Multiple Calls

Details:
  TestName: sessionReturnsSameInstanceOnMultipleCalls
  Description: Verifies that repeated calls to `session()` on the same `InvocationContext`
               instance always return the same `Session` object, confirming idempotency
               and immutability of the private final `session` field.
Execution:
  Arrange: Create a mock `Session` object. Build an `InvocationContext` instance using
           the builder with that session.
  Act: Call `invocationContext.session()` multiple times (e.g., three times) and store
       each result.
  Assert: Use `assertSame(firstResult, secondResult)` and `assertSame(firstResult, thirdResult)`
          to confirm all calls return the identical reference.
Validation:
  Since `session` is a `private final` field, its value cannot change after construction.
  This test verifies the immutability guarantee, ensuring that callers can safely cache
  or rely on the session reference without concern for it changing between accesses.
  This is critical in multi-step agent workflows where session context must remain stable.

---

Scenario 4: Session Returned Matches the Session Used in copyOf

Details:
  TestName: sessionReturnsSameSessionAfterCopyOf
  Description: Verifies that when `InvocationContext.copyOf(other)` is used to create a
               shallow copy, the `session()` method on the copied context returns the same
               `Session` instance as the original context. This confirms that `copyOf`
               correctly propagates the session reference.
Execution:
  Arrange: Create a mock `Session` object. Build an original `InvocationContext` with
           that session. Call `InvocationContext.copyOf(originalContext)` to create
           a copied context.
  Act: Call `copiedContext.session()` on the new context.
  Assert: Use `assertSame(originalContext.session(), copiedContext.session())` to confirm
          both return the same `Session` reference.
Validation:
  The `copyOf` method performs a shallow copy and explicitly passes `other.session` to the
  builder. This test validates that the session propagation in `copyOf` works correctly.
  In agent delegation scenarios where sub-contexts are created from parent contexts, it is
  essential that the same session is shared to maintain conversational coherence.

---

Scenario 5: Session Object Returned Reflects the Correct Application Name via appName()

Details:
  TestName: sessionReturnedAllowsAccessToAppName
  Description: Verifies that the `Session` object returned by `session()` is functional
               and correctly exposes the application name. This test validates the
               integration between the `session()` accessor and the `appName()` method,
               which internally delegates to `session.appName()`.
Execution:
  Arrange: Create a mock `Session` object configured to return a specific app name
           (e.g., "test-app") when `appName()` is called. Build an `InvocationContext`
           with this mock session.
  Act: Retrieve the session via `invocationContext.session()` and call `appName()` on
       the returned session. Also call `invocationContext.appName()` directly.
  Assert: Use `assertEquals("test-app", invocationContext.session().appName())` and
          `assertEquals(invocationContext.session().appName(), invocationContext.appName())`
          to confirm consistency.
Validation:
  The `appName()` method on `InvocationContext` delegates to `session.appName()`,
  confirming that the session returned by `session()` is the live, functional object
  used by the context. This test verifies the correctness of the delegation chain and
  ensures the session is not a stale or incorrectly wrapped copy.

---

Scenario 6: Session Object Returned Reflects the Correct User ID via userId()

Details:
  TestName: sessionReturnedAllowsAccessToUserId
  Description: Verifies that the `Session` object returned by `session()` correctly
               exposes the user ID. This validates that the same session object used
               internally by `userId()` delegation is accessible via `session()`.
Execution:
  Arrange: Create a mock `Session` configured to return a specific user ID
           (e.g., "user-123") when `userId()` is called. Build an `InvocationContext`
           using this session.
  Act: Call `invocationContext.session()` to get the session, then call `userId()` on it.
       Also call `invocationContext.userId()` directly.
  Assert: Use `assertEquals("user-123", invocationContext.session().userId())` and
          `assertEquals(invocationContext.session().userId(), invocationContext.userId())`
          to confirm they are consistent.
Validation:
  Similar to `appName()`, the `userId()` method on `InvocationContext` delegates to the
  session. This test ensures the session returned by `session()` is the authoritative
  source for user identity information, verifying that no data inconsistency exists
  between direct access and delegated access patterns.

---

Scenario 7: Session Is Preserved After Modifying Other Mutable Fields of InvocationContext

Details:
  TestName: sessionRemainsUnchangedAfterMutatingOtherFields
  Description: Verifies that the `session` field remains unchanged even after mutating
               other mutable fields of the `InvocationContext` (such as `endInvocation`,
               `branch`, or `agent`). Since `session` is `private final`, it must not
               be affected by mutations to other fields.
Execution:
  Arrange: Create a mock `Session` object. Build an `InvocationContext` with that session.
           Capture the session reference returned by `invocationContext.session()` before
           any mutations.
  Act: Call `invocationContext.setEndInvocation(true)`, `invocationContext.branch("new-branch")`,
       and `invocationContext.agent(mockAgent)`. After these mutations, call
       `invocationContext.session()` again.
  Assert: Use `assertSame(originalSession, invocationContext.session())` to confirm
          the session reference has not changed after mutations.
Validation:
  The `session` field is declared as `private final`, meaning it can only be set during
  construction and cannot be reassigned. This test provides confidence that mutable
  operations on the context do not inadvertently affect the session binding, which is
  critical for maintaining session integrity during complex, multi-step agent interactions.

---

Scenario 8: Session Returned by session() Is the Same Object Used in equals() Comparison

Details:
  TestName: sessionContributesToEqualityCheck
  Description: Verifies that the `Session` object returned by `session()` is the same
               field used in the `equals()` method of `InvocationContext`. Two contexts
               built with the same session should reflect equal session references, while
               those built with different sessions should not be considered equal solely
               based on session difference.
Execution:
  Arrange: Create two distinct mock `Session` objects (`sessionA` and `sessionB`).
           Build two `InvocationContext` instances using identical builder configurations
           except that one uses `sessionA` and the other uses `sessionB`.
  Act: Call `session()` on both instances and compare using `assertSame` / `assertNotSame`.
       Also call `assertEquals` / `assertNotEquals` on the two context instances.
  Assert: Use `assertSame(sessionA, contextA.session())`, `assertSame(sessionB, contextB.session())`,
          `assertNotSame(contextA.session(), contextB.session())`, and
          `assertNotEquals(contextA, contextB)`.
Validation:
  The `equals()` method in `InvocationContext` includes `Objects.equals(session, that.session)`
  as part of its equality logic. This test confirms that `session()` returns the field
  that participates in equality checks. Verifying this is important for use cases where
  contexts are compared, stored in collections, or deduplicated based on their content.

---

Scenario 9: Session Returned via Deprecated Constructor Matches the Provided Session

Details:
  TestName: sessionReturnedFromDeprecatedConstructorMatchesInput
  Description: Verifies that when the deprecated public constructor of `InvocationContext`
               is used to create an instance, the `session()` method still returns the
               same `Session` object that was passed in. This ensures backward
               compatibility of the `session()` accessor regardless of how the context
               was constructed.
Execution:
  Arrange: Create mock instances for `BaseSessionService`, `BaseArtifactService`,
           `BaseMemoryService`, `PluginManager`, `LiveRequestQueue`, `BaseAgent`,
           `Session`, `Content`, and `RunConfig`. Use the deprecated constructor:
           `new InvocationContext(sessionService, artifactService, memoryService,
           pluginManager, Optional.of(liveRequestQueue), Optional.empty(), "inv-id",
           agent, mockSession, Optional.empty(), runConfig, false)`.
  Act: Call `invocationContext.session()` on the instance created via the deprecated
       constructor.
  Assert: Use `assertSame(mockSession, invocationContext.session())` to confirm
          the correct session is returned.
Validation:
  Even though the deprecated constructors delegate to the builder internally, this test
  ensures the session field is correctly threaded through the builder chain and that
  no accidental data loss occurs. It preserves confidence in backward compatibility for
  existing users of the deprecated API.

---

Scenario 10: Session Returned via Static create() Factory Method Matches the Provided Session

Details:
  TestName: sessionReturnedFromStaticCreateMethodMatchesInput
  Description: Verifies that when the deprecated static `create()` factory method is used
               to instantiate `InvocationContext`, the `session()` accessor correctly
               returns the `Session` object passed to the factory method.
Execution:
  Arrange: Create mock instances for `BaseSessionService`, `BaseArtifactService`,
           `BaseAgent`, `Session`, `Content`, and `RunConfig`. Use the deprecated
           static factory: `InvocationContext.create(sessionService, artifactService,
           "inv-id", agent, mockSession, userContent, runConfig)`.
  Act: Call `invocationContext.session()` on the resulting instance.
  Assert: Use `assertSame(mockSession, invocationContext.session())` to confirm the
          session is the exact object passed to the factory method.
Validation:
  The static `create()` methods are deprecated but still part of the public API contract.
  This test ensures that regardless of the instantiation mechanism, the `session()`
  accessor consistently returns the correct `Session` object, reinforcing that all
  creation paths correctly initialize the internal `session` field.

*/

// ********RoostGPT********

```java
package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.events.Event;
import com.google.adk.flows.llmflows.ResumabilityConfig;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.models.LlmCallsLimitExceededException;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.genai.types.Content;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.junit.jupiter.api.*;
import com.google.common.collect.ImmutableSet;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import com.google.errorprone.annotations.InlineMe;
import com.google.genai.types.FunctionCall;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import javax.annotation.Nullable;

@ExtendWith(MockitoExtension.class)
public class InvocationContextSessionTest {

	@Mock
	private BaseSessionService mockSessionService;

	@Mock
	private BaseArtifactService mockArtifactService;

	@Mock
	private BaseMemoryService mockMemoryService;

	@Mock
	private PluginManager mockPluginManager;

	@Mock
	private Session mockSession;

	@Mock
	private Session mockSessionA;

	@Mock
	private Session mockSessionB;

	@Mock
	private BaseAgent mockAgent;

	@Mock
	private Content mockUserContent;

	@Mock
	private RunConfig mockRunConfig;

	@Mock
	private LiveRequestQueue mockLiveRequestQueue;

	@Mock
	private ResumabilityConfig mockResumabilityConfig;

	private static final String INVOCATION_ID = "test-invocation-id";

	private static final String APP_NAME = "test-app";

	private static final String USER_ID = "user-123";

	@BeforeEach
	void setUp() {
		lenient().when(mockSession.appName()).thenReturn(APP_NAME);
		lenient().when(mockSession.userId()).thenReturn(USER_ID);
		lenient().when(mockRunConfig.maxLlmCalls()).thenReturn(500);
	}

	@Test
	@Tag("valid")
	void sessionReturnsSessionSetViaBuilder() {
		// Arrange
		InvocationContext invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId(INVOCATION_ID)
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.ofNullable(mockUserContent))
			.runConfig(mockRunConfig)
			.build();
		// Act
		Session result = invocationContext.session();
		// Assert
		assertSame(mockSession, result);
	}

	@Test
	@Tag("valid")
	void sessionReturnsNonNullWhenValidSessionProvided() {
		// Arrange
		InvocationContext invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId(INVOCATION_ID)
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.ofNullable(mockUserContent))
			.runConfig(mockRunConfig)
			.build();
		// Act
		Session result = invocationContext.session();
		// Assert
		assertNotNull(result);
	}

	@Test
	@Tag("valid")
	void sessionReturnsSameInstanceOnMultipleCalls() {
		// Arrange
		InvocationContext invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId(INVOCATION_ID)
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.ofNullable(mockUserContent))
			.runConfig(mockRunConfig)
			.build();
		// Act
		Session firstResult = invocationContext.session();
		Session secondResult = invocationContext.session();
		Session thirdResult = invocationContext.session();
		// Assert
		assertSame(firstResult, secondResult);
		assertSame(firstResult, thirdResult);
	}

	@Test
	@Tag("integration")
	void sessionReturnsSameSessionAfterCopyOf() {
		// Arrange
		InvocationContext originalContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId(INVOCATION_ID)
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.ofNullable(mockUserContent))
			.runConfig(mockRunConfig)
			.build();
		// Act
		InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
		Session copiedSession = copiedContext.session();
		// Assert
		assertSame(originalContext.session(), copiedSession);
		assertSame(mockSession, copiedSession);
	}

	@Test
    @Tag("integration")
    void sessionReturnedAllowsAccessToAppName() {
        // Arrange
        when(mockSession.appName()).thenReturn(APP_NAME);
        InvocationContext invocationContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId(INVOCATION_ID)
                .agent(mockAgent)
                .session(mockSession)
                .userContent(Optional.ofNullable(mockUserContent))
                .runConfig(mockRunConfig)
                .build();
        // Act
        String appNameFromSession = invocationContext.session().appName();
        String appNameFromContext = invocationContext.appName();
        // Assert
        assertEquals(APP_NAME, appNameFromSession);
        assertEquals(invocationContext.session().appName(), appNameFromContext);
        assertEquals(APP_NAME, appNameFromContext);
    }

	@Test
    @Tag("integration")
    void sessionReturnedAllowsAccessToUserId() {
        // Arrange
        when(mockSession.userId()).thenReturn(USER_ID);
        InvocationContext invocationContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId(INVOCATION_ID)
                .agent(mockAgent)
                .session(mockSession)
                .userContent(Optional.ofNullable(mockUserContent))
                .runConfig(mockRunConfig)
                .build();
        // Act
        String userIdFromSession = invocationContext.session().userId();
        String userIdFromContext = invocationContext.userId();
        // Assert
        assertEquals(USER_ID, userIdFromSession);
        assertEquals(invocationContext.session().userId(), userIdFromContext);
        assertEquals(USER_ID, userIdFromContext);
    }

	@Test
	@Tag("valid")
	void sessionRemainsUnchangedAfterMutatingOtherFields() {
		// Arrange
		InvocationContext invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId(INVOCATION_ID)
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.ofNullable(mockUserContent))
			.runConfig(mockRunConfig)
			.build();
		Session originalSession = invocationContext.session();
		// Act
		invocationContext.setEndInvocation(true);
		invocationContext.branch("new-branch");
		invocationContext.agent(mockAgent);
		Session sessionAfterMutations = invocationContext.session();
		// Assert
		assertSame(originalSession, sessionAfterMutations);
		assertSame(mockSession, sessionAfterMutations);
	}

	@Test
	@Tag("valid")
	void sessionContributesToEqualityCheck() {
		// Arrange
		InvocationContext contextA = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId(INVOCATION_ID)
			.agent(mockAgent)
			.session(mockSessionA)
			.userContent(Optional.ofNullable(mockUserContent))
			.runConfig(mockRunConfig)
			.build();
		InvocationContext contextB = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId(INVOCATION_ID)
			.agent(mockAgent)
			.session(mockSessionB)
			.userContent(Optional.ofNullable(mockUserContent))
			.runConfig(mockRunConfig)
			.build();
		// Act & Assert
		assertSame(mockSessionA, contextA.session());
		assertSame(mockSessionB, contextB.session());
		assertNotSame(contextA.session(), contextB.session());
		assertNotEquals(contextA, contextB);
	}

	@Test
	@Tag("valid")
	void sessionReturnedFromDeprecatedConstructorMatchesInput() {
		// Arrange
		@SuppressWarnings("deprecation")
		InvocationContext invocationContext = new InvocationContext(mockSessionService, mockArtifactService,
				mockMemoryService, mockPluginManager, Optional.of(mockLiveRequestQueue), Optional.empty(),
				INVOCATION_ID, mockAgent, mockSession, Optional.empty(), mockRunConfig, false);
		// Act
		Session result = invocationContext.session();
		// Assert
		assertSame(mockSession, result);
		assertNotNull(result);
	}

	@Test
	@Tag("valid")
	void sessionReturnedFromDeprecatedConstructorWithoutPluginManagerMatchesInput() {
		// Arrange
		@SuppressWarnings("deprecation")
		InvocationContext invocationContext = new InvocationContext(mockSessionService, mockArtifactService,
				mockMemoryService, Optional.of(mockLiveRequestQueue), Optional.empty(), INVOCATION_ID, mockAgent,
				mockSession, Optional.empty(), mockRunConfig, false);
		// Act
		Session result = invocationContext.session();
		// Assert
		assertSame(mockSession, result);
		assertNotNull(result);
	}

	@Test
	@Tag("valid")
	void sessionReturnedFromStaticCreateMethodMatchesInput() {
		// Arrange
		InvocationContext invocationContext = InvocationContext.create(mockSessionService, mockArtifactService,
				INVOCATION_ID, mockAgent, mockSession, mockUserContent, mockRunConfig);
		// Act
		Session result = invocationContext.session();
		// Assert
		assertSame(mockSession, result);
		assertNotNull(result);
	}

	@Test
	@Tag("valid")
	void sessionReturnedFromStaticCreateMethodWithLiveQueueMatchesInput() {
		// Arrange
		InvocationContext invocationContext = InvocationContext.create(mockSessionService, mockArtifactService,
				mockAgent, mockSession, mockLiveRequestQueue, mockRunConfig);
		// Act
		Session result = invocationContext.session();
		// Assert
		assertSame(mockSession, result);
		assertNotNull(result);
	}

	@Test
	@Tag("boundary")
	void sessionReturnedFromStaticCreateMethodWithNullUserContentMatchesInput() {
		// Arrange
		InvocationContext invocationContext = InvocationContext.create(mockSessionService, mockArtifactService,
				INVOCATION_ID, mockAgent, mockSession, null, mockRunConfig);
		// Act
		Session result = invocationContext.session();
		// Assert
		assertSame(mockSession, result);
		assertNotNull(result);
		assertTrue(invocationContext.userContent().isEmpty());
	}

	@Test
	@Tag("boundary")
	void sessionReturnedFromStaticCreateMethodWithNullLiveQueueMatchesInput() {
		// Arrange
		InvocationContext invocationContext = InvocationContext.create(mockSessionService, mockArtifactService,
				mockAgent, mockSession, null, mockRunConfig);
		// Act
		Session result = invocationContext.session();
		// Assert
		assertSame(mockSession, result);
		assertNotNull(result);
		assertTrue(invocationContext.liveRequestQueue().isEmpty());
	}

	@Test
	@Tag("valid")
	void sessionIsConsistentWithCopyOfAfterMutation() {
		// Arrange
		InvocationContext originalContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId(INVOCATION_ID)
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.ofNullable(mockUserContent))
			.runConfig(mockRunConfig)
			.build();
		InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
		// Act
		originalContext.setEndInvocation(true);
		originalContext.branch("modified-branch");
		// Assert
		assertSame(mockSession, originalContext.session());
		assertSame(mockSession, copiedContext.session());
		assertSame(originalContext.session(), copiedContext.session());
	}

	@Test
    @Tag("integration")
    void sessionAccessorIsConsistentWithAppNameDelegation() {
        // Arrange
        when(mockSession.appName()).thenReturn(APP_NAME);
        InvocationContext invocationContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId(INVOCATION_ID)
                .agent(mockAgent)
                .session(mockSession)
                .runConfig(mockRunConfig)
                .build();
        // Act
        String appNameViaSession = invocationContext.session().appName();
        String appNameDirectly = invocationContext.appName();
        // Assert
        assertNotNull(invocationContext.session());
        assertEquals(appNameViaSession, appNameDirectly);
        verify(mockSession, atLeastOnce()).appName();
    }

	@Test
    @Tag("integration")
    void sessionAccessorIsConsistentWithUserIdDelegation() {
        // Arrange
        when(mockSession.userId()).thenReturn(USER_ID);
        InvocationContext invocationContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId(INVOCATION_ID)
                .agent(mockAgent)
                .session(mockSession)
                .runConfig(mockRunConfig)
                .build();
        // Act
        String userIdViaSession = invocationContext.session().userId();
        String userIdDirectly = invocationContext.userId();
        // Assert
        assertNotNull(invocationContext.session());
        assertEquals(userIdViaSession, userIdDirectly);
        verify(mockSession, atLeastOnce()).userId();
    }

@Test
    @Tag("valid")
    void sessionFieldParticipatesInHashCode() {
        // Arrange
        InvocationContext context1 = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId(INVOCATION_ID)
                .agent(mockAgent)
                .