/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=pluginManager_009a0b1a05
ROOST_METHOD_SIG_HASH=pluginManager_3452d016c7

Scenario 1: Verify That pluginManager() Returns the PluginManager Set via Builder

Details:
  TestName: pluginManagerReturnsInstanceSetViaBuilder
  Description: Verifies that when a specific PluginManager instance is provided through the builder,
               the pluginManager() method returns that exact same instance.
Execution:
  Arrange: Create a PluginManager instance. Build an InvocationContext using
           InvocationContext.builder().pluginManager(pluginManager).build().
  Act: Call pluginManager() on the constructed InvocationContext.
  Assert: Use assertSame() to verify the returned PluginManager is identical (same reference)
          to the one provided during construction.
Validation:
  This assertion confirms that the pluginManager field is stored and retrieved without any
  transformation or wrapping. It is critical that the InvocationContext faithfully returns
  the exact PluginManager it was given, ensuring all plugin registrations and tool
  configurations are preserved and accessible during the agent invocation lifecycle.

*/

// ********RoostGPT********

```java
package com.google.adk.agents;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.events.Event;
import com.google.adk.flows.llmflows.ResumabilityConfig;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.models.LlmCallsLimitExceededException;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.common.collect.ImmutableSet;
import com.google.genai.types.Content;
import com.google.genai.types.FunctionCall;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import javax.annotation.Nullable;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.junit.jupiter.api.*;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import com.google.errorprone.annotations.InlineMe;

@ExtendWith(MockitoExtension.class)
public class InvocationContextPluginManagerTest {
    @Mock
    private BaseSessionService mockSessionService;
    @Mock
    private BaseArtifactService mockArtifactService;
    @Mock
    private BaseMemoryService mockMemoryService;
    @Mock
    private BaseAgent mockAgent;
    private Session session;
    private RunConfig runConfig;
    private PluginManager pluginManager;
    @BeforeEach
    void setUp() {
        session = Session.builder("test-session-id")
                .build();
        runConfig = RunConfig.builder().build();
        pluginManager = new PluginManager();
    }
    @Test
    @Tag("valid")
    void pluginManagerReturnsInstanceSetViaBuilder() {
        // Arrange
        PluginManager expectedPluginManager = new PluginManager();
        InvocationContext context = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .pluginManager(expectedPluginManager)
                .invocationId("test-invocation-id")
                .agent(mockAgent)
                .session(session)
                .userContent(Optional.empty())
                .runConfig(runConfig)
                .build();
        // Act
        PluginManager result = context.pluginManager();
        // Assert
        assertSame(expectedPluginManager, result,
                "pluginManager() should return the exact same PluginManager instance set via builder");
    }
    @Test
    @Tag("valid")
    void pluginManagerReturnsNullWhenNotSet() {
        // Arrange
        InvocationContext context = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .invocationId("test-invocation-id")
                .agent(mockAgent)
                .session(session)
                .userContent(Optional.empty())
                .runConfig(runConfig)
                .build();
        // Act
        PluginManager result = context.pluginManager();
        // Assert
        assertNull(result, "pluginManager() should return null when no PluginManager was set");
    }
    @Test
    @Tag("valid")
    void pluginManagerReturnsSameInstanceAcrossMultipleCalls() {
        // Arrange
        PluginManager expectedPluginManager = new PluginManager();
        InvocationContext context = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .pluginManager(expectedPluginManager)
                .invocationId("test-invocation-id")
                .agent(mockAgent)
                .session(session)
                .userContent(Optional.empty())
                .runConfig(runConfig)
                .build();
        // Act
        PluginManager firstCall = context.pluginManager();
        PluginManager secondCall = context.pluginManager();
        // Assert
        assertSame(firstCall, secondCall,
                "pluginManager() should return the same instance across multiple calls");
        assertSame(expectedPluginManager, firstCall,
                "pluginManager() should return the exact instance set via builder");
    }
    @Test
    @Tag("valid")
    void pluginManagerReturnedInstancePreservesRegisteredPlugins() {
        // Arrange
        PluginManager expectedPluginManager = new PluginManager();
        InvocationContext context = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .pluginManager(expectedPluginManager)
                .invocationId("test-invocation-id")
                .agent(mockAgent)
                .session(session)
                .userContent(Optional.empty())
                .runConfig(runConfig)
                .build();
        // Act
        PluginManager result = context.pluginManager();
        // Assert
        assertNotNull(result, "pluginManager() should not return null when a PluginManager was set");
        assertSame(expectedPluginManager, result,
                "Returned PluginManager should be the same reference as the one set");
    }
    @Test
    @Tag("valid")
    void pluginManagerReturnedFromCopyOfPreservesOriginal() {
        // Arrange
        PluginManager expectedPluginManager = new PluginManager();
        InvocationContext originalContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .pluginManager(expectedPluginManager)
                .invocationId("test-invocation-id")
                .agent(mockAgent)
                .session(session)
                .userContent(Optional.empty())
                .runConfig(runConfig)
                .build();
        // Act
        InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
        PluginManager result = copiedContext.pluginManager();
        // Assert
        assertSame(expectedPluginManager, result,
                "copyOf should preserve the same PluginManager reference");
        assertSame(originalContext.pluginManager(), copiedContext.pluginManager(),
                "Original and copied contexts should share the same PluginManager instance");
    }
    @Test
    @Tag("valid")
    void pluginManagerNotNullWhenExplicitlySet() {
        // Arrange
        PluginManager expectedPluginManager = new PluginManager();
        InvocationContext context = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .pluginManager(expectedPluginManager)
                .invocationId("test-invocation-id")
                .agent(mockAgent)
                .session(session)
                .userContent(Optional.empty())
                .runConfig(runConfig)
                .build();
        // Act & Assert
        assertNotNull(context.pluginManager(),
                "pluginManager() should not be null when explicitly set");
    }
    @Test
    @Tag("valid")
    void pluginManagerIsIndependentFromMemoryService() {
        // Arrange
        PluginManager expectedPluginManager = new PluginManager();
        InvocationContext context = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .memoryService(mockMemoryService)
                .pluginManager(expectedPluginManager)
                .invocationId("test-invocation-id")
                .agent(mockAgent)
                .session(session)
                .userContent(Optional.empty())
                .runConfig(runConfig)
                .build();
        // Act
        PluginManager result = context.pluginManager();
        // Assert
        assertSame(expectedPluginManager, result,
                "pluginManager() should be independent from other services like memoryService");
        assertNotNull(context.memoryService(),
                "memoryService should still be accessible");
    }
    @Test
    @Tag("valid")
    void pluginManagerReturnedFromCreateMethodWithUserContent() {
        // Arrange
        PluginManager expectedPluginManager = new PluginManager();
        String invocationId = InvocationContext.newInvocationContextId();
        Content userContent = mock(Content.class);
        InvocationContext context = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .pluginManager(expectedPluginManager)
                .invocationId(invocationId)
                .agent(mockAgent)
                .session(session)
                .userContent(Optional.of(userContent))
                .runConfig(runConfig)
                .build();
        // Act
        PluginManager result = context.pluginManager();
        // Assert
        assertSame(expectedPluginManager, result,
                "pluginManager() should return the same instance regardless of userContent");
    }
    @Test
    @Tag("valid")
    void pluginManagerReturnedFromDeprecatedConstructor() {
        // Arrange
        PluginManager expectedPluginManager = new PluginManager();
        String invocationId = "test-invocation-id";
        @SuppressWarnings("deprecation")
        InvocationContext context = new InvocationContext(
                mockSessionService,
                mockArtifactService,
                mockMemoryService,
                expectedPluginManager,
                Optional.empty(),
                Optional.empty(),
                invocationId,
                mockAgent,
                session,
                Optional.empty(),
                runConfig,
                false
        );
        // Act
        PluginManager result = context.pluginManager();
        // Assert
        assertSame(expectedPluginManager, result,
                "pluginManager() should return the exact instance passed to the deprecated constructor");
    }
    @Test
    @Tag("valid")
    void pluginManagerReturnedFromDeprecatedConstructorWithoutPluginManager() {
        // Arrange
        String invocationId = "test-invocation-id";
        @SuppressWarnings("deprecation")
        InvocationContext context = new InvocationContext(
                mockSessionService,
                mockArtifactService,
                mockMemoryService,
                Optional.empty(),
                Optional.empty(),
                invocationId,
                mockAgent,
                session,
                Optional.empty(),
                runConfig,
                false
        );
        // Act
        PluginManager result = context.pluginManager();
        // Assert
        assertNull(result,
                "pluginManager() should return null when not passed in deprecated constructor without PluginManager");
    }
    @Test
    @Tag("integration")
    void pluginManagerAccessibleAfterMultipleContextOperations() {
        // Arrange
        PluginManager expectedPluginManager = new PluginManager();
        String invocationId = InvocationContext.newInvocationContextId();
        InvocationContext context = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .memoryService(mockMemoryService)
                .pluginManager(expectedPluginManager)
                .invocationId(invocationId)
                .agent(mockAgent)
                .session(session)
                .userContent(Optional.empty())
                .runConfig(runConfig)
                .build();
        // Act - perform multiple operations on the context
        context.setEndInvocation(true);
        context.branch("test.branch");
        context.agent(mockAgent);
        PluginManager result = context.pluginManager();
        // Assert
        assertSame(expectedPluginManager, result,
                "pluginManager() should remain accessible and unchanged after other context mutations");
        assertTrue(context.endInvocation(), "endInvocation should be set to true");
        assertTrue(context.branch().isPresent(), "branch should be set");
    }
    @Test
    @Tag("boundary")
    void pluginManagerWithMinimalBuilderConfiguration() {
        // Arrange - build with only minimum required fields plus pluginManager
        PluginManager expectedPluginManager = new PluginManager();
        InvocationContext context = InvocationContext.builder()
                .pluginManager(expectedPluginManager)
                .build();
        // Act
        PluginManager result = context.pluginManager();
        // Assert
        assertSame(expectedPluginManager, result,
                "pluginManager() should return the set instance even with minimal builder configuration");
    }
    @Test
    @Tag("boundary")
    void pluginManagerDoesNotChangeWhenCopyOfIsInvokedAndOtherFieldsAreModified() {
        // Arrange
        PluginManager expectedPluginManager = new PluginManager();
        InvocationContext originalContext = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .pluginManager(expectedPluginManager)
                .invocationId("original-id")
                .agent(mockAgent)
                .session(session)
                .userContent(Optional.empty())
                .runConfig(runConfig)
                .build();
        InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
        // Act - modify copied context's branch
        copiedContext.branch("new-branch");
        // Assert
        assertSame(expectedPluginManager, copiedContext.pluginManager(),
                "Modifying branch should not affect pluginManager reference");
        assertSame(originalContext.pluginManager(), copiedContext.pluginManager(),
                "Both original and copied contexts should share the same PluginManager");
    }
    @Test
    @Tag("valid")
    void pluginManagerEqualsCheckIncludesPluginManager() {
        // Arrange
        PluginManager pluginManager1 = new PluginManager();
        PluginManager pluginManager2 = new PluginManager();
        InvocationContext context1 = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .pluginManager(pluginManager1)
                .invocationId("test-id")
                .agent(mockAgent)
                .session(session)
                .userContent(Optional.empty())
                .runConfig(runConfig)
                .build();
        InvocationContext context2 = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .pluginManager(pluginManager2)
                .invocationId("test-id")
                .agent(mockAgent)
                .session(session)
                .userContent(Optional.empty())
                .runConfig(runConfig)
                .build();
        // Act & Assert
        assertNotEquals(context1, context2,
                "Contexts with different PluginManager instances should not be equal");
        assertSame(pluginManager1, context1.pluginManager());
        assertSame(pluginManager2, context2.pluginManager());
        assertNotSame(context1.pluginManager(), context2.pluginManager(),
                "Different PluginManager instances should not be the same reference");
    }
    @Test
    @Tag("valid")
    void pluginManagerSameInstanceResultsInEqualContexts() {
        // Arrange
        PluginManager sharedPluginManager = new PluginManager();
        InvocationContext context1 = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .pluginManager(sharedPluginManager)
                .invocationId("test-id")
                .agent(mockAgent)
                .session(session)
                .userContent(Optional.empty())
                .runConfig(runConfig)
                .build();
        InvocationContext context2 = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifact