/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=userContent_84fbf4a756
ROOST_METHOD_SIG_HASH=userContent_7428a149e0

Scenario 1: Return Present Optional When User Content Is Set With a Content Object

Details:
  TestName: userContentReturnsPresentOptionalWhenContentIsProvided
  Description: Verifies that the `userContent()` method returns a non-empty Optional when
               a valid `Content` object is supplied to the builder during construction
               of the `InvocationContext`.

Execution:
  Arrange: Create a mock or stub `Content` object. Build an `InvocationContext` using
           `InvocationContext.builder()` with `.userContent(contentObject)` set to
           the created `Content` instance. Also set the minimum required fields such as
           `sessionService`, `artifactService`, `session`, and `agent` using mocks.
  Act: Call `invocationContext.userContent()` on the constructed context.
  Assert: Use `assertTrue(invocationContext.userContent().isPresent())` to confirm
          that the returned Optional contains a value.

Validation:
  This assertion confirms that when a `Content` object is passed via the builder's
  `.userContent(Content)` method, the `userContent()` accessor correctly wraps it in
  a non-empty Optional. This is critical for downstream components that rely on the
  presence of user-provided content to drive agent invocation logic.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.genai.types.Content;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class InvocationContextUserContentTest {
  @Mock private BaseSessionService mockSessionService;
  @Mock private BaseArtifactService mockArtifactService;
  @Mock private BaseMemoryService mockMemoryService;
  @Mock private PluginManager mockPluginManager;
  @Mock private Session mockSession;
  @Mock private BaseAgent mockAgent;
  @Mock private Content mockContent;
  @Mock private RunConfig mockRunConfig;

  @BeforeEach
  void setUp() {
    when(mockSession.appName()).thenReturn("testApp");
    when(mockSession.userId()).thenReturn("testUser");
    when(mockSession.id()).thenReturn("testSessionId");
  }

  @Test
  @Tag("valid")
  void userContentReturnsPresentOptionalWhenContentIsProvided() {
    // Arrange
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId("test-invocation-id")
            .agent(mockAgent)
            .session(mockSession)
            .userContent(mockContent)
            .runConfig(mockRunConfig)
            .build();
    // Act
    Optional<Content> result = context.userContent();
    // Assert
    assertTrue(
        result.isPresent(),
        "userContent() should return a non-empty Optional when content is provided");
  }

  @Test
  @Tag("valid")
  void userContentReturnsCorrectContentObjectWhenSet() {
    // Arrange
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId("test-invocation-id")
            .agent(mockAgent)
            .session(mockSession)
            .userContent(mockContent)
            .runConfig(mockRunConfig)
            .build();
    // Act
    Optional<Content> result = context.userContent();
    // Assert
    assertTrue(result.isPresent());
    assertSame(
        mockContent,
        result.get(),
        "userContent() should return the exact same Content object that was set");
  }

  @Test
  @Tag("valid")
  void userContentReturnsEmptyOptionalWhenNullContentPassedToOptionalBuilder() {
    // Arrange
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId("test-invocation-id")
            .agent(mockAgent)
            .session(mockSession)
            .userContent(Optional.empty())
            .runConfig(mockRunConfig)
            .build();
    // Act
    Optional<Content> result = context.userContent();
    // Assert
    assertFalse(
        result.isPresent(),
        "userContent() should return an empty Optional when Optional.empty() is set");
  }

  @Test
  @Tag("valid")
  void userContentReturnsEmptyOptionalWhenNotSet() {
    // Arrange
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId("test-invocation-id")
            .agent(mockAgent)
            .session(mockSession)
            .runConfig(mockRunConfig)
            .build();
    // Act
    Optional<Content> result = context.userContent();
    // Assert
    assertFalse(
        result.isPresent(),
        "userContent() should return an empty Optional when no content was set");
  }

  @Test
  @Tag("valid")
  void userContentReturnsOptionalContainingContentWhenSetViaOptionalWrapper() {
    // Arrange
    Optional<Content> optionalContent = Optional.of(mockContent);
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId("test-invocation-id")
            .agent(mockAgent)
            .session(mockSession)
            .userContent(optionalContent)
            .runConfig(mockRunConfig)
            .build();
    // Act
    Optional<Content> result = context.userContent();
    // Assert
    assertTrue(
        result.isPresent(),
        "userContent() should return a present Optional when set via Optional.of()");
    assertSame(
        mockContent, result.get(), "userContent() should return the content wrapped in Optional");
  }

  @Test
  @Tag("valid")
  void userContentReturnsPresentOptionalWhenCreatedViaStaticCreateMethod() {
    // Arrange
    InvocationContext context =
        InvocationContext.create(
            mockSessionService,
            mockArtifactService,
            "test-invocation-id",
            mockAgent,
            mockSession,
            mockContent,
            mockRunConfig);
    // Act
    Optional<Content> result = context.userContent();
    // Assert
    assertTrue(
        result.isPresent(),
        "userContent() should return a present Optional when created via static create()");
    assertSame(
        mockContent, result.get(), "userContent() should return the expected Content object");
  }

  @Test
  @Tag("valid")
  void userContentReturnsEmptyOptionalWhenNullPassedToStaticCreateMethod() {
    // Arrange
    InvocationContext context =
        InvocationContext.create(
            mockSessionService,
            mockArtifactService,
            "test-invocation-id",
            mockAgent,
            mockSession,
            null,
            mockRunConfig);
    // Act
    Optional<Content> result = context.userContent();
    // Assert
    assertFalse(
        result.isPresent(),
        "userContent() should return empty Optional when null is passed to static create()");
  }

  @Test
  @Tag("valid")
  void userContentReturnsSameOptionalTypeNotNull() {
    // Arrange
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId("test-invocation-id")
            .agent(mockAgent)
            .session(mockSession)
            .userContent(mockContent)
            .runConfig(mockRunConfig)
            .build();
    // Act
    Optional<Content> result = context.userContent();
    // Assert
    assertNotNull(result, "userContent() should never return null; it should return Optional");
  }

  @Test
  @Tag("valid")
  void userContentReturnsNotNullWhenContentIsNotSet() {
    // Arrange
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId("test-invocation-id")
            .agent(mockAgent)
            .session(mockSession)
            .runConfig(mockRunConfig)
            .build();
    // Act
    Optional<Content> result = context.userContent();
    // Assert
    assertNotNull(
        result,
        "userContent() should never return null even when no content is set; should return Optional.empty()");
  }

  @Test
  @Tag("integration")
  void userContentIsPreservedAfterCopyOf() {
    // Arrange
    InvocationContext original =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId("test-invocation-id")
            .agent(mockAgent)
            .session(mockSession)
            .userContent(mockContent)
            .runConfig(mockRunConfig)
            .build();
    // Act
    InvocationContext copied = InvocationContext.copyOf(original);
    Optional<Content> result = copied.userContent();
    // Assert
    assertTrue(result.isPresent(), "userContent() should be preserved in copied InvocationContext");
    assertSame(
        mockContent, result.get(), "Copied context should reference the same Content object");
  }

  @Test
  @Tag("integration")
  void userContentEmptyIsPreservedAfterCopyOf() {
    // Arrange
    InvocationContext original =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId("test-invocation-id")
            .agent(mockAgent)
            .session(mockSession)
            .userContent(Optional.empty())
            .runConfig(mockRunConfig)
            .build();
    // Act
    InvocationContext copied = InvocationContext.copyOf(original);
    Optional<Content> result = copied.userContent();
    // Assert
    assertFalse(
        result.isPresent(), "Empty userContent should be preserved in copied InvocationContext");
  }

  @Test
  @Tag("boundary")
  void userContentReturnsPresentOptionalWhenExplicitlySetToOptionalOfContent() {
    // Arrange
    Content content = mock(Content.class);
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId("boundary-test-id")
            .agent(mockAgent)
            .session(mockSession)
            .userContent(Optional.of(content))
            .runConfig(mockRunConfig)
            .build();
    // Act
    Optional<Content> result = context.userContent();
    // Assert
    assertTrue(
        result.isPresent(),
        "userContent should be present when explicitly set as Optional.of(content)");
    assertEquals(content, result.get(), "userContent should return the exact content set");
  }

  @Test
  @Tag("boundary")
  void userContentReturnsEmptyOptionalWhenBuiltWithoutSetting() {
    // Arrange
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId("boundary-no-content-id")
            .agent(mockAgent)
            .session(mockSession)
            .runConfig(mockRunConfig)
            .build();
    // Act
    Optional<Content> result = context.userContent();
    // Assert
    assertEquals(
        Optional.empty(), result, "userContent should be Optional.empty() when not explicitly set");
  }

  @Test
  @Tag("valid")
  void userContentGetDoesNotThrowWhenPresent() {
    // Arrange
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId("test-invocation-id")
            .agent(mockAgent)
            .session(mockSession)
            .userContent(mockContent)
            .runConfig(mockRunConfig)
            .build();
    // Act & Assert
    assertDoesNotThrow(
        () -> {
          Optional<Content> result = context.userContent();
          result.get();
        },
        "Calling .get() on userContent() should not throw when content is present");
  }

  @Test
  @Tag("valid")
  void userContentIsConsistentAcrossMultipleCalls() {
    // Arrange
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId("test-invocation-id")
            .agent(mockAgent)
            .session(mockSession)
            .userContent(mockContent)
            .runConfig(mockRunConfig)
            .build();
    // Act
    Optional<Content> firstCall = context.userContent();
    Optional<Content> secondCall = context.userContent();
    // Assert
    assertEquals(
        firstCall, secondCall, "userContent() should return the same value on multiple calls");
    assertSame(
        firstCall.get(), secondCall.get(), "Both calls should return the same Content reference");
  }

  @Test
  @Tag("valid")
  void userContentReturnsContentSetViaDirectContentBuilder() {
    // Arrange
    Content directContent = mock(Content.class);
    InvocationContext context =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId("direct-content-id")
            .agent(mockAgent)
            .session(mockSession)
            .userContent(directContent)
            .runConfig(mockRunConfig)
            .build();
    // Act
    Optional<Content> result = context.userContent();
    // Assert
    assertTrue(
        result.isPresent(),
        "userContent() should be present when set via .userContent(Content) builder method");
    assertSame(directContent, result.get(), "userContent() should return the direct content set");
  }
}
