/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=pluginManager_009a0b1a05
ROOST_METHOD_SIG_HASH=pluginManager_3452d016c7

Scenario 1: Verify that pluginManager() returns the explicitly set PluginManager instance

Details:
  TestName: pluginManagerReturnsExplicitlySetInstance
  Description: Verifies that when a specific PluginManager instance is provided to the builder,
               the pluginManager() method returns exactly that same instance (reference equality).

Execution:
  Arrange:
    - Create a specific PluginManager instance: PluginManager expectedPluginManager = new PluginManager()
    - Build an InvocationContext using InvocationContext.builder()
        .pluginManager(expectedPluginManager)
        .build()
  Act:
    - Call invocationContext.pluginManager()
  Assert:
    - assertSame(expectedPluginManager, invocationContext.pluginManager())

Validation:
  This assertion confirms that the pluginManager() accessor returns the exact same reference
  that was injected during construction. Since pluginManager is a final field set once during
  construction, the returned object must be identical to the one provided. This is critical
  because consumers of InvocationContext rely on getting the correct plugin manager to access
  tools and plugins during agent invocation.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.genai.types.Content;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class InvocationContextPluginManagerTest {

	@Mock
	private BaseSessionService mockSessionService;

	@Mock
	private BaseArtifactService mockArtifactService;

	@Mock
	private BaseMemoryService mockMemoryService;

	@Mock
	private BaseAgent mockAgent;

	private Session session;

	private RunConfig runConfig;

	@BeforeEach
	void setUp() {
		session = Session.builder("test-session-id").appName("test-app").userId("test-user").build();
		runConfig = RunConfig.builder().build();
	}

	@Test
	@Tag("valid")
	void pluginManagerReturnsExplicitlySetInstance() {
		PluginManager expectedPluginManager = new PluginManager();
		InvocationContext invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(session)
			.userContent(Optional.empty())
			.runConfig(runConfig)
			.pluginManager(expectedPluginManager)
			.build();
		PluginManager actual = invocationContext.pluginManager();
		assertSame(expectedPluginManager, actual);
	}

	@Test
	@Tag("valid")
	void pluginManagerReturnsNullWhenNotSet() {
		InvocationContext invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(session)
			.userContent(Optional.empty())
			.runConfig(runConfig)
			.build();
		PluginManager actual = invocationContext.pluginManager();
		assertNull(actual);
	}

	@Test
	@Tag("valid")
	void pluginManagerReturnsSameInstanceOnMultipleCalls() {
		PluginManager expectedPluginManager = new PluginManager();
		InvocationContext invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(session)
			.userContent(Optional.empty())
			.runConfig(runConfig)
			.pluginManager(expectedPluginManager)
			.build();
		PluginManager first = invocationContext.pluginManager();
		PluginManager second = invocationContext.pluginManager();
		assertSame(first, second);
		assertSame(expectedPluginManager, first);
		assertSame(expectedPluginManager, second);
	}

	@Test
	@Tag("valid")
	void pluginManagerReturnedFromCopyOfIsSameInstance() {
		PluginManager expectedPluginManager = new PluginManager();
		InvocationContext original = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(session)
			.userContent(Optional.empty())
			.runConfig(runConfig)
			.pluginManager(expectedPluginManager)
			.build();
		InvocationContext copied = InvocationContext.copyOf(original);
		assertSame(expectedPluginManager, copied.pluginManager());
	}

	@Test
	@Tag("valid")
	void pluginManagerReturnedFromCopyOfWhenNullIsAlsoNull() {
		InvocationContext original = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(session)
			.userContent(Optional.empty())
			.runConfig(runConfig)
			.build();
		InvocationContext copied = InvocationContext.copyOf(original);
		assertNull(copied.pluginManager());
	}

	@Test
	@Tag("valid")
	void pluginManagerIsDistinctBetweenTwoContextsWithDifferentManagers() {
		PluginManager pluginManager1 = new PluginManager();
		PluginManager pluginManager2 = new PluginManager();
		InvocationContext context1 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("invocation-1")
			.agent(mockAgent)
			.session(session)
			.userContent(Optional.empty())
			.runConfig(runConfig)
			.pluginManager(pluginManager1)
			.build();
		InvocationContext context2 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("invocation-2")
			.agent(mockAgent)
			.session(session)
			.userContent(Optional.empty())
			.runConfig(runConfig)
			.pluginManager(pluginManager2)
			.build();
		assertSame(pluginManager1, context1.pluginManager());
		assertSame(pluginManager2, context2.pluginManager());
		assertNotSame(context1.pluginManager(), context2.pluginManager());
	}

	@Test
	@Tag("valid")
	void pluginManagerReturnedFromStaticCreateIsNull() {
		Content userContent = Content.builder().role("user").build();
		InvocationContext invocationContext = InvocationContext.create(mockSessionService, mockArtifactService,
				"test-invocation-id", mockAgent, session, userContent, runConfig);
		assertNull(invocationContext.pluginManager());
	}

	@Test
	@Tag("valid")
	void pluginManagerNotNullWhenExplicitlyProvided() {
		PluginManager pluginManager = new PluginManager();
		InvocationContext invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(session)
			.userContent(Optional.empty())
			.runConfig(runConfig)
			.pluginManager(pluginManager)
			.build();
		assertNotNull(invocationContext.pluginManager());
	}

	@Test
	@Tag("valid")
	void pluginManagerReturnedIsCorrectTypePluginManager() {
		PluginManager expectedPluginManager = new PluginManager();
		InvocationContext invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(session)
			.userContent(Optional.empty())
			.runConfig(runConfig)
			.pluginManager(expectedPluginManager)
			.build();
		PluginManager returned = invocationContext.pluginManager();
		assertNotNull(returned);
		assertInstanceOf(PluginManager.class, returned);
	}

	@Test
	@Tag("integration")
	void pluginManagerCanRegisterPluginsAfterRetrieval() {
		PluginManager pluginManager = new PluginManager();
		InvocationContext invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(session)
			.userContent(Optional.empty())
			.runConfig(runConfig)
			.pluginManager(pluginManager)
			.build();
		PluginManager retrievedManager = invocationContext.pluginManager();
		assertNotNull(retrievedManager);
		assertSame(pluginManager, retrievedManager);
	}

	@Test
	@Tag("integration")
	void pluginManagerSameAcrossOriginalAndCopiedContext() {
		PluginManager sharedPluginManager = new PluginManager();
		InvocationContext original = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(session)
			.userContent(Optional.empty())
			.runConfig(runConfig)
			.pluginManager(sharedPluginManager)
			.build();
		InvocationContext copied = InvocationContext.copyOf(original);
		assertSame(original.pluginManager(), copied.pluginManager());
		assertSame(sharedPluginManager, original.pluginManager());
		assertSame(sharedPluginManager, copied.pluginManager());
	}

	@Test
	@Tag("boundary")
	void pluginManagerIsNullByDefaultWhenBuilderNotSet() {
		InvocationContext invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("invocation-id")
			.agent(mockAgent)
			.session(session)
			.userContent(Optional.empty())
			.runConfig(runConfig)
			.build();
		assertNull(invocationContext.pluginManager());
	}

	@Test
	@Tag("boundary")
	void pluginManagerCanBeSetAfterOtherFieldsAreSet() {
		PluginManager pluginManager = new PluginManager();
		InvocationContext invocationContext = InvocationContext.builder()
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(session)
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.runConfig(runConfig)
			.userContent(Optional.empty())
			.pluginManager(pluginManager)
			.build();
		assertSame(pluginManager, invocationContext.pluginManager());
	}

	@Test
	@Tag("valid")
	void pluginManagerFieldNotModifiedByOtherContextOperations() {
		PluginManager expectedPluginManager = new PluginManager();
		InvocationContext invocationContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(session)
			.userContent(Optional.empty())
			.runConfig(runConfig)
			.pluginManager(expectedPluginManager)
			.build();
		invocationContext.setEndInvocation(true);
		invocationContext.branch("new-branch");
		invocationContext.agent(mockAgent);
		assertSame(expectedPluginManager, invocationContext.pluginManager());
	}

	@Test
	@Tag("valid")
	void pluginManagerEqualityBetweenContextsWithSamePluginManager() {
		PluginManager sharedPluginManager = new PluginManager();
		InvocationContext context1 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("invocation-1")
			.agent(mockAgent)
			.session(session)
			.userContent(Optional.empty())
			.runConfig(runConfig)
			.pluginManager(sharedPluginManager)
			.build();
		InvocationContext context2 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("invocation-1")
			.agent(mockAgent)
			.session(session)
			.userContent(Optional.empty())
			.runConfig(runConfig)
			.pluginManager(sharedPluginManager)
			.build();
		assertSame(context1.pluginManager(), context2.pluginManager());
	}

}
