/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=incrementLlmCallsCount_728a2657e3
ROOST_METHOD_SIG_HASH=incrementLlmCallsCount_ccbe51a785

Scenario 1: Successful Single LLM Call Increment Without Limit Configured

Details:
  TestName: incrementLlmCallsCountSucceedsWhenNoLimitConfigured
  Description: Verifies that calling incrementLlmCallsCount() once succeeds without throwing an exception
               when the RunConfig has no maxLlmCalls limit set (default RunConfig with maxLlmCalls <= 0).

Execution:
  Arrange:
    - Create a mock or stub for BaseSessionService, BaseArtifactService, and Session.
    - Build a RunConfig using RunConfig.builder().build() (default, which means maxLlmCalls is 0 or not set).
    - Build an InvocationContext using InvocationContext.builder()
        .sessionService(mockSessionService)
        .artifactService(mockArtifactService)
        .session(mockSession)
        .runConfig(defaultRunConfig)
        .build().
  Act:
    - Call invocationContext.incrementLlmCallsCount().
  Assert:
    - No exception is thrown (the method completes normally).

Validation:
  Verifies that when maxLlmCalls is not configured (default of 0 or negative), no limit enforcement
  occurs and the method completes without throwing LlmCallsLimitExceededException. This is important
  to ensure the system operates without restrictions when no limit is intended.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.models.LlmCallsLimitExceededException;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class InvocationContextIncrementLlmCallsCountTest {
  @Mock private BaseSessionService mockSessionService;
  @Mock private BaseArtifactService mockArtifactService;
  @Mock private BaseMemoryService mockMemoryService;
  @Mock private PluginManager mockPluginManager;
  @Mock private Session mockSession;
  @Mock private BaseAgent mockAgent;
  private static final String TEST_INVOCATION_ID = "test-invocation-id";

  @BeforeEach
  void setUp() {
    when(mockSession.appName()).thenReturn("testApp");
    when(mockSession.userId()).thenReturn("testUser");
    when(mockSession.id()).thenReturn("testSessionId");
  }

  private InvocationContext buildContext(RunConfig runConfig) {
    return InvocationContext.builder()
        .sessionService(mockSessionService)
        .artifactService(mockArtifactService)
        .invocationId(TEST_INVOCATION_ID)
        .agent(mockAgent)
        .session(mockSession)
        .userContent(Optional.empty())
        .runConfig(runConfig)
        .build();
  }

  @Test
  @Tag("valid")
  void incrementLlmCallsCountSucceedsWhenNoLimitConfigured() {
    // Arrange
    RunConfig defaultRunConfig = RunConfig.builder().setMaxLlmCalls(0).build();
    InvocationContext invocationContext = buildContext(defaultRunConfig);
    // Act & Assert
    assertDoesNotThrow(
        () -> invocationContext.incrementLlmCallsCount(),
        "incrementLlmCallsCount should not throw when maxLlmCalls is 0 (no limit)");
  }

  @Test
  @Tag("valid")
  void incrementLlmCallsCountSucceedsWithNullRunConfig() {
    // Arrange
    InvocationContext invocationContext = buildContext(null);
    // Act & Assert
    assertDoesNotThrow(
        () -> invocationContext.incrementLlmCallsCount(),
        "incrementLlmCallsCount should not throw when runConfig is null");
  }

  @Test
  @Tag("valid")
  void incrementLlmCallsCountSucceedsWithNegativeMaxLlmCalls() {
    // Arrange
    RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(-1).build();
    InvocationContext invocationContext = buildContext(runConfig);
    // Act & Assert
    assertDoesNotThrow(
        () -> invocationContext.incrementLlmCallsCount(),
        "incrementLlmCallsCount should not throw when maxLlmCalls is negative (no limit)");
  }

  @Test
  @Tag("valid")
  void incrementLlmCallsCountSucceedsWhenCallsWithinLimit() {
    // Arrange
    int maxCalls = 5;
    RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(maxCalls).build();
    InvocationContext invocationContext = buildContext(runConfig);
    // Act & Assert - call 4 times, all within limit
    assertDoesNotThrow(
        () -> {
          for (int i = 0; i < maxCalls - 1; i++) {
            invocationContext.incrementLlmCallsCount();
          }
        },
        "incrementLlmCallsCount should not throw when calls are within the limit");
  }

  @Test
  @Tag("boundary")
  void incrementLlmCallsCountSucceedsAtExactlyMaxLlmCalls() {
    // Arrange
    int maxCalls = 3;
    RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(maxCalls).build();
    InvocationContext invocationContext = buildContext(runConfig);
    // Act & Assert - call exactly maxCalls times, should not throw
    assertDoesNotThrow(
        () -> {
          for (int i = 0; i < maxCalls; i++) {
            invocationContext.incrementLlmCallsCount();
          }
        },
        "incrementLlmCallsCount should not throw when called exactly maxLlmCalls times");
  }

  @Test
  @Tag("boundary")
  void incrementLlmCallsCountThrowsWhenExceedsLimitByOne() {
    // Arrange
    int maxCalls = 3;
    RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(maxCalls).build();
    InvocationContext invocationContext = buildContext(runConfig);
    // Act - call maxCalls times without throwing
    assertDoesNotThrow(
        () -> {
          for (int i = 0; i < maxCalls; i++) {
            invocationContext.incrementLlmCallsCount();
          }
        });
    // Assert - the (maxCalls + 1)th call should throw
    assertThrows(
        LlmCallsLimitExceededException.class,
        () -> invocationContext.incrementLlmCallsCount(),
        "incrementLlmCallsCount should throw LlmCallsLimitExceededException when limit is exceeded by one");
  }

  @Test
  @Tag("invalid")
  void incrementLlmCallsCountThrowsWhenLimitExceeded() {
    // Arrange
    int maxCalls = 2;
    RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(maxCalls).build();
    InvocationContext invocationContext = buildContext(runConfig);
    // Act - exhaust the limit
    assertDoesNotThrow(
        () -> {
          for (int i = 0; i < maxCalls; i++) {
            invocationContext.incrementLlmCallsCount();
          }
        });
    // Assert
    LlmCallsLimitExceededException exception =
        assertThrows(
            LlmCallsLimitExceededException.class,
            () -> invocationContext.incrementLlmCallsCount(),
            "Should throw LlmCallsLimitExceededException when limit is exceeded");
    assertNotNull(exception.getMessage(), "Exception message should not be null");
  }

  @Test
  @Tag("invalid")
  void incrementLlmCallsCountThrowsWithCorrectMessageWhenLimitExceeded() {
    // Arrange
    int maxCalls = 1;
    RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(maxCalls).build();
    InvocationContext invocationContext = buildContext(runConfig);
    // Act - exhaust the limit
    assertDoesNotThrow(() -> invocationContext.incrementLlmCallsCount());
    // Assert
    LlmCallsLimitExceededException exception =
        assertThrows(
            LlmCallsLimitExceededException.class,
            () -> invocationContext.incrementLlmCallsCount(),
            "Should throw LlmCallsLimitExceededException with meaningful message");
    assertTrue(
        exception.getMessage().contains(String.valueOf(maxCalls)),
        "Exception message should contain the max limit value");
  }

  @Test
  @Tag("valid")
  void incrementLlmCallsCountSucceedsWithSingleCallAndHighLimit() {
    // Arrange
    int maxCalls = 500;
    RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(maxCalls).build();
    InvocationContext invocationContext = buildContext(runConfig);
    // Act & Assert
    assertDoesNotThrow(
        () -> invocationContext.incrementLlmCallsCount(),
        "A single call should succeed when maxLlmCalls is 500");
  }

  @Test
  @Tag("boundary")
  void incrementLlmCallsCountSucceedsWithMaxLlmCallsOfOne() {
    // Arrange
    RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(1).build();
    InvocationContext invocationContext = buildContext(runConfig);
    // Act & Assert - exactly 1 call should succeed
    assertDoesNotThrow(
        () -> invocationContext.incrementLlmCallsCount(),
        "First call should succeed when maxLlmCalls is 1");
  }

  @Test
  @Tag("boundary")
  void incrementLlmCallsCountThrowsOnSecondCallWhenMaxLlmCallsIsOne() {
    // Arrange
    RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(1).build();
    InvocationContext invocationContext = buildContext(runConfig);
    // Act - first call should succeed
    assertDoesNotThrow(() -> invocationContext.incrementLlmCallsCount());
    // Assert - second call should fail
    assertThrows(
        LlmCallsLimitExceededException.class,
        () -> invocationContext.incrementLlmCallsCount(),
        "Second call should throw when maxLlmCalls is 1");
  }

  @Test
  @Tag("invalid")
  void incrementLlmCallsCountThrowsMultipleTimesAfterLimitExceeded() {
    // Arrange
    int maxCalls = 2;
    RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(maxCalls).build();
    InvocationContext invocationContext = buildContext(runConfig);
    // Act - exhaust limit
    assertDoesNotThrow(
        () -> {
          for (int i = 0; i < maxCalls; i++) {
            invocationContext.incrementLlmCallsCount();
          }
        });
    // Assert - multiple subsequent calls should also throw
    assertThrows(
        LlmCallsLimitExceededException.class, () -> invocationContext.incrementLlmCallsCount());
    assertThrows(
        LlmCallsLimitExceededException.class, () -> invocationContext.incrementLlmCallsCount());
  }

  @Test
  @Tag("valid")
  void incrementLlmCallsCountEachContextHasIndependentCounter()
      throws LlmCallsLimitExceededException {
    // Arrange
    int maxCalls = 1;
    RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(maxCalls).build();
    InvocationContext context1 = buildContext(runConfig);
    InvocationContext context2 = buildContext(runConfig);
    // Act - exhaust limit in context1
    context1.incrementLlmCallsCount();
    // Assert - context2 should still work independently
    assertDoesNotThrow(
        () -> context2.incrementLlmCallsCount(),
        "context2 should have its own independent counter");
    // And context1 should throw
    assertThrows(
        LlmCallsLimitExceededException.class,
        () -> context1.incrementLlmCallsCount(),
        "context1 should throw as its limit is exceeded");
  }

  @Test
  @Tag("valid")
  void incrementLlmCallsCountWithDefaultRunConfigDoesNotThrow() {
    // Arrange
    RunConfig defaultRunConfig = RunConfig.builder().build();
    InvocationContext invocationContext = buildContext(defaultRunConfig);
    // Act & Assert - default maxLlmCalls is 500, calling once should not throw
    assertDoesNotThrow(
        () -> invocationContext.incrementLlmCallsCount(),
        "Calling incrementLlmCallsCount once with default RunConfig should not throw");
  }

  @Test
  @Tag("integration")
  void incrementLlmCallsCountWithCopiedContextSharesNoCounterState()
      throws LlmCallsLimitExceededException {
    // Arrange
    int maxCalls = 2;
    RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(maxCalls).build();
    InvocationContext originalContext = buildContext(runConfig);
    // Act - increment original context once
    originalContext.incrementLlmCallsCount();
    // Copy the context (copy should start fresh internally based on InvocationCostManager being new
    // per instance)
    InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
    // Assert - copied context should be able to make its own calls
    assertNotNull(copiedContext, "Copied context should not be null");
    assertDoesNotThrow(
        () -> copiedContext.incrementLlmCallsCount(),
        "Copied context should be able to increment LLM calls");
  }

  @Test
  @Tag("boundary")
  void incrementLlmCallsCountWithLargeMaxLlmCallsValue() {
    // Arrange
    int maxCalls = Integer.MAX_VALUE;
    RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(maxCalls).build();
    InvocationContext invocationContext = buildContext(runConfig);
    // Act & Assert - single call should be fine
    assertDoesNotThrow(
        () -> invocationContext.incrementLlmCallsCount(),
        "Should not throw with very large maxLlmCalls and a single call");
  }

  @Test
  @Tag("valid")
  void incrementLlmCallsCountDoesNotAffectOtherContextFields()
      throws LlmCallsLimitExceededException {
    // Arrange
    RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(10).build();
    InvocationContext invocationContext = buildContext(runConfig);
    String expectedInvocationId = TEST_INVOCATION_ID;
    // Act
    invocationContext.incrementLlmCallsCount();
    // Assert - other fields should remain unchanged
    assertEquals(
        expectedInvocationId,
        invocationContext.invocationId(),
        "invocationId should remain unchanged after incrementLlmCallsCount");
    assertEquals(
        mockSession,
        invocationContext.session(),
        "session should remain unchanged after incrementLlmCallsCount");
    assertEquals(
        runConfig,
        invocationContext.runConfig(),
        "runConfig should remain unchanged after incrementLlmCallsCount");
  }
}
