/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=create_a8299eaa31
ROOST_METHOD_SIG_HASH=create_95f62994c3

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/june-java-unit/1782282926/source/adk-java/core/src/test/java/com/google/adk/agents/ToolResolverTest.java
Tests:
    "@Test
public void testResolveToolInstance_fromRegistry() throws Exception {
    FunctionTool testTool = FunctionTool.create(TestToolWithMethods.class, "method1");
    testRegistry.register("test.tool.instance", testTool);
    BaseTool resolved = ToolResolver.resolveToolInstance("test.tool.instance");
    assertThat(resolved).isEqualTo(testTool);
}
"
    "@Test
public void testResolveTools_mixedTypes() throws Exception {

    FunctionTool registeredTool = FunctionTool.create(TestToolWithMethods.class, "method1");
    testRegistry.register("registered.tool", registeredTool);
    ImmutableList<BaseTool.ToolConfig> toolConfigs = ImmutableList.of(
    createToolConfig("registered.tool", null),
    createToolConfig(TestToolWithDefaultConstructor.class.getName(), null), createToolConfig(TestToolWithStaticField.class.getName() + ".INSTANCE",
    null));
    ImmutableList<BaseTool> resolved = ToolResolver.resolveTools(toolConfigs, "/test/path");
    assertThat(resolved).hasSize(3);
    assertThat(resolved.get(0)).isEqualTo(registeredTool);
    assertThat(resolved.get(1)).isInstanceOf(TestToolWithDefaultConstructor.class);
    assertThat(resolved.get(2)).isInstanceOf(TestToolWithStaticField.class);
}
"Scenario 1: Create InvocationContext With All Valid Non-Null Parameters

Details:
  TestName: createWithAllValidNonNullParameters
  Description: Verifies that the `create` method successfully constructs an `InvocationContext` when all parameters,
               including a non-null `userContent`, are provided with valid values. This confirms that each field
               is correctly assigned through the builder chain.
Execution:
  Arrange:
    - Create a mock of `BaseSessionService`.
    - Create a mock of `BaseArtifactService`.
    - Create a mock of `BaseAgent`.
    - Create a mock of `Session`.
    - Create a mock of `Content` (non-null userContent).
    - Create a mock of `RunConfig`.
    - Define a non-empty `invocationId` string (e.g., "test-invocation-id-001").
  Act:
    - Call `InvocationContext.create(sessionService, artifactService, invocationId, agent, session, userContent, runConfig)`.
  Assert:
    - Assert that the returned `InvocationContext` object is not null.
    - Assert that `context.sessionService()` equals the provided `sessionService` mock.
    - Assert that `context.artifactService()` equals the provided `artifactService` mock.
    - Assert that `context.invocationId()` equals "test-invocation-id-001".
    - Assert that `context.agent()` equals the provided `agent` mock.
    - Assert that `context.session()` equals the provided `session` mock.
    - Assert that `context.userContent()` is present and equals the provided `userContent` mock.
    - Assert that `context.runConfig()` equals the provided `runConfig` mock.
Validation:
  This test validates the primary happy-path scenario, ensuring that the factory method correctly
  delegates all provided parameters to the underlying builder and that the resulting context
  accurately reflects all supplied values. This is fundamental to the correct initialization of
  an invocation lifecycle.

*/

// ********RoostGPT********

```java
package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.genai.types.Content;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.junit.jupiter.api.*;
import com.google.adk.events.Event;
import com.google.adk.flows.llmflows.ResumabilityConfig;
import com.google.adk.models.LlmCallsLimitExceededException;
import com.google.common.collect.ImmutableSet;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import com.google.errorprone.annotations.InlineMe;
import com.google.genai.types.FunctionCall;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import javax.annotation.Nullable;

@ExtendWith(MockitoExtension.class)
public class InvocationContextCreateTest {

	@Mock
	private BaseSessionService mockSessionService;

	@Mock
	private BaseArtifactService mockArtifactService;

	@Mock
	private BaseAgent mockAgent;

	@Mock
	private Session mockSession;

	@Mock
	private Content mockUserContent;

	@Mock
	private RunConfig mockRunConfig;

	@Mock
	private BaseMemoryService mockMemoryService;

	@Mock
	private PluginManager mockPluginManager;

	private static final String VALID_INVOCATION_ID = "test-invocation-id-001";

	@BeforeEach
	void setUp() {
		// Common setup if needed
	}

	// ===== Scenario 1: Create InvocationContext With All Valid Non-Null Parameters =====
	@Test
	@Tag("valid")
	void createWithAllValidNonNullParameters() {
		// Arrange
		String invocationId = VALID_INVOCATION_ID;
		// Act
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, invocationId,
				mockAgent, mockSession, mockUserContent, mockRunConfig);
		// Assert
		assertNotNull(context);
		assertEquals(mockSessionService, context.sessionService());
		assertEquals(mockArtifactService, context.artifactService());
		assertEquals(invocationId, context.invocationId());
		assertEquals(mockAgent, context.agent());
		assertEquals(mockSession, context.session());
		assertTrue(context.userContent().isPresent());
		assertEquals(mockUserContent, context.userContent().get());
		assertEquals(mockRunConfig, context.runConfig());
	}

	// ===== Scenario 2: Create InvocationContext With Null UserContent =====
	@Test
	@Tag("valid")
	void createWithNullUserContentResultsInEmptyOptional() {
		// Arrange
		String invocationId = "test-invocation-null-content";
		// Act
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, invocationId,
				mockAgent, mockSession, null, mockRunConfig);
		// Assert
		assertNotNull(context);
		assertFalse(context.userContent().isPresent());
		assertEquals(invocationId, context.invocationId());
		assertEquals(mockSessionService, context.sessionService());
		assertEquals(mockArtifactService, context.artifactService());
		assertEquals(mockAgent, context.agent());
		assertEquals(mockSession, context.session());
		assertEquals(mockRunConfig, context.runConfig());
	}

	// ===== Scenario 3: Create InvocationContext With Null SessionService =====
	@Test
	@Tag("valid")
	void createWithNullSessionService() {
		// Arrange
		String invocationId = "test-invocation-null-session-service";
		// Act
		InvocationContext context = InvocationContext.create(null, mockArtifactService, invocationId, mockAgent,
				mockSession, mockUserContent, mockRunConfig);
		// Assert
		assertNotNull(context);
		assertNull(context.sessionService());
		assertEquals(mockArtifactService, context.artifactService());
		assertEquals(invocationId, context.invocationId());
	}

	// ===== Scenario 4: Create InvocationContext With Null ArtifactService =====
	@Test
	@Tag("valid")
	void createWithNullArtifactService() {
		// Arrange
		String invocationId = "test-invocation-null-artifact-service";
		// Act
		InvocationContext context = InvocationContext.create(mockSessionService, null, invocationId, mockAgent,
				mockSession, mockUserContent, mockRunConfig);
		// Assert
		assertNotNull(context);
		assertEquals(mockSessionService, context.sessionService());
		assertNull(context.artifactService());
		assertEquals(invocationId, context.invocationId());
	}

	// ===== Scenario 5: Create InvocationContext With Empty InvocationId =====
	@Test
	@Tag("boundary")
	void createWithEmptyInvocationId() {
		// Arrange
		String emptyInvocationId = "";
		// Act
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, emptyInvocationId,
				mockAgent, mockSession, mockUserContent, mockRunConfig);
		// Assert
		assertNotNull(context);
		assertEquals("", context.invocationId());
		assertEquals(mockSessionService, context.sessionService());
		assertEquals(mockArtifactService, context.artifactService());
	}

	// ===== Scenario 6: Create InvocationContext With Null InvocationId =====
	@Test
	@Tag("boundary")
	void createWithNullInvocationId() {
		// Arrange - null invocationId
		// Act
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, null, mockAgent,
				mockSession, mockUserContent, mockRunConfig);
		// Assert
		assertNotNull(context);
		assertNull(context.invocationId());
	}

	// ===== Scenario 7: Create InvocationContext With Null Agent =====
	@Test
	@Tag("valid")
	void createWithNullAgent() {
		// Arrange
		String invocationId = "test-invocation-null-agent";
		// Act
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, invocationId,
				null, mockSession, mockUserContent, mockRunConfig);
		// Assert
		assertNotNull(context);
		assertNull(context.agent());
		assertEquals(invocationId, context.invocationId());
	}

	// ===== Scenario 8: Create InvocationContext With Null Session =====
	@Test
	@Tag("valid")
	void createWithNullSession() {
		// Arrange
		String invocationId = "test-invocation-null-session";
		// Act
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, invocationId,
				mockAgent, null, mockUserContent, mockRunConfig);
		// Assert
		assertNotNull(context);
		assertNull(context.session());
		assertEquals(invocationId, context.invocationId());
	}

	// ===== Scenario 9: Create InvocationContext With Null RunConfig =====
	@Test
	@Tag("valid")
	void createWithNullRunConfig() {
		// Arrange
		String invocationId = "test-invocation-null-runconfig";
		// Act
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, invocationId,
				mockAgent, mockSession, mockUserContent, null);
		// Assert
		assertNotNull(context);
		assertNull(context.runConfig());
		assertEquals(invocationId, context.invocationId());
	}

	// ===== Scenario 10: Create InvocationContext With All Null Parameters =====
	@Test
	@Tag("boundary")
	void createWithAllNullParameters() {
		// Act
		InvocationContext context = InvocationContext.create(null, null, null, null, null, null, null);
		// Assert
		assertNotNull(context);
		assertNull(context.sessionService());
		assertNull(context.artifactService());
		assertNull(context.invocationId());
		assertNull(context.agent());
		assertNull(context.session());
		assertFalse(context.userContent().isPresent());
		assertNull(context.runConfig());
	}

	// ===== Scenario 11: Create InvocationContext Returns Non-Null Object =====
	@Test
	@Tag("valid")
	void createReturnsNonNullObject() {
		// Act
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService,
				VALID_INVOCATION_ID, mockAgent, mockSession, mockUserContent, mockRunConfig);
		// Assert
		assertNotNull(context, "The create method must not return null");
	}

	// ===== Scenario 12: Create InvocationContext Verifies UserContent Is Wrapped In
	// Optional =====
	@Test
	@Tag("valid")
	void createUserContentIsWrappedInOptional() {
		// Act
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService,
				VALID_INVOCATION_ID, mockAgent, mockSession, mockUserContent, mockRunConfig);
		// Assert
		assertNotNull(context.userContent());
		assertTrue(context.userContent() instanceof Optional);
		assertTrue(context.userContent().isPresent());
		assertSame(mockUserContent, context.userContent().get());
	}

	// ===== Scenario 13: Create Two InvocationContexts Are Independent =====
	@Test
	@Tag("valid")
	void createTwoContextsAreIndependent() {
		// Arrange
		BaseSessionService anotherSessionService = mock(BaseSessionService.class);
		String invocationId1 = "invocation-001";
		String invocationId2 = "invocation-002";
		// Act
		InvocationContext context1 = InvocationContext.create(mockSessionService, mockArtifactService, invocationId1,
				mockAgent, mockSession, mockUserContent, mockRunConfig);
		InvocationContext context2 = InvocationContext.create(anotherSessionService, mockArtifactService, invocationId2,
				mockAgent, mockSession, null, mockRunConfig);
		// Assert
		assertNotEquals(context1.invocationId(), context2.invocationId());
		assertNotEquals(context1.sessionService(), context2.sessionService());
		assertTrue(context1.userContent().isPresent());
		assertFalse(context2.userContent().isPresent());
	}

	// ===== Scenario 14: Create InvocationContext Has Default endInvocation False =====
	@Test
	@Tag("valid")
	void createDefaultEndInvocationIsFalse() {
		// Act
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService,
				VALID_INVOCATION_ID, mockAgent, mockSession, mockUserContent, mockRunConfig);
		// Assert
		assertFalse(context.endInvocation(), "Default endInvocation should be false");
	}

	// ===== Scenario 15: Create InvocationContext Has Empty Branch By Default =====
	@Test
	@Tag("valid")
	void createDefaultBranchIsEmpty() {
		// Act
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService,
				VALID_INVOCATION_ID, mockAgent, mockSession, mockUserContent, mockRunConfig);
		// Assert
		assertNotNull(context.branch());
		assertFalse(context.branch().isPresent(), "Default branch should be empty");
	}

	// ===== Scenario 16: Create InvocationContext Has Empty LiveRequestQueue By Default
	// =====
	@Test
	@Tag("valid")
	void createDefaultLiveRequestQueueIsEmpty() {
		// Act
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService,
				VALID_INVOCATION_ID, mockAgent, mockSession, mockUserContent, mockRunConfig);
		// Assert
		assertNotNull(context.liveRequestQueue());
		assertFalse(context.liveRequestQueue().isPresent(), "Default liveRequestQueue should be empty");
	}

	// ===== Scenario 17: Create InvocationContext Has Empty ActiveStreamingTools By
	// Default =====
	@Test
	@Tag("valid")
	void createDefaultActiveStreamingToolsIsEmpty() {
		// Act
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService,
				VALID_INVOCATION_ID, mockAgent, mockSession, mockUserContent, mockRunConfig);
		// Assert
		assertNotNull(context.activeStreamingTools());
		assertTrue(context.activeStreamingTools().isEmpty(), "Default activeStreamingTools should be empty");
	}

	// ===== Scenario 18: Create InvocationContext With Long InvocationId =====
	@Test
	@Tag("boundary")
	void createWithVeryLongInvocationId() {
		// Arrange
		StringBuilder sb = new StringBuilder();
		for (int i = 0; i < 1000; i++) {
			sb.append("x");
		}
		String longInvocationId = sb.toString();
		// Act
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, longInvocationId,
				mockAgent, mockSession, mockUserContent, mockRunConfig);
		// Assert
		assertNotNull(context);
		assertEquals(longInvocationId, context.invocationId());
		assertEquals(1000, context.invocationId().length());
	}

	// ===== Scenario 19: Create InvocationContext Invocation Id With Special Characters
	// =====
	@Test
    @Tag("boundary")
    void createWithSpecialCharactersInInvocationId() {
        // Arrange
        String specialInvocationId = "e-" + java.util.UUID.randomUUID().toString();
        // Act
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                specialInvocationId,
                mockAgent,
                mockSession,
                mockUserContent,
                mockRunConfig
        );
        // Assert
        assertNotNull(context);
        assertEquals(specialInvocationId, context.invocationId());
        assertTrue(context.invocationId().startsWith("e-"));
    }

// ===== Scenario 20: Create Two Separate Calls Return Different Instances =====
@Test
    @Tag("valid")
    void createReturnsDifferentInstancesOnMultipleCalls() {
        // Act
        InvocationContext context1 = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                VALID_INVOCATION_ID,
                mockAgent,
                mockSession,