/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=isResumable_2397941e46
ROOST_METHOD_SIG_HASH=isResumable_6fb85ad5c9

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/june-java-unit/1782282457/source/adk-java/core/src/test/java/com/google/adk/agents/InvocationContextTest.java
Tests:
    "@Test
public void isResumable_whenResumabilityConfigIsNotResumable_isFalse() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(false)).build();
    assertThat(context.isResumable()).isFalse();
}
"
    "@Test
public void isResumable_whenResumabilityConfigIsResumable_isTrue() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(true)).build();
    assertThat(context.isResumable()).isTrue();
}
"Scenario 1: Verify isResumable Returns True When ResumabilityConfig Is Explicitly Set to True

Details:
  TestName: isResumable_whenResumabilityConfigExplicitlySetToTrue_returnsTrue
  Description: Verifies that the isResumable() method returns true when the InvocationContext is built
               with a ResumabilityConfig explicitly initialized with true. This ensures that the delegation
               from InvocationContext.isResumable() to ResumabilityConfig.isResumable() works correctly
               for the positive resumable case.
Execution:
  Arrange: Create an InvocationContext using the builder, supplying all required fields (sessionService,
           artifactService, memoryService, agent, session) and setting resumabilityConfig to
           new ResumabilityConfig(true).
  Act: Call context.isResumable() on the constructed InvocationContext instance.
  Assert: Assert that the returned boolean value is true.
Validation:
  This assertion confirms that when ResumabilityConfig is set to resumable, the InvocationContext
  correctly propagates this state through its isResumable() method. This is critical for the flow
  engine to determine whether an invocation can be paused and later resumed (e.g., during long-running
  tool executions).

---

Scenario 2: Verify isResumable Returns False When ResumabilityConfig Is Explicitly Set to False

Details:
  TestName: isResumable_whenResumabilityConfigExplicitlySetToFalse_returnsFalse
  Description: Verifies that the isResumable() method returns false when the InvocationContext is built
               with a ResumabilityConfig explicitly initialized with false. This confirms correct
               delegation for the non-resumable case.
Execution:
  Arrange: Create an InvocationContext using the builder, supplying all required fields and setting
           resumabilityConfig to new ResumabilityConfig(false).
  Act: Call context.isResumable() on the constructed InvocationContext instance.
  Assert: Assert that the returned boolean value is false.
Validation:
  This assertion verifies that the InvocationContext faithfully reflects a non-resumable configuration.
  When resumability is disabled, the flow engine should not attempt to pause and resume the invocation,
  making this a critical correctness check for the shouldPauseInvocation logic which depends on isResumable().

---

Scenario 3: Verify isResumable Returns the Default Value When No ResumabilityConfig Is Provided

Details:
  TestName: isResumable_whenResumabilityConfigIsDefault_returnsDefaultResumabilityValue
  Description: Verifies that the isResumable() method returns the default value determined by the
               default ResumabilityConfig when the builder is used without explicitly setting a
               resumabilityConfig. The builder defaults resumabilityConfig to new ResumabilityConfig(),
               so the test checks that isResumable() matches what a default ResumabilityConfig provides.
Execution:
  Arrange: Create an InvocationContext using the builder, supplying all required fields (sessionService,
           artifactService, memoryService, agent, session) but NOT calling .resumabilityConfig(...),
           allowing the builder's default (new ResumabilityConfig()) to be used. Also create a
           standalone ResumabilityConfig defaultConfig = new ResumabilityConfig() to determine the
           expected value via defaultConfig.isResumable().
  Act: Call context.isResumable() on the constructed InvocationContext instance.
  Assert: Assert that context.isResumable() equals defaultConfig.isResumable().
Validation:
  This test ensures that when no explicit resumability configuration is provided, the InvocationContext
  behaves consistently with the default ResumabilityConfig. This guards against regressions if the
  default value of ResumabilityConfig changes, as the InvocationContext should always reflect whatever
  the default configuration dictates.

---

Scenario 4: Verify isResumable Consistency After Copying InvocationContext with Resumable Config

Details:
  TestName: isResumable_whenInvocationContextCopiedWithResumableConfig_returnsTrueOnCopy
  Description: Verifies that when an InvocationContext with a resumable ResumabilityConfig is copied
               using InvocationContext.copyOf(), the resulting copy also returns true for isResumable().
               This tests that the copyOf() method correctly preserves the resumabilityConfig field.
Execution:
  Arrange: Create an original InvocationContext using the builder with resumabilityConfig set to
           new ResumabilityConfig(true) along with all required fields. Then create a copy using
           InvocationContext.copyOf(original).
  Act: Call copiedContext.isResumable() on the copied InvocationContext instance.
  Assert: Assert that the returned boolean value is true.
Validation:
  This assertion verifies that InvocationContext.copyOf() faithfully copies the resumabilityConfig,
  ensuring that copied contexts used in sub-agent delegations or flow branching maintain the same
  resumability state as the original context. Inconsistency here could cause unexpected behavior
  in multi-agent orchestration scenarios.

---

Scenario 5: Verify isResumable Consistency After Copying InvocationContext with Non-Resumable Config

Details:
  TestName: isResumable_whenInvocationContextCopiedWithNonResumableConfig_returnsFalseOnCopy
  Description: Verifies that when an InvocationContext with a non-resumable ResumabilityConfig is
               copied using InvocationContext.copyOf(), the resulting copy also returns false for
               isResumable(). This tests that copyOf() does not inadvertently change the resumability
               state.
Execution:
  Arrange: Create an original InvocationContext using the builder with resumabilityConfig set to
           new ResumabilityConfig(false) along with all required fields. Then create a copy using
           InvocationContext.copyOf(original).
  Act: Call copiedContext.isResumable() on the copied InvocationContext instance.
  Assert: Assert that the returned boolean value is false.
Validation:
  This assertion confirms that copying a non-resumable InvocationContext does not accidentally enable
  resumability on the copy. This is important for preserving consistent behavior across all copies of
  the context, particularly when the agent delegates to sub-agents while maintaining a non-resumable
  configuration.

---

Scenario 6: Verify isResumable Is Independent of Other InvocationContext Fields

Details:
  TestName: isResumable_whenOtherFieldsVaryButResumabilityConfigIsTrue_alwaysReturnsTrue
  Description: Verifies that the return value of isResumable() depends solely on the ResumabilityConfig
               and is not affected by other fields of InvocationContext such as endInvocation, branch,
               or userContent.
Execution:
  Arrange: Create two InvocationContext instances using the builder, both with resumabilityConfig set
           to new ResumabilityConfig(true), but differing in other fields: the first with
           endInvocation(false) and no branch set, the second with endInvocation(true) and a
           branch("some-branch") set. Both use the same required services, agent, and session.
  Act: Call isResumable() on both instances.
  Assert: Assert that both instances return true for isResumable().
Validation:
  This test confirms that isResumable() is a pure function of the ResumabilityConfig field and is
  not influenced by the state of other fields. This verifies the separation of concerns in the
  InvocationContext design and ensures predictable behavior of the resumability feature regardless
  of the overall invocation state.

---

Scenario 7: Verify isResumable Returns False When Other Context Fields Are Set and ResumabilityConfig Is False

Details:
  TestName: isResumable_whenEndInvocationTrueAndResumabilityConfigFalse_returnsFalse
  Description: Verifies that even when endInvocation is set to true and other fields are populated,
               isResumable() still returns false when ResumabilityConfig is set to false. This ensures
               the method's return value is not coupled to the endInvocation flag.
Execution:
  Arrange: Create an InvocationContext using the builder with all required fields, setting
           endInvocation(true), branch("test-branch"), and resumabilityConfig to
           new ResumabilityConfig(false).
  Act: Call context.isResumable() on the constructed InvocationContext instance.
  Assert: Assert that the returned boolean value is false.
Validation:
  This test validates that the isResumable() method exclusively delegates to ResumabilityConfig
  and is not inadvertently affected by the endInvocation state or branch fields. This is important
  because endInvocation and resumability are orthogonal concepts — an invocation that has ended
  is distinct from one that is non-resumable.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.when;

import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.flows.llmflows.ResumabilityConfig;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
class InvocationContextIsResumableTest {

	@Mock
	private BaseSessionService mockSessionService;

	@Mock
	private BaseArtifactService mockArtifactService;

	@Mock
	private BaseMemoryService mockMemoryService;

	@Mock
	private BaseAgent mockAgent;

	@Mock
	private Session mockSession;

	@BeforeEach
  void setUp() {
    when(mockSession.appName()).thenReturn("testApp");
    when(mockSession.userId()).thenReturn("testUser");
  }

	private InvocationContext.Builder baseBuilder() {
		return InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("test-invocation-id")
			.userContent(Optional.empty())
			.runConfig(RunConfig.builder().build());
	}

	@Test
	@Tag("valid")
	void isResumable_whenResumabilityConfigExplicitlySetToTrue_returnsTrue() {
		// Arrange
		ResumabilityConfig resumabilityConfig = new ResumabilityConfig(true);
		InvocationContext context = baseBuilder().resumabilityConfig(resumabilityConfig).build();
		// Act
		boolean result = context.isResumable();
		// Assert
		assertTrue(result, "isResumable() should return true when ResumabilityConfig is set to true");
	}

	@Test
	@Tag("valid")
	void isResumable_whenResumabilityConfigExplicitlySetToFalse_returnsFalse() {
		// Arrange
		ResumabilityConfig resumabilityConfig = new ResumabilityConfig(false);
		InvocationContext context = baseBuilder().resumabilityConfig(resumabilityConfig).build();
		// Act
		boolean result = context.isResumable();
		// Assert
		assertFalse(result, "isResumable() should return false when ResumabilityConfig is set to false");
	}

	@Test
	@Tag("boundary")
	void isResumable_whenResumabilityConfigIsDefault_returnsDefaultResumabilityValue() {
		// Arrange
		ResumabilityConfig defaultConfig = new ResumabilityConfig();
		InvocationContext context = baseBuilder().resumabilityConfig(defaultConfig).build();
		// Act
		boolean result = context.isResumable();
		// Assert
		assertEquals(defaultConfig.isResumable(), result,
				"isResumable() should match the default ResumabilityConfig's isResumable() value");
	}

	@Test
	@Tag("integration")
	void isResumable_whenInvocationContextCopiedWithResumableConfig_returnsTrueOnCopy() {
		// Arrange
		ResumabilityConfig resumabilityConfig = new ResumabilityConfig(true);
		InvocationContext original = baseBuilder().resumabilityConfig(resumabilityConfig).build();
		InvocationContext copiedContext = InvocationContext.copyOf(original);
		// Act
		boolean result = copiedContext.isResumable();
		// Assert
		assertTrue(result,
				"isResumable() should return true on copied InvocationContext when original had ResumabilityConfig(true)");
	}

	@Test
	@Tag("integration")
	void isResumable_whenInvocationContextCopiedWithNonResumableConfig_returnsFalseOnCopy() {
		// Arrange
		ResumabilityConfig resumabilityConfig = new ResumabilityConfig(false);
		InvocationContext original = baseBuilder().resumabilityConfig(resumabilityConfig).build();
		InvocationContext copiedContext = InvocationContext.copyOf(original);
		// Act
		boolean result = copiedContext.isResumable();
		// Assert
		assertFalse(result,
				"isResumable() should return false on copied InvocationContext when original had ResumabilityConfig(false)");
	}

	@Test
	@Tag("valid")
	void isResumable_whenOtherFieldsVaryButResumabilityConfigIsTrue_alwaysReturnsTrue() {
		// Arrange
		ResumabilityConfig resumabilityConfig = new ResumabilityConfig(true);
		InvocationContext contextWithDefaultFields = baseBuilder().resumabilityConfig(resumabilityConfig)
			.endInvocation(false)
			.build();
		InvocationContext contextWithVariedFields = baseBuilder().resumabilityConfig(resumabilityConfig)
			.endInvocation(true)
			.branch("some-branch")
			.build();
		// Act
		boolean resultDefault = contextWithDefaultFields.isResumable();
		boolean resultVaried = contextWithVariedFields.isResumable();
		// Assert
		assertTrue(resultDefault, "isResumable() should return true regardless of endInvocation=false and no branch");
		assertTrue(resultVaried, "isResumable() should return true regardless of endInvocation=true and branch set");
	}

	@Test
	@Tag("invalid")
	void isResumable_whenEndInvocationTrueAndResumabilityConfigFalse_returnsFalse() {
		// Arrange
		ResumabilityConfig resumabilityConfig = new ResumabilityConfig(false);
		InvocationContext context = baseBuilder().resumabilityConfig(resumabilityConfig)
			.endInvocation(true)
			.branch("test-branch")
			.build();
		// Act
		boolean result = context.isResumable();
		// Assert
		assertFalse(result,
				"isResumable() should return false even when endInvocation=true and branch is set, if ResumabilityConfig is false");
	}

	@Test
	@Tag("valid")
	void isResumable_whenResumabilityConfigTrueAndCopyPreservesResumability_bothOriginalAndCopyReturnTrue() {
		// Arrange
		ResumabilityConfig resumabilityConfig = new ResumabilityConfig(true);
		InvocationContext original = baseBuilder().resumabilityConfig(resumabilityConfig).build();
		InvocationContext copy = InvocationContext.copyOf(original);
		// Act
		boolean originalResult = original.isResumable();
		boolean copyResult = copy.isResumable();
		// Assert
		assertTrue(originalResult, "Original context isResumable() should return true");
		assertTrue(copyResult, "Copied context isResumable() should also return true");
		assertEquals(originalResult, copyResult,
				"Original and copied context should have the same isResumable() value");
	}

	@Test
	@Tag("valid")
	void isResumable_whenResumabilityConfigFalseAndCopyPreservesNonResumability_bothOriginalAndCopyReturnFalse() {
		// Arrange
		ResumabilityConfig resumabilityConfig = new ResumabilityConfig(false);
		InvocationContext original = baseBuilder().resumabilityConfig(resumabilityConfig).build();
		InvocationContext copy = InvocationContext.copyOf(original);
		// Act
		boolean originalResult = original.isResumable();
		boolean copyResult = copy.isResumable();
		// Assert
		assertFalse(originalResult, "Original context isResumable() should return false");
		assertFalse(copyResult, "Copied context isResumable() should also return false");
		assertEquals(originalResult, copyResult,
				"Original and copied context should have the same isResumable() value");
	}

	@Test
	@Tag("boundary")
	void isResumable_whenMultipleContextsWithDifferentResumabilityConfigs_returnCorrectValues() {
		// Arrange
		ResumabilityConfig trueConfig = new ResumabilityConfig(true);
		ResumabilityConfig falseConfig = new ResumabilityConfig(false);
		InvocationContext resumableContext = baseBuilder().resumabilityConfig(trueConfig).build();
		InvocationContext nonResumableContext = baseBuilder().resumabilityConfig(falseConfig).build();
		// Act
		boolean resumableResult = resumableContext.isResumable();
		boolean nonResumableResult = nonResumableContext.isResumable();
		// Assert
		assertTrue(resumableResult, "Context with ResumabilityConfig(true) should return true");
		assertFalse(nonResumableResult, "Context with ResumabilityConfig(false) should return false");
	}

	@Test
	@Tag("valid")
	void isResumable_whenResumabilityConfigTrueWithMemoryServiceAndPluginManager_returnsTrue() {
		// Arrange
		ResumabilityConfig resumabilityConfig = new ResumabilityConfig(true);
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("test-invocation-with-memory")
			.userContent(Optional.empty())
			.runConfig(RunConfig.builder().build())
			.resumabilityConfig(resumabilityConfig)
			.build();
		// Act
		boolean result = context.isResumable();
		// Assert
		assertTrue(result, "isResumable() should return true with all services set and ResumabilityConfig(true)");
	}

	@Test
	@Tag("boundary")
	void isResumable_whenDefaultResumabilityConfigMatchesExpectedDefault() {
		// Arrange
		ResumabilityConfig defaultConfig1 = new ResumabilityConfig();
		ResumabilityConfig defaultConfig2 = new ResumabilityConfig();
		InvocationContext context1 = baseBuilder().resumabilityConfig(defaultConfig1).build();
		InvocationContext context2 = baseBuilder().resumabilityConfig(defaultConfig2).build();
		// Act
		boolean result1 = context1.isResumable();
		boolean result2 = context2.isResumable();
		// Assert
		assertEquals(result1, result2,
				"Two contexts with default ResumabilityConfig should return the same isResumable() value");
		assertEquals(defaultConfig1.isResumable(), result1,
				"Context isResumable() should match standalone default ResumabilityConfig.isResumable()");
	}

}
