/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=liveRequestQueue_752dd14d55
ROOST_METHOD_SIG_HASH=liveRequestQueue_66d4c7a2b5

Scenario 1: Return Present Optional When LiveRequestQueue Is Explicitly Set

Details:
  TestName: liveRequestQueueReturnsPresentOptionalWhenQueueIsSet
  Description: Verifies that the liveRequestQueue() method returns a non-empty Optional when a LiveRequestQueue
               instance is explicitly provided to the builder during InvocationContext construction.
Execution:
  Arrange: Create a mock or real LiveRequestQueue instance. Use InvocationContext.builder() and call
           .liveRequestQueue(liveRequestQueueInstance) to set the queue. Also set all other required fields
           (sessionService, artifactService, agent, session, runConfig). Call .build() to produce the context.
  Act: Invoke context.liveRequestQueue() on the built InvocationContext instance.
  Assert: Use assertTrue(context.liveRequestQueue().isPresent()) to confirm the Optional is not empty.
          Use assertEquals(liveRequestQueueInstance, context.liveRequestQueue().get()) to confirm the same
          instance is returned.
Validation:
  This assertion verifies that when a LiveRequestQueue is provided through the builder, the method correctly
  wraps it in a non-empty Optional and returns it. This is critical for live/streaming agent interactions
  where the queue is the communication channel between the client and the agent runtime.

*/

// ********RoostGPT********

```java
package com.google.adk.agents;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.events.Event;
import com.google.adk.flows.llmflows.ResumabilityConfig;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.models.LlmCallsLimitExceededException;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.common.collect.ImmutableSet;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import com.google.genai.types.Content;
import com.google.genai.types.FunctionCall;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import javax.annotation.Nullable;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.junit.jupiter.api.*;
import com.google.errorprone.annotations.InlineMe;

@ExtendWith(MockitoExtension.class)
public class InvocationContextLiveRequestQueueTest {
    @Mock
    private BaseSessionService mockSessionService;
    @Mock
    private BaseArtifactService mockArtifactService;
    @Mock
    private BaseMemoryService mockMemoryService;
    @Mock
    private PluginManager mockPluginManager;
    @Mock
    private BaseAgent mockAgent;
    private Session mockSession;
    private RunConfig runConfig;
    @BeforeEach
    void setUp() {
        mockSession = Session.builder("test-session-id")
                .appName("test-app")
                .userId("test-user")
                .build();
        runConfig = RunConfig.builder().build();
    }
    // -----------------------------------------------------------------------
    // Scenario 1: Return Present Optional When LiveRequestQueue Is Explicitly Set
    // -----------------------------------------------------------------------
    @Test
    @Tag("valid")
    void liveRequestQueueReturnsPresentOptionalWhenQueueIsSet() {
        // Arrange
        LiveRequestQueue liveRequestQueueInstance = new LiveRequestQueue();
        InvocationContext context = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .agent(mockAgent)
                .session(mockSession)
                .liveRequestQueue(Optional.of(liveRequestQueueInstance))
                .runConfig(runConfig)
                .build();
        // Act
        Optional<LiveRequestQueue> result = context.liveRequestQueue();
        // Assert
        assertTrue(result.isPresent(), "LiveRequestQueue Optional should be present when queue is set");
        assertEquals(liveRequestQueueInstance, result.get(), "The returned LiveRequestQueue should be the same instance that was set");
    }
    // -----------------------------------------------------------------------
    // Scenario 2: Return Empty Optional When LiveRequestQueue Is Not Set
    // -----------------------------------------------------------------------
    @Test
    @Tag("valid")
    void liveRequestQueueReturnsEmptyOptionalWhenQueueIsNotSet() {
        // Arrange
        InvocationContext context = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .agent(mockAgent)
                .session(mockSession)
                .runConfig(runConfig)
                .build();
        // Act
        Optional<LiveRequestQueue> result = context.liveRequestQueue();
        // Assert
        assertNotNull(result, "liveRequestQueue() should never return null, even when not set");
        assertFalse(result.isPresent(), "LiveRequestQueue Optional should be empty when queue was not set");
    }
    // -----------------------------------------------------------------------
    // Scenario 3: Return Empty Optional When LiveRequestQueue Is Explicitly Set to Empty Optional
    // -----------------------------------------------------------------------
    @Test
    @Tag("valid")
    void liveRequestQueueReturnsEmptyOptionalWhenExplicitlySetToEmpty() {
        // Arrange
        InvocationContext context = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .agent(mockAgent)
                .session(mockSession)
                .liveRequestQueue(Optional.empty())
                .runConfig(runConfig)
                .build();
        // Act
        Optional<LiveRequestQueue> result = context.liveRequestQueue();
        // Assert
        assertNotNull(result, "liveRequestQueue() should never return null");
        assertFalse(result.isPresent(), "LiveRequestQueue Optional should be empty when explicitly set to Optional.empty()");
    }
    // -----------------------------------------------------------------------
    // Scenario 4: Return Present Optional When Using the Direct LiveRequestQueue Builder Method
    // -----------------------------------------------------------------------
    @Test
    @Tag("valid")
    void liveRequestQueueReturnsPresentOptionalWhenSetViaDirectBuilderMethod() {
        // Arrange
        LiveRequestQueue liveRequestQueueInstance = new LiveRequestQueue();
        InvocationContext context = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .agent(mockAgent)
                .session(mockSession)
                .liveRequestQueue(liveRequestQueueInstance)
                .runConfig(runConfig)
                .build();
        // Act
        Optional<LiveRequestQueue> result = context.liveRequestQueue();
        // Assert
        assertTrue(result.isPresent(), "LiveRequestQueue Optional should be present when queue is set via direct builder method");
        assertSame(liveRequestQueueInstance, result.get(), "The returned LiveRequestQueue should be the same instance");
    }
    // -----------------------------------------------------------------------
    // Scenario 5: Return Same LiveRequestQueue After CopyOf
    // -----------------------------------------------------------------------
    @Test
    @Tag("valid")
    void liveRequestQueueIsCopiedCorrectlyViaCopyOf() {
        // Arrange
        LiveRequestQueue liveRequestQueueInstance = new LiveRequestQueue();
        InvocationContext original = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .agent(mockAgent)
                .session(mockSession)
                .liveRequestQueue(Optional.of(liveRequestQueueInstance))
                .runConfig(runConfig)
                .build();
        // Act
        InvocationContext copied = InvocationContext.copyOf(original);
        // Assert
        assertTrue(copied.liveRequestQueue().isPresent(), "Copied context should have the LiveRequestQueue present");
        assertSame(liveRequestQueueInstance, copied.liveRequestQueue().get(), "Copied context should reference the same LiveRequestQueue instance");
    }
    // -----------------------------------------------------------------------
    // Scenario 6: LiveRequestQueue Not Present After CopyOf When Original Has None
    // -----------------------------------------------------------------------
    @Test
    @Tag("valid")
    void liveRequestQueueIsEmptyAfterCopyOfWhenOriginalHasNone() {
        // Arrange
        InvocationContext original = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .agent(mockAgent)
                .session(mockSession)
                .runConfig(runConfig)
                .build();
        // Act
        InvocationContext copied = InvocationContext.copyOf(original);
        // Assert
        assertNotNull(copied.liveRequestQueue(), "liveRequestQueue() should not return null after copyOf");
        assertFalse(copied.liveRequestQueue().isPresent(), "Copied context should have empty LiveRequestQueue when original had none");
    }
    // -----------------------------------------------------------------------
    // Scenario 7: liveRequestQueue() Returns non-null Result (Integration)
    // -----------------------------------------------------------------------
    @Test
    @Tag("integration")
    void liveRequestQueueReturnNonNullOptionalAlways() {
        // Arrange
        InvocationContext contextWithQueue = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .agent(mockAgent)
                .session(mockSession)
                .liveRequestQueue(new LiveRequestQueue())
                .runConfig(runConfig)
                .build();
        InvocationContext contextWithoutQueue = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .agent(mockAgent)
                .session(mockSession)
                .runConfig(runConfig)
                .build();
        // Act & Assert
        assertNotNull(contextWithQueue.liveRequestQueue(), "liveRequestQueue() should not return null when set");
        assertNotNull(contextWithoutQueue.liveRequestQueue(), "liveRequestQueue() should not return null when not set");
    }
    // -----------------------------------------------------------------------
    // Scenario 8: LiveRequestQueue Presence Verified via Static create Method
    // -----------------------------------------------------------------------
    @Test
    @Tag("valid")
    void liveRequestQueueReturnsPresentOptionalWhenContextCreatedViaStaticCreate() {
        // Arrange
        LiveRequestQueue liveRequestQueueInstance = new LiveRequestQueue();
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                mockAgent,
                mockSession,
                liveRequestQueueInstance,
                runConfig
        );
        // Act
        Optional<LiveRequestQueue> result = context.liveRequestQueue();
        // Assert
        assertTrue(result.isPresent(), "LiveRequestQueue Optional should be present when created via static create method");
        assertSame(liveRequestQueueInstance, result.get(), "The returned LiveRequestQueue should be the same instance passed to create");
    }
    // -----------------------------------------------------------------------
    // Scenario 9: LiveRequestQueue Is Empty When Created With Null via Static create Method
    // -----------------------------------------------------------------------
    @Test
    @Tag("boundary")
    void liveRequestQueueReturnsEmptyOptionalWhenNullPassedToStaticCreate() {
        // Arrange
        InvocationContext context = InvocationContext.create(
                mockSessionService,
                mockArtifactService,
                mockAgent,
                mockSession,
                (LiveRequestQueue) null,
                runConfig
        );
        // Act
        Optional<LiveRequestQueue> result = context.liveRequestQueue();
        // Assert
        assertNotNull(result, "liveRequestQueue() should not return null");
        assertFalse(result.isPresent(), "LiveRequestQueue Optional should be empty when null is passed to static create");
    }
    // -----------------------------------------------------------------------
    // Scenario 10: Two Contexts With Same Queue Are Equal
    // -----------------------------------------------------------------------
    @Test
    @Tag("valid")
    void twoContextsWithSameLiveRequestQueueAreEqual() {
        // Arrange
        LiveRequestQueue liveRequestQueueInstance = new LiveRequestQueue();
        InvocationContext context1 = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .agent(mockAgent)
                .session(mockSession)
                .liveRequestQueue(Optional.of(liveRequestQueueInstance))
                .invocationId("test-invocation-id")
                .runConfig(runConfig)
                .build();
        InvocationContext context2 = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .agent(mockAgent)
                .session(mockSession)
                .liveRequestQueue(Optional.of(liveRequestQueueInstance))
                .invocationId("test-invocation-id")
                .runConfig(runConfig)
                .build();
        // Act & Assert
        assertEquals(context1.liveRequestQueue(), context2.liveRequestQueue(),
                "Two contexts configured with the same LiveRequestQueue should return equal Optionals");
    }
    // -----------------------------------------------------------------------
    // Scenario 11: LiveRequestQueue Present When Using Optional Wrapper Builder
    // -----------------------------------------------------------------------
    @Test
    @Tag("valid")
    void liveRequestQueueReturnsPresentWhenSetViaOptionalWrapperBuilder() {
        // Arrange
        LiveRequestQueue liveRequestQueueInstance = new LiveRequestQueue();
        Optional<LiveRequestQueue> optionalQueue = Optional.of(liveRequestQueueInstance);
        InvocationContext context = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .agent(mockAgent)
                .session(mockSession)
                .liveRequestQueue(optionalQueue)
                .runConfig(runConfig)
                .build();
        // Act
        Optional<LiveRequestQueue> result = context.liveRequestQueue();
        // Assert
        assertTrue(result.isPresent(), "Optional should be present");
        assertEquals(optionalQueue, result, "The returned Optional should equal the one set via builder");
    }
    // -----------------------------------------------------------------------
    // Scenario 12: LiveRequestQueue Is Consistent Across Multiple Calls
    // -----------------------------------------------------------------------
    @Test
    @Tag("valid")
    void liveRequestQueueReturnsSameInstanceOnMultipleCalls() {
        // Arrange
        LiveRequestQueue liveRequestQueueInstance = new LiveRequestQueue();
        InvocationContext context = InvocationContext.builder()
                .sessionService(mockSessionService)
                .artifactService(mockArtifactService)
                .agent(mockAgent)
                .session(mockSession)
                .liveRequestQueue(Optional.of(liveRequestQueueInstance))
                .runConfig(runConfig)
                .build();
        // Act
        Optional<LiveRequestQueue> firstCall = context.liveRequestQueue();
        Optional<LiveRequestQueue> secondCall = context.liveRequestQueue();
        // Assert
        assertEquals(firstCall, secondCall, "Multiple calls to liveRequestQueue() should return consistent results");
        assertSame(firstCall.get(), secondCall.get(), "Multiple calls should return the same LiveRequestQueue instance");
    }
    // -----------------------------------------------------------------------
    // Scenario 13: liveRequestQueue() With Deprecated Constructor
    // -----------------------------------------------------------------------
    @SuppressWarnings("deprecation")
    @Test
    @Tag("boundary")
    void liveRequestQueueReturnsPresentOptionalWhenSetViaDeprecatedConstructor() {
        // Arrange
        LiveRequestQueue liveRequestQueueInstance = new LiveRequestQueue();
        Optional<LiveRequestQueue> optionalQueue = Optional.of(liveRequestQueueInstance);
        InvocationContext context = new InvocationContext(
                mockSessionService,
                mockArtifactService,
                mockMemoryService,
                mockPluginManager,
                optionalQueue,
                Optional.empty(),
                "test-invocation-id",
                mockAgent,
                mockSession,
                Optional.empty(),
                runConfig,
                false
        );
        // Act
        Optional<LiveRequestQueue> result = context.liveRequestQueue();
        // Assert
        assertTrue(result.isPresent(), "LiveRequestQueue Optional should be present when set via deprecated constructor");
        assertSame(liveRequestQueueInstance, result.get(), "The returned instance should be same as set via deprecated constructor");
    }
    // -----------------------------------------------------------------------
    // Scenario 14: Empty LiveRequestQueue via Deprecated Constructor
    // -----------------------------------------------------------------------
    @SuppressWarnings("deprecation")
    @Test
    @Tag("boundary")
    void liveRequestQueueReturnsEmptyOptionalWhenEmptyOptionalPassedViaDeprecatedConstructor() {
        // Arrange
        InvocationContext context = new InvocationContext(
                mockSessionService,
                mockArtifactService,
                mockMemoryService,
                mockPluginManager,
                Optional.empty(),
                Optional.empty(),
                "test-invocation-id",
                mockAgent,
                mockSession,
                Optional.empty(),
                runConfig,
                false
        );