/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=memoryService_1115878a43
ROOST_METHOD_SIG_HASH=memoryService_b8500b83f5

Scenario 1: Return Non-Null Memory Service When Explicitly Set Via Builder

Details:
  TestName: memoryServiceReturnsNonNullInstanceWhenSetViaBuilder
  Description: Verifies that the memoryService() method returns the exact BaseMemoryService instance
               that was provided to the builder during construction of InvocationContext. This ensures
               that the field assignment and retrieval work correctly end-to-end through the builder.
Execution:
  Arrange: Create a mock or concrete implementation of BaseMemoryService. Use InvocationContext.builder()
           and call .memoryService(mockedMemoryService) along with other required fields
           (sessionService, artifactService, agent, session) to construct a valid InvocationContext instance.
  Act: Call invocationContext.memoryService() on the constructed InvocationContext instance.
  Assert: Use assertEquals or assertSame to verify that the returned BaseMemoryService instance
          is the same object reference as the one passed into the builder.
Validation:
  This assertion confirms that the private final field memoryService is correctly assigned during
  construction and accurately returned by the accessor method. It is critical to verify that the
  builder properly wires the dependency through to the final object, ensuring other components
  that rely on memoryService() receive the correct service instance.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.genai.types.Content;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
class InvocationContextMemoryServiceTest {

	@Mock
	private BaseSessionService mockSessionService;

	@Mock
	private BaseArtifactService mockArtifactService;

	@Mock
	private BaseMemoryService mockMemoryService;

	@Mock
	private BaseAgent mockAgent;

	@Mock
	private Session mockSession;

	@Mock
	private RunConfig mockRunConfig;

	@Mock
	private PluginManager mockPluginManager;

	@BeforeEach
  void setUp() {
    when(mockSession.appName()).thenReturn("testApp");
    when(mockSession.userId()).thenReturn("testUser");
  }

	@Test
	@Tag("valid")
	void memoryServiceReturnsNonNullInstanceWhenSetViaBuilder() {
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("test-invocation-id")
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		BaseMemoryService result = context.memoryService();
		assertNotNull(result);
		assertSame(mockMemoryService, result);
	}

	@Test
	@Tag("valid")
	void memoryServiceReturnsSameReferenceAsProvided() {
		BaseMemoryService anotherMockMemoryService = mock(BaseMemoryService.class);
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(anotherMockMemoryService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("test-invocation-id-2")
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		BaseMemoryService result = context.memoryService();
		assertSame(anotherMockMemoryService, result);
	}

	@Test
	@Tag("valid")
	void memoryServiceReturnsNullWhenNotSetViaBuilder() {
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("test-invocation-id-3")
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		BaseMemoryService result = context.memoryService();
		assertNull(result);
	}

	@Test
	@Tag("valid")
	void memoryServiceIsConsistentAcrossMultipleCalls() {
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("test-invocation-id-4")
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		BaseMemoryService firstCall = context.memoryService();
		BaseMemoryService secondCall = context.memoryService();
		BaseMemoryService thirdCall = context.memoryService();
		assertSame(firstCall, secondCall);
		assertSame(secondCall, thirdCall);
		assertSame(mockMemoryService, firstCall);
	}

	@Test
	@Tag("valid")
	void memoryServiceReturnedFromCreateStaticFactoryMethod() {
		Content userContent = mock(Content.class);
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService,
				"test-invocation-id-5", mockAgent, mockSession, userContent, mockRunConfig);
		BaseMemoryService result = context.memoryService();
		assertNull(result);
	}

	@Test
	@Tag("valid")
	void memoryServicePreservedInCopyOf() {
		InvocationContext originalContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("original-invocation-id")
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
		assertSame(mockMemoryService, copiedContext.memoryService());
		assertSame(originalContext.memoryService(), copiedContext.memoryService());
	}

	@Test
	@Tag("valid")
	void memoryServiceNotSharedBetweenDifferentContexts() {
		BaseMemoryService firstMemoryService = mock(BaseMemoryService.class);
		BaseMemoryService secondMemoryService = mock(BaseMemoryService.class);
		InvocationContext context1 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(firstMemoryService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("invocation-id-1")
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		InvocationContext context2 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(secondMemoryService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("invocation-id-2")
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		assertSame(firstMemoryService, context1.memoryService());
		assertSame(secondMemoryService, context2.memoryService());
		assertNotSame(context1.memoryService(), context2.memoryService());
	}

	@Test
	@Tag("valid")
	void memoryServiceSetViaBuilderMethodIsImmutableAfterBuild() {
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("immutable-test-id")
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		BaseMemoryService beforeModAttempt = context.memoryService();
		assertSame(mockMemoryService, beforeModAttempt);
		assertSame(mockMemoryService, context.memoryService());
	}

	@Test
	@Tag("integration")
	void memoryServiceAccessibleAlongsideOtherServicesInContext() {
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.pluginManager(mockPluginManager)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("integration-test-id")
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		assertSame(mockMemoryService, context.memoryService());
		assertSame(mockSessionService, context.sessionService());
		assertSame(mockArtifactService, context.artifactService());
		assertSame(mockPluginManager, context.pluginManager());
	}

	@Test
	@Tag("valid")
	void memoryServicePreservedWhenBuilderOverridesOtherFields() {
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.pluginManager(mockPluginManager)
			.branch(Optional.of("test-branch"))
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("branch-test-id")
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.endInvocation(false)
			.build();
		assertSame(mockMemoryService, context.memoryService());
	}

	@Test
	@Tag("boundary")
	void memoryServiceNullIsReturnedWhenBuilderDoesNotSetIt() {
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("null-memory-service-id")
			.runConfig(mockRunConfig)
			.build();
		assertNull(context.memoryService());
	}

	@Test
	@Tag("integration")
	void memoryServicePreservedAfterCopyOfWithNullOriginalMemoryService() {
		InvocationContext originalContext = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("copy-null-memory-id")
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
		assertNull(copiedContext.memoryService());
		assertEquals(originalContext.memoryService(), copiedContext.memoryService());
	}

	@Test
	@Tag("valid")
	void memoryServiceEqualityInContextEqualsMethod() {
		InvocationContext context1 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("equals-test-id")
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		InvocationContext context2 = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId("equals-test-id")
			.userContent(Optional.empty())
			.runConfig(mockRunConfig)
			.build();
		assertEquals(context1.memoryService(), context2.memoryService());
	}

	@Test
	@Tag("valid")
	void memoryServiceSetViaBuilderWithAllRequiredFields() {
		String invocationId = "full-context-test-id";
		Content userContent = mock(Content.class);
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.agent(mockAgent)
			.session(mockSession)
			.invocationId(invocationId)
			.userContent(Optional.of(userContent))
			.runConfig(mockRunConfig)
			.build();
		BaseMemoryService result = context.memoryService();
		assertNotNull(result);
		assertSame(mockMemoryService, result);
		assertEquals(invocationId, context.invocationId());
	}

}
