/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=session_a0f90dafba
ROOST_METHOD_SIG_HASH=session_a2fc7a867d

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/june-java-unit/1782282457/source/adk-java/core/src/test/java/com/google/adk/agents/InvocationContextTest.java
Tests:
    "@Test
public void testCreateWithUserContent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).isEmpty();
    assertThat(context.invocationId()).isEqualTo(testInvocationId);
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).hasValue(userContent);
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testCreateWithNullUserContent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.userContent()).isEmpty();
}
"
    "@Test
public void testCreateWithLiveRequestQueue() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).liveRequestQueue(liveRequestQueue).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).hasValue(liveRequestQueue);

    assertThat(context.invocationId()).startsWith("e-");
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).isEmpty();
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testCopyOf() {
    InvocationContext originalContext = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    originalContext.activeStreamingTools().putAll(activeStreamingTools);
    InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
    assertThat(copiedContext).isNotNull();
    assertThat(copiedContext).isNotSameInstanceAs(originalContext);
    assertThat(copiedContext.sessionService()).isEqualTo(originalContext.sessionService());
    assertThat(copiedContext.artifactService()).isEqualTo(originalContext.artifactService());
    assertThat(copiedContext.memoryService()).isEqualTo(originalContext.memoryService());
    assertThat(copiedContext.liveRequestQueue()).isEqualTo(originalContext.liveRequestQueue());
    assertThat(copiedContext.invocationId()).isEqualTo(originalContext.invocationId());
    assertThat(copiedContext.agent()).isEqualTo(originalContext.agent());
    assertThat(copiedContext.session()).isEqualTo(originalContext.session());
    assertThat(copiedContext.userContent()).isEqualTo(originalContext.userContent());
    assertThat(copiedContext.runConfig()).isEqualTo(originalContext.runConfig());
    assertThat(copiedContext.endInvocation()).isEqualTo(originalContext.endInvocation());
    assertThat(copiedContext.activeStreamingTools()).isEqualTo(originalContext.activeStreamingTools());
}
"
    "@Test
public void testGetters() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).isEmpty();
    assertThat(context.invocationId()).isEqualTo(testInvocationId);
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).hasValue(userContent);
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testSetAgent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    BaseAgent newMockAgent = mock(BaseAgent.class);
    context.agent(newMockAgent);
    assertThat(context.agent()).isEqualTo(newMockAgent);
}
"
    "@Test
public void testEquals_sameObject() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(context)).isTrue();
}
"
    "@Test
public void testEquals_null() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(null)).isFalse();
}
"
    "@Test
public void testEquals_sameValues() {
    InvocationContext context1 = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext context2 = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context1.equals(context2)).isTrue();

    assertThat(context2.equals(context1)).isTrue();
}
"
    "@Test
public void testEquals_differentValues() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext contextWithDiffSessionService = InvocationContext.builder().sessionService(
    mock(BaseSessionService.class)).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffInvocationId = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(
    "another-id").agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffAgent = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(
    mock(BaseAgent.class)).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithUserContentEmpty = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithLiveQueuePresent = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).liveRequestQueue(liveRequestQueue).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(contextWithDiffSessionService)).isFalse();
    assertThat(context.equals(contextWithDiffInvocationId)).isFalse();
    assertThat(context.equals(contextWithDiffAgent)).isFalse();
    assertThat(context.equals(contextWithUserContentEmpty)).isFalse();
    assertThat(context.equals(contextWithLiveQueuePresent)).isFalse();
}
"
    "@Test
public void testHashCode_differentValues() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext contextWithDiffSessionService = InvocationContext.builder().sessionService(
    mock(BaseSessionService.class)).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffInvocationId = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(
    "another-id").agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotEqualTo(contextWithDiffSessionService);
    assertThat(context).isNotEqualTo(contextWithDiffInvocationId);
}
"
    "@Test
public void isResumable_whenResumabilityConfigIsNotResumable_isFalse() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(false)).build();
    assertThat(context.isResumable()).isFalse();
}
"
    "@Test
public void isResumable_whenResumabilityConfigIsResumable_isTrue() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(true)).build();
    assertThat(context.isResumable()).isTrue();
}
"
    "@Test
public void shouldPauseInvocation_whenNotResumable_isFalse() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(false)).build();
    Event event = Event.builder().longRunningToolIds(Optional.of(ImmutableSet.of("fc1"))).content(Content.builder().parts(ImmutableList.of(Part.builder().functionCall(FunctionCall.builder().name("tool1").id("fc1").build()).build())).build()).build();
    assertThat(context.shouldPauseInvocation(event)).isFalse();
}
"
    "@Test
public void shouldPauseInvocation_whenResumableAndNoLongRunningToolIds_isFalse() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(true)).build();
    Event event = Event.builder().content(Content.builder().parts(ImmutableList.of(Part.builder().functionCall(FunctionCall.builder().name("tool1").id("fc1").build()).build())).build()).build();
    assertThat(context.shouldPauseInvocation(event)).isFalse();
}
"
    "@Test
public void shouldPauseInvocation_whenResumableAndNoFunctionCalls_isFalse() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(true)).build();
    Event event = Event.builder().longRunningToolIds(Optional.of(ImmutableSet.of("fc1"))).build();
    assertThat(context.shouldPauseInvocation(event)).isFalse();
}
"
    "@Test
public void shouldPauseInvocation_whenResumableAndNoMatchingFunctionCallId_isFalse() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(true)).build();
    Event event = Event.builder().longRunningToolIds(Optional.of(ImmutableSet.of("fc2"))).content(Content.builder().parts(ImmutableList.of(Part.builder().functionCall(FunctionCall.builder().name("tool1").id("fc1").build()).build())).build()).build();
    assertThat(context.shouldPauseInvocation(event)).isFalse();
}
"
    "@Test
public void shouldPauseInvocation_whenResumableAndMatchingFunctionCallId_isTrue() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).agent(mockAgent).session(session).resumabilityConfig(new ResumabilityConfig(true)).build();
    Event event = Event.builder().longRunningToolIds(Optional.of(ImmutableSet.of("fc1"))).content(Content.builder().parts(ImmutableList.of(Part.builder().functionCall(FunctionCall.builder().name("tool1").id("fc1").build()).build())).build()).build();
    assertThat(context.shouldPauseInvocation(event)).isTrue();
}
"

File Path: /var/tmp/Roost/RoostGPT/june-java-unit/1782282457/source/adk-java/core/src/test/java/com/google/adk/agents/CallbacksTest.java
Tests:
    "@Test
public void testRun_withBeforeAgentCallback_returnsNothing() {
    Content modelContent = Content.fromParts(Part.fromText("Real LLM response"));
    TestLlm testLlm = createTestLlm(createLlmResponse(modelContent));
    LlmAgent agent = createTestAgentBuilder(testLlm).beforeAgentCallback(callbackContext -> Maybe.empty()).build();
    InvocationContext invocationContext = createInvocationContext(agent);
    List<Event> events = agent.runAsync(invocationContext).toList().blockingGet();
    Map<String, Object> finalState = invocationContext.session().state();

    assertThat(events).hasSize(1);
    assertThat(events.get(0).content()).hasValue(modelContent);
    assertThat(events.get(0).actions().stateDelta()).isEmpty();
    assertThat(finalState).isEmpty();
}
"
    "@Test
public void testRun_withBeforeAgentCallback_returnsContent() {
    Content modelContent = Content.fromParts(Part.fromText("Real LLM response"));
    TestLlm testLlm = createTestLlm(createLlmResponse(modelContent));
    Content beforeAgentContent = Content.fromParts(Part.fromText("before agent content"));
    LlmAgent agent = createTestAgentBuilder(testLlm).beforeAgentCallback(callbackContext -> {
        Object unused = callbackContext.state().put("before_key", "before_value");
        return Maybe.just(beforeAgentContent);
    }).build();
    InvocationContext invocationContext = createInvocationContext(agent);
    List<Event> events = agent.runAsync(invocationContext).toList().blockingGet();
    Map<String, Object> finalState = invocationContext.session().state();

    assertThat(events).hasSize(1);
    assertThat(events.get(0).content()).hasValue(beforeAgentContent);
    assertThat(events.get(0).actions().stateDelta()).containsExactly("before_key", "before_value");
    assertThat(finalState).containsEntry("before_key", "before_value");
}
"
    "@Test
public void testRun_withBeforeAgentCallback_modifiesStateOnly() {
    Content modelContent = Content.fromParts(Part.fromText("Real LLM response"));
    TestLlm testLlm = createTestLlm(createLlmResponse(modelContent));
    LlmAgent agent = createTestAgentBuilder(testLlm).beforeAgentCallback(callbackContext -> {
        Object unused = callbackContext.state().put("before_key", "before_value");

        return Maybe.empty();
    }).build();
    InvocationContext invocationContext = createInvocationContext(agent);
    List<Event> events = agent.runAsync(invocationContext).toList().blockingGet();
    Map<String, Object> finalState = invocationContext.session().state();

    assertThat(events).hasSize(2);


    assertThat(events.get(0).content().flatMap(Content::parts)).isEmpty();
    assertThat(events.get(0).actions().stateDelta()).containsExactly("before_key", "before_value");

    assertThat(events.get(1).content()).hasValue(modelContent);
    assertThat(events.get(1).actions().stateDelta()).isEmpty();
    assertThat(finalState).containsEntry("before_key", "before_value");
}
"
    "@Test
public void testRun_agentCallback_modifyStateAndOverrideResponse() {
    Content modelContent = Content.fromParts(Part.fromText("Real LLM response"));
    TestLlm testLlm = createTestLlm(createLlmResponse(modelContent));
    LlmAgent agent = createTestAgentBuilder(testLlm).beforeAgentCallback(callbackContext -> {
        Object unused = callbackContext.state().put("before_key", "before_value");
        return Maybe.empty();
    }).afterAgentCallback(callbackContext -> {
        Object unused = callbackContext.state().put("after_key", "after_value");
        return Maybe.just(Content.fromParts(Part.fromText("after agent content")));
    }).build();
    InvocationContext invocationContext = createInvocationContext(agent);
    List<Event> events = agent.runAsync(invocationContext).toList().blockingGet();
    Map<String, Object> finalState = invocationContext.session().state();
    assertThat(events).hasSize(3);
    assertThat(events.get(0).content().flatMap(Content::parts)).isEmpty();
    assertThat(events.get(0).actions().stateDelta()).containsExactly("before_key", "before_value");
    assertThat(events.get(1).content()).hasValue(modelContent);
    assertThat(events.get(1).actions().stateDelta()).isEmpty();
    assertThat(events.get(2).content().get().parts().get().get(0).text()).hasValue("after agent content");
    assertThat(events.get(2).actions().stateDelta()).containsExactly("after_key", "after_value");
    assertThat(finalState).containsEntry("before_key", "before_value");
    assertThat(finalState).containsEntry("after_key", "after_value");
}
"
    "@Test
public void testRun_withMultipleBeforeAgentCallbacks_firstReturnsContent() {
    Content modelContent = Content.fromParts(Part.fromText("Real LLM response"));
    Content beforeAgentContent1 = Content.fromParts(Part.fromText("before agent content 1"));
    Content beforeAgentContent2 = Content.fromParts(Part.fromText("before agent content 2"));
    TestLlm testLlm = createTestLlm(createLlmResponse(modelContent));
    Callbacks.BeforeAgentCallbackSync cb1 = callbackContext -> {
        var unused = callbackContext.state().put("key1", "value1");
        return Optional.of(beforeAgentContent1);
    };
    Callbacks.BeforeAgentCallback cb2 = callbackContext -> {
        var unused = callbackContext.state().put("key2", "value2");
        return Maybe.just(beforeAgentContent2);
    };
    LlmAgent agent = createTestAgentBuilder(testLlm).beforeAgentCallback(ImmutableList.of(cb1, cb2)).build();
    InvocationContext invocationContext = createInvocationContext(agent);
    List<Event> events = agent.runAsync(invocationContext).toList().blockingGet();
    Map<String, Object> finalState = invocationContext.session().state();
    assertThat(events).hasSize(1);
    Event event1 = events.get(0);
    assertThat(event1.content()).hasValue(beforeAgentContent1);
    assertThat(event1.actions().stateDelta()).containsExactly("key1", "value1");
    assertThat(finalState).containsExactly("key1", "value1");
    assertThat(testLlm.getRequests()).isEmpty();
}
"
    "@Test
public void testRun_withMultipleBeforeAgentCallbacks_allModifyState_noneReturnContent() {
    Content modelContent = Content.fromParts(Part.fromText("Real LLM response"));
    TestLlm testLlm = createTestLlm(createLlmResponse(modelContent));
    Callbacks.BeforeAgentCallbackSync cb1 = callbackContext -> {
        var unused = callbackContext.state().put("key1", "value1");
        return Optional.empty();
    };
    Callbacks.BeforeAgentCallback cb2 = callbackContext -> {
        var unused = callbackContext.state().put("key2", "value2");
        return Maybe.empty();
    };
    LlmAgent agent = createTestAgentBuilder(testLlm).beforeAgentCallback(ImmutableList.of(cb1, cb2)).build();
    InvocationContext invocationContext = createInvocationContext(agent);
    List<Event> events = agent.runAsync(invocationContext).toList().blockingGet();
    Map<String, Object> finalState = invocationContext.session().state();
    assertThat(events).hasSize(2);
    Event event1 = events.get(0);
    assertThat(event1.content().flatMap(Content::parts)).isEmpty();
    assertThat(event1.actions().stateDelta()).containsExactly("key1", "value1", "key2", "value2");
    Event event2 = events.get(1);
    assertThat(event2.content()).hasValue(modelContent);
    assertThat(event2.actions().stateDelta()).isEmpty();
    assertThat(finalState).containsExactly("key1", "value1", "key2", "value2");
    assertThat(testLlm.getRequests()).hasSize(1);
}
"
    "@Test
public void testRun_withMultipleAfterAgentCallbacks_firstReturnsContent() {
    Content modelContent = Content.fromParts(Part.fromText("Real LLM response"));
    Content afterAgentContent1 = Content.fromParts(Part.fromText("after agent content 1"));
    Content afterAgentContent2 = Content.fromParts(Part.fromText("after agent content 2"));
    TestLlm testLlm = createTestLlm(createLlmResponse(modelContent));
    Callbacks.AfterAgentCallbackSync cb1 = callbackContext -> {
        var unused = callbackContext.state().put("key1", "value1");
        return Optional.of(afterAgentContent1);
    };
    Callbacks.AfterAgentCallback cb2 = callbackContext -> {
        var unused = callbackContext.state().put("key2", "value2");
        return Maybe.just(afterAgentContent2);
    };
    LlmAgent agent = createTestAgentBuilder(testLlm).afterAgentCallback(ImmutableList.of(cb1, cb2)).build();
    InvocationContext invocationContext = createInvocationContext(agent);
    List<Event> events = agent.runAsync(invocationContext).toList().blockingGet();
    Map<String, Object> finalState = invocationContext.session().state();
    assertThat(events).hasSize(2);
    Event event1 = events.get(0);
    assertThat(event1.content()).hasValue(modelContent);
    assertThat(event1.actions().stateDelta()).isEmpty();
    Event event2 = events.get(1);
    assertThat(event2.content()).hasValue(afterAgentContent1);
    assertThat(event2.actions().stateDelta()).containsExactly("key1", "value1");
    assertThat(finalState).containsExactly("key1", "value1");
    assertThat(testLlm.getRequests()).hasSize(1);
}
"
    "@Test
public void testRun_withMultipleAfterAgentCallbacks_allModifyState_noneReturnContent() {
    Content modelContent = Content.fromParts(Part.fromText("Real LLM response"));
    TestLlm testLlm = createTestLlm(createLlmResponse(modelContent));
    Callbacks.AfterAgentCallbackSync cb1 = callbackContext -> {
        var unused = callbackContext.state().put("key1", "value1");
        return Optional.empty();
    };
    Callbacks.AfterAgentCallback cb2 = callbackContext -> {
        var unused = callbackContext.state().put("key2", "value2");
        return Maybe.empty();
    };
    LlmAgent agent = createTestAgentBuilder(testLlm).afterAgentCallback(ImmutableList.of(cb1, cb2)).build();
    InvocationContext invocationContext = createInvocationContext(agent);
    List<Event> events = agent.runAsync(invocationContext).toList().blockingGet();
    Map<String, Object> finalState = invocationContext.session().state();
    assertThat(events).hasSize(2);
    Event event1 = events.get(0);
    assertThat(event1.content()).hasValue(modelContent);
    assertThat(event1.actions().stateDelta()).isEmpty();
    Event event2 = events.get(1);
    assertThat(event2.content().flatMap(Content::parts)).isEmpty();
    assertThat(event2.actions().stateDelta()).containsExactly("key1", "value1", "key2", "value2");
    assertThat(finalState).containsExactly("key1", "value1", "key2", "value2");
    assertThat(testLlm.getRequests()).hasSize(1);
}
"
    "@Test
public void handleFunctionCalls_withChainedToolCallbacks_overridesResultAndPassesContext() {
    ImmutableMap<String, Object> originalToolInputArgs = ImmutableMap.of("input_key", "input_value");
    ImmutableMap<String, Object> stateAddedByBc2 = ImmutableMap.of("bc2_state_key", "bc2_state_value");
    ImmutableMap<String, Object> responseFromAc2 = ImmutableMap.of("ac2_response_key", "ac2_response_value");
    Callbacks.BeforeToolCallbackSync bc1 = (invCtx, toolName, args, currentToolCtx) -> Optional.empty();
    Callbacks.BeforeToolCallbackSync bc2 = (invCtx, toolName, args, currentToolCtx) -> {
        currentToolCtx.state().putAll(stateAddedByBc2);
        return Optional.empty();
    };
    TestUtils.EchoTool echoTool = new TestUtils.EchoTool();
    Callbacks.AfterToolCallbackSync ac1 = (invCtx, toolName, args, currentToolCtx, responseFromTool) -> Optional.empty();
    Callbacks.AfterToolCallbackSync ac2 = (invCtx, toolName, args, currentToolCtx, responseFromTool) -> Optional.of(responseFromAc2);
    InvocationContext invocationContext = createInvocationContext(createTestAgentBuilder(createTestLlm(LlmResponse.builder().build())).beforeToolCallback(ImmutableList.of(bc1, bc2)).afterToolCallback(ImmutableList.of(ac1, ac2)).build());
    Event eventWithFunctionCall = createEvent("event").toBuilder().content(createFunctionCallContent("fc_id_minimal", "echo_tool", originalToolInputArgs)).build();
    Event functionResponseEvent = Functions.handleFunctionCalls(invocationContext, eventWithFunctionCall, ImmutableMap.of("echo_tool", echoTool)).blockingGet();
    assertThat(getFunctionResponse(functionResponseEvent)).isEqualTo(responseFromAc2);
    assertThat(invocationContext.session().state()).containsExactlyEntriesIn(stateAddedByBc2);
}
"

File Path: /var/tmp/Roost/RoostGPT/june-java-unit/1782282457/source/adk-java/core/src/test/java/com/google/adk/agents/SequentialAgentTest.java
Tests:
    "@Test
public void runAsync_propagatesInvocationContextToSubAgents() {
    TestBaseAgent subAgent = createSubAgent("subAgent");
    SequentialAgent sequentialAgent = SequentialAgent.builder().name("seqAgent").subAgents(ImmutableList.of(subAgent)).build();
    InvocationContext parentContext = createInvocationContext(sequentialAgent);
    List<Event> unused = sequentialAgent.runAsync(parentContext).toList().blockingGet();
    InvocationContext capturedContext = subAgent.getLastInvocationContext();
    assertThat(capturedContext).isNotNull();
    assertThat(capturedContext.invocationId()).isEqualTo(parentContext.invocationId());
    assertThat(capturedContext.session()).isEqualTo(parentContext.session());
    assertThat(capturedContext.agent()).isEqualTo(subAgent);
    assertThat(subAgent.getInvocationCount()).isEqualTo(1);
}
"
    "@Test
public void runLive_propagatesInvocationContextToSubAgents() {
    TestBaseAgent subAgent = createSubAgent("subAgent_live");
    SequentialAgent sequentialAgent = SequentialAgent.builder().name("seqAgentLive").subAgents(ImmutableList.of(subAgent)).build();
    InvocationContext parentContext = createInvocationContext(sequentialAgent);
    List<Event> unused = sequentialAgent.runLive(parentContext).toList().blockingGet();
    InvocationContext capturedContext = subAgent.getLastInvocationContext();
    assertThat(capturedContext).isNotNull();
    assertThat(capturedContext.invocationId()).isEqualTo(parentContext.invocationId());
    assertThat(capturedContext.session()).isEqualTo(parentContext.session());
    assertThat(capturedContext.agent()).isEqualTo(subAgent);
    assertThat(subAgent.getInvocationCount()).isEqualTo(1);
}
"Scenario 1: Verify That session() Returns the Session Object Set During Construction

Details:
  TestName: sessionReturnsSessionSetDuringConstruction
  Description: Verifies that the session() method returns the exact Session instance that was provided to the builder when constructing the InvocationContext. This is the primary happy-path scenario for the session() accessor.
Execution:
  Arrange:
    - Create a mock Session object (e.g., mockSession).
    - Create a mock BaseSessionService, BaseArtifactService, and BaseMemoryService.
    - Build an InvocationContext using InvocationContext.builder() with the mocked session assigned via .session(mockSession).
  Act:
    - Invoke context.session() on the built InvocationContext.
  Assert:
    - assertThat(context.session()).isEqualTo(mockSession);
Validation:
  This assertion confirms that the session() accessor faithfully returns the Session instance stored in the private final field during object construction. Since the field is final and set only once via the builder, the returned object must be identical to the one supplied. This is foundational to the correct operation of any downstream logic that relies on session state, user ID, or app name.


Scenario 2: Verify That session() Does Not Return Null When a Valid Session Is Provided

Details:
  TestName: sessionDoesNotReturnNullWhenSessionIsProvided
  Description: Verifies that the session() method never returns null when a non-null Session object has been supplied through the builder. This guards against accidental null returns that could cause NullPointerExceptions in callers.
Execution:
  Arrange:
    - Create a mock Session object.
    - Build an InvocationContext via InvocationContext.builder() providing the mock session.
  Act:
    - Call context.session().
  Assert:
    - assertThat(context.session()).isNotNull();
Validation:
  The session field is final and assigned from the builder value. Asserting non-null ensures the accessor does not accidentally transform or discard the value. This test protects against regressions where a null-returning code path might be inadvertently introduced.


Scenario 3: Verify That session() Returns the Same Instance Across Multiple Calls (Idempotency)

Details:
  TestName: sessionReturnsSameInstanceOnRepeatedCalls
  Description: Verifies that multiple successive calls to session() on the same InvocationContext instance always return the same Session object, confirming the accessor is idempotent and consistent.
Execution:
  Arrange:
    - Create a mock Session object.
    - Build an InvocationContext via InvocationContext.builder() providing the mock session.
  Act:
    - Call context.session() twice, storing the results as firstCall and secondCall.
  Assert:
    - assertThat(firstCall).isSameInstanceAs(secondCall);
Validation:
  Since session is a private final field with no mutation path, every call to session() must return the identical object reference. This test confirms referential equality (same instance), not just value equality. Idempotency here is critical because many parts of the agent framework retrieve the session repeatedly and must observe a stable reference.


Scenario 4: Verify That session() Returns the Correct Session Object When a CopyOf Context Is Created

Details:
  TestName: sessionReturnsSameSessionAfterCopyOf
  Description: Verifies that after creating a copy of an InvocationContext using InvocationContext.copyOf(), the session() method on the copied context returns the same Session instance as the original, confirming that copyOf performs a shallow copy of the session field.
Execution:
  Arrange:
    - Create a mock Session object.
    - Build an original InvocationContext via InvocationContext.builder() with the mock session.
    - Create a copied context via InvocationContext.copyOf(originalContext).
  Act:
    - Call copiedContext.session().
  Assert:
    - assertThat(copiedContext.session()).isSameInstanceAs(originalContext.session());
Validation:
  The copyOf() method is documented to produce a shallow copy. Therefore, both the original and copied contexts must share the exact same Session reference. This is important because sub-agents and forked invocation paths should operate on the same session state unless explicitly provided with a different one.


Scenario 5: Verify That session() Returns the Correct Session When Multiple InvocationContexts Are Built With Different Sessions

Details:
  TestName: sessionReturnsDifferentSessionsForDifferentContexts
  Description: Verifies that two separately built InvocationContext instances each return their own respective Session objects from session(), with no cross-contamination between instances.
Execution:
  Arrange:
    - Create two distinct mock Session objects: mockSession1 and mockSession2.
    - Build context1 using InvocationContext.builder() with mockSession1.
    - Build context2 using InvocationContext.builder() with mockSession2.
  Act:
    - Call context1.session() and context2.session().
  Assert:
    - assertThat(context1.session()).isEqualTo(mockSession1);
    - assertThat(context2.session()).isEqualTo(mockSession2);
    - assertThat(context1.session()).isNotSameInstanceAs(context2.session());
Validation:
  This test confirms that InvocationContext instances are fully independent with respect to their session field. Each builder call produces an isolated object, so session data from one invocation cannot bleed into another. This is critical for multi-tenant or multi-session execution environments.


Scenario 6: Verify That session() Is Consistent With the Session Returned by appName() and userId() Accessors

Details:
  TestName: sessionIsConsistentWithAppNameAndUserId
  Description: Verifies that the Session object returned by session() is the same instance whose appName() and userId() are exposed by the InvocationContext's own appName() and userId() delegate methods, confirming internal consistency.
Execution:
  Arrange:
    - Create a mock Session configured to return a known appName (e.g., "testApp") and userId (e.g., "testUser").
    - Build an InvocationContext with this mock session.
  Act:
    - Call context.session(), context.appName(), and context.userId().
  Assert:
    - assertThat(context.appName()).isEqualTo(context.session().appName());
    - assertThat(context.userId()).isEqualTo(context.session().userId());
Validation:
  The InvocationContext delegates appName() and userId() directly to the session field. This test verifies that the object returned by session() is the authoritative source of those values, and that there is no discrepancy between reading from the session directly versus reading via the context's convenience accessors.


Scenario 7: Verify That session() Returns the Session Object When the Context Is Built Without Optional Fields

Details:
  TestName: sessionReturnedWhenContextBuiltWithMinimalRequiredFields
  Description: Verifies that session() correctly returns the supplied Session even when the InvocationContext is constructed with only the minimal required fields (sessionService, artifactService, memoryService, agent, session) and all optional fields are left at their defaults.
Execution:
  Arrange:
    - Create mocks for BaseSessionService, BaseArtifactService, BaseMemoryService, BaseAgent, and Session.
    - Build an InvocationContext using only the minimal required builder fields.
  Act:
    - Call context.session().
  Assert:
    - assertThat(context.session()).isNotNull();
    - assertThat(context.session()).isEqualTo(mockSession);
Validation:
  Confirms that the session() accessor works correctly irrespective of whether optional fields like liveRequestQueue, userContent, branch, or runConfig are set. This tests the robustness of the accessor in minimal-configuration scenarios, which are common in unit tests for agent flows.


Scenario 8: Verify That session() Returns the Correct Session After Agent Is Reassigned on the Context

Details:
  TestName: sessionRemainsUnchangedAfterAgentReassignment
  Description: Verifies that calling context.agent(newAgent) to reassign the agent on an InvocationContext does not affect the value returned by session(). The session field is final and must remain stable even when other mutable fields are updated.
Execution:
  Arrange:
    - Create a mock Session, mock BaseAgent (mockAgent), and a new mock BaseAgent (newMockAgent).
    - Build an InvocationContext with mockAgent and the mock session.
    - Call context.agent(newMockAgent) to mutate the agent field.
  Act:
    - Call context.session() after the agent reassignment.
  Assert:
    - assertThat(context.session()).isEqualTo(mockSession);
Validation:
  Since session is a private final field, it cannot be changed after construction. Mutating the agent field must not affect the session. This test ensures that the immutability contract of the session field is upheld even as other mutable parts of InvocationContext are modified during an invocation lifecycle.


Scenario 9: Verify That session() Returns the Correct Session After endInvocation State Is Changed

Details:
  TestName: sessionRemainsUnchangedAfterEndInvocationIsSet
  Description: Verifies that calling context.setEndInvocation(true) to signal the end of the invocation does not affect the Session object returned by session(). The session field must remain stable throughout the lifecycle of the context.
Execution:
  Arrange:
    - Create a mock Session and build an InvocationContext with endInvocation set to false.
    - Call context.setEndInvocation(true) to simulate ending the invocation.
  Act:
    - Call context.session().
  Assert:
    - assertThat(context.session()).isEqualTo(mockSession);
    - assertThat(context.endInvocation()).isTrue();
Validation:
  This scenario confirms that the session field is unaffected by lifecycle mutations such as ending the invocation. It validates the independence of the final session field from mutable state fields, ensuring that even in terminal states, session data remains accessible and accurate.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static com.google.common.truth.Truth.assertThat;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.flows.llmflows.ResumabilityConfig;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.genai.types.Content;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class InvocationContextSessionTest {

	@Mock
	private BaseSessionService mockSessionService;

	@Mock
	private BaseArtifactService mockArtifactService;

	@Mock
	private BaseMemoryService mockMemoryService;

	@Mock
	private PluginManager mockPluginManager;

	@Mock
	private Session mockSession;

	@Mock
	private BaseAgent mockAgent;

	@Mock
	private RunConfig mockRunConfig;

	@BeforeEach
  void setUp() {
    when(mockRunConfig.maxLlmCalls()).thenReturn(500);
  }

	private InvocationContext buildMinimalContext(Session session) {
		return InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.agent(mockAgent)
			.session(session)
			.runConfig(mockRunConfig)
			.invocationId("test-invocation-id")
			.build();
	}

	@Test
	@Tag("valid")
	void sessionReturnsSessionSetDuringConstruction() {
		// Arrange
		InvocationContext context = buildMinimalContext(mockSession);
		// Act
		Session result = context.session();
		// Assert
		assertThat(result).isEqualTo(mockSession);
	}

	@Test
	@Tag("valid")
	void sessionDoesNotReturnNullWhenSessionIsProvided() {
		// Arrange
		InvocationContext context = buildMinimalContext(mockSession);
		// Act
		Session result = context.session();
		// Assert
		assertThat(result).isNotNull();
	}

	@Test
	@Tag("valid")
	void sessionReturnsSameInstanceOnRepeatedCalls() {
		// Arrange
		InvocationContext context = buildMinimalContext(mockSession);
		// Act
		Session firstCall = context.session();
		Session secondCall = context.session();
		// Assert
		assertThat(firstCall).isSameInstanceAs(secondCall);
	}

	@Test
	@Tag("valid")
	void sessionReturnsSameSessionAfterCopyOf() {
		// Arrange
		InvocationContext originalContext = buildMinimalContext(mockSession);
		// Act
		InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
		// Assert
		assertThat(copiedContext.session()).isSameInstanceAs(originalContext.session());
	}

	@Test
	@Tag("valid")
	void sessionReturnsDifferentSessionsForDifferentContexts() {
		// Arrange
		Session mockSession1 = mock(Session.class);
		Session mockSession2 = mock(Session.class);
		InvocationContext context1 = buildMinimalContext(mockSession1);
		InvocationContext context2 = buildMinimalContext(mockSession2);
		// Act
		Session result1 = context1.session();
		Session result2 = context2.session();
		// Assert
		assertThat(result1).isEqualTo(mockSession1);
		assertThat(result2).isEqualTo(mockSession2);
		assertThat(result1).isNotSameInstanceAs(result2);
	}

	@Test
	@Tag("integration")
	void sessionIsConsistentWithAppNameAndUserId() {
		// Arrange
		String expectedAppName = "testApp";
		String expectedUserId = "testUser";
		when(mockSession.appName()).thenReturn(expectedAppName);
		when(mockSession.userId()).thenReturn(expectedUserId);
		InvocationContext context = buildMinimalContext(mockSession);
		// Act
		String appName = context.appName();
		String userId = context.userId();
		Session session = context.session();
		// Assert
		assertThat(appName).isEqualTo(session.appName());
		assertThat(userId).isEqualTo(session.userId());
		assertThat(appName).isEqualTo(expectedAppName);
		assertThat(userId).isEqualTo(expectedUserId);
	}

	@Test
	@Tag("valid")
	void sessionReturnedWhenContextBuiltWithMinimalRequiredFields() {
		// Arrange
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.agent(mockAgent)
			.session(mockSession)
			.build();
		// Act
		Session result = context.session();
		// Assert
		assertThat(result).isNotNull();
		assertThat(result).isEqualTo(mockSession);
	}

	@Test
	@Tag("valid")
	void sessionRemainsUnchangedAfterAgentReassignment() {
		// Arrange
		BaseAgent newMockAgent = mock(BaseAgent.class);
		InvocationContext context = buildMinimalContext(mockSession);
		// Act
		context.agent(newMockAgent);
		Session result = context.session();
		// Assert
		assertThat(result).isEqualTo(mockSession);
		assertThat(context.agent()).isSameInstanceAs(newMockAgent);
	}

	@Test
	@Tag("valid")
	void sessionRemainsUnchangedAfterEndInvocationIsSet() {
		// Arrange
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(mockRunConfig)
			.invocationId("test-invocation-id")
			.endInvocation(false)
			.build();
		// Act
		context.setEndInvocation(true);
		Session result = context.session();
		// Assert
		assertThat(result).isEqualTo(mockSession);
		assertThat(context.endInvocation()).isTrue();
	}

	@Test
	@Tag("valid")
	void sessionReturnedFromStaticCreateMethodWithUserContent() {
		// Arrange
		Content mockContent = mock(Content.class);
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService,
				"test-invocation-id", mockAgent, mockSession, mockContent, mockRunConfig);
		// Act
		Session result = context.session();
		// Assert
		assertThat(result).isNotNull();
		assertThat(result).isEqualTo(mockSession);
	}

	@Test
	@Tag("valid")
	void sessionReturnedFromStaticCreateMethodWithLiveRequestQueue() {
		// Arrange
		LiveRequestQueue liveRequestQueue = new LiveRequestQueue();
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, liveRequestQueue, mockRunConfig);
		// Act
		Session result = context.session();
		// Assert
		assertThat(result).isNotNull();
		assertThat(result).isEqualTo(mockSession);
	}

	@Test
	@Tag("valid")
	void sessionReturnedWithBranchSet() {
		// Arrange
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(mockRunConfig)
			.invocationId("test-invocation-id")
			.branch("main.sub-branch")
			.build();
		// Act
		Session result = context.session();
		// Assert
		assertThat(result).isNotNull();
		assertThat(result).isEqualTo(mockSession);
		assertThat(context.branch()).isEqualTo(Optional.of("main.sub-branch"));
	}

	@Test
	@Tag("integration")
	void sessionReturnedWithResumabilityConfigSet() {
		// Arrange
		ResumabilityConfig resumabilityConfig = mock(ResumabilityConfig.class);
		when(resumabilityConfig.isResumable()).thenReturn(true);
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(mockRunConfig)
			.invocationId("test-invocation-id")
			.resumabilityConfig(resumabilityConfig)
			.build();
		// Act
		Session result = context.session();
		// Assert
		assertThat(result).isNotNull();
		assertThat(result).isEqualTo(mockSession);
		assertThat(context.isResumable()).isTrue();
	}

	@Test
	@Tag("valid")
	void sessionReturnedWhenUserContentIsAbsent() {
		// Arrange
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(mockRunConfig)
			.invocationId("test-invocation-id")
			.userContent(Optional.empty())
			.build();
		// Act
		Session result = context.session();
		// Assert
		assertThat(result).isNotNull();
		assertThat(result).isEqualTo(mockSession);
		assertThat(context.userContent()).isEmpty();
	}

	@Test
	@Tag("integration")
	void sessionConsistentAcrossMultipleCopyOfOperations() {
		// Arrange
		InvocationContext originalContext = buildMinimalContext(mockSession);
		InvocationContext copiedOnce = InvocationContext.copyOf(originalContext);
		InvocationContext copiedTwice = InvocationContext.copyOf(copiedOnce);
		// Act & Assert
		assertThat(originalContext.session()).isSameInstanceAs(copiedOnce.session());
		assertThat(copiedOnce.session()).isSameInstanceAs(copiedTwice.session());
		assertThat(originalContext.session()).isSameInstanceAs(copiedTwice.session());
	}

	@Test
	@Tag("valid")
	void sessionReturnedFromContextBuiltWithAllOptionalFields() {
		// Arrange
		Content mockContent = mock(Content.class);
		PluginManager mockPluginManager = mock(PluginManager.class);
		LiveRequestQueue liveRequestQueue = new LiveRequestQueue();
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.pluginManager(mockPluginManager)
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(mockRunConfig)
			.invocationId("full-invocation-id")
			.userContent(mockContent)
			.branch("main")
			.liveRequestQueue(liveRequestQueue)
			.endInvocation(false)
			.build();
		// Act
		Session result = context.session();
		// Assert
		assertThat(result).isNotNull();
		assertThat(result).isEqualTo(mockSession);
	}

	@Test
	@Tag("boundary")
	void sessionReturnedWhenInvocationIdIsEmpty() {
		// Arrange
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.agent(mockAgent)
			.session(mockSession)
			.runConfig(mockRunConfig)
			.invocationId("")
			.build();
		// Act
		Session result = context.session();
		// Assert
		assertThat(result).isNotNull();
		assertThat(result).isEqualTo(mockSession);
	}

	@Test
	@Tag("valid")
	void sessionReturnedFromContextWithBranchMutation() {
		// Arrange
		InvocationContext context = buildMinimalContext(mockSession);
		// Act
		context.branch("new-branch");
		Session result = context.session();
		// Assert
		assertThat(result).isNotNull();
		assertThat(result).isEqualTo(mockSession);
		assertThat(context.branch()).isEqualTo(Optional.of("new-branch"));
	}

	@Test
	@Tag("valid")
	void sessionNotAffectedByActiveStreamingToolsAddition() {
		// Arrange
		InvocationContext context = buildMinimalContext(mockSession);
		ActiveStreamingTool mockStreamingTool = mock(ActiveStreamingTool.class);
		// Act
		context.activeStreamingTools().put("tool-1", mockStreamingTool);
		Session result = context.session();
		// Assert
		assertThat(result).isNotNull();
		assertThat(result).isEqualTo(mockSession);
		assertThat(context.activeStreamingTools()).containsKey("tool-1");
	}

}
