/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=memoryService_1115878a43
ROOST_METHOD_SIG_HASH=memoryService_b8500b83f5

Scenario 1: Memory Service Returns the Correct Non-Null Instance Set via Builder

Details:
  TestName: memoryServiceReturnsCorrectInstanceWhenSetViaBuilder
  Description: Verifies that the `memoryService()` method returns the exact same
               `BaseMemoryService` instance that was provided to the builder during
               construction of `InvocationContext`. This test ensures the field
               assignment and retrieval pipeline works correctly end-to-end.

Execution:
  Arrange:
    - Create a mock instance of `BaseMemoryService` using a mocking framework (e.g., Mockito).
    - Create a mock instance of `BaseSessionService`.
    - Create a mock instance of `BaseArtifactService`.
    - Create a mock instance of `BaseAgent`.
    - Create a mock instance of `Session`.
    - Use `InvocationContext.builder()` and supply the mocked `BaseMemoryService`
      via `.memoryService(mockMemoryService)`, along with other required fields
      (sessionService, artifactService, agent, session).
    - Call `.build()` to produce the `InvocationContext` instance.

  Act:
    - Invoke `invocationContext.memoryService()` on the built instance.

  Assert:
    - Use `assertSame(mockMemoryService, invocationContext.memoryService())` to
      confirm the returned reference is identical to the mock supplied at build time.

Validation:
  The assertion verifies referential equality between the provided mock and the
  returned value, ensuring no defensive copying or wrapping occurs. This is
  significant because downstream components (e.g., LLM flows) depend on receiving
  the exact service instance to perform memory lookups and storage operations
  consistently throughout an invocation lifecycle.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.genai.types.Content;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class InvocationContextMemoryServiceTest {
  @Mock private BaseSessionService mockSessionService;
  @Mock private BaseArtifactService mockArtifactService;
  @Mock private BaseMemoryService mockMemoryService;
  @Mock private BaseAgent mockAgent;
  @Mock private Session mockSession;
  @Mock private PluginManager mockPluginManager;
  @Mock private RunConfig mockRunConfig;

  @BeforeEach
  void setUp() {
    when(mockSession.appName()).thenReturn("testApp");
    when(mockSession.userId()).thenReturn("testUser");
  }

  @Test
  @Tag("valid")
  void memoryServiceReturnsCorrectInstanceWhenSetViaBuilder() {
    InvocationContext invocationContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .memoryService(mockMemoryService)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("test-invocation-id")
            .userContent(Optional.empty())
            .runConfig(mockRunConfig)
            .build();
    BaseMemoryService result = invocationContext.memoryService();
    assertSame(mockMemoryService, result);
  }

  @Test
  @Tag("valid")
  void memoryServiceReturnsNullWhenNotSetViaBuilder() {
    InvocationContext invocationContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("test-invocation-id")
            .userContent(Optional.empty())
            .runConfig(mockRunConfig)
            .build();
    BaseMemoryService result = invocationContext.memoryService();
    assertNull(result);
  }

  @Test
  @Tag("valid")
  void memoryServiceReturnsSameInstanceOnMultipleCalls() {
    InvocationContext invocationContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .memoryService(mockMemoryService)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("test-invocation-id")
            .userContent(Optional.empty())
            .runConfig(mockRunConfig)
            .build();
    BaseMemoryService firstCall = invocationContext.memoryService();
    BaseMemoryService secondCall = invocationContext.memoryService();
    assertSame(firstCall, secondCall);
  }

  @Test
  @Tag("valid")
  void memoryServiceReturnsDifferentInstancesForDifferentContexts() {
    BaseMemoryService mockMemoryService2 = mock(BaseMemoryService.class);
    InvocationContext context1 =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .memoryService(mockMemoryService)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("invocation-id-1")
            .userContent(Optional.empty())
            .runConfig(mockRunConfig)
            .build();
    InvocationContext context2 =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .memoryService(mockMemoryService2)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("invocation-id-2")
            .userContent(Optional.empty())
            .runConfig(mockRunConfig)
            .build();
    assertSame(mockMemoryService, context1.memoryService());
    assertSame(mockMemoryService2, context2.memoryService());
    assertNotSame(context1.memoryService(), context2.memoryService());
  }

  @Test
  @Tag("valid")
  void memoryServiceReturnedIsNotNull() {
    InvocationContext invocationContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .memoryService(mockMemoryService)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("test-invocation-id")
            .userContent(Optional.empty())
            .runConfig(mockRunConfig)
            .build();
    assertNotNull(invocationContext.memoryService());
  }

  @Test
  @Tag("valid")
  void memoryServicePreservedThroughCopyOf() {
    InvocationContext original =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .memoryService(mockMemoryService)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("test-invocation-id")
            .userContent(Optional.empty())
            .runConfig(mockRunConfig)
            .build();
    InvocationContext copy = InvocationContext.copyOf(original);
    assertSame(mockMemoryService, copy.memoryService());
  }

  @Test
  @Tag("valid")
  void memoryServicePreservedAfterBranchUpdate() {
    InvocationContext invocationContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .memoryService(mockMemoryService)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("test-invocation-id")
            .userContent(Optional.empty())
            .runConfig(mockRunConfig)
            .build();
    invocationContext.branch("testBranch");
    assertSame(mockMemoryService, invocationContext.memoryService());
  }

  @Test
  @Tag("valid")
  void memoryServicePreservedAfterAgentUpdate() {
    BaseAgent newMockAgent = mock(BaseAgent.class);
    InvocationContext invocationContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .memoryService(mockMemoryService)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("test-invocation-id")
            .userContent(Optional.empty())
            .runConfig(mockRunConfig)
            .build();
    invocationContext.agent(newMockAgent);
    assertSame(mockMemoryService, invocationContext.memoryService());
  }

  @Test
  @Tag("valid")
  void memoryServicePreservedAfterEndInvocationSet() {
    InvocationContext invocationContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .memoryService(mockMemoryService)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("test-invocation-id")
            .userContent(Optional.empty())
            .runConfig(mockRunConfig)
            .build();
    invocationContext.setEndInvocation(true);
    assertSame(mockMemoryService, invocationContext.memoryService());
  }

  @Test
  @Tag("valid")
  void memoryServiceWithStaticCreateMethod() {
    Content mockContent = mock(Content.class);
    InvocationContext invocationContext =
        InvocationContext.create(
            mockSessionService,
            mockArtifactService,
            "test-invocation-id",
            mockAgent,
            mockSession,
            mockContent,
            mockRunConfig);
    assertNull(invocationContext.memoryService());
  }

  @Test
  @Tag("integration")
  void memoryServiceWithAllFieldsSet() {
    InvocationContext invocationContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .memoryService(mockMemoryService)
            .pluginManager(mockPluginManager)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("full-invocation-id")
            .userContent(Optional.empty())
            .runConfig(mockRunConfig)
            .endInvocation(false)
            .build();
    assertSame(mockMemoryService, invocationContext.memoryService());
    assertNotNull(invocationContext.sessionService());
    assertNotNull(invocationContext.artifactService());
    assertNotNull(invocationContext.pluginManager());
  }

  @Test
  @Tag("valid")
  void memoryServiceEqualityBetweenTwoContextsWithSameService() {
    InvocationContext context1 =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .memoryService(mockMemoryService)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("invocation-id")
            .userContent(Optional.empty())
            .runConfig(mockRunConfig)
            .build();
    InvocationContext context2 =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .memoryService(mockMemoryService)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("invocation-id")
            .userContent(Optional.empty())
            .runConfig(mockRunConfig)
            .build();
    assertSame(context1.memoryService(), context2.memoryService());
  }

  @Test
  @Tag("boundary")
  void memoryServiceNullExplicitlyNotSetInBuilder() {
    InvocationContext invocationContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("test-invocation-id")
            .runConfig(mockRunConfig)
            .build();
    BaseMemoryService result = invocationContext.memoryService();
    assertNull(result);
  }

  @Test
  @Tag("valid")
  void memoryServiceWithBranchBuilderMethod() {
    InvocationContext invocationContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .memoryService(mockMemoryService)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("test-invocation-id")
            .branch("agentA.agentB")
            .userContent(Optional.empty())
            .runConfig(mockRunConfig)
            .build();
    assertSame(mockMemoryService, invocationContext.memoryService());
  }

  @Test
  @Tag("integration")
  void memoryServiceRetainedAfterCopyOfWithActiveStreamingTools() {
    InvocationContext original =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .memoryService(mockMemoryService)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("test-invocation-id")
            .userContent(Optional.empty())
            .runConfig(mockRunConfig)
            .build();
    InvocationContext copiedContext = InvocationContext.copyOf(original);
    assertSame(mockMemoryService, copiedContext.memoryService());
    assertEquals(original.memoryService(), copiedContext.memoryService());
  }

  @Test
  @Tag("valid")
  void memoryServiceWithLiveRequestQueueSet() {
    LiveRequestQueue liveRequestQueue = new LiveRequestQueue();
    InvocationContext invocationContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .memoryService(mockMemoryService)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId("test-invocation-id")
            .liveRequestQueue(liveRequestQueue)
            .runConfig(mockRunConfig)
            .build();
    assertSame(mockMemoryService, invocationContext.memoryService());
  }

  @Test
  @Tag("boundary")
  void memoryServiceDoesNotAffectOtherFields() {
    String expectedInvocationId = "specific-invocation-id";
    InvocationContext invocationContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .memoryService(mockMemoryService)
            .agent(mockAgent)
            .session(mockSession)
            .invocationId(expectedInvocationId)
            .userContent(Optional.empty())
            .runConfig(mockRunConfig)
            .build();
    assertSame(mockMemoryService, invocationContext.memoryService());
    assertEquals(expectedInvocationId, invocationContext.invocationId());
    assertSame(mockSessionService, invocationContext.sessionService());
    assertSame(mockArtifactService, invocationContext.artifactService());
  }
}
