/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=appName_a8fa25d446
ROOST_METHOD_SIG_HASH=appName_e2ea244c93

Scenario 1: Return Application Name from Session

Details:
  TestName: appNameReturnsSessionAppName
  Description: Verifies that the appName() method correctly delegates to the session's appName() method and returns the expected application name string.

Execution:
  Arrange:
    - Create a mock Session object using Mockito.
    - Configure the mock Session to return a specific non-null string value (e.g., "MyTestApp") when appName() is called.
    - Build an InvocationContext using InvocationContext.builder(), setting the mock Session via .session(mockSession), and providing the minimum required fields (sessionService, artifactService, agent, session).
  Act:
    - Call invocationContext.appName() on the constructed InvocationContext instance.
  Assert:
    - Use assertEquals("MyTestApp", result) to verify the returned value matches the mocked session's appName.

Validation:
  This assertion confirms that InvocationContext.appName() correctly proxies the call to session.appName() and returns its result unchanged. This is important because InvocationContext acts as an aggregating context for a session, and the application name must consistently reflect the session's identity throughout the invocation lifecycle.


---

Scenario 2: Application Name with a Different Session App Name Value

Details:
  TestName: appNameReturnsDifferentAppNameFromSession
  Description: Verifies that appName() returns the exact string value stored in the session regardless of what other fields are set in the InvocationContext, confirming no transformation is applied.

Execution:
  Arrange:
    - Create a mock Session object.
    - Configure the mock Session to return a distinct application name (e.g., "AnotherApplication").
    - Build an InvocationContext using InvocationContext.builder() with the mock session, along with other required fields.
  Act:
    - Invoke invocationContext.appName().
  Assert:
    - Use assertEquals("AnotherApplication", result) to verify the exact value is returned.

Validation:
  Ensures there is no string manipulation, caching, or transformation between InvocationContext.appName() and Session.appName(). The method must return the value exactly as provided by the session.


---

Scenario 3: Application Name Delegation Verified via Session Interaction

Details:
  TestName: appNameDelegatesToSessionAppName
  Description: Verifies that appName() in InvocationContext calls session.appName() exactly once, confirming proper delegation behavior.

Execution:
  Arrange:
    - Create a mock Session using Mockito.
    - Configure the mock Session's appName() to return "DelegationTestApp".
    - Construct an InvocationContext via InvocationContext.builder() with the mock session.
  Act:
    - Call invocationContext.appName().
  Assert:
    - Use Mockito.verify(mockSession, times(1)).appName() to confirm the session's appName() was called exactly once.

Validation:
  This verifies that InvocationContext.appName() does not bypass the session or call appName() multiple times. Ensuring single delegation is critical to avoid unintended side effects and to confirm the method's implementation is straightforward pass-through behavior.


---

Scenario 4: Application Name Consistency with Session Created via copyOf

Details:
  TestName: appNameReturnsSameValueAfterCopyOf
  Description: Verifies that after creating a shallow copy of an InvocationContext using InvocationContext.copyOf(), the copied context's appName() returns the same value as the original's appName().

Execution:
  Arrange:
    - Create a mock Session configured to return "CopiedApp" for appName().
    - Build an original InvocationContext via InvocationContext.builder() with the mock session and required fields.
    - Create a copy using InvocationContext.copyOf(originalContext).
  Act:
    - Call appName() on both the original and the copied InvocationContext.
  Assert:
    - Use assertEquals(originalContext.appName(), copiedContext.appName()) to verify both return the same value "CopiedApp".

Validation:
  Since copyOf() creates a shallow copy reusing the same Session object, both contexts should reference the same session and therefore return identical app names. This validates that copyOf() correctly preserves session references and that appName() consistency is maintained across copies.


---

Scenario 5: Application Name with Alphanumeric and Special Characters in App Name

Details:
  TestName: appNameReturnsAppNameWithSpecialCharacters
  Description: Verifies that appName() handles and correctly returns an application name string that contains alphanumeric characters, spaces, hyphens, or underscores without any modification.

Execution:
  Arrange:
    - Create a mock Session.
    - Configure the mock Session to return a complex string like "My-App_v2 (Test)" when appName() is called.
    - Build an InvocationContext using InvocationContext.builder() with the mock session.
  Act:
    - Call invocationContext.appName().
  Assert:
    - Use assertEquals("My-App_v2 (Test)", result) to verify the returned string matches exactly.

Validation:
  Ensures that InvocationContext.appName() does not perform any trimming, escaping, or modification of the session's app name. The method should handle any valid string value returned by the session without alteration.


---

Scenario 6: Application Name with an Empty String Returned by Session

Details:
  TestName: appNameReturnsEmptyStringWhenSessionAppNameIsEmpty
  Description: Verifies that appName() correctly returns an empty string when the underlying session's appName() returns an empty string, without throwing an exception or substituting a default value.

Execution:
  Arrange:
    - Create a mock Session.
    - Configure the mock Session's appName() to return an empty string "".
    - Build an InvocationContext via InvocationContext.builder() with this mock session.
  Act:
    - Call invocationContext.appName().
  Assert:
    - Use assertEquals("", result) to confirm an empty string is returned.

Validation:
  While an empty app name may be an edge case, the appName() method should faithfully return whatever the session provides without defensive logic that alters the value. This validates the absence of unintended default substitution or null-checking behavior.


---

Scenario 7: Application Name Returned via Deprecated Constructor

Details:
  TestName: appNameReturnsCorrectValueWhenBuiltWithDeprecatedConstructor
  Description: Verifies that when an InvocationContext is constructed using the deprecated public constructor (not the builder), the appName() method still correctly delegates to the session's appName() method.

Execution:
  Arrange:
    - Create a mock Session configured to return "DeprecatedConstructorApp" for appName().
    - Create mock instances for BaseSessionService, BaseArtifactService, BaseMemoryService, PluginManager, and BaseAgent.
    - Instantiate InvocationContext using the deprecated constructor:
      new InvocationContext(sessionService, artifactService, memoryService, pluginManager, Optional.empty(), Optional.empty(), "inv-id", mockAgent, mockSession, Optional.empty(), mockRunConfig, false).
  Act:
    - Call invocationContext.appName().
  Assert:
    - Use assertEquals("DeprecatedConstructorApp", result).

Validation:
  This test confirms that the deprecated constructor correctly sets the session field and that appName() works properly regardless of which construction pathway is used. This ensures backward compatibility is maintained.


---

Scenario 8: Application Name with a Long String Value

Details:
  TestName: appNameReturnsLongAppNameString
  Description: Verifies that appName() correctly handles and returns a very long application name string without truncation, corruption, or exception.

Execution:
  Arrange:
    - Create a mock Session.
    - Generate a long string (e.g., a 1000-character string of repeated characters) and configure the mock Session's appName() to return it.
    - Build an InvocationContext using InvocationContext.builder() with this mock session.
  Act:
    - Call invocationContext.appName().
  Assert:
    - Use assertEquals(longAppName, result) to verify the complete long string is returned unchanged.

Validation:
  Tests robustness of the delegation by ensuring that InvocationContext.appName() does not impose length restrictions or cause string-related issues when the session returns an unusually long application name.


---

Scenario 9: Application Name Is Consistent Across Multiple Calls

Details:
  TestName: appNameReturnsConsistentValueAcrossMultipleCalls
  Description: Verifies that calling appName() multiple times on the same InvocationContext instance consistently returns the same value, confirming there is no state mutation or side effect between calls.

Execution:
  Arrange:
    - Create a mock Session configured to return "ConsistentApp" for appName().
    - Build an InvocationContext using InvocationContext.builder() with the mock session.
  Act:
    - Call invocationContext.appName() three times and store each result.
  Assert:
    - Use assertEquals on all three returned values to confirm they are all equal to "ConsistentApp".

Validation:
  Confirms that appName() is idempotent and deterministic. Since the method simply delegates to session.appName(), repeated calls should yield identical results assuming the session's app name does not change, which is the expected behavior for the session's identity properties.


---

Scenario 10: Application Name Returned via create() Static Factory Method

Details:
  TestName: appNameReturnsCorrectValueWhenBuiltWithCreateStaticFactory
  Description: Verifies that when InvocationContext is created using the static factory method InvocationContext.create(...), the appName() method correctly returns the session's application name.

Execution:
  Arrange:
    - Create a mock Session configured to return "StaticFactoryApp" for appName().
    - Create mock instances for BaseSessionService, BaseArtifactService, and BaseAgent.
    - Construct InvocationContext using InvocationContext.create(sessionService, artifactService, invocationId, agent, mockSession, null, runConfig).
  Act:
    - Call invocationContext.appName().
  Assert:
    - Use assertEquals("StaticFactoryApp", result).

Validation:
  Ensures that the static factory method correctly propagates the session to the constructed InvocationContext, and that appName() reliably works regardless of which supported construction mechanism is used.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class InvocationContextAppNameTest {
  @Mock private BaseSessionService mockSessionService;
  @Mock private BaseArtifactService mockArtifactService;
  @Mock private BaseMemoryService mockMemoryService;
  @Mock private PluginManager mockPluginManager;
  @Mock private BaseAgent mockAgent;
  @Mock private Session mockSession;
  private RunConfig defaultRunConfig;

  @BeforeEach
  void setUp() {
    defaultRunConfig = RunConfig.builder().build();
  }

  @Test
  @Tag("valid")
  void appNameReturnsSessionAppName() {
    when(mockSession.appName()).thenReturn("MyTestApp");
    InvocationContext invocationContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId("test-invocation-id")
            .agent(mockAgent)
            .session(mockSession)
            .userContent(Optional.empty())
            .runConfig(defaultRunConfig)
            .build();
    String result = invocationContext.appName();
    assertEquals("MyTestApp", result);
  }

  @Test
  @Tag("valid")
  void appNameReturnsDifferentAppNameFromSession() {
    when(mockSession.appName()).thenReturn("AnotherApplication");
    InvocationContext invocationContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId("test-invocation-id")
            .agent(mockAgent)
            .session(mockSession)
            .userContent(Optional.empty())
            .runConfig(defaultRunConfig)
            .build();
    String result = invocationContext.appName();
    assertEquals("AnotherApplication", result);
  }

  @Test
  @Tag("valid")
  void appNameDelegatesToSessionAppName() {
    when(mockSession.appName()).thenReturn("DelegationTestApp");
    InvocationContext invocationContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId("test-invocation-id")
            .agent(mockAgent)
            .session(mockSession)
            .userContent(Optional.empty())
            .runConfig(defaultRunConfig)
            .build();
    invocationContext.appName();
    verify(mockSession, times(1)).appName();
  }

  @Test
  @Tag("integration")
  void appNameReturnsSameValueAfterCopyOf() {
    when(mockSession.appName()).thenReturn("CopiedApp");
    InvocationContext originalContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId("test-invocation-id")
            .agent(mockAgent)
            .session(mockSession)
            .userContent(Optional.empty())
            .runConfig(defaultRunConfig)
            .build();
    InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
    assertEquals(originalContext.appName(), copiedContext.appName());
    assertEquals("CopiedApp", copiedContext.appName());
  }

  @Test
  @Tag("valid")
  void appNameReturnsAppNameWithSpecialCharacters() {
    when(mockSession.appName()).thenReturn("My-App_v2 (Test)");
    InvocationContext invocationContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId("test-invocation-id")
            .agent(mockAgent)
            .session(mockSession)
            .userContent(Optional.empty())
            .runConfig(defaultRunConfig)
            .build();
    String result = invocationContext.appName();
    assertEquals("My-App_v2 (Test)", result);
  }

  @Test
  @Tag("boundary")
  void appNameReturnsEmptyStringWhenSessionAppNameIsEmpty() {
    when(mockSession.appName()).thenReturn("");
    InvocationContext invocationContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId("test-invocation-id")
            .agent(mockAgent)
            .session(mockSession)
            .userContent(Optional.empty())
            .runConfig(defaultRunConfig)
            .build();
    String result = invocationContext.appName();
    assertEquals("", result);
  }

  @Test
  @Tag("valid")
  @SuppressWarnings("deprecation")
  void appNameReturnsCorrectValueWhenBuiltWithDeprecatedConstructor() {
    when(mockSession.appName()).thenReturn("DeprecatedConstructorApp");
    InvocationContext invocationContext =
        new InvocationContext(
            mockSessionService,
            mockArtifactService,
            mockMemoryService,
            mockPluginManager,
            Optional.empty(),
            Optional.empty(),
            "inv-id",
            mockAgent,
            mockSession,
            Optional.empty(),
            defaultRunConfig,
            false);
    String result = invocationContext.appName();
    assertEquals("DeprecatedConstructorApp", result);
  }

  @Test
  @Tag("boundary")
  void appNameReturnsLongAppNameString() {
    String longAppName = "A".repeat(1000);
    when(mockSession.appName()).thenReturn(longAppName);
    InvocationContext invocationContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId("test-invocation-id")
            .agent(mockAgent)
            .session(mockSession)
            .userContent(Optional.empty())
            .runConfig(defaultRunConfig)
            .build();
    String result = invocationContext.appName();
    assertEquals(longAppName, result);
    assertEquals(1000, result.length());
  }

  @Test
  @Tag("valid")
  void appNameReturnsConsistentValueAcrossMultipleCalls() {
    when(mockSession.appName()).thenReturn("ConsistentApp");
    InvocationContext invocationContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId("test-invocation-id")
            .agent(mockAgent)
            .session(mockSession)
            .userContent(Optional.empty())
            .runConfig(defaultRunConfig)
            .build();
    String result1 = invocationContext.appName();
    String result2 = invocationContext.appName();
    String result3 = invocationContext.appName();
    assertEquals("ConsistentApp", result1);
    assertEquals("ConsistentApp", result2);
    assertEquals("ConsistentApp", result3);
    assertEquals(result1, result2);
    assertEquals(result2, result3);
  }

  @Test
  @Tag("valid")
  void appNameReturnsCorrectValueWhenBuiltWithCreateStaticFactory() {
    when(mockSession.appName()).thenReturn("StaticFactoryApp");
    InvocationContext invocationContext =
        InvocationContext.create(
            mockSessionService,
            mockArtifactService,
            "test-invocation-id",
            mockAgent,
            mockSession,
            null,
            defaultRunConfig);
    String result = invocationContext.appName();
    assertEquals("StaticFactoryApp", result);
  }

  @Test
  @Tag("valid")
  void appNameReturnsCorrectValueWithNumericAppName() {
    when(mockSession.appName()).thenReturn("App123");
    InvocationContext invocationContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId("test-invocation-id")
            .agent(mockAgent)
            .session(mockSession)
            .userContent(Optional.empty())
            .runConfig(defaultRunConfig)
            .build();
    String result = invocationContext.appName();
    assertEquals("App123", result);
  }

  @Test
  @Tag("integration")
  void appNameReturnsSameValueAfterCopyOfVerifiesSessionCalledOnce() {
    when(mockSession.appName()).thenReturn("CopiedApp");
    InvocationContext originalContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId("test-invocation-id")
            .agent(mockAgent)
            .session(mockSession)
            .userContent(Optional.empty())
            .runConfig(defaultRunConfig)
            .build();
    InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
    String copiedAppName = copiedContext.appName();
    verify(mockSession, times(1)).appName();
    assertEquals("CopiedApp", copiedAppName);
  }

  @Test
  @Tag("valid")
  @SuppressWarnings("deprecation")
  void appNameReturnsCorrectValueWhenBuiltWithSecondDeprecatedConstructor() {
    when(mockSession.appName()).thenReturn("DeprecatedConstructorApp2");
    InvocationContext invocationContext =
        new InvocationContext(
            mockSessionService,
            mockArtifactService,
            mockMemoryService,
            Optional.empty(),
            Optional.empty(),
            "inv-id",
            mockAgent,
            mockSession,
            Optional.empty(),
            defaultRunConfig,
            false);
    String result = invocationContext.appName();
    assertEquals("DeprecatedConstructorApp2", result);
  }

  @Test
  @Tag("valid")
  void appNameReturnsCorrectValueWithUnicodeCharacters() {
    when(mockSession.appName()).thenReturn("App\u00E9\u00E0\u00FC");
    InvocationContext invocationContext =
        InvocationContext.builder()
            .sessionService(mockSessionService)
            .artifactService(mockArtifactService)
            .invocationId("test-invocation-id")
            .agent(mockAgent)
            .session(mockSession)
            .userContent(Optional.empty())
            .runConfig(defaultRunConfig)
            .build();
    String result = invocationContext.appName();
    assertEquals("App\u00E9\u00E0\u00FC", result);
  }
}
