/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=newInvocationContextId_87a927076b
ROOST_METHOD_SIG_HASH=newInvocationContextId_db44e2dbb1

Scenario 1: Verify the Return Value Starts with the Expected Prefix

Details:
  TestName: returnValueStartsWithExpectedPrefix
  Description: Verifies that the string returned by newInvocationContextId() always begins with the
               fixed prefix "e-", which is the documented contract of this method.

Execution:
  Arrange: No setup is required since newInvocationContextId() is a static method with no
           external dependencies.
  Act:     Invoke InvocationContext.newInvocationContextId() and store the result.
  Assert:  Use assertTrue(result.startsWith("e-")) to confirm the prefix is present.

Validation:
  The assertion ensures that the "e-" prefix is always prepended to the UUID. This prefix is
  part of the invocation ID contract and is used throughout the system (e.g., in the Builder's
  default invocationId field) to identify invocation contexts. Any deviation would break
  downstream logic that relies on this naming convention.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;

import java.util.HashSet;
import java.util.Set;
import java.util.UUID;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

class InvocationContextNewInvocationContextIdTest {

	private static final String EXPECTED_PREFIX = "e-";

	@Test
	@Tag("valid")
	void returnValueStartsWithExpectedPrefix() {
		String result = InvocationContext.newInvocationContextId();
		assertNotNull(result, "newInvocationContextId() should not return null");
		assertTrue(result.startsWith(EXPECTED_PREFIX), "Expected result to start with 'e-' but was: " + result);
	}

	@Test
	@Tag("valid")
	void returnValueIsNotNull() {
		String result = InvocationContext.newInvocationContextId();
		assertNotNull(result, "newInvocationContextId() should never return null");
	}

	@Test
	@Tag("valid")
	void returnValueIsNotEmpty() {
		String result = InvocationContext.newInvocationContextId();
		assertFalse(result.isEmpty(), "newInvocationContextId() should never return an empty string");
	}

	@Test
	@Tag("valid")
	void returnValueContainsValidUuidAfterPrefix() {
		String result = InvocationContext.newInvocationContextId();
		assertTrue(result.startsWith(EXPECTED_PREFIX), "Result must start with 'e-' prefix");
		String uuidPart = result.substring(EXPECTED_PREFIX.length());
		assertDoesNotThrow(() -> UUID.fromString(uuidPart),
				"The part after 'e-' prefix should be a valid UUID, but was: " + uuidPart);
	}

	@Test
	@Tag("valid")
	void returnValueHasCorrectFormat() {
		String result = InvocationContext.newInvocationContextId();
		assertNotNull(result);
		assertTrue(result.startsWith(EXPECTED_PREFIX), "Result must start with 'e-'");
		String uuidPart = result.substring(EXPECTED_PREFIX.length());
		// UUID format: 8-4-4-4-12 hex chars separated by hyphens
		assertTrue(uuidPart.matches("[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"),
				"UUID part should match standard UUID format, but was: " + uuidPart);
	}

	@Test
	@Tag("valid")
	void returnValueHasExpectedLength() {
		String result = InvocationContext.newInvocationContextId();
		// "e-" (2 chars) + UUID (36 chars) = 38 chars total
		int expectedLength = EXPECTED_PREFIX.length() + 36;
		assertEquals(expectedLength, result.length(),
				"Expected length of " + expectedLength + " but was: " + result.length());
	}

	@Test
	@Tag("valid")
	void consecutiveCallsReturnDifferentValues() {
		String result1 = InvocationContext.newInvocationContextId();
		String result2 = InvocationContext.newInvocationContextId();
		assertNotEquals(result1, result2,
				"Consecutive calls to newInvocationContextId() should return different values");
	}

	@Test
	@Tag("valid")
	void multipleCallsAllStartWithPrefix() {
		int callCount = 10;
		for (int i = 0; i < callCount; i++) {
			String result = InvocationContext.newInvocationContextId();
			assertTrue(result.startsWith(EXPECTED_PREFIX),
					"Call #" + i + " did not start with 'e-', result was: " + result);
		}
	}

	@Test
	@Tag("valid")
	void multipleCallsProduceUniqueValues() {
		int callCount = 100;
		Set<String> generatedIds = new HashSet<>();
		for (int i = 0; i < callCount; i++) {
			String result = InvocationContext.newInvocationContextId();
			assertTrue(generatedIds.add(result), "Duplicate ID generated on call #" + i + ": " + result);
		}
		assertEquals(callCount, generatedIds.size(), "All generated IDs should be unique");
	}

	@Test
	@Tag("valid")
	void returnValuePrefixIsExactlyEDash() {
		String result = InvocationContext.newInvocationContextId();
		assertEquals('e', result.charAt(0), "First character should be 'e'");
		assertEquals('-', result.charAt(1), "Second character should be '-'");
	}

	@Test
	@Tag("boundary")
	void uuidPartAfterPrefixHasCorrectLength() {
		String result = InvocationContext.newInvocationContextId();
		String uuidPart = result.substring(EXPECTED_PREFIX.length());
		// Standard UUID string representation is 36 characters
		assertEquals(36, uuidPart.length(), "UUID part should be 36 characters long, but was: " + uuidPart.length());
	}

	@Test
	@Tag("boundary")
	void returnValueDoesNotStartWithJustE() {
		String result = InvocationContext.newInvocationContextId();
		assertFalse(result.startsWith("e") && !result.startsWith("e-"), "Result should start with 'e-' not just 'e'");
	}

	@Test
	@Tag("boundary")
	void returnValueDoesNotStartWithDashE() {
		String result = InvocationContext.newInvocationContextId();
		assertFalse(result.startsWith("-e"), "Result should start with 'e-' not '-e'");
	}

	@Test
	@Tag("valid")
	void returnValueDoesNotContainOnlyPrefix() {
		String result = InvocationContext.newInvocationContextId();
		assertNotEquals(EXPECTED_PREFIX, result, "Result should not be just the prefix 'e-'");
	}

	@Test
	@Tag("valid")
	void uuidPartIsVersion4Uuid() {
		String result = InvocationContext.newInvocationContextId();
		String uuidPart = result.substring(EXPECTED_PREFIX.length());
		UUID uuid = UUID.fromString(uuidPart);
		assertEquals(4, uuid.version(), "UUID should be version 4 (random), but was version: " + uuid.version());
	}

	@Test
	@Tag("valid")
	void uuidPartIsVariant2Uuid() {
		String result = InvocationContext.newInvocationContextId();
		String uuidPart = result.substring(EXPECTED_PREFIX.length());
		UUID uuid = UUID.fromString(uuidPart);
		assertEquals(2, uuid.variant(), "UUID should be variant 2 (IETF RFC 4122), but was variant: " + uuid.variant());
	}

	@Test
	@Tag("valid")
	void isStaticMethodCallableWithoutInstance() {
		// Verify the method can be called statically without any instance setup
		assertDoesNotThrow(() -> {
			String result = InvocationContext.newInvocationContextId();
			assertNotNull(result);
		}, "newInvocationContextId() should be callable as a static method without any setup");
	}

	@Test
	@Tag("valid")
	void returnValueDoesNotContainWhitespace() {
		String result = InvocationContext.newInvocationContextId();
		assertFalse(result.contains(" "), "Result should not contain spaces");
		assertFalse(result.contains("\t"), "Result should not contain tabs");
		assertFalse(result.contains("\n"), "Result should not contain newlines");
	}

	@Test
	@Tag("valid")
	void prefixIsLowercaseE() {
		String result = InvocationContext.newInvocationContextId();
		assertEquals('e', result.charAt(0), "Prefix should be lowercase 'e', not uppercase 'E'");
	}

	@Test
	@Tag("integration")
	void generatedIdCanBeUsedAsBuilderId() {
		String generatedId = InvocationContext.newInvocationContextId();
		assertNotNull(generatedId, "Generated ID should not be null");
		assertTrue(generatedId.startsWith("e-"), "Generated ID used as invocation ID should start with 'e-'");
		// Verify the ID is a valid string that could be used in builders
		assertFalse(generatedId.isEmpty(), "Generated ID should not be empty when used as invocation ID");
	}

	@Test
	@Tag("valid")
	void idHyphenSeparatesePrefixAndUuid() {
		String result = InvocationContext.newInvocationContextId();
		// Verify structure: "e-" + UUID
		String[] parts = result.split("-", 2);
		assertEquals(2, parts.length, "Result should have at least one hyphen separating 'e' from UUID");
		assertEquals("e", parts[0], "First part before first hyphen should be 'e'");
	}

	@Test
	@Tag("boundary")
	void largeNumberOfCallsAllProduceValidIds() {
		int callCount = 1000;
		for (int i = 0; i < callCount; i++) {
			String result = InvocationContext.newInvocationContextId();
			assertNotNull(result, "Call #" + i + " returned null");
			assertTrue(result.startsWith("e-"), "Call #" + i + " did not start with 'e-'");
			assertEquals(38, result.length(), "Call #" + i + " had unexpected length: " + result.length());
		}
	}

}
