/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=incrementLlmCallsCount_728a2657e3
ROOST_METHOD_SIG_HASH=incrementLlmCallsCount_ccbe51a785

Scenario 1: Successful LLM Call Increment When RunConfig Is Null

Details:
  TestName: incrementLlmCallsCountSucceedsWhenRunConfigIsNull
  Description: Verifies that calling incrementLlmCallsCount() does not throw any exception
               when the RunConfig is null, meaning no limit enforcement is applied.

Execution:
  Arrange: Build an InvocationContext using InvocationContext.builder() with all required
           fields (sessionService, artifactService, session, agent) but pass null as the
           runConfig (or rely on the fact that a null runConfig skips the limit check).
           Specifically set runConfig to null via builder.runConfig(null).
  Act:     Call invocationContext.incrementLlmCallsCount().
  Assert:  Assert that no LlmCallsLimitExceededException is thrown.

Validation:
  Confirms that when runConfig is null, the internal check
  "if (runConfig != null && ...)" evaluates to false, and the method completes normally.
  This is important to ensure backward compatibility when no RunConfig is provided.


---

Scenario 2: Successful LLM Call Increment When maxLlmCalls Is Zero (No Limit Set)

Details:
  TestName: incrementLlmCallsCountSucceedsWhenMaxLlmCallsIsZero
  Description: Verifies that calling incrementLlmCallsCount() does not throw an exception
               when RunConfig has maxLlmCalls set to 0, which means "unlimited" calls.

Execution:
  Arrange: Build a RunConfig with maxLlmCalls = 0 (the default or explicitly set).
           Build an InvocationContext using InvocationContext.builder() with the
           constructed RunConfig.
  Act:     Call invocationContext.incrementLlmCallsCount() once.
  Assert:  Assert that no LlmCallsLimitExceededException is thrown.

Validation:
  Confirms that the condition "runConfig.maxLlmCalls() > 0" is false when maxLlmCalls is 0,
  so the limit is never enforced. This represents the "unlimited" scenario in the application.


---

Scenario 3: Successful LLM Call Increment When Count Is Within the Defined Limit

Details:
  TestName: incrementLlmCallsCountSucceedsWhenWithinLimit
  Description: Verifies that calling incrementLlmCallsCount() does not throw an exception
               when the number of LLM calls made so far has not yet exceeded the configured
               maximum.

Execution:
  Arrange: Build a RunConfig with maxLlmCalls = 5.
           Build an InvocationContext using InvocationContext.builder() with this RunConfig.
  Act:     Call invocationContext.incrementLlmCallsCount() exactly 5 times.
  Assert:  Assert that no LlmCallsLimitExceededException is thrown during any of the 5 calls.

Validation:
  Confirms the boundary condition where numberOfLlmCalls equals maxLlmCalls.
  The condition "numberOfLlmCalls > runConfig.maxLlmCalls()" is false when they are equal,
  so the last allowed call must complete without an exception.


---

Scenario 4: LlmCallsLimitExceededException Thrown When Count Exceeds the Defined Limit

Details:
  TestName: incrementLlmCallsCountThrowsExceptionWhenLimitExceeded
  Description: Verifies that calling incrementLlmCallsCount() throws
               LlmCallsLimitExceededException when the number of LLM calls made exceeds
               the configured maximum in RunConfig.

Execution:
  Arrange: Build a RunConfig with maxLlmCalls = 3.
           Build an InvocationContext using InvocationContext.builder() with this RunConfig.
           Call invocationContext.incrementLlmCallsCount() 3 times without exception.
  Act:     Call invocationContext.incrementLlmCallsCount() a 4th time (exceeding the limit).
  Assert:  Assert that LlmCallsLimitExceededException is thrown on the 4th call.

Validation:
  Confirms the core enforcement behavior: when numberOfLlmCalls (4) > maxLlmCalls (3),
  the method must throw LlmCallsLimitExceededException. This is critical to prevent
  runaway LLM usage that could incur unexpected costs.


---

Scenario 5: LlmCallsLimitExceededException Message Contains Correct Limit Value

Details:
  TestName: incrementLlmCallsCountExceptionMessageContainsMaxLlmCalls
  Description: Verifies that the exception message thrown when the LLM call limit is exceeded
               contains the configured maxLlmCalls value, so callers can identify the limit
               that was breached.

Execution:
  Arrange: Build a RunConfig with maxLlmCalls = 2.
           Build an InvocationContext using InvocationContext.builder() with this RunConfig.
           Call invocationContext.incrementLlmCallsCount() twice (reaching the limit).
  Act:     Call invocationContext.incrementLlmCallsCount() a 3rd time and capture the
           thrown LlmCallsLimitExceededException.
  Assert:  Assert that the exception message contains "2" (the maxLlmCalls value).

Validation:
  Confirms that the error message "Max number of llm calls limit of 2 exceeded" is produced
  correctly. A descriptive error message aids in diagnosing issues in production and provides
  meaningful feedback to the caller.


---

Scenario 6: Single LLM Call Succeeds When maxLlmCalls Is Exactly One

Details:
  TestName: incrementLlmCallsCountSucceedsWithExactlyOneCallWhenLimitIsOne
  Description: Verifies that the first and only allowed LLM call does not throw an exception
               when maxLlmCalls is set to 1.

Execution:
  Arrange: Build a RunConfig with maxLlmCalls = 1.
           Build an InvocationContext using InvocationContext.builder() with this RunConfig.
  Act:     Call invocationContext.incrementLlmCallsCount() once.
  Assert:  Assert that no LlmCallsLimitExceededException is thrown.

Validation:
  Confirms the boundary condition at the lowest meaningful positive limit.
  When numberOfLlmCalls (1) equals maxLlmCalls (1), the condition
  "numberOfLlmCalls > maxLlmCalls" is false, so the call is allowed.


---

Scenario 7: Second LLM Call Throws Exception When maxLlmCalls Is One

Details:
  TestName: incrementLlmCallsCountThrowsExceptionOnSecondCallWhenLimitIsOne
  Description: Verifies that the second LLM call throws LlmCallsLimitExceededException
               when maxLlmCalls is configured to 1, since only one call is permitted.

Execution:
  Arrange: Build a RunConfig with maxLlmCalls = 1.
           Build an InvocationContext using InvocationContext.builder() with this RunConfig.
           Call invocationContext.incrementLlmCallsCount() once (allowed call).
  Act:     Call invocationContext.incrementLlmCallsCount() a second time.
  Assert:  Assert that LlmCallsLimitExceededException is thrown on the second call.

Validation:
  Validates the strict enforcement when maxLlmCalls = 1. This tests the smallest
  non-trivial limit and ensures the counter increments correctly before the check.


---

Scenario 8: Successful LLM Calls When maxLlmCalls Is Negative (No Limit Enforced)

Details:
  TestName: incrementLlmCallsCountSucceedsWhenMaxLlmCallsIsNegative
  Description: Verifies that calling incrementLlmCallsCount() multiple times does not throw
               an exception when maxLlmCalls is configured to a negative value, since the
               condition "maxLlmCalls() > 0" would be false.

Execution:
  Arrange: Build a RunConfig with maxLlmCalls set to a negative value (e.g., -1).
           Build an InvocationContext using InvocationContext.builder() with this RunConfig.
  Act:     Call invocationContext.incrementLlmCallsCount() multiple times (e.g., 10 times).
  Assert:  Assert that no LlmCallsLimitExceededException is thrown during any call.

Validation:
  Confirms that negative values for maxLlmCalls are treated as "no limit" due to the
  guard condition "runConfig.maxLlmCalls() > 0". This prevents accidental enforcement
  from misconfigured negative values.


---

Scenario 9: LLM Call Count Is Cumulative Across Multiple Increments Until Limit

Details:
  TestName: incrementLlmCallsCountIsCumulativeAcrossMultipleIncrements
  Description: Verifies that the LLM call counter accumulates correctly across multiple
               successive calls to incrementLlmCallsCount(), and that the exception is thrown
               only when the cumulative count exceeds the configured limit.

Execution:
  Arrange: Build a RunConfig with maxLlmCalls = 4.
           Build an InvocationContext using InvocationContext.builder() with this RunConfig.
  Act:     Call invocationContext.incrementLlmCallsCount() four times without exception,
           then call it a fifth time.
  Assert:  Assert that no exception is thrown during the first 4 calls and
           LlmCallsLimitExceededException is thrown on the 5th call.

Validation:
  Confirms that the internal numberOfLlmCalls counter is persistent across calls within
  the same InvocationContext instance and enforces the limit correctly at the right boundary.
  This validates the stateful nature of the InvocationCostManager.


---

Scenario 10: Consecutive Exception Thrown After Limit Is Exceeded

Details:
  TestName: incrementLlmCallsCountContinuesToThrowAfterLimitIsExceeded
  Description: Verifies that once the LLM call limit is exceeded and an exception is thrown,
               subsequent calls to incrementLlmCallsCount() also throw
               LlmCallsLimitExceededException, ensuring the limit remains enforced.

Execution:
  Arrange: Build a RunConfig with maxLlmCalls = 2.
           Build an InvocationContext using InvocationContext.builder() with this RunConfig.
           Call invocationContext.incrementLlmCallsCount() twice (reaching the limit).
  Act:     Call invocationContext.incrementLlmCallsCount() a 3rd time (limit exceeded).
           Call invocationContext.incrementLlmCallsCount() a 4th time.
  Assert:  Assert that LlmCallsLimitExceededException is thrown on both the 3rd and 4th calls.

Validation:
  Confirms that once the limit is exceeded, the enforcement is persistent and the counter
  continues to increment past the limit. The condition remains true for all subsequent calls
  since numberOfLlmCalls keeps growing beyond maxLlmCalls.


---

Scenario 11: InvocationContext Built With Default RunConfig Does Not Enforce LLM Limit

Details:
  TestName: incrementLlmCallsCountWithDefaultRunConfigDoesNotThrow
  Description: Verifies that an InvocationContext built using only the builder's defaults
               (which sets a default RunConfig with maxLlmCalls = 0) does not throw
               LlmCallsLimitExceededException when incrementLlmCallsCount() is called
               many times.

Execution:
  Arrange: Build an InvocationContext using InvocationContext.builder() without explicitly
           setting a RunConfig (relying on the builder default of RunConfig.builder().build()).
  Act:     Call invocationContext.incrementLlmCallsCount() many times (e.g., 100 times).
  Assert:  Assert that no LlmCallsLimitExceededException is thrown at any point.

Validation:
  Confirms that the default configuration of an InvocationContext imposes no LLM call
  limit. This is important for ensuring that agents work unrestricted unless a limit is
  explicitly configured by the caller.


---

Scenario 12: InvocationContext With Large maxLlmCalls Limit Enforces at Correct Boundary

Details:
  TestName: incrementLlmCallsCountEnforcesLimitAtCorrectBoundaryForLargeLimit
  Description: Verifies that when maxLlmCalls is set to a large value, the exception is thrown
               only after the exact number of allowed calls has been exceeded.

Execution:
  Arrange: Build a RunConfig with maxLlmCalls = 1000.
           Build an InvocationContext using InvocationContext.builder() with this RunConfig.
  Act:     Call invocationContext.incrementLlmCallsCount() exactly 1000 times (should succeed),
           then call it one more time (the 1001st call).
  Assert:  Assert that no exception is thrown during the first 1000 calls and
           LlmCallsLimitExceededException is thrown on the 1001st call.

Validation:
  Validates the precision of the counter and limit enforcement for larger configured limits.
  Ensures the boundary condition (numberOfLlmCalls > maxLlmCalls) is correctly evaluated
  at scale, avoiding off-by-one errors in the implementation.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.models.LlmCallsLimitExceededException;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

class InvocationContextIncrementLlmCallsCountTest {

	private BaseSessionService mockSessionService;

	private BaseArtifactService mockArtifactService;

	private BaseAgent mockAgent;

	private Session mockSession;

	@BeforeEach
	void setUp() {
		mockSessionService = mock(BaseSessionService.class);
		mockArtifactService = mock(BaseArtifactService.class);
		mockAgent = mock(BaseAgent.class);
		mockSession = mock(Session.class);
		when(mockSession.appName()).thenReturn("testApp");
		when(mockSession.userId()).thenReturn("testUser");
	}

	private InvocationContext buildContext(RunConfig runConfig) {
		return InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(runConfig)
			.build();
	}

	@Test
	@Tag("valid")
	void incrementLlmCallsCountSucceedsWhenRunConfigIsNull() {
		InvocationContext context = buildContext(null);
		assertDoesNotThrow(() -> context.incrementLlmCallsCount(), "Should not throw when RunConfig is null");
	}

	@Test
	@Tag("valid")
	void incrementLlmCallsCountSucceedsWhenMaxLlmCallsIsZero() {
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(0).build();
		InvocationContext context = buildContext(runConfig);
		assertDoesNotThrow(() -> context.incrementLlmCallsCount(),
				"Should not throw when maxLlmCalls is 0 (unlimited)");
	}

	@Test
	@Tag("boundary")
	void incrementLlmCallsCountSucceedsWhenWithinLimit() {
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(5).build();
		InvocationContext context = buildContext(runConfig);
		assertDoesNotThrow(() -> {
			for (int i = 0; i < 5; i++) {
				context.incrementLlmCallsCount();
			}
		}, "Should not throw when calls are within the configured limit of 5");
	}

	@Test
	@Tag("invalid")
	void incrementLlmCallsCountThrowsExceptionWhenLimitExceeded() throws LlmCallsLimitExceededException {
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(3).build();
		InvocationContext context = buildContext(runConfig);
		context.incrementLlmCallsCount();
		context.incrementLlmCallsCount();
		context.incrementLlmCallsCount();
		assertThrows(LlmCallsLimitExceededException.class, () -> context.incrementLlmCallsCount(),
				"Should throw LlmCallsLimitExceededException on the 4th call when limit is 3");
	}

	@Test
	@Tag("invalid")
	void incrementLlmCallsCountExceptionMessageContainsMaxLlmCalls() throws LlmCallsLimitExceededException {
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(2).build();
		InvocationContext context = buildContext(runConfig);
		context.incrementLlmCallsCount();
		context.incrementLlmCallsCount();
		LlmCallsLimitExceededException exception = assertThrows(LlmCallsLimitExceededException.class,
				() -> context.incrementLlmCallsCount(),
				"Should throw LlmCallsLimitExceededException on the 3rd call when limit is 2");
		assertTrue(exception.getMessage().contains("2"),
				"Exception message should contain the maxLlmCalls value '2'. Actual message: "
						+ exception.getMessage());
	}

	@Test
	@Tag("boundary")
	void incrementLlmCallsCountSucceedsWithExactlyOneCallWhenLimitIsOne() {
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(1).build();
		InvocationContext context = buildContext(runConfig);
		assertDoesNotThrow(() -> context.incrementLlmCallsCount(),
				"Should not throw on the first call when maxLlmCalls is 1");
	}

	@Test
	@Tag("boundary")
	void incrementLlmCallsCountThrowsExceptionOnSecondCallWhenLimitIsOne() throws LlmCallsLimitExceededException {
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(1).build();
		InvocationContext context = buildContext(runConfig);
		context.incrementLlmCallsCount();
		assertThrows(LlmCallsLimitExceededException.class, () -> context.incrementLlmCallsCount(),
				"Should throw LlmCallsLimitExceededException on the second call when maxLlmCalls is 1");
	}

	@Test
	@Tag("valid")
	void incrementLlmCallsCountSucceedsWhenMaxLlmCallsIsNegative() {
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(-1).build();
		InvocationContext context = buildContext(runConfig);
		assertDoesNotThrow(() -> {
			for (int i = 0; i < 10; i++) {
				context.incrementLlmCallsCount();
			}
		}, "Should not throw when maxLlmCalls is negative (treated as no limit)");
	}

	@Test
	@Tag("boundary")
	void incrementLlmCallsCountIsCumulativeAcrossMultipleIncrements() throws LlmCallsLimitExceededException {
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(4).build();
		InvocationContext context = buildContext(runConfig);
		assertDoesNotThrow(() -> {
			context.incrementLlmCallsCount();
			context.incrementLlmCallsCount();
			context.incrementLlmCallsCount();
			context.incrementLlmCallsCount();
		}, "Should not throw for the first 4 calls when maxLlmCalls is 4");
		assertThrows(LlmCallsLimitExceededException.class, () -> context.incrementLlmCallsCount(),
				"Should throw LlmCallsLimitExceededException on the 5th call when limit is 4");
	}

	@Test
	@Tag("invalid")
	void incrementLlmCallsCountContinuesToThrowAfterLimitIsExceeded() throws LlmCallsLimitExceededException {
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(2).build();
		InvocationContext context = buildContext(runConfig);
		context.incrementLlmCallsCount();
		context.incrementLlmCallsCount();
		assertThrows(LlmCallsLimitExceededException.class, () -> context.incrementLlmCallsCount(),
				"Should throw LlmCallsLimitExceededException on the 3rd call when limit is 2");
		assertThrows(LlmCallsLimitExceededException.class, () -> context.incrementLlmCallsCount(),
				"Should throw LlmCallsLimitExceededException on the 4th call as well");
	}

	@Test
	@Tag("valid")
	void incrementLlmCallsCountWithDefaultRunConfigDoesNotThrow() {
		RunConfig defaultRunConfig = RunConfig.builder().build();
		InvocationContext context = buildContext(defaultRunConfig);
		assertDoesNotThrow(() -> {
			for (int i = 0; i < 100; i++) {
				context.incrementLlmCallsCount();
			}
		}, "Should not throw when using default RunConfig (maxLlmCalls defaults to 500 or 0, no limit enforced in test range)");
	}

	@Test
	@Tag("boundary")
	void incrementLlmCallsCountEnforcesLimitAtCorrectBoundaryForLargeLimit() {
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(1000).build();
		InvocationContext context = buildContext(runConfig);
		assertDoesNotThrow(() -> {
			for (int i = 0; i < 1000; i++) {
				context.incrementLlmCallsCount();
			}
		}, "Should not throw for the first 1000 calls when maxLlmCalls is 1000");
		assertThrows(LlmCallsLimitExceededException.class, () -> context.incrementLlmCallsCount(),
				"Should throw LlmCallsLimitExceededException on the 1001st call when limit is 1000");
	}

	@Test
	@Tag("integration")
	void incrementLlmCallsCountWithFullContextBuilderSucceedsAndThenThrows() throws LlmCallsLimitExceededException {
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(3).build();
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mock(BaseMemoryService.class))
			.pluginManager(mock(PluginManager.class))
			.invocationId(InvocationContext.newInvocationContextId())
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(runConfig)
			.endInvocation(false)
			.build();
		context.incrementLlmCallsCount();
		context.incrementLlmCallsCount();
		context.incrementLlmCallsCount();
		assertThrows(LlmCallsLimitExceededException.class, () -> context.incrementLlmCallsCount(),
				"Should throw LlmCallsLimitExceededException when limit is exceeded in fully built context");
	}

	@Test
	@Tag("integration")
	void incrementLlmCallsCountOnCopiedContextIsIndependentFromOriginal() throws LlmCallsLimitExceededException {
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(3).build();
		InvocationContext original = buildContext(runConfig);
		original.incrementLlmCallsCount();
		original.incrementLlmCallsCount();
		InvocationContext copied = InvocationContext.copyOf(original);
		assertDoesNotThrow(() -> copied.incrementLlmCallsCount(),
				"Copied context should have its own independent InvocationCostManager, so 1st call on copy should succeed");
	}

	@Test
	@Tag("valid")
	void incrementLlmCallsCountSingleCallSucceedsWithValidRunConfig() {
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(10).build();
		InvocationContext context = buildContext(runConfig);
		assertDoesNotThrow(() -> context.incrementLlmCallsCount(),
				"A single call should not throw when maxLlmCalls is 10");
	}

	@Test
	@Tag("invalid")
	void incrementLlmCallsCountThrowsCorrectExceptionType() throws LlmCallsLimitExceededException {
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(1).build();
		InvocationContext context = buildContext(runConfig);
		context.incrementLlmCallsCount();
		LlmCallsLimitExceededException exception = assertThrows(LlmCallsLimitExceededException.class,
				() -> context.incrementLlmCallsCount(), "Should throw exactly LlmCallsLimitExceededException");
		assertTrue(exception instanceof LlmCallsLimitExceededException,
				"Exception should be of type LlmCallsLimitExceededException");
	}

}
