/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=runConfig_09ff6f346f
ROOST_METHOD_SIG_HASH=runConfig_dbfa69ec19

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/june-java-unit/1782282457/source/adk-java/core/src/test/java/com/google/adk/agents/InvocationContextTest.java
Tests:
    "@Test
public void testCreateWithUserContent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).isEmpty();
    assertThat(context.invocationId()).isEqualTo(testInvocationId);
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).hasValue(userContent);
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testCreateWithNullUserContent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.userContent()).isEmpty();
}
"
    "@Test
public void testCreateWithLiveRequestQueue() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).liveRequestQueue(liveRequestQueue).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).hasValue(liveRequestQueue);

    assertThat(context.invocationId()).startsWith("e-");
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).isEmpty();
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testCopyOf() {
    InvocationContext originalContext = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    originalContext.activeStreamingTools().putAll(activeStreamingTools);
    InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
    assertThat(copiedContext).isNotNull();
    assertThat(copiedContext).isNotSameInstanceAs(originalContext);
    assertThat(copiedContext.sessionService()).isEqualTo(originalContext.sessionService());
    assertThat(copiedContext.artifactService()).isEqualTo(originalContext.artifactService());
    assertThat(copiedContext.memoryService()).isEqualTo(originalContext.memoryService());
    assertThat(copiedContext.liveRequestQueue()).isEqualTo(originalContext.liveRequestQueue());
    assertThat(copiedContext.invocationId()).isEqualTo(originalContext.invocationId());
    assertThat(copiedContext.agent()).isEqualTo(originalContext.agent());
    assertThat(copiedContext.session()).isEqualTo(originalContext.session());
    assertThat(copiedContext.userContent()).isEqualTo(originalContext.userContent());
    assertThat(copiedContext.runConfig()).isEqualTo(originalContext.runConfig());
    assertThat(copiedContext.endInvocation()).isEqualTo(originalContext.endInvocation());
    assertThat(copiedContext.activeStreamingTools()).isEqualTo(originalContext.activeStreamingTools());
}
"
    "@Test
public void testGetters() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).isEmpty();
    assertThat(context.invocationId()).isEqualTo(testInvocationId);
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).hasValue(userContent);
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testSetAgent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    BaseAgent newMockAgent = mock(BaseAgent.class);
    context.agent(newMockAgent);
    assertThat(context.agent()).isEqualTo(newMockAgent);
}
"
    "@Test
public void testEquals_sameObject() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(context)).isTrue();
}
"
    "@Test
public void testEquals_null() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(null)).isFalse();
}
"
    "@Test
public void testEquals_sameValues() {
    InvocationContext context1 = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext context2 = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context1.equals(context2)).isTrue();

    assertThat(context2.equals(context1)).isTrue();
}
"
    "@Test
public void testEquals_differentValues() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext contextWithDiffSessionService = InvocationContext.builder().sessionService(
    mock(BaseSessionService.class)).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffInvocationId = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(
    "another-id").agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffAgent = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(
    mock(BaseAgent.class)).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithUserContentEmpty = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithLiveQueuePresent = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).liveRequestQueue(liveRequestQueue).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(contextWithDiffSessionService)).isFalse();
    assertThat(context.equals(contextWithDiffInvocationId)).isFalse();
    assertThat(context.equals(contextWithDiffAgent)).isFalse();
    assertThat(context.equals(contextWithUserContentEmpty)).isFalse();
    assertThat(context.equals(contextWithLiveQueuePresent)).isFalse();
}
"
    "@Test
public void testHashCode_differentValues() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext contextWithDiffSessionService = InvocationContext.builder().sessionService(
    mock(BaseSessionService.class)).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffInvocationId = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(
    "another-id").agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotEqualTo(contextWithDiffSessionService);
    assertThat(context).isNotEqualTo(contextWithDiffInvocationId);
}
"Scenario 1: Verify that runConfig() returns the exact RunConfig instance set during construction via builder

Details:
  TestName: runConfigReturnsConfigSetViaBuilder
  Description: Verifies that the runConfig() method returns the exact same RunConfig instance that was provided to the builder during InvocationContext construction. This ensures that the field is correctly assigned and retrieved without modification.

Execution:
  Arrange:
    - Create a RunConfig instance using RunConfig.builder().build() and assign it to a variable (e.g., expectedRunConfig).
    - Build an InvocationContext using InvocationContext.builder() with all required fields (sessionService, artifactService, memoryService, pluginManager, invocationId, agent, session, userContent) and supply the expectedRunConfig to the .runConfig() builder method.
  Act:
    - Call context.runConfig() on the constructed InvocationContext.
  Assert:
    - Assert that the returned value is equal to expectedRunConfig using assertThat(context.runConfig()).isEqualTo(expectedRunConfig).

Validation:
  This assertion confirms that the runConfig() getter faithfully returns the RunConfig instance stored during construction. It is essential that the run configuration is accessible for controlling agent run behavior, such as enforcing LLM call limits and other runtime settings.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static com.google.common.truth.Truth.assertThat;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.flows.llmflows.ResumabilityConfig;
import com.google.adk.memory.BaseMemoryService;
import com.google.adk.models.LlmCallsLimitExceededException;
import com.google.adk.plugins.PluginManager;
import com.google.adk.sessions.BaseSessionService;
import com.google.adk.sessions.Session;
import com.google.genai.types.Content;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
class InvocationContextRunConfigTest {

	@Mock
	private BaseSessionService mockSessionService;

	@Mock
	private BaseArtifactService mockArtifactService;

	@Mock
	private BaseMemoryService mockMemoryService;

	@Mock
	private PluginManager mockPluginManager;

	@Mock
	private BaseAgent mockAgent;

	@Mock
	private Session mockSession;

	@BeforeEach
  void setUp() {
    when(mockSession.appName()).thenReturn("testApp");
    when(mockSession.userId()).thenReturn("testUser");
  }

	private InvocationContext buildContext(RunConfig runConfig) {
		return InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.pluginManager(mockPluginManager)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(runConfig)
			.build();
	}

	@Test
	@Tag("valid")
	void runConfigReturnsConfigSetViaBuilder() {
		RunConfig expectedRunConfig = RunConfig.builder().build();
		InvocationContext context = buildContext(expectedRunConfig);
		assertThat(context.runConfig()).isEqualTo(expectedRunConfig);
	}

	@Test
	@Tag("valid")
	void runConfigReturnsSameInstanceSetViaBuilder() {
		RunConfig expectedRunConfig = RunConfig.builder().build();
		InvocationContext context = buildContext(expectedRunConfig);
		assertThat(context.runConfig()).isSameInstanceAs(expectedRunConfig);
	}

	@Test
	@Tag("valid")
	void runConfigReturnsConfigWithCustomMaxLlmCalls() {
		RunConfig expectedRunConfig = RunConfig.builder().setMaxLlmCalls(100).build();
		InvocationContext context = buildContext(expectedRunConfig);
		assertThat(context.runConfig()).isEqualTo(expectedRunConfig);
		assertThat(context.runConfig().maxLlmCalls()).isEqualTo(100);
	}

	@Test
	@Tag("valid")
	void runConfigReturnsConfigWithDefaultMaxLlmCalls() {
		RunConfig expectedRunConfig = RunConfig.builder().build();
		InvocationContext context = buildContext(expectedRunConfig);
		assertThat(context.runConfig()).isNotNull();
		assertThat(context.runConfig().maxLlmCalls()).isEqualTo(500);
	}

	@Test
	@Tag("valid")
	void runConfigReturnsSameValueAfterMultipleCalls() {
		RunConfig expectedRunConfig = RunConfig.builder().setMaxLlmCalls(200).build();
		InvocationContext context = buildContext(expectedRunConfig);
		RunConfig firstCall = context.runConfig();
		RunConfig secondCall = context.runConfig();
		assertThat(firstCall).isSameInstanceAs(secondCall);
	}

	@Test
	@Tag("valid")
	void runConfigIsPreservedAfterCopyOf() {
		RunConfig expectedRunConfig = RunConfig.builder().setMaxLlmCalls(300).build();
		InvocationContext original = buildContext(expectedRunConfig);
		InvocationContext copied = InvocationContext.copyOf(original);
		assertThat(copied.runConfig()).isEqualTo(expectedRunConfig);
		assertThat(copied.runConfig()).isSameInstanceAs(original.runConfig());
	}

	@Test
	@Tag("valid")
	void runConfigReturnedFromCreateMethod() {
		RunConfig expectedRunConfig = RunConfig.builder().setMaxLlmCalls(150).build();
		Content userContent = mock(Content.class);
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService,
				"test-invocation-id", mockAgent, mockSession, userContent, expectedRunConfig);
		assertThat(context.runConfig()).isEqualTo(expectedRunConfig);
	}

	@Test
	@Tag("valid")
	void runConfigReturnedFromCreateWithLiveQueueMethod() {
		RunConfig expectedRunConfig = RunConfig.builder().setMaxLlmCalls(75).build();
		LiveRequestQueue liveRequestQueue = new LiveRequestQueue();
		InvocationContext context = InvocationContext.create(mockSessionService, mockArtifactService, mockAgent,
				mockSession, liveRequestQueue, expectedRunConfig);
		assertThat(context.runConfig()).isEqualTo(expectedRunConfig);
	}

	@Test
	@Tag("boundary")
	void runConfigWithZeroMaxLlmCalls() {
		RunConfig expectedRunConfig = RunConfig.builder().setMaxLlmCalls(0).build();
		InvocationContext context = buildContext(expectedRunConfig);
		assertThat(context.runConfig()).isNotNull();
		assertThat(context.runConfig().maxLlmCalls()).isEqualTo(0);
	}

	@Test
	@Tag("boundary")
	void runConfigWithMaxIntMaxLlmCalls() {
		RunConfig expectedRunConfig = RunConfig.builder().setMaxLlmCalls(Integer.MAX_VALUE).build();
		InvocationContext context = buildContext(expectedRunConfig);
		assertThat(context.runConfig()).isNotNull();
		assertThat(context.runConfig().maxLlmCalls()).isEqualTo(Integer.MAX_VALUE);
	}

	@Test
	@Tag("boundary")
	void runConfigWithMinimumMaxLlmCallsOfOne() {
		RunConfig expectedRunConfig = RunConfig.builder().setMaxLlmCalls(1).build();
		InvocationContext context = buildContext(expectedRunConfig);
		assertThat(context.runConfig()).isNotNull();
		assertThat(context.runConfig().maxLlmCalls()).isEqualTo(1);
	}

	@Test
	@Tag("valid")
	void runConfigDoesNotChangeWhenOtherFieldsAreModified() {
		RunConfig expectedRunConfig = RunConfig.builder().setMaxLlmCalls(50).build();
		InvocationContext context = buildContext(expectedRunConfig);
		context.setEndInvocation(true);
		context.agent(mock(BaseAgent.class));
		context.branch("newBranch");
		assertThat(context.runConfig()).isEqualTo(expectedRunConfig);
		assertThat(context.runConfig()).isSameInstanceAs(expectedRunConfig);
	}

	@Test
	@Tag("integration")
	void runConfigIsUsedByIncrementLlmCallsCount() throws LlmCallsLimitExceededException {
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(2).build();
		InvocationContext context = buildContext(runConfig);
		assertThat(context.runConfig().maxLlmCalls()).isEqualTo(2);
		context.incrementLlmCallsCount();
		context.incrementLlmCallsCount();
		org.junit.jupiter.api.Assertions.assertThrows(LlmCallsLimitExceededException.class,
				() -> context.incrementLlmCallsCount());
	}

	@Test
	@Tag("integration")
	void runConfigIsConsistentAcrossContextEquality() {
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(100).build();
		InvocationContext context1 = buildContext(runConfig);
		InvocationContext context2 = buildContext(runConfig);
		assertThat(context1.runConfig()).isEqualTo(context2.runConfig());
	}

	@Test
	@Tag("valid")
	void runConfigNotNullAfterConstruction() {
		RunConfig expectedRunConfig = RunConfig.builder().build();
		InvocationContext context = buildContext(expectedRunConfig);
		assertThat(context.runConfig()).isNotNull();
	}

	@Test
	@Tag("valid")
	void runConfigWithSaveInputBlobsAsArtifactsTrue() {
		RunConfig expectedRunConfig = RunConfig.builder().setSaveInputBlobsAsArtifacts(true).build();
		InvocationContext context = buildContext(expectedRunConfig);
		assertThat(context.runConfig()).isNotNull();
		assertThat(context.runConfig().saveInputBlobsAsArtifacts()).isTrue();
	}

	@Test
	@Tag("valid")
	void runConfigPreservedWithResumabilityConfigInContext() {
		RunConfig expectedRunConfig = RunConfig.builder().setMaxLlmCalls(10).build();
		ResumabilityConfig resumabilityConfig = mock(ResumabilityConfig.class);
		InvocationContext context = InvocationContext.builder()
			.sessionService(mockSessionService)
			.artifactService(mockArtifactService)
			.memoryService(mockMemoryService)
			.pluginManager(mockPluginManager)
			.invocationId("test-invocation-id")
			.agent(mockAgent)
			.session(mockSession)
			.userContent(Optional.empty())
			.runConfig(expectedRunConfig)
			.resumabilityConfig(resumabilityConfig)
			.build();
		assertThat(context.runConfig()).isEqualTo(expectedRunConfig);
		assertThat(context.runConfig()).isSameInstanceAs(expectedRunConfig);
	}

	@Test
	@Tag("integration")
	void runConfigCopiedContextHasSameRunConfigBehavior() throws LlmCallsLimitExceededException {
		RunConfig runConfig = RunConfig.builder().setMaxLlmCalls(3).build();
		InvocationContext original = buildContext(runConfig);
		InvocationContext copied = InvocationContext.copyOf(original);
		assertThat(copied.runConfig()).isEqualTo(original.runConfig());
		assertThat(copied.runConfig().maxLlmCalls()).isEqualTo(3);
		copied.incrementLlmCallsCount();
		copied.incrementLlmCallsCount();
		copied.incrementLlmCallsCount();
		org.junit.jupiter.api.Assertions.assertThrows(LlmCallsLimitExceededException.class,
				() -> copied.incrementLlmCallsCount());
	}

}
