/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=builder_0aac37399c
ROOST_METHOD_SIG_HASH=builder_80041265ae

Scenario 1: Builder Instance Is Not Null

Details:
  TestName: builderReturnsNonNullInstance
  Description: Verifies that the `builder()` method returns a non-null `Builder` instance, ensuring the factory method is properly initialized and functional.

Execution:
  Arrange: No special setup is required since this test directly invokes the static factory method.
  Act: Call `LiveRequest.builder()` and store the result in a variable of type `LiveRequest.Builder`.
  Assert: Use `assertNotNull` to verify the returned builder is not null.

Validation:
  This assertion confirms that the `builder()` method consistently returns a valid, usable `Builder` object. A null return would prevent any further method chaining, making the factory method entirely non-functional and breaking all dependent code paths.

---

Scenario 2: Builder Returns Correct Type

Details:
  TestName: builderReturnsCorrectBuilderType
  Description: Verifies that the object returned by `builder()` is an instance of `LiveRequest.Builder`, ensuring proper type compatibility for method chaining.

Execution:
  Arrange: No special setup required.
  Act: Call `LiveRequest.builder()` and store the result.
  Assert: Use `assertInstanceOf` or `assertTrue` with `instanceof LiveRequest.Builder` to confirm the returned type.

Validation:
  Ensures that the return type contract is satisfied. Returning an incorrect type would cause `ClassCastException` at runtime and break the fluent builder pattern expected by callers of `LiveRequest.builder()`.

---

Scenario 3: Default Close Value Is Set To False

Details:
  TestName: builderDefaultsClosToFalse
  Description: Verifies that when `builder()` is called, the `close` field is pre-initialized to `false` as specified in the method implementation `.close(false)`.

Execution:
  Arrange: Obtain a builder by calling `LiveRequest.builder()`, then set a required field (e.g., `blob`) to satisfy the build precondition.
  Act: Build a `LiveRequest` by calling `.blob(someBlob).build()` on the builder and then call `shouldClose()` on the resulting instance.
  Assert: Use `assertFalse` to verify that `shouldClose()` returns `false`.

Validation:
  The `builder()` method explicitly sets `close(false)` as a default. This test ensures that the default initialization is honored, preventing unintended session closures when the caller does not explicitly set the `close` field.

---

Scenario 4: Default Close Optional Is Present With Value False

Details:
  TestName: builderDefaultCloseOptionalIsPresentWithFalse
  Description: Verifies that the `close()` optional on the built object is present and holds the value `false` when the builder is obtained via `builder()` without further modification.

Execution:
  Arrange: Call `LiveRequest.builder()` and chain a valid `blob` to satisfy the build precondition.
  Act: Build the `LiveRequest` by calling `.build()` and inspect the result of `close()`.
  Assert: Use `assertTrue` to assert `close().isPresent()` and `assertEquals(false, close().get())`.

Validation:
  This distinguishes between the `close` field being absent versus being explicitly set to `false`. Since `builder()` explicitly sets `.close(false)`, the `Optional` should be present and contain `false`, not be empty.

---

Scenario 5: Builder Allows Chaining Content After Default Initialization

Details:
  TestName: builderAllowsChainingContentAfterDefaultInit
  Description: Verifies that the `Builder` returned by `builder()` allows further method chaining, specifically setting a `Content` object after the default `close(false)` is applied.

Execution:
  Arrange: Create a `Content` object using its available API. Call `LiveRequest.builder()`.
  Act: Chain `.content(content).build()` on the returned builder.
  Assert: Use `assertNotNull` to confirm the resulting `LiveRequest` is not null and `assertTrue` to confirm `content().isPresent()`.

Validation:
  Validates that the default initialization of `close` does not interfere with subsequent builder calls. The builder must remain fully functional for all fields after being returned by `builder()`.

---

Scenario 6: Builder Allows Chaining Blob After Default Initialization

Details:
  TestName: builderAllowsChainingBlobAfterDefaultInit
  Description: Verifies that the `Builder` returned by `builder()` supports chaining the `blob` field after the default initialization.

Execution:
  Arrange: Create a `Blob` object using its available API. Call `LiveRequest.builder()`.
  Act: Chain `.blob(blob).build()` on the returned builder.
  Assert: Use `assertNotNull` on the resulting `LiveRequest` and `assertTrue` on `blob().isPresent()`.

Validation:
  Confirms that the builder remains operational for setting the `blob` field after `builder()` initializes `close`. This is critical for real-time mode usage where only a blob is sent.

---

Scenario 7: Builder Allows Overriding Default Close Value To True

Details:
  TestName: builderAllowsOverridingDefaultCloseToTrue
  Description: Verifies that the default `close(false)` set by `builder()` can be overridden by calling `.close(true)` on the returned builder.

Execution:
  Arrange: Call `LiveRequest.builder()`.
  Act: Chain `.close(true).build()` and call `shouldClose()` on the resulting `LiveRequest`.
  Assert: Use `assertTrue` to verify that `shouldClose()` returns `true`.

Validation:
  Ensures that the default `close(false)` is merely a default and not a locked value. Callers must be able to override it to `true` to signal the connection should be closed after the request.

---

Scenario 8: Builder Allows Setting Close To Null After Default Initialization

Details:
  TestName: builderAllowsSettingCloseToNullOverridingDefault
  Description: Verifies that after `builder()` sets `close` to `false`, passing `null` to `.close(Boolean)` overrides the default, and the build will fail if no other field is set (per Preconditions check).

Execution:
  Arrange: Call `LiveRequest.builder()`.
  Act: Chain `.close((Boolean) null)` and attempt to call `.build()` without setting `content` or `blob`.
  Assert: Expect an `IllegalStateException` to be thrown, validating that the Preconditions check catches the empty state.

Validation:
  This tests the interaction between the default-setting behavior of `builder()` and the ability to nullify it. The build precondition requires at least one of `content`, `blob`, or `close` to be present, so nullifying the default without setting another field must fail.

---

Scenario 9: Multiple Calls To builder() Return Independent Instances

Details:
  TestName: multipleBuilderCallsReturnIndependentInstances
  Description: Verifies that each invocation of `builder()` returns a new, independent `Builder` instance, preventing shared mutable state between multiple build chains.

Execution:
  Arrange: No additional setup required.
  Act: Call `LiveRequest.builder()` twice and store the results as `builder1` and `builder2`.
  Assert: Use `assertNotSame` to verify that `builder1` and `builder2` are distinct object references.

Validation:
  Shared builder instances would cause severe concurrency and correctness issues. Each call to `builder()` must produce a fresh builder to allow independent construction of multiple `LiveRequest` objects without cross-contamination of fields.

---

Scenario 10: Builder Returned Can Build A Valid LiveRequest With Close Only

Details:
  TestName: builderCanBuildValidRequestWithCloseOnly
  Description: Verifies that the `Builder` returned by `builder()`, which defaults `close` to `false`, can produce a valid `LiveRequest` without requiring any other fields, since `close` is already set.

Execution:
  Arrange: Call `LiveRequest.builder()` which pre-sets `close(false)`.
  Act: Immediately call `.build()` on the returned builder without setting `content` or `blob`.
  Assert: Use `assertNotNull` to verify the resulting `LiveRequest` is a valid object, and `assertFalse` on `shouldClose()`.

Validation:
  Since `builder()` pre-initializes `close` to `false`, the `Preconditions.checkState` condition (`close().isPresent()` is true) should be satisfied immediately, allowing `build()` to succeed without additional field assignments. This is a core behavioral guarantee of the method.

---

Scenario 11: Builder Preserves Close False When Content Is Also Set

Details:
  TestName: builderPreservesDefaultCloseFalseWhenContentIsSet
  Description: Verifies that the default `close(false)` is retained alongside a separately set `content` field when building the `LiveRequest`.

Execution:
  Arrange: Create a `Content` object. Call `LiveRequest.builder()`.
  Act: Chain `.content(content).build()` and inspect both `close()` and `content()` on the result.
  Assert: Use `assertFalse` on `shouldClose()` and `assertTrue` on `content().isPresent()`.

Validation:
  Confirms that setting additional fields does not unintentionally reset or remove the default `close(false)` value. Both fields should coexist in the final built object, reflecting the intended multi-field behavior of the builder.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;

import com.google.genai.types.Blob;
import com.google.genai.types.Content;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

public class LiveRequestBuilderTest {

  @Test
  @Tag("valid")
  void builderReturnsNonNullInstance() {
    LiveRequest.Builder builder = LiveRequest.builder();
    assertNotNull(builder, "builder() should return a non-null Builder instance");
  }

  @Test
  @Tag("valid")
  void builderReturnsCorrectBuilderType() {
    Object builder = LiveRequest.builder();
    assertInstanceOf(
        LiveRequest.Builder.class,
        builder,
        "builder() should return an instance of LiveRequest.Builder");
  }

  @Test
  @Tag("valid")
  void builderDefaultsCloseToFalse() {
    LiveRequest request = LiveRequest.builder().build();
    assertFalse(request.shouldClose(), "Default close value should be false when using builder()");
  }

  @Test
  @Tag("valid")
  void builderDefaultCloseOptionalIsPresentWithFalse() {
    LiveRequest request = LiveRequest.builder().build();
    assertTrue(
        request.close().isPresent(),
        "close() Optional should be present after builder() initialization");
    assertEquals(
        false, request.close().get(), "close() Optional should contain false as default value");
  }

  @Test
  @Tag("valid")
  void builderAllowsChainingContentAfterDefaultInit() {
    Content content = Content.builder().role("user").build();
    LiveRequest.Builder builder = LiveRequest.builder();
    LiveRequest request = builder.content(content).build();
    assertNotNull(request, "LiveRequest should not be null after setting content");
    assertTrue(
        request.content().isPresent(),
        "content() should be present after being set on the builder");
  }

  @Test
  @Tag("valid")
  void builderAllowsChainingBlobAfterDefaultInit() {
    Blob blob = Blob.builder().mimeType("audio/pcm").build();
    LiveRequest.Builder builder = LiveRequest.builder();
    LiveRequest request = builder.blob(blob).build();
    assertNotNull(request, "LiveRequest should not be null after setting blob");
    assertTrue(
        request.blob().isPresent(), "blob() should be present after being set on the builder");
  }

  @Test
  @Tag("valid")
  void builderAllowsOverridingDefaultCloseToTrue() {
    LiveRequest request = LiveRequest.builder().close(true).build();
    assertTrue(
        request.shouldClose(),
        "shouldClose() should return true after overriding default close with true");
  }

  @Test
  @Tag("invalid")
  void builderAllowsSettingCloseToNullOverridingDefault() {
    assertThrows(
        IllegalStateException.class,
        () -> {
          LiveRequest.builder().close((Boolean) null).build();
        },
        "build() should throw IllegalStateException when close is null and no other field is set");
  }

  @Test
  @Tag("valid")
  void multipleBuilderCallsReturnIndependentInstances() {
    LiveRequest.Builder builder1 = LiveRequest.builder();
    LiveRequest.Builder builder2 = LiveRequest.builder();
    assertNotSame(
        builder1,
        builder2,
        "Each call to builder() should return a new, independent Builder instance");
  }

  @Test
  @Tag("valid")
  void builderCanBuildValidRequestWithCloseOnly() {
    LiveRequest request = LiveRequest.builder().build();
    assertNotNull(
        request,
        "builder() should produce a valid LiveRequest without additional field assignments");
    assertFalse(
        request.shouldClose(),
        "shouldClose() should return false when only default initialization is done");
  }

  @Test
  @Tag("valid")
  void builderPreservesDefaultCloseFalseWhenContentIsSet() {
    Content content = Content.builder().role("user").build();
    LiveRequest request = LiveRequest.builder().content(content).build();
    assertFalse(
        request.shouldClose(), "Default close(false) should be preserved when content is also set");
    assertTrue(
        request.content().isPresent(), "content() should be present on the built LiveRequest");
  }

  @Test
  @Tag("integration")
  void builderIndependentInstancesDoNotShareState() {
    LiveRequest.Builder builder1 = LiveRequest.builder();
    LiveRequest.Builder builder2 = LiveRequest.builder();
    builder1.close(true);
    LiveRequest request1 = builder1.build();
    LiveRequest request2 = builder2.build();
    assertTrue(request1.shouldClose(), "builder1's close should be true after explicit override");
    assertFalse(
        request2.shouldClose(),
        "builder2's close should remain false, unaffected by builder1's state");
  }

  @Test
  @Tag("valid")
  void builderDefaultCloseOptionalIsNotEmpty() {
    LiveRequest request = LiveRequest.builder().build();
    assertFalse(
        request.close().isEmpty(),
        "close() Optional should not be empty after builder() sets default close(false)");
  }

  @Test
  @Tag("boundary")
  void builderWithBlobAndDefaultCloseFalseIsValid() {
    Blob blob = Blob.builder().mimeType("audio/pcm").build();
    LiveRequest request = LiveRequest.builder().blob(blob).build();
    assertTrue(request.blob().isPresent(), "blob() should be present in the built LiveRequest");
    assertTrue(
        request.close().isPresent(), "close() should be present as default false alongside blob");
    assertFalse(
        request.shouldClose(),
        "shouldClose() should be false when default is retained alongside blob");
  }

  @Test
  @Tag("boundary")
  void builderWithCloseSetToFalseExplicitlyMatchesDefault() {
    LiveRequest defaultRequest = LiveRequest.builder().build();
    LiveRequest explicitRequest = LiveRequest.builder().close(false).build();
    assertEquals(
        defaultRequest.shouldClose(),
        explicitRequest.shouldClose(),
        "Explicit close(false) should produce same result as default initialization");
    assertEquals(
        defaultRequest.close().get(),
        explicitRequest.close().get(),
        "Both requests should have close Optional containing false");
  }

  @Test
  @Tag("integration")
  void builderIntegrationWithContentAndCloseOverride() {
    Content content = Content.builder().role("model").build();
    LiveRequest request = LiveRequest.builder().content(content).close(true).build();
    assertNotNull(request, "Built LiveRequest should not be null");
    assertTrue(request.content().isPresent(), "content() should be present");
    assertTrue(request.close().isPresent(), "close() should be present");
    assertTrue(request.shouldClose(), "shouldClose() should return true after explicit override");
  }

  @Test
  @Tag("integration")
  void builderIntegrationWithBlobAndCloseOverride() {
    Blob blob = Blob.builder().mimeType("video/webm").build();
    LiveRequest request = LiveRequest.builder().blob(blob).close(true).build();
    assertNotNull(request, "Built LiveRequest should not be null");
    assertTrue(request.blob().isPresent(), "blob() should be present");
    assertTrue(request.close().isPresent(), "close() should be present");
    assertTrue(request.shouldClose(), "shouldClose() should return true after explicit override");
  }
}
