/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test june-java-unit using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-6

ROOST_METHOD_HASH=builder_0aac37399c
ROOST_METHOD_SIG_HASH=builder_80041265ae

Scenario 1: Verify That builder() Returns a Non-Null Builder Instance

Details:
  TestName: builderReturnsNonNullInstance
  Description: Verifies that the static builder() method returns a non-null Builder instance,
               ensuring the factory method is properly initialized and usable.
Execution:
  Arrange: No special setup is required since builder() is a static factory method.
  Act: Call LiveRequest.builder() to obtain a Builder instance.
  Assert: Assert that the returned Builder instance is not null using assertNotNull().
Validation:
  The assertion confirms that the builder() method successfully creates and returns a Builder object.
  This is a fundamental test to ensure the factory method is operational and does not return null,
  which would cause NullPointerExceptions downstream in the application.


Scenario 2: Verify That the Builder Has close Set to false by Default

Details:
  TestName: builderSetsCloseToFalseByDefault
  Description: Verifies that the builder returned by builder() has the close field pre-initialized
               to false, confirming the default value is correctly applied without any additional
               configuration.
Execution:
  Arrange: No special setup is required.
  Act: Call LiveRequest.builder() to get a Builder, then call build() directly after setting
       a valid content field (e.g., using content(Optional.empty()) with blob or any required field).
       Since close is already set to false, build() should succeed.
       Obtain the resulting LiveRequest object.
  Assert: Assert that the resulting LiveRequest's shouldClose() returns false,
          confirming that close was pre-set to false by builder().
Validation:
  The assertion verifies that the builder() method pre-sets close to false.
  This default behavior is critical to prevent unintended connection closures when a developer
  creates a new LiveRequest without explicitly setting the close field.


Scenario 3: Verify That builder() Returns a Fresh Builder on Each Invocation

Details:
  TestName: builderReturnsFreshInstanceOnEachCall
  Description: Verifies that each call to builder() returns a new, independent Builder instance,
               ensuring that different Builder objects do not share state.
Execution:
  Arrange: No special setup is required.
  Act: Call LiveRequest.builder() twice to obtain two separate Builder instances (builder1 and builder2).
  Assert: Assert that builder1 and builder2 are not the same object reference using assertNotSame().
Validation:
  The assertion confirms that builder() creates a new Builder object on every invocation.
  This is important to ensure that building multiple LiveRequest objects independently does not
  result in shared mutable state, which could lead to subtle and hard-to-detect bugs.


Scenario 4: Verify That Builder Returned by builder() Can Successfully Build a LiveRequest

Details:
  TestName: builderCanBuildValidLiveRequest
  Description: Verifies that the Builder returned by builder() is fully functional and can
               produce a valid LiveRequest object when build() is called, given that the
               close field is already pre-set to false.
Execution:
  Arrange: No special setup is required since close is pre-set by builder().
  Act: Call LiveRequest.builder() to get a Builder and immediately call build() without
       setting any additional fields (close is already set to false by builder()).
  Assert: Assert that the resulting LiveRequest object is not null using assertNotNull().
Validation:
  The assertion confirms that the default Builder state (with close set to false) satisfies
  the Preconditions.checkState constraint that requires at least one of content, blob, or close
  to be present. This test ensures the builder() method creates a usable Builder that produces
  a valid LiveRequest without requiring additional field configuration.


Scenario 5: Verify That the Built LiveRequest Has close Present as Optional

Details:
  TestName: builtLiveRequestHasClosePresentInOptional
  Description: Verifies that after calling builder() and subsequently build(), the resulting
               LiveRequest has the close field present as a non-empty Optional with a value of false.
Execution:
  Arrange: No special setup is required.
  Act: Call LiveRequest.builder().build() to create a LiveRequest.
  Assert: Assert that the resulting LiveRequest's close() Optional is present (isPresent() returns true)
          and that the value inside the Optional equals false.
Validation:
  The assertion verifies that close() returns Optional.of(false), not Optional.empty().
  This confirms that builder() properly pre-populates the close field using the Builder's
  close(false) call, which is critical for downstream logic that relies on the Optional's
  presence to determine whether a close value was explicitly set.


Scenario 6: Verify That shouldClose() Returns false on a LiveRequest Built Directly from builder()

Details:
  TestName: shouldCloseReturnsFalseOnDefaultBuilder
  Description: Verifies that shouldClose() returns false on a LiveRequest built directly from
               the default builder(), confirming the convenience method correctly reads the
               pre-set close field value.
Execution:
  Arrange: No special setup is required.
  Act: Call LiveRequest.builder().build() to create a LiveRequest, then invoke shouldClose() on it.
  Assert: Assert that shouldClose() returns false using assertFalse().
Validation:
  The assertion ensures that shouldClose() correctly interprets the default close field value
  set by builder(). This is important for application logic that uses shouldClose() to determine
  whether to terminate a live connection after sending the request.


Scenario 7: Verify That builder() Returns an Instance of Builder Class

Details:
  TestName: builderReturnsInstanceOfBuilderClass
  Description: Verifies that the object returned by builder() is an instance of LiveRequest.Builder,
               ensuring the correct type is returned by the factory method.
Execution:
  Arrange: No special setup is required.
  Act: Call LiveRequest.builder() and capture the result.
  Assert: Assert that the returned object is an instance of LiveRequest.Builder using assertInstanceOf()
          or assertTrue() with instanceof.
Validation:
  The assertion confirms the return type of builder() is the expected LiveRequest.Builder class.
  This is important for type safety and ensures that callers receive a properly typed Builder
  object that exposes all the expected builder methods.


Scenario 8: Verify That Builder Produced by builder() Allows Overriding the Default close Value

Details:
  TestName: builderAllowsOverridingDefaultCloseValue
  Description: Verifies that the default close value of false set by builder() can be overridden
               by calling close(true) on the returned Builder, ensuring the default is not immutable
               and can be changed for use cases that require closing the connection.
Execution:
  Arrange: No special setup is required.
  Act: Call LiveRequest.builder(), then call close(true) on the Builder to override the default,
       then call build() to obtain the resulting LiveRequest.
  Assert: Assert that shouldClose() on the built LiveRequest returns true using assertTrue().
Validation:
  The assertion verifies that the pre-set close(false) value is not locked and can be overridden
  by the caller. This is important for use cases where a developer explicitly wants to close the
  live connection after sending the request, confirming the builder pattern's flexibility.


Scenario 9: Verify That Builder Produced by builder() Allows Setting a Content Field

Details:
  TestName: builderAllowsSettingContentField
  Description: Verifies that the Builder returned by builder() allows setting the content field
               via content(Optional<Content>) without any issue, ensuring all Builder methods
               remain accessible and functional after builder() initializes the close field.
Execution:
  Arrange: Create an Optional.empty() for Content to be used as the content value.
  Act: Call LiveRequest.builder(), chain content(Optional.empty()), and then call build().
  Assert: Assert that the resulting LiveRequest's content() returns Optional.empty()
          using assertEquals() or assertTrue() on content().isEmpty().
Validation:
  The assertion confirms that calling builder() and then chaining content() works correctly.
  This verifies that the pre-initialization of close in builder() does not interfere with
  subsequent Builder method calls, ensuring the full Builder API remains functional.


Scenario 10: Verify That Builder Produced by builder() Allows Setting a Blob Field

Details:
  TestName: builderAllowsSettingBlobField
  Description: Verifies that the Builder returned by builder() allows setting the blob field
               via blob(Optional<Blob>) without issue, confirming all Builder methods are
               accessible after builder() pre-sets the close field.
Execution:
  Arrange: Create an Optional.empty() for Blob to pass to the blob() method.
  Act: Call LiveRequest.builder(), chain blob(Optional.empty()), then call build().
  Assert: Assert that the resulting LiveRequest's blob() returns Optional.empty()
          using assertTrue() on blob().isEmpty().
Validation:
  The assertion confirms that setting the blob field on the Builder returned by builder()
  functions correctly and does not conflict with the pre-set close value.
  This ensures the builder() factory method produces a fully flexible Builder object
  where all fields can be set independently.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;

import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

class LiveRequestBuilderTest {

  @Test
  @Tag("valid")
  void builderReturnsNonNullInstance() {
    LiveRequest.Builder builder = LiveRequest.builder();
    assertNotNull(builder, "builder() should return a non-null Builder instance");
  }

  @Test
  @Tag("valid")
  void builderSetsCloseToFalseByDefault() {
    LiveRequest liveRequest = LiveRequest.builder().build();
    assertFalse(liveRequest.shouldClose(), "Default builder should pre-set close to false");
  }

  @Test
  @Tag("valid")
  void builderReturnsFreshInstanceOnEachCall() {
    LiveRequest.Builder builder1 = LiveRequest.builder();
    LiveRequest.Builder builder2 = LiveRequest.builder();
    assertNotSame(
        builder1,
        builder2,
        "Each call to builder() should return a new, independent Builder instance");
  }

  @Test
  @Tag("valid")
  void builderCanBuildValidLiveRequest() {
    LiveRequest liveRequest = LiveRequest.builder().build();
    assertNotNull(
        liveRequest, "Builder with default close=false should successfully build a LiveRequest");
  }

  @Test
  @Tag("valid")
  void builtLiveRequestHasClosePresentInOptional() {
    LiveRequest liveRequest = LiveRequest.builder().build();
    assertTrue(
        liveRequest.close().isPresent(),
        "close() Optional should be present after building with builder()");
    assertEquals(
        Boolean.FALSE,
        liveRequest.close().get(),
        "close() Optional value should be false by default");
  }

  @Test
  @Tag("valid")
  void shouldCloseReturnsFalseOnDefaultBuilder() {
    LiveRequest liveRequest = LiveRequest.builder().build();
    assertFalse(
        liveRequest.shouldClose(),
        "shouldClose() should return false on a LiveRequest built with default builder()");
  }

  @Test
  @Tag("valid")
  void builderReturnsInstanceOfBuilderClass() {
    Object builder = LiveRequest.builder();
    assertNotNull(builder, "builder() should not return null");
    assertInstanceOf(
        LiveRequest.Builder.class,
        builder,
        "builder() should return an instance of LiveRequest.Builder");
  }

  @Test
  @Tag("valid")
  void builderAllowsOverridingDefaultCloseValue() {
    LiveRequest liveRequest = LiveRequest.builder().close(true).build();
    assertTrue(
        liveRequest.shouldClose(),
        "shouldClose() should return true when close(true) overrides the default");
  }

  @Test
  @Tag("valid")
  void builderAllowsSettingContentField() {
    LiveRequest liveRequest = LiveRequest.builder().content(Optional.empty()).build();
    assertNotNull(
        liveRequest, "LiveRequest built with content(Optional.empty()) should not be null");
    assertTrue(
        liveRequest.content().isEmpty(),
        "content() should return Optional.empty() when set to Optional.empty()");
  }

  @Test
  @Tag("valid")
  void builderAllowsSettingBlobField() {
    LiveRequest liveRequest = LiveRequest.builder().blob(Optional.empty()).build();
    assertNotNull(liveRequest, "LiveRequest built with blob(Optional.empty()) should not be null");
    assertTrue(
        liveRequest.blob().isEmpty(),
        "blob() should return Optional.empty() when set to Optional.empty()");
  }

  @Test
  @Tag("boundary")
  void builderWithCloseSetToFalseExplicitly() {
    LiveRequest liveRequest = LiveRequest.builder().close(false).build();
    assertFalse(
        liveRequest.shouldClose(),
        "shouldClose() should return false when explicitly set to false");
    assertTrue(
        liveRequest.close().isPresent(),
        "close() Optional should be present when explicitly set to false");
    assertEquals(
        Boolean.FALSE,
        liveRequest.close().get(),
        "close() Optional value should be false when explicitly set");
  }

  @Test
  @Tag("valid")
  void multipleBuildsFromSameBuilderAreIndependent() {
    LiveRequest.Builder builder1 = LiveRequest.builder();
    LiveRequest.Builder builder2 = LiveRequest.builder().close(true);
    LiveRequest request1 = builder1.build();
    LiveRequest request2 = builder2.build();
    assertFalse(
        request1.shouldClose(), "First request built with default builder should have close=false");
    assertTrue(
        request2.shouldClose(), "Second request built with close(true) should have close=true");
  }

  @Test
  @Tag("integration")
  void builderChainWithAllOptionalFieldsEmpty() {
    LiveRequest liveRequest =
        LiveRequest.builder().content(Optional.empty()).blob(Optional.empty()).close(false).build();
    assertNotNull(liveRequest, "LiveRequest with all optional fields empty should not be null");
    assertTrue(liveRequest.content().isEmpty(), "content() should be empty Optional");
    assertTrue(liveRequest.blob().isEmpty(), "blob() should be empty Optional");
    assertFalse(liveRequest.shouldClose(), "shouldClose() should be false");
  }

  @Test
  @Tag("integration")
  void builderProducesConsistentResultsForSameConfiguration() {
    LiveRequest request1 = LiveRequest.builder().build();
    LiveRequest request2 = LiveRequest.builder().build();
    assertEquals(
        request1.shouldClose(),
        request2.shouldClose(),
        "Two LiveRequests built with default builder() should have the same shouldClose() value");
    assertEquals(
        request1.close().isPresent(),
        request2.close().isPresent(),
        "Two LiveRequests built with default builder() should have the same close Optional presence");
  }

  @Test
  @Tag("valid")
  void builderCloseOptionalPresentAfterOverride() {
    LiveRequest liveRequest = LiveRequest.builder().close(true).build();
    assertTrue(
        liveRequest.close().isPresent(),
        "close() Optional should be present after overriding with close(true)");
    assertEquals(
        Boolean.TRUE,
        liveRequest.close().get(),
        "close() Optional value should be true after overriding");
  }
}
