/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Open AI and AI Model gpt-5-nano

ROOST_METHOD_HASH=builder_2187989d2f
ROOST_METHOD_SIG_HASH=builder_80041265ae

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/unit-java-adk/883911c6-f994-442d-9414-e32d6f1dbc6b/source/adk-java/core/src/test/java/com/google/adk/agents/LoopAgentTest.java
Tests:
    "@Test
public void runAsync_withNoAgents_returnsEmptyEvents() {
    LoopAgent loopAgent = LoopAgent.builder().name("loopAgent").subAgents(ImmutableList.of()).build();
    InvocationContext invocationContext = createInvocationContext(loopAgent);
    List<Event> events = loopAgent.runAsync(invocationContext).toList().blockingGet();
    assertThat(events).isEmpty();
}
"
    "@Test
public void runAsync_withSingleAgent_singleIteration_returnsEvents() {
    Event event1 = createEvent("event1");
    Event event2 = createEvent("event2");
    TestBaseAgent subAgent = createSubAgent("subAgent", Flowable.just(event1, event2));
    LoopAgent loopAgent = LoopAgent.builder().name("loopAgent").subAgents(ImmutableList.of(subAgent)).maxIterations(1).build();
    InvocationContext invocationContext = createInvocationContext(loopAgent);
    List<Event> events = loopAgent.runAsync(invocationContext).toList().blockingGet();
    assertThat(events).containsExactly(event1, event2).inOrder();
}
"
    "@Test
public void runAsync_withSingleAgent_multipleIterations_returnsEvents() {
    Event event1 = createEvent("event1");
    Event event2 = createEvent("event2");
    Event event3 = createEvent("event3");
    Event event4 = createEvent("event4");
    TestBaseAgent subAgent = createSubAgent("subAgent", Flowable.just(event1, event2), Flowable.just(event3, event4));
    LoopAgent loopAgent = LoopAgent.builder().name("loopAgent").subAgents(ImmutableList.of(subAgent)).maxIterations(2).build();
    InvocationContext invocationContext = createInvocationContext(loopAgent);
    List<Event> events = loopAgent.runAsync(invocationContext).toList().blockingGet();
    assertThat(events).containsExactly(event1, event2, event3, event4).inOrder();
}
"
    "@Test
public void runAsync_withMultipleAgents_loopsAndReturnsEvents() {
    Event event1 = createEvent("event1");
    Event event2 = createEvent("event2");
    Event event3 = createEvent("event3");
    Event event4 = createEvent("event4");
    TestBaseAgent subAgent1 = createSubAgent("subAgent1", Flowable.just(event1), Flowable.just(event3));
    TestBaseAgent subAgent2 = createSubAgent("subAgent2", Flowable.just(event2), Flowable.just(event4));
    LoopAgent loopAgent = LoopAgent.builder().name("loopAgent").subAgents(ImmutableList.of(subAgent1, subAgent2)).maxIterations(2).build();
    InvocationContext invocationContext = createInvocationContext(loopAgent);
    List<Event> events = loopAgent.runAsync(invocationContext).toList().blockingGet();
    assertThat(events).containsExactly(event1, event2, event3, event4).inOrder();
}
"
    "@Test
public void runAsync_withEscalateAction_returnsEventsUpToEscalateAndStops() {
    Event event1 = createEvent("event1");
    Event escalateEvent2 = createEscalateEvent("escalate2");
    Event event3 = createEvent("event3");
    Event event4 = createEvent("event4");
    Flowable<Event> subAgent1Events = Flowable.just(event1, escalateEvent2, event3);
    Flowable<Event> subAgent2Events = Flowable.just(event4);
    TestBaseAgent subAgent1 = createSubAgent("subAgent1", subAgent1Events);
    TestBaseAgent subAgent2 = createSubAgent("subAgent2", subAgent2Events);
    LoopAgent loopAgent = LoopAgent.builder().name("loopAgent").subAgents(ImmutableList.of(subAgent1, subAgent2)).maxIterations(1).build();
    InvocationContext invocationContext = createInvocationContext(loopAgent);
    List<Event> events = loopAgent.runAsync(invocationContext).toList().blockingGet();
    assertThat(events).containsExactly(event1, escalateEvent2).inOrder();
}
"
    "@Test
public void runAsync_withEscalateAction_loopsAndReturnsEventsUpToEscalateAndStops() {
    Event event1 = createEvent("event1");
    Event event2 = createEvent("event2");
    Event event3 = createEvent("event3");
    Event event4 = createEvent("event4");
    Event escalateEvent5 = createEscalateEvent("escalate5");
    Event escalateEvent6 = createEscalateEvent("escalate6");
    TestBaseAgent subAgent1 = createSubAgent("subAgent1", Flowable.just(event1, event2), Flowable.just(event4));
    TestBaseAgent subAgent2 = createSubAgent("subAgent2", Flowable.just(event3), Flowable.just(escalateEvent5, escalateEvent6));
    LoopAgent loopAgent = LoopAgent.builder().name("loopAgent").subAgents(ImmutableList.of(subAgent1, subAgent2)).maxIterations(3).build();
    InvocationContext invocationContext = createInvocationContext(loopAgent);
    List<Event> events = loopAgent.runAsync(invocationContext).toList().blockingGet();
    assertThat(events).containsExactly(event1, event2, event3, event4, escalateEvent5).inOrder();
}
"
    "@Test
public void runAsync_withNoMaxIterations_keepsLooping() {
    Event event1 = createEvent("event1");
    Event event2 = createEvent("event2");
    TestBaseAgent subAgent = createSubAgent("subAgent", () -> Flowable.just(event1, event2));
    LoopAgent loopAgent = LoopAgent.builder().name("loopAgent").subAgents(ImmutableList.of(subAgent)).maxIterations(Optional.empty()).build();
    InvocationContext invocationContext = createInvocationContext(loopAgent);
    Iterable<Event> result = loopAgent.runAsync(invocationContext).blockingIterable();
    Iterable<Event> first10Events = Iterables.limit(result, 10);
    assertThat(first10Events).containsExactly(event1, event2, event1, event2, event1, event2, event1, event2, event1, event2).inOrder();
}
"
    "@Test
public void runAsync_withEndInvocationInSubAgentCallback_stopsSubAgentButLoopContinues() {
    AtomicInteger normalAgentRunCount = new AtomicInteger(0);
    TestBaseAgent normalAgent = createSubAgent("NormalAgent", () -> {
        int count = normalAgentRunCount.incrementAndGet();
        return Flowable.just(createEvent("Normal Agent Run " + count));
    });
    AtomicInteger subAgent2CallbackCount = new AtomicInteger(0);
    AtomicInteger subAgent2RunCount = new AtomicInteger(0);
    BeforeAgentCallback subAgent2BeforeCallback = (callbackContext) -> {
        int callbackCount = subAgent2CallbackCount.incrementAndGet();
        if (callbackCount > 1) {
            return Maybe.just(Content.fromParts(Part.fromText("Exit Callback Triggered After " + callbackCount + " Runs")));
        }
        return Maybe.empty();
    };
    TestBaseAgent earlyExitAgent = new TestBaseAgent("EarlyExitAgent", "An agent that exits early after its callback is called once", () -> {
        int count = subAgent2RunCount.incrementAndGet();
        return Flowable.just(createEvent("Early Exit Agent Run " + count));
    },
    ImmutableList.of(),
    ImmutableList.of(subAgent2BeforeCallback),
    ImmutableList.of());
    LoopAgent loopAgent = LoopAgent.builder().name("loopAgent").subAgents(ImmutableList.of(normalAgent, earlyExitAgent)).maxIterations(3).build();
    InvocationContext invocationContext = createInvocationContext(loopAgent);
    List<Event> events = loopAgent.runAsync(invocationContext).toList().blockingGet();
    ImmutableList<String> eventTexts = events.stream().filter(e -> e.content().isPresent()).map(e -> e.content().get().text()).collect(toImmutableList());
    assertThat(eventTexts).containsExactly("content for event Normal Agent Run 1", "content for event Early Exit Agent Run 1", "content for event Normal Agent Run 2", "Exit Callback Triggered After 2 Runs", "content for event Normal Agent Run 3", "Exit Callback Triggered After 3 Runs").inOrder();
    assertThat(normalAgentRunCount.get()).isEqualTo(3);
    assertThat(subAgent2RunCount.get()).isEqualTo(1);
}
"Scenario 1: Builder returns a non-null Builder instance from LoopAgent.builder()

Details:
  TestName: builderReturnsNonNullInstance
  Description: Verify that invoking LoopAgent.builder() returns a valid Builder object and not null, indicating the builder pattern is accessible and ready to configure.
Execution:
  Arrange: None.
  Act: Call LoopAgent.builder() and capture the returned object.
  Assert: The result is not null and is an instance of LoopAgent.Builder.
Validation:
  The test confirms the factory method provides a concrete Builder, ensuring the fluent configuration path is available for subsequent setup steps.


*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;

import java.util.Collections;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

public class LoopAgentBuilderTest extends BaseAgent {

  public LoopAgentBuilderTest() {
    super(
        "dummy",
        "dummy",
        Collections.emptyList(),
        Collections.emptyList(),
        Collections.emptyList());
  }

  @Test
  @Tag("valid")
  public void testBuilderReturnsNonNullInstance() {
    LoopAgent.Builder builder = LoopAgent.builder();
    assertNotNull(builder);
    assertTrue(builder instanceof LoopAgent.Builder);
  }

  @Test
  @Tag("valid")
  public void testBuilderReturnsDistinctInstancesOnConsecutiveCalls() {
    LoopAgent.Builder b1 = LoopAgent.builder();
    LoopAgent.Builder b2 = LoopAgent.builder();
    assertNotNull(b1);
    assertNotNull(b2);
    assertNotSame(b1, b2);
  }
}
