/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Azure Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=runAsyncImpl_d6001493a1
ROOST_METHOD_SIG_HASH=runAsyncImpl_99c1534d6f

[
  {
    "description": "When runAsyncImpl is called with multiple subAgents and maxIterations set to a value greater than 1, it repeats the concatMapped events up to maxIterations or until hasEscalateAction returns true.",
    "category": "critical",
    "source": "llm",
    "priority": "high"
  },
  {
    "description": "When runAsyncImpl is called and one or more subAgent events trigger hasEscalateAction, the Flowable terminates early as expected.",
    "category": "critical",
    "source": "llm",
    "priority": "high"
  },
  {
    "description": "When runAsyncImpl is called with subAgents as an empty list, it returns an empty Flowable (not just null).",
    "category": "critical",
    "source": "audit",
    "priority": "high"
  },
  {
    "description": "When runAsyncImpl is called with maxIterations present and set to 1, it only invokes one iteration even if hasEscalateAction never fires.",
    "category": "critical",
    "source": "audit",
    "priority": "high"
  },
  {
    "description": "Verify a non-default branch in runAsyncImpl.",
    "category": "branch",
    "source": "seeded",
    "priority": "medium"
  },
  {
    "description": "Verify an additional edge or guard branch in runAsyncImpl.",
    "category": "branch",
    "source": "seeded",
    "priority": "medium"
  },
  {
    "description": "Verify the main expected behavior of runAsyncImpl.",
    "category": "happy_path",
    "source": "seeded",
    "priority": "high"
  },
  {
    "description": "When runAsyncImpl is called with subAgents as null, it returns an empty Flowable (empty event list).",
    "category": "recommended",
    "source": "llm",
    "priority": "medium"
  },
  {
    "description": "runAsyncImpl returns Flowable.empty() when subAgents() is empty.",
    "category": "branch",
    "source": "verified",
    "priority": "high"
  },
  {
    "description": "runAsyncImpl returns Flowable.empty() when subAgents() is null (defensive guard branch).",
    "category": "branch",
    "source": "verified",
    "priority": "medium"
  },
  {
    "description": "runAsyncImpl emits events in expected order from each subAgent in subAgents(), repeats up to maxIterations if specified, and stops early if hasEscalateAction returns true.",
    "category": "happy_path",
    "source": "verified",
    "priority": "high"
  }
]
*/

// ********RoostGPT********

/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.adk.agents;

import static com.google.adk.testing.TestUtils.createEscalateEvent;
import static com.google.adk.testing.TestUtils.createEvent;
import static com.google.adk.testing.TestUtils.createInvocationContext;
import static com.google.adk.testing.TestUtils.createSubAgent;
import static com.google.common.truth.Truth.assertThat;

import com.google.adk.events.Event;
import com.google.adk.testing.TestBaseAgent;
import com.google.common.collect.ImmutableList;
import io.reactivex.rxjava3.core.Flowable;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;
import org.junit.Test;
import org.junit.jupiter.api.*;
import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;

/** Focused tests for LoopAgent.runAsyncImpl. */
@RunWith(JUnit4.class)
public class LoopAgentRunAsyncImplTest {

	@Test
	public void runAsyncImpl_withEmptySubAgents_returnsEmptyFlowable() {
		// subAgents() returns empty list
		LoopAgent agent = LoopAgent.builder().name("loop-empty").subAgents(ImmutableList.of()).build();
		var ctx = createInvocationContext(agent);
		List<Event> events = agent.runAsyncImpl(ctx).toList().blockingGet();
		assertThat(events).isEmpty();
	}

	@Test
	public void runAsyncImpl_withSubAgents_repeatsAndStopsByEscalate() {
		// Two sub-agents: first emits a normal event, second emits escalate event
		Event eventA = createEvent("a1");
		Event eventB = createEscalateEvent("b1");
		TestBaseAgent agentA = createSubAgent("A", Flowable.just(eventA));
		TestBaseAgent agentB = createSubAgent("B", Flowable.just(eventB));
		// Repeat up to 3 times, but loop should stop after escalate event
		LoopAgent loop = LoopAgent.builder().name("loop").subAgents(agentA, agentB).maxIterations(3).build();
		var ctx = createInvocationContext(loop);
		List<Event> events = loop.runAsyncImpl(ctx).toList().blockingGet();
		// Should emit [eventA, eventB], then stop (eventB isEscalate)
		assertThat(events).containsExactly(eventA, eventB).inOrder();
	}

	@Test
	public void runAsyncImpl_withSubAgents_repeatsUpToMaxIterations() {
		// Provide a Supplier that yields increasing event ids for each iteration
		AtomicInteger counter = new AtomicInteger(0);
		TestBaseAgent agentA = createSubAgent("A2",
				() -> Flowable.just(createEvent("a2-" + counter.incrementAndGet())));
		LoopAgent loop = LoopAgent.builder().name("loop2").subAgents(agentA).maxIterations(2).build();
		var ctx = createInvocationContext(loop);
		List<Event> events = loop.runAsyncImpl(ctx).toList().blockingGet();
		assertThat(events).hasSize(2);
		assertThat(events.get(0).id()).isEqualTo("a2-1");
		assertThat(events.get(1).id()).isEqualTo("a2-2");
	}

}
