/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Open AI and AI Model gpt-5-nano

ROOST_METHOD_HASH=runAsyncImpl_d6001493a1
ROOST_METHOD_SIG_HASH=runAsyncImpl_99c1534d6f

Scenario 1: When subAgents() returns null, runAsyncImpl should return an empty Flowable with no emitted events.

Details:
  TestName: emptySubAgentsReturnsEmptyFlowable
  Description: Verify that if the LoopAgent has no sub-agents (subAgents is null), the method returns Flowable.empty() and emits nothing.

Execution:
  Arrange: Create a LoopAgent via the builder with subAgents set to null and maxIterations left as Optional.empty.
  Act: Call runAsyncImpl with a mocked or dummy InvocationContext.
  Assert: The resulting Flowable completes immediately with no onNext events.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.mockito.Mockito.*;

import com.google.adk.events.Event;
import io.reactivex.rxjava3.core.Flowable;
import io.reactivex.rxjava3.subscribers.TestSubscriber;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class LoopAgentRunAsyncImplTest extends BaseAgent {

  public LoopAgentRunAsyncImplTest() {
    super("test", "desc", new ArrayList<>(), new ArrayList<>(), new ArrayList<>());
  }

  @Test
  @Tag("boundary")
  public void testEmptySubAgentsReturnsEmptyFlowable() {
    LoopAgent loopAgent =
        LoopAgent.builder()
            .name("loop")
            .description("desc")
            .subAgents((List<? extends BaseAgent>) null)
            .maxIterations(Optional.empty())
            .build();
    InvocationContext invocationContext = mock(InvocationContext.class);
    Flowable<Event> flowable = loopAgent.runAsyncImpl(invocationContext);
    TestSubscriber<Event> testSubscriber = flowable.test();
    testSubscriber.awaitDone(1, java.util.concurrent.TimeUnit.SECONDS);
    testSubscriber.assertComplete();
    testSubscriber.assertNoValues();
  }
}
