/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Azure Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=runAsyncImpl_d6001493a1
ROOST_METHOD_SIG_HASH=runAsyncImpl_99c1534d6f

[
  {
    "description": "LoopAgent.runAsyncImpl propagates an error when a sub-agent's runAsync throws an exception.",
    "testName": "runAsyncImpl_propagatesErrorFromSubAgent",
    "execution": {
      "Arrange": "Create a sub-agent whose runAsync throws an exception.",
      "Act": "Call runAsyncImpl and subscribe to errors.",
      "Assert": "Verify Flowable emits the exception."
    },
    "validation": "Ensures exception propagation from dependencies; prevents silent failures.",
    "category": "critical",
    "source": "llm",
    "priority": "high"
  },
  {
    "description": "LoopAgent.runAsyncImpl repeats zero times when maxIterations is set to zero.",
    "testName": "runAsyncImpl_repeatsZeroTimesWhenMaxIterationsZero",
    "execution": {
      "Arrange": "Create LoopAgent with maxIterations=0 and at least one sub-agent.",
      "Act": "Call runAsyncImpl and collect events.",
      "Assert": "Verify Flowable emits no events."
    },
    "validation": "Zero repeat edge is crucial to avoid unexpected emission.",
    "category": "critical",
    "source": "llm",
    "priority": "high"
  },
  {
    "description": "LoopAgent.runAsyncImpl emits events when sub-agent's runAsync returns null (should not emit events and propagate error or terminate).",
    "testName": "runAsyncImpl_handlesSubAgentRunAsyncReturnsNull",
    "execution": {
      "Arrange": "Create a sub-agent whose runAsync returns null.",
      "Act": "Call runAsyncImpl and subscribe.",
      "Assert": "Verify Flowable emits error or does not emit events."
    },
    "validation": "Null dependency handling prevents NPE or silent failures.",
    "category": "critical",
    "source": "llm",
    "priority": "high"
  },
  {
    "description": "LoopAgent.runAsyncImpl handles sub-agents returning Flowable.error and propagates their error downstream.",
    "testName": "runAsyncImpl_propagatesErrorFlowableFromSubAgent",
    "execution": {
      "Arrange": "Create LoopAgent with sub-agents whose runAsync emits Flowable.error.",
      "Act": "Call runAsyncImpl and observe error.",
      "Assert": "Verify Flowable emits corresponding error."
    },
    "validation": "Error Flowable propagation is critical for reliability and cascading failures.",
    "category": "critical",
    "source": "llm",
    "priority": "high"
  },
  {
    "description": "LoopAgent.runAsyncImpl returns Flowable.empty() when subAgents() returns null.",
    "testName": "",
    "execution": null,
    "validation": "",
    "category": "critical",
    "source": "audit",
    "priority": "high"
  },
  {
    "description": "LoopAgent.runAsyncImpl emits events from sub-agents when maxIterations is negative (should behave as zero iterations).",
    "testName": "runAsyncImpl_handlesNegativeMaxIterations",
    "execution": {
      "Arrange": "Create LoopAgent with maxIterations=-1 and at least one sub-agent.",
      "Act": "Call runAsyncImpl and collect events.",
      "Assert": "Verify Flowable emits no events (negative repeat count results in zero loops)."
    },
    "validation": "Covers negative boundary behavior.",
    "category": "recommended",
    "source": "llm",
    "priority": "medium"
  },
  {
    "description": "LoopAgent.runAsyncImpl defaults to repeating Integer.MAX_VALUE iterations when maxIterations is empty.",
    "testName": "runAsyncImpl_defaultsToMaxValueWhenMaxIterationsEmpty",
    "execution": {
      "Arrange": "Create LoopAgent with maxIterations=Optional.empty().",
      "Act": "Call runAsyncImpl and subscribe to events (possibly with limit or cancellation to prevent infinite loop).",
      "Assert": "Verify Flowable emits events for Integer.MAX_VALUE iterations unless stopped by escalate action."
    },
    "validation": "Confirms default branching for unset maxIterations.",
    "category": "recommended",
    "source": "llm",
    "priority": "medium"
  },
  {
    "description": "LoopAgent.runAsyncImpl performs as expected with a very large maxIterations value (boundary: Integer.MAX_VALUE).",
    "testName": "runAsyncImpl_handlesMaxIterationsIntegerMaxValue",
    "execution": {
      "Arrange": "Create LoopAgent with maxIterations=Integer.MAX_VALUE and at least one sub-agent.",
      "Act": "Call runAsyncImpl and verify initial batch of events (do not actually run all iterations; use timeouts or early stop by escalate event).",
      "Assert": "Verify events from repeated sub-agent runs."
    },
    "validation": "Tests iteration boundary and scalability.",
    "category": "recommended",
    "source": "llm",
    "priority": "medium"
  },
  {
    "description": "LoopAgent.runAsyncImpl does not emit events when sub-agent's runAsync returns a Flowable that completes immediately.",
    "testName": "runAsyncImpl_handlesSubAgentReturnsEmptyFlowable",
    "execution": {
      "Arrange": "Create LoopAgent with a sub-agent whose runAsync returns Flowable.empty().",
      "Act": "Call runAsyncImpl and subscribe.",
      "Assert": "Verify Flowable emits no events."
    },
    "validation": "Tests correct handling for empty sub-agent emission.",
    "category": "recommended",
    "source": "llm",
    "priority": "medium"
  },
  {
    "description": "LoopAgent.runAsyncImpl correctly passes InvocationContext to each sub-agent's runAsync.",
    "testName": "runAsyncImpl_passesInvocationContextToEachSubAgent",
    "execution": {
      "Arrange": "Create sub-agents that record received InvocationContext; build LoopAgent with these agents.",
      "Act": "Call runAsyncImpl with custom InvocationContext.",
      "Assert": "Verify each sub-agent received the correct context."
    },
    "validation": "Confirms context propagation.",
    "category": "recommended",
    "source": "llm",
    "priority": "medium"
  },
  {
    "description": "LoopAgent.runAsyncImpl emits events from sub-agents whose output includes escalate action events interleaved with other events.",
    "testName": "runAsyncImpl_stopsOnFirstEscalateActionAmongInterleavedEvents",
    "execution": {
      "Arrange": "Create sub-agent Flowables with escalate action events not at the start.",
      "Act": "Call runAsyncImpl and subscribe.",
      "Assert": "Verify emission stops after first escalate event."
    },
    "validation": "Tests takeUntil predicate with mixed event streams.",
    "category": "recommended",
    "source": "llm",
    "priority": "medium"
  },
  {
    "description": "LoopAgent.runAsyncImpl emits events for all sub-agents when none emits an escalate action event regardless of maxIterations.",
    "testName": "runAsyncImpl_emitsEventsWhenNoEscalateActionPresent",
    "execution": {
      "Arrange": "Create LoopAgent with sub-agents whose events never escalate and a finite maxIterations.",
      "Act": "Call runAsyncImpl and collect events.",
      "Assert": "Verify events emitted for all iterations."
    },
    "validation": "Confirms full execution when stopping condition is never met.",
    "category": "recommended",
    "source": "llm",
    "priority": "medium"
  },
  {
    "description": "LoopAgent.runAsyncImpl works when sub-agents() list contains duplicates.",
    "testName": "runAsyncImpl_handlesDuplicateSubAgents",
    "execution": {
      "Arrange": "Create LoopAgent with duplicate sub-agents in its list.",
      "Act": "Call runAsyncImpl and collect events.",
      "Assert": "Verify duplicate events are emitted according to iteration logic."
    },
    "validation": "Validates handling of redundant agent entries.",
    "category": "recommended",
    "source": "llm",
    "priority": "medium"
  },
  {
    "description": "LoopAgent.runAsyncImpl works when sub-agents return events with escalate action set to null (should not stop early).",
    "testName": "runAsyncImpl_handlesEscalateActionNull",
    "execution": {
      "Arrange": "Create sub-agents that emit events whose actions.escalate() returns null.",
      "Act": "Call runAsyncImpl and collect events.",
      "Assert": "Verify iterations proceed as normal, not stopping."
    },
    "validation": "Checks defensive null handling in escalate predicate.",
    "category": "recommended",
    "source": "llm",
    "priority": "medium"
  }
]
*/

// ********RoostGPT********

package com.google.adk.agents;

import com.google.adk.events.Event;
import com.google.adk.events.EventActions;
import com.google.common.truth.Truth;
import io.reactivex.rxjava3.core.Flowable;
import io.reactivex.rxjava3.subscribers.TestSubscriber;
import java.lang.reflect.Constructor;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Optional;
import org.junit.Test;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;

public class LoopAgentRunAsyncImplTest {

	// Test-doubles for sub-agents
	static class TestBaseAgent extends BaseAgent {

		private final java.util.function.Function<InvocationContext, Flowable<Event>> runAsync;

		TestBaseAgent(String name, java.util.function.Function<InvocationContext, Flowable<Event>> runAsync) {
			super(name, name, Collections.emptyList(), Collections.emptyList(), Collections.emptyList());
			this.runAsync = runAsync;
		}

		@Override
		protected Flowable<Event> runAsyncImpl(InvocationContext invocationContext) {
			return runAsync.apply(invocationContext);
		}

		@Override
		protected Flowable<Event> runLiveImpl(InvocationContext invocationContext) {
			return Flowable.empty();
		}

	}

	static class SimpleEventActions extends EventActions {

		private final Optional<Boolean> escalate;

		SimpleEventActions(Boolean escalate) {
			this.escalate = (escalate == null) ? Optional.empty() : Optional.of(escalate);
		}

		public Optional<Boolean> escalate() {
			return escalate;
		}

	}

	// Helper to create LoopAgent, even with private constructor
	private LoopAgent createLoopAgent(List<? extends BaseAgent> subAgents, Optional<Integer> maxIterations) {
		try {
			Constructor<LoopAgent> ctor = LoopAgent.class.getDeclaredConstructor(String.class, String.class, List.class,
					Optional.class, List.class, List.class);
			ctor.setAccessible(true);
			return ctor.newInstance("loop", "desc", subAgents, maxIterations, Collections.emptyList(),
					Collections.emptyList());
		}
		catch (Exception e) {
			throw new RuntimeException(e);
		}
	}

	private InvocationContext createInvocationContext() {
		// Session is null due to inaccessible constructor.
		return new InvocationContext(null, null, null, null, Optional.empty(), Optional.empty(), "id", null, null,
				Optional.empty(), null, false);
	}

	/**
	 * Scenario: LoopAgent.runAsyncImpl propagates an error when a sub-agent's runAsync
	 * throws an exception. Execution: Arrange a sub-agent whose runAsync throws; Act by
	 * invoking; Assert error is received. Validation: Ensures error propagation, no
	 * silent failure.
	 */
	@Test
	@Tag("invalid")
	public void runAsyncImpl_propagatesErrorFromSubAgent() {
		Throwable expected = new RuntimeException("boom");
		TestBaseAgent errorAgent = new TestBaseAgent("fail", ctx -> Flowable.error(expected));
		LoopAgent agent = createLoopAgent(List.of(errorAgent), Optional.of(1));
		TestSubscriber<Event> ts = new TestSubscriber<>();
		agent.runAsyncImpl(createInvocationContext()).subscribe(ts);
		ts.assertError(expected);
	}

	/**
	 * Scenario: LoopAgent.runAsyncImpl repeats zero times when maxIterations is set to
	 * zero. Execution: Arrange LoopAgent(maxIterations=0); Act collect events; Assert
	 * none emitted. Validation: Zero repeat edge avoids unintended emission.
	 */
	@Test
	@Tag("boundary")
	public void runAsyncImpl_repeatsZeroTimesWhenMaxIterationsZero() {
		TestBaseAgent emitsAgent = new TestBaseAgent("emit", ctx -> Flowable.just(createDummyEvent("event1", false)));
		LoopAgent agent = createLoopAgent(List.of(emitsAgent), Optional.of(0));
		TestSubscriber<Event> ts = new TestSubscriber<>();
		agent.runAsyncImpl(createInvocationContext()).subscribe(ts);
		ts.assertNoValues();
		Truth.assertThat(ts.values()).isEmpty();
	}

	/**
	 * Scenario: LoopAgent.runAsyncImpl emits events when sub-agent's runAsync returns
	 * null (should error or terminate). Execution: Arrange sub-agent with runAsync
	 * returns null; Act subscribe; Assert error or terminate. Validation: Null dependency
	 * handling avoids NPE.
	 */
	@Test
	@Tag("invalid")
	public void runAsyncImpl_handlesSubAgentRunAsyncReturnsNull() {
		TestBaseAgent nullAgent = new TestBaseAgent("null", ctx -> null);
		LoopAgent agent = createLoopAgent(List.of(nullAgent), Optional.of(1));
		TestSubscriber<Event> ts = new TestSubscriber<>();
		agent.runAsyncImpl(createInvocationContext()).subscribe(ts);
		ts.assertError(Throwable.class);
	}

	/**
	 * Scenario: LoopAgent.runAsyncImpl handles sub-agents returning Flowable.error and
	 * propagates their error downstream. Execution: Arrange agent with sub-agent that
	 * emits Flowable.error; Act observe error; Assert error emitted. Validation: Error
	 * Flowable propagated for reliability.
	 */
	@Test
	@Tag("invalid")
	public void runAsyncImpl_propagatesErrorFlowableFromSubAgent() {
		Throwable expected = new IllegalStateException("failFlowable");
		TestBaseAgent failAgent = new TestBaseAgent("err", ctx -> Flowable.error(expected));
		LoopAgent agent = createLoopAgent(List.of(failAgent), Optional.of(1));
		TestSubscriber<Event> ts = new TestSubscriber<>();
		agent.runAsyncImpl(createInvocationContext()).subscribe(ts);
		ts.assertError(expected);
	}

	/**
	 * Scenario: LoopAgent.runAsyncImpl returns Flowable.empty() when subAgents() returns
	 * null. Execution: Arrange agent with null subAgents; Act subscribe; Assert no
	 * events. Validation: Defensive null handling.
	 */
	@Test
	@Tag("invalid")
	public void runAsyncImpl_returnsFlowableEmptyWhenSubAgentsNull() {
		LoopAgent agent = createLoopAgent(null, Optional.of(1));
		TestSubscriber<Event> ts = new TestSubscriber<>();
		agent.runAsyncImpl(createInvocationContext()).subscribe(ts);
		Truth.assertThat(ts.values()).isEmpty();
	}

	/**
	 * Scenario: LoopAgent.runAsyncImpl emits events when maxIterations is negative
	 * (should behave as zero iterations). Execution: Arrange LoopAgent(maxIterations=-1);
	 * Act subscribe; Assert error thrown. Validation: Negative repeat count results in
	 * IllegalArgumentException.
	 */
	@Test
	@Tag("boundary")
	public void runAsyncImpl_handlesNegativeMaxIterations() {
		TestBaseAgent emitsAgent = new TestBaseAgent("agent", ctx -> Flowable.just(createDummyEvent("eventA", false)));
		LoopAgent agent = createLoopAgent(List.of(emitsAgent), Optional.of(-1));
		TestSubscriber<Event> ts = new TestSubscriber<>();
		agent.runAsyncImpl(createInvocationContext()).subscribe(ts);
		ts.assertError(IllegalArgumentException.class);
	}

	/**
	 * Scenario: LoopAgent.runAsyncImpl defaults to repeating Integer.MAX_VALUE iterations
	 * when maxIterations is empty. Execution: Arrange LoopAgent(maxIterations=empty); Act
	 * subscribe to events; Assert emission occurs for default max value. Validation:
	 * Confirms Integer.MAX_VALUE default branching.
	 */
	@Test
	@Tag("boundary")
	public void runAsyncImpl_defaultsToMaxValueWhenMaxIterationsEmpty() {
		TestBaseAgent emitsAgent = new TestBaseAgent("emit", ctx -> Flowable.just(createDummyEvent("e", false)));
		LoopAgent agent = createLoopAgent(List.of(emitsAgent), Optional.empty());
		TestSubscriber<Event> ts = new TestSubscriber<>();
		// Defensive: limit events collected
		agent.runAsyncImpl(createInvocationContext()).take(5).subscribe(ts);
		Truth.assertThat(ts.values().size()).isEqualTo(5);
	}

	/**
	 * Scenario: LoopAgent.runAsyncImpl performs as expected with very large maxIterations
	 * value (Integer.MAX_VALUE). Execution: Arrange LoopAgent(maxIterations=MAX_VALUE);
	 * Act subscribe to first N events; Assert N events emitted. Validation: Boundary and
	 * scalability test.
	 */
	@Test
	@Tag("boundary")
	public void runAsyncImpl_handlesMaxIterationsIntegerMaxValue() {
		TestBaseAgent emitsAgent = new TestBaseAgent("emit", ctx -> Flowable.just(createDummyEvent("event", false)));
		LoopAgent agent = createLoopAgent(List.of(emitsAgent), Optional.of(Integer.MAX_VALUE));
		TestSubscriber<Event> ts = new TestSubscriber<>();
		agent.runAsyncImpl(createInvocationContext()).take(10).subscribe(ts);
		Truth.assertThat(ts.values().size()).isEqualTo(10);
	}

	/**
	 * Scenario: LoopAgent.runAsyncImpl does not emit events when sub-agent's runAsync
	 * returns a Flowable that completes immediately. Execution: Arrange sub-agent returns
	 * Flowable.empty(); Act subscribe; Assert no events. Validation: Correct handling for
	 * empty emission.
	 */
	@Test
	@Tag("valid")
	public void runAsyncImpl_handlesSubAgentReturnsEmptyFlowable() {
		TestBaseAgent emptyAgent = new TestBaseAgent("empty", ctx -> Flowable.empty());
		LoopAgent agent = createLoopAgent(List.of(emptyAgent), Optional.of(1));
		TestSubscriber<Event> ts = new TestSubscriber<>();
		agent.runAsyncImpl(createInvocationContext()).subscribe(ts);
		Truth.assertThat(ts.values()).isEmpty();
	}

	/**
	 * Scenario: LoopAgent.runAsyncImpl correctly passes InvocationContext to each
	 * sub-agent's runAsync. Execution: Arrange recording sub-agents; Act invoke with
	 * custom context; Assert agents received correct context. Validation: Confirms
	 * context propagation.
	 */
	@Test
	@Tag("integration")
	public void runAsyncImpl_passesInvocationContextToEachSubAgent() {
		final InvocationContext ctx = createInvocationContext();
		final List<InvocationContext> received = new java.util.ArrayList<>();
		TestBaseAgent recorder = new TestBaseAgent("recorder", rec -> {
			received.add(rec);
			return Flowable.just(createDummyEvent("ev", false));
		});
		LoopAgent agent = createLoopAgent(List.of(recorder), Optional.of(1));
		agent.runAsyncImpl(ctx).blockingSubscribe();
		Truth.assertThat(received).containsExactly(ctx);
	}

	/**
	 * Scenario: LoopAgent.runAsyncImpl emits events from sub-agents whose output includes
	 * escalate action events interleaved. Execution: Arrange agent emits normal then
	 * escalate; Act subscribe; Assert stop occurs after escalate event. Validation: Tests
	 * takeUntil predicate with interleaved escalations.
	 */
	@Test
	@Tag("valid")
	public void runAsyncImpl_stopsOnFirstEscalateActionAmongInterleavedEvents() {
		Event e1 = createDummyEvent("a", false);
		Event e2 = createDummyEvent("b", true);
		Event e3 = createDummyEvent("c", false);
		TestBaseAgent mixed = new TestBaseAgent("mix", ctx -> Flowable.fromIterable(Arrays.asList(e1, e2, e3)));
		LoopAgent agent = createLoopAgent(List.of(mixed), Optional.of(5));
		TestSubscriber<Event> ts = new TestSubscriber<>();
		agent.runAsyncImpl(createInvocationContext()).subscribe(ts);
		Truth.assertThat(ts.values()).containsExactly(e1, e2);
	}

	/**
	 * Scenario: LoopAgent.runAsyncImpl emits events for all sub-agents when none emits
	 * escalate action event regardless of maxIterations. Execution: Arrange agents whose
	 * events never escalate; finite maxIterations; Assert events for each iteration
	 * emitted. Validation: Confirms full execution when stopping condition is never met.
	 */
	@Test
	@Tag("valid")
	public void runAsyncImpl_emitsEventsWhenNoEscalateActionPresent() {
		TestBaseAgent agent1 = new TestBaseAgent("a1", ctx -> Flowable.just(createDummyEvent("e1", false)));
		TestBaseAgent agent2 = new TestBaseAgent("a2", ctx -> Flowable.just(createDummyEvent("e2", false)));
		LoopAgent agent = createLoopAgent(List.of(agent1, agent2), Optional.of(2));
		TestSubscriber<Event> ts = new TestSubscriber<>();
		agent.runAsyncImpl(createInvocationContext()).subscribe(ts);
		Truth.assertThat(ts.values())
			.containsExactly(createDummyEvent("e1", false), createDummyEvent("e2", false),
					createDummyEvent("e1", false), createDummyEvent("e2", false))
			.inOrder();
	}

	/**
	 * Scenario: LoopAgent.runAsyncImpl works when sub-agents() list contains duplicates.
	 * Execution: Arrange duplicate agents; Act subscribe; Assert duplicate events emitted
	 * according to logic. Validation: Handles redundant agent entries.
	 */
	@Test
	@Tag("integration")
	public void runAsyncImpl_handlesDuplicateSubAgents() {
		TestBaseAgent emitsAgent = new TestBaseAgent("dup", ctx -> Flowable.just(createDummyEvent("ev", false)));
		LoopAgent agent = createLoopAgent(Arrays.asList(emitsAgent, emitsAgent), Optional.of(1));
		TestSubscriber<Event> ts = new TestSubscriber<>();
		agent.runAsyncImpl(createInvocationContext()).subscribe(ts);
		Truth.assertThat(ts.values())
			.containsExactly(createDummyEvent("ev", false), createDummyEvent("ev", false))
			.inOrder();
	}

	/**
	 * Scenario: LoopAgent.runAsyncImpl works when sub-agents return escalate action
	 * events with escalate as null. Execution: Arrange agent emits events with
	 * escalate=null; Act subscribe; Assert iterations proceed (not stop). Validation:
	 * Defensive null handling in escalate predicate.
	 */
	@Test
	@Tag("boundary")
	public void runAsyncImpl_handlesEscalateActionNull() {
		TestBaseAgent nullEscalateAgent = new TestBaseAgent("nullEscalate",
				ctx -> Flowable.just(createDummyEvent("ev", null)));
		LoopAgent agent = createLoopAgent(List.of(nullEscalateAgent), Optional.of(2));
		TestSubscriber<Event> ts = new TestSubscriber<>();
		agent.runAsyncImpl(createInvocationContext()).subscribe(ts);
		Truth.assertThat(ts.values())
			.containsExactly(createDummyEvent("ev", null), createDummyEvent("ev", null))
			.inOrder();
	}

	// Helper to create dummy Event with named ID and escalate flag.
	private static Event createDummyEvent(String id, Boolean escalateFlag) {
		return Event.builder().id(id).actions(new SimpleEventActions(escalateFlag)).build();
	}

}
