/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Azure Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=runLiveImpl_cd0da3baf4
ROOST_METHOD_SIG_HASH=runLiveImpl_c38f00b520

[
  {
    "description": "LoopAgent.runLiveImpl(invocationContext) returns a Flowable that emits an UnsupportedOperationException when called on a properly constructed LoopAgent instance with all fields set.",
    "category": "critical",
    "source": "llm",
    "priority": "high"
  },
  {
    "description": "LoopAgent.runLiveImpl(invocationContext) propagates the exact exception message 'runLive is not defined for LoopAgent yet.' in the emitted UnsupportedOperationException.",
    "category": "critical",
    "source": "llm",
    "priority": "high"
  },
  {
    "description": "LoopAgent.runLiveImpl(invocationContext) returns a Flowable that emits an UnsupportedOperationException regardless of the InvocationContext parameter value, including null.",
    "category": "critical",
    "source": "llm",
    "priority": "high"
  },
  {
    "description": "LoopAgent.runLiveImpl(invocationContext) emits exactly one error and completes without emitting any Event values.",
    "category": "critical",
    "source": "llm",
    "priority": "high"
  },
  {
    "description": "LoopAgent.runLiveImpl(invocationContext) returns a Flowable that emits an UnsupportedOperationException when called on a LoopAgent instance constructed with null or empty fields.",
    "category": "recommended",
    "source": "llm",
    "priority": "medium"
  },
  {
    "description": "LoopAgent.runLiveImpl(invocationContext) does not mutate any LoopAgent fields or global state after invocation.",
    "category": "recommended",
    "source": "llm",
    "priority": "medium"
  },
  {
    "description": "LoopAgent.runLiveImpl(invocationContext) emits the error immediately upon subscription to the returned Flowable, without delay or blocking.",
    "category": "recommended",
    "source": "llm",
    "priority": "medium"
  },
  {
    "description": "LoopAgent.runLiveImpl(invocationContext) emits the error even if the LoopAgent was constructed with maxIterations set to Integer.MAX_VALUE or other boundary values.",
    "category": "recommended",
    "source": "llm",
    "priority": "medium"
  }
]
*/

// ********RoostGPT********

package com.google.adk.agents;

import org.junit.jupiter.api.Test;
import static org.assertj.core.api.Assertions.*;
import io.reactivex.rxjava3.core.Flowable;
import io.reactivex.rxjava3.subscribers.TestSubscriber;
import com.google.adk.agents.InvocationContext;
import com.google.adk.events.Event;
import org.junit.jupiter.api.*;
import com.google.common.collect.ImmutableList;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import java.util.List;
import java.util.Optional;

public class LoopAgentRunLiveImplTest {

	// Utility to construct a properly initialized LoopAgent
	private LoopAgent createProperLoopAgent() {
		return LoopAgent.builder().name("LoopAgentTest").maxIterations(10).build();
	}

	// Scenario 1: Proper instance, emits UnsupportedOperationException
	@Test
	void runLiveImpl_onProperLoopAgent_returnsUnsupportedOperationException() {
		LoopAgent agent = createProperLoopAgent();
		InvocationContext context = InvocationContext.builder().build();
		Flowable<Event> flowable = agent.runLiveImpl(context);
		TestSubscriber<Event> ts = new TestSubscriber<>();
		flowable.subscribe(ts);
		ts.assertError(UnsupportedOperationException.class);
		ts.assertNoValues();
		// onComplete not expected after an error
	}

	// Scenario 2: Exception message is as expected
	@Test
	void runLiveImpl_emitsExceptionWithCorrectMessage() {
		LoopAgent agent = createProperLoopAgent();
		InvocationContext context = InvocationContext.builder().build();
		Flowable<Event> flowable = agent.runLiveImpl(context);
		assertThatThrownBy(() -> flowable.blockingSubscribe()).isInstanceOf(UnsupportedOperationException.class)
			.hasMessage("runLive is not defined for LoopAgent yet.");
	}

	// Scenario 3: Propagates error regardless of InvocationContext value (including null)
	@Test
	void runLiveImpl_withNullInvocationContext_emitsUnsupportedOperationException() {
		LoopAgent agent = createProperLoopAgent();
		Flowable<Event> flowable = agent.runLiveImpl(null);
		TestSubscriber<Event> ts = new TestSubscriber<>();
		flowable.subscribe(ts);
		ts.assertError(UnsupportedOperationException.class);
		ts.assertNoValues();
		// onComplete not expected after an error
	}

	@Test
	void runLiveImpl_withArbitraryInvocationContext_emitsUnsupportedOperationException() {
		LoopAgent agent = createProperLoopAgent();
		InvocationContext context = InvocationContext.builder().build();
		Flowable<Event> flowable = agent.runLiveImpl(context);
		TestSubscriber<Event> ts = new TestSubscriber<>();
		flowable.subscribe(ts);
		ts.assertError(UnsupportedOperationException.class);
		ts.assertNoValues();
		// onComplete not expected after an error
	}

	// Scenario 4: Emits exactly one error and completes, no Event values
	@Test
	void runLiveImpl_emitsOneError_andNoEvents_thenCompletes() {
		LoopAgent agent = createProperLoopAgent();
		InvocationContext context = InvocationContext.builder().build();
		Flowable<Event> flowable = agent.runLiveImpl(context);
		TestSubscriber<Event> ts = new TestSubscriber<>();
		flowable.subscribe(ts);
		ts.assertError(UnsupportedOperationException.class);
		ts.assertNoValues();
		// onComplete not expected after an error
	}

	// Scenario 5: LoopAgent with null/empty fields
	@Test
	void runLiveImpl_onLoopAgentWithNullFields_returnsUnsupportedOperationException() {
		LoopAgent agent = LoopAgent.builder().name(null).maxIterations(0).build();
		InvocationContext context = null;
		Flowable<Event> flowable = agent.runLiveImpl(context);
		TestSubscriber<Event> ts = new TestSubscriber<>();
		flowable.subscribe(ts);
		ts.assertError(UnsupportedOperationException.class);
		ts.assertNoValues();
		// onComplete not expected after an error
	}

	// Scenario 6: No field mutation or global state change
	@Test
	void runLiveImpl_doesNotMutateLoopAgentFields() throws Exception {
		LoopAgent agent = createProperLoopAgent();
		InvocationContext context = InvocationContext.builder().build();
		java.lang.reflect.Field maxIterationsField = LoopAgent.class.getDeclaredField("maxIterations");
		maxIterationsField.setAccessible(true);
		Object beforeMaxIterations = maxIterationsField.get(agent);
		agent.runLiveImpl(context).subscribe(new TestSubscriber<>());
		Object afterMaxIterations = maxIterationsField.get(agent);
		assertThat(beforeMaxIterations).isEqualTo(afterMaxIterations);
	}

	// Scenario 7: Error emitted immediately upon subscription
	@Test
	void runLiveImpl_emitsErrorImmediatelyUponSubscription() {
		LoopAgent agent = createProperLoopAgent();
		InvocationContext context = InvocationContext.builder().build();
		Flowable<Event> flowable = agent.runLiveImpl(context);
		long start = System.nanoTime();
		TestSubscriber<Event> ts = new TestSubscriber<>();
		flowable.subscribe(ts);
		long end = System.nanoTime();
		long elapsedMillis = (end - start) / 1_000_000;
		ts.assertError(UnsupportedOperationException.class);
		assertThat(elapsedMillis).isLessThan(100);
		// onComplete not expected after an error
	}

	// Scenario 8: Error emitted for boundary values (Integer.MAX_VALUE)
	@Test
	void runLiveImpl_withMaxIterationsMaxValue_returnsUnsupportedOperationException() {
		LoopAgent agent = LoopAgent.builder().name("BoundaryLoopAgent").maxIterations(Integer.MAX_VALUE).build();
		InvocationContext context = InvocationContext.builder().build();
		Flowable<Event> flowable = agent.runLiveImpl(context);
		TestSubscriber<Event> ts = new TestSubscriber<>();
		flowable.subscribe(ts);
		ts.assertError(UnsupportedOperationException.class);
		ts.assertNoValues();
		// onComplete not expected after an error
	}

}