/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Open AI and AI Model gpt-5-nano

ROOST_METHOD_HASH=runLiveImpl_cd0da3baf4
ROOST_METHOD_SIG_HASH=runLiveImpl_c38f00b520

Scenario 1: Basic behavior - runLiveImpl always throws an UnsupportedOperationException

Details:
  TestName: runLiveShouldThrowUnsupportedOperation
  Description: This scenario validates that invoking runLiveImpl on a LoopAgent always results in a Flowable that signals an UnsupportedOperationException with the exact message "runLive is not defined for LoopAgent yet.", regardless of the provided invocationContext.

Execution:
  Arrange: Create a LoopAgent instance using the public Builder with a minimal set of required fields (name, description) and an empty list of subAgents. Prepare a non-null InvocationContext (or a suitable stub/mock as appropriate for the test environment).
  Act: Call runLiveImpl(invocationContext) on the LoopAgent.
  Assert: The returned Flowable should emit an error of type UnsupportedOperationException and the error message should be exactly "runLive is not defined for LoopAgent yet.".

Validation:
  The assertion verifies that the runLive path is explicitly not implemented for LoopAgent, enforcing the documented limitation and preventing downstream live-run logic from being used unintentionally.

*/

// ********RoostGPT********

package com.google.adk.agents;

import com.google.adk.events.Event;
import com.google.common.collect.ImmutableList;
import io.reactivex.rxjava3.core.Flowable;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class LoopAgentRunLiveImplTest extends BaseAgent {

  public LoopAgentRunLiveImplTest() {
    super("test-loop-agent", "desc", ImmutableList.of(), ImmutableList.of(), ImmutableList.of());
  }

  @Test
  @Tag("invalid")
  public void testRunLiveShouldThrowUnsupportedOperation() {
    LoopAgent loopAgent =
        LoopAgent.builder().name("loop").description("desc").subAgents(ImmutableList.of()).build();
    Flowable<Event> result = loopAgent.runLiveImpl(null);
    result
        .test()
        .assertError(
            throwable ->
                throwable instanceof UnsupportedOperationException
                    && "runLive is not defined for LoopAgent yet.".equals(throwable.getMessage()));
  }
}
