/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Open AI and AI Model gpt-5-nano

ROOST_METHOD_HASH=runLiveImpl_cd0da3baf4
ROOST_METHOD_SIG_HASH=runLiveImpl_c38f00b520

[
  {
    "description": "Critical: Ensure that any consumer calling runLive receives an UnsupportedOperationException with the exact message, surfaced via onError to subscribers.",
    "category": "critical",
    "source": "llm",
    "priority": "high"
  },
  {
    "description": "Verify the main expected behavior of runLiveImpl.",
    "category": "happy_path",
    "source": "seeded",
    "priority": "high"
  },
  {
    "description": "runLive should propagate the exact UnsupportedOperationException with message 'runLive is not defined for LoopAgent yet.' when invoked.",
    "category": "recommended",
    "source": "llm",
    "priority": "medium"
  },
  {
    "description": "The Flowable returned by runLive should emit onError containing the same UnsupportedOperationException.",
    "category": "recommended",
    "source": "llm",
    "priority": "medium"
  },
  {
    "description": "runLive delegates to runLiveImpl and propagates UnsupportedOperationException when runLive is invoked",
    "category": "happy_path",
    "source": "seeded",
    "priority": "high"
  }
]
*/

// ********RoostGPT********

package com.google.adk.agents;

import static com.google.common.truth.Truth.assertThat;
import static org.junit.Assert.fail;
import static com.google.adk.testing.TestUtils.createInvocationContext;
import com.google.common.collect.ImmutableList;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;
import org.junit.jupiter.api.*;
import com.google.adk.events.Event;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import io.reactivex.rxjava3.core.Flowable;
import java.util.List;
import java.util.Optional;

// RoostGPT-generated test for LoopAgent.runLiveImpl behavior exposure via runLive
@RunWith(JUnit4.class)
public final class LoopAgentRunLiveImplTest {

	@Test
	public void runLive_delegatesToRunLiveImpl_andPropagatesUnsupportedOperation() {
		LoopAgent loopAgent = LoopAgent.builder().name("loopAgent").subAgents(ImmutableList.of()).build();
		InvocationContext invocationContext = createInvocationContext(loopAgent);
		try {
			// This should propagate the UnsupportedOperationException defined in
			// runLiveImpl
			loopAgent.runLive(invocationContext).toList().blockingGet();
			fail("Expected an exception from runLiveImpl");
		}
		catch (Throwable t) {
			assertThat(t).isInstanceOf(UnsupportedOperationException.class);
			assertThat(t.getMessage()).isEqualTo("runLive is not defined for LoopAgent yet.");
		}
	}

}