/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test functional-from-source-code using AI Type Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=userContent_c62cda1ff0
ROOST_METHOD_SIG_HASH=userContent_7428a149e0

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/functional-from-source-code/5ce8eb4e-e5ae-411a-9a71-43493e595c35/source/adk-java/core/src/test/java/com/google/adk/agents/InvocationContextTest.java
Tests:
    "@Test
public void testCreateWithUserContent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).isEmpty();
    assertThat(context.invocationId()).isEqualTo(testInvocationId);
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).hasValue(userContent);
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testCreateWithNullUserContent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.userContent()).isEmpty();
}
"
    "@Test
public void testCreateWithLiveRequestQueue() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).liveRequestQueue(liveRequestQueue).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).hasValue(liveRequestQueue);

    assertThat(context.invocationId()).startsWith("e-");
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).isEmpty();
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testCopyOf() {
    InvocationContext originalContext = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    originalContext.activeStreamingTools().putAll(activeStreamingTools);
    InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
    assertThat(copiedContext).isNotNull();
    assertThat(copiedContext).isNotSameInstanceAs(originalContext);
    assertThat(copiedContext.sessionService()).isEqualTo(originalContext.sessionService());
    assertThat(copiedContext.artifactService()).isEqualTo(originalContext.artifactService());
    assertThat(copiedContext.memoryService()).isEqualTo(originalContext.memoryService());
    assertThat(copiedContext.liveRequestQueue()).isEqualTo(originalContext.liveRequestQueue());
    assertThat(copiedContext.invocationId()).isEqualTo(originalContext.invocationId());
    assertThat(copiedContext.agent()).isEqualTo(originalContext.agent());
    assertThat(copiedContext.session()).isEqualTo(originalContext.session());
    assertThat(copiedContext.userContent()).isEqualTo(originalContext.userContent());
    assertThat(copiedContext.runConfig()).isEqualTo(originalContext.runConfig());
    assertThat(copiedContext.endInvocation()).isEqualTo(originalContext.endInvocation());
    assertThat(copiedContext.activeStreamingTools()).isEqualTo(originalContext.activeStreamingTools());
}
"
    "@Test
public void testGetters() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).isEmpty();
    assertThat(context.invocationId()).isEqualTo(testInvocationId);
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).hasValue(userContent);
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testSetAgent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    BaseAgent newMockAgent = mock(BaseAgent.class);
    context.agent(newMockAgent);
    assertThat(context.agent()).isEqualTo(newMockAgent);
}
"
    "@Test
public void testEquals_sameObject() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(context)).isTrue();
}
"
    "@Test
public void testEquals_null() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(null)).isFalse();
}
"
    "@Test
public void testEquals_sameValues() {
    InvocationContext context1 = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext context2 = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context1.equals(context2)).isTrue();

    assertThat(context2.equals(context1)).isTrue();
}
"
    "@Test
public void testEquals_differentValues() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext contextWithDiffSessionService = InvocationContext.builder().sessionService(
    mock(BaseSessionService.class)).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffInvocationId = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(
    "another-id").agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffAgent = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(
    mock(BaseAgent.class)).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithUserContentEmpty = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithLiveQueuePresent = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).liveRequestQueue(liveRequestQueue).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(contextWithDiffSessionService)).isFalse();
    assertThat(context.equals(contextWithDiffInvocationId)).isFalse();
    assertThat(context.equals(contextWithDiffAgent)).isFalse();
    assertThat(context.equals(contextWithUserContentEmpty)).isFalse();
    assertThat(context.equals(contextWithLiveQueuePresent)).isFalse();
}
"
    "@Test
public void testHashCode_differentValues() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext contextWithDiffSessionService = InvocationContext.builder().sessionService(
    mock(BaseSessionService.class)).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffInvocationId = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(
    "another-id").agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotEqualTo(contextWithDiffSessionService);
    assertThat(context).isNotEqualTo(contextWithDiffInvocationId);
}
"Scenario 1: InvocationContext Returns Present User Content

Details:
  TestName: userContentReturnsPresentOptional
  Description: This test checks that when the underlying InvocationContext returns an Optional containing a Content object, the userContent() method of ReadonlyContext returns the same Optional with the expected Content instance.

Execution:
  Arrange: Create a mock or stub InvocationContext that returns Optional.of(someContent) when userContent() is called. Instantiate ReadonlyContext with this InvocationContext.
  Act: Call userContent() on the ReadonlyContext instance.
  Assert: Assert that the returned Optional is present and contains the expected Content object.
Validation:
  The assertion verifies that ReadonlyContext correctly delegates to InvocationContext and returns the present user content. This ensures that user-initiated content is accessible as expected in normal operation.

Scenario 2: InvocationContext Returns Empty User Content

Details:
  TestName: userContentReturnsEmptyOptional
  Description: This test checks that when the underlying InvocationContext returns Optional.empty() for userContent(), the ReadonlyContext.userContent() method also returns Optional.empty().

Execution:
  Arrange: Create a mock or stub InvocationContext that returns Optional.empty() when userContent() is called. Instantiate ReadonlyContext with this InvocationContext.
  Act: Call userContent() on the ReadonlyContext instance.
  Assert: Assert that the returned Optional is empty.
Validation:
  The assertion ensures that ReadonlyContext properly reflects the absence of user content, which is important for scenarios where no user input initiated the invocation.

Scenario 3: InvocationContext Returns Null Instead of Optional

Details:
  TestName: userContentHandlesNullFromInvocationContext
  Description: This test checks the behavior when the underlying InvocationContext.userContent() method returns null instead of an Optional. It verifies that ReadonlyContext.userContent() handles this gracefully, either by throwing a NullPointerException or by some other means.

Execution:
  Arrange: Create a mock or stub InvocationContext that returns null when userContent() is called. Instantiate ReadonlyContext with this InvocationContext.
  Act: Call userContent() on the ReadonlyContext instance.
  Assert: Assert that a NullPointerException is thrown, or that the behavior is as specified by the implementation.
Validation:
  The assertion verifies robustness against contract violations in InvocationContext. This is significant for defensive programming and error handling in the application.

Scenario 4: InvocationContext Throws Exception on userContent()

Details:
  TestName: userContentPropagatesException
  Description: This test checks that if InvocationContext.userContent() throws a runtime exception, the exception is propagated by ReadonlyContext.userContent().

Execution:
  Arrange: Create a mock or stub InvocationContext that throws a RuntimeException when userContent() is called. Instantiate ReadonlyContext with this InvocationContext.
  Act: Call userContent() on the ReadonlyContext instance.
  Assert: Assert that the same RuntimeException is thrown.
Validation:
  The assertion ensures that ReadonlyContext does not suppress or alter exceptions from InvocationContext, preserving expected error propagation semantics.

Scenario 5: Multiple Calls to userContent() Return Consistent Results

Details:
  TestName: userContentReturnsConsistentResults
  Description: This test checks that multiple invocations of ReadonlyContext.userContent() return the same Optional instance or equivalent value, ensuring consistency.

Execution:
  Arrange: Create a mock or stub InvocationContext that returns a specific Optional<Content> when userContent() is called. Instantiate ReadonlyContext with this InvocationContext.
  Act: Call userContent() multiple times on the ReadonlyContext instance.
  Assert: Assert that all returned Optionals are equal (and, if appropriate, the same instance).
Validation:
  The assertion verifies that ReadonlyContext does not cache, mutate, or otherwise alter the result between calls, which is important for predictable behavior in client code.

Scenario 6: ReadonlyContext Constructed with Null InvocationContext

Details:
  TestName: userContentWithNullInvocationContext
  Description: This test checks the behavior when ReadonlyContext is constructed with a null InvocationContext and userContent() is called.

Execution:
  Arrange: Instantiate ReadonlyContext with a null InvocationContext.
  Act: Call userContent() on the ReadonlyContext instance.
  Assert: Assert that a NullPointerException is thrown.
Validation:
  The assertion ensures that the class fails fast when constructed with invalid arguments, which is important for preventing subtle bugs and ensuring contract adherence.

Scenario 7: InvocationContext Returns Optional with Null Content

Details:
  TestName: userContentReturnsOptionalWithNullContent
  Description: This test checks the behavior when InvocationContext.userContent() returns Optional.of(null), which is a contract violation for Optional. The test verifies how ReadonlyContext.userContent() handles this situation.

Execution:
  Arrange: Create a mock or stub InvocationContext that returns Optional.of(null) when userContent() is called. Instantiate ReadonlyContext with this InvocationContext.
  Act: Call userContent() on the ReadonlyContext instance.
  Assert: Assert that a NullPointerException is thrown, or that the behavior is as specified by the implementation.
Validation:
  The assertion checks for robustness against improper use of Optional, ensuring that such contract violations are detected or handled appropriately.

Scenario 8: InvocationContext is a Subclass with Overridden userContent()

Details:
  TestName: userContentWithOverriddenInvocationContext
  Description: This test checks that ReadonlyContext.userContent() correctly delegates to an overridden userContent() method in a subclass of InvocationContext.

Execution:
  Arrange: Create a subclass of InvocationContext that overrides userContent() to return a specific Optional<Content>. Instantiate ReadonlyContext with this subclass instance.
  Act: Call userContent() on the ReadonlyContext instance.
  Assert: Assert that the returned Optional matches the value returned by the overridden method.
Validation:
  The assertion ensures that ReadonlyContext is compatible with subclasses of InvocationContext, supporting polymorphic behavior as expected in object-oriented design.

Scenario 9: ReadonlyContext Used Concurrently from Multiple Threads

Details:
  TestName: userContentThreadSafety
  Description: This test checks the thread safety of ReadonlyContext.userContent() when accessed concurrently from multiple threads, ensuring no unexpected exceptions or inconsistent results.

Execution:
  Arrange: Create a mock or stub InvocationContext that returns a specific Optional<Content>. Instantiate ReadonlyContext with this InvocationContext.
  Act: Call userContent() concurrently from multiple threads.
  Assert: Assert that all threads receive the expected Optional<Content> and no exceptions are thrown.
Validation:
  The assertion verifies that ReadonlyContext is safe to use in multi-threaded environments, which is important for applications with concurrent access patterns.

Scenario 10: ReadonlyContext with InvocationContext Returning Different Optionals Over Time

Details:
  TestName: userContentReflectsInvocationContextChanges
  Description: This test checks that if InvocationContext.userContent() returns different Optional<Content> values on subsequent calls (e.g., due to internal state changes), ReadonlyContext.userContent() reflects these changes.

Execution:
  Arrange: Create a mock or stub InvocationContext that returns different Optional<Content> values on each call to userContent(). Instantiate ReadonlyContext with this InvocationContext.
  Act: Call userContent() multiple times on the ReadonlyContext instance.
  Assert: Assert that the returned Optionals match the sequence provided by the InvocationContext.
Validation:
  The assertion ensures that ReadonlyContext does not cache or stale the result, and always delegates to the current state of InvocationContext, supporting dynamic behavior.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.genai.types.Content;
import java.util.Optional;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicInteger;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.function.Executable;

public class ReadonlyContextUserContentTest {

  @Test
  @Tag("valid")
  public void testUserContentReturnsPresentOptional() {
    Content expectedContent = mock(Content.class);
    InvocationContext mockInvocationContext = mock(InvocationContext.class);
    when(mockInvocationContext.userContent()).thenReturn(Optional.of(expectedContent));
    ReadonlyContext readonlyContext = new ReadonlyContext(mockInvocationContext);
    Optional<Content> result = readonlyContext.userContent();
    assertTrue(((Optional<Content>) result).isPresent(), "Expected Optional to be present");
    assertSame(
        expectedContent, ((Optional<Content>) result).get(), "Expected the same Content instance");
  }

  @Test
  @Tag("valid")
  public void testUserContentReturnsEmptyOptional() {
    InvocationContext mockInvocationContext = mock(InvocationContext.class);
    when(mockInvocationContext.userContent()).thenReturn(Optional.empty());
    ReadonlyContext readonlyContext = new ReadonlyContext(mockInvocationContext);
    Optional<Content> result = readonlyContext.userContent();
    assertFalse(((Optional<Content>) result).isPresent(), "Expected Optional to be empty");
  }

  @Test
  @Tag("invalid")
  public void testUserContentHandlesNullFromInvocationContext() {
    InvocationContext mockInvocationContext = mock(InvocationContext.class);
    when(mockInvocationContext.userContent()).thenReturn(null);
    ReadonlyContext readonlyContext = new ReadonlyContext(mockInvocationContext);
    assertThrows(
        NullPointerException.class,
        (Executable) readonlyContext::userContent,
        "Expected NullPointerException when InvocationContext.userContent() returns null");
  }

  @Test
  @Tag("invalid")
  public void testUserContentPropagatesException() {
    InvocationContext mockInvocationContext = mock(InvocationContext.class);
    RuntimeException expectedException = new RuntimeException("Test exception");
    when(mockInvocationContext.userContent()).thenThrow(expectedException);
    ReadonlyContext readonlyContext = new ReadonlyContext(mockInvocationContext);
    RuntimeException thrown =
        assertThrows(
            RuntimeException.class,
            (Executable) readonlyContext::userContent,
            "Expected RuntimeException to be propagated");
    assertSame(
        expectedException, thrown, "Expected the same RuntimeException instance to be thrown");
  }

  @Test
  @Tag("valid")
  public void testUserContentReturnsConsistentResults() {
    Content expectedContent = mock(Content.class);
    Optional<Content> expectedOptional = Optional.of(expectedContent);
    InvocationContext mockInvocationContext = mock(InvocationContext.class);
    when(mockInvocationContext.userContent()).thenReturn(expectedOptional);
    ReadonlyContext readonlyContext = new ReadonlyContext(mockInvocationContext);
    Optional<Content> result1 = readonlyContext.userContent();
    Optional<Content> result2 = readonlyContext.userContent();
    assertEquals(
        expectedOptional,
        (Optional<Content>) result1,
        "First call should return the expected Optional");
    assertEquals(
        expectedOptional,
        (Optional<Content>) result2,
        "Second call should return the expected Optional");
  }

  @Test
  @Tag("invalid")
  public void testUserContentWithNullInvocationContext() {
    ReadonlyContext readonlyContext = new ReadonlyContext(null);
    assertThrows(
        NullPointerException.class,
        (Executable) readonlyContext::userContent,
        "Expected NullPointerException when constructed with null InvocationContext");
  }

  @Test
  @Tag("invalid")
  public void testUserContentReturnsOptionalWithNullContent() {
    InvocationContext mockInvocationContext = mock(InvocationContext.class);
    // This is a contract violation, but we test for robustness
    when(mockInvocationContext.userContent()).thenReturn(Optional.ofNullable(null));
    ReadonlyContext readonlyContext = new ReadonlyContext(mockInvocationContext);
    assertThrows(
        NullPointerException.class,
        () -> ((Optional<Content>) readonlyContext.userContent()).get(),
        "Expected NullPointerException when Optional contains null");
  }

  @Test
  @Tag("integration")
  public void testUserContentWithOverriddenInvocationContext() {
    // The original test tried to subclass InvocationContext and use undefined
    // classes.
    // Instead, use a Mockito mock with a stubbed userContent() method.
    Content overriddenContent = mock(Content.class);
    InvocationContext mockInvocationContext = mock(InvocationContext.class);
    when(mockInvocationContext.userContent()).thenReturn(Optional.of(overriddenContent));
    ReadonlyContext readonlyContext = new ReadonlyContext(mockInvocationContext);
    Optional<Content> result = readonlyContext.userContent();
    assertTrue(
        ((Optional<Content>) result).isPresent(),
        "Expected Optional to be present from overridden method");
    assertSame(
        overriddenContent,
        ((Optional<Content>) result).get(),
        "Expected the overridden Content instance");
    // NOTE: This test was rewritten to avoid compilation errors due to missing types.
  }

  @Test
  @Tag("boundary")
  public void testUserContentThreadSafety() throws InterruptedException, ExecutionException {
    Content expectedContent = mock(Content.class);
    Optional<Content> expectedOptional = Optional.of(expectedContent);
    InvocationContext mockInvocationContext = mock(InvocationContext.class);
    when(mockInvocationContext.userContent()).thenReturn(expectedOptional);
    ReadonlyContext readonlyContext = new ReadonlyContext(mockInvocationContext);
    int threadCount = 10; // TODO: Adjust thread count if needed
    ExecutorService executor = Executors.newFixedThreadPool(threadCount);
    Callable<Optional<Content>> task = readonlyContext::userContent;
    Future<Optional<Content>>[] futures = new Future[threadCount];
    for (int i = 0; i < threadCount; i++) {
      futures[i] = executor.submit(task);
    }
    for (Future<Optional<Content>> future : futures) {
      Optional<Content> result = future.get();
      assertEquals(
          expectedOptional,
          (Optional<Content>) result,
          "All threads should receive the expected Optional<Content>");
    }
    executor.shutdown();
    assertTrue(executor.awaitTermination(2, TimeUnit.SECONDS), "Executor should terminate cleanly");
  }

  @Test
  @Tag("boundary")
  public void testUserContentReflectsInvocationContextChanges() {
    Content content1 = mock(Content.class);
    Content content2 = mock(Content.class);
    Optional<Content> optional1 = Optional.of(content1);
    Optional<Content> optional2 = Optional.of(content2);
    InvocationContext mockInvocationContext = mock(InvocationContext.class);
    AtomicInteger callCount = new AtomicInteger(0);
    when(mockInvocationContext.userContent())
        .thenAnswer(
            invocation -> {
              int count = callCount.getAndIncrement();
              if (count == 0) return optional1;
              else return optional2;
            });
    ReadonlyContext readonlyContext = new ReadonlyContext(mockInvocationContext);
    Optional<Content> firstCall = readonlyContext.userContent();
    Optional<Content> secondCall = readonlyContext.userContent();
    assertEquals(
        optional1,
        (Optional<Content>) firstCall,
        "First call should return the first Optional<Content>");
    assertEquals(
        optional2,
        (Optional<Content>) secondCall,
        "Second call should return the second Optional<Content>");
  }
}
