/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test functional-from-source-code using AI Type Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=agentName_8552218e45
ROOST_METHOD_SIG_HASH=agentName_06835aa1e1

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/functional-from-source-code/5ce8eb4e-e5ae-411a-9a71-43493e595c35/source/adk-java/core/src/test/java/com/google/adk/agents/CallbacksTest.java
Tests:
    "@Test
public void testRun_withModelCallbacks_receivesCorrectContext() {
    Content realContent = Content.fromParts(Part.fromText("Real LLM response"));
    TestLlm testLlm = createTestLlm(createLlmResponse(realContent));
    LlmAgent agent = createTestAgentBuilder(testLlm).beforeModelCallback((callbackContext, request) -> {
        assertThat(callbackContext.invocationId()).isNotEmpty();
        assertThat(callbackContext.agentName()).isEqualTo("test agent");
        return Maybe.empty();
    }).afterModelCallback((callbackContext, response) -> {
        assertThat(callbackContext.invocationId()).isNotEmpty();
        assertThat(callbackContext.agentName()).isEqualTo("test agent");
        assertThat(response.content()).hasValue(realContent);
        return Maybe.empty();
    }).build();
    InvocationContext invocationContext = createInvocationContext(agent);
    List<Event> events = agent.runAsync(invocationContext).toList().blockingGet();
    assertThat(events).hasSize(1);
    assertThat(getOnlyElement(events).content()).hasValue(realContent);
}
"Scenario 1: Agent Name is Returned Correctly When Present

Details:
  TestName: agentNameReturnsCorrectValueWhenPresent
  Description: This test checks that the agentName() method returns the correct agent name when the underlying InvocationContext and its agent() method are properly configured to return a valid name string.
Execution:
  Arrange: Create a mock or stub for InvocationContext such that agent().name() returns a specific, non-null string (e.g., "TestAgent").
  Act: Instantiate ReadonlyContext with this InvocationContext and call agentName().
  Assert: Assert that the returned value equals "TestAgent".
Validation:
  This assertion verifies that agentName() correctly delegates to invocationContext.agent().name() and returns the expected agent name. This is significant to ensure the method provides the correct agent identity in normal operation.

Scenario 2: Agent Name is Null

Details:
  TestName: agentNameReturnsNullWhenAgentNameIsNull
  Description: This test checks the behavior of agentName() when the agent().name() method returns null, ensuring that the method can handle and propagate null values gracefully.
Execution:
  Arrange: Create a mock or stub for InvocationContext such that agent().name() returns null.
  Act: Instantiate ReadonlyContext with this InvocationContext and call agentName().
  Assert: Assert that the returned value is null.
Validation:
  This assertion ensures that agentName() does not throw an exception or alter the null value, which is important for robustness in cases where agent names may not be set.

Scenario 3: Agent Object is Null

Details:
  TestName: agentNameThrowsExceptionWhenAgentIsNull
  Description: This test checks the behavior of agentName() when the agent() method of InvocationContext returns null, which should result in a NullPointerException when attempting to call name() on null.
Execution:
  Arrange: Create a mock or stub for InvocationContext such that agent() returns null.
  Act: Instantiate ReadonlyContext with this InvocationContext and call agentName().
  Assert: Assert that a NullPointerException is thrown.
Validation:
  This assertion verifies that the method fails fast and predictably when the agent object is missing, which is important for debugging and error handling in the application.

Scenario 4: Agent Name is an Empty String

Details:
  TestName: agentNameReturnsEmptyStringWhenAgentNameIsEmpty
  Description: This test checks the behavior of agentName() when the agent().name() method returns an empty string, ensuring that empty names are handled and returned as-is.
Execution:
  Arrange: Create a mock or stub for InvocationContext such that agent().name() returns "" (empty string).
  Act: Instantiate ReadonlyContext with this InvocationContext and call agentName().
  Assert: Assert that the returned value is an empty string.
Validation:
  This assertion ensures that agentName() does not modify or reject empty agent names, which may be valid in some business contexts.

Scenario 5: InvocationContext is Null

Details:
  TestName: agentNameThrowsExceptionWhenInvocationContextIsNull
  Description: This test checks the behavior of agentName() when ReadonlyContext is constructed with a null InvocationContext, which should result in a NullPointerException when agentName() is called.
Execution:
  Arrange: Instantiate ReadonlyContext with a null InvocationContext.
  Act: Call agentName() on this instance.
  Assert: Assert that a NullPointerException is thrown.
Validation:
  This assertion ensures that the method fails predictably when the core context is missing, which is important for application stability and debugging.

Scenario 6: Agent Name Contains Special Characters

Details:
  TestName: agentNameReturnsSpecialCharactersCorrectly
  Description: This test checks that agentName() correctly returns agent names containing special characters, spaces, or unicode symbols.
Execution:
  Arrange: Create a mock or stub for InvocationContext such that agent().name() returns a string with special characters (e.g., "Agent_#42! 🚀").
  Act: Instantiate ReadonlyContext with this InvocationContext and call agentName().
  Assert: Assert that the returned value matches the special character string.
Validation:
  This assertion verifies that agentName() does not alter or misinterpret agent names with special formatting, which is important for internationalization and user experience.

Scenario 7: Agent Name is a Very Long String

Details:
  TestName: agentNameHandlesVeryLongAgentNames
  Description: This test checks that agentName() can handle and return very long agent names without truncation or error.
Execution:
  Arrange: Create a mock or stub for InvocationContext such that agent().name() returns a very long string (e.g., 10,000 characters).
  Act: Instantiate ReadonlyContext with this InvocationContext and call agentName().
  Assert: Assert that the returned value matches the long string exactly.
Validation:
  This assertion ensures that the method can handle large input sizes, which is important for robustness and to prevent unexpected failures in edge cases.

Scenario 8: Multiple Calls to agentName Return Consistent Results

Details:
  TestName: agentNameReturnsConsistentResultsOnMultipleCalls
  Description: This test checks that multiple invocations of agentName() on the same ReadonlyContext instance return the same result, confirming statelessness and consistency.
Execution:
  Arrange: Create a mock or stub for InvocationContext such that agent().name() returns a specific string.
  Act: Instantiate ReadonlyContext and call agentName() multiple times.
  Assert: Assert that all returned values are identical.
Validation:
  This assertion ensures that agentName() is deterministic and does not change state between calls, which is important for predictability in application logic.

Scenario 9: InvocationContext.agent() Throws an Exception

Details:
  TestName: agentNamePropagatesExceptionFromAgentMethod
  Description: This test checks the behavior when the agent() method of InvocationContext throws a runtime exception, ensuring that agentName() does not suppress or alter the exception.
Execution:
  Arrange: Create a mock or stub for InvocationContext such that agent() throws a RuntimeException when called.
  Act: Instantiate ReadonlyContext and call agentName().
  Assert: Assert that the same RuntimeException is thrown.
Validation:
  This assertion ensures that exceptions from underlying context methods are properly propagated, which is important for debugging and error transparency.

Scenario 10: agent().name() Throws an Exception

Details:
  TestName: agentNamePropagatesExceptionFromNameMethod
  Description: This test checks the behavior when the name() method of the agent object throws a runtime exception, ensuring that agentName() does not suppress or alter the exception.
Execution:
  Arrange: Create a mock or stub for InvocationContext.agent() that returns an agent object whose name() method throws a RuntimeException.
  Act: Instantiate ReadonlyContext and call agentName().
  Assert: Assert that the same RuntimeException is thrown.
Validation:
  This assertion ensures that exceptions from the agent's name() method are properly propagated, which is important for error handling and debugging.

*/

// ********RoostGPT********

package com.google.adk.agents;

import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

public class ReadonlyContextAgentNameTest {

  @Test
  @Tag("valid")
  @DisplayName("Agent Name is Returned Correctly When Present")
  public void testAgentNameReturnsCorrectValueWhenPresent() {
    InvocationContext mockInvocationContext = Mockito.mock(InvocationContext.class);
    BaseAgent mockAgent = Mockito.mock(BaseAgent.class);
    Mockito.when(mockInvocationContext.agent()).thenReturn(mockAgent);
    Mockito.when(mockAgent.name()).thenReturn("TestAgent");
    ReadonlyContext context = new ReadonlyContext(mockInvocationContext);
    String result = context.agentName();
    Assertions.assertEquals(
        "TestAgent", result, "agentName() should return the correct agent name");
  }

  @Test
  @Tag("boundary")
  @DisplayName("Agent Name is Null")
  public void testAgentNameReturnsNullWhenAgentNameIsNull() {
    InvocationContext mockInvocationContext = Mockito.mock(InvocationContext.class);
    BaseAgent mockAgent = Mockito.mock(BaseAgent.class);
    Mockito.when(mockInvocationContext.agent()).thenReturn(mockAgent);
    Mockito.when(mockAgent.name()).thenReturn(null);
    ReadonlyContext context = new ReadonlyContext(mockInvocationContext);
    String result = context.agentName();
    Assertions.assertNull(result, "agentName() should return null when agent().name() is null");
  }

  @Test
  @Tag("invalid")
  @DisplayName("Agent Object is Null")
  public void testAgentNameThrowsExceptionWhenAgentIsNull() {
    InvocationContext mockInvocationContext = Mockito.mock(InvocationContext.class);
    Mockito.when(mockInvocationContext.agent()).thenReturn(null);
    ReadonlyContext context = new ReadonlyContext(mockInvocationContext);
    Assertions.assertThrows(
        NullPointerException.class,
        context::agentName,
        "agentName() should throw NullPointerException when agent() is null");
  }

  @Test
  @Tag("boundary")
  @DisplayName("Agent Name is an Empty String")
  public void testAgentNameReturnsEmptyStringWhenAgentNameIsEmpty() {
    InvocationContext mockInvocationContext = Mockito.mock(InvocationContext.class);
    BaseAgent mockAgent = Mockito.mock(BaseAgent.class);
    Mockito.when(mockInvocationContext.agent()).thenReturn(mockAgent);
    Mockito.when(mockAgent.name()).thenReturn("");
    ReadonlyContext context = new ReadonlyContext(mockInvocationContext);
    String result = context.agentName();
    Assertions.assertEquals(
        "", result, "agentName() should return an empty string when agent().name() is empty");
  }

  @Test
  @Tag("invalid")
  @DisplayName("InvocationContext is Null")
  public void testAgentNameThrowsExceptionWhenInvocationContextIsNull() {
    ReadonlyContext context = new ReadonlyContext(null);
    Assertions.assertThrows(
        NullPointerException.class,
        context::agentName,
        "agentName() should throw NullPointerException when invocationContext is null");
  }

  @Test
  @Tag("boundary")
  @DisplayName("Agent Name Contains Special Characters")
  public void testAgentNameReturnsSpecialCharactersCorrectly() {
    InvocationContext mockInvocationContext = Mockito.mock(InvocationContext.class);
    BaseAgent mockAgent = Mockito.mock(BaseAgent.class);
    String specialName = "Agent_#42! 🚀";
    Mockito.when(mockInvocationContext.agent()).thenReturn(mockAgent);
    Mockito.when(mockAgent.name()).thenReturn(specialName);
    ReadonlyContext context = new ReadonlyContext(mockInvocationContext);
    String result = context.agentName();
    Assertions.assertEquals(
        specialName,
        result,
        "agentName() should return agent names with special characters correctly");
  }

  @Test
  @Tag("boundary")
  @DisplayName("Agent Name is a Very Long String")
  public void testAgentNameHandlesVeryLongAgentNames() {
    InvocationContext mockInvocationContext = Mockito.mock(InvocationContext.class);
    BaseAgent mockAgent = Mockito.mock(BaseAgent.class);
    String longName = "A".repeat(10_000); // TODO: Adjust length if needed
    Mockito.when(mockInvocationContext.agent()).thenReturn(mockAgent);
    Mockito.when(mockAgent.name()).thenReturn(longName);
    ReadonlyContext context = new ReadonlyContext(mockInvocationContext);
    String result = context.agentName();
    Assertions.assertEquals(
        longName, result, "agentName() should handle very long agent names without truncation");
  }

  @Test
  @Tag("valid")
  @DisplayName("Multiple Calls to agentName Return Consistent Results")
  public void testAgentNameReturnsConsistentResultsOnMultipleCalls() {
    InvocationContext mockInvocationContext = Mockito.mock(InvocationContext.class);
    BaseAgent mockAgent = Mockito.mock(BaseAgent.class);
    Mockito.when(mockInvocationContext.agent()).thenReturn(mockAgent);
    Mockito.when(mockAgent.name()).thenReturn("ConsistentAgent");
    ReadonlyContext context = new ReadonlyContext(mockInvocationContext);
    String result1 = context.agentName();
    String result2 = context.agentName();
    String result3 = context.agentName();
    Assertions.assertEquals(
        "ConsistentAgent", result1, "First call to agentName() should return the correct value");
    Assertions.assertEquals(
        result1, result2, "Subsequent calls to agentName() should return the same value");
    Assertions.assertEquals(result2, result3, "All calls to agentName() should be consistent");
  }

  @Test
  @Tag("invalid")
  @DisplayName("InvocationContext.agent() Throws an Exception")
  public void testAgentNamePropagatesExceptionFromAgentMethod() {
    InvocationContext mockInvocationContext = Mockito.mock(InvocationContext.class);
    Mockito.when(mockInvocationContext.agent())
        .thenThrow(new RuntimeException("Agent method failure"));
    ReadonlyContext context = new ReadonlyContext(mockInvocationContext);
    RuntimeException thrown =
        Assertions.assertThrows(
            RuntimeException.class,
            context::agentName,
            "agentName() should propagate exception from agent()");
    Assertions.assertEquals(
        "Agent method failure",
        thrown.getMessage(),
        "Exception message should match the thrown exception");
  }

  @Test
  @Tag("invalid")
  @DisplayName("agent().name() Throws an Exception")
  public void testAgentNamePropagatesExceptionFromNameMethod() {
    InvocationContext mockInvocationContext = Mockito.mock(InvocationContext.class);
    BaseAgent mockAgent = Mockito.mock(BaseAgent.class);
    Mockito.when(mockInvocationContext.agent()).thenReturn(mockAgent);
    Mockito.when(mockAgent.name()).thenThrow(new RuntimeException("Name method failure"));
    ReadonlyContext context = new ReadonlyContext(mockInvocationContext);
    RuntimeException thrown =
        Assertions.assertThrows(
            RuntimeException.class,
            context::agentName,
            "agentName() should propagate exception from agent().name()");
    Assertions.assertEquals(
        "Name method failure",
        thrown.getMessage(),
        "Exception message should match the thrown exception");
  }
}
