/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test functional-from-source-code using AI Type Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=invocationId_2ee437869d
ROOST_METHOD_SIG_HASH=invocationId_6cd6fb05e4

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/functional-from-source-code/5ce8eb4e-e5ae-411a-9a71-43493e595c35/source/adk-java/core/src/test/java/com/google/adk/agents/LlmAgentTest.java
Tests:
    "@Test
public void testCanonicalInstruction_providerInstructionInjectsContext() {
    String instruction = "Test provider instruction for invocation: ";
    LlmAgent agent = createTestAgentBuilder(createTestLlm(LlmResponse.builder().build())).instruction(new Instruction.Provider(context -> Single.just(instruction + context.invocationId()))).build();
    ReadonlyContext invocationContext = new ReadonlyContext(createInvocationContext(agent));
    String canonicalInstruction = agent.canonicalInstruction(invocationContext).blockingGet().getKey();
    assertThat(canonicalInstruction).isEqualTo(instruction + invocationContext.invocationId());
}
"
    "@Test
public void testCanonicalGlobalInstruction_providerInstructionInjectsContext() {
    String instruction = "Test provider global instruction for invocation: ";
    LlmAgent agent = createTestAgentBuilder(createTestLlm(LlmResponse.builder().build())).globalInstruction(new Instruction.Provider(context -> Single.just(instruction + context.invocationId()))).build();
    ReadonlyContext invocationContext = new ReadonlyContext(createInvocationContext(agent));
    String canonicalInstruction = agent.canonicalGlobalInstruction(invocationContext).blockingGet().getKey();
    assertThat(canonicalInstruction).isEqualTo(instruction + invocationContext.invocationId());
}
"

File Path: /var/tmp/Roost/RoostGPT/functional-from-source-code/5ce8eb4e-e5ae-411a-9a71-43493e595c35/source/adk-java/core/src/test/java/com/google/adk/agents/InstructionTest.java
Tests:
    "@Test
public void testCanonicalInstruction_providerInstructionInjectsContext() {
    String instruction = "Test provider instruction for invocation: ";
    LlmAgent agent = createTestAgentBuilder(createTestLlm(LlmResponse.builder().build())).instruction(new Instruction.Provider(context -> Single.just(instruction + context.invocationId()))).build();
    ReadonlyContext invocationContext = new ReadonlyContext(createInvocationContext(agent));
    String canonicalInstruction = agent.canonicalInstruction(invocationContext).blockingGet().getKey();
    assertThat(canonicalInstruction).isEqualTo(instruction + invocationContext.invocationId());
}
"
    "@Test
public void testCanonicalGlobalInstruction_providerInstructionInjectsContext() {
    String instruction = "Test provider global instruction for invocation: ";
    LlmAgent agent = createTestAgentBuilder(createTestLlm(LlmResponse.builder().build())).globalInstruction(new Instruction.Provider(context -> Single.just(instruction + context.invocationId()))).build();
    ReadonlyContext invocationContext = new ReadonlyContext(createInvocationContext(agent));
    String canonicalInstruction = agent.canonicalGlobalInstruction(invocationContext).blockingGet().getKey();
    assertThat(canonicalInstruction).isEqualTo(instruction + invocationContext.invocationId());
}
"

File Path: /var/tmp/Roost/RoostGPT/functional-from-source-code/5ce8eb4e-e5ae-411a-9a71-43493e595c35/source/adk-java/core/src/test/java/com/google/adk/agents/SequentialAgentTest.java
Tests:
    "@Test
public void runAsync_propagatesInvocationContextToSubAgents() {
    TestBaseAgent subAgent = createSubAgent("subAgent");
    SequentialAgent sequentialAgent = SequentialAgent.builder().name("seqAgent").subAgents(ImmutableList.of(subAgent)).build();
    InvocationContext parentContext = createInvocationContext(sequentialAgent);
    List<Event> unused = sequentialAgent.runAsync(parentContext).toList().blockingGet();
    InvocationContext capturedContext = subAgent.getLastInvocationContext();
    assertThat(capturedContext).isNotNull();
    assertThat(capturedContext.invocationId()).isEqualTo(parentContext.invocationId());
    assertThat(capturedContext.session()).isEqualTo(parentContext.session());
    assertThat(capturedContext.agent()).isEqualTo(subAgent);
    assertThat(subAgent.getInvocationCount()).isEqualTo(1);
}
"
    "@Test
public void runLive_propagatesInvocationContextToSubAgents() {
    TestBaseAgent subAgent = createSubAgent("subAgent_live");
    SequentialAgent sequentialAgent = SequentialAgent.builder().name("seqAgentLive").subAgents(ImmutableList.of(subAgent)).build();
    InvocationContext parentContext = createInvocationContext(sequentialAgent);
    List<Event> unused = sequentialAgent.runLive(parentContext).toList().blockingGet();
    InvocationContext capturedContext = subAgent.getLastInvocationContext();
    assertThat(capturedContext).isNotNull();
    assertThat(capturedContext.invocationId()).isEqualTo(parentContext.invocationId());
    assertThat(capturedContext.session()).isEqualTo(parentContext.session());
    assertThat(capturedContext.agent()).isEqualTo(subAgent);
    assertThat(subAgent.getInvocationCount()).isEqualTo(1);
}
"

File Path: /var/tmp/Roost/RoostGPT/functional-from-source-code/5ce8eb4e-e5ae-411a-9a71-43493e595c35/source/adk-java/core/src/test/java/com/google/adk/agents/InvocationContextTest.java
Tests:
    "@Test
public void testCreateWithUserContent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).isEmpty();
    assertThat(context.invocationId()).isEqualTo(testInvocationId);
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).hasValue(userContent);
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testCreateWithNullUserContent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.userContent()).isEmpty();
}
"
    "@Test
public void testCreateWithLiveRequestQueue() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).liveRequestQueue(liveRequestQueue).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotNull();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).hasValue(liveRequestQueue);

    assertThat(context.invocationId()).startsWith("e-");
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).isEmpty();
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testCopyOf() {
    InvocationContext originalContext = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    originalContext.activeStreamingTools().putAll(activeStreamingTools);
    InvocationContext copiedContext = InvocationContext.copyOf(originalContext);
    assertThat(copiedContext).isNotNull();
    assertThat(copiedContext).isNotSameInstanceAs(originalContext);
    assertThat(copiedContext.sessionService()).isEqualTo(originalContext.sessionService());
    assertThat(copiedContext.artifactService()).isEqualTo(originalContext.artifactService());
    assertThat(copiedContext.memoryService()).isEqualTo(originalContext.memoryService());
    assertThat(copiedContext.liveRequestQueue()).isEqualTo(originalContext.liveRequestQueue());
    assertThat(copiedContext.invocationId()).isEqualTo(originalContext.invocationId());
    assertThat(copiedContext.agent()).isEqualTo(originalContext.agent());
    assertThat(copiedContext.session()).isEqualTo(originalContext.session());
    assertThat(copiedContext.userContent()).isEqualTo(originalContext.userContent());
    assertThat(copiedContext.runConfig()).isEqualTo(originalContext.runConfig());
    assertThat(copiedContext.endInvocation()).isEqualTo(originalContext.endInvocation());
    assertThat(copiedContext.activeStreamingTools()).isEqualTo(originalContext.activeStreamingTools());
}
"
    "@Test
public void testGetters() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.sessionService()).isEqualTo(mockSessionService);
    assertThat(context.artifactService()).isEqualTo(mockArtifactService);
    assertThat(context.memoryService()).isEqualTo(mockMemoryService);
    assertThat(context.liveRequestQueue()).isEmpty();
    assertThat(context.invocationId()).isEqualTo(testInvocationId);
    assertThat(context.agent()).isEqualTo(mockAgent);
    assertThat(context.session()).isEqualTo(session);
    assertThat(context.userContent()).hasValue(userContent);
    assertThat(context.runConfig()).isEqualTo(runConfig);
    assertThat(context.endInvocation()).isFalse();
}
"
    "@Test
public void testSetAgent() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    BaseAgent newMockAgent = mock(BaseAgent.class);
    context.agent(newMockAgent);
    assertThat(context.agent()).isEqualTo(newMockAgent);
}
"
    "@Test
public void testEquals_sameObject() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(context)).isTrue();
}
"
    "@Test
public void testEquals_null() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(null)).isFalse();
}
"
    "@Test
public void testEquals_sameValues() {
    InvocationContext context1 = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext context2 = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context1.equals(context2)).isTrue();

    assertThat(context2.equals(context1)).isTrue();
}
"
    "@Test
public void testEquals_differentValues() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext contextWithDiffSessionService = InvocationContext.builder().sessionService(
    mock(BaseSessionService.class)).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffInvocationId = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(
    "another-id").agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffAgent = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(
    mock(BaseAgent.class)).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithUserContentEmpty = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithLiveQueuePresent = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).liveRequestQueue(liveRequestQueue).agent(mockAgent).session(session).userContent(Optional.empty()).runConfig(runConfig).endInvocation(false).build();
    assertThat(context.equals(contextWithDiffSessionService)).isFalse();
    assertThat(context.equals(contextWithDiffInvocationId)).isFalse();
    assertThat(context.equals(contextWithDiffAgent)).isFalse();
    assertThat(context.equals(contextWithUserContentEmpty)).isFalse();
    assertThat(context.equals(contextWithLiveQueuePresent)).isFalse();
}
"
    "@Test
public void testHashCode_differentValues() {
    InvocationContext context = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();

    InvocationContext contextWithDiffSessionService = InvocationContext.builder().sessionService(
    mock(BaseSessionService.class)).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(testInvocationId).agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    InvocationContext contextWithDiffInvocationId = InvocationContext.builder().sessionService(mockSessionService).artifactService(mockArtifactService).memoryService(mockMemoryService).pluginManager(pluginManager).invocationId(
    "another-id").agent(mockAgent).session(session).userContent(Optional.of(userContent)).runConfig(runConfig).endInvocation(false).build();
    assertThat(context).isNotEqualTo(contextWithDiffSessionService);
    assertThat(context).isNotEqualTo(contextWithDiffInvocationId);
}
"

File Path: /var/tmp/Roost/RoostGPT/functional-from-source-code/5ce8eb4e-e5ae-411a-9a71-43493e595c35/source/adk-java/core/src/test/java/com/google/adk/agents/CallbacksTest.java
Tests:
    "@Test
public void testRun_withModelCallbacks_receivesCorrectContext() {
    Content realContent = Content.fromParts(Part.fromText("Real LLM response"));
    TestLlm testLlm = createTestLlm(createLlmResponse(realContent));
    LlmAgent agent = createTestAgentBuilder(testLlm).beforeModelCallback((callbackContext, request) -> {
        assertThat(callbackContext.invocationId()).isNotEmpty();
        assertThat(callbackContext.agentName()).isEqualTo("test agent");
        return Maybe.empty();
    }).afterModelCallback((callbackContext, response) -> {
        assertThat(callbackContext.invocationId()).isNotEmpty();
        assertThat(callbackContext.agentName()).isEqualTo("test agent");
        assertThat(response.content()).hasValue(realContent);
        return Maybe.empty();
    }).build();
    InvocationContext invocationContext = createInvocationContext(agent);
    List<Event> events = agent.runAsync(invocationContext).toList().blockingGet();
    assertThat(events).hasSize(1);
    assertThat(getOnlyElement(events).content()).hasValue(realContent);
}
"Scenario 1: ReturnsInvocationIdWhenInvocationContextIsValid

Details:
  TestName: returnsInvocationIdWhenInvocationContextIsValid
  Description: This test checks that the invocationId() method of ReadonlyContext returns the correct invocation ID when the underlying InvocationContext is properly initialized with a non-null, non-empty invocation ID string.

Execution:
  Arrange: Create a mock or stub of InvocationContext that returns a known, non-null string (e.g., "invocation-123") when invocationId() is called. Instantiate ReadonlyContext with this InvocationContext.
  Act: Call the invocationId() method on the ReadonlyContext instance.
  Assert: Assert that the returned value matches the expected invocation ID string ("invocation-123").

Validation:
  This assertion verifies that ReadonlyContext correctly delegates the invocationId() call to its internal InvocationContext and returns the expected value. This is fundamental to ensuring that consumers of ReadonlyContext receive accurate invocation identifiers for tracking and logging purposes.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;

import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

class ReadonlyContextInvocationIdTest {

  private InvocationContext mockInvocationContext;

  @BeforeEach
  void setUp() {
    mockInvocationContext = mock(InvocationContext.class);
  }

  @Test
  @Tag("valid")
  public void testReturnsInvocationIdWhenInvocationContextIsValid() {
    String expectedInvocationId = "invocation-123"; // TODO: Change to desired test
    // value if needed
    when(mockInvocationContext.invocationId()).thenReturn(expectedInvocationId);
    ReadonlyContext readonlyContext = new ReadonlyContext(mockInvocationContext);
    String actualInvocationId = readonlyContext.invocationId();
    assertEquals(expectedInvocationId, actualInvocationId);
  }
}
