/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Azure Open AI and AI Model gpt-5

ROOST_METHOD_HASH=addSessionToMemory_8a630adf5c
ROOST_METHOD_SIG_HASH=addSessionToMemory_3e3003d0a0

Scenario 1: Successfully stores a session with events that have non-empty parts

Details:
  TestName: storesSessionWithEventsHavingNonEmptyParts
  Description: Verifies that addSessionToMemory stores a session whose events include content with present, non-empty parts. Confirms that the returned Completable completes without errors and that the stored events are discoverable via searchMemory.

Execution:
  Arrange: Create a Session with appName "appA", userId "user1", session id "s1", and events where at least one event has content().isPresent() and parts().isPresent() with a non-empty list containing a Part with non-empty text like "hello world".
  Act: Invoke addSessionToMemory(session) and await the Completable to complete. Then call searchMemory("appA", "user1", "hello") to retrieve memories.
  Assert: Assert the Completable completes successfully. Assert that searchMemory returns at least one MemoryEntry with content containing the word "hello".

Validation:
  Confirms that events meeting the filter (content present, parts present and non-empty) are retained and can be retrieved through searchMemory. Ensures the Completable signals completion, indicating the write to memory occurred.

*/

// ********RoostGPT********

package com.google.adk.memory;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import com.google.adk.events.Event;
import com.google.adk.sessions.Session;
import com.google.common.collect.ImmutableList;
import com.google.genai.types.Content;
import com.google.genai.types.Part;
import io.reactivex.rxjava3.core.Completable;
import io.reactivex.rxjava3.core.Single;
import java.time.Instant;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class InMemoryMemoryServiceAddSessionToMemoryTest {

  private InMemoryMemoryService service;

  @BeforeEach
  public void setUp() {
    service = new InMemoryMemoryService();
  }

  @Test
  @Tag("integration")
  public void storesSessionWithEventsHavingNonEmptyParts() {
    EventBundle valid = createEventWithText("hello world", "authorA", 1700000000L);
    EventBundle invalidEmptyParts = createEventWithEmptyParts("authorB", 1700000001L);
    Session session =
        createSession(
            "appA", "user1", "s1", ImmutableList.of(valid.event, invalidEmptyParts.event));
    Completable completable = service.addSessionToMemory(session);
    com.google.common.truth.Truth.assertThat(
            completable.test().assertNoErrors().assertComplete().isDisposed())
        .isTrue();
    Single<SearchMemoryResponse> single = service.searchMemory("appA", "user1", "hello");
    SearchMemoryResponse response = single.blockingGet();
    assertNotNull((Object) response);
    ImmutableList<MemoryEntry> memories = response.memories();
    assertNotNull((Object) memories);
    assertEquals((int) 1, (int) memories.size());
    MemoryEntry memory = memories.get(0);
    assertEquals((Object) valid.content, (Object) memory.content());
    String expectedTimestamp = Instant.ofEpochSecond(1700000000L).toString();
    assertEquals((String) expectedTimestamp, (String) memory.timestamp());
  }

  @Test
  @Tag("invalid")
  public void ignoresEventsWithEmptyParts() {
    EventBundle invalidEmptyParts = createEventWithEmptyParts("authorC", 1700000002L);
    Session session =
        createSession("appA", "user1", "s2", ImmutableList.of(invalidEmptyParts.event));
    Completable completable = service.addSessionToMemory(session);
    com.google.common.truth.Truth.assertThat(
            completable.test().assertNoErrors().assertComplete().isDisposed())
        .isTrue();
    SearchMemoryResponse response = service.searchMemory("appA", "user1", "anything").blockingGet();
    assertNotNull((Object) response);
    ImmutableList<MemoryEntry> memories = response.memories();
    assertEquals((int) 0, (int) memories.size());
  }

  @Test
  @Tag("invalid")
  public void ignoresEventsWithNoContent() {
    Event eventNoContent = mock(Event.class);
    when(eventNoContent.content()).thenReturn(Optional.empty());
    when(eventNoContent.author()).thenReturn("authorD");
    when(eventNoContent.timestamp()).thenReturn(1700000003L);
    Session session = createSession("appA", "user1", "s3", ImmutableList.of(eventNoContent));
    Completable completable = service.addSessionToMemory(session);
    com.google.common.truth.Truth.assertThat(
            completable.test().assertNoErrors().assertComplete().isDisposed())
        .isTrue();
    SearchMemoryResponse response = service.searchMemory("appA", "user1", "any").blockingGet();
    assertNotNull((Object) response);
    ImmutableList<MemoryEntry> memories = response.memories();
    assertEquals((int) 0, (int) memories.size());
  }

  @Test
  @Tag("valid")
  public void caseInsensitiveAndRegexMatching() {
    EventBundle valid = createEventWithText("Hello, World.", "authorE", 1800000000L);
    Session session = createSession("appA", "user1", "s4", ImmutableList.of(valid.event));
    Completable completable = service.addSessionToMemory(session);
    com.google.common.truth.Truth.assertThat(
            completable.test().assertNoErrors().assertComplete().isDisposed())
        .isTrue();
    SearchMemoryResponse response = service.searchMemory("appA", "user1", "hello").blockingGet();
    assertNotNull((Object) response);
    ImmutableList<MemoryEntry> memories = response.memories();
    assertEquals((int) 1, (int) memories.size());
    MemoryEntry memory = memories.get(0);
    String expectedTimestamp = Instant.ofEpochSecond(1800000000L).toString();
    assertEquals((String) expectedTimestamp, (String) memory.timestamp());
  }

  @Test
  @Tag("boundary")
  public void searchIsIsolatedByAppAndUser() {
    EventBundle valid = createEventWithText("isolation check", "authorF", 1900000000L);
    Session session = createSession("appA", "user1", "s5", ImmutableList.of(valid.event));
    Completable completable = service.addSessionToMemory(session);
    com.google.common.truth.Truth.assertThat(
            completable.test().assertNoErrors().assertComplete().isDisposed())
        .isTrue();
    SearchMemoryResponse wrongApp =
        service.searchMemory("appB", "user1", "isolation").blockingGet(); // TODO:
    // change
    // app
    // name
    // if
    // needed
    ImmutableList<MemoryEntry> wrongAppMemories = wrongApp.memories();
    assertEquals((int) 0, (int) wrongAppMemories.size());
    SearchMemoryResponse wrongUser =
        service.searchMemory("appA", "user2", "isolation").blockingGet(); // TODO:
    // change
    // user
    // id
    // if
    // needed
    ImmutableList<MemoryEntry> wrongUserMemories = wrongUser.memories();
    assertEquals((int) 0, (int) wrongUserMemories.size());
    SearchMemoryResponse correct = service.searchMemory("appA", "user1", "isolation").blockingGet();
    ImmutableList<MemoryEntry> correctMemories = correct.memories();
    assertEquals((int) 1, (int) correctMemories.size());
  }

  @Test
  @Tag("integration")
  public void multipleSessionsForSameUser() {
    EventBundle eventAlpha = createEventWithText("alpha note", "authorG", 2000000000L);
    Session session1 = createSession("appA", "user1", "s6", ImmutableList.of(eventAlpha.event));
    EventBundle eventBeta = createEventWithText("beta memo", "authorH", 2000000100L);
    Session session2 = createSession("appA", "user1", "s7", ImmutableList.of(eventBeta.event));
    com.google.common.truth.Truth.assertThat(
            service
                .addSessionToMemory(session1)
                .test()
                .assertNoErrors()
                .assertComplete()
                .isDisposed())
        .isTrue();
    com.google.common.truth.Truth.assertThat(
            service
                .addSessionToMemory(session2)
                .test()
                .assertNoErrors()
                .assertComplete()
                .isDisposed())
        .isTrue();
    SearchMemoryResponse alphaSearch = service.searchMemory("appA", "user1", "alpha").blockingGet();
    assertEquals((int) 1, (int) alphaSearch.memories().size());
    SearchMemoryResponse betaSearch = service.searchMemory("appA", "user1", "beta").blockingGet();
    assertEquals((int) 1, (int) betaSearch.memories().size());
  }

  @Test
  @Tag("boundary")
  public void completesWhenSessionHasNoEvents() {
    Session session = createSession("appA", "user1", "s8", ImmutableList.of());
    com.google.common.truth.Truth.assertThat(
            service
                .addSessionToMemory(session)
                .test()
                .assertNoErrors()
                .assertComplete()
                .isDisposed())
        .isTrue();
    SearchMemoryResponse response = service.searchMemory("appA", "user1", "query").blockingGet();
    assertEquals((int) 0, (int) response.memories().size());
  }

  @Test
  @Tag("invalid")
  public void ignoresEventsWithEmptyTextParts() {
    Part emptyTextPart = mock(Part.class);
    when(emptyTextPart.text()).thenReturn(Optional.of(""));
    Content content = mock(Content.class);
    when(content.parts()).thenReturn(Optional.of(ImmutableList.of(emptyTextPart)));
    Event event = mock(Event.class);
    when(event.content()).thenReturn(Optional.of(content));
    when(event.author()).thenReturn("authorI");
    when(event.timestamp()).thenReturn(2100000000L);
    Session session = createSession("appA", "user1", "s9", ImmutableList.of(event));
    com.google.common.truth.Truth.assertThat(
            service
                .addSessionToMemory(session)
                .test()
                .assertNoErrors()
                .assertComplete()
                .isDisposed())
        .isTrue();
    SearchMemoryResponse response = service.searchMemory("appA", "user1", "any").blockingGet();
    assertEquals((int) 0, (int) response.memories().size());
  }

  private Session createSession(
      String appName, String userId, String sessionId, ImmutableList<Event> events) {
    Session session = mock(Session.class);
    when(session.appName()).thenReturn(appName);
    when(session.userId()).thenReturn(userId);
    when(session.id()).thenReturn(sessionId);
    when(session.events()).thenReturn(events);
    return session;
  }

  private EventBundle createEventWithText(String text, String author, long epochSeconds) {
    Part part = mock(Part.class);
    when(part.text()).thenReturn(Optional.of(text));
    Content content = mock(Content.class);
    when(content.parts()).thenReturn(Optional.of(ImmutableList.of(part)));
    Event event = mock(Event.class);
    when(event.content()).thenReturn(Optional.of(content));
    when(event.author()).thenReturn(author);
    when(event.timestamp()).thenReturn(epochSeconds);
    return new EventBundle(event, content);
  }

  private EventBundle createEventWithEmptyParts(String author, long epochSeconds) {
    Content content = mock(Content.class);
    when(content.parts()).thenReturn(Optional.of(ImmutableList.of()));
    Event event = mock(Event.class);
    when(event.content()).thenReturn(Optional.of(content));
    when(event.author()).thenReturn(author);
    when(event.timestamp()).thenReturn(epochSeconds);
    return new EventBundle(event, content);
  }

  private static class EventBundle {

    final Event event;

    final Content content;

    EventBundle(Event event, Content content) {
      this.event = event;
      this.content = content;
    }
  }
}
