/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Azure Open AI and AI Model gpt-5

ROOST_METHOD_HASH=addSessionToMemory_8a630adf5c
ROOST_METHOD_SIG_HASH=addSessionToMemory_3e3003d0a0

Scenario 1: Successfully stores a session with events that have non-empty parts

Details:
  TestName: storesSessionWithEventsHavingNonEmptyParts
  Description: Verifies that addSessionToMemory stores a session whose events include content with present, non-empty parts. Confirms that the returned Completable completes without errors and that the stored events are discoverable via searchMemory.

Execution:
  Arrange: Create a Session with appName "appA", userId "user1", session id "s1", and events where at least one event has content().isPresent() and parts().isPresent() with a non-empty list containing a Part with non-empty text like "hello world".
  Act: Invoke addSessionToMemory(session) and await the Completable to complete. Then call searchMemory("appA", "user1", "hello") to retrieve memories.
  Assert: Assert the Completable completes successfully. Assert that searchMemory returns at least one MemoryEntry with content containing the word "hello".

Validation:
  Confirms that events meeting the filter (content present, parts present and non-empty) are retained and can be retrieved through searchMemory. Ensures the Completable signals completion, indicating the write to memory occurred.

*/

// ********RoostGPT********

package com.google.adk.memory;

import static org.junit.jupiter.api.Assertions.*;

import com.google.adk.events.Event;
import com.google.adk.sessions.Session;
import com.google.genai.types.Content;
import com.google.genai.types.Part;
import io.reactivex.rxjava3.core.Completable;
import io.reactivex.rxjava3.core.Single;
import java.util.List;
import java.util.Locale;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class InMemoryMemoryServiceAddSessionToMemoryTest {

  @Test
  @Tag("integration")
  public void testStoresSessionWithEventsHavingNonEmptyParts() {
    InMemoryMemoryService service = new InMemoryMemoryService();
    Session session = Mockito.mock(Session.class);
    Mockito.when(session.appName()).thenReturn("appA");
    Mockito.when(session.userId()).thenReturn("user1");
    Mockito.when(session.id()).thenReturn("s1"); // TODO: Change session id if needed
    // Event with non-empty parts (should be retained)
    Event keptEvent = Mockito.mock(Event.class);
    Content keptContent = Mockito.mock(Content.class);
    Part partWithText = Mockito.mock(Part.class);
    Mockito.when(partWithText.text()).thenReturn(Optional.of("hello world")); // Non-empty
    // text
    Mockito.when(keptContent.parts()).thenReturn(Optional.of(List.of(partWithText)));
    Mockito.when(keptEvent.content()).thenReturn(Optional.of(keptContent));
    Mockito.when(keptEvent.author()).thenReturn("author1");
    Mockito.when(keptEvent.timestamp()).thenReturn(1700000000L);
    // Event with empty parts (should be filtered out)
    Event emptyPartsEvent = Mockito.mock(Event.class);
    Content emptyContent = Mockito.mock(Content.class);
    Mockito.when(emptyContent.parts()).thenReturn(Optional.of(List.of()));
    Mockito.when(emptyPartsEvent.content()).thenReturn(Optional.of(emptyContent));
    Mockito.when(emptyPartsEvent.author()).thenReturn("author2");
    Mockito.when(emptyPartsEvent.timestamp()).thenReturn(1700000001L);
    // Event with no content (should be filtered out)
    Event noContentEvent = Mockito.mock(Event.class);
    Mockito.when(noContentEvent.content()).thenReturn(Optional.empty());
    Mockito.when(noContentEvent.author()).thenReturn("author3");
    Mockito.when(noContentEvent.timestamp()).thenReturn(1700000002L);
    Mockito.when(session.events()).thenReturn(List.of(keptEvent, emptyPartsEvent, noContentEvent));
    Completable completable = service.addSessionToMemory(session);
    assertDoesNotThrow(
        () -> {
          completable.blockingAwait();
        });
    Single<SearchMemoryResponse> searchSingle = service.searchMemory("appA", "user1", "hello");
    SearchMemoryResponse response = assertDoesNotThrow(searchSingle::blockingGet);
    assertNotNull((Object) response);
    // Validate that at least one memory contains the word "hello" in its parts
    List<MemoryEntry> memories = response.memories();
    assertNotNull((Object) memories);
    assertFalse(
        ((List<MemoryEntry>) memories).isEmpty(), "Expected at least one memory to be returned");
    boolean foundHello = false;
    for (MemoryEntry memory : memories) {
      assertNotNull((Object) memory.content(), "Memory content should not be null");
      Optional<List<Part>> partsOpt = memory.content().parts();
      if (partsOpt.isPresent()) {
        for (Part p : partsOpt.get()) {
          String text = p.text().orElse("");
          if (text.toLowerCase(Locale.ROOT).contains("hello")) {
            foundHello = true;
            break;
          }
        }
      }
      if (foundHello) {
        break;
      }
    }
    assertTrue((boolean) foundHello, "Expected at least one memory to contain the word 'hello'");
  }
}
