/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Azure Open AI and AI Model gpt-5

ROOST_METHOD_HASH=addSessionToMemory_8a630adf5c
ROOST_METHOD_SIG_HASH=addSessionToMemory_3e3003d0a0

Scenario 1: Successfully stores a session with events that have non-empty parts

Details:
  TestName: storesSessionWithEventsHavingNonEmptyParts
  Description: Verifies that addSessionToMemory stores a session whose events include content with present, non-empty parts. Confirms that the returned Completable completes without errors and that the stored events are discoverable via searchMemory.

Execution:
  Arrange: Create a Session with appName "appA", userId "user1", session id "s1", and events where at least one event has content().isPresent() and parts().isPresent() with a non-empty list containing a Part with non-empty text like "hello world".
  Act: Invoke addSessionToMemory(session) and await the Completable to complete. Then call searchMemory("appA", "user1", "hello") to retrieve memories.
  Assert: Assert the Completable completes successfully. Assert that searchMemory returns at least one MemoryEntry with content containing the word "hello".

Validation:
  Confirms that events meeting the filter (content present, parts present and non-empty) are retained and can be retrieved through searchMemory. Ensures the Completable signals completion, indicating the write to memory occurred.

*/

// ********RoostGPT********

package com.google.adk.memory;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.google.adk.events.Event;
import com.google.adk.sessions.Session;
import com.google.genai.types.Content;
import com.google.genai.types.Part;
import io.reactivex.rxjava3.core.Completable;
import io.reactivex.rxjava3.core.Single;
import java.time.Instant;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class InMemoryMemoryServiceAddSessionToMemoryTest {

  private InMemoryMemoryService service;

  @BeforeEach
  public void setUp() {
    service = new InMemoryMemoryService();
  }

  @Test
  @Tag("valid")
  public void testStoresSessionWithEventsHavingNonEmptyParts() {
    Session session = Mockito.mock(Session.class);
    Event event = Mockito.mock(Event.class);
    Content content = Mockito.mock(Content.class);
    Part part = Mockito.mock(Part.class);
    Mockito.when(session.appName()).thenReturn("appA"); // TODO: Change if app name
    // differs
    Mockito.when(session.userId()).thenReturn("user1"); // TODO: Change if user id
    // differs
    Mockito.when(session.id()).thenReturn("s1"); // TODO: Change if session id differs
    Mockito.when(part.text()).thenReturn(Optional.of("hello world"));
    Mockito.when(content.parts()).thenReturn(Optional.of(Arrays.asList(part)));
    Mockito.when(event.content()).thenReturn(Optional.of(content));
    Mockito.when(event.author()).thenReturn("author1");
    Mockito.when(event.timestamp()).thenReturn(Instant.now().getEpochSecond());
    List<Event> events = Arrays.asList(event);
    Mockito.when(session.events()).thenReturn(events);
    Completable completable = service.addSessionToMemory(session);
    assertDoesNotThrow(
        () -> completable.blockingAwait(), "Completable should complete without errors");
    Single<SearchMemoryResponse> single = service.searchMemory("appA", "user1", "hello");
    SearchMemoryResponse response = single.blockingGet();
    assertNotNull(response, "Response should not be null");
    // Assert there is at least one memory entry that contains the word "hello"
    boolean found = false;
    List<MemoryEntry> memories = response.memories();
    assertNotNull(memories, "Memories should not be null");
    if (((int) memories.size()) > (int) 0) {
      for (MemoryEntry entry : memories) {
        if (entry != null && entry.content() != null && entry.content().parts().isPresent()) {
          List<Part> parts = entry.content().parts().get();
          for (Part p : parts) {
            if (p != null
                && p.text().isPresent()
                && p.text().get().toLowerCase().contains("hello")) {
              found = true;
              break;
            }
          }
        }
        if (found) {
          break;
        }
      }
    }
    assertTrue(found, "Expected at least one memory entry to contain the word 'hello'");
  }
}
