/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Azure Open AI and AI Model gpt-5

ROOST_METHOD_HASH=build_2a52dae09f
ROOST_METHOD_SIG_HASH=build_8cfd748976

Scenario 1: Build succeeds with minimal valid model and explicit proxy URL

Details:
  TestName: buildWithMinimalValidModelAndExplicitProxySucceeds
  Description: Verifies that build() returns a non-null ApigeeLlm instance when provided with a minimal valid model string in the format "apigee/<model_id>" and a non-empty proxyUrl. This confirms the happy-path for the simplest valid input.

Execution:
  Arrange: Create a Builder, call modelName("apigee/gemini-2.5-flash"), proxyUrl("https://apigee.example.com"), and customHeaders(new HashMap<>()).
  Act: Invoke build().
  Assert: Use assertNotNull to ensure the returned object is not null. Optionally, assertEquals(ApigeeLlm.class, result.getClass()) to confirm the type.

Validation:
  Confirms that a properly formatted model string and an explicit proxy URL result in a successful build. This validates the primary use case where all mandatory data is provided directly by the caller.


Scenario 2: Build succeeds with provider-only model and explicit proxy URL

Details:
  TestName: buildWithProviderOnlyModelAndExplicitProxySucceeds
  Description: Ensures that a model string with "apigee/<provider>/<model_id>" (e.g., "apigee/gemini/gemini-2.5-flash") is accepted and build() succeeds when a valid proxyUrl is supplied.

Execution:
  Arrange: Create a Builder, set modelName("apigee/gemini/gemini-2.5-flash"), proxyUrl("https://apigee.example.com"), and customHeaders(Collections.emptyMap()).
  Act: Call build().
  Assert: assertNotNull on the returned instance and assertEquals(ApigeeLlm.class, result.getClass()).

Validation:
  Verifies acceptance of a two-segment model (provider + model_id) as valid according to validateModelString, ensuring build() supports this allowed format.


Scenario 3: Build succeeds with version-only model and explicit proxy URL

Details:
  TestName: buildWithVersionOnlyModelAndExplicitProxySucceeds
  Description: Checks that a model string in the format "apigee/<version>/<model_id>" (e.g., "apigee/v1/gemini-2.5-flash") is valid and that build() returns an instance when proxyUrl is provided.

Execution:
  Arrange: Initialize Builder with modelName("apigee/v1/gemini-2.5-flash"), proxyUrl("https://apigee.example.com"), customHeaders(new HashMap<>()).
  Act: Invoke build().
  Assert: assertNotNull for the returned ApigeeLlm instance.

Validation:
  Confirms that version-only (two segment) model strings are recognized as valid by validateModelString and that build() proceeds without error.


Scenario 4: Build succeeds with provider, version, and model ID

Details:
  TestName: buildWithProviderVersionAndModelIdSucceeds
  Description: Ensures that a fully qualified model string "apigee/<provider>/<version>/<model_id>" (e.g., "apigee/gemini/v1/gemini-2.5-flash") is accepted and build() returns an instance when proxyUrl is set.

Execution:
  Arrange: Use Builder with modelName("apigee/gemini/v1/gemini-2.5-flash"), proxyUrl("https://apigee.example.com"), customHeaders(Collections.emptyMap()).
  Act: Call build().
  Assert: assertNotNull on the returned ApigeeLlm.

Validation:
  Demonstrates support for the most explicit model string form, ensuring that validateModelString and constructor integration permit it.


Scenario 5: Null modelName results in NullPointerException

Details:
  TestName: buildWithNullModelNameThrowsNullPointerException
  Description: Ensures that build() throws a NullPointerException when modelName is not provided (null), as validateModelString will dereference a null and throw.

Execution:
  Arrange: Create a Builder without calling modelName(..); set a valid proxyUrl("https://apigee.example.com").
  Act: Invoke build() expecting an exception.
  Assert: Use assertThrows(NullPointerException.class, ...).

Validation:
  Confirms the documented contract that a null modelName triggers a NullPointerException via validateModelString, enforcing mandatory model input.


Scenario 6: Missing "apigee/" prefix causes IllegalArgumentException

Details:
  TestName: buildWithMissingApigeePrefixThrowsIllegalArgumentException
  Description: Verifies that model strings without the "apigee/" prefix (e.g., "gemini-2.5-flash") are rejected by build().

Execution:
  Arrange: Builder with modelName("gemini-2.5-flash"), proxyUrl("https://apigee.example.com").
  Act: Call build() expecting an exception.
  Assert: assertThrows(IllegalArgumentException.class, ...) and optionally check that the message contains "Invalid model string: gemini-2.5-flash".

Validation:
  Ensures only model strings beginning with "apigee/" are allowed, as required by validateModelString.


Scenario 7: Trailing slash in model causes IllegalArgumentException

Details:
  TestName: buildWithTrailingSlashThrowsIllegalArgumentException
  Description: Checks that a model ending with a slash (e.g., "apigee/gemini-2.5-flash/") is considered invalid.

Execution:
  Arrange: Builder with modelName("apigee/gemini-2.5-flash/"), proxyUrl("https://apigee.example.com").
  Act: Invoke build() expecting failure.
  Assert: assertThrows(IllegalArgumentException.class, ...) and message contains "Invalid model string: apigee/gemini-2.5-flash/".

Validation:
  Confirms that an empty last path component is invalid per validateModelString.


Scenario 8: Empty model part after "apigee/" causes IllegalArgumentException

Details:
  TestName: buildWithEmptyModelPartThrowsIllegalArgumentException
  Description: Validates that "apigee/" with no model ID (i.e., nothing after the prefix) fails.

Execution:
  Arrange: Builder with modelName("apigee/"), proxyUrl("https://apigee.example.com").
  Act: Call build() expecting an exception.
  Assert: assertThrows(IllegalArgumentException.class, ...) and verify the message includes the invalid string.

Validation:
  Ensures that the model ID is required, as an empty post-prefix segment is invalid.


Scenario 9: Invalid provider token in three-segment model causes IllegalArgumentException

Details:
  TestName: buildWithInvalidProviderInThreeSegmentModelThrowsIllegalArgumentException
  Description: Ensures that a three-segment model with an unknown provider (e.g., "apigee/other/v1/gemini-2.5-flash") is rejected.

Execution:
  Arrange: Builder with modelName("apigee/other/v1/gemini-2.5-flash"), proxyUrl("https://apigee.example.com").
  Act: Invoke build().
  Assert: assertThrows(IllegalArgumentException.class, ...).

Validation:
  Confirms that only "vertex_ai" or "gemini" are accepted providers in the first position for three-segment models.


Scenario 10: Provider present but missing model ID causes IllegalArgumentException

Details:
  TestName: buildWithProviderButMissingModelIdThrowsIllegalArgumentException
  Description: Ensures that "apigee/gemini/" (provider plus trailing slash but missing model ID) fails.

Execution:
  Arrange: Builder with modelName("apigee/gemini/"), proxyUrl("https://apigee.example.com").
  Act: Call build() expecting failure.
  Assert: assertThrows(IllegalArgumentException.class, ...).

Validation:
  Confirms the requirement that the last component (model ID) must be non-empty.


Scenario 11: Too many path segments cause IllegalArgumentException

Details:
  TestName: buildWithTooManyPathSegmentsThrowsIllegalArgumentException
  Description: Ensures that a model string with more than three segments after "apigee/" (e.g., "apigee/a/b/c/d") is invalid.

Execution:
  Arrange: Builder with modelName("apigee/a/b/c/d"), proxyUrl("https://apigee.example.com").
  Act: Invoke build().
  Assert: assertThrows(IllegalArgumentException.class, ...).

Validation:
  Ensures strict adherence to allowed model string structures.


Scenario 12: Null proxyUrl uses APIGEE_PROXY_URL environment variable

Details:
  TestName: buildWithNullProxyUrlAndEnvVarSetSucceeds
  Description: Verifies that when proxyUrl is null but the environment variable APIGEE_PROXY_URL is set to a valid URL, build() succeeds.

Execution:
  Arrange: Temporarily set environment variable APIGEE_PROXY_URL to "https://env.apigee.example.com". Create Builder with modelName("apigee/gemini-2.5-flash") and proxyUrl(null).
  Act: Call build().
  Assert: assertNotNull on the returned ApigeeLlm instance.

Validation:
  Confirms that the constructor’s fallback logic to the environment variable is engaged, allowing build() to succeed without an explicit proxy URL.


Scenario 13: Empty proxyUrl string uses APIGEE_PROXY_URL environment variable

Details:
  TestName: buildWithEmptyProxyUrlAndEnvVarSetSucceeds
  Description: Ensures that an explicitly empty proxyUrl ("") is treated as absent, and if APIGEE_PROXY_URL is set, build() succeeds.

Execution:
  Arrange: Set APIGEE_PROXY_URL to a valid URL. Use Builder with modelName("apigee/gemini-2.5-flash"), proxyUrl(""), and empty headers.
  Act: Invoke build().
  Assert: assertNotNull on the result.

Validation:
  Verifies that empty proxyUrl values are considered unset and the environment variable can fulfill the requirement.


Scenario 14: Null proxyUrl and missing environment variable cause IllegalArgumentException

Details:
  TestName: buildWithNullProxyUrlAndNoEnvVarThrowsIllegalArgumentException
  Description: Checks that if proxyUrl is null and APIGEE_PROXY_URL is not set, build() fails due to the ApigeeLlm constructor validating the proxy URL.

Execution:
  Arrange: Ensure APIGEE_PROXY_URL is not set for the process. Create Builder with modelName("apigee/gemini-2.5-flash") and proxyUrl(null).
  Act: Call build().
  Assert: assertThrows(IllegalArgumentException.class, ...) and verify the message contains "APIGEE_PROXY_URL" and "not set".

Validation:
  Confirms strict requirement for a proxy URL via either explicit input or environment variable, aligning with constructor validation.


Scenario 15: Empty proxyUrl and missing environment variable cause IllegalArgumentException

Details:
  TestName: buildWithEmptyProxyUrlAndNoEnvVarThrowsIllegalArgumentException
  Description: Similar to Scenario 14 but with proxyUrl set to "". Verifies that an empty string is treated as unset and results in an exception when no environment fallback exists.

Execution:
  Arrange: Ensure APIGEE_PROXY_URL is not present. Builder with modelName("apigee/gemini-2.5-flash"), proxyUrl(""), and default headers.
  Act: Invoke build().
  Assert: assertThrows(IllegalArgumentException.class, ...) and assert that the message references APIGEE_PROXY_URL.

Validation:
  Reinforces that empty proxies are invalid without an environment-provided fallback.


Scenario 16: Duplicate tracking header in customHeaders causes IllegalArgumentException

Details:
  TestName: buildWithDuplicateTrackingHeaderInCustomHeadersThrowsIllegalArgumentException
  Description: Ensures that if customHeaders contains a key already set by internal tracking headers (e.g., "user-agent" or "x-goog-api-client"), the ImmutableMap builder in the constructor throws an IllegalArgumentException.

Execution:
  Arrange: Builder with valid modelName("apigee/gemini-2.5-flash") and proxyUrl("https://apigee.example.com"). Provide customHeaders map containing "user-agent" or "x-goog-api-client".
  Act: Invoke build() expecting an exception.
  Assert: assertThrows(IllegalArgumentException.class, ...).

Validation:
  Confirms that duplicate header keys are not allowed due to ImmutableMap’s duplicate key restrictions, protecting internal tracking headers from being overridden.


Scenario 17: Null header key causes NullPointerException

Details:
  TestName: buildWithNullHeaderKeyThrowsNullPointerException
  Description: Verifies that if customHeaders includes a null key, the ImmutableMap builder propagates a NullPointerException during build.

Execution:
  Arrange: Builder with valid model and proxy. Create customHeaders with a null key and a non-null value.
  Act: Invoke build().
  Assert: assertThrows(NullPointerException.class, ...).

Validation:
  Ensures header maps must have non-null keys, aligning with ImmutableMap constraints and preventing malformed HTTP headers.


Scenario 18: Null header value causes NullPointerException

Details:
  TestName: buildWithNullHeaderValueThrowsNullPointerException
  Description: Ensures that if customHeaders contains a null value, the constructor’s copy into an ImmutableMap fails with a NullPointerException.

Execution:
  Arrange: Builder with valid model and proxy. Set customHeaders with a valid string key and a null value.
  Act: Call build().
  Assert: assertThrows(NullPointerException.class, ...).

Validation:
  Confirms that header values must be non-null to avoid runtime failures when constructing HttpOptions.


Scenario 19: Large customHeaders map builds successfully

Details:
  TestName: buildWithLargeCustomHeadersMapSucceeds
  Description: Validates that build() can handle a large number of custom headers without error, provided there are no nulls or duplicates with tracking headers.

Execution:
  Arrange: Builder with valid model and proxy. Prepare a customHeaders map with many unique, valid header entries that do not conflict with "user-agent" or "x-goog-api-client".
  Act: Invoke build().
  Assert: assertNotNull on the returned ApigeeLlm.

Validation:
  Demonstrates robustness of the build process under larger configuration payloads.


Scenario 20: Leading whitespace in modelName causes IllegalArgumentException

Details:
  TestName: buildWithLeadingWhitespaceInModelNameThrowsIllegalArgumentException
  Description: Ensures that a model name with leading/trailing whitespace (e.g., " apigee/gemini-2.5-flash") is considered invalid by validateModelString.

Execution:
  Arrange: Builder with modelName(" apigee/gemini-2.5-flash") and valid proxyUrl.
  Act: Call build().
  Assert: assertThrows(IllegalArgumentException.class, ...).

Validation:
  Confirms that the model string must match the expected format exactly and is not auto-trimmed.


Scenario 21: Case-sensitive provider name invalidates model string

Details:
  TestName: buildWithCaseSensitiveProviderNameInvalidThrowsIllegalArgumentException
  Description: Verifies that using "Gemini" (capitalized) as the provider (e.g., "apigee/Gemini/v1/model") fails validation, since provider checks are case-sensitive.

Execution:
  Arrange: Builder with modelName("apigee/Gemini/v1/gemini-2.5-flash") and valid proxyUrl.
  Act: Invoke build().
  Assert: assertThrows(IllegalArgumentException.class, ...).

Validation:
  Reinforces that only the exact lowercase tokens "gemini" and "vertex_ai" are accepted providers in the three-segment form.


Scenario 22: Version without 'v' prefix in three-segment model causes IllegalArgumentException

Details:
  TestName: buildWithProviderVersionWhereVersionLacksVPrefixThrowsIllegalArgumentException
  Description: Ensures that a three-segment model with a version not starting with 'v' (e.g., "apigee/gemini/1/gemini-2.5-flash") is rejected.

Execution:
  Arrange: Builder with modelName("apigee/gemini/1/gemini-2.5-flash") and valid proxyUrl.
  Act: Call build().
  Assert: assertThrows(IllegalArgumentException.class, ...).

Validation:
  Confirms the version format requirement enforced by validateModelString.


Scenario 23: Single-letter 'v' as version in two-segment model succeeds

Details:
  TestName: buildWithSingleLetterVersionVSucceeds
  Description: Verifies that "apigee/v/gemini-2.5-flash" is considered valid since the version segment only needs to start with 'v'.

Execution:
  Arrange: Builder with modelName("apigee/v/gemini-2.5-flash"), proxyUrl("https://apigee.example.com"), and empty headers.
  Act: Invoke build().
  Assert: assertNotNull on the returned ApigeeLlm object.

Validation:
  Ensures that minimal version identifiers beginning with 'v' are accepted by the validator.


Scenario 24: Valid model and null customHeaders build successfully

Details:
  TestName: buildWithValidModelAndNullCustomHeadersSucceeds
  Description: Ensures that passing customHeaders(null) is permitted and results in a successful build when modelName and proxyUrl are valid.

Execution:
  Arrange: Builder with modelName("apigee/gemini-2.5-flash"), proxyUrl("https://apigee.example.com"), customHeaders(null).
  Act: Call build().
  Assert: assertNotNull on the returned instance.

Validation:
  Confirms that customHeaders is optional and that the constructor bypasses header merging when null is provided.


Scenario 25: Repeated build invocations yield distinct instances

Details:
  TestName: buildRepeatedInvocationsReturnDistinctInstances
  Description: Verifies that calling build() multiple times on the same Builder yields separate ApigeeLlm instances (no caching/sharing of instances).

Execution:
  Arrange: Builder with valid modelName and proxyUrl; ensure headers are valid.
  Act: Invoke build() twice, recording both results.
  Assert: Use assertNotSame(first, second) and assertNotNull for both instances.

Validation:
  Confirms that Builder creates new ApigeeLlm instances on each call, preventing unintended shared state between builds.

*/

// ********RoostGPT********

package com.google.adk.models;

import static com.google.common.base.Strings.isNullOrEmpty;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNotSame;
import static org.junit.jupiter.api.Assertions.assertThrows;

import java.lang.reflect.Field;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

public class ApigeeLlmBuilderBuildTest {

  private static final String ENV_PROXY_KEY = "APIGEE_PROXY_URL";

  private String originalProxyEnv;

  @BeforeEach
  public void beforeEach() {
    originalProxyEnv = System.getenv(ENV_PROXY_KEY);
  }

  @AfterEach
  public void afterEach() {
    if (isNullOrEmpty(originalProxyEnv)) {
      clearEnvVar(ENV_PROXY_KEY);
    } else {
      setEnvVar(ENV_PROXY_KEY, originalProxyEnv);
    }
  }

  @Test
  @Tag("valid")
  public void testBuildWithMinimalValidModelAndExplicitProxySucceeds() {
    ApigeeLlm.Builder builder = newParentBuilder();
    builder
        .modelName("apigee/gemini-2.5-flash")
        .proxyUrl("https://apigee.example.com") // TODO change to target proxy for
        // your environment
        .customHeaders(new HashMap<>());
    ApigeeLlm result = builder.build();
    assertNotNull((Object) result);
    assertEquals((Class<?>) ApigeeLlm.class, (Class<?>) result.getClass());
  }

  @Test
  @Tag("valid")
  public void testBuildWithProviderOnlyModelAndExplicitProxySucceeds() {
    ApigeeLlm.Builder builder = newParentBuilder();
    builder
        .modelName("apigee/gemini/gemini-2.5-flash")
        .proxyUrl("https://apigee.example.com") // TODO change to target proxy for
        // your environment
        .customHeaders(Collections.emptyMap());
    ApigeeLlm result = builder.build();
    assertNotNull((Object) result);
    assertEquals((Class<?>) ApigeeLlm.class, (Class<?>) result.getClass());
  }

  @Test
  @Tag("valid")
  public void testBuildWithVersionOnlyModelAndExplicitProxySucceeds() {
    ApigeeLlm.Builder builder = newParentBuilder();
    builder
        .modelName("apigee/v1/gemini-2.5-flash")
        .proxyUrl("https://apigee.example.com") // TODO change to target proxy for
        // your environment
        .customHeaders(new HashMap<>());
    ApigeeLlm result = builder.build();
    assertNotNull((Object) result);
  }

  @Test
  @Tag("valid")
  public void testBuildWithProviderVersionAndModelIdSucceeds() {
    ApigeeLlm.Builder builder = newParentBuilder();
    builder
        .modelName("apigee/gemini/v1/gemini-2.5-flash")
        .proxyUrl("https://apigee.example.com") // TODO change to target proxy for
        // your environment
        .customHeaders(Collections.emptyMap());
    ApigeeLlm result = builder.build();
    assertNotNull((Object) result);
  }

  @Test
  @Tag("invalid")
  public void testBuildWithNullModelNameThrowsNullPointerException() {
    ApigeeLlm.Builder builder = newParentBuilder();
    builder.proxyUrl("https://apigee.example.com"); // TODO change to target proxy for
    // your environment
    NullPointerException ex =
        assertThrows(
            (Class<NullPointerException>) NullPointerException.class, () -> builder.build());
    assertNotNull((Object) ex);
  }

  @Test
  @Tag("invalid")
  public void testBuildWithMissingApigeePrefixThrowsIllegalArgumentException() {
    ApigeeLlm.Builder builder = newParentBuilder();
    builder.modelName("gemini-2.5-flash").proxyUrl("https://apigee.example.com"); // TODO
    // change
    // to
    // target
    // proxy
    // for
    // your
    // environment
    IllegalArgumentException ex =
        assertThrows(
            (Class<IllegalArgumentException>) IllegalArgumentException.class,
            () -> builder.build());
    String msg = Objects.requireNonNull(ex.getMessage());
    assertNotNull((Object) msg);
    // Message should include the invalid string
    org.junit.jupiter.api.Assertions.assertTrue(
        msg.contains("Invalid model string: gemini-2.5-flash"));
  }

  @Test
  @Tag("invalid")
  public void testBuildWithTrailingSlashThrowsIllegalArgumentException() {
    ApigeeLlm.Builder builder = newParentBuilder();
    builder.modelName("apigee/gemini-2.5-flash/").proxyUrl("https://apigee.example.com"); // TODO
    // change
    // to
    // target
    // proxy
    // for
    // your
    // environment
    IllegalArgumentException ex =
        assertThrows(
            (Class<IllegalArgumentException>) IllegalArgumentException.class,
            () -> builder.build());
    String msg = Objects.requireNonNull(ex.getMessage());
    assertNotNull((Object) msg);
    org.junit.jupiter.api.Assertions.assertTrue(
        msg.contains("Invalid model string: apigee/gemini-2.5-flash/"));
  }

  @Test
  @Tag("invalid")
  public void testBuildWithEmptyModelPartThrowsIllegalArgumentException() {
    ApigeeLlm.Builder builder = newParentBuilder();
    builder.modelName("apigee/").proxyUrl("https://apigee.example.com"); // TODO
    // change
    // to
    // target
    // proxy
    // for
    // your
    // environment
    IllegalArgumentException ex =
        assertThrows(
            (Class<IllegalArgumentException>) IllegalArgumentException.class,
            () -> builder.build());
    String msg = Objects.requireNonNull(ex.getMessage());
    assertNotNull((Object) msg);
    org.junit.jupiter.api.Assertions.assertTrue(msg.contains("apigee/"));
  }

  @Test
  @Tag("invalid")
  public void testBuildWithInvalidProviderInThreeSegmentModelThrowsIllegalArgumentException() {
    ApigeeLlm.Builder builder = newParentBuilder();
    builder
        .modelName("apigee/other/v1/gemini-2.5-flash")
        .proxyUrl("https://apigee.example.com"); // TODO
    // change
    // to
    // target
    // proxy
    // for
    // your
    // environment
    assertThrows(
        (Class<IllegalArgumentException>) IllegalArgumentException.class, () -> builder.build());
  }

  @Test
  @Tag("invalid")
  public void testBuildWithProviderButMissingModelIdThrowsIllegalArgumentException() {
    ApigeeLlm.Builder builder = newParentBuilder();
    builder.modelName("apigee/gemini/").proxyUrl("https://apigee.example.com"); // TODO
    // change
    // to
    // target
    // proxy
    // for
    // your
    // environment
    assertThrows(
        (Class<IllegalArgumentException>) IllegalArgumentException.class, () -> builder.build());
  }

  @Test
  @Tag("invalid")
  public void testBuildWithTooManyPathSegmentsThrowsIllegalArgumentException() {
    ApigeeLlm.Builder builder = newParentBuilder();
    builder.modelName("apigee/a/b/c/d").proxyUrl("https://apigee.example.com"); // TODO
    // change
    // to
    // target
    // proxy
    // for
    // your
    // environment
    assertThrows(
        (Class<IllegalArgumentException>) IllegalArgumentException.class, () -> builder.build());
  }

  @Test
  @Tag("integration")
  public void testBuildWithNullProxyUrlAndEnvVarSetSucceeds() {
    setEnvVar(ENV_PROXY_KEY, "https://env.apigee.example.com"); // TODO set to
    // environment-provided
    // proxy URL
    ApigeeLlm.Builder builder = newParentBuilder();
    builder.modelName("apigee/gemini-2.5-flash").proxyUrl(null).customHeaders(new HashMap<>());
    ApigeeLlm result = builder.build();
    assertNotNull((Object) result);
  }

  @Test
  @Tag("integration")
  public void testBuildWithEmptyProxyUrlAndEnvVarSetSucceeds() {
    setEnvVar(ENV_PROXY_KEY, "https://env.apigee.example.com"); // TODO set to
    // environment-provided
    // proxy URL
    ApigeeLlm.Builder builder = newParentBuilder();
    builder.modelName("apigee/gemini-2.5-flash").proxyUrl("").customHeaders(Collections.emptyMap());
    ApigeeLlm result = builder.build();
    assertNotNull((Object) result);
  }

  @Test
  @Tag("integration")
  public void testBuildWithNullProxyUrlAndNoEnvVarThrowsIllegalArgumentException() {
    clearEnvVar(ENV_PROXY_KEY);
    ApigeeLlm.Builder builder = newParentBuilder();
    builder.modelName("apigee/gemini-2.5-flash").proxyUrl(null);
    IllegalArgumentException ex =
        assertThrows(
            (Class<IllegalArgumentException>) IllegalArgumentException.class,
            () -> builder.build());
    String msg = Objects.requireNonNull(ex.getMessage());
    assertNotNull((Object) msg);
    org.junit.jupiter.api.Assertions.assertTrue(msg.contains("APIGEE_PROXY_URL"));
  }

  @Test
  @Tag("integration")
  public void testBuildWithEmptyProxyUrlAndNoEnvVarThrowsIllegalArgumentException() {
    clearEnvVar(ENV_PROXY_KEY);
    ApigeeLlm.Builder builder = newParentBuilder();
    builder.modelName("apigee/gemini-2.5-flash").proxyUrl("").customHeaders(new HashMap<>());
    IllegalArgumentException ex =
        assertThrows(
            (Class<IllegalArgumentException>) IllegalArgumentException.class,
            () -> builder.build());
    String msg = Objects.requireNonNull(ex.getMessage());
    assertNotNull((Object) msg);
    org.junit.jupiter.api.Assertions.assertTrue(msg.contains("APIGEE_PROXY_URL"));
  }

  @Test
  @Tag("invalid")
  public void testBuildWithDuplicateTrackingHeaderInCustomHeadersThrowsIllegalArgumentException() {
    Map<String, String> headers = new HashMap<>();
    headers.put("user-agent", "duplicate-ua");
    ApigeeLlm.Builder builder = newParentBuilder();
    builder
        .modelName("apigee/gemini-2.5-flash")
        .proxyUrl("https://apigee.example.com") // TODO change to target proxy for
        // your environment
        .customHeaders(headers);
    assertThrows(
        (Class<IllegalArgumentException>) IllegalArgumentException.class, () -> builder.build());
  }

  @Test
  @Tag("invalid")
  public void testBuildWithNullHeaderKeyThrowsNullPointerException() {
    Map<String, String> headers = new HashMap<>();
    headers.put(null, "value");
    ApigeeLlm.Builder builder = newParentBuilder();
    builder
        .modelName("apigee/gemini-2.5-flash")
        .proxyUrl("https://apigee.example.com") // TODO change to target proxy for
        // your environment
        .customHeaders(headers);
    assertThrows((Class<NullPointerException>) NullPointerException.class, () -> builder.build());
  }

  @Test
  @Tag("invalid")
  public void testBuildWithNullHeaderValueThrowsNullPointerException() {
    Map<String, String> headers = new HashMap<>();
    headers.put("x-custom", null);
    ApigeeLlm.Builder builder = newParentBuilder();
    builder
        .modelName("apigee/gemini-2.5-flash")
        .proxyUrl("https://apigee.example.com") // TODO change to target proxy for
        // your environment
        .customHeaders(headers);
    assertThrows((Class<NullPointerException>) NullPointerException.class, () -> builder.build());
  }

  @Test
  @Tag("boundary")
  public void testBuildWithLargeCustomHeadersMapSucceeds() {
    Map<String, String> headers = new HashMap<>();
    for (int i = 0; i < 100; i++) {
      headers.put("x-h-" + i, "v-" + i);
    }
    ApigeeLlm.Builder builder = newParentBuilder();
    builder
        .modelName("apigee/gemini-2.5-flash")
        .proxyUrl("https://apigee.example.com") // TODO change to target proxy for
        // your environment
        .customHeaders(headers);
    ApigeeLlm result = builder.build();
    assertNotNull((Object) result);
  }

  @Test
  @Tag("invalid")
  public void testBuildWithLeadingWhitespaceInModelNameThrowsIllegalArgumentException() {
    ApigeeLlm.Builder builder = newParentBuilder();
    builder.modelName(" apigee/gemini-2.5-flash").proxyUrl("https://apigee.example.com"); // TODO
    // change
    // to
    // target
    // proxy
    // for
    // your
    // environment
    assertThrows(
        (Class<IllegalArgumentException>) IllegalArgumentException.class, () -> builder.build());
  }

  @Test
  @Tag("invalid")
  public void testBuildWithCaseSensitiveProviderNameInvalidThrowsIllegalArgumentException() {
    ApigeeLlm.Builder builder = newParentBuilder();
    builder
        .modelName("apigee/Gemini/v1/gemini-2.5-flash")
        .proxyUrl("https://apigee.example.com"); // TODO
    // change
    // to
    // target
    // proxy
    // for
    // your
    // environment
    assertThrows(
        (Class<IllegalArgumentException>) IllegalArgumentException.class, () -> builder.build());
  }

  @Test
  @Tag("invalid")
  public void testBuildWithProviderVersionWhereVersionLacksVPrefixThrowsIllegalArgumentException() {
    ApigeeLlm.Builder builder = newParentBuilder();
    builder
        .modelName("apigee/gemini/1/gemini-2.5-flash")
        .proxyUrl("https://apigee.example.com"); // TODO
    // change
    // to
    // target
    // proxy
    // for
    // your
    // environment
    assertThrows(
        (Class<IllegalArgumentException>) IllegalArgumentException.class, () -> builder.build());
  }

  @Test
  @Tag("boundary")
  public void testBuildWithSingleLetterVersionVSucceeds() {
    ApigeeLlm.Builder builder = newParentBuilder();
    builder
        .modelName("apigee/v/gemini-2.5-flash")
        .proxyUrl("https://apigee.example.com") // TODO change to target proxy for
        // your environment
        .customHeaders(Collections.emptyMap());
    ApigeeLlm result = builder.build();
    assertNotNull((Object) result);
  }

  @Test
  @Tag("valid")
  public void testBuildWithValidModelAndNullCustomHeadersSucceeds() {
    ApigeeLlm.Builder builder = newParentBuilder();
    builder
        .modelName("apigee/gemini-2.5-flash")
        .proxyUrl("https://apigee.example.com") // TODO change to target proxy for
        // your environment
        .customHeaders(null);
    ApigeeLlm result = builder.build();
    assertNotNull((Object) result);
  }

  @Test
  @Tag("boundary")
  public void testBuildRepeatedInvocationsReturnDistinctInstances() {
    ApigeeLlm.Builder builder = newParentBuilder();
    builder
        .modelName("apigee/gemini-2.5-flash")
        .proxyUrl("https://apigee.example.com") // TODO change to target proxy for
        // your environment
        .customHeaders(Collections.emptyMap());
    ApigeeLlm first = builder.build();
    ApigeeLlm second = builder.build();
    assertNotNull((Object) first);
    assertNotNull((Object) second);
    assertNotSame((Object) first, (Object) second);
  }

  private ApigeeLlm.Builder newParentBuilder() {
    return new ApigeeLlm.Builder();
  }

  private void setEnvVar(String key, String value) {
    try {
      Map<String, String> newEnv = new HashMap<>();
      newEnv.put(key, value);
      Class<?> processEnvironmentClass = Class.forName("java.lang.ProcessEnvironment");
      Field theEnvironmentField = processEnvironmentClass.getDeclaredField("theEnvironment");
      theEnvironmentField.setAccessible(true);
      @SuppressWarnings("unchecked")
      Map<String, String> env = (Map<String, String>) theEnvironmentField.get(null);
      env.putAll(newEnv);
      Field theCaseInsensitiveEnvironmentField =
          processEnvironmentClass.getDeclaredField("theCaseInsensitiveEnvironment");
      theCaseInsensitiveEnvironmentField.setAccessible(true);
      @SuppressWarnings("unchecked")
      Map<String, String> cienv =
          (Map<String, String>) theCaseInsensitiveEnvironmentField.get(null);
      if (cienv != null) {
        cienv.putAll(newEnv);
      }
    } catch (Throwable t) {
      try {
        Map<String, String> env = System.getenv();
        Class<?> cl = env.getClass();
        Field field = cl.getDeclaredField("m");
        field.setAccessible(true);
        @SuppressWarnings("unchecked")
        Map<String, String> map = (Map<String, String>) field.get(env);
        map.put(key, value);
      } catch (Throwable ignored) {
        // If environment can't be mutated in this runtime, proceed without
        // failing the test.
      }
    }
  }

  private void clearEnvVar(String key) {
    try {
      Class<?> processEnvironmentClass = Class.forName("java.lang.ProcessEnvironment");
      Field theEnvironmentField = processEnvironmentClass.getDeclaredField("theEnvironment");
      theEnvironmentField.setAccessible(true);
      @SuppressWarnings("unchecked")
      Map<String, String> env = (Map<String, String>) theEnvironmentField.get(null);
      env.remove(key);
      Field theCaseInsensitiveEnvironmentField =
          processEnvironmentClass.getDeclaredField("theCaseInsensitiveEnvironment");
      theCaseInsensitiveEnvironmentField.setAccessible(true);
      @SuppressWarnings("unchecked")
      Map<String, String> cienv =
          (Map<String, String>) theCaseInsensitiveEnvironmentField.get(null);
      if (cienv != null) {
        cienv.remove(key);
      }
    } catch (Throwable t) {
      try {
        Map<String, String> env = System.getenv();
        Class<?> cl = env.getClass();
        Field field = cl.getDeclaredField("m");
        field.setAccessible(true);
        @SuppressWarnings("unchecked")
        Map<String, String> map = (Map<String, String>) field.get(env);
        map.remove(key);
      } catch (Throwable ignored) {
        // If environment can't be mutated in this runtime, proceed without
        // failing the test.
      }
    }
  }
}
