/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Azure Open AI and AI Model gpt-5

ROOST_METHOD_HASH=modelName_423c161ca3
ROOST_METHOD_SIG_HASH=modelName_2d01dc01ba


Scenario 1: Setting a valid model string returns the same Builder instance

Details:
  TestName: setsValidModelNameReturnsSameBuilderInstance
  Description: Verifies that calling modelName with a valid Apigee model string stores the value and returns the same Builder instance to support fluent chaining.

Execution:
  Arrange: Create a new builder via ApigeeLlm.builder() and set a valid proxyUrl to avoid environment dependency.
  Act: Call modelName("apigee/gemini-2.5-flash") and capture the returned reference.
  Assert: Use JUnit assertions to verify the returned reference is the exact same instance as the original builder (assertSame). Also verify it is not null (assertNotNull).

Validation:
  Confirms that the method is fluent and returns this as documented. Ensures clients can chain calls without losing the reference or context.

*/

// ********RoostGPT********

package com.google.adk.models;

import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class ApigeeLlmBuilderModelNameTest {

  private ApigeeLlm.Builder builder;

  @BeforeEach
  public void setUp() {
    // Prefer using ApigeeLlm.builder() if available.
    // TODO: If ApigeeLlm.builder() exists, replace with ApigeeLlm.builder()
    builder = new ApigeeLlm.Builder();
  }

  @Test
  @Tag("valid")
  public void testSetsValidModelNameReturnsSameBuilderInstance() {
    String validModelName = "apigee/gemini-2.5-flash";
    String proxyUrl = "https://proxy.example.com"; // TODO: Update proxy URL if
    // required by environment
    ApigeeLlm.Builder returned = builder.modelName(validModelName);
    Assertions.assertSame(
        (Object) builder, (Object) returned, "Expected the same Builder instance to be returned");
    Assertions.assertNotNull((Object) returned, "Returned Builder should not be null");
  }

  @Test
  @Tag("invalid")
  public void testModelNameWithNullReturnsSameBuilderInstance() {
    String proxyUrl = "https://proxy.example.com"; // TODO: Update proxy URL if
    // required by environment
    ApigeeLlm.Builder returned = builder.modelName(null);
    Assertions.assertSame(
        (Object) builder,
        (Object) returned,
        "Expected the same Builder instance to be returned when passing null");
    Assertions.assertNotNull((Object) returned, "Returned Builder should not be null");
  }

  @Test
  @Tag("boundary")
  public void testModelNameWithEmptyStringReturnsSameBuilderInstance() {
    String emptyModelName = "";
    String proxyUrl = "https://proxy.example.com"; // TODO: Update proxy URL if
    // required by environment
    ApigeeLlm.Builder returned = builder.modelName(emptyModelName);
    Assertions.assertSame(
        (Object) builder,
        (Object) returned,
        "Expected the same Builder instance to be returned when passing empty string");
    Assertions.assertNotNull((Object) returned, "Returned Builder should not be null");
  }

  @Test
  @Tag("integration")
  public void testModelNameChainingReturnsSameBuilderInstance() {
    String firstModel = "apigee/gemini-2.5-flash";
    String secondModel = "apigee/gemini-2.5-pro";
    String proxyUrl = "https://proxy.example.com"; // TODO: Update proxy URL if
    // required by environment
    ApigeeLlm.Builder returned = builder.modelName(firstModel).modelName(secondModel);
    Assertions.assertSame(
        (Object) builder,
        (Object) returned,
        "Expected the same Builder instance after chaining modelName calls");
    Assertions.assertNotNull(
        (Object) returned, "Returned Builder should not be null after chaining");
  }

  @Test
  @Tag("boundary")
  public void testModelNameWithLongStringReturnsSameBuilderInstance() {
    // Construct a long model name to simulate boundary condition
    String longModelName = "apigee/" + "gemini-2.5-flash".repeat(50); // TODO: Adjust
    // length if
    // needed
    String proxyUrl = "https://proxy.example.com"; // TODO: Update proxy URL if
    // required by environment
    ApigeeLlm.Builder returned = builder.modelName(longModelName);
    Assertions.assertSame(
        (Object) builder,
        (Object) returned,
        "Expected the same Builder instance to be returned with a long model name");
    Assertions.assertNotNull(
        (Object) returned, "Returned Builder should not be null with a long model name");
  }
}
