/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Azure Open AI and AI Model gpt-5

ROOST_METHOD_HASH=customHeaders_a1e628bbb9
ROOST_METHOD_SIG_HASH=customHeaders_6d66c908fd

Scenario 1: Returning the same Builder instance for fluent chaining

Details:
  TestName: returnsSameBuilderInstanceForFluentChaining
  Description: Verify that calling customHeaders(Map<String, String>) returns the same Builder instance, enabling method chaining.

Execution:
  Arrange: Create an ApigeeLlm.Builder using ApigeeLlm.builder(). Prepare a simple headers map with one non-conflicting entry (e.g., "x-extra": "v1").
  Act: Invoke customHeaders(headers) and capture the returned reference.
  Assert: Use assertSame to confirm the returned reference is the same object as the original Builder.

Validation:
  Confirming the returned instance is identical ensures the method adheres to the fluent Builder contract and allows chaining of subsequent calls without losing state.

*/

// ********RoostGPT********

package com.google.adk.models;

import static com.google.common.base.StandardSystemProperty.JAVA_VERSION;
import static com.google.common.base.Strings.isNullOrEmpty;

import com.google.common.collect.ImmutableMap;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

public class ApigeeLlmBuilderCustomHeadersTest {

  private ApigeeLlm.Builder builder;

  @BeforeEach
  public void setUp() {
    this.builder = ApigeeLlm.builder();
    Assertions.assertNotNull((Object) this.builder);
    String javaVersion = JAVA_VERSION.value();
    Assertions.assertFalse((boolean) isNullOrEmpty(javaVersion));
  }

  @Test
  @Tag("valid")
  public void testReturnsSameBuilderInstanceForFluentChaining() {
    Map<String, String> headers = new HashMap<>();
    headers.put("x-extra", "v1"); // TODO change header values if needed
    ApigeeLlm.Builder returned = this.builder.customHeaders(headers);
    Assertions.assertSame((Object) this.builder, (Object) returned);
  }

  @Test
  @Tag("boundary")
  public void testReturnsSameBuilderInstanceForEmptyHeadersMap() {
    Map<String, String> headers = new HashMap<>();
    ApigeeLlm.Builder returned = this.builder.customHeaders(headers);
    Assertions.assertSame((Object) this.builder, (Object) returned);
  }

  @Test
  @Tag("invalid")
  public void testReturnsSameBuilderInstanceForNullHeaders() {
    Map<String, String> headers = null;
    ApigeeLlm.Builder returned = this.builder.customHeaders(headers);
    Assertions.assertSame((Object) this.builder, (Object) returned);
  }

  @Test
  @Tag("integration")
  public void testChainingMultipleCustomHeadersCallsKeepsSameInstance() {
    Map<String, String> headers1 =
        ImmutableMap.of(
            "x-extra", "v1" // TODO change
            // header values
            // if needed
            );
    Map<String, String> headers2 = new HashMap<>();
    headers2.put("x-feature", "enabled"); // TODO adjust header values based on
    // feature needs
    headers2.put("x-trace", "true"); // TODO adjust header values to match tracing
    // configuration
    ApigeeLlm.Builder returned1 = this.builder.customHeaders(headers1);
    Assertions.assertSame((Object) this.builder, (Object) returned1);
    ApigeeLlm.Builder returned2 = returned1.customHeaders(headers2);
    Assertions.assertSame((Object) this.builder, (Object) returned2);
    // Additional sanity checks to ensure objects are not null during chaining
    Assertions.assertNotNull((Object) returned1);
    Assertions.assertNotNull((Object) returned2);
    Assertions.assertTrue((boolean) Objects.nonNull(returned1));
    Assertions.assertTrue((boolean) Objects.nonNull(returned2));
  }
}
