/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Azure Open AI and AI Model gpt-5

ROOST_METHOD_HASH=proxyUrl_3e147df46b
ROOST_METHOD_SIG_HASH=proxyUrl_611a9955d6

Scenario 1: Returns the same Builder instance when a non-null proxy URL is set

Details:
  TestName: returnsSameBuilderWhenNonNullUrlPassed
  Description: Verify that calling proxyUrl with a non-null string sets the internal field and returns the same Builder instance to support fluent chaining.

Execution:
  Arrange: Create a new ApigeeLlm.Builder via ApigeeLlm.builder() and prepare a valid model name such as "apigee/gemini-2.5-flash".
  Act: Call proxyUrl("https://apigee.example.com") and capture the returned object; then chain modelName("apigee/gemini-2.5-flash") and call build().
  Assert: Use assertSame on the original builder and the returned reference from proxyUrl. Use assertDoesNotThrow for the build() call.

Validation:
  Confirm that proxyUrl returns the same builder instance to enable fluent API usage, and that providing a non-null URL allows the object to be built without error. This ensures method chainability and correct state application.

*/

// ********RoostGPT********

package com.google.adk.models;

import static com.google.common.base.StandardSystemProperty.JAVA_VERSION;
import static com.google.common.base.Strings.isNullOrEmpty;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

public class ApigeeLlmBuilderProxyUrlTest {

  private ApigeeLlm.Builder builder;

  @BeforeEach
  public void setUp() {
    builder = ApigeeLlm.builder();
    assertNotNull((Object) builder);
  }

  @Test
  @Tag("valid")
  public void testReturnsSameBuilderWhenNonNullUrlPassed() {
    String validModel = "apigee/gemini-2.5-flash"; // TODO change model name if
    // required
    assertTrue((boolean) (!isNullOrEmpty(validModel)));
    String url = "https://apigee.example.com";
    ApigeeLlm.Builder returned = builder.proxyUrl(url);
    assertSame((Object) builder, (Object) returned);
    assertDoesNotThrow(() -> returned.modelName(validModel).build());
    String javaVersion = JAVA_VERSION.value();
    assertTrue((boolean) (!isNullOrEmpty(javaVersion)));
    assertTrue((boolean) (javaVersion.length() > 0 && javaVersion.length() <= 100));
  }

  @Test
  @Tag("boundary")
  public void testReturnsSameBuilderWhenNullUrlPassed() {
    String validModel = "apigee/gemini-2.5-flash"; // TODO change model name if
    // required
    assertTrue((boolean) (!isNullOrEmpty(validModel)));
    ApigeeLlm.Builder returned = builder.proxyUrl(null);
    assertSame((Object) builder, (Object) returned);
    assertDoesNotThrow(() -> returned.modelName(validModel).build());
  }

  @Test
  @Tag("boundary")
  public void testReturnsSameBuilderWhenEmptyUrlPassed() {
    String validModel = "apigee/gemini-2.5-flash"; // TODO change model name if
    // required
    assertTrue((boolean) (!isNullOrEmpty(validModel)));
    ApigeeLlm.Builder returned = builder.proxyUrl("");
    assertSame((Object) builder, (Object) returned);
    assertDoesNotThrow(() -> returned.modelName(validModel).build());
  }

  @Test
  @Tag("boundary")
  public void testReturnsSameBuilderWhenWhitespaceUrlPassed() {
    String validModel = "apigee/gemini-2.5-flash"; // TODO change model name if
    // required
    assertTrue((boolean) (!isNullOrEmpty(validModel)));
    ApigeeLlm.Builder returned = builder.proxyUrl("   ");
    assertSame((Object) builder, (Object) returned);
    assertDoesNotThrow(() -> returned.modelName(validModel).build());
  }

  @Test
  @Tag("boundary")
  public void testReturnsSameBuilderAcrossMultipleProxyUrlCalls() {
    String validModel = "apigee/gemini-2.5-flash"; // TODO change model name if
    // required
    assertTrue((boolean) (!isNullOrEmpty(validModel)));
    ApigeeLlm.Builder b1 = builder.proxyUrl("https://proxy1.example.com");
    ApigeeLlm.Builder b2 = b1.proxyUrl("https://proxy2.example.com");
    ApigeeLlm.Builder b3 = b2.proxyUrl(null);
    assertSame((Object) builder, (Object) b1);
    assertSame((Object) builder, (Object) b2);
    assertSame((Object) builder, (Object) b3);
    assertDoesNotThrow(() -> b3.modelName(validModel).build());
  }
}
