/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Open AI and AI Model gpt-5-nano

ROOST_METHOD_HASH=apiClient_c66ebe1d58
ROOST_METHOD_SIG_HASH=apiClient_d59e3a5ed5

Scenario 1: apiClient_setsExplicitClient

Details:
  TestName: apiClient_setsExplicitClient
  Description: Verify that calling apiClient with a non-null Client assigns the provided client to the builder and returns the same builder instance to support chaining.

Execution:
  Arrange: Create a Gemini.Builder via Gemini.builder(); prepare a mock/stub Client instance named mockClient.
  Act: Builder resultBuilder = builder.apiClient(mockClient);
  Assert: Assert that resultBuilder is the same object instance as the original builder (reference equality); optionally verify that the builder can continue chaining by calling another method and ensuring no exception is thrown.
  Validation: Ensures that the explicit client is stored in the builder and that the fluent API contract (returning this) is preserved, enabling method chaining.


*/

// ********RoostGPT********

package com.google.adk.models;

import static org.junit.jupiter.api.Assertions.*;

import com.google.genai.Client;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

public class BuilderApiClientTest {

	@Test
	@Tag("valid")
	@DisplayName("apiClient_setsExplicitClient")
	public void testApiClient_setsExplicitClient() {
		Gemini.Builder builder = Gemini.builder();
		Client mockClient = Mockito.mock(Client.class);
		Gemini.Builder resultBuilder = builder.apiClient(mockClient);
		assertSame(builder, resultBuilder);
		// Continue chaining to ensure fluent API contract
		Gemini.Builder chained = resultBuilder.modelName("test-model");
		Gemini gemini = chained.build();
		assertNotNull(gemini);
	}

	@Test
	@Tag("valid")
	@DisplayName("apiClient_acceptsNullAndReturnsThisForChaining")
	public void testApiClient_acceptsNullAndReturnsThisForChaining() {
		Gemini.Builder builder = Gemini.builder();
		Gemini.Builder result = builder.apiClient(null);
		assertSame(builder, result);
	}

}
