/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Open AI and AI Model gpt-5-nano

ROOST_METHOD_HASH=apiClient_c66ebe1d58
ROOST_METHOD_SIG_HASH=apiClient_d59e3a5ed5

Scenario 1: apiClient_setsExplicitClient

Details:
  TestName: apiClient_setsExplicitClient
  Description: Verify that calling apiClient with a non-null Client assigns the provided client to the builder and returns the same builder instance to support chaining.

Execution:
  Arrange: Create a Gemini.Builder via Gemini.builder(); prepare a mock/stub Client instance named mockClient.
  Act: Builder resultBuilder = builder.apiClient(mockClient);
  Assert: Assert that resultBuilder is the same object instance as the original builder (reference equality); optionally verify that the builder can continue chaining by calling another method and ensuring no exception is thrown.
  Validation: Ensures that the explicit client is stored in the builder and that the fluent API contract (returning this) is preserved, enabling method chaining.


*/

// ********RoostGPT********

package com.google.adk.models;

import static org.junit.jupiter.api.Assertions.assertSame;
import static org.mockito.Mockito.mock;

import com.google.genai.Client;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

/** Test suite for Gemini.Builder.apiClient(Client apiClient) */
public class BuilderApiClientTest {

  @Test
  @Tag("valid")
  public void testApiClientSetsExplicitClient() {
    Gemini.Builder builder = Gemini.builder();
    Client mockClient = mock(Client.class);
    Gemini.Builder resultBuilder = builder.apiClient(mockClient);
    // Ensure fluent API returns the same builder instance (enables chaining)
    assertSame(builder, resultBuilder);
    // Ensure chaining remains functional by calling another method on the same
    // builder
    Gemini.Builder chained = resultBuilder.modelName("test-model"); // TODO: adjust
    // modelName as
    // needed
    assertSame(builder, chained);
  }

  @Test
  @Tag("boundary")
  public void testApiClientAcceptsNullClient() {
    Gemini.Builder builder = Gemini.builder();
    Gemini.Builder resultBuilder = builder.apiClient(null);
    // Even with null input, the fluent API should return the same builder instance
    assertSame(builder, resultBuilder);
    // Chaining should continue to work with a null client
    Gemini.Builder chained = resultBuilder.modelName("test-model-null"); // TODO:
    // adjust
    // modelName
    // as
    // needed
    assertSame(builder, chained);
  }
}
