/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Open AI and AI Model gpt-5-nano

ROOST_METHOD_HASH=vertexCredentials_05534933e8
ROOST_METHOD_SIG_HASH=vertexCredentials_ad6dd8135d

Scenario 1: vertexCredentialsWithNonNullSetsFieldAndAllowsChaining

Details:
  TestName: vertexCredentialsWithNonNullSetsFieldAndAllowsChaining
  Description: Verifies that calling vertexCredentials with a non-null VertexCredentials on the Builder stores the value in the builder and returns the same Builder instance to enable fluent chaining. It also implies that when the builder later constructs a Gemini, the VertexCredentials path will be used if no higher-precedence option is set.

Execution:
  Arrange: Create a non-null VertexCredentials instance (vc). Obtain a Gemini.Builder via Gemini.builder().
  Act: Call builder.vertexCredentials(vc) and capture the returned value.
  Assert: The returned value should be the exact same Builder instance (identity equality).

Validation:
  The test confirms the fluent API contract of vertexCredentials, ensuring that the method mutates the builder state correctly and supports chaining. This aligns with the implementation which returns this after assignment. If subsequent build() is invoked with modelName set and no higher-precedence fields, the Gemini should be constructed using the provided VertexCredentials.

Scenario 2: vertexCredentialsWithNullDoesNotThrowAndIgnoresInput

Details:
  TestName: vertexCredentialsWithNullDoesNotThrowAndIgnoresInput
  Description: Ensures that passing null to vertexCredentials does not throw and simply leaves the internal vertexCredentials field as null, allowing the builder to continue with other configuration paths.

Execution:
  Arrange: Create a VertexCredentials reference vc = null. Obtain a Gemini.Builder via Gemini.builder() and set a modelName later.
  Act: Call builder.vertexCredentials(vc) and capture the returned value.
  Assert: The returned value should be the same Builder instance.

Validation:
  This confirms that a null input does not cause an exception and that subsequent build() will follow the next-available precedence rule (likely using a default client path if no other credentials are provided).

Scenario 3: vertexCredentialsIgnoredWhenApiClientPresent

Details:
  TestName: vertexCredentialsIgnoredWhenApiClientPresent
  Description: Validates that if an explicit apiClient is already set on the Builder, invoking vertexCredentials does not override the intended path; the build() should use the explicit apiClient path.

Execution:
  Arrange: Create a mock Client instance (mockApiClient). Obtain a Gemini.Builder; set apiClient(mockApiClient); create a VertexCredentials vc and call vertexCredentials(vc) afterward.
  Act: Build the Gemini via builder.build().
  Assert: The resulting Gemini should be constructed using the explicit apiClient path rather than VertexCredentials.

Validation:
  The test ensures the precedence rule in the build() method: apiClient takes priority over vertexCredentials when both are present.

Scenario 4: vertexCredentialsIgnoredWhenApiKeyPresent

Details:
  TestName: vertexCredentialsIgnoredWhenApiKeyPresent
  Description: Confirms that when an apiKey is set on the Builder (and apiClient is not set), but vertexCredentials is also provided, the build() should prefer the apiKey path over VertexCredentials.

Execution:
  Arrange: Obtain a Gemini.Builder; set apiKey("sample-key"); call vertexCredentials with a non-null VertexCredentials vc.
  Act: Build the Gemini via builder.build().
  Assert: The resulting Gemini should be constructed using the apiKey path (Gemini(modelName, apiKey)) rather than VertexCredentials.

Validation:
  Verifies the precedence order in the build logic: apiKey overrides vertexCredentials when apiClient is not present.

Scenario 5: vertexCredentialsLastValueWinsWithMultipleCalls

Details:
  TestName: vertexCredentialsLastValueWinsWithMultipleCalls
  Description: Checks that successive calls to vertexCredentials overwrite the previously stored value, and the final value is the one used when building the Gemini.

Execution:
  Arrange: Create vc1 and vc2 as VertexCredentials instances. Obtain a Gemini.Builder.
  Act: Call builder.vertexCredentials(vc1); then builder.vertexCredentials(vc2); then build().
  Assert: If a path using VertexCredentials is chosen (no apiClient/apiKey set), the Gemini should reflect vc2 as the last provided credentials (in behavior terms).

Validation:
  Ensures that the builder state reflects the most recent vertexCredentials call, consistent with typical fluent API semantics.

Scenario 6: vertexCredentialsWithoutModelNameThrowsNullPointerException

Details:
  TestName: vertexCredentialsWithoutModelNameThrowsNullPointerException
  Description: Validates that calling build() without setting a modelName results in a NullPointerException, confirming the required modelName precondition even when vertexCredentials has been supplied.

Execution:
  Arrange: Obtain a Gemini.Builder; do not call modelName; call vertexCredentials with a non-null VertexCredentials vc.
  Act: Call build() and observe the exception.
  Assert: A NullPointerException is thrown with the message indicating modelName must be set.

Validation:
  Verifies enforcement of the precondition in build() for modelName, ensuring that a valid model name is always required for Gemini construction.

Scenario 7: vertexCredentialsUsedWhenOnlyVertexCredentialsAndModelNameSet

Details:
  TestName: vertexCredentialsUsedWhenOnlyVertexCredentialsAndModelNameSet
  Description: Ensures that when only a VertexCredentials instance and a modelName are provided (no apiClient/apiKey), the build() path uses VertexCredentials to create the Gemini instance.

Execution:
  Arrange: Create vc, obtain a Builder, set modelName("gemini-model"), call vertexCredentials(vc).
  Act: Build the Gemini.
  Assert: The Gemini is constructed via the VertexCredentials path (Gemini(modelName, vertexCredentials)).

Validation:
  Confirms the intended path is taken when VertexCredentials is the only credential source provided besides the required modelName.

Scenario 8: vertexCredentialsOverridesPreviousConsiderationsWhenNoOtherCredentialsArePresent

Details:
  TestName: vertexCredentialsOverridesPreviousConsiderationsWhenNoOtherCredentialsArePresent
  Description: Verifies that after previously configuring apiClient or apiKey, calling vertexCredentials does not retroactively change the chosen path unless those higher-priority fields are cleared; specifically, in the absence of apiClient/apiKey, vertexCredentials should be used.

Execution:
  Arrange: Start with a builder that has modelName set and apiClient/apiKey are null. Call vertexCredentials(vc) with a non-null VertexCredentials.
  Act: Build the Gemini.
  Assert: The VertexCredentials path is used in Gemini construction.

Validation:
  Ensures correct behavior when transitioning from no credentials to VertexCredentials as the sole credential source.


*/

// ********RoostGPT********

package com.google.adk.models;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.mock;

import com.google.genai.Client;
import java.lang.reflect.Field;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

public class BuilderVertexCredentialsTest {

  // Helper to inspect which credential source was used inside Gemini
  private Object getUsedCredentialSource(Gemini gem) {
    Class<?> cls = gem.getClass();
    for (String fieldName : new String[] {"apiClient", "apiKey", "vertexCredentials"}) {
      try {
        Field f = cls.getDeclaredField(fieldName);
        f.setAccessible(true);
        Object value = f.get(gem);
        if (value != null) {
          return value;
        }
      } catch (NoSuchFieldException | IllegalAccessException e) {
        // Ignore and try next
      }
    }
    return null;
  }

  @Test
  @Tag("valid")
  @DisplayName("vertexCredentialsWithNonNullSetsFieldAndAllowsChaining")
  public void vertexCredentialsWithNonNullSetsFieldAndAllowsChaining() throws Exception {
    VertexCredentials vc = VertexCredentials.builder().build();
    Gemini.Builder builder = Gemini.builder();
    Gemini.Builder returned = builder.vertexCredentials(vc);
    // Fluent API contract: same instance returned for chaining
    assertSame(builder, returned);
    // Prepare to build and verify that VertexCredentials path is used
    builder.modelName("gemini-model");
    Gemini gem = builder.build();
    Object used = getUsedCredentialSource(gem);
    assertSame(vc, used, "Expected VertexCredentials to be the credential source used.");
  }

  @Test
  @Tag("boundary")
  @DisplayName("vertexCredentialsWithNullDoesNotThrowAndIgnoresInput")
  public void vertexCredentialsWithNullDoesNotThrowAndIgnoresInput() {
    Gemini.Builder builder = Gemini.builder();
    Gemini.Builder returned = builder.vertexCredentials(null);
    // Fluent API contract: same instance returned for chaining even with null
    assertSame(builder, returned);
  }

  @Test
  @Tag("integration")
  @DisplayName("vertexCredentialsIgnoredWhenApiClientPresent")
  public void vertexCredentialsIgnoredWhenApiClientPresent() throws Exception {
    Client mockApiClient = mock(Client.class);
    VertexCredentials vc = VertexCredentials.builder().build();
    Gemini.Builder builder = Gemini.builder();
    builder.apiClient(mockApiClient);
    builder.vertexCredentials(vc);
    builder.modelName("gemini-model");
    Gemini gem = builder.build();
    Object used = getUsedCredentialSource(gem);
    assertSame(
        mockApiClient, used, "Expected API client to take precedence over VertexCredentials.");
  }

  @Test
  @Tag("integration")
  @DisplayName("vertexCredentialsIgnoredWhenApiKeyPresent")
  public void vertexCredentialsIgnoredWhenApiKeyPresent() throws Exception {
    VertexCredentials vc = VertexCredentials.builder().build();
    Gemini.Builder builder = Gemini.builder();
    builder.apiKey("sample-key");
    builder.vertexCredentials(vc);
    builder.modelName("gemini-model");
    Gemini gem = builder.build();
    // When apiKey is present, it should be the credential source used
    Object used = getUsedCredentialSource(gem);
    assertNotNull(used, "Expected some credential source to be used.");
    assert (used instanceof String) : "Expected apiKey to be a String.";
    assert "sample-key".equals(used) : "Expected apiKey value to be used.";
  }

  @Test
  @Tag("valid")
  @DisplayName("vertexCredentialsLastValueWinsWithMultipleCalls")
  public void vertexCredentialsLastValueWinsWithMultipleCalls() throws Exception {
    VertexCredentials vc1 = VertexCredentials.builder().build();
    VertexCredentials vc2 = VertexCredentials.builder().build();
    Gemini.Builder builder = Gemini.builder();
    builder.vertexCredentials(vc1);
    builder.vertexCredentials(vc2);
    builder.modelName("gemini-model");
    Gemini gem = builder.build();
    Object used = getUsedCredentialSource(gem);
    assertSame(
        vc2,
        used,
        "The last provided VertexCredentials should be used when no higher-priority credentials are present.");
  }

  @Test
  @Tag("invalid")
  @DisplayName("vertexCredentialsWithoutModelNameThrowsNullPointerException")
  public void vertexCredentialsWithoutModelNameThrowsNullPointerException() {
    VertexCredentials vc = VertexCredentials.builder().build();
    Gemini.Builder builder = Gemini.builder();
    builder.vertexCredentials(vc);
    NullPointerException ex = assertThrows(NullPointerException.class, () -> builder.build());
    // Ensure that the NPE message indicates the required modelName
    String msg = ex.getMessage();
    assertNotNull(msg);
    assert msg.contains("modelName") : "Expected message to mention modelName.";
  }

  @Test
  @Tag("valid")
  @DisplayName("vertexCredentialsUsedWhenOnlyVertexCredentialsAndModelNameSet")
  public void vertexCredentialsUsedWhenOnlyVertexCredentialsAndModelNameSet() throws Exception {
    VertexCredentials vc = VertexCredentials.builder().build();
    Gemini.Builder builder = Gemini.builder();
    builder.modelName("gemini-model");
    builder.vertexCredentials(vc);
    Gemini gem = builder.build();
    Object used = getUsedCredentialSource(gem);
    assertSame(
        vc,
        used,
        "Expected VertexCredentials path to be used when only VertexCredentials and modelName are set.");
  }

  @Test
  @Tag("valid")
  @DisplayName("vertexCredentialsOverridesPreviousConsiderationsWhenNoOtherCredentialsArePresent")
  public void vertexCredentialsOverridesPreviousConsiderationsWhenNoOtherCredentialsArePresent()
      throws Exception {
    VertexCredentials vc = VertexCredentials.builder().build();
    Gemini.Builder builder = Gemini.builder();
    builder.modelName("gemini-model");
    // No apiClient/apiKey set; VertexCredentials should be used
    builder.vertexCredentials(vc);
    Gemini gem = builder.build();
    Object used = getUsedCredentialSource(gem);
    assertSame(
        vc,
        used,
        "Expected VertexCredentials to be used when no other credentials are configured.");
  }
}
