/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Open AI and AI Model gpt-5-nano

ROOST_METHOD_HASH=build_a5a48bce54
ROOST_METHOD_SIG_HASH=build_6248639c03

Scenario 1: Build with explicit apiClient returns Gemini using that client
Details:
  TestName: buildWithApiClient
  Description: When apiClient is provided to the Builder along with a non-null modelName, the build() method should instantiate Gemini using that exact apiClient, ignoring apiKey and vertexCredentials.
Execution:
  Arrange: Create a Builder, set modelName to "gemini-2.0", create a mock Client instance named apiClientMock, and call builder.apiClient(apiClientMock).
  Act: Call builder.build().
  Assert: The returned object is an instance of Gemini, and via reflection verify that the internal apiClient reference equals apiClientMock; verify the modelName used is "gemini-2.0".
Validation:
  Clarify that the test confirms explicit apiClient takes precedence over other credential options and that the Gemini is wired to use the provided client.

*/

// ********RoostGPT********

package com.google.adk.models;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import com.google.genai.Client;
import java.lang.reflect.Field;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.*;
import static com.google.common.base.StandardSystemProperty.JAVA_VERSION;
import com.google.adk.Version;
import com.google.common.collect.ImmutableMap;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import com.google.genai.ResponseStream;
import com.google.genai.types.Candidate;
import com.google.genai.types.Content;
import com.google.genai.types.FinishReason;
import com.google.genai.types.GenerateContentConfig;
import com.google.genai.types.GenerateContentResponse;
import com.google.genai.types.HttpOptions;
import com.google.genai.types.LiveConnectConfig;
import com.google.genai.types.Part;
import io.reactivex.rxjava3.core.Flowable;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class BuilderBuildTest {

	@Test
	@Tag("valid")
	public void buildWithApiClient() throws Exception {
		Client apiClientMock = mock(Client.class);
		Gemini gemini = Gemini.builder().modelName("gemini-2.0").apiClient(apiClientMock).build();
		assertEquals("gemini-2.0", gemini.model());
		Field f = Gemini.class.getDeclaredField("apiClient");
		f.setAccessible(true);
		Object value = f.get(gemini);
		assertSame(apiClientMock, value);
	}

	@Test
	@Tag("valid")
	public void buildWithApiKey() throws Exception {
		String apiKey = "test-key";
		Gemini gemini = Gemini.builder().modelName("gemini-2.0").apiKey(apiKey).build();
		assertEquals("gemini-2.0", gemini.model());
		Field f = Gemini.class.getDeclaredField("apiKey");
		f.setAccessible(true);
		Object value = f.get(gemini);
		assertEquals(apiKey, (String) value);
	}

	@Test
	@Tag("valid")
	public void buildWithVertexCredentials() throws Exception {
		VertexCredentials vc = VertexCredentials.builder().build();
		Gemini gemini = Gemini.builder().modelName("gemini-2.0").vertexCredentials(vc).build();
		assertEquals("gemini-2.0", gemini.model());
		Field f = Gemini.class.getDeclaredField("vertexCredentials");
		f.setAccessible(true);
		Object value = f.get(gemini);
		assertSame(vc, value);
	}

	@Test
	@Tag("integration")
	public void buildWithDefaultClient() throws Exception {
		Gemini gemini = Gemini.builder().modelName("gemini-2.0").build();
		assertEquals("gemini-2.0", gemini.model());
		Field f = Gemini.class.getDeclaredField("apiClient");
		f.setAccessible(true);
		Object value = f.get(gemini);
		assertNotNull(value);
		assertTrue(value instanceof Client);
	}

	@Test
	@Tag("invalid")
	public void buildWithNullModelNameThrows() {
		assertThrows(NullPointerException.class, () -> Gemini.builder().modelName(null).build());
	}

}