/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Open AI and AI Model gpt-5-nano

ROOST_METHOD_HASH=build_a5a48bce54
ROOST_METHOD_SIG_HASH=build_6248639c03

Scenario 1: Build with explicit apiClient returns Gemini using that client
Details:
  TestName: buildWithApiClient
  Description: When apiClient is provided to the Builder along with a non-null modelName, the build() method should instantiate Gemini using that exact apiClient, ignoring apiKey and vertexCredentials.
Execution:
  Arrange: Create a Builder, set modelName to "gemini-2.0", create a mock Client instance named apiClientMock, and call builder.apiClient(apiClientMock).
  Act: Call builder.build().
  Assert: The returned object is an instance of Gemini, and via reflection verify that the internal apiClient reference equals apiClientMock; verify the modelName used is "gemini-2.0".
Validation:
  Clarify that the test confirms explicit apiClient takes precedence over other credential options and that the Gemini is wired to use the provided client.

*/

// ********RoostGPT********

package com.google.adk.models;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.genai.Client;
import java.lang.reflect.Field;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class BuilderBuildTest {

  @Test
  @Tag("valid")
  @DisplayName("buildWithApiClient: Build with explicit apiClient returns Gemini using that client")
  public void testBuildWithApiClient() throws Exception {
    // Arrange
    Gemini.Builder builder = Gemini.builder();
    String modelName = "gemini-2.0"; // TODO: adjust if needed for different test
    // environments
    Client apiClientMock = mock(Client.class);
    // Act
    Gemini gemini = builder.modelName(modelName).apiClient(apiClientMock).build();
    // Assert
    assertNotNull(gemini, "Gemini instance should not be null");
    // Use reflection to verify internal fields
    Field modelField = Gemini.class.getDeclaredField("modelName");
    modelField.setAccessible(true);
    Object actualModelName = modelField.get(gemini);
    assertEquals(modelName, actualModelName, "modelName should be set to the provided value");
    Field apiClientField = Gemini.class.getDeclaredField("apiClient");
    apiClientField.setAccessible(true);
    Object actualApiClient = apiClientField.get(gemini);
    assertEquals(apiClientMock, actualApiClient, "apiClient should be the same as provided");
  }

  @Test
  @Tag("valid")
  @DisplayName("buildWithApiKey: Build with explicit apiKey")
  public void testBuildWithApiKey() throws Exception {
    // Arrange
    Gemini.Builder builder = Gemini.builder();
    String modelName = "gemini-2.0"; // TODO: adjust if needed
    String apiKey = "test-api-key";
    // Act
    Gemini gemini = builder.modelName(modelName).apiKey(apiKey).build();
    // Assert
    Field modelField = Gemini.class.getDeclaredField("modelName");
    modelField.setAccessible(true);
    Object actualModelName = modelField.get(gemini);
    assertEquals(modelName, actualModelName, "modelName should be set to the provided value");
    Field apiKeyField = Gemini.class.getDeclaredField("apiKey");
    apiKeyField.setAccessible(true);
    Object actualApiKey = apiKeyField.get(gemini);
    assertEquals(apiKey, actualApiKey, "apiKey should be the same as provided");
  }

  @Test
  @Tag("valid")
  @DisplayName("buildWithVertexCredentials: Build with vertexCredentials")
  public void testBuildWithVertexCredentials() throws Exception {
    // Arrange
    Gemini.Builder builder = Gemini.builder();
    String modelName = "gemini-2.0"; // TODO: adjust if needed
    VertexCredentials vertexCredentials = VertexCredentials.builder().build();
    // Act
    Gemini gemini = builder.modelName(modelName).vertexCredentials(vertexCredentials).build();
    // Assert
    Field modelField = Gemini.class.getDeclaredField("modelName");
    modelField.setAccessible(true);
    Object actualModelName = modelField.get(gemini);
    assertEquals(modelName, actualModelName, "modelName should be set to the provided value");
    Field vcField = Gemini.class.getDeclaredField("vertexCredentials");
    vcField.setAccessible(true);
    Object actualVertexCreds = vcField.get(gemini);
    assertEquals(
        vertexCredentials, actualVertexCreds, "vertexCredentials should be the same as provided");
  }

  @Test
  @Tag("boundary")
  @DisplayName("buildWithNoCredentials: Build with no credentials uses default Client")
  public void testBuildWithNoCredentials() throws Exception {
    // Arrange
    Gemini.Builder builder = Gemini.builder();
    String modelName = "gemini-2.0"; // TODO: adjust if needed
    // Act
    Gemini gemini = builder.modelName(modelName).build();
    // Assert
    Field modelField = Gemini.class.getDeclaredField("modelName");
    modelField.setAccessible(true);
    Object actualModelName = modelField.get(gemini);
    assertEquals(modelName, actualModelName, "modelName should be set to the provided value");
    Field apiClientField = Gemini.class.getDeclaredField("apiClient");
    apiClientField.setAccessible(true);
    Object actualApiClient = apiClientField.get(gemini);
    assertNotNull(
        actualApiClient,
        "apiClient should be initialized by default when no credentials are provided");
    assertTrue(actualApiClient instanceof Client, "apiClient should be an instance of Client");
  }

  @Test
  @Tag("invalid")
  @DisplayName("buildWithNullModelNameThrows: Null modelName should throw NullPointerException")
  public void testBuildWithNullModelNameThrows() {
    // Arrange
    Gemini.Builder builder = Gemini.builder();
    // Act & Assert
    assertThrows(
        NullPointerException.class,
        () -> builder.build(),
        "Expected NPE when modelName is not set");
  }
}
