/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Open AI and AI Model gpt-5-nano

ROOST_METHOD_HASH=apiKey_6f7fe65f1f
ROOST_METHOD_SIG_HASH=apiKey_f645a7d0cc

Scenario 1: Setting non-null apiKey stores the value and enables fluent chaining on the Builder
Details:
  TestName: settingApiKeyStoresValue
  Description: Verify that calling apiKey with a non-null string assigns that value to the builder's apiKey field and returns the same Builder instance to support method chaining.
Execution:
  Arrange: Instantiate a new Gemini.Builder via Gemini.builder().
  Act: Call builder.apiKey("my-api-key") and capture the returned reference.
  Assert: The returned reference is the same instance as the original builder (identity check) to confirm fluent chaining is preserved.
Validation:
  The assertion confirms fluent API usage for the Builder.apiKey method, ensuring subsequent builder methods can be chained without losing the current state.

*/

// ********RoostGPT********

package com.google.adk.models;

import static org.junit.jupiter.api.Assertions.*;

import java.lang.reflect.Field;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

public class BuilderApiKeyTest {

	@Test
	@Tag("valid")
	public void settingApiKeyStoresValue() throws Exception {
		// Arrange
		Gemini.Builder builder = Gemini.builder();
		String testApiKey = java.util.UUID.randomUUID().toString();
		// Act
		Gemini.Builder returned = builder.apiKey(testApiKey); // TODO: Replace with a
																// known key if using
																// integration tests
		// Assert fluent chaining
		assertSame(builder, returned, "apiKey should return the same builder instance for fluent chaining.");
		// Assert that the value is stored in the builder (private field access via
		// reflection)
		Field field = Gemini.Builder.class.getDeclaredField("apiKey");
		field.setAccessible(true);
		String value = (String) field.get(builder);
		assertEquals(testApiKey, value, "The apiKey value stored in the builder should match the input value.");
	}

	@Test
	@Tag("valid")
	public void settingApiKeyWithNullValue() throws Exception {
		// Arrange
		Gemini.Builder builder = Gemini.builder();
		// Act
		Gemini.Builder returned = builder.apiKey(null);
		// Assert fluent chaining
		assertSame(builder, returned, "apiKey(null) should return the same builder instance for fluent chaining.");
		// Assert that the value stored is null
		Field field = Gemini.Builder.class.getDeclaredField("apiKey");
		field.setAccessible(true);
		String value = (String) field.get(builder);
		assertNull(value, "The apiKey value should be null when null is passed.");
	}

}
