/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Open AI and AI Model gpt-5-nano

ROOST_METHOD_HASH=vertexCredentials_05534933e8
ROOST_METHOD_SIG_HASH=vertexCredentials_ad6dd8135d

Scenario 1: vertexCredentialsWithNonNullSetsFieldAndAllowsChaining

Details:
  TestName: vertexCredentialsWithNonNullSetsFieldAndAllowsChaining
  Description: Verifies that calling vertexCredentials with a non-null VertexCredentials on the Builder stores the value in the builder and returns the same Builder instance to enable fluent chaining. It also implies that when the builder later constructs a Gemini, the VertexCredentials path will be used if no higher-precedence option is set.

Execution:
  Arrange: Create a non-null VertexCredentials instance (vc). Obtain a Gemini.Builder via Gemini.builder().
  Act: Call builder.vertexCredentials(vc) and capture the returned value.
  Assert: The returned value should be the exact same Builder instance (identity equality).

Validation:
  The test confirms the fluent API contract of vertexCredentials, ensuring that the method mutates the builder state correctly and supports chaining. This aligns with the implementation which returns this after assignment. If subsequent build() is invoked with modelName set and no higher-precedence fields, the Gemini should be constructed using the provided VertexCredentials.

Scenario 2: vertexCredentialsWithNullDoesNotThrowAndIgnoresInput

Details:
  TestName: vertexCredentialsWithNullDoesNotThrowAndIgnoresInput
  Description: Ensures that passing null to vertexCredentials does not throw and simply leaves the internal vertexCredentials field as null, allowing the builder to continue with other configuration paths.

Execution:
  Arrange: Create a VertexCredentials reference vc = null. Obtain a Gemini.Builder via Gemini.builder() and set a modelName later.
  Act: Call builder.vertexCredentials(vc) and capture the returned value.
  Assert: The returned value should be the same Builder instance.

Validation:
  This confirms that a null input does not cause an exception and that subsequent build() will follow the next-available precedence rule (likely using a default client path if no other credentials are provided).

Scenario 3: vertexCredentialsIgnoredWhenApiClientPresent

Details:
  TestName: vertexCredentialsIgnoredWhenApiClientPresent
  Description: Validates that if an explicit apiClient is already set on the Builder, invoking vertexCredentials does not override the intended path; the build() should use the explicit apiClient path.

Execution:
  Arrange: Create a mock Client instance (mockApiClient). Obtain a Gemini.Builder; set apiClient(mockApiClient); create a VertexCredentials vc and call vertexCredentials(vc) afterward.
  Act: Build the Gemini via builder.build().
  Assert: The resulting Gemini should be constructed using the explicit apiClient path rather than VertexCredentials.

Validation:
  The test ensures the precedence rule in the build() method: apiClient takes priority over vertexCredentials when both are present.

Scenario 4: vertexCredentialsIgnoredWhenApiKeyPresent

Details:
  TestName: vertexCredentialsIgnoredWhenApiKeyPresent
  Description: Confirms that when an apiKey is set on the Builder (and apiClient is not set), but vertexCredentials is also provided, the build() should prefer the apiKey path over VertexCredentials.

Execution:
  Arrange: Obtain a Gemini.Builder; set apiKey("sample-key"); call vertexCredentials with a non-null VertexCredentials vc.
  Act: Build the Gemini via builder.build().
  Assert: The resulting Gemini should be constructed using the apiKey path (Gemini(modelName, apiKey)) rather than VertexCredentials.

Validation:
  Verifies the precedence order in the build logic: apiKey overrides vertexCredentials when apiClient is not present.

Scenario 5: vertexCredentialsLastValueWinsWithMultipleCalls

Details:
  TestName: vertexCredentialsLastValueWinsWithMultipleCalls
  Description: Checks that successive calls to vertexCredentials overwrite the previously stored value, and the final value is the one used when building the Gemini.

Execution:
  Arrange: Create vc1 and vc2 as VertexCredentials instances. Obtain a Gemini.Builder.
  Act: Call builder.vertexCredentials(vc1); then builder.vertexCredentials(vc2); then build().
  Assert: If a path using VertexCredentials is chosen (no apiClient/apiKey set), the Gemini should reflect vc2 as the last provided credentials (in behavior terms).

Validation:
  Ensures that the builder state reflects the most recent vertexCredentials call, consistent with typical fluent API semantics.

Scenario 6: vertexCredentialsWithoutModelNameThrowsNullPointerException

Details:
  TestName: vertexCredentialsWithoutModelNameThrowsNullPointerException
  Description: Validates that calling build() without setting a modelName results in a NullPointerException, confirming the required modelName precondition even when vertexCredentials has been supplied.

Execution:
  Arrange: Obtain a Gemini.Builder; do not call modelName; call vertexCredentials with a non-null VertexCredentials vc.
  Act: Call build() and observe the exception.
  Assert: A NullPointerException is thrown with the message indicating modelName must be set.

Validation:
  Verifies enforcement of the precondition in build() for modelName, ensuring that a valid model name is always required for Gemini construction.

Scenario 7: vertexCredentialsUsedWhenOnlyVertexCredentialsAndModelNameSet

Details:
  TestName: vertexCredentialsUsedWhenOnlyVertexCredentialsAndModelNameSet
  Description: Ensures that when only a VertexCredentials instance and a modelName are provided (no apiClient/apiKey), the build() path uses VertexCredentials to create the Gemini instance.

Execution:
  Arrange: Create vc, obtain a Builder, set modelName("gemini-model"), call vertexCredentials(vc).
  Act: Build the Gemini.
  Assert: The Gemini is constructed via the VertexCredentials path (Gemini(modelName, vertexCredentials)).

Validation:
  Confirms the intended path is taken when VertexCredentials is the only credential source provided besides the required modelName.

Scenario 8: vertexCredentialsOverridesPreviousConsiderationsWhenNoOtherCredentialsArePresent

Details:
  TestName: vertexCredentialsOverridesPreviousConsiderationsWhenNoOtherCredentialsArePresent
  Description: Verifies that after previously configuring apiClient or apiKey, calling vertexCredentials does not retroactively change the chosen path unless those higher-priority fields are cleared; specifically, in the absence of apiClient/apiKey, vertexCredentials should be used.

Execution:
  Arrange: Start with a builder that has modelName set and apiClient/apiKey are null. Call vertexCredentials(vc) with a non-null VertexCredentials.
  Act: Build the Gemini.
  Assert: The VertexCredentials path is used in Gemini construction.

Validation:
  Ensures correct behavior when transitioning from no credentials to VertexCredentials as the sole credential source.


*/

// ********RoostGPT********

package com.google.adk.models;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.mock;

import com.google.genai.Client;
import java.lang.reflect.Field;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

/**
 * Tests for Gemini.Builder.vertexCredentials(VertexCredentials) Generated class
 * BuilderVertexCredentialsTest: BuilderVertexCredentialsTest
 */
class BuilderVertexCredentialsTest {

	private static final Class<?> BUILDER_CLASS;

	static {
		try {
			BUILDER_CLASS = Class.forName("com.google.adk.models.Gemini$Builder");
		}
		catch (ClassNotFoundException e) {
			throw new RuntimeException("Unable to locate Gemini.Builder class", e);
		}
	}

	private Object newBuilder() {
		// Gemini.builder() is expected to provide a Builder instance
		try {
			return Class.forName("com.google.adk.models.Gemini").getMethod("builder").invoke(null);
		}
		catch (Exception e) {
			throw new RuntimeException("Failed to create Gemini Builder", e);
		}
	}

	@Test
	@Tag("valid")
	public void vertexCredentialsWithNonNullSetsFieldAndAllowsChaining() throws Exception {
		VertexCredentials vc = VertexCredentials.builder().build();
		Object builder = newBuilder();
		Method vertexCredentialsMethod = BUILDER_CLASS.getMethod("vertexCredentials", VertexCredentials.class);
		Object returned = vertexCredentialsMethod.invoke(builder, vc);
		assertSame(builder, returned, "vertexCredentials should return the same Builder instance");
		Field fVertexCredentials = BUILDER_CLASS.getDeclaredField("vertexCredentials");
		fVertexCredentials.setAccessible(true);
		Object value = fVertexCredentials.get(builder);
		assertEquals(vc, value, "vertexCredentials field should store the provided value");
	}

	@Test
	@Tag("valid")
	public void vertexCredentialsWithNullDoesNotThrowAndIgnoresInput() throws Exception {
		Object builder = newBuilder();
		Method vertexCredentialsMethod = BUILDER_CLASS.getMethod("vertexCredentials", VertexCredentials.class);
		Object returned = vertexCredentialsMethod.invoke(builder, (Object) null);
		assertSame(builder, returned, "vertexCredentials should return the same Builder instance on null input");
		Field fVertexCredentials = BUILDER_CLASS.getDeclaredField("vertexCredentials");
		fVertexCredentials.setAccessible(true);
		Object value = fVertexCredentials.get(builder);
		assertNull(value, "vertexCredentials field should remain null when null is provided");
	}

	@Test
	@Tag("integration")
	public void vertexCredentialsIgnoredWhenApiClientPresent() throws Exception {
		Object builder = newBuilder();
		Client mockApiClient = mock(Client.class);
		Method apiClientMethod = BUILDER_CLASS.getMethod("apiClient", Client.class);
		apiClientMethod.invoke(builder, mockApiClient);
		VertexCredentials vc = VertexCredentials.builder().build();
		Method vertexCredentialsMethod = BUILDER_CLASS.getMethod("vertexCredentials", VertexCredentials.class);
		vertexCredentialsMethod.invoke(builder, vc);
		Field fApiClient = BUILDER_CLASS.getDeclaredField("apiClient");
		fApiClient.setAccessible(true);
		Object value = fApiClient.get(builder);
		assertEquals(mockApiClient, value, "apiClient should be the explicit provided client");
		// Also ensure VertexCredentials was set (to reflect last write), but build() will
		// still prefer
		// apiClient
		Field fVertexCredentials = BUILDER_CLASS.getDeclaredField("vertexCredentials");
		fVertexCredentials.setAccessible(true);
		Object vcValue = fVertexCredentials.get(builder);
		assertEquals(vc, vcValue,
				"vertexCredentials should be stored but ignored by build path when apiClient is present");
	}

	@Test
	@Tag("integration")
	public void vertexCredentialsIgnoredWhenApiKeyPresent() throws Exception {
		Object builder = newBuilder();
		Method apiKeyMethod = BUILDER_CLASS.getMethod("apiKey", String.class);
		apiKeyMethod.invoke(builder, "sample-key");
		VertexCredentials vc = VertexCredentials.builder().build();
		Method vertexCredentialsMethod = BUILDER_CLASS.getMethod("vertexCredentials", VertexCredentials.class);
		vertexCredentialsMethod.invoke(builder, vc);
		Field fApiKey = BUILDER_CLASS.getDeclaredField("apiKey");
		fApiKey.setAccessible(true);
		Object keyValue = fApiKey.get(builder);
		assertEquals("sample-key", keyValue, "apiKey should store the provided key");
		Field fApiClient = BUILDER_CLASS.getDeclaredField("apiClient");
		fApiClient.setAccessible(true);
		Object apiClientValue = fApiClient.get(builder);
		assertNull(apiClientValue, "apiClient should remain null when only apiKey is provided");
	}

	@Test
	@Tag("boundary")
	public void vertexCredentialsLastValueWinsWithMultipleCalls() throws Exception {
		Object builder = newBuilder();
		VertexCredentials vc1 = VertexCredentials.builder().build();
		VertexCredentials vc2 = VertexCredentials.builder().build();
		Method vertexCredentialsMethod = BUILDER_CLASS.getMethod("vertexCredentials", VertexCredentials.class);
		vertexCredentialsMethod.invoke(builder, vc1);
		vertexCredentialsMethod.invoke(builder, vc2);
		Field fVertexCredentials = BUILDER_CLASS.getDeclaredField("vertexCredentials");
		fVertexCredentials.setAccessible(true);
		Object value = fVertexCredentials.get(builder);
		assertEquals(vc2, value, "The last provided VertexCredentials should be stored in the Builder");
	}

	@Test
	@Tag("invalid")
	public void vertexCredentialsWithoutModelNameThrowsNullPointerException() throws Exception {
		Object builder = newBuilder();
		VertexCredentials vc = VertexCredentials.builder().build();
		Method vertexCredentialsMethod = BUILDER_CLASS.getMethod("vertexCredentials", VertexCredentials.class);
		vertexCredentialsMethod.invoke(builder, vc);
		Method buildMethod = BUILDER_CLASS.getMethod("build");
		InvocationTargetException invocationTargetException = assertThrows(InvocationTargetException.class, () -> {
			buildMethod.invoke(builder);
		});
		Throwable cause = invocationTargetException.getCause();
		assertNotNull(cause, "Expected a cause for the InvocationTargetException");
		assertTrue(cause instanceof NullPointerException, "Expected NullPointerException when modelName is not set");
		String msg = cause.getMessage();
		assertTrue(msg == null || msg.contains("modelName"), "Error message should indicate missing modelName");
	}

	@Test
	@Tag("valid")
	public void vertexCredentialsUsedWhenOnlyVertexCredentialsAndModelNameSet() throws Exception {
		Object builder = newBuilder();
		VertexCredentials vc = VertexCredentials.builder().build();
		Method modelNameMethod = BUILDER_CLASS.getMethod("modelName", String.class);
		modelNameMethod.invoke(builder, "gemini-model");
		Method vertexCredentialsMethod = BUILDER_CLASS.getMethod("vertexCredentials", VertexCredentials.class);
		vertexCredentialsMethod.invoke(builder, vc);
		Field fVertexCredentials = BUILDER_CLASS.getDeclaredField("vertexCredentials");
		fVertexCredentials.setAccessible(true);
		Object value = fVertexCredentials.get(builder);
		assertEquals(vc, value,
				"VertexCredentials should be used when only VertexCredentials and modelName are provided");
	}

	@Test
	@Tag("boundary")
	public void vertexCredentialsOverridesPreviousConsiderationsWhenNoOtherCredentialsArePresent() throws Exception {
		Object builder = newBuilder();
		VertexCredentials vc = VertexCredentials.builder().build();
		Method modelNameMethod = BUILDER_CLASS.getMethod("modelName", String.class);
		modelNameMethod.invoke(builder, "gemini-model");
		Method vertexCredentialsMethod = BUILDER_CLASS.getMethod("vertexCredentials", VertexCredentials.class);
		vertexCredentialsMethod.invoke(builder, vc);
		Field fApiClient = null;
		Field fApiKey = null;
		try {
			fApiClient = BUILDER_CLASS.getDeclaredField("apiClient");
			fApiClient.setAccessible(true);
		}
		catch (NoSuchFieldException e) {
			// ignore if absent in some implementations
		}
		try {
			fApiKey = BUILDER_CLASS.getDeclaredField("apiKey");
			fApiKey.setAccessible(true);
		}
		catch (NoSuchFieldException e) {
			// ignore if absent in some implementations
		}
		if (fApiClient != null) {
			Object apiClientValue = fApiClient.get(builder);
			assertNull(apiClientValue, "apiClient should be null when no explicit client is provided");
		}
		if (fApiKey != null) {
			Object apiKeyValue = fApiKey.get(builder);
			assertNull(apiKeyValue, "apiKey should be null when no explicit key is provided");
		}
		Field fVertexCredentials = BUILDER_CLASS.getDeclaredField("vertexCredentials");
		fVertexCredentials.setAccessible(true);
		Object value = fVertexCredentials.get(builder);
		assertEquals(vc, value, "VertexCredentials should be the active credential source when others are absent");
	}

}
