/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Azure Open AI and AI Model gpt-5

ROOST_METHOD_HASH=connect_a5c76abc47
ROOST_METHOD_SIG_HASH=connect_967ce38618

Scenario 1: Throws UnsupportedOperationException for any non-null input

Details:
  TestName: throwsUnsupportedOperationExceptionForValidInput
  Description: Verify that calling connect with a syntactically valid LlmRequest object always throws UnsupportedOperationException, as live connections are explicitly not supported for Claude models. This ensures the method enforces the documented limitation regardless of request content.

Execution:
  Arrange: Create a Claude instance with a chosen model name (e.g., "claude-3-opus-20240229") and a harmless test double for AnthropicClient. Prepare a minimal LlmRequest test double (mock or stub) to pass to the method.
  Act: Invoke connect(llmRequest) with the prepared non-null request.
  Assert: Use JUnit’s assertThrows to confirm that an UnsupportedOperationException is thrown.

Validation:
  The assertion verifies that the method does not allow a live connection under any normal usage scenario. This is significant because it enforces the contract stated in the class documentation and prevents unsupported runtime behavior.

*/

// ********RoostGPT********

package com.google.adk.models;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

import com.anthropic.client.AnthropicClient;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class ClaudeConnectTest {

  @Mock private AnthropicClient anthropicClient;

  private Claude claude;

  @BeforeEach
  public void setup() {
    // TODO: Change model name if needed to match your environment or preferences
    this.claude = new Claude("claude-3-opus-20240229", anthropicClient);
  }

  @Test
  @Tag("valid")
  public void testThrowsUnsupportedOperationExceptionForValidInput() {
    LlmRequest llmRequest = Mockito.mock(LlmRequest.class);
    Mockito.when(llmRequest.model()).thenReturn(Optional.of("claude-3-opus-20240229"));
    UnsupportedOperationException ex =
        assertThrows(UnsupportedOperationException.class, () -> claude.connect(llmRequest));
    assertEquals("Live connection is not supported for Claude models.", (String) ex.getMessage());
  }

  @Test
  @Tag("invalid")
  public void testThrowsUnsupportedOperationExceptionForNullInput() {
    UnsupportedOperationException ex =
        assertThrows(UnsupportedOperationException.class, () -> claude.connect(null));
    assertEquals("Live connection is not supported for Claude models.", (String) ex.getMessage());
  }

  @Test
  @Tag("boundary")
  public void testThrowsUnsupportedOperationExceptionForMinimalRequest() {
    LlmRequest llmRequest = Mockito.mock(LlmRequest.class);
    UnsupportedOperationException ex =
        assertThrows(UnsupportedOperationException.class, () -> claude.connect(llmRequest));
    assertEquals("Live connection is not supported for Claude models.", (String) ex.getMessage());
  }

  @Test
  @Tag("integration")
  public void testThrowsUnsupportedOperationExceptionWithAlternateConstructor() {
    // TODO: Adjust maxTokens as needed based on your test configuration
    Claude altClaude = new Claude("claude-3-opus-20240229", anthropicClient, 1024);
    LlmRequest llmRequest = Mockito.mock(LlmRequest.class);
    Mockito.when(llmRequest.model()).thenReturn(Optional.of("claude-3-opus-20240229"));
    UnsupportedOperationException ex =
        assertThrows(UnsupportedOperationException.class, () -> altClaude.connect(llmRequest));
    assertEquals("Live connection is not supported for Claude models.", (String) ex.getMessage());
  }
}
