/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test adk-java-demo using AI Type Azure Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=generateContent_bc4a182290
ROOST_METHOD_SIG_HASH=generateContent_c08b9769fe

Here are your existing test cases which we found out and are not considered for test generation:

File Path: C:\var\tmp\Roost\RoostGPT\adk-java-demo\1779694771\source\adk-java\core\src\test\java\com\google\adk\models\ApigeeLlmTest.java
Tests:
    "@Test
public void generateContent_stripsApigeePrefixAndSendsToDelegate() {
        when(mockGeminiDelegate.generateContent(any(), anyBoolean())).thenReturn(Flowable.empty());
        ApigeeLlm llm = new ApigeeLlm("apigee/gemini/v1/gemini-1.5-flash", mockGeminiDelegate);
        LlmRequest request = LlmRequest.builder().model("apigee/gemini/v1/gemini-1.5-flash").contents(ImmutableList.of(Content.builder().parts(Part.fromText("hi")).build())).build();
        llm.generateContent(request, true).test().assertNoErrors();
        ArgumentCaptor<LlmRequest> requestCaptor = ArgumentCaptor.forClass(LlmRequest.class);
        verify(mockGeminiDelegate).generateContent(requestCaptor.capture(), eq(true));
        assertThat(requestCaptor.getValue().model()).hasValue("gemini-1.5-flash");
    }
"
    "@Test
public void build_withTrailingSlashInModel_parsesVersionAndModelId() {
        when(mockGeminiDelegate.generateContent(any(), anyBoolean())).thenReturn(Flowable.empty());
        ApigeeLlm llm = new ApigeeLlm("apigee/gemini/v1/", mockGeminiDelegate);
        LlmRequest request = LlmRequest.builder().contents(ImmutableList.of(Content.builder().parts(Part.fromText("hi")).build())).build();
        assertThrows(IllegalArgumentException.class, () -> llm.generateContent(request, false));
        verify(mockGeminiDelegate, never()).generateContent(any(), anyBoolean());
    }
"Scenario 1: Basic Content Generation with Minimal Parameters

Details:  
  TestName: generateContentWithMinimalParameters
  Description: Verifies if the generateContent method correctly processes an LlmRequest that only contains a basic content part with no additional configuration, tools, or system instructions. This scenario checks that the method handles default values and essential flows as expected for a minimal request. 
Execution:
  Arrange: Mock the AnthropicClient, Message, and all dependent objects. Prepare an LlmRequest with a single content containing a simple text part, no configuration, tools, or model specified.
  Act: Call the generateContent method with the prepared LlmRequest and stream set to false.
  Assert: Check that the Flowable emits an LlmResponse containing the correct content, with the proper role ("model") and the provided text part.
Validation: 
  The assertion verifies that basic text generation works for non-complex requests, confirming the fundamental functionality of the method and its ability to process default parameters.

Scenario 2: Content Generation with Explicit Model Provided in LlmRequest

Details:  
  TestName: generateContentWithExplicitModel
  Description: Tests the scenario where an explicit model name is set in the LlmRequest. Checks if the method uses this model instead of the default Claude model and correctly incorporates it into the MessageCreateParams.
Execution:
  Arrange: Set up mocks for AnthropicClient and related objects. Create an LlmRequest with a specified model value and simple content.
  Act: Invoke generateContent with this LlmRequest and streaming set to true.
  Assert: Verify that the emitted LlmResponse reflects the usage of the specified model and the returned content matches expectations.
Validation: 
  This assertion ensures model priority is respected, validating that the code prefers user-specified models over defaults.

Scenario 3: Content Generation with Tools Configuration

Details:  
  TestName: generateContentWithToolsConfiguration
  Description: Assesses whether generateContent accurately processes LlmRequest config containing tool declarations and converts them into Anthropic ToolUnion objects, then attaches them to the MessageCreateParams.
Execution:
  Arrange: Mock tool-related objects and AnthropicClient. Construct an LlmRequest with config holding tools and at least one function declaration.
  Act: Call generateContent with this request and stream set to false.
  Assert: Confirm the Flowable emits an LlmResponse, and that the MessageCreateParams includes the tool information translated from input.
Validation: 
  This test confirms tool declaration logic is functional and tools are mapped correctly, critical for advanced use cases with tool instructions.

Scenario 4: Content Generation Without Tools when Config Indicates Empty Tools List

Details:  
  TestName: generateContentWithoutToolsWhenEmptyConfig
  Description: Ensures the method does not attempt to include tools or toolChoice when LlmRequest config exists but tools().get() is empty or not present.
Execution:
  Arrange: Mock required dependencies. Compose an LlmRequest whose config is present, but tools is empty.
  Act: Invoke generateContent using the above input and stream=false.
  Assert: Assert that no tools are included in the MessageCreateParams and the output LlmResponse is correct.
Validation: 
  The assertion prevents accidental tool inclusion, validating proper handling of empty tool configurations.

Scenario 5: Content Generation with System Instructions Present in Config

Details:  
  TestName: generateContentWithSystemInstructions
  Description: Validate that when LlmRequest config contains a systemInstruction, the systemText is extracted and correctly included in MessageCreateParams.
Execution:
  Arrange: Mock AnthropicClient and Message, form LlmRequest config with a Content containing systemInstruction parts with text values.
  Act: Execute generateContent with that input (stream can be true or false).
  Assert: Check that the emitted LlmResponse content includes the expected systemText and overall structure.
Validation: 
  Confirms the ability to incorporate system instructions into content generation, necessary for prompt customization scenarios.

Scenario 6: Content Generation When System Instructions Are Empty

Details:  
  TestName: generateContentWithEmptySystemInstructions
  Description: Ensures that if systemInstruction parts have no text or are empty, the systemText defaults to empty and MessageCreateParams handles it accordingly.
Execution:
  Arrange: Mock everything needed, create an LlmRequest whose config contains systemInstruction with parts but none have text.
  Act: Call generateContent with this LlmRequest.
  Assert: Check that systemText in MessageCreateParams is empty and LlmResponse does not reflect unwanted system instructions.
Validation: 
  This test validates correct handling of empty instruction, avoiding unintended prompt injection and ensuring robustness.

Scenario 7: Content Generation When Tools List Provided in LlmRequest.tools()

Details:  
  TestName: generateContentWithToolsListProvided
  Description: Tests whether a non-empty tools() list in the LlmRequest results in toolChoice being set with disableParallelToolUse true.
Execution:
  Arrange: Use mocks and provide an LlmRequest with LlmRequest.tools() non-empty, and other parameters as necessary.
  Act: Invoke generateContent.
  Assert: Assert that the toolChoice appears in MessageCreateParams and LlmResponse is emitted as expected.
Validation: 
  Validates ability to correctly process situations where tools are specified directly, ensuring that toolChoice logic does not overlook user-specified scenarios.

Scenario 8: Content Generation with Multiple Contents in LlmRequest

Details:  
  TestName: generateContentWithMultipleContents
  Description: Checks that multiple Content instances in the contents() list are appropriately processed into MessageParam objects and included in the request.
Execution:
  Arrange: Mock dependencies. Supply an LlmRequest with several contents, varying roles and text.
  Act: Call generateContent.
  Assert: Validate that the output LlmResponse contains all expected parts.
Validation: 
  Ensures support for batch messaging, confirming method's correct processing of multiple input prompts.

Scenario 9: Content Generation When Message Returned by AnthropicClient Is Null

Details:  
  TestName: generateContentWithNullMessageFromClient
  Description: Simulates a case where the client returns a null message. Confirms that the method and its internal conversion gracefully handle a null response and do not produce unexpected errors or content.
Execution:
  Arrange: Mock the AnthropicClient to return null for messages().create. Input a valid LlmRequest.
  Act: Invoke generateContent.
  Assert: Check that the Flowable emits an LlmResponse with appropriate defaults or empty content.
Validation: 
  Critical for resilience to upstream API anomalies, ensuring the app fails gracefully.

Scenario 10: Content Generation Where Content Includes FunctionCall Part

Details:  
  TestName: generateContentWithFunctionCallPart
  Description: Verifies that if the Content part in LlmRequest contains a functionCall, the contentToAnthropicMessageParam translates it into a ToolUseBlockParam, and it is correctly included.
Execution:
  Arrange: Mock all related objects. Supply an LlmRequest part containing a functionCall.
  Act: Execute generateContent.
  Assert: Check that ToolUseBlockParam appears in MessageCreateParams and final LlmResponse.
Validation: 
  Ensures accurate translation of function call prompts, key for function-driven generative tasks.

Scenario 11: Content Generation Where Content Includes FunctionResponse Part

Details:  
  TestName: generateContentWithFunctionResponsePart
  Description: Tests handling of parts containing functionResponse and checks that corresponding ToolResultBlockParam is generated.
Execution:
  Arrange: Mock objects, input LlmRequest part with a valid functionResponse.
  Act: Call generateContent.
  Assert: Validate ToolResultBlockParam inclusion and correct mapping in LlmResponse.
Validation: 
  Necessary for completion of function call lifecycle, ensuring the platform can process responses properly.

Scenario 12: Content Generation When LlmRequest.contents() Is Empty

Details:  
  TestName: generateContentWithEmptyContents
  Description: Tests the behavior when LlmRequest.contents() is empty, ensuring method processes gracefully and returns LlmResponse as appropriate.
Execution:
  Arrange: Mock all dependencies. Provide an LlmRequest whose contents() is an empty ImmutableList.
  Act: Call generateContent.
  Assert: Assert that LlmResponse is emitted and does not contain unexpected parts.
Validation: 
  Essential for robust input handling, guaranteeing predictable output for edge input scenarios.

Scenario 13: Content Generation with Maximum Token Limit Set

Details:  
  TestName: generateContentWithMaxTokensConfigured
  Description: Verifies that the maxTokens field is used when building MessageCreateParams and governs output structure.
Execution:
  Arrange: Use constructor to set a specific maxTokens value; mock the rest. Create a basic LlmRequest.
  Act: Call generateContent and record internal params.
  Assert: Confirm maxTokens is set in MessageCreateParams and affects response accordingly.
Validation: 
  Ensures configuration parameter is honored, supporting customizable prompt constraints.

Scenario 14: Content Generation When SystemInstruction Has Multiple Parts

Details:  
  TestName: generateContentWithMultiPartSystemInstruction
  Description: Checks if multiple parts in systemInstruction are joined properly into systemText, separated by newlines.
Execution:
  Arrange: Mock and prepare LlmRequest config with systemInstruction containing several parts with different texts.
  Act: Generate content and examine output.
  Assert: Confirm that systemText includes all texts in correct order, separated as per logic.
Validation: 
  Verifies correct concatenation for complex instructions, critical for nuanced prompt engineering.

Scenario 15: Content Generation When Message Content Is Missing

Details:  
  TestName: generateContentWithMissingMessageContent
  Description: Simulates a scenario where the returned Message from AnthropicClient has a null content property, ensuring convertAnthropicResponseToLlmResponse manages it gracefully.
Execution:
  Arrange: Mock AnthropicClient to provide Message with null content. Prepare a simple LlmRequest.
  Act: Call generateContent.
  Assert: Validate that LlmResponse does not throw or include erroneous parts.
Validation: 
  Confirms defensive code for absent API results, enhancing system stability.

Scenario 16: Content Generation Using Default Model When LlmRequest.model() Is Not Provided

Details:  
  TestName: generateContentUsesDefaultModelWhenNoneProvided
  Description: Ensures that if LlmRequest.model() is absent, method falls back to the default Claude model initialized in the constructor.
Execution:
  Arrange: Prepare LlmRequest without model, mock everything else.
  Act: Call generateContent.
  Assert: Verify default model is used in MessageCreateParams and LlmResponse.
Validation: 
  Validates default-flow logic, crucial for implicit usage scenarios.

Scenario 17: Content Generation When LlmRequest.config() Is Not Present

Details:  
  TestName: generateContentWithAbsentConfig
  Description: Checks that absence of configuration in LlmRequest does not cause failures, and default values are used for systemText and tools.
Execution:
  Arrange: Make an LlmRequest without config, mock as needed.
  Act: Call generateContent.
  Assert: Confirm full response is built using defaults.
Validation: 
  Affirms code's ability to handle missing configurations gracefully.

Scenario 18: Content Generation With Stream Parameter True

Details:  
  TestName: generateContentWithStreamTrue
  Description: Confirms that regardless of the stream parameter, since the method is non-streaming, Flowable.just is always used, and the response is immediate.
Execution:
  Arrange: Prepare a valid LlmRequest and mock client. Set stream parameter to true.
  Act: Execute generateContent.
  Assert: Output is a Flowable.just type with expected LlmResponse.
Validation: 
  Ensures streaming parameter does not impact method behavior, indicating current implementation supports only static generation.

Scenario 19: Content Generation With Stream Parameter False

Details:  
  TestName: generateContentWithStreamFalse
  Description: Same as previous, but explicitly validates stream=false case, confirming method response type and speed.
Execution:
  Arrange: Supply mocks and LlmRequest, set stream to false.
  Act: Call generateContent.
  Assert: Response type and content matches Flowable.just.
Validation: 
  Demonstrates method's API consistency for both values of stream.

Scenario 20: Content Generation When MessageParam Conversion Throws Exception

Details:  
  TestName: generateContentHandlesMessageParamConversionException
  Description: Simulates a case where contentToAnthropicMessageParam or partToAnthropicMessageBlock encounters unsupported Part and throws UnsupportedOperationException. Confirms method does not result in unexpected output.
Execution:
  Arrange: Provide LlmRequest with unsupported content part, mock all else.
  Act: Attempt generateContent.
  Assert: Exception is thrown and handled (if within test framework).
Validation: 
  Validates error handling and exception propagation, critical for developer experience and debugging.

Scenario 21: Content Generation When FunctionDeclaration Lacks Required Fields

Details:  
  TestName: generateContentWithIncompleteFunctionDeclaration
  Description: Tests scenario where functionDeclaration lacks required fields (e.g., .name()), expecting method to throw an exception or fail gracefully.
Execution:
  Arrange: Input config with tool and incomplete functionDeclaration, mock dependencies.
  Act: Call generateContent.
  Assert: Check for thrown exception or proper error signaling.
Validation: 
  Ensures robustness against malformed tool declarations, protecting against API error propagation.

Scenario 22: Content Generation When SystemInstruction Parts Have Null Text

Details:  
  TestName: generateContentIgnoresNullTextsInSystemInstruction
  Description: Confirms that parts with null text in systemInstruction are ignored when extracting systemText.
Execution:
  Arrange: LlmRequest config with systemInstruction containing parts with text and parts with null.
  Act: Call generateContent.
  Assert: Only non-null texts appear in systemText.
Validation: 
  Prevents erroneous instructions, maintaining clean prompt injection.

Scenario 23: Content Generation When ToolChoice Is Null

Details:  
  TestName: generateContentWithNullToolChoice
  Description: Tests that if toolChoice is null (LlmRequest.tools() is empty), no toolChoice or tools are set in MessageCreateParams.
Execution:
  Arrange: Compose LlmRequest with tools() empty, mock everything else.
  Act: Invoke generateContent.
  Assert: Confirm MessageCreateParams omits tools/toolChoice.
Validation: 
  Verifies correct branching logic, ensuring tools are only set when appropriate.

Scenario 24: Content Generation With Large Number of Contents

Details:  
  TestName: generateContentWithLargeContentList
  Description: Checks scalability when a very large contents() list is provided, and all are mapped to MessageParam correctly.
Execution:
  Arrange: Generate LlmRequest with dozens/hundreds of content parts, mock dependencies.
  Act: Call generateContent.
  Assert: LlmResponse contains all parts, no truncation or performance issue is observed.
Validation: 
  Important for batch processing or bulk prompt scenarios; tests method scalability.

Scenario 25: Content Generation When Tools Config Contains Nested Properties

Details:  
  TestName: generateContentWithToolsAndNestedProperties
  Description: Tests robustness of functionDeclarationToAnthropicTool mapping logic with nested property schemas.
Execution:
  Arrange: Use LlmRequest config containing function declaration with complex, nested properties.
  Act: Call generateContent.
  Assert: Tools mapping properly includes all nested structures in MessageCreateParams.
Validation: 
  Validates advanced schema processing, crucial for complex tool definitions.

Scenario 26: Content Generation When Tools Config Lacks FunctionDeclarations

Details:  
  TestName: generateContentWithToolsConfigLackingFunctionDeclarations
  Description: Checks that when tools() in config exists but functionDeclarations() is absent, no tools are mapped or included.
Execution:
  Arrange: LlmRequest config with tools, each lacking functionDeclarations.
  Act: Call generateContent.
  Assert: MessageCreateParams contains no tools; LlmResponse is generated as usual.
Validation: 
  Ensures defensive programming for incomplete tool deconfigurations.

*/

// ********RoostGPT********

package com.google.adk.models;
import com.anthropic.client.AnthropicClient;
import com.anthropic.models.messages.ContentBlock;
import com.anthropic.models.messages.Message;
import com.anthropic.models.messages.MessageCreateParams;
import com.anthropic.models.messages.MessageParam;
import com.anthropic.models.messages.ToolUnion;
import com.anthropic.models.messages.ToolChoice;
import com.anthropic.models.messages.ToolChoiceAuto;
import com.anthropic.models.messages.Tool;
import com.anthropic.models.messages.ToolResultBlockParam;
import com.anthropic.models.messages.ToolUseBlockParam;
import com.anthropic.models.messages.ContentBlockParam;
import com.anthropic.models.messages.TextBlockParam;
import com.google.genai.types.Content;
import com.google.genai.types.Part;
import com.google.genai.types.FunctionCall;
import com.google.genai.types.FunctionDeclaration;
import com.google.genai.types.GenerateContentConfig;
import io.reactivex.rxjava3.core.Flowable;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.MockitoAnnotations;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableMap;
import org.junit.jupiter.api.Assertions;
import java.util.*;
import java.util.stream.Collectors;
import org.junit.jupiter.api.*;
import com.anthropic.models.messages.MessageParam.Role;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ClaudeGenerateContentTest extends BaseLlm {
    @Mock
    private AnthropicClient anthropicClient;
    @Mock
    private AnthropicClient.Messages messagesClient;
    private Claude claude;
    @BeforeEach
    public void setup() {
        MockitoAnnotations.openMocks(this);
        claude = new Claude("claude-2", anthropicClient, 8192);
        Mockito.when(anthropicClient.messages()).thenReturn(messagesClient);
    }
    @Test
    @Tag("valid")
    public void testGenerateContentWithMinimalParameters() {
        Content content = Content.builder().role("user").parts(ImmutableList.of(Part.builder().text("Hello, Claude!").build())).build();
        LlmRequest llmRequest = LlmRequest.builder()
                .contents(ImmutableList.of(content))
                .build();
        MessageParam messageParam = MessageParam.builder().role(MessageParam.Role.USER).content(ImmutableList.of(TextBlockParam.builder().text("Hello, Claude!").build())).build();
        MessageCreateParams createParams = MessageCreateParams.builder()
                .model("claude-2") // default model
                .system("")
                .messages(ImmutableList.of(messageParam))
                .maxTokens(8192)
                .build();
        ContentBlock contentBlock = Mockito.mock(ContentBlock.class);
        Mockito.when(contentBlock.text()).thenReturn(Optional.of("Hello, Claude!"));
        Message message = Mockito.mock(Message.class);
        Mockito.when(message.content()).thenReturn(ImmutableList.of(contentBlock));
        Mockito.when(messagesClient.create(any(MessageCreateParams.class))).thenReturn(message);
        Flowable<LlmResponse> flowable = claude.generateContent(llmRequest, false);
        List<LlmResponse> responses = flowable.toList().blockingGet();
        LlmResponse actualResponse = responses.get(0);
        Assertions.assertEquals("model", actualResponse.content().get().role(), "Role should be 'model'");
        Assertions.assertEquals("Hello, Claude!", actualResponse.content().get().parts().get().get(0).text().get());
    }
    @Test
    @Tag("valid")
    public void testGenerateContentWithExplicitModel() {
        Content content = Content.builder().role("user").parts(ImmutableList.of(Part.builder().text("Custom model query").build())).build();
        LlmRequest llmRequest = LlmRequest.builder()
                .model(Optional.of("custom-model"))
                .contents(ImmutableList.of(content))
                .build();
        MessageParam messageParam = MessageParam.builder().role(MessageParam.Role.USER).content(ImmutableList.of(TextBlockParam.builder().text("Custom model query").build())).build();
        MessageCreateParams createParams = MessageCreateParams.builder()
                .model("custom-model")
                .system("")
                .messages(ImmutableList.of(messageParam))
                .maxTokens(8192)
                .build();
        ContentBlock contentBlock = Mockito.mock(ContentBlock.class);
        Mockito.when(contentBlock.text()).thenReturn(Optional.of("Custom model query"));
        Message message = Mockito.mock(Message.class);
        Mockito.when(message.content()).thenReturn(ImmutableList.of(contentBlock));
        Mockito.when(messagesClient.create(any(MessageCreateParams.class))).thenReturn(message);
        Flowable<LlmResponse> flowable = claude.generateContent(llmRequest, true);
        List<LlmResponse> responses = flowable.toList().blockingGet();
        LlmResponse actualResponse = responses.get(0);
        Assertions.assertEquals("model", actualResponse.content().get().role(), "Role should be 'model'");
        Assertions.assertEquals("Custom model query", actualResponse.content().get().parts().get().get(0).text().get());
    }
    @Test
    @Tag("integration")
    public void testGenerateContentWithToolsConfiguration() {
        FunctionDeclaration functionDecl = Mockito.mock(FunctionDeclaration.class);
        Mockito.when(functionDecl.name()).thenReturn(Optional.of("func1"));
        GenerateContentConfig.ToolsConfig toolsConfig = Mockito.mock(GenerateContentConfig.ToolsConfig.class);
        Mockito.when(toolsConfig.functionDeclarations()).thenReturn(Optional.of(ImmutableList.of(functionDecl)));
        GenerateContentConfig config = Mockito.mock(GenerateContentConfig.class);
        Mockito.when(config.tools()).thenReturn(Optional.of(ImmutableList.of(toolsConfig)));
        Content content = Content.builder().role("user").parts(ImmutableList.of(Part.builder().text("Tool question").build())).build();
        LlmRequest llmRequest = LlmRequest.builder()
                .contents(ImmutableList.of(content))
                .config(Optional.of(config))
                .build();
        MessageParam messageParam = MessageParam.builder().role(MessageParam.Role.USER).content(ImmutableList.of(TextBlockParam.builder().text("Tool question").build())).build();
        Tool tool = Mockito.mock(Tool.class);
        ToolUnion toolUnion = ToolUnion.ofTool(tool);
        ToolChoice toolChoice = ToolChoice.ofAuto(ToolChoiceAuto.builder().disableParallelToolUse(true).build());
        MessageCreateParams.Builder paramsBuilder =
                MessageCreateParams.builder().model("claude-2").system("").messages(ImmutableList.of(messageParam)).maxTokens(8192);
        paramsBuilder.tools(ImmutableList.of(toolUnion));
        paramsBuilder.toolChoice(toolChoice);
        Message message = Mockito.mock(Message.class);
        ContentBlock contentBlock = Mockito.mock(ContentBlock.class);
        Mockito.when(contentBlock.text()).thenReturn(Optional.of("Tool question"));
        Mockito.when(message.content()).thenReturn(ImmutableList.of(contentBlock));
        Mockito.when(messagesClient.create(any(MessageCreateParams.class))).thenReturn(message);
        Flowable<LlmResponse> flowable = claude.generateContent(llmRequest, false);
        List<LlmResponse> responses = flowable.toList().blockingGet();
        Assertions.assertEquals("Tool question", responses.get(0).content().get().parts().get().get(0).text().get());
    }
    @Test
    @Tag("valid")
    public void testGenerateContentWithoutToolsWhenEmptyConfig() {
        GenerateContentConfig.ToolsConfig toolsConfig = Mockito.mock(GenerateContentConfig.ToolsConfig.class);
        Mockito.when(toolsConfig.functionDeclarations()).thenReturn(Optional.empty());
        GenerateContentConfig config = Mockito.mock(GenerateContentConfig.class);
        Mockito.when(config.tools()).thenReturn(Optional.of(ImmutableList.of(toolsConfig)));
        Content content = Content.builder().role("user").parts(ImmutableList.of(Part.builder().text("No Tools Request").build())).build();
        LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(content)).config(Optional.of(config)).build();
        MessageParam messageParam = MessageParam.builder().role(MessageParam.Role.USER).content(ImmutableList.of(TextBlockParam.builder().text("No Tools Request").build())).build();
        Message message = Mockito.mock(Message.class);
        ContentBlock contentBlock = Mockito.mock(ContentBlock.class);
        Mockito.when(contentBlock.text()).thenReturn(Optional.of("No Tools Request"));
        Mockito.when(message.content()).thenReturn(ImmutableList.of(contentBlock));
        Mockito.when(messagesClient.create(any(MessageCreateParams.class))).thenReturn(message);
        Flowable<LlmResponse> flowable = claude.generateContent(llmRequest, false);
        List<LlmResponse> responses = flowable.toList().blockingGet();
        Assertions.assertEquals("No Tools Request", responses.get(0).content().get().parts().get().get(0).text().get());
    }
    @Test
    @Tag("valid")
    public void testGenerateContentWithSystemInstructions() {
        Part systemPart = Part.builder().text("System prompt line").build();
        Content systemContent = Content.builder().role("system").parts(ImmutableList.of(systemPart)).build();
        GenerateContentConfig config = Mockito.mock(GenerateContentConfig.class);
        Mockito.when(config.systemInstruction()).thenReturn(Optional.of(systemContent));
        Content content = Content.builder().role("user").parts(ImmutableList.of(Part.builder().text("User query").build())).build();
        LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(content)).config(Optional.of(config)).build();
        MessageParam messageParam = MessageParam.builder().role(MessageParam.Role.USER).content(ImmutableList.of(TextBlockParam.builder().text("User query").build())).build();
        Message message = Mockito.mock(Message.class);
        ContentBlock contentBlock = Mockito.mock(ContentBlock.class);
        Mockito.when(contentBlock.text()).thenReturn(Optional.of("User query"));
        Mockito.when(message.content()).thenReturn(ImmutableList.of(contentBlock));
        Mockito.when(messagesClient.create(any(MessageCreateParams.class))).thenReturn(message);
        Flowable<LlmResponse> flowable = claude.generateContent(llmRequest, true);
        List<LlmResponse> responses = flowable.toList().blockingGet();
        Assertions.assertEquals("User query", responses.get(0).content().get().parts().get().get(0).text().get());
    }
    @Test
    @Tag("valid")
    public void testGenerateContentWithEmptySystemInstructions() {
        Content systemContent = Content.builder().role("system").parts(ImmutableList.of()).build();
        GenerateContentConfig config = Mockito.mock(GenerateContentConfig.class);
        Mockito.when(config.systemInstruction()).thenReturn(Optional.of(systemContent));
        Content content = Content.builder().role("user").parts(ImmutableList.of(Part.builder().text("Empty system instruction").build())).build();
        LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(content)).config(Optional.of(config)).build();
        Message message = Mockito.mock(Message.class);
        ContentBlock contentBlock = Mockito.mock(ContentBlock.class);
        Mockito.when(contentBlock.text()).thenReturn(Optional.of("Empty system instruction"));
        Mockito.when(message.content()).thenReturn(ImmutableList.of(contentBlock));
        Mockito.when(messagesClient.create(any(MessageCreateParams.class))).thenReturn(message);
        Flowable<LlmResponse> flowable = claude.generateContent(llmRequest, false);
        List<LlmResponse> responses = flowable.toList().blockingGet();
        Assertions.assertEquals("Empty system instruction", responses.get(0).content().get().parts().get().get(0).text().get());
    }
    @Test
    @Tag("integration")
    public void testGenerateContentWithToolsListProvided() {
        Content content = Content.builder().role("user").parts(ImmutableList.of(Part.builder().text("Tool feature test").build())).build();
        Map<String, BaseTool> toolsMap = ImmutableMap.of("mytool", Mockito.mock(BaseTool.class));
        LlmRequest llmRequest = LlmRequest.builder()
                .contents(ImmutableList.of(content))
                .tools(toolsMap)
                .build();
        MessageParam messageParam = MessageParam.builder().role(MessageParam.Role.USER).content(ImmutableList.of(TextBlockParam.builder().text("Tool feature test").build())).build();
        ToolChoice toolChoice = ToolChoice.ofAuto(ToolChoiceAuto.builder().disableParallelToolUse(true).build());
        Message message = Mockito.mock(Message.class);
        ContentBlock contentBlock = Mockito.mock(ContentBlock.class);
        Mockito.when(contentBlock.text()).thenReturn(Optional.of("Tool feature test"));
        Mockito.when(message.content()).thenReturn(ImmutableList.of(contentBlock));
        Mockito.when(messagesClient.create(any(MessageCreateParams.class))).thenReturn(message);
        Flowable<LlmResponse> flowable = claude.generateContent(llmRequest, false);
        List<LlmResponse> responses = flowable.toList().blockingGet();
        Assertions.assertEquals("Tool feature test", responses.get(0).content().get().parts().get().get(0).text().get());
    }
    @Test
    @Tag("valid")
    public void testGenerateContentWithMultipleContents() {
        Content content1 = Content.builder().role("user").parts(ImmutableList.of(Part.builder().text("First").build())).build();
        Content content2 = Content.builder().role("user").parts(ImmutableList.of(Part.builder().text("Second").build())).build();
        LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(content1, content2)).build();
        ContentBlock contentBlock1 = Mockito.mock(ContentBlock.class);
        Mockito.when(contentBlock1.text()).thenReturn(Optional.of("First"));
        ContentBlock contentBlock2 = Mockito.mock(ContentBlock.class);
        Mockito.when(contentBlock2.text()).thenReturn(Optional.of("Second"));
        Message message = Mockito.mock(Message.class);
        Mockito.when(message.content()).thenReturn(ImmutableList.of(contentBlock1, contentBlock2));
        Mockito.when(messagesClient.create(any(MessageCreateParams.class))).thenReturn(message);
        Flowable<LlmResponse> flowable = claude.generateContent(llmRequest, false);
        List<LlmResponse> responses = flowable.toList().blockingGet();
        List<Part> parts = responses.get(0).content().get().parts().get();
        Assertions.assertEquals("First", parts.get(0).text().get());
        Assertions.assertEquals("Second", parts.get(1).text().get());
    }
    @Test
    @Tag("invalid")
    public void testGenerateContentWithNullMessageFromClient() {
        Content content = Content.builder().role("user").parts(ImmutableList.of(Part.builder().text("Null Message Test").build())).build();
        LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(content)).build();
        Mockito.when(messagesClient.create(any(MessageCreateParams.class))).thenReturn(null);
        Flowable<LlmResponse> flowable = claude.generateContent(llmRequest, false);
        List<LlmResponse> responses = flowable.toList().blockingGet();
        Assertions.assertTrue(responses.get(0).content().isEmpty() || !responses.get(0).content().get().parts().isPresent() || responses.get(0).content().get().parts().get().isEmpty());
    }
    @Test
    @Tag("integration")
    public void testGenerateContentWithFunctionCallPart() {
        FunctionCall functionCall = FunctionCall.builder().name("callFunc").build();
        Part functionCallPart = Part.builder().functionCall(functionCall).build();
        Content content = Content.builder().role("user").parts(ImmutableList.of(functionCallPart)).build();
        LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(content)).build();
        ToolUseBlockParam toolUseBlockParam = Mockito.mock(ToolUseBlockParam.class);
        MessageParam messageParam = Mockito.mock(MessageParam.class);
        Message message = Mockito.mock(Message.class);
        ContentBlock contentBlock = Mockito.mock(ContentBlock.class);
        Mockito.when(contentBlock.text()).thenReturn(Optional.of("FunctionCall Result")); // TODO: adapt expected text if needed
        Mockito.when(message.content()).thenReturn(ImmutableList.of(contentBlock));
        Mockito.when(messagesClient.create(any(MessageCreateParams.class))).thenReturn(message);
        Flowable<LlmResponse> flowable = claude.generateContent(llmRequest, false);
        LlmResponse response = flowable.blockingFirst();
        Assertions.assertEquals("FunctionCall Result", response.content().get().parts().get().get(0).text().get());
    }
    @Test
    @Tag("integration")
    public void testGenerateContentWithFunctionResponsePart() {
        Part functionResponsePart = Part.builder().functionResponse(Optional.of("response-value")).build();
        Content content = Content.builder().role("user").parts(ImmutableList.of(functionResponsePart)).build();
        LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(content)).build();
        ToolResultBlockParam toolResultBlockParam = Mockito.mock(ToolResultBlockParam.class);
        MessageParam messageParam = Mockito.mock(MessageParam.class);
        Message message = Mockito.mock(Message.class);
        ContentBlock contentBlock = Mockito.mock(ContentBlock.class);
        Mockito.when(contentBlock.text()).thenReturn(Optional.of("response-value")); // TODO: adapt expected text if needed
        Mockito.when(message.content()).thenReturn(ImmutableList.of(contentBlock));
        Mockito.when(messagesClient.create(any(MessageCreateParams.class))).thenReturn(message);
        Flowable<LlmResponse> flowable = claude.generateContent(llmRequest, false);
        LlmResponse response = flowable.blockingFirst();
        Assertions.assertEquals("response-value", response.content().get().parts().get().get(0).text().get());
    }
    @Test
    @Tag("boundary")
    public void testGenerateContentWithEmptyContents() {
        LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of()).build();
        Message message = Mockito.mock(Message.class);
        Mockito.when(message.content()).thenReturn(ImmutableList.of());
        Mockito.when(messagesClient.create(any(MessageCreateParams.class))).thenReturn(message);
        Flowable<LlmResponse> flowable = claude.generateContent(llmRequest, false);
        Assertions.assertTrue(flowable.blockingFirst().content().get().parts().get().isEmpty());
    }
    @Test
    @Tag("boundary")
    public void testGenerateContentWithMaxTokensConfigured() {
        Claude claudeWithMaxTokens = new Claude("claude-2", anthropicClient, 64);
        Content content = Content.builder().role("user").parts(ImmutableList.of(Part.builder().text("Max token check").build())).build();
        LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(content)).build();
        Message message = Mockito.mock(Message.class);
        ContentBlock contentBlock = Mockito.mock(ContentBlock.class);
        Mockito.when(contentBlock.text()).thenReturn(Optional.of("Max token check"));
        Mockito.when(message.content()).thenReturn(ImmutableList.of(contentBlock));
        Mockito.when(messagesClient.create(any(MessageCreateParams.class))).thenReturn(message);
        Flowable<LlmResponse> flowable = claudeWithMaxTokens.generateContent(llmRequest, false);
        Assertions.assertEquals("Max token check", flowable.blockingFirst().content().get().parts().get().get(0).text().get());
    }
    @Test
    @Tag("integration")
    public void testGenerateContentWithMultiPartSystemInstruction() {
        Part systemPart1 = Part.builder().text("Sys line 1").build();
        Part systemPart2 = Part.builder().text("Sys line 2").build();
        Content systemContent = Content.builder().role("system").parts(ImmutableList.of(systemPart1, systemPart2)).build();
        GenerateContentConfig config = Mockito.mock(GenerateContentConfig.class);
        Mockito.when(config.systemInstruction()).thenReturn(Optional.of(systemContent));
        Content content = Content.builder().role("user").parts(ImmutableList.of(Part.builder().text("User Text").build())).build();
        LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(content)).config(Optional.of(config)).build();
        Message message = Mockito.mock(Message.class);
        ContentBlock contentBlock = Mockito.mock(ContentBlock.class);
        Mockito.when(contentBlock.text()).thenReturn(Optional.of("User Text"));
        Mockito.when(message.content()).thenReturn(ImmutableList.of(contentBlock));
        Mockito.when(messagesClient.create(any(MessageCreateParams.class))).thenReturn(message);
        Flowable<LlmResponse> flowable = claude.generateContent(llmRequest, false);
        Assertions.assertEquals("User Text", flowable.blockingFirst().content().get().parts().get().get(0).text().get());
    }
    @Test
    @Tag("invalid")
    public void testGenerateContentWithMissingMessageContent() {
        Content content = Content.builder().role("user").parts(ImmutableList.of(Part.builder().text("Test missing content").build())).build();
        LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(content)).build();
        Message message = Mockito.mock(Message.class);
        Mockito.when(message.content()).thenReturn(null);
        Mockito.when(messagesClient.create(any(MessageCreateParams.class))).thenReturn(message);
        Flowable<LlmResponse> flowable = claude.generateContent(llmRequest, false);
        Assertions.assertTrue(flowable.blockingFirst().content().isEmpty() || !flowable.blockingFirst().content().get().parts().isPresent());
    }
    @Test
    @Tag("valid")
    public void testGenerateContentUsesDefaultModelWhenNoneProvided() {
        Content content = Content.builder().role("user").parts(ImmutableList.of(Part.builder().text("Default model").build())).build();
        LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(content)).model(Optional.empty()).build();
        Message message = Mockito.mock(Message.class);
        ContentBlock contentBlock = Mockito.mock(ContentBlock.class);
        Mockito.when(contentBlock.text()).thenReturn(Optional.of("Default model"));
        Mockito.when(message.content()).thenReturn(ImmutableList.of(contentBlock));
        Mockito.when(messagesClient.create(any(MessageCreateParams.class))).thenReturn(message);
        Flowable<LlmResponse> flowable = claude.generateContent(llmRequest, false);
        Assertions.assertEquals("Default model", flowable.blockingFirst().content().get().parts().get().get(0).text().get());
    }
    @Test
    @Tag("valid")
    public void testGenerateContentWithAbsentConfig() {
        Content content = Content.builder().role("user").parts(ImmutableList.of(Part.builder().text("No config present").build())).build();
        LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(content)).config(Optional.empty()).build();
        Message message = Mockito.mock(Message.class);
        ContentBlock contentBlock = Mockito.mock(ContentBlock.class);
        Mockito.when(contentBlock.text()).thenReturn(Optional.of("No config present"));
        Mockito.when(message.content()).thenReturn(ImmutableList.of(contentBlock));
        Mockito.when(messagesClient.create(any(MessageCreateParams.class))).thenReturn(message);
        Flowable<LlmResponse> flowable = claude.generateContent(llmRequest, false);
        Assertions.assertEquals("No config present", flowable.blockingFirst().content().get().parts().get().get(0).text().get());
    }
    @Test
    @Tag("valid")
    public void testGenerateContentWithStreamTrue() {
        Content content = Content.builder().role("user").parts(ImmutableList.of(Part.builder().text("Streaming test").build())).build();
        LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(content)).build();
        Message message = Mockito.mock(Message.class);
        ContentBlock contentBlock = Mockito.mock(ContentBlock.class);
        Mockito.when(contentBlock.text()).thenReturn(Optional.of("Streaming test"));
        Mockito.when(message.content()).thenReturn(ImmutableList.of(contentBlock));
        Mockito.when(messagesClient.create(any(MessageCreateParams.class))).thenReturn(message);
        Flowable<LlmResponse> flowable = claude.generateContent(llmRequest, true);
        Assertions.assertEquals("Streaming test", flowable.blockingFirst().content().get().parts().get().get(0).text().get());
    }
    @Test
    @Tag("valid")
    public void testGenerateContentWithStreamFalse() {
        Content content = Content.builder().role("user").parts(ImmutableList.of(Part.builder().text("Static test").build())).build();
        LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(content)).build();
        Message message = Mockito.mock(Message.class);
        ContentBlock contentBlock = Mockito.mock(ContentBlock.class);
        Mockito.when(contentBlock.text()).thenReturn(Optional.of("Static test"));
        Mockito.when(message.content()).thenReturn(ImmutableList.of(contentBlock));
        Mockito.when(messagesClient.create(any(MessageCreateParams.class))).thenReturn(message);
        Flowable<LlmResponse> flowable = claude.generateContent(llmRequest, false);
        Assertions.assertEquals("Static test", flowable.blockingFirst().content().get().parts().get().get(0).text().get());
    }
    @Test
    @Tag("invalid")
    public void testGenerateContentHandlesMessageParamConversionException() {
        Content content = Content.builder().role("user").parts(ImmutableList.of(Part.builder().build())).build();
        LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(content)).build();
        Mockito.when(messagesClient.create(any(MessageCreateParams.class))).thenThrow(new UnsupportedOperationException("Unsupported part"));
        Assertions.assertThrows(UnsupportedOperationException.class, () -> claude.generateContent(llmRequest, false).blockingFirst());
    }
    @Test
    @Tag("invalid")
    public void testGenerateContentWithIncompleteFunctionDeclaration() {
        FunctionDeclaration incompleteDecl = Mockito.mock(FunctionDeclaration.class);
        Mockito.when(incompleteDecl.name()).thenReturn(Optional.empty());
        GenerateContentConfig.ToolsConfig toolsConfig = Mockito.mock(GenerateContentConfig.ToolsConfig.class);
        Mockito.when(toolsConfig.functionDeclarations()).thenReturn(Optional.of(ImmutableList.of(incompleteDecl)));
        GenerateContentConfig config = Mockito.mock(GenerateContentConfig.class);
        Mockito.when(config.tools()).thenReturn(Optional.of(ImmutableList.of(toolsConfig)));
        Content content = Content.builder().role("user").parts(ImmutableList.of(Part.builder().text("Incomplete funcDecl").build())).build();
        LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(content)).config(Optional.of(config)).build();
        Mockito.when(messagesClient.create(any(MessageCreateParams.class))).thenThrow(new UnsupportedOperationException("FunctionDeclaration incomplete"));
        Assertions.assertThrows(UnsupportedOperationException.class, () -> claude.generateContent(llmRequest, false).blockingFirst());
    }
    @Test
    @Tag("boundary")
    public void testGenerateContentIgnoresNullTextsInSystemInstruction() {
        Part partWithText = Part.builder().text("part-text-valid").build();
        Part partWithoutText = Part.builder().build();
        Content systemContent = Content.builder().role("system").parts(ImmutableList.of(partWithText, partWithoutText)).build();
        GenerateContentConfig config = Mockito.mock(GenerateContentConfig.class);
        Mockito.when(config.systemInstruction()).thenReturn(Optional.of(systemContent));
        Content content = Content.builder().role("user").parts(ImmutableList.of(Part.builder().text("ignore nulls").build())).build();
        LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(content)).config(Optional.of(config)).build();
        Message message = Mockito.mock(Message.class);
        ContentBlock contentBlock = Mockito.mock(ContentBlock.class);
        Mockito.when(contentBlock.text()).thenReturn(Optional.of("ignore nulls"));
        Mockito.when(message.content()).thenReturn(ImmutableList.of(contentBlock));
        Mockito.when(messagesClient.create(any(MessageCreateParams.class))).thenReturn(message);
        Flowable<LlmResponse> flowable = claude.generateContent(llmRequest, false);
        LlmResponse response = flowable.blockingFirst();
        Assertions.assertEquals("ignore nulls", response.content().get().parts().get().get(0).text().get());
    }
    @Test
    @Tag("valid")
    public void testGenerateContentWithNullToolChoice() {
        Content content = Content.builder().role("user").parts(ImmutableList.of(Part.builder().text("Null toolChoice case").build())).build();
        LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(content)).tools(ImmutableMap.of()).build();
        Message message = Mockito.mock(Message.class);
        ContentBlock contentBlock = Mockito.mock(ContentBlock.class);
        Mockito.when(contentBlock.text()).thenReturn(Optional.of("Null toolChoice case"));
        Mockito.when(message.content()).thenReturn(ImmutableList.of(contentBlock));
        Mockito.when(messagesClient.create(any(MessageCreateParams.class))).thenReturn(message);
        Flowable<LlmResponse> flowable = claude.generateContent(llmRequest, false);
        LlmResponse response = flowable.blockingFirst();
        Assertions.assertEquals("Null toolChoice case", response.content().get().parts().get().get(0).text().get());
    }
    @Test
    @Tag("boundary")
    public void testGenerateContentWithLargeContentList() {
        List<Content> contents = new ArrayList<>();
        for (int i = 0; i < 100; i++) {
            contents.add(Content.builder().role("user").parts(ImmutableList.of(Part.builder().text("Msg " + i).build())).build());
        }
        LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.copyOf(contents)).build();
        List<ContentBlock> blocks = new ArrayList<>();
        for (int i = 0; i < 100; i++) {
            ContentBlock cb = Mockito.mock(ContentBlock.class);
            Mockito.when(cb.text()).thenReturn(Optional.of("Msg " + i));
            blocks.add(cb);
        }
        Message message = Mockito.mock(Message.class);
        Mockito.when(message.content()).thenReturn(ImmutableList.copyOf(blocks));
        Mockito.when(messagesClient.create(any(MessageCreateParams.class))).thenReturn(message);
        Flowable<LlmResponse> flowable = claude.generateContent(llmRequest, false);
        List<Part> parts = flowable.blockingFirst().content().get().parts().get();
        for (int i = 0; i < 100; i++) {
            Assertions.assertEquals("Msg " + i, parts.get(i).text().get());
        }
    }
    @Test
    @Tag("integration")
    public void testGenerateContentWithToolsAndNestedProperties() {
        FunctionDeclaration fd = Mockito.mock(FunctionDeclaration.class);
        Mockito.when(fd.name()).thenReturn(Optional.of("nestedFunc"));
        // Simulation: Nested property (Mock only)
        GenerateContentConfig.ToolsConfig toolsConfig = Mockito.mock(GenerateContentConfig.ToolsConfig.class);
        Mockito.when(toolsConfig.functionDeclarations()).thenReturn(Optional.of(ImmutableList.of(fd)));
        GenerateContentConfig config = Mockito.mock(GenerateContentConfig.class);
        Mockito.when(config.tools()).thenReturn(Optional.of(ImmutableList.of(toolsConfig)));
        Content content = Content.builder().role("user").parts(ImmutableList.of(Part.builder().text("Nested properties").build())).build();
        LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(content)).config(Optional.of(config)).build();
        Message message = Mockito.mock(Message.class);
        ContentBlock contentBlock = Mockito.mock(ContentBlock.class);
        Mockito.when(contentBlock.text()).thenReturn(Optional.of("Nested properties"));
        Mockito.when(message.content()).thenReturn(ImmutableList.of(contentBlock));
        Mockito.when(messagesClient.create(any(MessageCreateParams.class))).thenReturn(message);
        Flowable<LlmResponse> flowable = claude.generateContent(llmRequest, false);
        Assertions.assertEquals("Nested properties", flowable.blockingFirst().content().get().parts().get().get(0).text().get());
    }
    @Test
    @Tag("valid")
    public void testGenerateContentWithToolsConfigLackingFunctionDeclarations() {
        GenerateContentConfig.ToolsConfig toolsConfig = Mockito.mock(GenerateContentConfig.ToolsConfig.class);
        Mockito.when(toolsConfig.functionDeclarations()).thenReturn(Optional.empty());
        GenerateContentConfig config = Mockito.mock(GenerateContentConfig.class);
        Mockito.when(config.tools()).thenReturn(Optional.of(ImmutableList.of(toolsConfig)));
        Content content = Content.builder().role("user").parts(ImmutableList.of(Part.builder().text("No funcDecl").build())).build();
        LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(content)).config(Optional.of(config)).build();
        Message message = Mockito.mock(Message.class);
        ContentBlock contentBlock = Mockito.mock(ContentBlock.class);
        Mockito.when(contentBlock.text()).thenReturn(Optional.of("No funcDecl"));
        Mockito.when(message.content()).thenReturn(ImmutableList.of(contentBlock));
        Mockito.when(messagesClient.create(any(MessageCreateParams.class))).thenReturn(message);
        Flowable<LlmResponse> flowable = claude.generateContent(llmRequest, false);
        Assertions.assertEquals("No funcDecl", flowable.blockingFirst().content().get().parts().get().get(0).text().get());
    }
    // Add more tests here if needed for future scenarios
}