/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Azure Open AI and AI Model gpt-5

ROOST_METHOD_HASH=close_4be23fe575
ROOST_METHOD_SIG_HASH=close_3eadcb718b

Scenario 1: Throws NullPointerException when throwable is null

Details:
  TestName: throwsNpeWhenThrowableIsNull
  Description: Verifies that calling close(Throwable) with a null argument immediately throws a NullPointerException with the expected message and does not alter connection state or the response stream.

Execution:
  Arrange: Set up a GeminiLlmConnection instance with a mocked Client that returns a controllable CompletableFuture for the AsyncSession. No subscribers are needed for this test.
  Act: Invoke close(null).
  Assert: Expect a NullPointerException to be thrown with the message "throwable cannot be null for close". Confirm that no further actions are taken (e.g., the underlying session future is not canceled, and no terminal event is emitted to the response stream).

Validation:
  This ensures the method enforces its precondition via Objects.requireNonNull and prevents invalid usage. It also confirms that the guard occurs before any state changes, preserving connection integrity when misuse occurs.

*/

// ********RoostGPT********

package com.google.adk.models;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;

import com.google.genai.AsyncSession;
import com.google.genai.Client;
import com.google.genai.types.LiveConnectConfig;
import io.reactivex.rxjava3.core.Flowable;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.atomic.AtomicBoolean;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.AdditionalAnswers;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class GeminiLlmConnectionClose692Test {

  @Test
  @Tag("invalid")
  public void throwsNpeWhenThrowableIsNull() {
    final Client client = Mockito.mock(Client.class, Mockito.RETURNS_DEEP_STUBS);
    final LiveConnectConfig connectConfig = Mockito.mock(LiveConnectConfig.class);
    final CompletableFuture<AsyncSession> sessionFuture = new CompletableFuture<>();
    Mockito.when(client.async.live.connect(Mockito.any(String.class), Mockito.eq(connectConfig)))
        .thenReturn(sessionFuture);
    final String modelName = "models/test-model"; // TODO change to target model name
    // used in your environment
    final GeminiLlmConnection connection =
        new GeminiLlmConnection(client, modelName, connectConfig);
    final AtomicBoolean completed = new AtomicBoolean(false);
    final AtomicBoolean errored = new AtomicBoolean(false);
    final Flowable<LlmResponse> stream = connection.receive();
    stream.subscribe(r -> {}, e -> errored.set(true), () -> completed.set(true));
    final NullPointerException npe =
        assertThrows(
            NullPointerException.class,
            () -> {
              connection.close(null);
            });
    assertEquals((String) "throwable cannot be null for close", (String) npe.getMessage());
    assertFalse((boolean) sessionFuture.isCancelled());
    assertFalse((boolean) completed.get());
    assertFalse((boolean) errored.get());
  }

  @Test
  @Tag("valid")
  public void closeWithErrorBeforeSessionCompletionCancelsFutureAndEmitsError() {
    final Client client = Mockito.mock(Client.class, Mockito.RETURNS_DEEP_STUBS);
    final LiveConnectConfig connectConfig = Mockito.mock(LiveConnectConfig.class);
    final CompletableFuture<AsyncSession> sessionFuture = new CompletableFuture<>();
    Mockito.when(client.async.live.connect(Mockito.any(String.class), Mockito.eq(connectConfig)))
        .thenReturn(sessionFuture);
    final String modelName = "models/test-model"; // TODO change to target model name
    // used in your environment
    final GeminiLlmConnection connection =
        new GeminiLlmConnection(client, modelName, connectConfig);
    final AtomicBoolean completed = new AtomicBoolean(false);
    final AtomicBoolean errored = new AtomicBoolean(false);
    final AtomicBoolean errorCountIncremented = new AtomicBoolean(false);
    connection
        .receive()
        .subscribe(
            r -> {},
            e -> {
              errored.set(true);
              if (!errorCountIncremented.get()) {
                errorCountIncremented.set(true);
              }
            },
            () -> completed.set(true));
    final RuntimeException closeError = new RuntimeException("closing error");
    connection.close(closeError);
    assertFalse((boolean) completed.get());
    assertEquals((boolean) true, (boolean) errored.get());
    assertEquals((boolean) true, (boolean) sessionFuture.isCancelled());
  }

  @Test
  @Tag("valid")
  public void closeWithErrorAfterSessionCompletionClosesSessionAndEmitsError() {
    final Client client = Mockito.mock(Client.class, Mockito.RETURNS_DEEP_STUBS);
    final LiveConnectConfig connectConfig = Mockito.mock(LiveConnectConfig.class);
    final AsyncSession asyncSession = Mockito.mock(AsyncSession.class);
    Mockito.when(asyncSession.receive(Mockito.any()))
        .thenAnswer(
            AdditionalAnswers.answersWithDelay(
                0, invocation -> CompletableFuture.completedFuture(null)));
    Mockito.when(asyncSession.close()).thenReturn(CompletableFuture.completedFuture(null));
    final CompletableFuture<AsyncSession> sessionFuture =
        CompletableFuture.completedFuture(asyncSession);
    Mockito.when(client.async.live.connect(Mockito.any(String.class), Mockito.eq(connectConfig)))
        .thenReturn(sessionFuture);
    final String modelName = "models/test-model"; // TODO change to target model name
    // used in your environment
    final GeminiLlmConnection connection =
        new GeminiLlmConnection(client, modelName, connectConfig);
    final AtomicBoolean completed = new AtomicBoolean(false);
    final AtomicBoolean errored = new AtomicBoolean(false);
    final Flowable<LlmResponse> stream = connection.receive();
    stream.subscribe(r -> {}, e -> errored.set(true), () -> completed.set(true));
    final IllegalStateException closeError = new IllegalStateException("error");
    connection.close(closeError);
    Mockito.verify(asyncSession, Mockito.times(1)).close();
    assertFalse((boolean) completed.get());
    assertEquals((boolean) true, (boolean) errored.get());
    assertEquals((boolean) false, (boolean) sessionFuture.isCancelled());
  }

  @Test
  @Tag("boundary")
  public void closeCalledTwiceDoesNotEmitDuplicateTerminalEventsOrReCancel() {
    final Client client = Mockito.mock(Client.class, Mockito.RETURNS_DEEP_STUBS);
    final LiveConnectConfig connectConfig = Mockito.mock(LiveConnectConfig.class);
    final CompletableFuture<AsyncSession> sessionFuture = new CompletableFuture<>();
    Mockito.when(client.async.live.connect(Mockito.any(String.class), Mockito.eq(connectConfig)))
        .thenReturn(sessionFuture);
    final String modelName = "models/test-model"; // TODO change to target model name
    // used in your environment
    final GeminiLlmConnection connection =
        new GeminiLlmConnection(client, modelName, connectConfig);
    final AtomicBoolean completed = new AtomicBoolean(false);
    final AtomicBoolean errored = new AtomicBoolean(false);
    final int[] errorCount = new int[] {0};
    connection
        .receive()
        .subscribe(
            r -> {},
            e -> {
              errored.set(true);
              errorCount[0] = errorCount[0] + 1;
            },
            () -> completed.set(true));
    final RuntimeException closeError1 = new RuntimeException("first close");
    connection.close(closeError1);
    final RuntimeException closeError2 = new RuntimeException("second close");
    connection.close(closeError2);
    assertEquals((boolean) true, (boolean) errored.get());
    assertEquals((int) 1, (int) errorCount[0]);
    assertEquals((boolean) true, (boolean) sessionFuture.isCancelled());
    assertFalse((boolean) completed.get());
  }
}
