/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Azure Open AI and AI Model gpt-5

ROOST_METHOD_HASH=sendHistory_705fa44cdb
ROOST_METHOD_SIG_HASH=sendHistory_4aed389686

Scenario 1: Successfully sends a non-empty conversation history

Details:
  TestName: sendHistoryWithNonEmptyHistoryCompletesSuccessfully
  Description: Verifies that calling sendHistory with a non-empty List<Content> delegates to the underlying AsyncSession.sendClientContent and that the returned Completable completes successfully.

Execution:
  Arrange: Set up a mock Client whose async.live.connect returns a successfully completed CompletableFuture<AsyncSession>. Stub the AsyncSession to ensure sendClientContent completes successfully (e.g., returns a completed future). Prepare a non-empty history list containing at least one Content built via Content.builder(). Instantiate GeminiLlmConnection with the mocked dependencies so its sessionFuture is already resolved with the mock AsyncSession.
  Act: Invoke sendHistory(history) and subscribe/block on the returned Completable to wait for completion.
  Assert: Confirm the Completable completes without error, and verify that AsyncSession.sendClientContent is invoked exactly once with a LiveSendClientContentParameters whose turns are the same history list.

Validation:
  The assertion verifies that sendHistory correctly transforms the input history into LiveSendClientContentParameters and delegates the actual send to the session. It confirms the success path works and that the method’s Completable reflects the success of the underlying send operation.


Scenario 2: Sends an empty conversation history

Details:
  TestName: sendHistoryWithEmptyHistorySendsEmptyTurnsAndCompletes
  Description: Ensures that an empty history list is accepted and forwarded as-is, resulting in a successful completion.

Execution:
  Arrange: Configure the connection as in Scenario 1 with a mock AsyncSession whose sendClientContent completes successfully. Prepare an empty List<Content>.
  Act: Call sendHistory(emptyHistory) and wait for the Completable to complete.
  Assert: Verify the Completable completes successfully and that AsyncSession.sendClientContent is called with parameters whose turns are an empty list.

Validation:
  This confirms the method does not enforce non-empty history and that it forwards empty turns to the server correctly, maintaining predictable behavior for callers that may send a “warm-up” or placeholder history.


Scenario 3: Null history is rejected by parameter construction

Details:
  TestName: sendHistoryWithNullHistoryThrowsAtBuildTime
  Description: Ensures that a null history argument results in an immediate failure because LiveSendClientContentParameters cannot be constructed with null turns.

Execution:
  Arrange: Create a GeminiLlmConnection with a ready AsyncSession as before. Prepare a null List<Content> reference for history.
  Act: Invoke sendHistory(null).
  Assert: Expect an immediate exception during parameter building (e.g., NullPointerException or an equivalent construction-time error), rather than a Completable being returned.

Validation:
  This demonstrates defensive behavior at the parameter construction step and clarifies to integrators that null collections are not allowed inputs for sendHistory.


Scenario 4: Uses the already established session

Details:
  TestName: sendHistoryWhenSessionFutureAlreadySucceededDelegatesToSendClientContent
  Description: Verifies that when the sessionFuture is already completed with a valid AsyncSession, sendHistory immediately delegates to session.sendClientContent.

Execution:
  Arrange: Build a GeminiLlmConnection with a sessionFuture already completed (mock AsyncSession), ensuring sendClientContent returns a successfully completed future. Create a small non-empty history.
  Act: Call sendHistory(history) and wait for completion.
  Assert: Ensure the Completable completes successfully and that sendClientContent is invoked without any additional connection attempts.

Validation:
  Confirms that the method correctly chains off an already successful connection and avoids unnecessary blocking or reconnection logic.


Scenario 5: Propagates connection failure when sessionFuture completes exceptionally

Details:
  TestName: sendHistoryWhenSessionFutureCompletesExceptionallyPropagatesError
  Description: Ensures that if the WebSocket connection attempt failed (sessionFuture completed exceptionally), the returned Completable from sendHistory terminates with the same error.

Execution:
  Arrange: Configure Client.async.live.connect to return a CompletableFuture that completes exceptionally (e.g., SocketException). Instantiate GeminiLlmConnection so its sessionFuture reflects the failure.
  Act: Invoke sendHistory(anyHistory) and subscribe to the Completable.
  Assert: Assert that the Completable terminates with the same exception cause that completed the sessionFuture exceptionally.

Validation:
  This verifies error propagation semantics: sendHistory’s Completable reflects upstream connection errors consistently, allowing callers to handle connection failures uniformly.


Scenario 6: Waits for session establishment and then succeeds

Details:
  TestName: sendHistoryWhenSessionFuturePendingThenSucceedsCompletesEventually
  Description: Validates that if the sessionFuture is not yet complete at invocation time, sendHistory waits until the session is available and then completes when sendClientContent succeeds.

Execution:
  Arrange: Create a GeminiLlmConnection where the sessionFuture completes after a short delay with a mock AsyncSession. Ensure sendClientContent returns a success. Prepare a non-empty history list.
  Act: Call sendHistory(history) immediately and then let the sessionFuture complete; wait on the Completable.
  Assert: Confirm that the Completable completes successfully and sendClientContent is called exactly once after the session is ready.

Validation:
  Confirms asynchronous correctness: the method handles pending connections by deferring the send until the session is established, preserving call ordering and delivery guarantees.


Scenario 7: Propagates failure from sendClientContent

Details:
  TestName: sendHistoryWhenSendClientContentFailsPropagatesError
  Description: Ensures that if AsyncSession.sendClientContent completes exceptionally, sendHistory’s Completable terminates with that error.

Execution:
  Arrange: Create a GeminiLlmConnection with a ready mock AsyncSession. Stub sendClientContent to return a CompletableFuture that completes exceptionally (e.g., IllegalStateException).
  Act: Invoke sendHistory(history) and await termination.
  Assert: Validate that the Completable errors with the same exception as produced by sendClientContent.

Validation:
  Confirms that failures from the underlying send operation are correctly surfaced to callers, enabling robust error handling at the call site.


Scenario 8: Called after close() before session establishment

Details:
  TestName: sendHistoryAfterCloseBeforeSessionEstablishedEmitsCancellation
  Description: Verifies behavior when sendHistory is invoked after close() has been called while the sessionFuture has not yet completed and was canceled by close.

Execution:
  Arrange: Instantiate GeminiLlmConnection with a sessionFuture that is not yet complete. Call close() immediately so the connection cancels the sessionFuture. Prepare a history list.
  Act: Invoke sendHistory(history) and subscribe to the Completable.
  Assert: Expect the Completable to terminate with a cancellation-related error (e.g., CancellationException) because the underlying sessionFuture was canceled.

Validation:
  Ensures that once the connection is closed prior to session establishment, further send attempts do not hang or succeed, but rather fail fast in a predictable, cancelation-driven manner.


Scenario 9: Called after close() with an already established session

Details:
  TestName: sendHistoryAfterCloseWithActiveSessionPropagatesSendError
  Description: Tests that if close() has been invoked after the session is established, a subsequent sendHistory call fails because the session is closed and cannot send.

Execution:
  Arrange: Create a GeminiLlmConnection with a ready mock AsyncSession. Call close() to close the connection and have the AsyncSession.close() invoked. Configure AsyncSession.sendClientContent to fail when called after close (e.g., return a failed future).
  Act: Invoke sendHistory(history) after close and subscribe.
  Assert: Verify the Completable terminates with an error (e.g., IllegalStateException) representing that sending on a closed session is not allowed.

Validation:
  Confirms that the connection’s closed state is respected and that attempts to send after closure are surfaced as errors to the caller.


Scenario 10: Multiple calls send independently and succeed

Details:
  TestName: multipleSendHistoryCallsAreIndependentlyCompletedAndDelegated
  Description: Ensures that multiple sequential calls to sendHistory result in separate sends, each completing successfully, without interfering with each other.

Execution:
  Arrange: Use a GeminiLlmConnection with a ready mock AsyncSession whose sendClientContent returns success for each call. Prepare two distinct non-empty history lists.
  Act: Call sendHistory(history1) and sendHistory(history2), subscribing to both Completables.
  Assert: Confirm both Completables complete successfully and that sendClientContent is invoked exactly twice, once per call, with each call receiving the corresponding history list in its parameters.

Validation:
  Verifies idempotent behavior across calls and that the method does not serialize or suppress subsequent sends inadvertently.


Scenario 11: Does not emit responses directly to receive() as a side-effect

Details:
  TestName: sendHistoryDoesNotEmitToResponseStreamDirectly
  Description: Ensures that invoking sendHistory does not itself publish any LlmResponse on the receive() Flowable; only server messages should produce responses.

Execution:
  Arrange: Create a GeminiLlmConnection with a ready mock AsyncSession. Subscribe to receive() using a test subscriber to collect emissions. Stub sendClientContent to succeed without triggering any simulated incoming server messages.
  Act: Call sendHistory(history) and wait for its Completable to complete.
  Assert: Verify that the receive() subscriber did not observe any LlmResponse emissions as a result of this send alone.

Validation:
  This confirms separation of concerns: sending history enqueues outbound content, while inbound responses appear only when the server sends messages (not as a synchronous side-effect of the send).


Scenario 12: Handles large history lists

Details:
  TestName: sendHistoryWithLargeHistoryListIsAcceptedAndDelegated
  Description: Ensures that a large List<Content> (e.g., hundreds of entries) is accepted and delegated without immediate client-side failure, completing successfully when the session send succeeds.

Execution:
  Arrange: Prepare a large List<Content> (constructed with Content.builder()) and a GeminiLlmConnection whose AsyncSession.sendClientContent returns success.
  Act: Invoke sendHistory(largeHistory) and await completion.
  Assert: Confirm the Completable completes successfully and that sendClientContent is invoked once with parameters that include the entire history list.

Validation:
  Validates that the method itself does not impose size-related constraints and that it forwards the entire history for sending, relying on downstream components to handle size limits if any.


Scenario 13: History containing a null element triggers validation failure downstream

Details:
  TestName: sendHistoryWithHistoryContainingNullEntryPropagatesValidationError
  Description: Verifies that if the history list contains a null Content element, the send fails with an error produced by the parameter builder or by AsyncSession.sendClientContent.

Execution:
  Arrange: Create a history list that includes at least one null alongside valid Content objects. Build a GeminiLlmConnection using a ready AsyncSession. Depending on the parameter builder’s behavior, expect either parameter construction to fail immediately or AsyncSession.sendClientContent to complete exceptionally.
  Act: Call sendHistory(historyWithNull) and subscribe to the Completable.
  Assert: Validate that the Completable terminates with an appropriate error (e.g., NullPointerException or IllegalArgumentException) indicating invalid input.

Validation:
  Confirms that invalid entries within the history are not silently accepted and that errors are surfaced to the caller rather than leading to undefined behavior.

*/

// ********RoostGPT********

package com.google.adk.models;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.RETURNS_DEEP_STUBS;
import static org.mockito.Mockito.argThat;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.google.common.collect.ImmutableList;
import com.google.genai.AsyncSession;
import com.google.genai.Client;
import com.google.genai.types.Content;
import com.google.genai.types.LiveConnectConfig;
import com.google.genai.types.LiveSendClientContentParameters;
import com.google.genai.types.Part;
import io.reactivex.rxjava3.core.Completable;
import io.reactivex.rxjava3.subscribers.TestSubscriber;
import java.net.SocketException;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.CancellationException;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Answers;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class GeminiLlmConnectionSendHistoryTest {

  @Mock(answer = Answers.RETURNS_DEEP_STUBS)
  private Client apiClient;

  @Mock private AsyncSession asyncSession;

  @Mock private LiveConnectConfig connectConfig;

  private static String modelName() {
    return "models/gemini-1.5-pro"; // TODO: change model name if needed
  }

  private static Content simpleContent() {
    // Build a minimal Content with an empty parts list
    return Content.builder().parts(ImmutableList.<Part>of()).build();
  }

  private static CompletableFuture<AsyncSession> readySessionFuture(AsyncSession session) {
    return CompletableFuture.completedFuture(session);
  }

  private static CompletableFuture<AsyncSession> failedSessionFuture(Throwable t) {
    CompletableFuture<AsyncSession> f = new CompletableFuture<>();
    f.completeExceptionally(t);
    return f;
  }

  private static CompletableFuture<AsyncSession> pendingSessionFuture() {
    return new CompletableFuture<>();
  }

  private GeminiLlmConnection newConnectionWithFuture(CompletableFuture<AsyncSession> future) {
    try {
      java.lang.reflect.Field asyncField = Client.class.getField("async");
      Object asyncObj = org.mockito.Mockito.mock(asyncField.getType(), RETURNS_DEEP_STUBS);
      java.lang.reflect.Field liveField = asyncField.getType().getField("live");
      Class<?> liveType = liveField.getType();
      Object liveMock =
          org.mockito.Mockito.mock(
              liveType,
              invocation -> {
                if ("connect".equals(invocation.getMethod().getName())) {
                  Object[] args = invocation.getArguments();
                  if (args != null
                      && args.length == 2
                      && (args[0] instanceof String)
                      && (args[1] instanceof LiveConnectConfig)) {
                    return future;
                  }
                }
                return org.mockito.Mockito.RETURNS_DEFAULTS.answer(invocation);
              });
      liveField.setAccessible(true);
      liveField.set(asyncObj, liveMock);
      asyncField.setAccessible(true);
      asyncField.set(apiClient, asyncObj);
    } catch (Exception e) {
      throw new RuntimeException(e);
    }
    when(asyncSession.receive(any())).thenReturn(CompletableFuture.completedFuture(null));
    when(asyncSession.close()).thenReturn(CompletableFuture.completedFuture(null));
    return new GeminiLlmConnection(apiClient, modelName(), connectConfig);
  }

  private static void awaitCompletable(Completable completable) {
    completable.<Object>toCompletionStage(null).toCompletableFuture().join();
  }

  @Test
  @Tag("valid")
  public void sendHistoryWithNonEmptyHistoryCompletesSuccessfully() {
    GeminiLlmConnection connection = newConnectionWithFuture(readySessionFuture(asyncSession));
    List<Content> history = ImmutableList.of(simpleContent());
    when(asyncSession.sendClientContent(any(LiveSendClientContentParameters.class)))
        .thenReturn(CompletableFuture.completedFuture(null));
    Completable c = connection.sendHistory(history);
    awaitCompletable(c);
    verify(asyncSession, times(1))
        .sendClientContent(
            argThat(
                params -> {
                  if (params == null) return false;
                  Optional<List<Content>> turns = (Optional<List<Content>>) params.turns();
                  return turns.isPresent() && history.equals(turns.get());
                }));
  }

  @Test
  @Tag("valid")
  public void sendHistoryWithEmptyHistorySendsEmptyTurnsAndCompletes() {
    GeminiLlmConnection connection = newConnectionWithFuture(readySessionFuture(asyncSession));
    List<Content> emptyHistory = ImmutableList.of();
    when(asyncSession.sendClientContent(any(LiveSendClientContentParameters.class)))
        .thenReturn(CompletableFuture.completedFuture(null));
    Completable c = connection.sendHistory(emptyHistory);
    awaitCompletable(c);
    verify(asyncSession, times(1))
        .sendClientContent(
            argThat(
                params -> {
                  if (params == null) return false;
                  Optional<List<Content>> turns = (Optional<List<Content>>) params.turns();
                  return !turns.isPresent() || turns.get().isEmpty();
                }));
  }

  @Test
  @Tag("invalid")
  public void sendHistoryWithNullHistoryThrowsAtBuildTime() {
    GeminiLlmConnection connection = newConnectionWithFuture(readySessionFuture(asyncSession));
    assertThrows(
        NullPointerException.class,
        () -> {
          connection.sendHistory(null);
        });
  }

  @Test
  @Tag("valid")
  public void sendHistoryWhenSessionFutureAlreadySucceededDelegatesToSendClientContent() {
    GeminiLlmConnection connection = newConnectionWithFuture(readySessionFuture(asyncSession));
    List<Content> history = ImmutableList.of(simpleContent());
    when(asyncSession.sendClientContent(any(LiveSendClientContentParameters.class)))
        .thenReturn(CompletableFuture.completedFuture(null));
    Completable c = connection.sendHistory(history);
    awaitCompletable(c);
    verify(asyncSession, times(1)).sendClientContent(any(LiveSendClientContentParameters.class));
  }

  @Test
  @Tag("invalid")
  public void sendHistoryWhenSessionFutureCompletesExceptionallyPropagatesError() {
    GeminiLlmConnection connection =
        newConnectionWithFuture(failedSessionFuture(new SocketException()));
    List<Content> history = ImmutableList.of(simpleContent());
    Completable c = connection.sendHistory(history);
    assertThrows(
        CompletionException.class,
        () -> {
          c.<Object>toCompletionStage(null).toCompletableFuture().join();
        });
  }

  @Test
  @Tag("valid")
  public void sendHistoryWhenSessionFuturePendingThenSucceedsCompletesEventually() {
    CompletableFuture<AsyncSession> pending = pendingSessionFuture();
    GeminiLlmConnection connection = newConnectionWithFuture(pending);
    List<Content> history = ImmutableList.of(simpleContent());
    when(asyncSession.sendClientContent(any(LiveSendClientContentParameters.class)))
        .thenReturn(CompletableFuture.completedFuture(null));
    Completable c = connection.sendHistory(history);
    pending.complete(asyncSession);
    awaitCompletable(c);
    verify(asyncSession, times(1)).sendClientContent(any(LiveSendClientContentParameters.class));
  }

  @Test
  @Tag("invalid")
  public void sendHistoryWhenSendClientContentFailsPropagatesError() {
    GeminiLlmConnection connection = newConnectionWithFuture(readySessionFuture(asyncSession));
    List<Content> history = ImmutableList.of(simpleContent());
    CompletableFuture<Void> failedSend = new CompletableFuture<>();
    failedSend.completeExceptionally(new IllegalStateException());
    when(asyncSession.sendClientContent(any(LiveSendClientContentParameters.class)))
        .thenReturn(failedSend);
    Completable c = connection.sendHistory(history);
    CompletionException ex =
        assertThrows(
            CompletionException.class,
            () -> {
              c.<Object>toCompletionStage(null).toCompletableFuture().join();
            });
    assertEquals(true, ((Throwable) ex.getCause()) instanceof IllegalStateException);
  }

  @Test
  @Tag("invalid")
  public void sendHistoryAfterCloseBeforeSessionEstablishedEmitsCancellation() {
    CompletableFuture<AsyncSession> pending = pendingSessionFuture();
    GeminiLlmConnection connection = newConnectionWithFuture(pending);
    connection.close();
    List<Content> history = ImmutableList.of(simpleContent());
    Completable c = connection.sendHistory(history);
    assertThrows(
        CancellationException.class,
        () -> {
          c.<Object>toCompletionStage(null).toCompletableFuture().join();
        });
  }

  @Test
  @Tag("invalid")
  public void sendHistoryAfterCloseWithActiveSessionPropagatesSendError() {
    GeminiLlmConnection connection = newConnectionWithFuture(readySessionFuture(asyncSession));
    when(asyncSession.close()).thenReturn(CompletableFuture.completedFuture(null));
    connection.close();
    List<Content> history = ImmutableList.of(simpleContent());
    CompletableFuture<Void> failedSend = new CompletableFuture<>();
    failedSend.completeExceptionally(new IllegalStateException());
    when(asyncSession.sendClientContent(any(LiveSendClientContentParameters.class)))
        .thenReturn(failedSend);
    Completable c = connection.sendHistory(history);
    assertThrows(
        CompletionException.class,
        () -> {
          c.<Object>toCompletionStage(null).toCompletableFuture().join();
        });
  }

  @Test
  @Tag("valid")
  public void multipleSendHistoryCallsAreIndependentlyCompletedAndDelegated() {
    GeminiLlmConnection connection = newConnectionWithFuture(readySessionFuture(asyncSession));
    List<Content> history1 = ImmutableList.of(simpleContent(), simpleContent());
    List<Content> history2 = ImmutableList.of(simpleContent());
    when(asyncSession.sendClientContent(any(LiveSendClientContentParameters.class)))
        .thenReturn(CompletableFuture.completedFuture(null));
    Completable c1 = connection.sendHistory(history1);
    Completable c2 = connection.sendHistory(history2);
    awaitCompletable(c1);
    awaitCompletable(c2);
    ArgumentCaptor<LiveSendClientContentParameters> captor =
        ArgumentCaptor.forClass(LiveSendClientContentParameters.class);
    verify(asyncSession, times(2)).sendClientContent(captor.capture());
    List<LiveSendClientContentParameters> paramsList = captor.getAllValues();
    Optional<List<Content>> turns0 = (Optional<List<Content>>) paramsList.get(0).turns();
    Optional<List<Content>> turns1 = (Optional<List<Content>>) paramsList.get(1).turns();
    assertEquals(history1, turns0.orElse(ImmutableList.of()));
    assertEquals(history2, turns1.orElse(ImmutableList.of()));
  }

  @Test
  @Tag("valid")
  public void sendHistoryDoesNotEmitToResponseStreamDirectly() {
    GeminiLlmConnection connection = newConnectionWithFuture(readySessionFuture(asyncSession));
    when(asyncSession.sendClientContent(any(LiveSendClientContentParameters.class)))
        .thenReturn(CompletableFuture.completedFuture(null));
    TestSubscriber<LlmResponse> subscriber = connection.receive().test();
    List<Content> history = ImmutableList.of(simpleContent());
    Completable c = connection.sendHistory(history);
    awaitCompletable(c);
    subscriber.assertNoValues();
  }

  @Test
  @Tag("boundary")
  public void sendHistoryWithLargeHistoryListIsAcceptedAndDelegated() {
    GeminiLlmConnection connection = newConnectionWithFuture(readySessionFuture(asyncSession));
    List<Content> largeHistory = new ArrayList<>();
    for (int i = 0; i < 500; i++) {
      largeHistory.add(simpleContent());
    }
    when(asyncSession.sendClientContent(any(LiveSendClientContentParameters.class)))
        .thenReturn(CompletableFuture.completedFuture(null));
    Completable c = connection.sendHistory(ImmutableList.copyOf(largeHistory));
    awaitCompletable(c);
    verify(asyncSession, times(1))
        .sendClientContent(
            argThat(
                params -> {
                  if (params == null) return false;
                  Optional<List<Content>> turns = (Optional<List<Content>>) params.turns();
                  int size = turns.map(List::size).orElse(0);
                  return size == 500;
                }));
  }

  @Test
  @Tag("invalid")
  public void sendHistoryWithHistoryContainingNullEntryPropagatesValidationError() {
    GeminiLlmConnection connection = newConnectionWithFuture(readySessionFuture(asyncSession));
    List<Content> historyWithNull = ImmutableList.of(simpleContent(), null);
    assertThrows(
        NullPointerException.class,
        () -> {
          connection.sendHistory(historyWithNull);
        });
  }
}
