/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Azure Open AI and AI Model gpt-5

ROOST_METHOD_HASH=sendContent_002f7a9a3a
ROOST_METHOD_SIG_HASH=sendContent_f9ade81376

Scenario 1: Null content argument should throw NullPointerException

Details:
  TestName: nullContentThrowsNullPointerException
  Description: Verifies that sendContent(Content) rejects a null Content argument by throwing a NullPointerException with the expected message, ensuring defensive programming and input validation.

Execution:
  Arrange: Prepare a GeminiLlmConnection instance with a pre-resolved sessionFuture and no special session behavior needed, since the call should fail before any session use.
  Act: Invoke sendContent(null).
  Assert: Assert that a NullPointerException is thrown and its message is exactly "content cannot be null".

Validation:
  The assertion verifies strict non-null contract enforcement for the content parameter. This is significant to prevent ambiguous runtime behavior and to fail fast on incorrect API usage.


Scenario 2: Content with no parts (Optional empty) routes to sendClientContent

Details:
  TestName: emptyPartsOptionalRoutesToClientContent
  Description: Ensures that when Content.parts() is Optional.empty(), extractFunctionResponses returns Optional.empty(), causing sendContent to invoke sendClientContentInternal with a single-turn list and turnComplete = true.

Execution:
  Arrange:
    - Create Content with parts() as Optional.empty().
    - Mock AsyncSession so that sendClientContent returns a successfully completed future.
    - Configure sessionFuture to complete with the mocked AsyncSession.
  Act: Call sendContent(content).
  Assert:
    - Verify AsyncSession.sendClientContent was called exactly once.
    - Capture LiveSendClientContentParameters and assert:
      - turns contains exactly the provided content (size 1, same instance).
      - turnComplete is true.
    - Assert the returned Completable completes successfully.

Validation:
  Confirms the fallback path for content lacking parts and the correct construction of LiveSendClientContentParameters, aligning with the method’s documented behavior.


Scenario 3: Content with an empty parts list (present but empty) routes to sendClientContent

Details:
  TestName: presentEmptyPartsListRoutesToClientContent
  Description: Validates that when Content.parts() is present but contains an empty list, extractFunctionResponses returns Optional.empty(), thus sendContent uses the client content path.

Execution:
  Arrange:
    - Build Content where parts() is present with an empty ImmutableList.
    - Mock AsyncSession.sendClientContent to succeed.
    - Provide a sessionFuture that resolves to the mocked AsyncSession.
  Act: Call sendContent(content).
  Assert:
    - sendClientContent invoked once with parameters having:
      - turns list containing the same content object.
      - turnComplete = true.
    - Returned Completable completes without error.

Validation:
  Ensures both “no parts optional” and “empty parts list” cases behave identically, safeguarding consistent routing logic.


Scenario 4: All parts are FunctionResponse routes to sendToolResponse

Details:
  TestName: allPartsFunctionResponsesRoutesToToolResponse
  Description: Confirms that when every Part in Content has a FunctionResponse, extractFunctionResponses returns a populated Optional and sendContent invokes sendToolResponseInternal.

Execution:
  Arrange:
    - Construct Content with multiple Part instances, each having a FunctionResponse present.
    - Mock AsyncSession.sendToolResponse to succeed.
    - sessionFuture completes with mocked AsyncSession.
  Act: Call sendContent(content).
  Assert:
    - sendToolResponse called once.
    - Capture LiveSendToolResponseParameters and assert:
      - functionResponses list size matches the parts count.
      - All FunctionResponse instances are exactly those from the content parts and in the same order.
    - Returned Completable completes successfully.

Validation:
  Verifies correct branching to the tool response path and faithful forwarding of all function responses, preserving order and integrity.


Scenario 5: Mixed parts (some FunctionResponse, some not) routes to sendClientContent

Details:
  TestName: mixedPartsRoutesToClientContent
  Description: Ensures that when only a subset of parts are FunctionResponse and others are not (e.g., text or functionCall), the method takes the client content path.

Execution:
  Arrange:
    - Create Content with multiple parts where at least one part lacks a FunctionResponse.
    - Mock AsyncSession.sendClientContent to return success.
    - Resolve sessionFuture with the mocked AsyncSession.
  Act: Call sendContent(content).
  Assert:
    - sendClientContent is called exactly once.
    - Parameters’ turns contain exactly the original content and turnComplete = true.
    - Completable completes successfully.

Validation:
  Confirms the “all-or-nothing” rule for routing to tool response; any non-FunctionResponse part forces client content sending.


Scenario 6: No FunctionResponse in any part routes to sendClientContent

Details:
  TestName: noFunctionResponsesRoutesToClientContent
  Description: If none of the parts contain FunctionResponse, the method must send client content.

Execution:
  Arrange:
    - Build Content containing parts with other types (e.g., functionCall or text), with functionResponse Optional.empty() for each.
    - Mock AsyncSession.sendClientContent to succeed.
    - Provide a sessionFuture resolved to the mocked AsyncSession.
  Act: Call sendContent(content).
  Assert:
    - Verify single invocation of sendClientContent.
    - Confirm parameters: turns has exactly the content; turnComplete = true.
    - Completable completes without error.

Validation:
  Ensures correct detection of absence of tool responses and appropriate default routing.


Scenario 7: sendClientContent Completable completes when AsyncSession.sendClientContent completes

Details:
  TestName: clientContentCompletesWhenSessionSendCompletes
  Description: Verifies that the Completable returned by sendContent completes successfully when the underlying AsyncSession.sendClientContent future completes successfully.

Execution:
  Arrange:
    - Prepare Content that routes to client content (e.g., empty parts).
    - Mock AsyncSession.sendClientContent to return a completed future.
    - sessionFuture completes with mocked AsyncSession.
  Act: Call sendContent(content) and subscribe to the Completable.
  Assert:
    - Assert subscription completes successfully and no errors are emitted.

Validation:
  Confirms correct propagation of completion from the underlying future into the RxJava Completable.


Scenario 8: sendToolResponse Completable completes when AsyncSession.sendToolResponse completes

Details:
  TestName: toolResponseCompletesWhenSessionSendCompletes
  Description: Ensures that when routing to tool response, the returned Completable completes successfully upon the successful completion of AsyncSession.sendToolResponse.

Execution:
  Arrange:
    - Prepare Content wherein every part has a FunctionResponse.
    - Mock AsyncSession.sendToolResponse to complete successfully.
    - sessionFuture completes with mocked AsyncSession.
  Act: Call sendContent(content) and subscribe to the Completable.
  Assert:
    - Assert the Completable completes successfully without errors.

Validation:
  Verifies completion propagation for the tool response path.


Scenario 9: sessionFuture completes exceptionally — client content path propagates error

Details:
  TestName: sessionFutureFailurePropagatesOnClientContentPath
  Description: Validates that if sessionFuture completes exceptionally, the Completable returned for the client content path terminates with the same error.

Execution:
  Arrange:
    - Create client-content-routing Content (e.g., empty parts).
    - Configure sessionFuture to complete exceptionally with a specific Throwable.
  Act: Call sendContent(content).
  Assert:
    - The returned Completable emits an error matching the sessionFuture failure (type/message).

Validation:
  Ensures robust error propagation from session establishment through to the caller, preventing silent failures.


Scenario 10: sessionFuture completes exceptionally — tool response path propagates error

Details:
  TestName: sessionFutureFailurePropagatesOnToolResponsePath
  Description: Confirms that if all parts are FunctionResponse but sessionFuture fails, the resulting Completable also signals the same error.

Execution:
  Arrange:
    - Build Content with only FunctionResponse parts.
    - Configure sessionFuture to complete exceptionally.
  Act: Call sendContent(content).
  Assert:
    - The Completable fails with the same exception thrown by sessionFuture.

Validation:
  Demonstrates consistent error propagation, regardless of routing branch.


Scenario 11: AsyncSession.sendClientContent completes exceptionally — error propagates

Details:
  TestName: clientContentSendFailurePropagatesError
  Description: Ensures that when AsyncSession.sendClientContent returns a future that completes exceptionally, the sendContent Completable emits the same error.

Execution:
  Arrange:
    - Create Content that routes to client content.
    - Mock AsyncSession.sendClientContent to return a future completed exceptionally.
    - sessionFuture completes with mocked AsyncSession.
  Act: Call sendContent(content).
  Assert:
    - The Completable errors with the exception provided by sendClientContent.

Validation:
  Confirms that downstream send failures are surfaced to the caller for proper handling/retries.


Scenario 12: AsyncSession.sendToolResponse completes exceptionally — error propagates

Details:
  TestName: toolResponseSendFailurePropagatesError
  Description: Validates that failures occurring in AsyncSession.sendToolResponse are propagated through the returned Completable to the caller.

Execution:
  Arrange:
    - Construct Content with only FunctionResponse parts.
    - Mock AsyncSession.sendToolResponse to return an exceptionally completed future.
    - sessionFuture completes with mocked AsyncSession.
  Act: Call sendContent(content).
  Assert:
    - The Completable emits the same error as the failing future.

Validation:
  Ensures error visibility for the tool response path.


Scenario 13: Cancellation of underlying future is propagated to Completable subscriber

Details:
  TestName: cancellationIsPropagatedToCompletable
  Description: Checks that if the underlying composed future (sessionFuture.thenCompose(...)) becomes cancelled, the returned Completable reflects this cancellation as an error/termination consistent with RxJava Completable semantics.

Execution:
  Arrange:
    - Use Content that routes to either path (client content or tool response).
    - Arrange mocks so that the composed future is cancelled (e.g., cancel returned future).
  Act: Call sendContent(content).
  Assert:
    - The Completable terminates with a cancellation signal (e.g., CancellationException propagated).

Validation:
  Confirms correct propagation of cancellation semantics, crucial for cooperative cancellation and resource cleanup.


Scenario 14: Client content parameters include the exact content and set turnComplete = true

Details:
  TestName: clientContentParametersContainOriginalContentAndTurnCompleteTrue
  Description: Verifies the exact parameter construction for the client content path, particularly that the original Content instance is wrapped in a single-element turns list and turnComplete is true.

Execution:
  Arrange:
    - Create Content that routes to client content.
    - Mock AsyncSession to capture LiveSendClientContentParameters.
  Act: Invoke sendContent(content).
  Assert:
    - Captured parameters’ turns.size() == 1.
    - turns.get(0) is the same Content instance passed in.
    - turnComplete is true.

Validation:
  Ensures no unintended transformation of input and adherence to the “turn complete” contract.


Scenario 15: Tool response parameters contain all FunctionResponse parts in the original order

Details:
  TestName: toolResponseParametersPreserveOrderAndContents
  Description: Asserts that LiveSendToolResponseParameters.functionResponses contains exactly all FunctionResponse instances from the content parts and preserves their order.

Execution:
  Arrange:
    - Create Content with multiple parts, each having a unique FunctionResponse that can be identified.
    - Mock AsyncSession to capture LiveSendToolResponseParameters.
  Act: Call sendContent(content).
  Assert:
    - The captured functionResponses list length equals the number of parts.
    - Each element corresponds to the FunctionResponse of the part at the same index.

Validation:
  Guarantees that extraction is a faithful, ordered mapping from parts to parameters, critical for tools expecting ordered responses.


Scenario 16: Multiple consecutive calls with different content route independently

Details:
  TestName: multipleCallsRouteIndependentlyByContent
  Description: Ensures that calling sendContent multiple times with varying content (one with tool responses, one without) routes each call to the appropriate internal send method and completes accordingly.

Execution:
  Arrange:
    - Create contentA with all FunctionResponse parts.
    - Create contentB with no FunctionResponse parts.
    - Mock AsyncSession so both sendToolResponse and sendClientContent succeed.
    - sessionFuture completes with the mocked session.
  Act: Call sendContent(contentA), then call sendContent(contentB).
  Assert:
    - First call triggers sendToolResponse once; second call triggers sendClientContent once.
    - Both returned Completables complete successfully.

Validation:
  Verifies stateless, per-invocation routing logic without cross-call interference.


Scenario 17: Calling sendContent after connection is closed and session not yet established propagates cancellation/error

Details:
  TestName: sendAfterCloseBeforeSessionEstablishedPropagatesError
  Description: If close() is invoked before sessionFuture completes, the connection cancels the sessionFuture. A subsequent sendContent should surface a cancellation/error when composing against the cancelled sessionFuture.

Execution:
  Arrange:
    - Construct GeminiLlmConnection so that sessionFuture is not immediately resolved.
    - Call close() to trigger cancellation of session initialization.
    - Prepare content that routes to client content (or tool response).
  Act: Call sendContent(content).
  Assert:
    - The returned Completable emits a cancellation/error consistent with the cancelled sessionFuture.

Validation:
  Confirms that lifecycle operations (close) impact subsequent sends as expected by surfacing errors rather than silently failing.


Scenario 18: Large number of FunctionResponse parts forwarded correctly

Details:
  TestName: manyFunctionResponsesAreAllForwarded
  Description: Tests scalability and correctness by using a Content with a large list of FunctionResponse parts and verifying that all are forwarded without truncation or reordering.

Execution:
  Arrange:
    - Build Content with many Part instances, each having a distinct FunctionResponse.
    - Mock AsyncSession to capture parameters and succeed.
  Act: Call sendContent(content).
  Assert:
    - Captured functionResponses size equals the number of parts.
    - All FunctionResponse instances match exactly and are in the same order.
    - Completable completes successfully.

Validation:
  Ensures robustness under larger payloads and preserves data integrity.


Scenario 19: Parts Optional present but contains some parts with functionResponse absent leads to client content path

Details:
  TestName: presentPartsWithMissingFunctionResponsesRoutesToClientContent
  Description: Confirms that if parts() Optional is present and the list is non-empty but at least one part has functionResponse Optional.empty(), the method routes to client content.

Execution:
  Arrange:
    - Create Content with multiple parts where one or more parts return Optional.empty() for functionResponse.
    - Mock AsyncSession.sendClientContent to succeed.
  Act: Call sendContent(content).
  Assert:
    - sendClientContent invoked once with turns containing the content and turnComplete = true.
    - Completable completes successfully.

Validation:
  Reinforces the strict requirement that all parts must be FunctionResponse to use the tool response path.


Scenario 20: Ensures only one internal path is taken per invocation

Details:
  TestName: exactlyOneInternalSendMethodInvokedPerCall
  Description: Validates that for a single call to sendContent, exactly one of sendClientContent or sendToolResponse is invoked, ensuring no duplicate sends.

Execution:
  Arrange:
    - Prepare two variants of Content: one for client content routing, another for tool response routing.
    - Mock AsyncSession with verifiable interactions for both send methods.
  Act: Call sendContent(contentForClient) once; Call sendContent(contentForTool) once.
  Assert:
    - For the first call, sendClientContent invoked once, sendToolResponse not invoked.
    - For the second call, sendToolResponse invoked once, sendClientContent not invoked.
    - Both Completables complete successfully.

Validation:
  Confirms exclusive branching and prevents duplicate network calls per invocation, which is important for correctness and performance.

*/

// ********RoostGPT********

package com.google.adk.models;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

import com.google.common.collect.ImmutableList;
import com.google.genai.AsyncSession;
import com.google.genai.Client;
import com.google.genai.types.Content;
import com.google.genai.types.FunctionCall;
import com.google.genai.types.FunctionResponse;
import com.google.genai.types.LiveConnectConfig;
import com.google.genai.types.LiveSendClientContentParameters;
import com.google.genai.types.LiveSendToolResponseParameters;
import com.google.genai.types.Part;
import io.reactivex.rxjava3.core.Completable;
import io.reactivex.rxjava3.observers.TestObserver;
import io.reactivex.rxjava3.processors.PublishProcessor;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.CancellationException;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.atomic.AtomicBoolean;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Answers;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class GeminiLlmConnectionSendContentTest {

  @Mock(answer = Answers.RETURNS_DEEP_STUBS)
  private Client mockClient;

  @Mock private AsyncSession mockSession;

  private LiveConnectConfig connectConfig;

  private String modelName;

  @BeforeEach
  public void setup() {
    connectConfig = LiveConnectConfig.builder().build();
    modelName = "test-model"; // TODO replace with a valid model name if needed
    // Default behaviors to avoid NPE during constructor setupReceiver
    when(mockSession.receive(any())).thenReturn(CompletableFuture.completedFuture(null));
    when(mockSession.close()).thenReturn(CompletableFuture.completedFuture(null));
    when(mockSession.sendClientContent(any())).thenReturn(CompletableFuture.completedFuture(null));
    when(mockSession.sendToolResponse(any())).thenReturn(CompletableFuture.completedFuture(null));
  }

  private static void setField(Object target, String fieldName, Object value) {
    try {
      Field f = target.getClass().getDeclaredField(fieldName);
      f.setAccessible(true);
      f.set(target, value);
    } catch (Exception e) {
      throw new RuntimeException(e);
    }
  }

  private GeminiLlmConnection newConnectionWithFuture(CompletableFuture<AsyncSession> future) {
    try {
      // Allocate without invoking constructor and inject fields directly.
      sun.misc.Unsafe unsafe;
      {
        Field theUnsafe = sun.misc.Unsafe.class.getDeclaredField("theUnsafe");
        theUnsafe.setAccessible(true);
        unsafe = (sun.misc.Unsafe) theUnsafe.get(null);
      }
      GeminiLlmConnection connection =
          (GeminiLlmConnection) unsafe.allocateInstance(GeminiLlmConnection.class);
      setField(connection, "apiClient", mockClient);
      setField(connection, "modelName", modelName);
      setField(connection, "connectConfig", connectConfig);
      setField(connection, "sessionFuture", future);
      PublishProcessor<LlmResponse> processor = PublishProcessor.create();
      setField(connection, "responseProcessor", processor);
      setField(connection, "responseFlowable", processor.serialize());
      setField(connection, "closed", new AtomicBoolean(false));
      return connection;
    } catch (Throwable t) {
      throw new RuntimeException(t);
    }
  }

  private Content contentWithEmptyOptionalParts() {
    return Content.builder().build();
  }

  private Content contentWithEmptyPartsList() {
    return Content.builder().parts(ImmutableList.of()).build();
  }

  private Content contentWithFunctionResponses(List<FunctionResponse> responses) {
    List<Part> parts = new ArrayList<>();
    for (FunctionResponse response : responses) {
      parts.add(Part.builder().functionResponse(response).build());
    }
    return Content.builder().parts(ImmutableList.copyOf(parts)).build();
  }

  private Content contentWithMixedParts(FunctionResponse functionResponse) {
    Part pr1 = Part.builder().functionResponse(functionResponse).build();
    Part pr2 = Part.builder().functionCall(mock(FunctionCall.class)).build();
    return Content.builder().parts(ImmutableList.of(pr1, pr2)).build();
  }

  private Content contentWithNoFunctionResponses() {
    Part p1 = Part.builder().functionCall(mock(FunctionCall.class)).build();
    return Content.builder().parts(ImmutableList.of(p1)).build();
  }

  @Test
  @Tag("invalid")
  public void testNullContentThrowsNullPointerException() {
    CompletableFuture<AsyncSession> sessionFuture = CompletableFuture.completedFuture(mockSession);
    GeminiLlmConnection connection = newConnectionWithFuture(sessionFuture);
    NullPointerException ex =
        assertThrows(
            NullPointerException.class,
            () -> {
              connection.sendContent(null);
            });
    assertEquals("content cannot be null", (String) ex.getMessage());
  }

  @Test
  @Tag("valid")
  public void testEmptyPartsOptionalRoutesToClientContent() {
    CompletableFuture<AsyncSession> future = CompletableFuture.completedFuture(mockSession);
    GeminiLlmConnection connection = newConnectionWithFuture(future);
    Content content = contentWithEmptyOptionalParts();
    Completable completable = connection.sendContent(content);
    TestObserver<Void> observer = completable.test();
    observer.assertComplete();
    ArgumentCaptor<LiveSendClientContentParameters> captor =
        ArgumentCaptor.forClass(LiveSendClientContentParameters.class);
    verify(mockSession, times(1)).sendClientContent(captor.capture());
    LiveSendClientContentParameters params = captor.getValue();
    Optional<List<Content>> turnsOpt = params.turns();
    assertEquals(true, (Boolean) turnsOpt.isPresent());
    assertEquals(1, (int) turnsOpt.get().size());
    assertEquals(content, (Content) turnsOpt.get().get(0));
    Optional<Boolean> tc = params.turnComplete();
    assertEquals(true, (Boolean) tc.isPresent());
    assertEquals(true, (Boolean) tc.get());
  }

  @Test
  @Tag("valid")
  public void testPresentEmptyPartsListRoutesToClientContent() {
    CompletableFuture<AsyncSession> future = CompletableFuture.completedFuture(mockSession);
    GeminiLlmConnection connection = newConnectionWithFuture(future);
    Content content = contentWithEmptyPartsList();
    Completable completable = connection.sendContent(content);
    TestObserver<Void> observer = completable.test();
    observer.assertComplete();
    ArgumentCaptor<LiveSendClientContentParameters> captor =
        ArgumentCaptor.forClass(LiveSendClientContentParameters.class);
    verify(mockSession, times(1)).sendClientContent(captor.capture());
    LiveSendClientContentParameters params = captor.getValue();
    Optional<List<Content>> turnsOpt = params.turns();
    assertEquals(true, (Boolean) turnsOpt.isPresent());
    assertEquals(1, (int) turnsOpt.get().size());
    assertEquals(content, (Content) turnsOpt.get().get(0));
    Optional<Boolean> tc = params.turnComplete();
    assertEquals(true, (Boolean) tc.isPresent());
    assertEquals(true, (Boolean) tc.get());
  }

  @Test
  @Tag("valid")
  public void testAllPartsFunctionResponsesRoutesToToolResponse() {
    CompletableFuture<AsyncSession> future = CompletableFuture.completedFuture(mockSession);
    GeminiLlmConnection connection = newConnectionWithFuture(future);
    FunctionResponse fr1 = mock(FunctionResponse.class);
    FunctionResponse fr2 = mock(FunctionResponse.class);
    Content content = contentWithFunctionResponses(ImmutableList.of(fr1, fr2));
    Completable completable = connection.sendContent(content);
    TestObserver<Void> observer = completable.test();
    observer.assertComplete();
    ArgumentCaptor<LiveSendToolResponseParameters> captor =
        ArgumentCaptor.forClass(LiveSendToolResponseParameters.class);
    verify(mockSession, times(1)).sendToolResponse(captor.capture());
    LiveSendToolResponseParameters params = captor.getValue();
    Optional<List<FunctionResponse>> responsesOpt = params.functionResponses();
    assertEquals(true, (Boolean) responsesOpt.isPresent());
    List<FunctionResponse> responses = responsesOpt.get();
    assertEquals(2, (int) responses.size());
    assertEquals(fr1, (FunctionResponse) responses.get(0));
    assertEquals(fr2, (FunctionResponse) responses.get(1));
  }

  @Test
  @Tag("valid")
  public void testMixedPartsRoutesToClientContent() {
    CompletableFuture<AsyncSession> future = CompletableFuture.completedFuture(mockSession);
    GeminiLlmConnection connection = newConnectionWithFuture(future);
    FunctionResponse fr = mock(FunctionResponse.class);
    Content content = contentWithMixedParts(fr);
    Completable completable = connection.sendContent(content);
    TestObserver<Void> observer = completable.test();
    observer.assertComplete();
    ArgumentCaptor<LiveSendClientContentParameters> captor =
        ArgumentCaptor.forClass(LiveSendClientContentParameters.class);
    verify(mockSession, times(1)).sendClientContent(captor.capture());
    LiveSendClientContentParameters params = captor.getValue();
    Optional<List<Content>> turnsOpt = params.turns();
    assertEquals(true, (Boolean) turnsOpt.isPresent());
    assertEquals(1, (int) turnsOpt.get().size());
    assertEquals(content, (Content) turnsOpt.get().get(0));
    Optional<Boolean> tc = params.turnComplete();
    assertEquals(true, (Boolean) tc.isPresent());
    assertEquals(true, (Boolean) tc.get());
    verify(mockSession, times(0)).sendToolResponse(any());
  }

  @Test
  @Tag("valid")
  public void testNoFunctionResponsesRoutesToClientContent() {
    CompletableFuture<AsyncSession> future = CompletableFuture.completedFuture(mockSession);
    GeminiLlmConnection connection = newConnectionWithFuture(future);
    Content content = contentWithNoFunctionResponses();
    Completable completable = connection.sendContent(content);
    TestObserver<Void> observer = completable.test();
    observer.assertComplete();
    ArgumentCaptor<LiveSendClientContentParameters> captor =
        ArgumentCaptor.forClass(LiveSendClientContentParameters.class);
    verify(mockSession, times(1)).sendClientContent(captor.capture());
    LiveSendClientContentParameters params = captor.getValue();
    Optional<List<Content>> turnsOpt = params.turns();
    assertEquals(true, (Boolean) turnsOpt.isPresent());
    assertEquals(1, (int) turnsOpt.get().size());
    assertEquals(content, (Content) turnsOpt.get().get(0));
    Optional<Boolean> tc = params.turnComplete();
    assertEquals(true, (Boolean) tc.isPresent());
    assertEquals(true, (Boolean) tc.get());
    verify(mockSession, times(0)).sendToolResponse(any());
  }

  @Test
  @Tag("valid")
  public void testClientContentCompletesWhenSessionSendCompletes() {
    CompletableFuture<AsyncSession> future = CompletableFuture.completedFuture(mockSession);
    GeminiLlmConnection connection = newConnectionWithFuture(future);
    Content content = contentWithEmptyOptionalParts();
    when(mockSession.sendClientContent(any(LiveSendClientContentParameters.class)))
        .thenReturn(CompletableFuture.completedFuture(null));
    TestObserver<Void> observer = connection.sendContent(content).test();
    observer.assertComplete();
  }

  @Test
  @Tag("valid")
  public void testToolResponseCompletesWhenSessionSendCompletes() {
    CompletableFuture<AsyncSession> future = CompletableFuture.completedFuture(mockSession);
    GeminiLlmConnection connection = newConnectionWithFuture(future);
    FunctionResponse fr = mock(FunctionResponse.class);
    Content content = contentWithFunctionResponses(ImmutableList.of(fr));
    when(mockSession.sendToolResponse(any(LiveSendToolResponseParameters.class)))
        .thenReturn(CompletableFuture.completedFuture(null));
    TestObserver<Void> observer = connection.sendContent(content).test();
    observer.assertComplete();
  }

  @Test
  @Tag("invalid")
  public void testSessionFutureFailurePropagatesOnClientContentPath() {
    RuntimeException expected = new RuntimeException(); // TODO set message if needed
    CompletableFuture<AsyncSession> failed = new CompletableFuture<>();
    failed.completeExceptionally(expected);
    GeminiLlmConnection connection = newConnectionWithFuture(failed);
    Content content = contentWithEmptyOptionalParts();
    TestObserver<Void> observer = connection.sendContent(content).test();
    observer.assertError(throwable -> throwable == expected);
  }

  @Test
  @Tag("invalid")
  public void testSessionFutureFailurePropagatesOnToolResponsePath() {
    RuntimeException expected = new RuntimeException(); // TODO set message if needed
    CompletableFuture<AsyncSession> failed = new CompletableFuture<>();
    failed.completeExceptionally(expected);
    GeminiLlmConnection connection = newConnectionWithFuture(failed);
    FunctionResponse fr = mock(FunctionResponse.class);
    Content content = contentWithFunctionResponses(ImmutableList.of(fr));
    TestObserver<Void> observer = connection.sendContent(content).test();
    observer.assertError(throwable -> throwable == expected);
  }

  @Test
  @Tag("invalid")
  public void testClientContentSendFailurePropagatesError() {
    CompletableFuture<AsyncSession> future = CompletableFuture.completedFuture(mockSession);
    GeminiLlmConnection connection = newConnectionWithFuture(future);
    Content content = contentWithEmptyOptionalParts();
    RuntimeException expected = new RuntimeException(); // TODO set message if needed
    when(mockSession.sendClientContent(any(LiveSendClientContentParameters.class)))
        .thenReturn(CompletableFuture.failedFuture(expected));
    TestObserver<Void> observer = connection.sendContent(content).test();
    observer.assertError(throwable -> throwable == expected);
  }

  @Test
  @Tag("invalid")
  public void testToolResponseSendFailurePropagatesError() {
    CompletableFuture<AsyncSession> future = CompletableFuture.completedFuture(mockSession);
    GeminiLlmConnection connection = newConnectionWithFuture(future);
    FunctionResponse fr = mock(FunctionResponse.class);
    Content content = contentWithFunctionResponses(ImmutableList.of(fr));
    RuntimeException expected = new RuntimeException(); // TODO set message if needed
    when(mockSession.sendToolResponse(any(LiveSendToolResponseParameters.class)))
        .thenReturn(CompletableFuture.failedFuture(expected));
    TestObserver<Void> observer = connection.sendContent(content).test();
    observer.assertError(throwable -> throwable == expected);
  }

  @Test
  @Tag("boundary")
  public void testCancellationIsPropagatedToCompletable() {
    CompletableFuture<AsyncSession> cancelled = new CompletableFuture<>();
    cancelled.cancel(true);
    GeminiLlmConnection connection = newConnectionWithFuture(cancelled);
    Content content = contentWithEmptyOptionalParts();
    TestObserver<Void> observer = connection.sendContent(content).test();
    observer.assertError(throwable -> throwable instanceof CancellationException);
  }

  @Test
  @Tag("valid")
  public void testClientContentParametersContainOriginalContentAndTurnCompleteTrue() {
    CompletableFuture<AsyncSession> future = CompletableFuture.completedFuture(mockSession);
    GeminiLlmConnection connection = newConnectionWithFuture(future);
    Content original = contentWithEmptyOptionalParts();
    TestObserver<Void> observer = connection.sendContent(original).test();
    observer.assertComplete();
    ArgumentCaptor<LiveSendClientContentParameters> captor =
        ArgumentCaptor.forClass(LiveSendClientContentParameters.class);
    verify(mockSession, times(1)).sendClientContent(captor.capture());
    LiveSendClientContentParameters params = captor.getValue();
    Optional<List<Content>> turnsOpt = params.turns();
    assertEquals(true, (Boolean) turnsOpt.isPresent());
    assertEquals(1, (int) turnsOpt.get().size());
    assertEquals(original, (Content) turnsOpt.get().get(0));
    Optional<Boolean> tc = params.turnComplete();
    assertEquals(true, (Boolean) tc.isPresent());
    assertEquals(true, (Boolean) tc.get());
  }

  @Test
  @Tag("valid")
  public void testToolResponseParametersPreserveOrderAndContents() {
    CompletableFuture<AsyncSession> future = CompletableFuture.completedFuture(mockSession);
    GeminiLlmConnection connection = newConnectionWithFuture(future);
    FunctionResponse fr1 = mock(FunctionResponse.class);
    FunctionResponse fr2 = mock(FunctionResponse.class);
    FunctionResponse fr3 = mock(FunctionResponse.class);
    Content content = contentWithFunctionResponses(ImmutableList.of(fr1, fr2, fr3));
    TestObserver<Void> observer = connection.sendContent(content).test();
    observer.assertComplete();
    ArgumentCaptor<LiveSendToolResponseParameters> captor =
        ArgumentCaptor.forClass(LiveSendToolResponseParameters.class);
    verify(mockSession, times(1)).sendToolResponse(captor.capture());
    Optional<List<FunctionResponse>> opt = captor.getValue().functionResponses();
    assertEquals(true, (Boolean) opt.isPresent());
    List<FunctionResponse> responses = opt.get();
    assertEquals(3, (int) responses.size());
    assertEquals(fr1, (FunctionResponse) responses.get(0));
    assertEquals(fr2, (FunctionResponse) responses.get(1));
    assertEquals(fr3, (FunctionResponse) responses.get(2));
  }

  @Test
  @Tag("integration")
  public void testMultipleCallsRouteIndependentlyByContent() {
    CompletableFuture<AsyncSession> future = CompletableFuture.completedFuture(mockSession);
    GeminiLlmConnection connection = newConnectionWithFuture(future);
    FunctionResponse fr = mock(FunctionResponse.class);
    Content contentTool = contentWithFunctionResponses(ImmutableList.of(fr));
    Content contentClient = contentWithEmptyOptionalParts();
    TestObserver<Void> obs1 = connection.sendContent(contentTool).test();
    TestObserver<Void> obs2 = connection.sendContent(contentClient).test();
    obs1.assertComplete();
    obs2.assertComplete();
    verify(mockSession, times(1)).sendToolResponse(any(LiveSendToolResponseParameters.class));
    verify(mockSession, times(1)).sendClientContent(any(LiveSendClientContentParameters.class));
  }

  @Test
  @Tag("integration")
  public void testSendAfterCloseBeforeSessionEstablishedPropagatesError() {
    CompletableFuture<AsyncSession> future = new CompletableFuture<>();
    GeminiLlmConnection connection = newConnectionWithFuture(future);
    connection.close();
    Content content = contentWithEmptyOptionalParts();
    TestObserver<Void> observer = connection.sendContent(content).test();
    observer.assertError(throwable -> throwable instanceof CancellationException);
  }

  @Test
  @Tag("boundary")
  public void testManyFunctionResponsesAreAllForwarded() {
    CompletableFuture<AsyncSession> future = CompletableFuture.completedFuture(mockSession);
    GeminiLlmConnection connection = newConnectionWithFuture(future);
    int count = 50; // boundary size for test
    List<FunctionResponse> responses = new ArrayList<>();
    for (int i = 0; i < count; i++) {
      responses.add(mock(FunctionResponse.class));
    }
    Content content = contentWithFunctionResponses(responses);
    TestObserver<Void> observer = connection.sendContent(content).test();
    observer.assertComplete();
    ArgumentCaptor<LiveSendToolResponseParameters> captor =
        ArgumentCaptor.forClass(LiveSendToolResponseParameters.class);
    verify(mockSession, times(1)).sendToolResponse(captor.capture());
    Optional<List<FunctionResponse>> opt = captor.getValue().functionResponses();
    assertEquals(true, (Boolean) opt.isPresent());
    List<FunctionResponse> captured = opt.get();
    assertEquals(count, (int) captured.size());
    for (int i = 0; i < count; i++) {
      assertEquals(responses.get(i), (FunctionResponse) captured.get(i));
    }
  }

  @Test
  @Tag("valid")
  public void testPresentPartsWithMissingFunctionResponsesRoutesToClientContent() {
    CompletableFuture<AsyncSession> future = CompletableFuture.completedFuture(mockSession);
    GeminiLlmConnection connection = newConnectionWithFuture(future);
    FunctionResponse fr = mock(FunctionResponse.class);
    Part p1 = Part.builder().functionResponse(fr).build();
    Part p2 = Part.builder().functionCall(mock(FunctionCall.class)).build();
    Content content = Content.builder().parts(ImmutableList.of(p1, p2)).build();
    TestObserver<Void> observer = connection.sendContent(content).test();
    observer.assertComplete();
    verify(mockSession, times(1)).sendClientContent(any(LiveSendClientContentParameters.class));
    verify(mockSession, times(0)).sendToolResponse(any());
  }

  @Test
  @Tag("valid")
  public void testExactlyOneInternalSendMethodInvokedPerCall() {
    CompletableFuture<AsyncSession> future = CompletableFuture.completedFuture(mockSession);
    GeminiLlmConnection connection = newConnectionWithFuture(future);
    FunctionResponse fr = mock(FunctionResponse.class);
    Content contentForTool = contentWithFunctionResponses(ImmutableList.of(fr));
    Content contentForClient = contentWithEmptyOptionalParts();
    TestObserver<Void> o1 = connection.sendContent(contentForClient).test();
    TestObserver<Void> o2 = connection.sendContent(contentForTool).test();
    o1.assertComplete();
    o2.assertComplete();
    verify(mockSession, times(1)).sendClientContent(any(LiveSendClientContentParameters.class));
    verify(mockSession, times(0)).sendClientContent(argThat(params -> params == null)); // ensure
    // only
    // one
    // invocation
    verify(mockSession, times(1)).sendToolResponse(any(LiveSendToolResponseParameters.class));
    verify(mockSession, times(0)).sendToolResponse(argThat(params -> params == null)); // ensure
    // only
    // one
    // invocation
  }
}
