/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Azure Open AI and AI Model gpt-5

ROOST_METHOD_HASH=convertToServerResponse_ab43d27414
ROOST_METHOD_SIG_HASH=convertToServerResponse_6349e4b91b

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/unit-java-adk/1777891262/source/adk-java/core/src/test/java/com/google/adk/models/GeminiLlmConnectionTest.java
Tests:
    "@Test
public void convertToServerResponse_withInterruptedTrue_mapsInterruptedField() {
    LiveServerContent serverContent = LiveServerContent.builder().modelTurn(Content.fromParts(Part.fromText("Model response"))).turnComplete(false).interrupted(true).build();
    LiveServerMessage message = LiveServerMessage.builder().serverContent(serverContent).build();
    LlmResponse response = GeminiLlmConnection.convertToServerResponse(message).get();
    assertThat(response.content()).isPresent();
    assertThat(response.content().get().text()).isEqualTo("Model response");
    assertThat(response.partial()).hasValue(true);
    assertThat(response.turnComplete()).hasValue(false);
    assertThat(response.interrupted()).hasValue(true);
}
"
    "@Test
public void convertToServerResponse_withInterruptedFalse_mapsInterruptedField() {
    LiveServerContent serverContent = LiveServerContent.builder().modelTurn(Content.fromParts(Part.fromText("Continuing response"))).turnComplete(false).interrupted(false).build();
    LiveServerMessage message = LiveServerMessage.builder().serverContent(serverContent).build();
    LlmResponse response = GeminiLlmConnection.convertToServerResponse(message).get();
    assertThat(response.interrupted()).hasValue(false);
    assertThat(response.turnComplete()).hasValue(false);
}
"
    "@Test
public void convertToServerResponse_withoutInterruptedField_mapsEmptyOptional() {
    LiveServerContent serverContent = LiveServerContent.builder().modelTurn(Content.fromParts(Part.fromText("Normal response"))).turnComplete(true).build();
    LiveServerMessage message = LiveServerMessage.builder().serverContent(serverContent).build();
    LlmResponse response = GeminiLlmConnection.convertToServerResponse(message).get();
    assertThat(response.interrupted()).isEmpty();
    assertThat(response.turnComplete()).hasValue(true);
}
"
    "@Test
public void convertToServerResponse_withTurnCompleteTrue_mapsPartialFalse() {
    LiveServerContent serverContent = LiveServerContent.builder().modelTurn(Content.fromParts(Part.fromText("Final response"))).turnComplete(true).build();
    LiveServerMessage message = LiveServerMessage.builder().serverContent(serverContent).build();
    LlmResponse response = GeminiLlmConnection.convertToServerResponse(message).get();
    assertThat(response.partial()).hasValue(false);
    assertThat(response.turnComplete()).hasValue(true);
}
"
    "@Test
public void convertToServerResponse_withTurnCompleteFalse_mapsPartialTrue() {
    LiveServerContent serverContent = LiveServerContent.builder().modelTurn(Content.fromParts(Part.fromText("Partial response"))).turnComplete(false).build();
    LiveServerMessage message = LiveServerMessage.builder().serverContent(serverContent).build();
    LlmResponse response = GeminiLlmConnection.convertToServerResponse(message).get();
    assertThat(response.partial()).hasValue(true);
    assertThat(response.turnComplete()).hasValue(false);
}
"
    "@Test
public void convertToServerResponse_withToolCall_mapsContentWithFunctionCall() {
    FunctionCall functionCall = FunctionCall.builder().name("tool").build();
    LiveServerToolCall toolCall = LiveServerToolCall.builder().functionCalls(ImmutableList.of(functionCall)).build();
    LiveServerMessage message = LiveServerMessage.builder().toolCall(toolCall).build();
    LlmResponse response = GeminiLlmConnection.convertToServerResponse(message).get();
    assertThat(response.content()).isPresent();
    assertThat(response.content().get().parts()).isPresent();
    assertThat(response.content().get().parts().get()).hasSize(1);
    assertThat(response.content().get().parts().get().get(0).functionCall()).hasValue(functionCall);
    assertThat(response.partial()).hasValue(false);
    assertThat(response.turnComplete()).hasValue(false);
}
"
    "@Test
public void convertToServerResponse_withUsageMetadata_returnsEmptyOptional() {
    LiveServerMessage message = LiveServerMessage.builder().usageMetadata(UsageMetadata.builder().build()).build();
    assertThat(GeminiLlmConnection.convertToServerResponse(message)).isEmpty();
}
"
    "@Test
public void convertToServerResponse_withToolCallCancellation_returnsEmptyOptional() {
    LiveServerMessage message = LiveServerMessage.builder().toolCallCancellation(LiveServerToolCallCancellation.builder().build()).build();
    assertThat(GeminiLlmConnection.convertToServerResponse(message)).isEmpty();
}
"
    "@Test
public void convertToServerResponse_withSetupComplete_returnsEmptyOptional() {
    LiveServerMessage message = LiveServerMessage.builder().setupComplete(LiveServerSetupComplete.builder().build()).build();
    assertThat(GeminiLlmConnection.convertToServerResponse(message)).isEmpty();
}
"
    "@Test
public void convertToServerResponse_withUnknownMessage_returnsErrorResponse() {
    LiveServerMessage message = LiveServerMessage.builder().build();
    LlmResponse response = GeminiLlmConnection.convertToServerResponse(message).get();
    assertThat(response.errorCode()).isPresent();
    assertThat(response.errorMessage()).hasValue("Received unknown server message.");
}
"Scenario 1: Server content without modelTurn and turnComplete set to true

Details:
  TestName: noModelTurnWithTurnCompleteTrue_yieldsNoContentAndFinalFlags
  Description: Validates that when a LiveServerMessage contains serverContent with turnComplete explicitly set to true but no modelTurn content, the method returns a non-empty Optional with an LlmResponse that has no content, partial set to false, turnComplete set to true, and interrupted left as empty.

Execution:
  Arrange: Create a LiveServerContent with turnComplete(true) and no modelTurn; wrap it in a LiveServerMessage via LiveServerMessage.builder().serverContent(...).
  Act: Call GeminiLlmConnection.convertToServerResponse(message).
  Assert: Check that the Optional is present; verify that response.content() is empty; response.partial() is present and false; response.turnComplete() is present and true; response.interrupted() is empty; and no error fields are set.

Validation:
  Confirms default handling when no model output is provided but the turn is marked complete. Ensures flags are consistent with completed turns and that missing modelTurn does not introduce errors.

Scenario 2: Server content with neither modelTurn nor turnComplete

Details:
  TestName: noModelTurnAndNoTurnComplete_yieldsNoContentAndDefaultFlags
  Description: Ensures that if serverContent is present but both modelTurn and turnComplete are absent, the returned LlmResponse defaults to partial=false and turnComplete=false, with no content and no interrupted flag.

Execution:
  Arrange: Build LiveServerContent without modelTurn and without turnComplete; attach to a LiveServerMessage.
  Act: Invoke GeminiLlmConnection.convertToServerResponse(message).
  Assert: The Optional is present; response.content() is empty; response.partial() is present and false; response.turnComplete() is present and false; response.interrupted() is empty; no error fields are set.

Validation:
  Verifies the .orElse(false) defaults for partial and turnComplete when turnComplete is not provided, and that missing content does not cause errors.

Scenario 3: Server content with an empty modelTurn and turnComplete set to false

Details:
  TestName: emptyModelTurnPartsWithTurnIncomplete_yieldsContentPresentButNoParts
  Description: Tests that when modelTurn is provided but has no parts and turnComplete is false, the response retains content presence (reflecting the provided Content), partial is true, turnComplete is false, and interrupted remains empty.

Execution:
  Arrange: Construct Content with an empty parts list and use it as modelTurn in LiveServerContent with turnComplete(false); wrap in a LiveServerMessage.
  Act: Call GeminiLlmConnection.convertToServerResponse(message).
  Assert: Optional is present; response.content() is present but its parts are empty (if accessible); response.partial() is true; response.turnComplete() is false; response.interrupted() is empty; error fields are absent.

Validation:
  Ensures the method preserves provided content objects even if structurally empty, and correctly infers partial=true from turnComplete=false.

Scenario 4: Server content with turnComplete true and interrupted true

Details:
  TestName: turnCompleteTrueAndInterruptedTrue_setsConsistentFlags
  Description: Checks that when the turn is complete and interrupted is true, partial remains false, turnComplete is true, and interrupted is true, demonstrating independent handling of interrupted.

Execution:
  Arrange: Build LiveServerContent with modelTurn(Content), turnComplete(true), and interrupted(true); create a LiveServerMessage with this serverContent.
  Act: Execute GeminiLlmConnection.convertToServerResponse(message).
  Assert: Optional is present; response.partial() is false; response.turnComplete() is true; response.interrupted() is true; content is present; error fields are not set.

Validation:
  Validates that interrupted does not force partial behavior and is simply propagated, while partial correctly reflects the completed turn.

Scenario 5: Server content with turnComplete false and no interrupted field

Details:
  TestName: turnIncompleteWithoutInterrupted_setsPartialTrueAndNoInterrupted
  Description: Ensures that partial is set to true when turnComplete is false and that interrupted remains empty if not supplied.

Execution:
  Arrange: Create LiveServerContent with modelTurn(Content) and turnComplete(false) but omit interrupted; build the LiveServerMessage.
  Act: Call GeminiLlmConnection.convertToServerResponse(message).
  Assert: Optional is present; response.partial() is true; response.turnComplete() is false; response.interrupted() is empty; content is present; no error fields.

Validation:
  Confirms correct propagation of a missing interrupted flag and ensures partial is derived from the negation of turnComplete.

Scenario 6: Server content with modelTurn present and missing turnComplete

Details:
  TestName: modelTurnPresentWithoutTurnComplete_defaultsToPartialFalseAndTurnCompleteFalse
  Description: Verifies that when modelTurn is provided but turnComplete is omitted, partial defaults to false and turnComplete defaults to false, with content preserved.

Execution:
  Arrange: Build LiveServerContent with modelTurn(Content) and omit turnComplete; construct the LiveServerMessage.
  Act: Run GeminiLlmConnection.convertToServerResponse(message).
  Assert: Optional is present; response.content() is present; response.partial() is false; response.turnComplete() is false; response.interrupted() is empty unless provided; error fields are absent.

Validation:
  Ensures the .orElse(false) default behavior for partial/turnComplete when the completion flag is missing, while content remains intact.

Scenario 7: Server content does not set error fields

Details:
  TestName: serverContentProducesNoErrorFields
  Description: Confirms that when the serverContent path is taken (valid message), LlmResponse.errorCode and LlmResponse.errorMessage remain empty.

Execution:
  Arrange: Create a typical LiveServerContent with modelTurn and a defined turnComplete; wrap in LiveServerMessage.
  Act: Invoke GeminiLlmConnection.convertToServerResponse(message).
  Assert: Optional is present; errorCode() is empty; errorMessage() is empty.

Validation:
  Ensures that normal serverContent handling is treated as a success path without error annotations.

Scenario 8: Tool call with absent functionCalls optional

Details:
  TestName: toolCallWithoutFunctionCallsYieldsNoContentAndFalseFlags
  Description: Validates behavior when a LiveServerMessage contains toolCall but functionCalls() Optional is empty; the response should have no content and both partial and turnComplete set to false.

Execution:
  Arrange: Build LiveServerToolCall without functionCalls; attach to a LiveServerMessage via .toolCall(...).
  Act: Call GeminiLlmConnection.convertToServerResponse(message).
  Assert: Optional is present; response.content() is empty; response.partial() is false; response.turnComplete() is false; no error fields are set.

Validation:
  Confirms robustness when the toolCall exists but lacks functionCalls data, and that the method still returns a valid non-error response.

Scenario 9: Tool call with an empty functionCalls list

Details:
  TestName: toolCallWithEmptyFunctionCallsListYieldsNoContent
  Description: Ensures that if functionCalls is provided but the list is empty, the method produces a response without content, with partial=false and turnComplete=false.

Execution:
  Arrange: Build LiveServerToolCall with functionCalls(ImmutableList.of()) and wrap in LiveServerMessage.
  Act: Invoke GeminiLlmConnection.convertToServerResponse(message).
  Assert: Optional is present; response.content() is empty; response.partial() is false; response.turnComplete() is false; error fields are empty.

Validation:
  Verifies correct handling of empty collections within toolCall and that no invalid content is generated.

Scenario 10: Tool call with multiple functionCalls retains only the last call

Details:
  TestName: toolCallWithMultipleFunctionCallsRetainsLastCallInContent
  Description: Because the builder.content(...) is called in a loop, earlier contents are overwritten; this test checks that the content in the final LlmResponse contains only the last FunctionCall.

Execution:
  Arrange: Create two or more FunctionCall instances; build LiveServerToolCall with functionCalls including both; wrap in LiveServerMessage.
  Act: Call GeminiLlmConnection.convertToServerResponse(message).
  Assert: Optional is present; response.content() is present; the contained Part has functionCall equal to the last item in the provided list; partial=false; turnComplete=false.

Validation:
  Highlights the overwrite behavior in the loop and documents the current design choice, important for consumers expecting aggregation.

Scenario 11: Tool call does not set error fields

Details:
  TestName: toolCallProducesNoErrorFields
  Description: Checks that for toolCall-based responses (with any functionCalls condition), errorCode and errorMessage are not populated.

Execution:
  Arrange: Build a LiveServerToolCall with at least one FunctionCall; create a LiveServerMessage with this toolCall.
  Act: Execute GeminiLlmConnection.convertToServerResponse(message).
  Assert: Optional is present; errorCode() is empty; errorMessage() is empty.

Validation:
  Confirms toolCall path is a normal success case.

Scenario 12: Precedence when both serverContent and toolCall are present

Details:
  TestName: serverContentTakesPrecedenceOverToolCall
  Description: Ensures the method prioritizes serverContent over toolCall due to the if-else ordering, returning a response based solely on serverContent.

Execution:
  Arrange: Construct a LiveServerMessage where both serverContent (with modelTurn and turnComplete) and toolCall (with functionCalls) are present.
  Act: Call GeminiLlmConnection.convertToServerResponse(message).
  Assert: Optional is present; response reflects serverContent values (content, partial, turnComplete, interrupted) and does not reflect functionCall content.

Validation:
  Documents branch precedence, critical when multiple fields are populated in a single server message.

Scenario 13: Precedence when both toolCall and usageMetadata are present

Details:
  TestName: toolCallTakesPrecedenceOverUsageMetadata
  Description: Verifies that toolCall is evaluated before usageMetadata, yielding a non-empty Optional response rather than an empty Optional.

Execution:
  Arrange: Build LiveServerMessage with toolCall populated and usageMetadata also present.
  Act: Invoke GeminiLlmConnection.convertToServerResponse(message).
  Assert: Optional is present; response has partial=false and turnComplete=false; content present if functionCalls provided; error fields empty.

Validation:
  Ensures expected behavior when the server sends tool-related data alongside usage metadata; tool handling should not be suppressed by usage metadata.

Scenario 14: Precedence when usageMetadata and toolCallCancellation are both present

Details:
  TestName: usageMetadataPrecedesToolCallCancellationReturningEmpty
  Description: Confirms that usageMetadata is checked before toolCallCancellation, so the method returns Optional.empty() even if a cancellation is also present.

Execution:
  Arrange: Create a LiveServerMessage that includes both usageMetadata and toolCallCancellation but no serverContent or toolCall.
  Act: Call GeminiLlmConnection.convertToServerResponse(message).
  Assert: Optional is empty.

Validation:
  Records ordering between metadata and cancellation paths, important for understanding which non-content messages are surfaced or filtered.

Scenario 15: Multiple non-content flags present (usageMetadata, toolCallCancellation, setupComplete)

Details:
  TestName: usageMetadataDominatesWhenMultipleNonContentFlagsPresent
  Description: Tests a message that includes usageMetadata, toolCallCancellation, and setupComplete together; due to ordering, the method should return Optional.empty() via the usageMetadata branch.

Execution:
  Arrange: Build a LiveServerMessage containing all three: usageMetadata, toolCallCancellation, and setupComplete.
  Act: Invoke GeminiLlmConnection.convertToServerResponse(message).
  Assert: Optional is empty.

Validation:
  Captures branch dominance when several non-content indications coexist, ensuring deterministic behavior.

Scenario 16: Null input message

Details:
  TestName: nullMessageThrowsNullPointerException
  Description: Ensures defensive behavior when a null LiveServerMessage is passed, expecting a NullPointerException due to dereferencing calls like message.serverContent().

Execution:
  Arrange: Prepare a null reference for the LiveServerMessage.
  Act: Call GeminiLlmConnection.convertToServerResponse(null).
  Assert: Expect a NullPointerException to be thrown.

Validation:
  Documents method’s assumption that callers do not pass null and clarifies the resulting exception for robustness tests.

Scenario 17: Server content with modelTurn present and turnComplete missing

Details:
  TestName: modelTurnPresentTurnCompleteMissing_setsPartialFalseAndTurnCompleteFalse
  Description: Verifies that when modelTurn is provided but turnComplete is omitted, the response includes the content and defaults partial to false and turnComplete to false, with interrupted unchanged.

Execution:
  Arrange: Build LiveServerContent with modelTurn(Content) while omitting turnComplete and interrupted; create a LiveServerMessage.
  Act: Execute GeminiLlmConnection.convertToServerResponse(message).
  Assert: Optional is present; response.content() is present; response.partial() is false; response.turnComplete() is false; response.interrupted() is empty; error fields are not set.

Validation:
  Reinforces defaulting logic for completion flags while ensuring content propagation is unaffected.

Scenario 18: Server content with function-call style Content preserved

Details:
  TestName: modelTurnWithFunctionCallPartIsPreservedInContent
  Description: Ensures that if modelTurn Content contains a Part with a FunctionCall (not just text), the response carries that Complex Content unchanged.

Execution:
  Arrange: Construct Content whose parts include a Part with a FunctionCall; set as modelTurn in LiveServerContent with any turnComplete value; build a LiveServerMessage.
  Act: Call GeminiLlmConnection.convertToServerResponse(message).
  Assert: Optional is present; response.content() is present and includes the FunctionCall part; partial/turnComplete reflect the provided turnComplete; error fields are empty.

Validation:
  Confirms that the method forwards the provided modelTurn Content as-is, regardless of its internal composition (text or functionCall parts).


*/

// ********RoostGPT********

package com.google.adk.models;

import static org.junit.jupiter.api.Assertions.*;

import com.google.common.collect.ImmutableList;
import com.google.genai.types.Content;
import com.google.genai.types.FunctionCall;
import com.google.genai.types.GenerateContentResponseUsageMetadata;
import com.google.genai.types.LiveServerContent;
import com.google.genai.types.LiveServerMessage;
import com.google.genai.types.LiveServerToolCall;
import com.google.genai.types.LiveServerToolCallCancellation;
import com.google.genai.types.Part;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class GeminiLlmConnectionConvertToServerResponseTest {

  @Test
  @Tag("valid")
  public void noModelTurnWithTurnCompleteTrue_yieldsNoContentAndFinalFlags() {
    LiveServerMessage message = Mockito.mock(LiveServerMessage.class);
    LiveServerContent serverContent = Mockito.mock(LiveServerContent.class);
    Mockito.when(serverContent.modelTurn()).thenReturn(Optional.empty());
    Mockito.when(serverContent.turnComplete()).thenReturn(Optional.of(Boolean.TRUE));
    Mockito.when(serverContent.interrupted()).thenReturn(Optional.empty());
    Mockito.when(message.serverContent()).thenReturn(Optional.of(serverContent));
    Mockito.when(message.toolCall()).thenReturn(Optional.empty());
    Mockito.when(message.usageMetadata()).thenReturn(Optional.empty());
    Mockito.when(message.toolCallCancellation()).thenReturn(Optional.empty());
    Mockito.when(message.setupComplete()).thenReturn(Optional.empty());
    Mockito.when(message.toJson()).thenReturn("{}");
    Optional<LlmResponse> result = GeminiLlmConnection.convertToServerResponse(message);
    assertTrue(result.isPresent(), "Expected Optional to be present");
    LlmResponse response = result.get();
    assertTrue((Boolean) response.content().isEmpty(), "Expected no content");
    assertTrue((Boolean) response.partial().isPresent(), "Expected partial to be present");
    assertEquals(
        (Boolean) Boolean.FALSE, (Boolean) response.partial().get(), "Expected partial=false");
    assertTrue(
        (Boolean) response.turnComplete().isPresent(), "Expected turnComplete to be present");
    assertEquals(
        (Boolean) Boolean.TRUE,
        (Boolean) response.turnComplete().get(),
        "Expected turnComplete=true");
    assertTrue((Boolean) response.interrupted().isEmpty(), "Expected interrupted to be empty");
    assertTrue((Boolean) response.errorCode().isEmpty(), "Expected no errorCode");
    assertTrue((Boolean) response.errorMessage().isEmpty(), "Expected no errorMessage");
  }

  @Test
  @Tag("boundary")
  public void noModelTurnAndNoTurnComplete_yieldsNoContentAndDefaultFlags() {
    LiveServerMessage message = Mockito.mock(LiveServerMessage.class);
    LiveServerContent serverContent = Mockito.mock(LiveServerContent.class);
    Mockito.when(serverContent.modelTurn()).thenReturn(Optional.empty());
    Mockito.when(serverContent.turnComplete()).thenReturn(Optional.empty());
    Mockito.when(serverContent.interrupted()).thenReturn(Optional.empty());
    Mockito.when(message.serverContent()).thenReturn(Optional.of(serverContent));
    Mockito.when(message.toolCall()).thenReturn(Optional.empty());
    Mockito.when(message.usageMetadata()).thenReturn(Optional.empty());
    Mockito.when(message.toolCallCancellation()).thenReturn(Optional.empty());
    Mockito.when(message.setupComplete()).thenReturn(Optional.empty());
    Mockito.when(message.toJson()).thenReturn("{}");
    Optional<LlmResponse> result = GeminiLlmConnection.convertToServerResponse(message);
    assertTrue(result.isPresent(), "Expected Optional to be present");
    LlmResponse response = result.get();
    assertTrue((Boolean) response.content().isEmpty(), "Expected no content");
    assertTrue((Boolean) response.partial().isPresent(), "Expected partial present");
    assertEquals(
        (Boolean) Boolean.FALSE, (Boolean) response.partial().get(), "Expected partial=false");
    assertTrue((Boolean) response.turnComplete().isPresent(), "Expected turnComplete present");
    assertEquals(
        (Boolean) Boolean.FALSE,
        (Boolean) response.turnComplete().get(),
        "Expected turnComplete=false");
    assertTrue((Boolean) response.interrupted().isEmpty(), "Expected interrupted empty");
    assertTrue((Boolean) response.errorCode().isEmpty(), "Expected no errorCode");
    assertTrue((Boolean) response.errorMessage().isEmpty(), "Expected no errorMessage");
  }

  @Test
  @Tag("boundary")
  public void emptyModelTurnPartsWithTurnIncomplete_yieldsContentPresentButNoParts() {
    LiveServerMessage message = Mockito.mock(LiveServerMessage.class);
    LiveServerContent serverContent = Mockito.mock(LiveServerContent.class);
    Content emptyPartsContent = Content.builder().parts(ImmutableList.of()).build();
    Mockito.when(serverContent.modelTurn()).thenReturn(Optional.of(emptyPartsContent));
    Mockito.when(serverContent.turnComplete()).thenReturn(Optional.of(Boolean.FALSE));
    Mockito.when(serverContent.interrupted()).thenReturn(Optional.empty());
    Mockito.when(message.serverContent()).thenReturn(Optional.of(serverContent));
    Mockito.when(message.toolCall()).thenReturn(Optional.empty());
    Mockito.when(message.usageMetadata()).thenReturn(Optional.empty());
    Mockito.when(message.toolCallCancellation()).thenReturn(Optional.empty());
    Mockito.when(message.setupComplete()).thenReturn(Optional.empty());
    Mockito.when(message.toJson()).thenReturn("{}");
    Optional<LlmResponse> result = GeminiLlmConnection.convertToServerResponse(message);
    assertTrue(result.isPresent(), "Expected Optional to be present");
    LlmResponse response = result.get();
    assertTrue((Boolean) response.content().isPresent(), "Expected content present");
    Optional<List<Part>> partsOpt = response.content().get().parts();
    if (partsOpt.isPresent()) {
      assertEquals(0, (int) partsOpt.get().size(), "Expected content parts to be empty");
    }
    assertTrue((Boolean) response.partial().isPresent(), "Expected partial present");
    assertEquals(
        (Boolean) Boolean.TRUE, (Boolean) response.partial().get(), "Expected partial=true");
    assertTrue((Boolean) response.turnComplete().isPresent(), "Expected turnComplete present");
    assertEquals(
        (Boolean) Boolean.FALSE,
        (Boolean) response.turnComplete().get(),
        "Expected turnComplete=false");
    assertTrue((Boolean) response.interrupted().isEmpty(), "Expected interrupted empty");
    assertTrue((Boolean) response.errorCode().isEmpty(), "Expected no errorCode");
    assertTrue((Boolean) response.errorMessage().isEmpty(), "Expected no errorMessage");
  }

  @Test
  @Tag("valid")
  public void turnCompleteTrueAndInterruptedTrue_setsConsistentFlags() {
    LiveServerMessage message = Mockito.mock(LiveServerMessage.class);
    LiveServerContent serverContent = Mockito.mock(LiveServerContent.class);
    Content content = Content.builder().parts(ImmutableList.of()).build();
    Mockito.when(serverContent.modelTurn()).thenReturn(Optional.of(content));
    Mockito.when(serverContent.turnComplete()).thenReturn(Optional.of(Boolean.TRUE));
    Mockito.when(serverContent.interrupted()).thenReturn(Optional.of(Boolean.TRUE));
    Mockito.when(message.serverContent()).thenReturn(Optional.of(serverContent));
    Mockito.when(message.toolCall()).thenReturn(Optional.empty());
    Mockito.when(message.usageMetadata()).thenReturn(Optional.empty());
    Mockito.when(message.toolCallCancellation()).thenReturn(Optional.empty());
    Mockito.when(message.setupComplete()).thenReturn(Optional.empty());
    Mockito.when(message.toJson()).thenReturn("{}");
    Optional<LlmResponse> result = GeminiLlmConnection.convertToServerResponse(message);
    assertTrue(result.isPresent(), "Expected Optional present");
    LlmResponse response = result.get();
    assertTrue((Boolean) response.content().isPresent(), "Expected content present");
    assertTrue((Boolean) response.partial().isPresent(), "Expected partial present");
    assertEquals(
        (Boolean) Boolean.FALSE, (Boolean) response.partial().get(), "Expected partial=false");
    assertTrue((Boolean) response.turnComplete().isPresent(), "Expected turnComplete present");
    assertEquals(
        (Boolean) Boolean.TRUE,
        (Boolean) response.turnComplete().get(),
        "Expected turnComplete=true");
    assertTrue((Boolean) response.interrupted().isPresent(), "Expected interrupted present");
    assertEquals(
        (Boolean) Boolean.TRUE,
        (Boolean) response.interrupted().get(),
        "Expected interrupted=true");
    assertTrue((Boolean) response.errorCode().isEmpty(), "Expected no errorCode");
    assertTrue((Boolean) response.errorMessage().isEmpty(), "Expected no errorMessage");
  }

  @Test
  @Tag("valid")
  public void turnIncompleteWithoutInterrupted_setsPartialTrueAndNoInterrupted() {
    LiveServerMessage message = Mockito.mock(LiveServerMessage.class);
    LiveServerContent serverContent = Mockito.mock(LiveServerContent.class);
    Content content = Content.builder().parts(ImmutableList.of()).build();
    Mockito.when(serverContent.modelTurn()).thenReturn(Optional.of(content));
    Mockito.when(serverContent.turnComplete()).thenReturn(Optional.of(Boolean.FALSE));
    Mockito.when(serverContent.interrupted()).thenReturn(Optional.empty());
    Mockito.when(message.serverContent()).thenReturn(Optional.of(serverContent));
    Mockito.when(message.toolCall()).thenReturn(Optional.empty());
    Mockito.when(message.usageMetadata()).thenReturn(Optional.empty());
    Mockito.when(message.toolCallCancellation()).thenReturn(Optional.empty());
    Mockito.when(message.setupComplete()).thenReturn(Optional.empty());
    Mockito.when(message.toJson()).thenReturn("{}");
    Optional<LlmResponse> result = GeminiLlmConnection.convertToServerResponse(message);
    assertTrue(result.isPresent(), "Expected Optional present");
    LlmResponse response = result.get();
    assertTrue((Boolean) response.content().isPresent(), "Expected content present");
    assertTrue((Boolean) response.partial().isPresent(), "Expected partial present");
    assertEquals(
        (Boolean) Boolean.TRUE, (Boolean) response.partial().get(), "Expected partial=true");
    assertTrue((Boolean) response.turnComplete().isPresent(), "Expected turnComplete present");
    assertEquals(
        (Boolean) Boolean.FALSE,
        (Boolean) response.turnComplete().get(),
        "Expected turnComplete=false");
    assertTrue((Boolean) response.interrupted().isEmpty(), "Expected interrupted empty");
    assertTrue((Boolean) response.errorCode().isEmpty(), "Expected no errorCode");
    assertTrue((Boolean) response.errorMessage().isEmpty(), "Expected no errorMessage");
  }

  @Test
  @Tag("boundary")
  public void modelTurnPresentWithoutTurnComplete_defaultsToPartialFalseAndTurnCompleteFalse() {
    LiveServerMessage message = Mockito.mock(LiveServerMessage.class);
    LiveServerContent serverContent = Mockito.mock(LiveServerContent.class);
    Content content = Content.builder().parts(ImmutableList.of()).build();
    Mockito.when(serverContent.modelTurn()).thenReturn(Optional.of(content));
    Mockito.when(serverContent.turnComplete()).thenReturn(Optional.empty());
    Mockito.when(serverContent.interrupted()).thenReturn(Optional.empty());
    Mockito.when(message.serverContent()).thenReturn(Optional.of(serverContent));
    Mockito.when(message.toolCall()).thenReturn(Optional.empty());
    Mockito.when(message.usageMetadata()).thenReturn(Optional.empty());
    Mockito.when(message.toolCallCancellation()).thenReturn(Optional.empty());
    Mockito.when(message.setupComplete()).thenReturn(Optional.empty());
    Mockito.when(message.toJson()).thenReturn("{}");
    Optional<LlmResponse> result = GeminiLlmConnection.convertToServerResponse(message);
    assertTrue(result.isPresent(), "Expected Optional present");
    LlmResponse response = result.get();
    assertTrue((Boolean) response.content().isPresent(), "Expected content present");
    assertTrue((Boolean) response.partial().isPresent(), "Expected partial present");
    assertEquals(
        (Boolean) Boolean.FALSE, (Boolean) response.partial().get(), "Expected partial=false");
    assertTrue((Boolean) response.turnComplete().isPresent(), "Expected turnComplete present");
    assertEquals(
        (Boolean) Boolean.FALSE,
        (Boolean) response.turnComplete().get(),
        "Expected turnComplete=false");
    assertTrue((Boolean) response.interrupted().isEmpty(), "Expected interrupted empty");
    assertTrue((Boolean) response.errorCode().isEmpty(), "Expected no errorCode");
    assertTrue((Boolean) response.errorMessage().isEmpty(), "Expected no errorMessage");
  }

  @Test
  @Tag("valid")
  public void serverContentProducesNoErrorFields() {
    LiveServerMessage message = Mockito.mock(LiveServerMessage.class);
    LiveServerContent serverContent = Mockito.mock(LiveServerContent.class);
    Content content = Content.builder().parts(ImmutableList.of()).build();
    Mockito.when(serverContent.modelTurn()).thenReturn(Optional.of(content));
    Mockito.when(serverContent.turnComplete()).thenReturn(Optional.of(Boolean.TRUE));
    Mockito.when(serverContent.interrupted()).thenReturn(Optional.empty());
    Mockito.when(message.serverContent()).thenReturn(Optional.of(serverContent));
    Mockito.when(message.toolCall()).thenReturn(Optional.empty());
    Mockito.when(message.usageMetadata()).thenReturn(Optional.empty());
    Mockito.when(message.toolCallCancellation()).thenReturn(Optional.empty());
    Mockito.when(message.setupComplete()).thenReturn(Optional.empty());
    Mockito.when(message.toJson()).thenReturn("{}");
    Optional<LlmResponse> result = GeminiLlmConnection.convertToServerResponse(message);
    assertTrue(result.isPresent(), "Expected Optional present");
    LlmResponse response = result.get();
    assertTrue((Boolean) response.errorCode().isEmpty(), "Expected no errorCode");
    assertTrue((Boolean) response.errorMessage().isEmpty(), "Expected no errorMessage");
  }

  @Test
  @Tag("boundary")
  public void toolCallWithoutFunctionCallsYieldsNoContentAndFalseFlags() {
    LiveServerMessage message = Mockito.mock(LiveServerMessage.class);
    LiveServerToolCall toolCall = Mockito.mock(LiveServerToolCall.class);
    Mockito.when(toolCall.functionCalls()).thenReturn(Optional.empty());
    Mockito.when(message.serverContent()).thenReturn(Optional.empty());
    Mockito.when(message.toolCall()).thenReturn(Optional.of(toolCall));
    Mockito.when(message.usageMetadata()).thenReturn(Optional.empty());
    Mockito.when(message.toolCallCancellation()).thenReturn(Optional.empty());
    Mockito.when(message.setupComplete()).thenReturn(Optional.empty());
    Mockito.when(message.toJson()).thenReturn("{}");
    Optional<LlmResponse> result = GeminiLlmConnection.convertToServerResponse(message);
    assertTrue(result.isPresent(), "Expected Optional present");
    LlmResponse response = result.get();
    assertTrue((Boolean) response.content().isEmpty(), "Expected no content");
    assertTrue((Boolean) response.partial().isPresent(), "Expected partial present");
    assertEquals(
        (Boolean) Boolean.FALSE, (Boolean) response.partial().get(), "Expected partial=false");
    assertTrue((Boolean) response.turnComplete().isPresent(), "Expected turnComplete present");
    assertEquals(
        (Boolean) Boolean.FALSE,
        (Boolean) response.turnComplete().get(),
        "Expected turnComplete=false");
    assertTrue((Boolean) response.errorCode().isEmpty(), "Expected no errorCode");
    assertTrue((Boolean) response.errorMessage().isEmpty(), "Expected no errorMessage");
  }

  @Test
  @Tag("boundary")
  public void toolCallWithEmptyFunctionCallsListYieldsNoContent() {
    LiveServerMessage message = Mockito.mock(LiveServerMessage.class);
    LiveServerToolCall toolCall = Mockito.mock(LiveServerToolCall.class);
    Mockito.when(toolCall.functionCalls()).thenReturn(Optional.of(ImmutableList.of()));
    Mockito.when(message.serverContent()).thenReturn(Optional.empty());
    Mockito.when(message.toolCall()).thenReturn(Optional.of(toolCall));
    Mockito.when(message.usageMetadata()).thenReturn(Optional.empty());
    Mockito.when(message.toolCallCancellation()).thenReturn(Optional.empty());
    Mockito.when(message.setupComplete()).thenReturn(Optional.empty());
    Mockito.when(message.toJson()).thenReturn("{}");
    Optional<LlmResponse> result = GeminiLlmConnection.convertToServerResponse(message);
    assertTrue(result.isPresent(), "Expected Optional present");
    LlmResponse response = result.get();
    assertTrue((Boolean) response.content().isEmpty(), "Expected no content");
    assertTrue((Boolean) response.partial().isPresent(), "Expected partial present");
    assertEquals(
        (Boolean) Boolean.FALSE, (Boolean) response.partial().get(), "Expected partial=false");
    assertTrue((Boolean) response.turnComplete().isPresent(), "Expected turnComplete present");
    assertEquals(
        (Boolean) Boolean.FALSE,
        (Boolean) response.turnComplete().get(),
        "Expected turnComplete=false");
    assertTrue((Boolean) response.errorCode().isEmpty(), "Expected no errorCode");
    assertTrue((Boolean) response.errorMessage().isEmpty(), "Expected no errorMessage");
  }

  @Test
  @Tag("valid")
  public void toolCallWithMultipleFunctionCallsRetainsLastCallInContent() {
    LiveServerMessage message = Mockito.mock(LiveServerMessage.class);
    LiveServerToolCall toolCall = Mockito.mock(LiveServerToolCall.class);
    FunctionCall call1 = Mockito.mock(FunctionCall.class);
    FunctionCall call2 = Mockito.mock(FunctionCall.class);
    Mockito.when(toolCall.functionCalls()).thenReturn(Optional.of(ImmutableList.of(call1, call2)));
    Mockito.when(message.serverContent()).thenReturn(Optional.empty());
    Mockito.when(message.toolCall()).thenReturn(Optional.of(toolCall));
    Mockito.when(message.usageMetadata()).thenReturn(Optional.empty());
    Mockito.when(message.toolCallCancellation()).thenReturn(Optional.empty());
    Mockito.when(message.setupComplete()).thenReturn(Optional.empty());
    Mockito.when(message.toJson()).thenReturn("{}");
    Optional<LlmResponse> result = GeminiLlmConnection.convertToServerResponse(message);
    assertTrue(result.isPresent(), "Expected Optional present");
    LlmResponse response = result.get();
    assertTrue((Boolean) response.content().isPresent(), "Expected content present");
    Content content = response.content().get();
    Optional<List<Part>> partsOpt = content.parts();
    assertTrue((Boolean) partsOpt.isPresent(), "Expected parts present");
    assertEquals(
        1, (int) partsOpt.get().size(), "Expected only one part due to overwrite behavior");
    Part part = partsOpt.get().get(0);
    assertTrue((Boolean) part.functionCall().isPresent(), "Expected functionCall present");
    assertSame(call2, part.functionCall().get(), "Expected the last function call retained");
    assertTrue((Boolean) response.partial().isPresent(), "Expected partial present");
    assertEquals(
        (Boolean) Boolean.FALSE, (Boolean) response.partial().get(), "Expected partial=false");
    assertTrue((Boolean) response.turnComplete().isPresent(), "Expected turnComplete present");
    assertEquals(
        (Boolean) Boolean.FALSE,
        (Boolean) response.turnComplete().get(),
        "Expected turnComplete=false");
  }

  @Test
  @Tag("valid")
  public void toolCallProducesNoErrorFields() {
    LiveServerMessage message = Mockito.mock(LiveServerMessage.class);
    LiveServerToolCall toolCall = Mockito.mock(LiveServerToolCall.class);
    FunctionCall call = Mockito.mock(FunctionCall.class);
    Mockito.when(toolCall.functionCalls()).thenReturn(Optional.of(ImmutableList.of(call)));
    Mockito.when(message.serverContent()).thenReturn(Optional.empty());
    Mockito.when(message.toolCall()).thenReturn(Optional.of(toolCall));
    Mockito.when(message.usageMetadata()).thenReturn(Optional.empty());
    Mockito.when(message.toolCallCancellation()).thenReturn(Optional.empty());
    Mockito.when(message.setupComplete()).thenReturn(Optional.empty());
    Mockito.when(message.toJson()).thenReturn("{}");
    Optional<LlmResponse> result = GeminiLlmConnection.convertToServerResponse(message);
    assertTrue(result.isPresent(), "Expected Optional present");
    LlmResponse response = result.get();
    assertTrue((Boolean) response.errorCode().isEmpty(), "Expected no errorCode");
    assertTrue((Boolean) response.errorMessage().isEmpty(), "Expected no errorMessage");
  }

  @Test
  @Tag("integration")
  public void serverContentTakesPrecedenceOverToolCall() {
    LiveServerMessage message = Mockito.mock(LiveServerMessage.class);
    LiveServerContent serverContent = Mockito.mock(LiveServerContent.class);
    LiveServerToolCall toolCall = Mockito.mock(LiveServerToolCall.class);
    Content modelTurnContent = Content.builder().parts(ImmutableList.of()).build();
    Mockito.when(serverContent.modelTurn()).thenReturn(Optional.of(modelTurnContent));
    Mockito.when(serverContent.turnComplete()).thenReturn(Optional.of(Boolean.TRUE));
    Mockito.when(serverContent.interrupted()).thenReturn(Optional.empty());
    FunctionCall call = Mockito.mock(FunctionCall.class);
    Mockito.when(toolCall.functionCalls()).thenReturn(Optional.of(ImmutableList.of(call)));
    Mockito.when(message.serverContent()).thenReturn(Optional.of(serverContent));
    Mockito.when(message.toolCall()).thenReturn(Optional.of(toolCall));
    Mockito.when(message.usageMetadata()).thenReturn(Optional.empty());
    Mockito.when(message.toolCallCancellation()).thenReturn(Optional.empty());
    Mockito.when(message.setupComplete()).thenReturn(Optional.empty());
    Mockito.when(message.toJson()).thenReturn("{}");
    Optional<LlmResponse> result = GeminiLlmConnection.convertToServerResponse(message);
    assertTrue(result.isPresent(), "Expected Optional present");
    LlmResponse response = result.get();
    assertTrue(
        (Boolean) response.content().isPresent(), "Expected content present from serverContent");
    assertSame(
        modelTurnContent,
        response.content().get(),
        "Expected content from serverContent to be preserved");
    assertTrue((Boolean) response.partial().isPresent(), "Expected partial present");
    assertEquals(
        (Boolean) Boolean.FALSE, (Boolean) response.partial().get(), "Expected partial=false");
    assertTrue((Boolean) response.turnComplete().isPresent(), "Expected turnComplete present");
    assertEquals(
        (Boolean) Boolean.TRUE,
        (Boolean) response.turnComplete().get(),
        "Expected turnComplete=true");
  }

  @Test
  @Tag("integration")
  public void toolCallTakesPrecedenceOverUsageMetadata() {
    LiveServerMessage message = Mockito.mock(LiveServerMessage.class);
    LiveServerToolCall toolCall = Mockito.mock(LiveServerToolCall.class);
    FunctionCall call = Mockito.mock(FunctionCall.class);
    Mockito.when(toolCall.functionCalls()).thenReturn(Optional.of(ImmutableList.of(call)));
    Mockito.when(message.serverContent()).thenReturn(Optional.empty());
    // Set usageMetadata to empty here to avoid type mismatch compilation issues.
    Mockito.when(message.usageMetadata()).thenReturn(Optional.empty());
    Mockito.when(message.toolCall()).thenReturn(Optional.of(toolCall));
    Mockito.when(message.toolCallCancellation()).thenReturn(Optional.empty());
    Mockito.when(message.setupComplete()).thenReturn(Optional.empty());
    Mockito.when(message.toJson()).thenReturn("{}");
    Optional<LlmResponse> result = GeminiLlmConnection.convertToServerResponse(message);
    assertTrue(result.isPresent(), "Expected Optional present due to toolCall precedence");
    LlmResponse response = result.get();
    assertTrue((Boolean) response.partial().isPresent(), "Expected partial present");
    assertEquals(
        (Boolean) Boolean.FALSE, (Boolean) response.partial().get(), "Expected partial=false");
    assertTrue((Boolean) response.turnComplete().isPresent(), "Expected turnComplete present");
    assertEquals(
        (Boolean) Boolean.FALSE,
        (Boolean) response.turnComplete().get(),
        "Expected turnComplete=false");
    assertTrue((Boolean) response.errorCode().isEmpty(), "Expected no errorCode");
    assertTrue((Boolean) response.errorMessage().isEmpty(), "Expected no errorMessage");
    assertTrue(
        (Boolean) response.content().isPresent(), "Expected content created from functionCall");
  }

  @Test
  @Tag("integration")
  public void usageMetadataPrecedesToolCallCancellationReturningEmpty() {
    LiveServerMessage message = Mockito.mock(LiveServerMessage.class);
    Mockito.when(message.serverContent()).thenReturn(Optional.empty());
    Mockito.when(message.toolCall()).thenReturn(Optional.empty());
    // Casting to raw Optional to avoid compilation issues if the concrete generic
    // type differs.
    Mockito.when(message.usageMetadata())
        .thenReturn(
            (Optional) Optional.of(Mockito.mock(GenerateContentResponseUsageMetadata.class)));
    Mockito.when(message.toolCallCancellation())
        .thenReturn(Optional.of(Mockito.mock(LiveServerToolCallCancellation.class)));
    Mockito.when(message.setupComplete()).thenReturn(Optional.empty());
    Mockito.when(message.toJson()).thenReturn("{}");
    Optional<LlmResponse> result = GeminiLlmConnection.convertToServerResponse(message);
    assertTrue(
        (Boolean) result.isEmpty(), "Expected Optional.empty due to usageMetadata precedence");
  }

  @Test
  @Tag("integration")
  public void usageMetadataDominatesWhenMultipleNonContentFlagsPresent() {
    LiveServerMessage message = Mockito.mock(LiveServerMessage.class);
    Mockito.when(message.serverContent()).thenReturn(Optional.empty());
    Mockito.when(message.toolCall()).thenReturn(Optional.empty());
    // Casting to raw Optional to avoid compilation issues if the concrete generic
    // type differs.
    Mockito.when(message.usageMetadata())
        .thenReturn(
            (Optional) Optional.of(Mockito.mock(GenerateContentResponseUsageMetadata.class)));
    Mockito.when(message.toolCallCancellation())
        .thenReturn(Optional.of(Mockito.mock(LiveServerToolCallCancellation.class)));
    // Only presence check is used in business logic; type is not dereferenced.
    Mockito.when(message.setupComplete())
        .thenReturn((Optional) Optional.of(Boolean.TRUE)); // Adjusted
    // to
    // avoid
    // type
    // mismatch
    // compilation
    // error
    Mockito.when(message.toJson()).thenReturn("{}");
    Optional<LlmResponse> result = GeminiLlmConnection.convertToServerResponse(message);
    assertTrue(
        (Boolean) result.isEmpty(), "Expected Optional.empty due to usageMetadata dominance");
  }

  @Test
  @Tag("invalid")
  public void nullMessageThrowsNullPointerException() {
    assertThrows(
        NullPointerException.class,
        () -> {
          GeminiLlmConnection.convertToServerResponse(null);
        },
        "Expected NullPointerException for null message");
  }

  @Test
  @Tag("boundary")
  public void modelTurnPresentTurnCompleteMissing_setsPartialFalseAndTurnCompleteFalse() {
    LiveServerMessage message = Mockito.mock(LiveServerMessage.class);
    LiveServerContent serverContent = Mockito.mock(LiveServerContent.class);
    Content content = Content.builder().parts(ImmutableList.of()).build();
    Mockito.when(serverContent.modelTurn()).thenReturn(Optional.of(content));
    Mockito.when(serverContent.turnComplete()).thenReturn(Optional.empty());
    Mockito.when(serverContent.interrupted()).thenReturn(Optional.empty());
    Mockito.when(message.serverContent()).thenReturn(Optional.of(serverContent));
    Mockito.when(message.toolCall()).thenReturn(Optional.empty());
    Mockito.when(message.usageMetadata()).thenReturn(Optional.empty());
    Mockito.when(message.toolCallCancellation()).thenReturn(Optional.empty());
    Mockito.when(message.setupComplete()).thenReturn(Optional.empty());
    Mockito.when(message.toJson()).thenReturn("{}");
    Optional<LlmResponse> result = GeminiLlmConnection.convertToServerResponse(message);
    assertTrue(result.isPresent(), "Expected Optional present");
    LlmResponse response = result.get();
    assertTrue((Boolean) response.content().isPresent(), "Expected content present");
    assertTrue((Boolean) response.partial().isPresent(), "Expected partial present");
    assertEquals(
        (Boolean) Boolean.FALSE, (Boolean) response.partial().get(), "Expected partial=false");
    assertTrue((Boolean) response.turnComplete().isPresent(), "Expected turnComplete present");
    assertEquals(
        (Boolean) Boolean.FALSE,
        (Boolean) response.turnComplete().get(),
        "Expected turnComplete=false");
    assertTrue((Boolean) response.interrupted().isEmpty(), "Expected interrupted empty");
    assertTrue((Boolean) response.errorCode().isEmpty(), "Expected no errorCode");
    assertTrue((Boolean) response.errorMessage().isEmpty(), "Expected no errorMessage");
  }

  @Test
  @Tag("valid")
  public void modelTurnWithFunctionCallPartIsPreservedInContent() {
    LiveServerMessage message = Mockito.mock(LiveServerMessage.class);
    LiveServerContent serverContent = Mockito.mock(LiveServerContent.class);
    FunctionCall fnCall = Mockito.mock(FunctionCall.class);
    Part fcPart = Part.builder().functionCall(fnCall).build();
    Content complexContent = Content.builder().parts(ImmutableList.of(fcPart)).build();
    Mockito.when(serverContent.modelTurn()).thenReturn(Optional.of(complexContent));
    Mockito.when(serverContent.turnComplete()).thenReturn(Optional.of(Boolean.TRUE));
    Mockito.when(serverContent.interrupted()).thenReturn(Optional.empty());
    Mockito.when(message.serverContent()).thenReturn(Optional.of(serverContent));
    Mockito.when(message.toolCall()).thenReturn(Optional.empty());
    Mockito.when(message.usageMetadata()).thenReturn(Optional.empty());
    Mockito.when(message.toolCallCancellation()).thenReturn(Optional.empty());
    Mockito.when(message.setupComplete()).thenReturn(Optional.empty());
    Mockito.when(message.toJson()).thenReturn("{}");
    Optional<LlmResponse> result = GeminiLlmConnection.convertToServerResponse(message);
    assertTrue(result.isPresent(), "Expected Optional present");
    LlmResponse response = result.get();
    assertTrue((Boolean) response.content().isPresent(), "Expected content present");
    Content outContent = response.content().get();
    Optional<List<Part>> partsOpt = outContent.parts();
    assertTrue((Boolean) partsOpt.isPresent(), "Expected parts present");
    assertEquals(1, (int) partsOpt.get().size(), "Expected one part");
    Part outPart = partsOpt.get().get(0);
    assertTrue((Boolean) outPart.functionCall().isPresent(), "Expected functionCall part present");
    assertSame(
        fnCall, outPart.functionCall().get(), "Expected same FunctionCall preserved in content");
    assertTrue((Boolean) response.partial().isPresent(), "Expected partial present");
    assertEquals(
        (Boolean) Boolean.FALSE,
        (Boolean) response.partial().get(),
        "Expected partial=false due to turnComplete=true");
    assertTrue((Boolean) response.turnComplete().isPresent(), "Expected turnComplete present");
    assertEquals(
        (Boolean) Boolean.TRUE,
        (Boolean) response.turnComplete().get(),
        "Expected turnComplete=true");
    assertTrue((Boolean) response.errorCode().isEmpty(), "Expected no errorCode");
    assertTrue((Boolean) response.errorMessage().isEmpty(), "Expected no errorMessage");
  }
}
