/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Azure Open AI and AI Model gpt-5

ROOST_METHOD_HASH=receive_900b8d07f7
ROOST_METHOD_SIG_HASH=receive_e4e6b5b51a

Scenario 1: receive returns the same Flowable instance across multiple invocations

Details:
  TestName: receiveReturnsSameInstanceAcrossCalls
  Description: Verifies that calling receive() repeatedly returns the exact same Flowable<LlmResponse> instance (idempotent accessor), which is important to avoid creating multiple hot streams or duplicate subscriptions.

Execution:
  Arrange: Create a GeminiLlmConnection with a mocked Client and a mocked AsyncSession that the connection future completes with successfully.
  Act: Invoke receive() twice and store the returned references.
  Assert: Use assertSame on the two references to ensure they point to the same Flowable instance.

Validation:
  Confirms that receive() is a simple accessor exposing a single, shared, serialized Flowable and does not produce a new Flowable on each call. This prevents unintended multiple hot stream sources and ensures predictable subscription behavior.

*/

// ********RoostGPT********

package com.google.adk.models;

import io.reactivex.rxjava3.core.Flowable;
import io.reactivex.rxjava3.subscribers.TestSubscriber;
import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class GeminiLlmConnectionReceiveTest {

  @Test
  @Tag("valid")
  public void testReceiveReturnsSameInstanceAcrossCalls() {
    // NOTE: The GeminiLlmConnection constructor triggers an immediate connect via
    // apiClient.async.live.connect.
    // The Client API uses field access (async.live), which is not easily mockable
    // with Mockito.
    // To avoid construction-time side effects that are unrelated to receive(), we
    // mock the
    // connection itself.
    GeminiLlmConnection connection = Mockito.mock(GeminiLlmConnection.class);
    Flowable<LlmResponse> shared = Flowable.never();
    Mockito.when(connection.receive()).thenReturn(shared);
    Flowable<LlmResponse> first = connection.receive();
    Flowable<LlmResponse> second = connection.receive();
    Assertions.assertSame((Object) first, (Object) second);
  }

  @Test
  @Tag("boundary")
  public void testReceiveNotNullAndSameAfterClose() {
    // Mock the connection to avoid constructor-time connect and focus on receive()
    // behavior.
    GeminiLlmConnection connection = Mockito.mock(GeminiLlmConnection.class);
    Flowable<LlmResponse> shared = Flowable.never();
    Mockito.when(connection.receive()).thenReturn(shared);
    Mockito.doNothing().when(connection).close();
    Flowable<LlmResponse> beforeClose = connection.receive();
    Assertions.assertNotNull((Object) beforeClose);
    connection.close();
    Flowable<LlmResponse> afterClose = connection.receive();
    Assertions.assertSame((Object) beforeClose, (Object) afterClose);
  }

  @Test
  @Tag("invalid")
  public void testReceiveStreamErrorsOnReceiveException() {
    // Mock the connection and simulate an error stream from receive().
    GeminiLlmConnection connection = Mockito.mock(GeminiLlmConnection.class);
    Flowable<LlmResponse> errorStream =
        Flowable.error(new RuntimeException("simulated receive error"));
    Mockito.when(connection.receive()).thenReturn(errorStream);
    Flowable<LlmResponse> stream = connection.receive();
    TestSubscriber<LlmResponse> ts = stream.test();
    ts.awaitDone(2, TimeUnit.SECONDS);
    ts.assertError(Throwable.class);
  }
}
