/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Azure Open AI and AI Model gpt-5

ROOST_METHOD_HASH=sendHistory_705fa44cdb
ROOST_METHOD_SIG_HASH=sendHistory_4aed389686

Scenario 1: Successfully sends a non-empty history and completes

Details:
  TestName: sendsNonEmptyHistoryAndCompletesSuccessfully
  Description: Verifies that sendHistory(List<Content>) builds LiveSendClientContentParameters with the provided history, delegates to the AsyncSession via sendClientContent, and returns a Completable that completes successfully when the underlying future completes.

Execution:
  Arrange: Set up a mock AsyncSession that returns a successfully completed future from sendClientContent. Prepare a sessionFuture already completed with the mock AsyncSession. Create a List<Content> with multiple Content entries (e.g., 2 entries).
  Act: Invoke sendHistory(history) and subscribe to the returned Completable.
  Assert: Assert that the Completable terminates successfully (i.e., onComplete is called). Verify that AsyncSession.sendClientContent was invoked once with parameters whose turns contain exactly the provided history elements.

Validation:
  Confirms that the method correctly forwards the provided history to the session and completes normally when the session call succeeds. This ensures the happy path works for typical usage with multiple history turns.

*/

// ********RoostGPT********

package com.google.adk.models;

import com.google.common.collect.ImmutableList;
import com.google.genai.AsyncSession;
import com.google.genai.Client;
import com.google.genai.types.Content;
import com.google.genai.types.LiveConnectConfig;
import com.google.genai.types.LiveSendClientContentParameters;
import com.google.genai.types.Part;
import io.reactivex.rxjava3.core.Completable;
import io.reactivex.rxjava3.processors.PublishProcessor;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Answers;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;
import sun.misc.Unsafe;

@ExtendWith(MockitoExtension.class)
public class GeminiLlmConnectionSendHistoryTest {

  @Mock(answer = Answers.RETURNS_DEEP_STUBS)
  private AsyncSession asyncSession;

  private static Unsafe getUnsafe() throws Exception {
    Field f = Unsafe.class.getDeclaredField("theUnsafe");
    f.setAccessible(true);
    return (Unsafe) f.get(null);
  }

  private static void setFinalField(Object target, String fieldName, Object value)
      throws Exception {
    Field f = target.getClass().getDeclaredField(fieldName);
    f.setAccessible(true);
    Field modifiersField = Field.class.getDeclaredField("modifiers");
    modifiersField.setAccessible(true);
    modifiersField.setInt(f, f.getModifiers() & ~Modifier.FINAL);
    f.set(target, value);
  }

  private static <T> T allocateInstance(Class<T> cls) throws Exception {
    return (T) getUnsafe().allocateInstance(cls);
  }

  private GeminiLlmConnection createConnectionWithSession(AsyncSession session) throws Exception {
    GeminiLlmConnection connection = allocateInstance(GeminiLlmConnection.class);
    PublishProcessor<LlmResponse> rp = PublishProcessor.create();
    setFinalField(connection, "responseProcessor", rp);
    setFinalField(connection, "responseFlowable", rp.serialize());
    setFinalField(connection, "closed", new AtomicBoolean(false));
    setFinalField(connection, "sessionFuture", CompletableFuture.completedFuture(session));
    setFinalField(connection, "apiClient", Mockito.mock(Client.class, Answers.RETURNS_DEEP_STUBS));
    setFinalField(connection, "modelName", "test-model"); // TODO: Change model name
    // if needed
    setFinalField(connection, "connectConfig", Mockito.mock(LiveConnectConfig.class));
    return connection;
  }

  @Test
  @Tag("valid")
  public void testSendsNonEmptyHistoryAndCompletesSuccessfully() throws Exception {
    Mockito.when(asyncSession.sendClientContent(Mockito.any(LiveSendClientContentParameters.class)))
        .thenReturn(CompletableFuture.completedFuture(null));
    GeminiLlmConnection connection = createConnectionWithSession(asyncSession);
    Content content1 = Content.builder().parts(ImmutableList.of(Part.builder().build())).build();
    Content content2 = Content.builder().parts(ImmutableList.of(Part.builder().build())).build();
    List<Content> history = Arrays.asList(content1, content2);
    Completable completable = connection.sendHistory(history);
    io.reactivex.rxjava3.observers.TestObserver<Void> observer = completable.test();
    observer.awaitDone(2, TimeUnit.SECONDS);
    observer.assertComplete();
    observer.assertNoErrors();
    ArgumentCaptor<LiveSendClientContentParameters> paramsCaptor =
        ArgumentCaptor.forClass(LiveSendClientContentParameters.class);
    Mockito.verify(asyncSession, Mockito.times(1)).sendClientContent(paramsCaptor.capture());
    LiveSendClientContentParameters captured = paramsCaptor.getValue();
    Optional<List<Content>> turnsOptional = captured.turns();
    Assertions.assertTrue(
        ((Optional<List<Content>>) turnsOptional).isPresent(), "Turns should be present");
    List<Content> actualTurns = ((Optional<List<Content>>) turnsOptional).get();
    Assertions.assertEquals((int) history.size(), (int) actualTurns.size());
    Assertions.assertIterableEquals((Iterable<Content>) history, (Iterable<Content>) actualTurns);
  }
}
