/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test adk-java-demo using AI Type Azure Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=create_c0b4ba7866
ROOST_METHOD_SIG_HASH=create_c0b4ba7866

Scenario 1: Creating a Gemini Model Instance

Details:
  TestName: createReturnsGeminiInstanceForGeminiModel
  Description: Verifies that the create method in the LlmFactory nested interface returns a Gemini model instance when given a model name matching the "gemini-.*" pattern.

Execution:
  Arrange: Set up the LlmFactory to use the default Gemini builder as registered in the static block.
  Act: Call create with a model name like "gemini-pro".
  Assert: Verify that the returned object is an instance of Gemini and correctly reflects the provided model name.
Validation:
  This assertion checks that the registered factory for Gemini models generates the expected subtype (Gemini) and that model name is correctly set. It ensures factory mappings work as intended.


Scenario 2: Creating an Apigee Model Instance

Details:
  TestName: createReturnsApigeeLlmInstanceForApigeeModel
  Description: Checks that the create method returns an ApigeeLlm instance when passed a model name matching the "apigee/.*" pattern.

Execution:
  Arrange: Use the LlmFactory with the default ApigeeLlm builder.
  Act: Invoke create with "apigee/test-model" as the model name.
  Assert: Confirm the returned object is an ApigeeLlm and has the correct model name.
Validation:
  This test validates that Apigee model names are routed to the correct factory and the result is properly constructed. It supports accurate factory selection.


Scenario 3: Unmatched Model Name

Details:
  TestName: createThrowsExceptionForUnsupportedModel
  Description: Ensures the create method throws IllegalArgumentException if the model name does not match any registered pattern.

Execution:
  Arrange: Use the existing LlmFactory registrations only (no additional registration).
  Act: Call create with "random-model" or another unsupported name.
  Assert: Expect an IllegalArgumentException to be thrown.
Validation:
  The assertion checks proper error handling, confirming that factories are not invoked for unsupported models, which is vital for robust input validation.


Scenario 4: Factory Returns Null

Details:
  TestName: createHandlesFactoryReturningNull
  Description: Tests that the factory behaves as expected (either returning null or throwing an exception) if the registered factory returns null for a model name.

Execution:
  Arrange: Register a new factory for "null-*", which returns null.
  Act: Invoke create with "null-model".
  Assert: Assert the returned value is null, or verify exception handling if null is not permitted.
Validation:
  This scenario is important for exploring non-standard factory behavior, such as factories not being able to construct models, and ensures system resilience.


Scenario 5: Factory with Regex Collision

Details:
  TestName: createUsesFirstMatchingFactoryInCaseOfCollision
  Description: Checks that the correct factory is used when two registered regexes can match a model name, ensuring predictable factory selection order.

Execution:
  Arrange: Register two overlapping regex patterns like "gemini-.*" and "gemini-pro", with different factories.
  Act: Call create with "gemini-pro".
  Assert: Ensure the model returned is from the factory registered first (or as determined by registration ordering).
Validation:
  This validation ensures collision behavior is managed, preventing ambiguous factory selection, which can affect business logic.


Scenario 6: Factory Throws Runtime Exception

Details:
  TestName: createPropagatesExceptionFromFactory
  Description: Ensures that if the registered factory throws an unchecked exception, it is propagated out of the create method.

Execution:
  Arrange: Register a factory for "fail-.*" that throws a RuntimeException.
  Act: Invoke create with "fail-case".
  Assert: Expect RuntimeException to be thrown and propagated.
Validation:
  This confirms robust exception handling, ensuring the interface does not silently swallow exceptions during model construction.


Scenario 7: Factory Receives Correct Model Name

Details:
  TestName: createPassesModelNameToFactory
  Description: Verifies that the modelName parameter passed to create is accurately supplied to the registered factory.

Execution:
  Arrange: Register a factory that records the received model name.
  Act: Call create with distinct model name values.
  Assert: Assert that the factory received exactly the same model name argument.
Validation:
  Ensures data integrity in the contract between the create method and factory, which forms the core of this registration and resolution mechanism.


Scenario 8: Factory Registered at Runtime

Details:
  TestName: createUsesDynamicallyRegisteredFactory
  Description: Validates that factories registered after class initialization are immediately available for model creation.

Execution:
  Arrange: Register a new factory for "dynamic-.*" using registerLlm.
  Act: Call create with "dynamic-model".
  Assert: Confirm the correct model instance is returned.
Validation:
  This test demonstrates extensibility of the factory pattern, verifying dynamic registration and mapping updates take effect.


Scenario 9: Multi-threaded Access to Factory

Details:
  TestName: createIsThreadSafeUnderConcurrentAccess
  Description: Tests that concurrent calls to create with the same model name yield consistent results and do not introduce race conditions.

Execution:
  Arrange: Launch multiple threads invoking create using a concurrent model name.
  Act: Execute threads concurrently.
  Assert: Validate all threads receive valid, consistent BaseLlm instances.
Validation:
  This scenario focuses on thread safety, particularly as LlmFactory is part of a larger registry using ConcurrentHashMap for multi-threaded environments.


Scenario 10: Empty Model Name Input

Details:
  TestName: createHandlesEmptyModelNameInput
  Description: Examines the system's behavior when create is called with an empty string as the modelName parameter.

Execution:
  Arrange: No special registration (unless supporting empty names).
  Act: Call create with "".
  Assert: Check the result is either an exception (IllegalArgumentException) or a specific supported model instance.
Validation:
  It is significant for input validation, preventing unexpected null or empty model names from corrupting factory resolution.

*/

// ********RoostGPT********

package com.google.adk.models;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;
import org.mockito.Mockito;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicReference;
import org.junit.jupiter.api.BeforeEach;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.CountDownLatch;
import org.junit.jupiter.api.*;

// Dummy BaseLlm implementation for testing
class LlmFactoryCreateTest {
    final String modelName;
    BaseLlm(String modelName) {
        this.modelName = modelName;
    }
}
// Dummy Gemini and ApigeeLlm implementations for testing
class LlmFactoryCreateTest extends BaseLlm {
    Gemini(String modelName) { super(modelName); }
}
class LlmFactoryCreateTest extends BaseLlm {
    ApigeeLlm(String modelName) { super(modelName); }
}

class LlmFactoryCreateTest {
    // Simulate static registry
    static final Map<String, LlmFactory> llmFactories = new ConcurrentHashMap<>();
    public static void registerLlm(String modelNamePattern, LlmFactory factory) {
        llmFactories.put(modelNamePattern, factory);
    }
    public static BaseLlm create(String modelName) {
        for (Map.Entry<String, LlmFactory> entry : llmFactories.entrySet()) {
            if (modelName.matches(entry.getKey())) {
                return entry.getValue().create(modelName);
            }
        }
        throw new IllegalArgumentException("Unsupported model name: " + modelName);
    }
    public static
class LlmFactoryCreateTest {
        public BaseLlm create(String modelName) {
            // This method is intended to be overridden/mocked in tests
            return null;
        }
    }
}

class LlmFactoryCreateTest {
    @BeforeEach
    public void setup() {
        LlmRegistry.llmFactories.clear();
        // Register default factories
        LlmRegistry.registerLlm("gemini-.*", new LlmRegistry.LlmFactory() {
            @Override
            public BaseLlm create(String modelName) {
                return new Gemini(modelName);
            }
        });
        LlmRegistry.registerLlm("apigee/.*", new LlmRegistry.LlmFactory() {
            @Override
            public BaseLlm create(String modelName) {
                return new ApigeeLlm(modelName);
            }
        });
    }
    @Test
    @Tag("valid")
    public void testCreateReturnsGeminiInstanceForGeminiModel() {
        String modelName = "gemini-pro";
        BaseLlm result = LlmRegistry.create(modelName);
        Assertions.assertTrue(result instanceof Gemini, "Result should be an instance of Gemini");
        Assertions.assertEquals((String)modelName, (String)result.modelName, "Model name should match");
    }
    @Test
    @Tag("valid")
    public void testCreateReturnsApigeeLlmInstanceForApigeeModel() {
        String modelName = "apigee/test-model";
        BaseLlm result = LlmRegistry.create(modelName);
        Assertions.assertTrue(result instanceof ApigeeLlm, "Result should be an instance of ApigeeLlm");
        Assertions.assertEquals((String)modelName, (String)result.modelName, "Model name should match");
    }
    @Test
    @Tag("invalid")
    public void testCreateThrowsExceptionForUnsupportedModel() {
        String modelName = "random-model";
        IllegalArgumentException exception = Assertions.assertThrows(
            IllegalArgumentException.class,
            () -> LlmRegistry.create(modelName),
            "Should throw IllegalArgumentException for unsupported model"
        );
        Assertions.assertTrue(exception.getMessage().contains((String)modelName), "Exception message should contain model name");
    }
    @Test
    @Tag("boundary")
    public void testCreateHandlesFactoryReturningNull() {
        LlmRegistry.registerLlm("null-.*", new LlmRegistry.LlmFactory() {
            @Override
            public BaseLlm create(String modelName) {
                return null;
            }
        });
        String modelName = "null-model";
        BaseLlm result = LlmRegistry.create(modelName);
        Assertions.assertNull(result, "Returned value should be null");
    }
    @Test
    @Tag("boundary")
    public void testCreateUsesFirstMatchingFactoryInCaseOfCollision() {
        // Register a more specific pattern second
        LlmRegistry.llmFactories.clear();
        LlmRegistry.registerLlm("gemini-.*", new LlmRegistry.LlmFactory() {
            @Override
            public BaseLlm create(String modelName) {
                return new Gemini("first-factory"); // TODO: user can customize returned model name if needed
            }
        });
        LlmRegistry.registerLlm("gemini-pro", new LlmRegistry.LlmFactory() {
            @Override
            public BaseLlm create(String modelName) {
                return new Gemini("second-factory"); // TODO: user can customize returned model name if needed
            }
        });
        String modelName = "gemini-pro";
        BaseLlm result = LlmRegistry.create(modelName);
        Assertions.assertEquals((String)"first-factory", (String)result.modelName, "Should use first registered matching factory");
    }
    @Test
    @Tag("invalid")
    public void testCreatePropagatesExceptionFromFactory() {
        LlmRegistry.registerLlm("fail-.*", new LlmRegistry.LlmFactory() {
            @Override
            public BaseLlm create(String modelName) {
                throw new RuntimeException("Factory Failure"); // TODO: user can change exception message if needed
            }
        });
        String modelName = "fail-case";
        RuntimeException ex = Assertions.assertThrows(
                RuntimeException.class,
                () -> LlmRegistry.create(modelName),
                "Should propagate RuntimeException from factory"
        );
        Assertions.assertTrue(ex.getMessage().contains((String)"Factory Failure"), "Exception message should be as thrown");
    }
    @Test
    @Tag("valid")
    public void testCreatePassesModelNameToFactory() {
        AtomicReference<String> passedModelName = new AtomicReference<>();
        LlmRegistry.registerLlm("record-.*", new LlmRegistry.LlmFactory() {
            @Override
            public BaseLlm create(String modelName) {
                passedModelName.set(modelName);
                return new Gemini(modelName);
            }
        });
        String modelName = "record-model";
        BaseLlm result = LlmRegistry.create(modelName);
        Assertions.assertEquals((String)modelName, (String)passedModelName.get(), "Factory should receive the exact model name");
    }
    @Test
    @Tag("integration")
    public void testCreateUsesDynamicallyRegisteredFactory() {
        LlmRegistry.registerLlm("dynamic-.*", new LlmRegistry.LlmFactory() {
            @Override
            public BaseLlm create(String modelName) {
                return new Gemini("dynamic-instance"); // TODO: customize if needed
            }
        });
        String modelName = "dynamic-model";
        BaseLlm result = LlmRegistry.create(modelName);
        Assertions.assertEquals((String)"dynamic-instance", (String)result.modelName, "Dynamically registered factory should be used for model creation");
    }
    @Test
    @Tag("boundary")
    public void testCreateIsThreadSafeUnderConcurrentAccess() throws InterruptedException {
        // Register a factory for thread-safe test
        LlmRegistry.registerLlm("thread-.*", new LlmRegistry.LlmFactory() {
            @Override
            public BaseLlm create(String modelName) {
                return new Gemini(modelName);
            }
        });
        String modelName = "thread-model";
        int threadCount = 10; // TODO: user can adjust thread count
        List<BaseLlm> results = new ArrayList<>();
        CountDownLatch latch = new CountDownLatch(threadCount);
        Runnable task = () -> {
            BaseLlm llm = LlmRegistry.create(modelName);
            synchronized (results) {
                results.add(llm);
            }
            latch.countDown();
        };
        for (int i = 0; i < threadCount; i++) {
            new Thread(task).start();
        }
        latch.await();
        for (BaseLlm llm : results) {
            Assertions.assertTrue(llm instanceof Gemini, "Each returned object must be Gemini");
            Assertions.assertEquals((String)modelName, (String)llm.modelName, "Model name should be correct in all threads");
        }
        Assertions.assertEquals(threadCount, results.size(), "All threads should have returned results");
    }
    @Test
    @Tag("boundary")
    public void testCreateHandlesEmptyModelNameInput() {
        String modelName = "";
        IllegalArgumentException exception = Assertions.assertThrows(
                IllegalArgumentException.class,
                () -> LlmRegistry.create(modelName),
                "Should throw IllegalArgumentException for empty model name"
        );
        Assertions.assertTrue(exception.getMessage().contains((String)modelName), "Exception should mention empty input");
    }
}