/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Azure Open AI and AI Model gpt-5

ROOST_METHOD_HASH=registerTestLlm_14ec6c33f6
ROOST_METHOD_SIG_HASH=registerTestLlm_b0e327d7c8

Scenario 1: Registers a new non-overlapping pattern and uses it for future lookups

Details:
  TestName: registersNewPatternAndCreatesInstancesViaNewFactory
  Description: Verifies that when registerTestLlm is called with a new regex pattern that does not overlap with existing defaults, the factory is stored and subsequent getLlm calls for matching model names create and return instances from that factory.

Execution:
  Arrange: Prepare a test LlmFactory that returns a distinct, easily identifiable BaseLlm test double. Ensure no prior instances exist for the chosen model name (e.g., "custom-foo").
  Act: Invoke LlmRegistry.registerTestLlm("custom-.*", testFactory) and then call LlmRegistry.getLlm("custom-foo").
  Assert: Use JUnit assertions to verify that the returned BaseLlm is the same instance produced by testFactory for "custom-foo" (e.g., assertSame).

Validation:
  Confirms that registerTestLlm inserts the factory into the registry and that getLlm routes creation through the newly registered factory for matching names. This ensures extensibility for custom model name families during tests.


Scenario 2: Re-registering an existing pattern replaces the factory and clears matching cached instances

Details:
  TestName: reRegisterPatternReplacesFactoryAndInvalidatesCache
  Description: Ensures that calling registerTestLlm with a pattern already present replaces the factory and that any cached instances whose names match the pattern are removed.

Execution:
  Arrange:
    - Register a pattern "custom-.*" with factoryA and call getLlm("custom-1") to populate the cache with an instance from factoryA.
    - Prepare factoryB that returns a different identifiable BaseLlm.
  Act: Invoke LlmRegistry.registerTestLlm("custom-.*", factoryB) and then call getLlm("custom-1") again.
  Assert:
    - Verify the new returned instance is not the same as the previously cached one (assertNotSame).
    - Verify it is the instance produced by factoryB for "custom-1" (assertSame with factoryB’s product).

Validation:
  Confirms that the method’s removeIf logic clears cached matches to ensure test isolation, and that the factory mapping is updated atomically to the new factory.


Scenario 3: Non-matching cached entries remain unaffected

Details:
  TestName: nonMatchingCacheEntriesArePreserved
  Description: Verifies that registerTestLlm only removes cached instances whose model names match the given pattern and leaves others intact.

Execution:
  Arrange:
    - Pre-populate the cache by calling getLlm("gemini-pro") (uses default gemini factory) and getLlm("apigee/service-1") (uses default apigee factory).
  Act: Invoke LlmRegistry.registerTestLlm("custom-.*", someTestFactory).
  Assert:
    - Call getLlm("gemini-pro") again and assert it returns the same instance as before (assertSame).
    - Call getLlm("apigee/service-1") again and assert it returns the same instance as before.

Validation:
  Confirms selective cache invalidation and that unrelated cached entries are not disturbed by registering a new, non-overlapping pattern.


Scenario 4: Pattern matches multiple cached entries and removes them all

Details:
  TestName: clearsAllCachedInstancesThatMatchPattern
  Description: Ensures that when the pattern matches multiple cached model names, all those entries are removed.

Execution:
  Arrange:
    - Register test factoryA for "batch-.*" and call getLlm for "batch-a", "batch-b", and "batch-c" to populate the cache with factoryA instances.
    - Register a different factoryB to be used after cache clearing.
  Act: Invoke LlmRegistry.registerTestLlm("batch-.*", factoryB). Then call getLlm("batch-a"), "batch-b", "batch-c" again.
  Assert:
    - For each model name, assert the returned instance is not the previously cached object and matches factoryB’s created objects (assertNotSame previous; assertSame to new).
  Validation:
  Confirms that removeIf removes every matching key and that subsequent getLlm calls use the newly registered factory for those names.


Scenario 5: Using a catch-all regex clears the entire cache

Details:
  TestName: catchAllPatternClearsAllCachedInstances
  Description: Verifies that a broad pattern like ".*" removes every cached instance to guarantee a clean slate.

Execution:
  Arrange:
    - Populate the cache with several diverse model names (e.g., "gemini-pro", "apigee/service-x", "misc-123") by calling getLlm.
    - Prepare a test factory to re-create instances after clearing.
  Act: Invoke LlmRegistry.registerTestLlm(".*", testFactory).
  Assert:
    - Subsequent getLlm calls for any previously cached model name should return newly created instances from testFactory (assertNotSame vs prior; assertSame to new).
  Validation:
  Ensures that the method supports fully resetting the cache, which is valuable for test isolation across suites.


Scenario 6: Empty pattern behaves as a strict empty-string match and does not remove typical entries

Details:
  TestName: emptyPatternDoesNotAffectNonEmptyModelNames
  Description: Confirms that the empty regex "" only matches an empty model name and does not remove or affect normal cached entries.

Execution:
  Arrange:
    - Pre-populate cache with a normal model name like "custom-1".
    - Create a factory for the empty-string pattern.
  Act: Invoke LlmRegistry.registerTestLlm("", emptyPatternFactory).
  Assert:
    - Verify that calling getLlm("custom-1") returns the same cached instance (assertSame).
    - Optionally, verify that getLlm("") returns an instance created by emptyPatternFactory (assertSame).
  Validation:
  Demonstrates that registerTestLlm uses Java regex semantics via String.matches, and "" only matches empty inputs, leaving typical names unaffected.


Scenario 7: Null pattern results in a NullPointerException due to ConcurrentHashMap restrictions

Details:
  TestName: nullPatternThrowsNullPointerException
  Description: Ensures that passing a null modelNamePattern causes a NullPointerException during the llmFactories.put operation.

Execution:
  Arrange: Have a valid non-null factory ready.
  Act: Call LlmRegistry.registerTestLlm(null, validFactory) and expect an exception.
  Assert: Use assertThrows to check for NullPointerException.
  Validation:
  Confirms defensive behavior of ConcurrentHashMap and aligns with the method’s lack of null checks. The test protects against accidental null keys.


Scenario 8: Null factory results in a NullPointerException due to ConcurrentHashMap restrictions

Details:
  TestName: nullFactoryThrowsNullPointerException
  Description: Ensures that passing a null LlmFactory causes a NullPointerException when inserting into the ConcurrentHashMap.

Execution:
  Arrange: Choose any valid non-null pattern.
  Act: Call LlmRegistry.registerTestLlm("custom-.*", null) and expect an exception.
  Assert: Use assertThrows to check for NullPointerException.
  Validation:
  Confirms that null values are disallowed and the method behaves accordingly by bubbling up the NPE.


Scenario 9: Invalid regex pattern triggers a PatternSyntaxException during removal

Details:
  TestName: invalidRegexPatternThrowsPatternSyntaxException
  Description: Verifies that if an invalid regex (e.g., "(") is provided, the removal predicate throws PatternSyntaxException when evaluating matches.

Execution:
  Arrange:
    - Pre-populate the cache with one or more model names (e.g., "gemini-pro") so that removeIf attempts evaluation.
  Act: Invoke LlmRegistry.registerTestLlm("(", someFactory) and expect an exception.
  Assert: Use assertThrows to verify PatternSyntaxException is thrown.
  Validation:
  Confirms that the method does not suppress regex compilation errors and surfaces configuration mistakes early, even though the factory mapping is attempted first.


Scenario 10: The factory is not invoked during registration, only upon later getLlm

Details:
  TestName: factoryNotInvokedDuringRegistration
  Description: Ensures that registerTestLlm only stores the factory and clears the cache, but does not call LlmFactory.create until getLlm is invoked.

Execution:
  Arrange:
    - Prepare a spy or counter-enabled LlmFactory that increments a counter each time create is called.
  Act:
    - Call LlmRegistry.registerTestLlm("custom-.*", countingFactory) without calling getLlm.
  Assert:
    - Assert that the factory invocation counter remains zero.
    - After calling getLlm("custom-1"), assert that the counter increments to 1.
  Validation:
  Confirms lazy instantiation behavior: registration is side-effect free regarding object creation and creation occurs only on demand.


Scenario 11: Case sensitivity in regex matching prevents unintended removals

Details:
  TestName: regexIsCaseSensitiveForRemoval
  Description: Validates that the removal predicate is case-sensitive (per String.matches) and does not clear entries with different case.

Execution:
  Arrange:
    - Cache an instance under "gemini-pro" via getLlm.
  Act:
    - Call LlmRegistry.registerTestLlm("GEMINI-.*", someFactory).
  Assert:
    - Call getLlm("gemini-pro") again and assert it is the same cached instance as before (assertSame), indicating it was not removed.
  Validation:
  Ensures predictable behavior regarding case sensitivity in regex processing.


Scenario 12: Overriding the default gemini pattern clears its cached instances

Details:
  TestName: overridingDefaultGeminiClearsCachedGemini
  Description: Ensures that when the default "gemini-.*" pattern is overridden for testing, any previously cached gemini instances are cleared.

Execution:
  Arrange:
    - Call getLlm("gemini-pro") to create and cache a default gemini instance.
    - Prepare a test factory that creates a distinct test double for gemini names.
  Act:
    - Call LlmRegistry.registerTestLlm("gemini-.*", testFactory), then call getLlm("gemini-pro").
  Assert:
    - Verify the new instance differs from the previous cached one and matches the instance from testFactory (assertNotSame previous; assertSame to new).
  Validation:
  Confirms that registerTestLlm ensures test isolation by invalidating default-cached instances for overridden patterns.


Scenario 13: Concurrent registration and cache population does not cause concurrent modification errors

Details:
  TestName: concurrentRegistrationDoesNotThrowAndEndsInConsistentState
  Description: Verifies thread-safety under concurrency by invoking getLlm for matching names while calling registerTestLlm, ensuring no ConcurrentModificationException and eventual consistency.

Execution:
  Arrange:
    - Spawn one thread repeatedly calling getLlm("custom-1") using an initial factory registered for "custom-.*".
    - Prepare a second factory to replace the first.
    - Coordinate action with latches to overlap operations.
  Act:
    - In parallel, call LlmRegistry.registerTestLlm("custom-.*", secondFactory).
  Assert:
    - Assert no exceptions are thrown from either thread.
    - After registration completes, verify a subsequent getLlm("custom-1") returns an instance created by secondFactory.
  Validation:
  Confirms that the use of ConcurrentHashMap and keySet().removeIf is safe under concurrent access and results in the expected final behavior.


Scenario 14: Latest registration wins for the same pattern

Details:
  TestName: lastRegisteredFactoryForPatternIsUsed
  Description: Ensures that when the same regex pattern is registered multiple times sequentially, the last factory overwrites earlier ones for subsequent getLlm calls.

Execution:
  Arrange:
    - Register "custom-.*" with factoryA.
    - Register "custom-.*" again with factoryB.
  Act:
    - Call getLlm("custom-xyz").
  Assert:
    - Verify the returned instance is the one created by factoryB (assertSame), not by factoryA.
  Validation:
  Confirms deterministic overwrite behavior in the factory map for duplicate keys.


Scenario 15: Overriding apigee pattern does not affect gemini cached entries

Details:
  TestName: overridingApigeeDoesNotAffectGeminiCache
  Description: Ensures that when "apigee/.*" is overridden, only apigee entries are cleared and gemini entries remain cached.

Execution:
  Arrange:
    - Cache instances for "apigee/service-1" and "gemini-pro" using getLlm.
    - Prepare a test factory for "apigee/.*".
  Act:
    - Call LlmRegistry.registerTestLlm("apigee/.*", testFactory).
  Assert:
    - getLlm("apigee/service-1") returns a new instance from testFactory (assertNotSame previous; assertSame to new).
    - getLlm("gemini-pro") returns the same instance as before (assertSame).
  Validation:
  Confirms pattern-specific cache invalidation without collateral impact on other families.


Scenario 16: Exact match pattern only removes the exact model name, not similar prefixes

Details:
  TestName: exactPatternRemovesOnlyExactModelName
  Description: Verifies that a literal pattern like "custom-1" removes only "custom-1" and not "custom-10" or "custom-11", because String.matches requires a full-string match.

Execution:
  Arrange:
    - Register a factory for "custom-.*" and cache "custom-1" and "custom-10" via getLlm.
    - Prepare a replacement factory.
  Act:
    - Call LlmRegistry.registerTestLlm("custom-1", replacementFactory).
  Assert:
    - getLlm("custom-1") returns an instance from replacementFactory (new).
    - getLlm("custom-10") returns the same previously cached instance (unchanged).
  Validation:
  Demonstrates correct full-string regex matching semantics in removal behavior.


Scenario 17: Bulk cache clearing for many matching keys

Details:
  TestName: clearsLargeNumberOfMatchingCachedEntriesEfficiently
  Description: Ensures correctness when many keys need removal by verifying all matching entries are cleared and recreated via the new factory.

Execution:
  Arrange:
    - Register factoryA for "bulk-.*" and cache a large set of names: "bulk-1" through "bulk-100" using getLlm.
    - Prepare factoryB to replace factoryA.
  Act:
    - Call LlmRegistry.registerTestLlm("bulk-.*", factoryB). Then call getLlm on several of the bulk keys (e.g., first, middle, last).
  Assert:
    - For sampled keys, assert new instances are returned from factoryB and are different from previously cached ones (assertNotSame previous; assertSame to new).
  Validation:
  Confirms correctness at scale and that removal impacts all matching keys.


Scenario 18: Pattern with escaped special characters works as a regex

Details:
  TestName: escapedCharactersInPatternAreHandledCorrectly
  Description: Validates that regex metacharacters must be escaped to match literal characters and that removal respects these escapes.

Execution:
  Arrange:
    - Register a factory for "custom\\+model-.*" and cache "custom+model-1" via getLlm (ensure an earlier factory supports this name).
    - Prepare a replacement factory.
  Act:
    - Call LlmRegistry.registerTestLlm("custom\\+model-.*", replacementFactory) and then getLlm("custom+model-1").
  Assert:
    - Assert that the cached instance for "custom+model-1" was cleared and a new one from replacementFactory is returned (assertNotSame previous; assertSame to new).
  Validation:
  Confirms adherence to Java regex syntax in matching and cache invalidation.


Scenario 19: Registering a pattern that matches no current entries does not change existing cache

Details:
  TestName: nonMatchingPatternDoesNotClearExistingCache
  Description: Ensures that when no cached keys match the provided pattern, the cache remains unchanged while the factory is still registered for future use.

Execution:
  Arrange:
    - Cache a model like "gemini-pro" via getLlm.
  Act:
    - Call LlmRegistry.registerTestLlm("custom-.*", someFactory) where no "custom-.*" items are cached.
  Assert:
    - getLlm("gemini-pro") returns the same instance as before (assertSame).
    - getLlm("custom-1") afterward returns an instance produced by someFactory (assertSame to new), demonstrating the factory was registered.
  Validation:
  Confirms that cache clearing is conditional on matches and that future matching lookups leverage the new factory.


Scenario 20: After overriding pattern, subsequent creations use the new factory even for names created concurrently before registration completes

Details:
  TestName: postOverrideLookupsUseNewFactoryDespiteConcurrentActivity
  Description: Ensures that once registerTestLlm completes, any subsequent calls to getLlm for matching names return instances created by the newly registered factory, regardless of concurrent pre-registration cache state.

Execution:
  Arrange:
    - Start a thread that calls getLlm("override-1") using an initially registered factory (e.g., default or prior test factory) and pauses.
    - Prepare a new factory to override "override-.*".
  Act:
    - Call LlmRegistry.registerTestLlm("override-.*", newFactory) and then, after ensuring it completes, call getLlm("override-1").
  Assert:
    - Assert that getLlm("override-1") returns an instance from newFactory (assertSame to new and assertNotSame to any earlier instance, if present).
  Validation:
  Confirms the final consistency guarantee: after registration, future lookups use the latest factory and any matching cached entries have been purged.


*/

// ********RoostGPT********

package com.google.adk.models;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNotSame;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertThrows;

import com.google.adk.models.LlmRegistry.LlmFactory;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.CyclicBarrier;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicReference;
import java.util.regex.PatternSyntaxException;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.junit.jupiter.api.parallel.Execution;
import org.junit.jupiter.api.parallel.ExecutionMode;
import org.mockito.Mockito;

/** JUnit 5 test suite for LlmRegistry.registerTestLlm. */
@Execution(ExecutionMode.SAME_THREAD)
public class LlmRegistryRegisterTestLlmTest {

  // Utility factory that creates specific instances per name and tracks invocations.
  static class CountingFactory implements LlmFactory {

    private final AtomicInteger counter = new AtomicInteger(0);

    private final Map<String, BaseLlm> createdByName = new ConcurrentHashMap<>();

    @Override
    public BaseLlm create(String modelName) {
      counter.incrementAndGet();
      return createdByName.computeIfAbsent(modelName, n -> Mockito.mock(BaseLlm.class));
    }

    int getCount() {
      return counter.get();
    }

    BaseLlm getCreated(String modelName) {
      return createdByName.get(modelName);
    }
  }

  // Utility factory returning pre-mapped instances or creating mocks on demand.
  static class MappedFactory implements LlmFactory {

    private final Map<String, BaseLlm> mapping;

    MappedFactory(Map<String, BaseLlm> mapping) {
      this.mapping = mapping;
    }

    @Override
    public BaseLlm create(String modelName) {
      return mapping.computeIfAbsent(modelName, n -> Mockito.mock(BaseLlm.class));
    }

    BaseLlm expectedFor(String modelName) {
      return mapping.get(modelName);
    }
  }

  private static BaseLlm newLlm(String nameHint) {
    return Mockito.mock(BaseLlm.class, Mockito.withSettings().name(nameHint));
  }

  @Test
  @Tag("valid")
  public void testRegistersNewPatternAndCreatesInstancesViaNewFactory() {
    String pattern = "custom-.*";
    String model = "custom-foo";
    BaseLlm expected = (BaseLlm) newLlm("expected-custom-foo");
    LlmFactory testFactory = Mockito.mock(LlmFactory.class);
    Mockito.when(testFactory.create(Mockito.eq(model))).thenReturn(expected);
    LlmRegistry.registerTestLlm(pattern, testFactory);
    BaseLlm actual = (BaseLlm) LlmRegistry.getLlm(model);
    assertSame((BaseLlm) expected, (BaseLlm) actual);
  }

  @Test
  @Tag("valid")
  public void testReRegisterPatternReplacesFactoryAndInvalidatesCache() {
    String pattern = "custom-.*";
    String model = "custom-1";
    // First registration and instance
    BaseLlm firstInstance = (BaseLlm) newLlm("first-custom-1");
    LlmFactory factoryA = Mockito.mock(LlmFactory.class);
    Mockito.when(factoryA.create(Mockito.eq(model))).thenReturn(firstInstance);
    LlmRegistry.registerTestLlm(pattern, factoryA);
    BaseLlm cached = (BaseLlm) LlmRegistry.getLlm(model);
    assertSame((BaseLlm) firstInstance, (BaseLlm) cached);
    // Re-register with a different factory
    BaseLlm secondInstance = (BaseLlm) newLlm("second-custom-1");
    LlmFactory factoryB = Mockito.mock(LlmFactory.class);
    Mockito.when(factoryB.create(Mockito.eq(model))).thenReturn(secondInstance);
    LlmRegistry.registerTestLlm(pattern, factoryB);
    BaseLlm actual = (BaseLlm) LlmRegistry.getLlm(model);
    assertNotSame((BaseLlm) firstInstance, (BaseLlm) actual);
    assertSame((BaseLlm) secondInstance, (BaseLlm) actual);
  }

  @Test
  @Tag("valid")
  public void testNonMatchingCacheEntriesArePreserved() {
    String gemini = "gemini-pro";
    String apigee = "apigee/service-1";
    // Pre-populate default caches (assumes defaults exist in implementation)
    BaseLlm geminiInitial = (BaseLlm) LlmRegistry.getLlm(gemini);
    BaseLlm apigeeInitial = (BaseLlm) LlmRegistry.getLlm(apigee);
    assertNotNull((BaseLlm) geminiInitial);
    assertNotNull((BaseLlm) apigeeInitial);
    // Register a non-overlapping pattern
    LlmFactory someTestFactory = Mockito.mock(LlmFactory.class);
    LlmRegistry.registerTestLlm("custom-.*", someTestFactory);
    BaseLlm geminiAgain = (BaseLlm) LlmRegistry.getLlm(gemini);
    BaseLlm apigeeAgain = (BaseLlm) LlmRegistry.getLlm(apigee);
    assertSame((BaseLlm) geminiInitial, (BaseLlm) geminiAgain);
    assertSame((BaseLlm) apigeeInitial, (BaseLlm) apigeeAgain);
  }

  @Test
  @Tag("valid")
  public void testClearsAllCachedInstancesThatMatchPattern() {
    String pattern = "batch-.*";
    String[] names = {"batch-a", "batch-b", "batch-c"};
    // factoryA populates cache
    LlmFactory factoryA = Mockito.mock(LlmFactory.class);
    Map<String, BaseLlm> aMap = new ConcurrentHashMap<>();
    for (String n : names) {
      BaseLlm llm = (BaseLlm) newLlm("A-" + n);
      aMap.put(n, llm);
      Mockito.when(factoryA.create(Mockito.eq(n))).thenReturn(llm);
    }
    LlmRegistry.registerTestLlm(pattern, factoryA);
    BaseLlm a0 = (BaseLlm) LlmRegistry.getLlm(names[0]);
    BaseLlm a1 = (BaseLlm) LlmRegistry.getLlm(names[1]);
    BaseLlm a2 = (BaseLlm) LlmRegistry.getLlm(names[2]);
    // factoryB after clearing
    LlmFactory factoryB = Mockito.mock(LlmFactory.class);
    Map<String, BaseLlm> bMap = new ConcurrentHashMap<>();
    for (String n : names) {
      BaseLlm llm = (BaseLlm) newLlm("B-" + n);
      bMap.put(n, llm);
      Mockito.when(factoryB.create(Mockito.eq(n))).thenReturn(llm);
    }
    LlmRegistry.registerTestLlm(pattern, factoryB);
    BaseLlm b0 = (BaseLlm) LlmRegistry.getLlm(names[0]);
    BaseLlm b1 = (BaseLlm) LlmRegistry.getLlm(names[1]);
    BaseLlm b2 = (BaseLlm) LlmRegistry.getLlm(names[2]);
    assertNotSame((BaseLlm) a0, (BaseLlm) b0);
    assertNotSame((BaseLlm) a1, (BaseLlm) b1);
    assertNotSame((BaseLlm) a2, (BaseLlm) b2);
    assertSame((BaseLlm) bMap.get(names[0]), (BaseLlm) b0);
    assertSame((BaseLlm) bMap.get(names[1]), (BaseLlm) b1);
    assertSame((BaseLlm) bMap.get(names[2]), (BaseLlm) b2);
  }

  @Test
  @Tag("boundary")
  public void testCatchAllPatternClearsAllCachedInstances() {
    String[] names = {"gemini-pro", "apigee/service-x", "misc-123"};
    // Populate caches using existing/defaults
    BaseLlm[] before = new BaseLlm[names.length];
    for (int i = 0; i < names.length; i++) {
      before[i] = (BaseLlm) LlmRegistry.getLlm(names[i]);
      assertNotNull((BaseLlm) before[i]);
    }
    // Register catch-all factory
    LlmFactory testFactory = Mockito.mock(LlmFactory.class);
    Map<String, BaseLlm> newMap = new ConcurrentHashMap<>();
    for (String n : names) {
      BaseLlm llm = (BaseLlm) newLlm("catchall-" + n);
      newMap.put(n, llm);
      Mockito.when(testFactory.create(Mockito.eq(n))).thenReturn(llm);
    }
    LlmRegistry.registerTestLlm(".*", testFactory);
    for (int i = 0; i < names.length; i++) {
      BaseLlm after = (BaseLlm) LlmRegistry.getLlm(names[i]);
      assertNotSame((BaseLlm) before[i], (BaseLlm) after);
      assertSame((BaseLlm) newMap.get(names[i]), (BaseLlm) after);
    }
  }

  @Test
  @Tag("boundary")
  public void testEmptyPatternDoesNotAffectNonEmptyModelNames() {
    String model = "custom-1";
    String empty = "";
    // Prepare a baseline instance for non-empty model using its own factory
    LlmFactory customFactory = Mockito.mock(LlmFactory.class);
    BaseLlm baseline = (BaseLlm) newLlm("baseline-custom-1");
    LlmRegistry.registerTestLlm("custom-.*", customFactory);
    Mockito.when(customFactory.create(Mockito.eq(model))).thenReturn(baseline);
    BaseLlm before = (BaseLlm) LlmRegistry.getLlm(model);
    assertSame((BaseLlm) baseline, (BaseLlm) before);
    // Register empty-string pattern factory
    LlmFactory emptyFactory = Mockito.mock(LlmFactory.class);
    BaseLlm emptyLlm = (BaseLlm) newLlm("empty-name-llm");
    Mockito.when(emptyFactory.create(Mockito.eq(empty))).thenReturn(emptyLlm);
    LlmRegistry.registerTestLlm("", emptyFactory);
    // Non-empty should be unaffected
    BaseLlm after = (BaseLlm) LlmRegistry.getLlm(model);
    assertSame((BaseLlm) before, (BaseLlm) after);
    // Optional: empty name should match "" and use emptyFactory
    BaseLlm producedForEmpty = (BaseLlm) LlmRegistry.getLlm(empty);
    assertSame((BaseLlm) emptyLlm, (BaseLlm) producedForEmpty);
  }

  @Test
  @Tag("invalid")
  public void testNullPatternThrowsNullPointerException() {
    LlmFactory validFactory = Mockito.mock(LlmFactory.class);
    assertThrows(NullPointerException.class, () -> LlmRegistry.registerTestLlm(null, validFactory));
  }

  @Test
  @Tag("invalid")
  public void testNullFactoryThrowsNullPointerException() {
    String pattern = "custom-.*";
    assertThrows(NullPointerException.class, () -> LlmRegistry.registerTestLlm(pattern, null));
  }

  @Test
  @Tag("invalid")
  public void testInvalidRegexPatternThrowsPatternSyntaxException() {
    // Pre-populate cache to ensure removeIf's predicate attempts to evaluate matches
    BaseLlm pre = (BaseLlm) LlmRegistry.getLlm("gemini-pro");
    assertNotNull((BaseLlm) pre);
    LlmFactory someFactory = Mockito.mock(LlmFactory.class);
    assertThrows(PatternSyntaxException.class, () -> LlmRegistry.registerTestLlm("(", someFactory));
  }

  @Test
  @Tag("valid")
  public void testFactoryNotInvokedDuringRegistration() {
    CountingFactory countingFactory = new CountingFactory();
    assertEquals((int) 0, (int) countingFactory.getCount());
    LlmRegistry.registerTestLlm("custom-.*", countingFactory);
    assertEquals((int) 0, (int) countingFactory.getCount());
    BaseLlm produced = (BaseLlm) LlmRegistry.getLlm("custom-1");
    assertNotNull((BaseLlm) produced);
    assertEquals((int) 1, (int) countingFactory.getCount());
  }

  @Test
  @Tag("boundary")
  public void testRegexIsCaseSensitiveForRemoval() {
    String model = "gemini-pro";
    BaseLlm before = (BaseLlm) LlmRegistry.getLlm(model);
    assertNotNull((BaseLlm) before);
    LlmFactory someFactory = Mockito.mock(LlmFactory.class);
    LlmRegistry.registerTestLlm("GEMINI-.*", someFactory);
    BaseLlm after = (BaseLlm) LlmRegistry.getLlm(model);
    assertSame((BaseLlm) before, (BaseLlm) after);
  }

  @Test
  @Tag("valid")
  public void testOverridingDefaultGeminiClearsCachedGemini() {
    String model = "gemini-pro";
    BaseLlm before = (BaseLlm) LlmRegistry.getLlm(model);
    assertNotNull((BaseLlm) before);
    LlmFactory testFactory = Mockito.mock(LlmFactory.class);
    BaseLlm expected = (BaseLlm) newLlm("gemini-test-double");
    Mockito.when(testFactory.create(Mockito.eq(model))).thenReturn(expected);
    LlmRegistry.registerTestLlm("gemini-.*", testFactory);
    BaseLlm after = (BaseLlm) LlmRegistry.getLlm(model);
    assertNotSame((BaseLlm) before, (BaseLlm) after);
    assertSame((BaseLlm) expected, (BaseLlm) after);
  }

  @Test
  @Tag("integration")
  @Timeout(10)
  public void testConcurrentRegistrationDoesNotThrowAndEndsInConsistentState() throws Exception {
    String pattern = "conc-.*";
    String model = "conc-1";
    CountingFactory initialFactory = new CountingFactory();
    CountingFactory secondFactory = new CountingFactory();
    LlmRegistry.registerTestLlm(pattern, initialFactory);
    CyclicBarrier barrier = new CyclicBarrier(2);
    CountDownLatch done = new CountDownLatch(2);
    AtomicReference<Throwable> errorRef = new AtomicReference<>(null);
    Thread t1 =
        new Thread(
            () -> {
              try {
                barrier.await();
                // Repeatedly get LLM to exercise concurrent behavior
                for (int i = 0; i < 1000; i++) {
                  BaseLlm l = (BaseLlm) LlmRegistry.getLlm(model);
                  assertNotNull((BaseLlm) l);
                }
              } catch (Throwable t) {
                errorRef.set(t);
              } finally {
                done.countDown();
              }
            });
    Thread t2 =
        new Thread(
            () -> {
              try {
                barrier.await();
                // Register replacement factory concurrently
                LlmRegistry.registerTestLlm(pattern, secondFactory);
              } catch (Throwable t) {
                errorRef.set(t);
              } finally {
                done.countDown();
              }
            });
    t1.start();
    t2.start();
    // TODO: Adjust await time if CI is slow
    boolean finished = done.await(5, TimeUnit.SECONDS);
    assertEquals((boolean) true, (boolean) finished);
    if (errorRef.get() != null) {
      throw new AssertionError("Concurrent operation threw", errorRef.get());
    }
    // After registration completes, the new factory should be used
    BaseLlm finalInstance = (BaseLlm) LlmRegistry.getLlm(model);
    BaseLlm fromSecond = (BaseLlm) secondFactory.getCreated(model);
    assertSame((BaseLlm) fromSecond, (BaseLlm) finalInstance);
  }

  @Test
  @Tag("valid")
  public void testLastRegisteredFactoryForPatternIsUsed() {
    String pattern = "custom-.*";
    String model = "custom-xyz";
    LlmFactory factoryA = Mockito.mock(LlmFactory.class);
    BaseLlm a = (BaseLlm) newLlm("A");
    Mockito.when(factoryA.create(Mockito.eq(model))).thenReturn(a);
    LlmFactory factoryB = Mockito.mock(LlmFactory.class);
    BaseLlm b = (BaseLlm) newLlm("B");
    Mockito.when(factoryB.create(Mockito.eq(model))).thenReturn(b);
    LlmRegistry.registerTestLlm(pattern, factoryA);
    LlmRegistry.registerTestLlm(pattern, factoryB);
    BaseLlm actual = (BaseLlm) LlmRegistry.getLlm(model);
    assertSame((BaseLlm) b, (BaseLlm) actual);
  }

  @Test
  @Tag("valid")
  public void testOverridingApigeeDoesNotAffectGeminiCache() {
    String apigee = "apigee/service-1";
    String gemini = "gemini-pro";
    BaseLlm apigeeBefore = (BaseLlm) LlmRegistry.getLlm(apigee);
    BaseLlm geminiBefore = (BaseLlm) LlmRegistry.getLlm(gemini);
    assertNotNull((BaseLlm) apigeeBefore);
    assertNotNull((BaseLlm) geminiBefore);
    LlmFactory apigeeTestFactory = Mockito.mock(LlmFactory.class);
    BaseLlm apigeeAfterInstance = (BaseLlm) newLlm("apigee-test");
    Mockito.when(apigeeTestFactory.create(Mockito.eq(apigee))).thenReturn(apigeeAfterInstance);
    LlmRegistry.registerTestLlm("apigee/.*", apigeeTestFactory);
    BaseLlm apigeeAfter = (BaseLlm) LlmRegistry.getLlm(apigee);
    BaseLlm geminiAfter = (BaseLlm) LlmRegistry.getLlm(gemini);
    assertNotSame((BaseLlm) apigeeBefore, (BaseLlm) apigeeAfter);
    assertSame((BaseLlm) apigeeAfterInstance, (BaseLlm) apigeeAfter);
    assertSame((BaseLlm) geminiBefore, (BaseLlm) geminiAfter);
  }

  @Test
  @Tag("boundary")
  public void testExactPatternRemovesOnlyExactModelName() {
    // First, ensure cache for both names exists using custom base pattern
    String basePattern = "custom-.*";
    String exactPattern = "custom-1";
    String m1 = "custom-1";
    String m10 = "custom-10";
    LlmFactory baseFactory = Mockito.mock(LlmFactory.class);
    BaseLlm llm1 = (BaseLlm) newLlm("base-1");
    BaseLlm llm10 = (BaseLlm) newLlm("base-10");
    Mockito.when(baseFactory.create(Mockito.eq(m1))).thenReturn(llm1);
    Mockito.when(baseFactory.create(Mockito.eq(m10))).thenReturn(llm10);
    LlmRegistry.registerTestLlm(basePattern, baseFactory);
    BaseLlm before1 = (BaseLlm) LlmRegistry.getLlm(m1);
    BaseLlm before10 = (BaseLlm) LlmRegistry.getLlm(m10);
    assertSame((BaseLlm) llm1, (BaseLlm) before1);
    assertSame((BaseLlm) llm10, (BaseLlm) before10);
    // Now, re-register with exact pattern replacement factory
    LlmFactory replacementFactory = Mockito.mock(LlmFactory.class);
    BaseLlm replaced1 = (BaseLlm) newLlm("replaced-1");
    Mockito.when(replacementFactory.create(Mockito.eq(m1))).thenReturn(replaced1);
    LlmRegistry.registerTestLlm(exactPattern, replacementFactory);
    BaseLlm after1 = (BaseLlm) LlmRegistry.getLlm(m1);
    BaseLlm after10 = (BaseLlm) LlmRegistry.getLlm(m10);
    assertSame((BaseLlm) replaced1, (BaseLlm) after1);
    assertSame((BaseLlm) before10, (BaseLlm) after10);
  }

  @Test
  @Tag("valid")
  public void testClearsLargeNumberOfMatchingCachedEntriesEfficiently() {
    String pattern = "bulk-.*";
    // factoryA caches bulk-1..bulk-100
    LlmFactory factoryA = Mockito.mock(LlmFactory.class);
    Map<String, BaseLlm> aMap = new ConcurrentHashMap<>();
    for (int i = 1; i <= 100; i++) {
      String name = "bulk-" + i;
      BaseLlm llm = (BaseLlm) newLlm("A-" + name);
      aMap.put(name, llm);
      Mockito.when(factoryA.create(Mockito.eq(name))).thenReturn(llm);
    }
    LlmRegistry.registerTestLlm(pattern, factoryA);
    List<BaseLlm> before = new ArrayList<>();
    for (int i = 1; i <= 100; i++) {
      before.add((BaseLlm) LlmRegistry.getLlm("bulk-" + i));
    }
    // factoryB replaces
    LlmFactory factoryB = Mockito.mock(LlmFactory.class);
    Map<String, BaseLlm> bMap = new ConcurrentHashMap<>();
    for (int i = 1; i <= 100; i++) {
      String name = "bulk-" + i;
      BaseLlm llm = (BaseLlm) newLlm("B-" + name);
      bMap.put(name, llm);
      Mockito.when(factoryB.create(Mockito.eq(name))).thenReturn(llm);
    }
    LlmRegistry.registerTestLlm(pattern, factoryB);
    int[] samples = {1, 50, 100};
    for (int s : samples) {
      String key = "bulk-" + s;
      BaseLlm newLlm = (BaseLlm) LlmRegistry.getLlm(key);
      assertNotSame((BaseLlm) before.get(s - 1), (BaseLlm) newLlm);
      assertSame((BaseLlm) bMap.get(key), (BaseLlm) newLlm);
    }
  }

  @Test
  @Tag("boundary")
  public void testEscapedCharactersInPatternAreHandledCorrectly() {
    // Prepare an existing cached instance for name with '+'
    String name = "custom+model-1";
    String pattern = "custom\\+model-.*";
    // First register a base factory that will create the initial cache entry
    LlmFactory baseFactory = Mockito.mock(LlmFactory.class);
    BaseLlm initial = (BaseLlm) newLlm("base-plus");
    Mockito.when(baseFactory.create(Mockito.eq(name))).thenReturn(initial);
    LlmRegistry.registerTestLlm(pattern, baseFactory);
    BaseLlm before = (BaseLlm) LlmRegistry.getLlm(name);
    assertSame((BaseLlm) initial, (BaseLlm) before);
    // Now register a replacement factory for the escaped pattern
    LlmFactory replacementFactory = Mockito.mock(LlmFactory.class);
    BaseLlm replaced = (BaseLlm) newLlm("replaced-plus");
    Mockito.when(replacementFactory.create(Mockito.eq(name))).thenReturn(replaced);
    LlmRegistry.registerTestLlm(pattern, replacementFactory);
    BaseLlm after = (BaseLlm) LlmRegistry.getLlm(name);
    assertNotSame((BaseLlm) before, (BaseLlm) after);
    assertSame((BaseLlm) replaced, (BaseLlm) after);
  }

  @Test
  @Tag("valid")
  public void testNonMatchingPatternDoesNotClearExistingCache() {
    String existing = "gemini-pro";
    BaseLlm before = (BaseLlm) LlmRegistry.getLlm(existing);
    assertNotNull((BaseLlm) before);
    // Register a pattern with no current matches
    LlmFactory someFactory = Mockito.mock(LlmFactory.class);
    BaseLlm customInstance = (BaseLlm) newLlm("custom-1-instance");
    Mockito.when(someFactory.create(Mockito.eq("custom-1"))).thenReturn(customInstance);
    LlmRegistry.registerTestLlm("custom-.*", someFactory);
    // Existing should remain same
    BaseLlm after = (BaseLlm) LlmRegistry.getLlm(existing);
    assertSame((BaseLlm) before, (BaseLlm) after);
    // Future lookup should use new factory
    BaseLlm produced = (BaseLlm) LlmRegistry.getLlm("custom-1");
    assertSame((BaseLlm) customInstance, (BaseLlm) produced);
  }

  @Test
  @Tag("integration")
  @Timeout(10)
  public void testPostOverrideLookupsUseNewFactoryDespiteConcurrentActivity() throws Exception {
    String pattern = "override-.*";
    String model = "override-1";
    // Initial factory and cache
    LlmFactory initialFactory = Mockito.mock(LlmFactory.class);
    BaseLlm initialInstance = (BaseLlm) newLlm("initial-override-1");
    Mockito.when(initialFactory.create(Mockito.eq(model))).thenReturn(initialInstance);
    LlmRegistry.registerTestLlm(pattern, initialFactory);
    CountDownLatch started = new CountDownLatch(1);
    CountDownLatch proceed = new CountDownLatch(1);
    CountDownLatch done = new CountDownLatch(1);
    AtomicReference<Throwable> error = new AtomicReference<>(null);
    Thread actor =
        new Thread(
            () -> {
              try {
                // Create initial cache
                BaseLlm first = (BaseLlm) LlmRegistry.getLlm(model);
                assertSame((BaseLlm) initialInstance, (BaseLlm) first);
                started.countDown();
                // Wait to allow override
                proceed.await(3, TimeUnit.SECONDS); // TODO: adjust await as appropriate
                // After override, accesses should be fine (not verifying here)
                BaseLlm later = (BaseLlm) LlmRegistry.getLlm(model);
                assertNotNull((BaseLlm) later);
              } catch (Throwable t) {
                error.set(t);
              } finally {
                done.countDown();
              }
            });
    actor.start();
    started.await(3, TimeUnit.SECONDS); // TODO: adjust await as appropriate
    // New factory to override
    LlmFactory newFactory = Mockito.mock(LlmFactory.class);
    BaseLlm newInstance = (BaseLlm) newLlm("new-override-1");
    Mockito.when(newFactory.create(Mockito.eq(model))).thenReturn(newInstance);
    // Perform override
    LlmRegistry.registerTestLlm(pattern, newFactory);
    proceed.countDown();
    boolean finished = done.await(5, TimeUnit.SECONDS);
    assertEquals((boolean) true, (boolean) finished);
    if (error.get() != null) {
      throw new AssertionError("Concurrent activity failed", error.get());
    }
    // After override completes, subsequent lookups should use new factory
    BaseLlm after = (BaseLlm) LlmRegistry.getLlm(model);
    assertSame((BaseLlm) newInstance, (BaseLlm) after);
    assertNotSame((BaseLlm) initialInstance, (BaseLlm) after);
  }
}
