/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Azure Open AI and AI Model gpt-5

ROOST_METHOD_HASH=getLlm_7f9a36d638
ROOST_METHOD_SIG_HASH=getLlm_66c37a084b

Scenario 1: Returns a non-null LLM instance for a default Gemini model pattern

Details:
  TestName: returnsInstanceForDefaultGeminiPattern
  Description: Verifies that getLlm returns a non-null BaseLlm instance when called with a model name matching the default "gemini-.*" pattern registered in the static initializer (e.g., "gemini-1.5-pro").

Execution:
  Arrange: Choose a model name that matches the default Gemini pattern, such as "gemini-1.5-pro". No additional registration is needed.
  Act: Invoke LlmRegistry.getLlm("gemini-1.5-pro") and capture the returned BaseLlm.
  Assert: Use assertNotNull to verify the returned BaseLlm instance is not null.

Validation:
  Clarify that the assertion confirms the default factory mapping for "gemini-.*" is effective and the registry can create instances via the configured factory.
  Elaborate that this test ensures the registry’s out-of-the-box behavior for Gemini models works as expected, reflecting proper static initialization and pattern recognition.

*/

// ********RoostGPT********

package com.google.adk.models;

import static org.junit.jupiter.api.Assertions.*;

import com.google.adk.models.LlmRegistry.LlmFactory;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class LlmRegistryGetLlmTest {

  @Test
  @Tag("valid")
  public void testReturnsInstanceForDefaultGeminiPattern() {
    // TODO: If the default Gemini model name changes, update the value below
    // accordingly.
    String modelName = "gemini-1.5-pro";
    BaseLlm actual = LlmRegistry.getLlm(modelName);
    assertNotNull((Object) actual);
  }

  @Test
  @Tag("invalid")
  public void testThrowsForUnsupportedModelName() {
    String modelName = "unknown-999";
    IllegalArgumentException ex =
        assertThrows(
            IllegalArgumentException.class,
            () -> {
              LlmRegistry.getLlm(modelName);
            });
    assertEquals((String) ("Unsupported model: " + modelName), (String) ex.getMessage());
  }

  @Test
  @Tag("valid")
  public void testReturnsCachedInstanceOnSubsequentCalls() {
    String pattern = "mock-.*";
    String modelName = "mock-model-1";
    LlmFactory factory = Mockito.mock(LlmFactory.class);
    BaseLlm expected = Mockito.mock(BaseLlm.class);
    Mockito.when(factory.create(Mockito.eq(modelName))).thenReturn(expected);
    LlmRegistry.registerTestLlm(pattern, factory);
    BaseLlm first = LlmRegistry.getLlm(modelName);
    BaseLlm second = LlmRegistry.getLlm(modelName);
    assertSame((BaseLlm) expected, (BaseLlm) first);
    assertSame((BaseLlm) expected, (BaseLlm) second);
    Mockito.verify(factory, Mockito.times(1)).create(Mockito.eq(modelName));
  }

  @Test
  @Tag("integration")
  public void testReplacesCachedInstanceWhenRegisteringTestLlmAgain() {
    String pattern = "custom-.*";
    String modelName = "custom-xyz";
    LlmFactory factory1 = Mockito.mock(LlmFactory.class);
    BaseLlm instance1 = Mockito.mock(BaseLlm.class);
    Mockito.when(factory1.create(Mockito.eq(modelName))).thenReturn(instance1);
    LlmRegistry.registerTestLlm(pattern, factory1);
    BaseLlm first = LlmRegistry.getLlm(modelName);
    assertSame((BaseLlm) instance1, (BaseLlm) first);
    LlmFactory factory2 = Mockito.mock(LlmFactory.class);
    BaseLlm instance2 = Mockito.mock(BaseLlm.class);
    Mockito.when(factory2.create(Mockito.eq(modelName))).thenReturn(instance2);
    // Re-register the same pattern; should invalidate cached instance for matching
    // names.
    LlmRegistry.registerTestLlm(pattern, factory2);
    BaseLlm second = LlmRegistry.getLlm(modelName);
    assertSame((BaseLlm) instance2, (BaseLlm) second);
    Mockito.verify(factory1, Mockito.times(1)).create(Mockito.eq(modelName));
    Mockito.verify(factory2, Mockito.times(1)).create(Mockito.eq(modelName));
  }

  @Test
  @Tag("integration")
  public void testConcurrentGetLlmCreatesOneInstance() throws Exception {
    String pattern = "concurrent-.*";
    String modelName = "concurrent-test-model";
    LlmFactory factory = Mockito.mock(LlmFactory.class);
    BaseLlm createdInstance = Mockito.mock(BaseLlm.class);
    Mockito.when(factory.create(Mockito.eq(modelName))).thenAnswer(invocation -> createdInstance);
    LlmRegistry.registerTestLlm(pattern, factory);
    int threadCount = 8; // TODO: Adjust thread count if needed.
    ExecutorService executorService = Executors.newFixedThreadPool(threadCount);
    CountDownLatch startLatch = new CountDownLatch(1);
    CountDownLatch doneLatch = new CountDownLatch(threadCount);
    Map<Integer, BaseLlm> results = new ConcurrentHashMap<>();
    for (int i = 0; i < threadCount; i++) {
      final int idx = i;
      executorService.execute(
          () -> {
            try {
              startLatch.await();
              BaseLlm res = LlmRegistry.getLlm(modelName);
              results.put(idx, res);
            } catch (InterruptedException e) {
              Thread.currentThread().interrupt();
              fail("Thread interrupted");
            } finally {
              doneLatch.countDown();
            }
          });
    }
    startLatch.countDown();
    doneLatch.await();
    executorService.shutdown();
    // Ensure factory.create was called exactly once.
    Mockito.verify(factory, Mockito.times(1)).create(Mockito.eq(modelName));
    // Ensure all returned instances are the same object.
    BaseLlm first = results.get(0);
    assertNotNull((Object) first);
    for (int i = 1; i < threadCount; i++) {
      assertSame((BaseLlm) first, (BaseLlm) results.get(i));
    }
  }

  @Test
  @Tag("invalid")
  public void testNullModelNameThrowsNullPointerException() {
    assertThrows(
        NullPointerException.class,
        () -> {
          LlmRegistry.getLlm(null);
        });
  }

  @Test
  @Tag("valid")
  public void testPatternMatchingSelectsCorrectFactoryAmongMultiple() {
    String alphaPattern = "alpha-.*";
    String betaPattern = "beta-.*";
    String alphaModel = "alpha-1";
    String betaModel = "beta-1";
    LlmFactory alphaFactory = Mockito.mock(LlmFactory.class);
    LlmFactory betaFactory = Mockito.mock(LlmFactory.class);
    BaseLlm alphaInstance = Mockito.mock(BaseLlm.class);
    BaseLlm betaInstance = Mockito.mock(BaseLlm.class);
    Mockito.when(alphaFactory.create(Mockito.eq(alphaModel))).thenReturn(alphaInstance);
    Mockito.when(betaFactory.create(Mockito.eq(betaModel))).thenReturn(betaInstance);
    LlmRegistry.registerTestLlm(alphaPattern, alphaFactory);
    LlmRegistry.registerTestLlm(betaPattern, betaFactory);
    BaseLlm actualAlpha = LlmRegistry.getLlm(alphaModel);
    BaseLlm actualBeta = LlmRegistry.getLlm(betaModel);
    assertSame((BaseLlm) alphaInstance, (BaseLlm) actualAlpha);
    assertSame((BaseLlm) betaInstance, (BaseLlm) actualBeta);
    Mockito.verify(alphaFactory, Mockito.times(1)).create(Mockito.eq(alphaModel));
    Mockito.verify(betaFactory, Mockito.times(1)).create(Mockito.eq(betaModel));
  }

  @Test
  @Tag("boundary")
  public void testEmptyStringModelNameUnsupported() {
    String modelName = "";
    IllegalArgumentException ex =
        assertThrows(
            IllegalArgumentException.class,
            () -> {
              LlmRegistry.getLlm(modelName);
            });
    assertEquals((String) ("Unsupported model: " + modelName), (String) ex.getMessage());
  }
}
