/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Azure Open AI and AI Model gpt-5

ROOST_METHOD_HASH=registerLlm_39033090dc
ROOST_METHOD_SIG_HASH=registerLlm_6d1828529e

Scenario 1: Registering a new regex pattern allows resolving a matching model via the custom factory

Details:
  TestName: registersFactoryAndResolvesMatchingModel
  Description: Verifies that calling registerLlm with a new regex pattern successfully registers the factory, and that a subsequent call to getLlm with a model name matching that pattern returns an instance produced by the registered factory.

Execution:
  Arrange: Define a unique regex pattern (e.g., "custom/.*") and implement a dummy LlmFactory that returns a distinctive dummy BaseLlm subclass instance. Ensure the model name (e.g., "custom/modelA") does not collide with defaults ("gemini-.*", "apigee/.*").
  Act: Call registerLlm with the pattern and factory. Then call getLlm with the matching model name.
  Assert: Use assertions to verify that the returned instance is the exact object produced by the dummy factory (e.g., assertSame) or is an instance of the dummy subclass (e.g., assertTrue with instanceof).

Validation:
  Confirms that registerLlm adds the factory mapping and that getLlm routes model resolution through the newly registered factory. This validates the primary responsibility of the registration API.

*/

// ********RoostGPT********

package com.google.adk.models;

import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class LlmRegistryRegisterLlmTest {

  @Test
  @Tag("valid")
  public void testRegistersFactoryAndResolvesMatchingModel() {
    final String pattern = "custom/.*"; // TODO adjust pattern as needed
    final String modelName = "custom/modelA"; // TODO adjust model name as needed
    LlmRegistry.LlmFactory factory = Mockito.mock(LlmRegistry.LlmFactory.class);
    BaseLlm expected = Mockito.mock(BaseLlm.class);
    Mockito.when(factory.create(modelName)).thenReturn(expected);
    LlmRegistry.registerLlm(pattern, factory);
    BaseLlm actual = LlmRegistry.getLlm(modelName);
    Assertions.assertNotNull((Object) actual);
    Assertions.assertSame((BaseLlm) expected, (BaseLlm) actual);
    Assertions.assertTrue((boolean) (actual instanceof BaseLlm));
    Mockito.verify(factory, Mockito.times(1)).create(modelName);
  }

  @Test
  @Tag("invalid")
  public void testRegisterLlmWithNullPatternThrowsNPE() {
    LlmRegistry.LlmFactory factory = Mockito.mock(LlmRegistry.LlmFactory.class);
    Assertions.assertThrows(
        NullPointerException.class, () -> LlmRegistry.registerLlm(null, factory));
  }

  @Test
  @Tag("invalid")
  public void testRegisterLlmWithNullFactoryThrowsNPE() {
    final String pattern = "custom-null-factory/.*"; // TODO adjust pattern as needed
    Assertions.assertThrows(
        NullPointerException.class, () -> LlmRegistry.registerLlm(pattern, null));
  }

  @Test
  @Tag("boundary")
  public void testOverwritesFactoryForSamePatternBeforeResolution() {
    final String pattern = "custom2/.*"; // TODO adjust pattern as needed
    final String modelName = "custom2/modelB"; // TODO adjust model name as needed
    LlmRegistry.LlmFactory firstFactory = Mockito.mock(LlmRegistry.LlmFactory.class);
    BaseLlm firstInstance = Mockito.mock(BaseLlm.class);
    Mockito.when(firstFactory.create(modelName)).thenReturn(firstInstance);
    LlmRegistry.LlmFactory secondFactory = Mockito.mock(LlmRegistry.LlmFactory.class);
    BaseLlm secondInstance = Mockito.mock(BaseLlm.class);
    Mockito.when(secondFactory.create(modelName)).thenReturn(secondInstance);
    LlmRegistry.registerLlm(pattern, firstFactory);
    LlmRegistry.registerLlm(pattern, secondFactory);
    BaseLlm actual = LlmRegistry.getLlm(modelName);
    Assertions.assertSame((BaseLlm) secondInstance, (BaseLlm) actual);
    Mockito.verify(secondFactory, Mockito.times(1)).create(modelName);
    Mockito.verify(firstFactory, Mockito.never()).create(modelName);
  }

  @Test
  @Tag("invalid")
  public void testResolutionFailsForUnmatchedModel() {
    final String pattern = "other/.*"; // TODO adjust pattern as needed
    final String unmatchedModel = "unknown/modelX"; // TODO adjust model name as
    // needed
    LlmRegistry.LlmFactory factory = Mockito.mock(LlmRegistry.LlmFactory.class);
    LlmRegistry.registerLlm(pattern, factory);
    Assertions.assertThrows(
        IllegalArgumentException.class, () -> LlmRegistry.getLlm(unmatchedModel));
    Mockito.verify(factory, Mockito.never()).create(Mockito.anyString());
  }

  @Test
  @Tag("integration")
  public void testRegisterTestLlmClearsCachedInstanceAfterReRegistration() {
    final String pattern = "clear/.*"; // TODO adjust pattern as needed
    final String modelName = "clear/model1"; // TODO adjust model name as needed
    LlmRegistry.LlmFactory factory1 = Mockito.mock(LlmRegistry.LlmFactory.class);
    BaseLlm instance1 = Mockito.mock(BaseLlm.class);
    Mockito.when(factory1.create(modelName)).thenReturn(instance1);
    LlmRegistry.LlmFactory factory2 = Mockito.mock(LlmRegistry.LlmFactory.class);
    BaseLlm instance2 = Mockito.mock(BaseLlm.class);
    Mockito.when(factory2.create(modelName)).thenReturn(instance2);
    // Initial registration and resolution
    LlmRegistry.registerLlm(pattern, factory1);
    BaseLlm resolved1 = LlmRegistry.getLlm(modelName);
    Assertions.assertSame((BaseLlm) instance1, (BaseLlm) resolved1);
    // Re-register for tests; should clear cached instance for matching model names
    LlmRegistry.registerTestLlm(pattern, factory2);
    // Resolve again and ensure the new factory is used
    BaseLlm resolved2 = LlmRegistry.getLlm(modelName);
    Assertions.assertSame((BaseLlm) instance2, (BaseLlm) resolved2);
    Mockito.verify(factory1, Mockito.times(1)).create(modelName);
    Mockito.verify(factory2, Mockito.times(1)).create(modelName);
  }

  @Test
  @Tag("valid")
  public void testMultipleDistinctPatternsResolveCorrectFactories() {
    final String patternA = "pA/.*"; // TODO adjust pattern as needed
    final String modelA = "pA/model1"; // TODO adjust model name as needed
    final String patternB = "pB/.*"; // TODO adjust pattern as needed
    final String modelB = "pB/model2"; // TODO adjust model name as needed
    LlmRegistry.LlmFactory factoryA = Mockito.mock(LlmRegistry.LlmFactory.class);
    BaseLlm instanceA = Mockito.mock(BaseLlm.class);
    Mockito.when(factoryA.create(modelA)).thenReturn(instanceA);
    LlmRegistry.LlmFactory factoryB = Mockito.mock(LlmRegistry.LlmFactory.class);
    BaseLlm instanceB = Mockito.mock(BaseLlm.class);
    Mockito.when(factoryB.create(modelB)).thenReturn(instanceB);
    LlmRegistry.registerLlm(patternA, factoryA);
    LlmRegistry.registerLlm(patternB, factoryB);
    BaseLlm actualA = LlmRegistry.getLlm(modelA);
    BaseLlm actualB = LlmRegistry.getLlm(modelB);
    Assertions.assertSame((BaseLlm) instanceA, (BaseLlm) actualA);
    Assertions.assertSame((BaseLlm) instanceB, (BaseLlm) actualB);
    Mockito.verify(factoryA, Mockito.times(1)).create(modelA);
    Mockito.verify(factoryB, Mockito.times(1)).create(modelB);
  }

  @Test
  @Tag("boundary")
  public void testRegexBoundaryMatchingAndNonMatching() {
    final String pattern = "regex/\\w{3}"; // TODO adjust pattern as needed
    final String matchingModel = "regex/abc"; // TODO adjust model name as needed
    final String nonMatchingModel = "regex/abcd"; // TODO adjust model name as needed
    LlmRegistry.LlmFactory factory = Mockito.mock(LlmRegistry.LlmFactory.class);
    BaseLlm expectedMatch = Mockito.mock(BaseLlm.class);
    Mockito.when(factory.create(matchingModel)).thenReturn(expectedMatch);
    LlmRegistry.registerLlm(pattern, factory);
    // Matching case
    BaseLlm actualMatch = LlmRegistry.getLlm(matchingModel);
    Assertions.assertSame((BaseLlm) expectedMatch, (BaseLlm) actualMatch);
    Mockito.verify(factory, Mockito.times(1)).create(matchingModel);
    // Non-matching case should throw
    Assertions.assertThrows(
        IllegalArgumentException.class, () -> LlmRegistry.getLlm(nonMatchingModel));
    Mockito.verify(factory, Mockito.never()).create(nonMatchingModel);
  }
}
