/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Azure Open AI and AI Model gpt-5

ROOST_METHOD_HASH=registerTestLlm_14ec6c33f6
ROOST_METHOD_SIG_HASH=registerTestLlm_b0e327d7c8

Scenario 1: Registers a new non-overlapping pattern and uses it for future lookups

Details:
  TestName: registersNewPatternAndCreatesInstancesViaNewFactory
  Description: Verifies that when registerTestLlm is called with a new regex pattern that does not overlap with existing defaults, the factory is stored and subsequent getLlm calls for matching model names create and return instances from that factory.

Execution:
  Arrange: Prepare a test LlmFactory that returns a distinct, easily identifiable BaseLlm test double. Ensure no prior instances exist for the chosen model name (e.g., "custom-foo").
  Act: Invoke LlmRegistry.registerTestLlm("custom-.*", testFactory) and then call LlmRegistry.getLlm("custom-foo").
  Assert: Use JUnit assertions to verify that the returned BaseLlm is the same instance produced by testFactory for "custom-foo" (e.g., assertSame).

Validation:
  Confirms that registerTestLlm inserts the factory into the registry and that getLlm routes creation through the newly registered factory for matching names. This ensures extensibility for custom model name families during tests.


Scenario 2: Re-registering an existing pattern replaces the factory and clears matching cached instances

Details:
  TestName: reRegisterPatternReplacesFactoryAndInvalidatesCache
  Description: Ensures that calling registerTestLlm with a pattern already present replaces the factory and that any cached instances whose names match the pattern are removed.

Execution:
  Arrange:
    - Register a pattern "custom-.*" with factoryA and call getLlm("custom-1") to populate the cache with an instance from factoryA.
    - Prepare factoryB that returns a different identifiable BaseLlm.
  Act: Invoke LlmRegistry.registerTestLlm("custom-.*", factoryB) and then call getLlm("custom-1") again.
  Assert:
    - Verify the new returned instance is not the same as the previously cached one (assertNotSame).
    - Verify it is the instance produced by factoryB for "custom-1" (assertSame with factoryB’s product).

Validation:
  Confirms that the method’s removeIf logic clears cached matches to ensure test isolation, and that the factory mapping is updated atomically to the new factory.


Scenario 3: Non-matching cached entries remain unaffected

Details:
  TestName: nonMatchingCacheEntriesArePreserved
  Description: Verifies that registerTestLlm only removes cached instances whose model names match the given pattern and leaves others intact.

Execution:
  Arrange:
    - Pre-populate the cache by calling getLlm("gemini-pro") (uses default gemini factory) and getLlm("apigee/service-1") (uses default apigee factory).
  Act: Invoke LlmRegistry.registerTestLlm("custom-.*", someTestFactory).
  Assert:
    - Call getLlm("gemini-pro") again and assert it returns the same instance as before (assertSame).
    - Call getLlm("apigee/service-1") again and assert it returns the same instance as before.

Validation:
  Confirms selective cache invalidation and that unrelated cached entries are not disturbed by registering a new, non-overlapping pattern.


Scenario 4: Pattern matches multiple cached entries and removes them all

Details:
  TestName: clearsAllCachedInstancesThatMatchPattern
  Description: Ensures that when the pattern matches multiple cached model names, all those entries are removed.

Execution:
  Arrange:
    - Register test factoryA for "batch-.*" and call getLlm for "batch-a", "batch-b", and "batch-c" to populate the cache with factoryA instances.
    - Register a different factoryB to be used after cache clearing.
  Act: Invoke LlmRegistry.registerTestLlm("batch-.*", factoryB). Then call getLlm("batch-a"), "batch-b", "batch-c" again.
  Assert:
    - For each model name, assert the returned instance is not the previously cached object and matches factoryB’s created objects (assertNotSame previous; assertSame to new).
  Validation:
  Confirms that removeIf removes every matching key and that subsequent getLlm calls use the newly registered factory for those names.


Scenario 5: Using a catch-all regex clears the entire cache

Details:
  TestName: catchAllPatternClearsAllCachedInstances
  Description: Verifies that a broad pattern like ".*" removes every cached instance to guarantee a clean slate.

Execution:
  Arrange:
    - Populate the cache with several diverse model names (e.g., "gemini-pro", "apigee/service-x", "misc-123") by calling getLlm.
    - Prepare a test factory to re-create instances after clearing.
  Act: Invoke LlmRegistry.registerTestLlm(".*", testFactory).
  Assert:
    - Subsequent getLlm calls for any previously cached model name should return newly created instances from testFactory (assertNotSame vs prior; assertSame to new).
  Validation:
  Ensures that the method supports fully resetting the cache, which is valuable for test isolation across suites.


Scenario 6: Empty pattern behaves as a strict empty-string match and does not remove typical entries

Details:
  TestName: emptyPatternDoesNotAffectNonEmptyModelNames
  Description: Confirms that the empty regex "" only matches an empty model name and does not remove or affect normal cached entries.

Execution:
  Arrange:
    - Pre-populate cache with a normal model name like "custom-1".
    - Create a factory for the empty-string pattern.
  Act: Invoke LlmRegistry.registerTestLlm("", emptyPatternFactory).
  Assert:
    - Verify that calling getLlm("custom-1") returns the same cached instance (assertSame).
    - Optionally, verify that getLlm("") returns an instance created by emptyPatternFactory (assertSame).
  Validation:
  Demonstrates that registerTestLlm uses Java regex semantics via String.matches, and "" only matches empty inputs, leaving typical names unaffected.


Scenario 7: Null pattern results in a NullPointerException due to ConcurrentHashMap restrictions

Details:
  TestName: nullPatternThrowsNullPointerException
  Description: Ensures that passing a null modelNamePattern causes a NullPointerException during the llmFactories.put operation.

Execution:
  Arrange: Have a valid non-null factory ready.
  Act: Call LlmRegistry.registerTestLlm(null, validFactory) and expect an exception.
  Assert: Use assertThrows to check for NullPointerException.
  Validation:
  Confirms defensive behavior of ConcurrentHashMap and aligns with the method’s lack of null checks. The test protects against accidental null keys.


Scenario 8: Null factory results in a NullPointerException due to ConcurrentHashMap restrictions

Details:
  TestName: nullFactoryThrowsNullPointerException
  Description: Ensures that passing a null LlmFactory causes a NullPointerException when inserting into the ConcurrentHashMap.

Execution:
  Arrange: Choose any valid non-null pattern.
  Act: Call LlmRegistry.registerTestLlm("custom-.*", null) and expect an exception.
  Assert: Use assertThrows to check for NullPointerException.
  Validation:
  Confirms that null values are disallowed and the method behaves accordingly by bubbling up the NPE.


Scenario 9: Invalid regex pattern triggers a PatternSyntaxException during removal

Details:
  TestName: invalidRegexPatternThrowsPatternSyntaxException
  Description: Verifies that if an invalid regex (e.g., "(") is provided, the removal predicate throws PatternSyntaxException when evaluating matches.

Execution:
  Arrange:
    - Pre-populate the cache with one or more model names (e.g., "gemini-pro") so that removeIf attempts evaluation.
  Act: Invoke LlmRegistry.registerTestLlm("(", someFactory) and expect an exception.
  Assert: Use assertThrows to verify PatternSyntaxException is thrown.
  Validation:
  Confirms that the method does not suppress regex compilation errors and surfaces configuration mistakes early, even though the factory mapping is attempted first.


Scenario 10: The factory is not invoked during registration, only upon later getLlm

Details:
  TestName: factoryNotInvokedDuringRegistration
  Description: Ensures that registerTestLlm only stores the factory and clears the cache, but does not call LlmFactory.create until getLlm is invoked.

Execution:
  Arrange:
    - Prepare a spy or counter-enabled LlmFactory that increments a counter each time create is called.
  Act:
    - Call LlmRegistry.registerTestLlm("custom-.*", countingFactory) without calling getLlm.
  Assert:
    - Assert that the factory invocation counter remains zero.
    - After calling getLlm("custom-1"), assert that the counter increments to 1.
  Validation:
  Confirms lazy instantiation behavior: registration is side-effect free regarding object creation and creation occurs only on demand.


Scenario 11: Case sensitivity in regex matching prevents unintended removals

Details:
  TestName: regexIsCaseSensitiveForRemoval
  Description: Validates that the removal predicate is case-sensitive (per String.matches) and does not clear entries with different case.

Execution:
  Arrange:
    - Cache an instance under "gemini-pro" via getLlm.
  Act:
    - Call LlmRegistry.registerTestLlm("GEMINI-.*", someFactory).
  Assert:
    - Call getLlm("gemini-pro") again and assert it is the same cached instance as before (assertSame), indicating it was not removed.
  Validation:
  Ensures predictable behavior regarding case sensitivity in regex processing.


Scenario 12: Overriding the default gemini pattern clears its cached instances

Details:
  TestName: overridingDefaultGeminiClearsCachedGemini
  Description: Ensures that when the default "gemini-.*" pattern is overridden for testing, any previously cached gemini instances are cleared.

Execution:
  Arrange:
    - Call getLlm("gemini-pro") to create and cache a default gemini instance.
    - Prepare a test factory that creates a distinct test double for gemini names.
  Act:
    - Call LlmRegistry.registerTestLlm("gemini-.*", testFactory), then call getLlm("gemini-pro").
  Assert:
    - Verify the new instance differs from the previous cached one and matches the instance from testFactory (assertNotSame previous; assertSame to new).
  Validation:
  Confirms that registerTestLlm ensures test isolation by invalidating default-cached instances for overridden patterns.


Scenario 13: Concurrent registration and cache population does not cause concurrent modification errors

Details:
  TestName: concurrentRegistrationDoesNotThrowAndEndsInConsistentState
  Description: Verifies thread-safety under concurrency by invoking getLlm for matching names while calling registerTestLlm, ensuring no ConcurrentModificationException and eventual consistency.

Execution:
  Arrange:
    - Spawn one thread repeatedly calling getLlm("custom-1") using an initial factory registered for "custom-.*".
    - Prepare a second factory to replace the first.
    - Coordinate action with latches to overlap operations.
  Act:
    - In parallel, call LlmRegistry.registerTestLlm("custom-.*", secondFactory).
  Assert:
    - Assert no exceptions are thrown from either thread.
    - After registration completes, verify a subsequent getLlm("custom-1") returns an instance created by secondFactory.
  Validation:
  Confirms that the use of ConcurrentHashMap and keySet().removeIf is safe under concurrent access and results in the expected final behavior.


Scenario 14: Latest registration wins for the same pattern

Details:
  TestName: lastRegisteredFactoryForPatternIsUsed
  Description: Ensures that when the same regex pattern is registered multiple times sequentially, the last factory overwrites earlier ones for subsequent getLlm calls.

Execution:
  Arrange:
    - Register "custom-.*" with factoryA.
    - Register "custom-.*" again with factoryB.
  Act:
    - Call getLlm("custom-xyz").
  Assert:
    - Verify the returned instance is the one created by factoryB (assertSame), not by factoryA.
  Validation:
  Confirms deterministic overwrite behavior in the factory map for duplicate keys.


Scenario 15: Overriding apigee pattern does not affect gemini cached entries

Details:
  TestName: overridingApigeeDoesNotAffectGeminiCache
  Description: Ensures that when "apigee/.*" is overridden, only apigee entries are cleared and gemini entries remain cached.

Execution:
  Arrange:
    - Cache instances for "apigee/service-1" and "gemini-pro" using getLlm.
    - Prepare a test factory for "apigee/.*".
  Act:
    - Call LlmRegistry.registerTestLlm("apigee/.*", testFactory).
  Assert:
    - getLlm("apigee/service-1") returns a new instance from testFactory (assertNotSame previous; assertSame to new).
    - getLlm("gemini-pro") returns the same instance as before (assertSame).
  Validation:
  Confirms pattern-specific cache invalidation without collateral impact on other families.


Scenario 16: Exact match pattern only removes the exact model name, not similar prefixes

Details:
  TestName: exactPatternRemovesOnlyExactModelName
  Description: Verifies that a literal pattern like "custom-1" removes only "custom-1" and not "custom-10" or "custom-11", because String.matches requires a full-string match.

Execution:
  Arrange:
    - Register a factory for "custom-.*" and cache "custom-1" and "custom-10" via getLlm.
    - Prepare a replacement factory.
  Act:
    - Call LlmRegistry.registerTestLlm("custom-1", replacementFactory).
  Assert:
    - getLlm("custom-1") returns an instance from replacementFactory (new).
    - getLlm("custom-10") returns the same previously cached instance (unchanged).
  Validation:
  Demonstrates correct full-string regex matching semantics in removal behavior.


Scenario 17: Bulk cache clearing for many matching keys

Details:
  TestName: clearsLargeNumberOfMatchingCachedEntriesEfficiently
  Description: Ensures correctness when many keys need removal by verifying all matching entries are cleared and recreated via the new factory.

Execution:
  Arrange:
    - Register factoryA for "bulk-.*" and cache a large set of names: "bulk-1" through "bulk-100" using getLlm.
    - Prepare factoryB to replace factoryA.
  Act:
    - Call LlmRegistry.registerTestLlm("bulk-.*", factoryB). Then call getLlm on several of the bulk keys (e.g., first, middle, last).
  Assert:
    - For sampled keys, assert new instances are returned from factoryB and are different from previously cached ones (assertNotSame previous; assertSame to new).
  Validation:
  Confirms correctness at scale and that removal impacts all matching keys.


Scenario 18: Pattern with escaped special characters works as a regex

Details:
  TestName: escapedCharactersInPatternAreHandledCorrectly
  Description: Validates that regex metacharacters must be escaped to match literal characters and that removal respects these escapes.

Execution:
  Arrange:
    - Register a factory for "custom\\+model-.*" and cache "custom+model-1" via getLlm (ensure an earlier factory supports this name).
    - Prepare a replacement factory.
  Act:
    - Call LlmRegistry.registerTestLlm("custom\\+model-.*", replacementFactory) and then getLlm("custom+model-1").
  Assert:
    - Assert that the cached instance for "custom+model-1" was cleared and a new one from replacementFactory is returned (assertNotSame previous; assertSame to new).
  Validation:
  Confirms adherence to Java regex syntax in matching and cache invalidation.


Scenario 19: Registering a pattern that matches no current entries does not change existing cache

Details:
  TestName: nonMatchingPatternDoesNotClearExistingCache
  Description: Ensures that when no cached keys match the provided pattern, the cache remains unchanged while the factory is still registered for future use.

Execution:
  Arrange:
    - Cache a model like "gemini-pro" via getLlm.
  Act:
    - Call LlmRegistry.registerTestLlm("custom-.*", someFactory) where no "custom-.*" items are cached.
  Assert:
    - getLlm("gemini-pro") returns the same instance as before (assertSame).
    - getLlm("custom-1") afterward returns an instance produced by someFactory (assertSame to new), demonstrating the factory was registered.
  Validation:
  Confirms that cache clearing is conditional on matches and that future matching lookups leverage the new factory.


Scenario 20: After overriding pattern, subsequent creations use the new factory even for names created concurrently before registration completes

Details:
  TestName: postOverrideLookupsUseNewFactoryDespiteConcurrentActivity
  Description: Ensures that once registerTestLlm completes, any subsequent calls to getLlm for matching names return instances created by the newly registered factory, regardless of concurrent pre-registration cache state.

Execution:
  Arrange:
    - Start a thread that calls getLlm("override-1") using an initially registered factory (e.g., default or prior test factory) and pauses.
    - Prepare a new factory to override "override-.*".
  Act:
    - Call LlmRegistry.registerTestLlm("override-.*", newFactory) and then, after ensuring it completes, call getLlm("override-1").
  Assert:
    - Assert that getLlm("override-1") returns an instance from newFactory (assertSame to new and assertNotSame to any earlier instance, if present).
  Validation:
  Confirms the final consistency guarantee: after registration, future lookups use the latest factory and any matching cached entries have been purged.


*/

// ********RoostGPT********

package com.google.adk.models;

import com.google.adk.models.LlmRegistry.LlmFactory;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicReference;
import java.util.regex.PatternSyntaxException;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.mockito.Mockito;

@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class LlmRegistryRegisterTestLlmTest {

  private static LlmFactory factoryFromMap(Map<String, BaseLlm> map) {
    return (String modelName) -> {
      BaseLlm v = map.get(modelName);
      if (v != null) {
        return v;
      }
      BaseLlm created = Mockito.mock(BaseLlm.class);
      map.put(modelName, created);
      return created;
    };
  }

  @BeforeEach
  public void setUp() {
    // Intentionally empty to avoid cross-test interference with static state.
    // Each test uses unique patterns and names to isolate behavior.
  }

  @Test
  @Order(1)
  @Tag("valid")
  public void registersNewPatternAndCreatesInstancesViaNewFactory() {
    String pattern = "s1-custom-.*";
    String modelName = "s1-custom-foo";
    Map<String, BaseLlm> returns = new ConcurrentHashMap<>();
    BaseLlm expected = Mockito.mock(BaseLlm.class);
    returns.put(modelName, expected);
    LlmFactory testFactory = factoryFromMap(returns);
    LlmRegistry.registerTestLlm(pattern, testFactory);
    BaseLlm actual = LlmRegistry.getLlm(modelName);
    Assertions.assertSame((BaseLlm) expected, (BaseLlm) actual);
  }

  @Test
  @Order(2)
  @Tag("valid")
  public void reRegisterPatternReplacesFactoryAndInvalidatesCache() {
    String pattern = "s2-custom-.*";
    String modelName = "s2-custom-1";
    Map<String, BaseLlm> mapA = new ConcurrentHashMap<>();
    BaseLlm instanceA = Mockito.mock(BaseLlm.class);
    mapA.put(modelName, instanceA);
    LlmFactory factoryA = factoryFromMap(mapA);
    LlmRegistry.registerTestLlm(pattern, factoryA);
    BaseLlm cached = LlmRegistry.getLlm(modelName);
    Assertions.assertSame((BaseLlm) instanceA, (BaseLlm) cached);
    Map<String, BaseLlm> mapB = new ConcurrentHashMap<>();
    BaseLlm instanceB = Mockito.mock(BaseLlm.class);
    mapB.put(modelName, instanceB);
    LlmFactory factoryB = factoryFromMap(mapB);
    LlmRegistry.registerTestLlm(pattern, factoryB);
    BaseLlm after = LlmRegistry.getLlm(modelName);
    Assertions.assertNotSame((BaseLlm) instanceA, (BaseLlm) after);
    Assertions.assertSame((BaseLlm) instanceB, (BaseLlm) after);
  }

  @Test
  @Order(3)
  @Tag("valid")
  public void nonMatchingCacheEntriesArePreserved() {
    String geminiPattern = "s3-gemini-.*";
    String apigeePattern = "s3-apigee/.*";
    String customPattern = "s3-custom-.*";
    String geminiName = "s3-gemini-pro";
    String apigeeName = "s3-apigee/service-1";
    Map<String, BaseLlm> geminiMap = new ConcurrentHashMap<>();
    BaseLlm geminiInstance = Mockito.mock(BaseLlm.class);
    geminiMap.put(geminiName, geminiInstance);
    LlmFactory geminiFactory = factoryFromMap(geminiMap);
    LlmRegistry.registerLlm(geminiPattern, geminiFactory);
    Map<String, BaseLlm> apigeeMap = new ConcurrentHashMap<>();
    BaseLlm apigeeInstance = Mockito.mock(BaseLlm.class);
    apigeeMap.put(apigeeName, apigeeInstance);
    LlmFactory apigeeFactory = factoryFromMap(apigeeMap);
    LlmRegistry.registerLlm(apigeePattern, apigeeFactory);
    BaseLlm geminiCached = LlmRegistry.getLlm(geminiName);
    BaseLlm apigeeCached = LlmRegistry.getLlm(apigeeName);
    LlmFactory someTestFactory = factoryFromMap(new ConcurrentHashMap<>());
    LlmRegistry.registerTestLlm(customPattern, someTestFactory);
    BaseLlm geminiAfter = LlmRegistry.getLlm(geminiName);
    BaseLlm apigeeAfter = LlmRegistry.getLlm(apigeeName);
    Assertions.assertSame((BaseLlm) geminiCached, (BaseLlm) geminiAfter);
    Assertions.assertSame((BaseLlm) apigeeCached, (BaseLlm) apigeeAfter);
  }

  @Test
  @Order(4)
  @Tag("valid")
  public void clearsAllCachedInstancesThatMatchPattern() {
    String pattern = "s4-batch-.*";
    String a = "s4-batch-a";
    String b = "s4-batch-b";
    String c = "s4-batch-c";
    Map<String, BaseLlm> mapA = new ConcurrentHashMap<>();
    BaseLlm a1 = Mockito.mock(BaseLlm.class);
    BaseLlm b1 = Mockito.mock(BaseLlm.class);
    BaseLlm c1 = Mockito.mock(BaseLlm.class);
    mapA.put(a, a1);
    mapA.put(b, b1);
    mapA.put(c, c1);
    LlmFactory factoryA = factoryFromMap(mapA);
    LlmRegistry.registerTestLlm(pattern, factoryA);
    BaseLlm ca = LlmRegistry.getLlm(a);
    BaseLlm cb = LlmRegistry.getLlm(b);
    BaseLlm cc = LlmRegistry.getLlm(c);
    Assertions.assertSame((BaseLlm) a1, (BaseLlm) ca);
    Assertions.assertSame((BaseLlm) b1, (BaseLlm) cb);
    Assertions.assertSame((BaseLlm) c1, (BaseLlm) cc);
    Map<String, BaseLlm> mapB = new ConcurrentHashMap<>();
    BaseLlm a2 = Mockito.mock(BaseLlm.class);
    BaseLlm b2 = Mockito.mock(BaseLlm.class);
    BaseLlm c2 = Mockito.mock(BaseLlm.class);
    mapB.put(a, a2);
    mapB.put(b, b2);
    mapB.put(c, c2);
    LlmFactory factoryB = factoryFromMap(mapB);
    LlmRegistry.registerTestLlm(pattern, factoryB);
    BaseLlm na = LlmRegistry.getLlm(a);
    BaseLlm nb = LlmRegistry.getLlm(b);
    BaseLlm nc = LlmRegistry.getLlm(c);
    Assertions.assertNotSame((BaseLlm) a1, (BaseLlm) na);
    Assertions.assertNotSame((BaseLlm) b1, (BaseLlm) nb);
    Assertions.assertNotSame((BaseLlm) c1, (BaseLlm) nc);
    Assertions.assertSame((BaseLlm) a2, (BaseLlm) na);
    Assertions.assertSame((BaseLlm) b2, (BaseLlm) nb);
    Assertions.assertSame((BaseLlm) c2, (BaseLlm) nc);
  }

  @Test
  @Order(5)
  @Tag("boundary")
  public void emptyPatternDoesNotAffectNonEmptyModelNames() {
    String normalPattern = "s6-custom-.*";
    String normalName = "s6-custom-1";
    String emptyPattern = "";
    Map<String, BaseLlm> normalMap = new ConcurrentHashMap<>();
    BaseLlm normalInstance = Mockito.mock(BaseLlm.class);
    normalMap.put(normalName, normalInstance);
    LlmFactory normalFactory = factoryFromMap(normalMap);
    LlmRegistry.registerLlm(normalPattern, normalFactory);
    BaseLlm before = LlmRegistry.getLlm(normalName);
    Assertions.assertSame((BaseLlm) normalInstance, (BaseLlm) before);
    Map<String, BaseLlm> emptyMap = new ConcurrentHashMap<>();
    BaseLlm emptyInstance = Mockito.mock(BaseLlm.class);
    emptyMap.put("", emptyInstance);
    LlmFactory emptyFactory = factoryFromMap(emptyMap);
    LlmRegistry.registerTestLlm(emptyPattern, emptyFactory);
    BaseLlm after = LlmRegistry.getLlm(normalName);
    Assertions.assertSame((BaseLlm) normalInstance, (BaseLlm) after);
    BaseLlm emptyCreated = LlmRegistry.getLlm("");
    Assertions.assertSame((BaseLlm) emptyInstance, (BaseLlm) emptyCreated);
  }

  @Test
  @Order(6)
  @Tag("invalid")
  public void nullPatternThrowsNullPointerException() {
    LlmFactory validFactory = factoryFromMap(new ConcurrentHashMap<>());
    Assertions.assertThrows(
        NullPointerException.class, () -> LlmRegistry.registerTestLlm(null, validFactory));
  }

  @Test
  @Order(7)
  @Tag("invalid")
  public void nullFactoryThrowsNullPointerException() {
    Assertions.assertThrows(
        NullPointerException.class, () -> LlmRegistry.registerTestLlm("s8-custom-.*", null));
  }

  @Test
  @Order(8)
  @Tag("valid")
  public void factoryNotInvokedDuringRegistration() {
    String pattern = "s10-custom-.*";
    String name = "s10-custom-1";
    AtomicInteger counter = new AtomicInteger(0);
    LlmFactory countingFactory =
        (String modelName) -> {
          counter.incrementAndGet();
          return Mockito.mock(BaseLlm.class);
        };
    LlmRegistry.registerTestLlm(pattern, countingFactory);
    Assertions.assertEquals((int) 0, (int) counter.get());
    BaseLlm created = LlmRegistry.getLlm(name);
    Assertions.assertNotNull((Object) created);
    Assertions.assertEquals((int) 1, (int) counter.get());
  }

  @Test
  @Order(9)
  @Tag("boundary")
  public void regexIsCaseSensitiveForRemoval() {
    String basePattern = "s11-gemini-.*";
    String name = "s11-gemini-pro";
    Map<String, BaseLlm> baseMap = new ConcurrentHashMap<>();
    BaseLlm original = Mockito.mock(BaseLlm.class);
    baseMap.put(name, original);
    LlmFactory baseFactory = factoryFromMap(baseMap);
    LlmRegistry.registerLlm(basePattern, baseFactory);
    BaseLlm cached = LlmRegistry.getLlm(name);
    String upperPattern = "S11-GEMINI-.*";
    LlmFactory otherFactory = factoryFromMap(new ConcurrentHashMap<>());
    LlmRegistry.registerTestLlm(upperPattern, otherFactory);
    BaseLlm after = LlmRegistry.getLlm(name);
    Assertions.assertSame((BaseLlm) cached, (BaseLlm) after);
  }

  @Test
  @Order(10)
  @Tag("valid")
  public void overridingDefaultGeminiClearsCachedGemini() {
    String geminiPattern = "s12-gemini-.*";
    String modelName = "s12-gemini-pro";
    Map<String, BaseLlm> baseMap = new ConcurrentHashMap<>();
    BaseLlm defaultGemini = Mockito.mock(BaseLlm.class);
    baseMap.put(modelName, defaultGemini);
    LlmFactory baseFactory = factoryFromMap(baseMap);
    LlmRegistry.registerLlm(geminiPattern, baseFactory);
    BaseLlm cached = LlmRegistry.getLlm(modelName);
    Assertions.assertSame((BaseLlm) defaultGemini, (BaseLlm) cached);
    Map<String, BaseLlm> testMap = new ConcurrentHashMap<>();
    BaseLlm testGemini = Mockito.mock(BaseLlm.class);
    testMap.put(modelName, testGemini);
    LlmFactory testFactory = factoryFromMap(testMap);
    LlmRegistry.registerTestLlm(geminiPattern, testFactory);
    BaseLlm after = LlmRegistry.getLlm(modelName);
    Assertions.assertNotSame((BaseLlm) defaultGemini, (BaseLlm) after);
    Assertions.assertSame((BaseLlm) testGemini, (BaseLlm) after);
  }

  @Test
  @Order(11)
  @Tag("integration")
  public void concurrentRegistrationDoesNotThrowAndEndsInConsistentState()
      throws InterruptedException {
    String pattern = "s13-custom-.*";
    String name = "s13-custom-1";
    Map<String, BaseLlm> mapA = new ConcurrentHashMap<>();
    BaseLlm aInstance = Mockito.mock(BaseLlm.class);
    mapA.put(name, aInstance);
    LlmFactory factoryA = factoryFromMap(mapA);
    LlmRegistry.registerTestLlm(pattern, factoryA);
    AtomicReference<Throwable> failure = new AtomicReference<>(null);
    CountDownLatch ready = new CountDownLatch(1);
    Thread worker =
        new Thread(
            () -> {
              ready.countDown();
              for (int i = 0; i < 100; i++) { // TODO adjust iterations if needed
                try {
                  BaseLlm v = LlmRegistry.getLlm(name);
                  Assertions.assertNotNull((Object) v);
                } catch (Throwable t) {
                  failure.compareAndSet(null, t);
                }
              }
            });
    worker.start();
    ready.await();
    Map<String, BaseLlm> mapB = new ConcurrentHashMap<>();
    BaseLlm bInstance = Mockito.mock(BaseLlm.class);
    mapB.put(name, bInstance);
    LlmFactory factoryB = factoryFromMap(mapB);
    LlmRegistry.registerTestLlm(pattern, factoryB);
    worker.join();
    Assertions.assertNull((Throwable) failure.get());
    BaseLlm finalInstance = LlmRegistry.getLlm(name);
    Assertions.assertSame((BaseLlm) bInstance, (BaseLlm) finalInstance);
  }

  @Test
  @Order(12)
  @Tag("valid")
  public void lastRegisteredFactoryForPatternIsUsed() {
    String pattern = "s14-custom-.*";
    String name = "s14-custom-xyz";
    Map<String, BaseLlm> mapA = new ConcurrentHashMap<>();
    BaseLlm a = Mockito.mock(BaseLlm.class);
    mapA.put(name, a);
    LlmFactory factoryA = factoryFromMap(mapA);
    Map<String, BaseLlm> mapB = new ConcurrentHashMap<>();
    BaseLlm b = Mockito.mock(BaseLlm.class);
    mapB.put(name, b);
    LlmFactory factoryB = factoryFromMap(mapB);
    LlmRegistry.registerTestLlm(pattern, factoryA);
    LlmRegistry.registerTestLlm(pattern, factoryB);
    BaseLlm actual = LlmRegistry.getLlm(name);
    Assertions.assertSame((BaseLlm) b, (BaseLlm) actual);
  }

  @Test
  @Order(13)
  @Tag("valid")
  public void overridingApigeeDoesNotAffectGeminiCache() {
    String apigeePattern = "s15-apigee/.*";
    String geminiPattern = "s15-gemini-.*";
    String apigeeName = "s15-apigee/service-1";
    String geminiName = "s15-gemini-pro";
    Map<String, BaseLlm> apigeeBaseMap = new ConcurrentHashMap<>();
    BaseLlm apigeeInitial = Mockito.mock(BaseLlm.class);
    apigeeBaseMap.put(apigeeName, apigeeInitial);
    LlmFactory apigeeBaseFactory = factoryFromMap(apigeeBaseMap);
    LlmRegistry.registerLlm(apigeePattern, apigeeBaseFactory);
    Map<String, BaseLlm> geminiBaseMap = new ConcurrentHashMap<>();
    BaseLlm geminiInitial = Mockito.mock(BaseLlm.class);
    geminiBaseMap.put(geminiName, geminiInitial);
    LlmFactory geminiBaseFactory = factoryFromMap(geminiBaseMap);
    LlmRegistry.registerLlm(geminiPattern, geminiBaseFactory);
    BaseLlm apigeeCached = LlmRegistry.getLlm(apigeeName);
    BaseLlm geminiCached = LlmRegistry.getLlm(geminiName);
    Map<String, BaseLlm> apigeeNewMap = new ConcurrentHashMap<>();
    BaseLlm apigeeNew = Mockito.mock(BaseLlm.class);
    apigeeNewMap.put(apigeeName, apigeeNew);
    LlmFactory apigeeNewFactory = factoryFromMap(apigeeNewMap);
    LlmRegistry.registerTestLlm(apigeePattern, apigeeNewFactory);
    BaseLlm apigeeAfter = LlmRegistry.getLlm(apigeeName);
    BaseLlm geminiAfter = LlmRegistry.getLlm(geminiName);
    Assertions.assertNotSame((BaseLlm) apigeeCached, (BaseLlm) apigeeAfter);
    Assertions.assertSame((BaseLlm) apigeeNew, (BaseLlm) apigeeAfter);
    Assertions.assertSame((BaseLlm) geminiCached, (BaseLlm) geminiAfter);
  }

  @Test
  @Order(14)
  @Tag("boundary")
  public void exactPatternRemovesOnlyExactModelName() {
    String broadPattern = "s16-custom-.*";
    String exactPattern = "s16-custom-1";
    String name1 = "s16-custom-1";
    String name10 = "s16-custom-10";
    Map<String, BaseLlm> broadMap = new ConcurrentHashMap<>();
    BaseLlm i1 = Mockito.mock(BaseLlm.class);
    BaseLlm i10 = Mockito.mock(BaseLlm.class);
    broadMap.put(name1, i1);
    broadMap.put(name10, i10);
    LlmFactory broadFactory = factoryFromMap(broadMap);
    LlmRegistry.registerTestLlm(broadPattern, broadFactory);
    BaseLlm c1 = LlmRegistry.getLlm(name1);
    BaseLlm c10 = LlmRegistry.getLlm(name10);
    Assertions.assertSame((BaseLlm) i1, (BaseLlm) c1);
    Assertions.assertSame((BaseLlm) i10, (BaseLlm) c10);
    Map<String, BaseLlm> replacementMap = new ConcurrentHashMap<>();
    BaseLlm r1 = Mockito.mock(BaseLlm.class);
    replacementMap.put(name1, r1);
    LlmFactory replacementFactory = factoryFromMap(replacementMap);
    LlmRegistry.registerTestLlm(exactPattern, replacementFactory);
    BaseLlm n1 = LlmRegistry.getLlm(name1);
    BaseLlm n10 = LlmRegistry.getLlm(name10);
    Assertions.assertSame((BaseLlm) r1, (BaseLlm) n1);
    Assertions.assertSame((BaseLlm) i10, (BaseLlm) n10);
  }

  @Test
  @Order(15)
  @Tag("boundary")
  public void clearsLargeNumberOfMatchingCachedEntriesEfficiently() {
    String pattern = "s17-bulk-.*";
    Map<String, BaseLlm> mapA = new ConcurrentHashMap<>();
    Map<String, BaseLlm> mapB = new ConcurrentHashMap<>();
    for (int i = 1; i <= 100; i++) { // TODO adjust bulk size if necessary
      String key = "s17-bulk-" + i;
      mapA.put(key, Mockito.mock(BaseLlm.class));
      mapB.put(key, Mockito.mock(BaseLlm.class));
    }
    LlmFactory factoryA = factoryFromMap(mapA);
    LlmFactory factoryB = factoryFromMap(mapB);
    LlmRegistry.registerTestLlm(pattern, factoryA);
    BaseLlm firstA = LlmRegistry.getLlm("s17-bulk-1");
    BaseLlm midA = LlmRegistry.getLlm("s17-bulk-50");
    BaseLlm lastA = LlmRegistry.getLlm("s17-bulk-100");
    LlmRegistry.registerTestLlm(pattern, factoryB);
    BaseLlm firstB = LlmRegistry.getLlm("s17-bulk-1");
    BaseLlm midB = LlmRegistry.getLlm("s17-bulk-50");
    BaseLlm lastB = LlmRegistry.getLlm("s17-bulk-100");
    Assertions.assertNotSame((BaseLlm) firstA, (BaseLlm) firstB);
    Assertions.assertNotSame((BaseLlm) midA, (BaseLlm) midB);
    Assertions.assertNotSame((BaseLlm) lastA, (BaseLlm) lastB);
    Assertions.assertSame((BaseLlm) mapB.get("s17-bulk-1"), (BaseLlm) firstB);
    Assertions.assertSame((BaseLlm) mapB.get("s17-bulk-50"), (BaseLlm) midB);
    Assertions.assertSame((BaseLlm) mapB.get("s17-bulk-100"), (BaseLlm) lastB);
  }

  @Test
  @Order(16)
  @Tag("boundary")
  public void escapedCharactersInPatternAreHandledCorrectly() {
    String pattern = "s18-custom\\+model-.*";
    String name = "s18-custom+model-1";
    Map<String, BaseLlm> mapA = new ConcurrentHashMap<>();
    BaseLlm before = Mockito.mock(BaseLlm.class);
    mapA.put(name, before);
    LlmFactory factoryA = factoryFromMap(mapA);
    LlmRegistry.registerTestLlm(pattern, factoryA);
    BaseLlm cached = LlmRegistry.getLlm(name);
    Assertions.assertSame((BaseLlm) before, (BaseLlm) cached);
    Map<String, BaseLlm> mapB = new ConcurrentHashMap<>();
    BaseLlm after = Mockito.mock(BaseLlm.class);
    mapB.put(name, after);
    LlmFactory factoryB = factoryFromMap(mapB);
    LlmRegistry.registerTestLlm(pattern, factoryB);
    BaseLlm now = LlmRegistry.getLlm(name);
    Assertions.assertNotSame((BaseLlm) before, (BaseLlm) now);
    Assertions.assertSame((BaseLlm) after, (BaseLlm) now);
  }

  @Test
  @Order(17)
  @Tag("valid")
  public void nonMatchingPatternDoesNotClearExistingCache() {
    String existingPattern = "s19-gemini-.*";
    String newPattern = "s19-custom-.*";
    String existingName = "s19-gemini-pro";
    String newName = "s19-custom-1";
    Map<String, BaseLlm> baseMap = new ConcurrentHashMap<>();
    BaseLlm existing = Mockito.mock(BaseLlm.class);
    baseMap.put(existingName, existing);
    LlmFactory baseFactory = factoryFromMap(baseMap);
    LlmRegistry.registerLlm(existingPattern, baseFactory);
    BaseLlm cached = LlmRegistry.getLlm(existingName);
    Map<String, BaseLlm> newMap = new ConcurrentHashMap<>();
    BaseLlm created = Mockito.mock(BaseLlm.class);
    newMap.put(newName, created);
    LlmFactory newFactory = factoryFromMap(newMap);
    LlmRegistry.registerTestLlm(newPattern, newFactory);
    BaseLlm still = LlmRegistry.getLlm(existingName);
    Assertions.assertSame((BaseLlm) cached, (BaseLlm) still);
    BaseLlm newCreated = LlmRegistry.getLlm(newName);
    Assertions.assertSame((BaseLlm) created, (BaseLlm) newCreated);
  }

  @Test
  @Order(18)
  @Tag("integration")
  public void postOverrideLookupsUseNewFactoryDespiteConcurrentActivity()
      throws InterruptedException {
    String pattern = "s20-override-.*";
    String name = "s20-override-1";
    Map<String, BaseLlm> mapA = new ConcurrentHashMap<>();
    BaseLlm pre = Mockito.mock(BaseLlm.class);
    mapA.put(name, pre);
    LlmFactory factoryA = factoryFromMap(mapA);
    LlmRegistry.registerTestLlm(pattern, factoryA);
    CountDownLatch firstDone = new CountDownLatch(1);
    AtomicReference<BaseLlm> firstRef = new AtomicReference<>(null);
    Thread t =
        new Thread(
            () -> {
              BaseLlm v = LlmRegistry.getLlm(name);
              firstRef.set(v);
              firstDone.countDown();
            });
    t.start();
    firstDone.await();
    Map<String, BaseLlm> mapB = new ConcurrentHashMap<>();
    BaseLlm post = Mockito.mock(BaseLlm.class);
    mapB.put(name, post);
    LlmFactory factoryB = factoryFromMap(mapB);
    LlmRegistry.registerTestLlm(pattern, factoryB);
    BaseLlm after = LlmRegistry.getLlm(name);
    Assertions.assertNotSame((BaseLlm) firstRef.get(), (BaseLlm) after);
    Assertions.assertSame((BaseLlm) post, (BaseLlm) after);
  }

  @Test
  @Order(19)
  @Tag("boundary")
  public void catchAllPatternClearsAllCachedInstances() {
    String gPattern = "s5-gemini-.*";
    String aPattern = "s5-apigee/.*";
    String mPattern = "s5-misc-.*";
    String gName = "s5-gemini-pro";
    String aName = "s5-apigee/service-x";
    String mName = "s5-misc-123";
    Map<String, BaseLlm> gMap = new ConcurrentHashMap<>();
    BaseLlm gOld = Mockito.mock(BaseLlm.class);
    gMap.put(gName, gOld);
    LlmFactory gFactory = factoryFromMap(gMap);
    LlmRegistry.registerLlm(gPattern, gFactory);
    Map<String, BaseLlm> aMap = new ConcurrentHashMap<>();
    BaseLlm aOld = Mockito.mock(BaseLlm.class);
    aMap.put(aName, aOld);
    LlmFactory aFactory = factoryFromMap(aMap);
    LlmRegistry.registerLlm(aPattern, aFactory);
    Map<String, BaseLlm> mMap = new ConcurrentHashMap<>();
    BaseLlm mOld = Mockito.mock(BaseLlm.class);
    mMap.put(mName, mOld);
    LlmFactory mFactory = factoryFromMap(mMap);
    LlmRegistry.registerLlm(mPattern, mFactory);
    BaseLlm cG = LlmRegistry.getLlm(gName);
    BaseLlm cA = LlmRegistry.getLlm(aName);
    BaseLlm cM = LlmRegistry.getLlm(mName);
    Assertions.assertSame((BaseLlm) gOld, (BaseLlm) cG);
    Assertions.assertSame((BaseLlm) aOld, (BaseLlm) cA);
    Assertions.assertSame((BaseLlm) mOld, (BaseLlm) cM);
    String catchAll = ".*";
    Map<String, BaseLlm> allMap = new ConcurrentHashMap<>();
    BaseLlm gNew = Mockito.mock(BaseLlm.class);
    BaseLlm aNew = Mockito.mock(BaseLlm.class);
    BaseLlm mNew = Mockito.mock(BaseLlm.class);
    allMap.put(gName, gNew);
    allMap.put(aName, aNew);
    allMap.put(mName, mNew);
    LlmFactory allFactory = factoryFromMap(allMap);
    LlmRegistry.registerTestLlm(catchAll, allFactory);
    BaseLlm gAfter = LlmRegistry.getLlm(gName);
    BaseLlm aAfter = LlmRegistry.getLlm(aName);
    BaseLlm mAfter = LlmRegistry.getLlm(mName);
    Assertions.assertNotSame((BaseLlm) gOld, (BaseLlm) gAfter);
    Assertions.assertNotSame((BaseLlm) aOld, (BaseLlm) aAfter);
    Assertions.assertNotSame((BaseLlm) mOld, (BaseLlm) mAfter);
    Assertions.assertSame((BaseLlm) gNew, (BaseLlm) gAfter);
    Assertions.assertSame((BaseLlm) aNew, (BaseLlm) aAfter);
    Assertions.assertSame((BaseLlm) mNew, (BaseLlm) mAfter);
  }

  @Test
  @Order(20)
  @Tag("invalid")
  public void invalidRegexPatternThrowsPatternSyntaxException() {
    String existingPattern = "s9-gemini-.*";
    String existingName = "s9-gemini-pro";
    Map<String, BaseLlm> baseMap = new ConcurrentHashMap<>();
    BaseLlm existing = Mockito.mock(BaseLlm.class);
    baseMap.put(existingName, existing);
    LlmFactory baseFactory = factoryFromMap(baseMap);
    LlmRegistry.registerLlm(existingPattern, baseFactory);
    BaseLlm cached = LlmRegistry.getLlm(existingName);
    Assertions.assertSame((BaseLlm) existing, (BaseLlm) cached);
    LlmFactory someFactory = factoryFromMap(new ConcurrentHashMap<>());
    Assertions.assertThrows(
        PatternSyntaxException.class, () -> LlmRegistry.registerTestLlm("(", someFactory));
  }
}
