/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test adk-java-demo using AI Type Azure Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=registerLlm_39033090dc
ROOST_METHOD_SIG_HASH=registerLlm_6d1828529e

Scenario 1: Registering a New Model Name Pattern and Factory

Details:
  TestName: registerNewPatternAndFactory
  Description: This test case verifies that when the registerLlm method is invoked with a new, previously unregistered modelNamePattern and a valid factory, the mapping is correctly inserted into the llmFactories map.

Execution:
  Arrange: Prepare a unique model name pattern string and a mock or fake implementation of LlmFactory.
  Act: Call registerLlm with the unique pattern and the factory.
  Assert: Check that llmFactories contains the new pattern with its associated factory.

Validation:
  The assertion confirms that a new pattern-factory association is registered. This ensures extendability and correctness in dynamically registering new model providers.


Scenario 2: Overwriting an Existing Factory for an Existing Pattern

Details:
  TestName: overwriteExistingPatternFactory
  Description: This test checks whether calling registerLlm with an already-registered modelNamePattern will successfully overwrite the existing factory associated with that pattern in llmFactories.

Execution:
  Arrange: Add a pattern with an initial factory to llmFactories or via registerLlm; create a second factory.
  Act: Call registerLlm for the same pattern using the new factory.
  Assert: Confirm that llmFactories maps the pattern to the new factory, replacing the old one.

Validation:
  The assertion validates the expected overwrite behavior of the map, which is crucial to support factory updates or hot-swapping in runtime.


Scenario 3: Registering a Null Pattern

Details:
  TestName: registerNullPattern
  Description: This test checks what happens if registerLlm is invoked with a null modelNamePattern. It's intended to verify whether the ConcurrentHashMap accepts null keys and how the method handles this invalid input.

Execution:
  Arrange: Create a valid instance of LlmFactory.
  Act: Call registerLlm with null as the pattern and the valid factory.
  Assert: Validate the resulting behavior (expecting a NullPointerException or equivalent behavior due to ConcurrentHashMap policy).

Validation:
  The assertion demonstrates how the registry enforces or fails to enforce non-null keys, preventing accidental configuration errors and runtime faults.


Scenario 4: Registering a Null Factory

Details:
  TestName: registerNullFactory
  Description: This test ensures the method’s behavior when a valid modelNamePattern is registered but the factory argument is null.

Execution:
  Arrange: Prepare a valid model name pattern.
  Act: Call registerLlm with the valid pattern and a null factory.
  Assert: Check for the presence of the pattern in llmFactories with a null value or an exception if thrown.

Validation:
  The assertion is necessary to clarify if the implementation supports null factories, which could cause runtime failures when creating LLM instances.


Scenario 5: Registering Duplicate Patterns Concurrently

Details:
  TestName: registerPatternConcurrently
  Description: This test ensures that concurrent invocations of registerLlm for the same pattern but with different factories work correctly without causing data races or inconsistent state in llmFactories.

Execution:
  Arrange: Create multiple threads, each with the same pattern and different factory instances.
  Act: Start all threads to invoke registerLlm concurrently.
  Assert: After all threads finish, verify that llmFactories contains the pattern and one of the registered factories.

Validation:
  Verifies thread-safety and correct atomic map updating, essential in a concurrent environment such as a registry for LLM providers.


Scenario 6: Registering a Pattern that Matches Built-in Factories

Details:
  TestName: registerConflictingBuiltinPattern
  Description: This test assesses the result of registering a modelNamePattern that is identical to or overlaps with one of the patterns registered in the static initializer block (such as "gemini-.*").

Execution:
  Arrange: Prepare a pattern (like "gemini-.*") used in static registration and a test factory.
  Act: Call registerLlm with this pattern and the custom factory.
  Assert: Check that llmFactories now maps this pattern to the latest factory, overriding the built-in one.

Validation:
  This checks if user-supplied registrations can override pre-registered (default) factories, which could affect base functionality and configurability.


Scenario 7: Registering an Empty String as Pattern

Details:
  TestName: registerEmptyStringPattern
  Description: This test determines if an empty string pattern can be registered and properly stored in llmFactories.

Execution:
  Arrange: Create a valid LlmFactory.
  Act: Call registerLlm with an empty string and the factory.
  Assert: Verify that llmFactories has an entry with the empty string as the key and the provided factory as the value.

Validation:
  Needed to see how the system handles potentially invalid or catch-all configurations, as empty patterns might be applied broadly or lead to ambiguous matching.


Scenario 8: Registering Multiple Distinct Patterns

Details:
  TestName: registerMultipleDistinctPatterns
  Description: This test checks whether registerLlm can successfully register several different modelNamePatterns (all unique) with distinct factories, ensuring the map is additive and not destructive to previous entries.

Execution:
  Arrange: Prepare several unique patterns and their associated factories.
  Act: Invoke registerLlm multiple times (one per pattern/factory pair).
  Assert: Confirm that all patterns are present in llmFactories, each mapped to the correct factory.

Validation:
  Demonstrates the ability to support multiple providers, which is central to the extensibility of the registry.


Scenario 9: Registering a Pattern with Special Regex Characters

Details:
  TestName: registerRegexSpecialCharsPattern
  Description: This test validates that complex or special-regex-character patterns are correctly registered and retrievable from llmFactories.

Execution:
  Arrange: Define a pattern with special regex symbols (e.g., "^apigee-\\d{3}$") and a suitable factory.
  Act: Call registerLlm with this regex and the factory.
  Assert: Confirm the pattern exists as entered in llmFactories, with the expected factory.

Validation:
  Important for supporting advanced matching capabilities, ensuring users can employ precise or complex regex patterns without data loss or corruption.


Scenario 10: Registering a Factory with a Pattern Already Having Null Value

Details:
  TestName: registerFactoryWithPatternHavingNullValue
  Description: This test simulates a case where the llmFactories map (perhaps due to a previous faulty registration) has a pattern mapped to null and verifies that re-registering with a valid factory replaces the null.

Execution:
  Arrange: Insert a null value into llmFactories for a given pattern (using registerLlm or direct insertion if possible).
  Act: Call registerLlm with the pattern and a valid factory.
  Assert: Check that the pattern now maps to the new, non-null factory.

Validation:
  Ensures resiliency when recovering from unintentionally broken map entries, a plausible scenario in mutable registries.

*/

// ********RoostGPT********

package com.google.adk.models;

import java.util.Map;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

// Mocking dependencies according to instructions.
public class LlmRegistryRegisterLlmTest {

  // Using test setup to clean static map before each test
  @BeforeEach
  public void setUp() {
    // Clear static map to avoid cross-test pollution
    Map<String, LlmRegistry.LlmFactory> llmFactories = getLlmFactories();
    llmFactories.clear();
  }

  private Map<String, LlmRegistry.LlmFactory> getLlmFactories() {
    // Reflective access to static field for validation, according to instructions
    try {
      java.lang.reflect.Field f = LlmRegistry.class.getDeclaredField("llmFactories");
      f.setAccessible(true);
      return (Map<String, LlmRegistry.LlmFactory>) f.get(null);
    } catch (Exception ex) {
      throw new RuntimeException("Reflection failed", ex);
    }
  }

  @Test
  @Tag("valid")
  @DisplayName("Scenario 1: Registering a New Model Name Pattern and Factory")
  public void testRegisterNewPatternAndFactory() {
    String uniquePattern = "test-model-abc";
    LlmRegistry.LlmFactory mockFactory = Mockito.mock(LlmRegistry.LlmFactory.class);
    LlmRegistry.registerLlm(uniquePattern, mockFactory);
    Assertions.assertEquals(
        mockFactory,
        getLlmFactories().get(uniquePattern),
        "Factory should be registered for new pattern");
  }

  @Test
  @Tag("valid")
  @DisplayName("Scenario 2: Overwriting an Existing Factory for an Existing Pattern")
  public void testOverwriteExistingPatternFactory() {
    String pattern = "overwritable-pattern";
    LlmRegistry.LlmFactory firstFactory = Mockito.mock(LlmRegistry.LlmFactory.class);
    LlmRegistry.LlmFactory secondFactory = Mockito.mock(LlmRegistry.LlmFactory.class);
    LlmRegistry.registerLlm(pattern, firstFactory);
    LlmRegistry.registerLlm(pattern, secondFactory);
    Assertions.assertEquals(
        secondFactory, getLlmFactories().get(pattern), "Factory should be overwritten with latest");
  }

  @Test
  @Tag("invalid")
  @DisplayName("Scenario 3: Registering a Null Pattern")
  public void testRegisterNullPattern() {
    LlmRegistry.LlmFactory factory = Mockito.mock(LlmRegistry.LlmFactory.class);
    Assertions.assertThrows(
        NullPointerException.class,
        () -> {
          LlmRegistry.registerLlm(null, factory);
        },
        "ConcurrentHashMap should throw NullPointerException for null key");
  }

  @Test
  @Tag("invalid")
  @DisplayName("Scenario 4: Registering a Null Factory")
  public void testRegisterNullFactory() {
    String pattern = "null-factory-pattern";
    LlmRegistry.registerLlm(pattern, null);
    Assertions.assertNull(
        getLlmFactories().get(pattern), "Factory should be null for valid pattern");
  }

  @Test
  @Tag("integration")
  @DisplayName("Scenario 5: Registering Duplicate Patterns Concurrently")
  public void testRegisterPatternConcurrently() throws InterruptedException {
    String pattern = "concurrent-pattern";
    LlmRegistry.LlmFactory factory1 = Mockito.mock(LlmRegistry.LlmFactory.class);
    LlmRegistry.LlmFactory factory2 = Mockito.mock(LlmRegistry.LlmFactory.class);
    LlmRegistry.LlmFactory factory3 = Mockito.mock(LlmRegistry.LlmFactory.class);
    Thread t1 = new Thread(() -> LlmRegistry.registerLlm(pattern, factory1));
    Thread t2 = new Thread(() -> LlmRegistry.registerLlm(pattern, factory2));
    Thread t3 = new Thread(() -> LlmRegistry.registerLlm(pattern, factory3));
    t1.start();
    t2.start();
    t3.start();
    t1.join();
    t2.join();
    t3.join();
    // One of the factories (last write wins) should be associated
    LlmRegistry.LlmFactory actualFactory = getLlmFactories().get(pattern);
    Assertions.assertTrue(
        actualFactory == factory1 || actualFactory == factory2 || actualFactory == factory3,
        "One of the concurrently registered factories should be mapped");
  }

  @Test
  @Tag("boundary")
  @DisplayName("Scenario 6: Registering a Pattern that Matches Built-in Factories")
  public void testRegisterConflictingBuiltinPattern() {
    String builtinPattern = "gemini-.*"; // TODO: Adjust if builtin static initializer
    // uses a different pattern
    LlmRegistry.LlmFactory customFactory = Mockito.mock(LlmRegistry.LlmFactory.class);
    LlmRegistry.registerLlm(builtinPattern, customFactory);
    Assertions.assertEquals(
        customFactory,
        getLlmFactories().get(builtinPattern),
        "Custom factory should override builtin factory");
  }

  @Test
  @Tag("boundary")
  @DisplayName("Scenario 7: Registering an Empty String as Pattern")
  public void testRegisterEmptyStringPattern() {
    String emptyPattern = "";
    LlmRegistry.LlmFactory emptyFactory = Mockito.mock(LlmRegistry.LlmFactory.class);
    LlmRegistry.registerLlm(emptyPattern, emptyFactory);
    Assertions.assertEquals(
        emptyFactory,
        getLlmFactories().get(emptyPattern),
        "Empty pattern should be allowed and mapped");
  }

  @Test
  @Tag("valid")
  @DisplayName("Scenario 8: Registering Multiple Distinct Patterns")
  public void testRegisterMultipleDistinctPatterns() {
    LlmRegistry.LlmFactory factoryOne = Mockito.mock(LlmRegistry.LlmFactory.class);
    LlmRegistry.LlmFactory factoryTwo = Mockito.mock(LlmRegistry.LlmFactory.class);
    LlmRegistry.LlmFactory factoryThree = Mockito.mock(LlmRegistry.LlmFactory.class);
    String patternOne = "unique-pattern-1";
    String patternTwo = "unique-pattern-2";
    String patternThree = "unique-pattern-3";
    LlmRegistry.registerLlm(patternOne, factoryOne);
    LlmRegistry.registerLlm(patternTwo, factoryTwo);
    LlmRegistry.registerLlm(patternThree, factoryThree);
    Assertions.assertEquals(
        factoryOne,
        getLlmFactories().get(patternOne),
        "First unique pattern should match its factory");
    Assertions.assertEquals(
        factoryTwo,
        getLlmFactories().get(patternTwo),
        "Second unique pattern should match its factory");
    Assertions.assertEquals(
        factoryThree,
        getLlmFactories().get(patternThree),
        "Third unique pattern should match its factory");
  }

  @Test
  @Tag("boundary")
  @DisplayName("Scenario 9: Registering a Pattern with Special Regex Characters")
  public void testRegisterRegexSpecialCharsPattern() {
    String specialPattern = "^apigee-\\d{3}$";
    LlmRegistry.LlmFactory regexFactory = Mockito.mock(LlmRegistry.LlmFactory.class);
    LlmRegistry.registerLlm(specialPattern, regexFactory);
    Assertions.assertEquals(
        regexFactory,
        getLlmFactories().get(specialPattern),
        "Special regex pattern should be mapped correctly");
  }

  @Test
  @Tag("boundary")
  @DisplayName("Scenario 10: Registering a Factory with a Pattern Already Having Null Value")
  public void testRegisterFactoryWithPatternHavingNullValue() {
    String nullPattern = "null-pattern";
    // Register with null factory first
    LlmRegistry.registerLlm(nullPattern, null);
    Assertions.assertNull(getLlmFactories().get(nullPattern), "Should initially be null");
    // Register again with a valid factory
    LlmRegistry.LlmFactory recoveryFactory = Mockito.mock(LlmRegistry.LlmFactory.class);
    LlmRegistry.registerLlm(nullPattern, recoveryFactory);
    Assertions.assertEquals(
        recoveryFactory,
        getLlmFactories().get(nullPattern),
        "Null should be replaced with valid factory");
  }
}
