/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-adk using AI Type Azure Open AI and AI Model gpt-5

ROOST_METHOD_HASH=registerLlm_39033090dc
ROOST_METHOD_SIG_HASH=registerLlm_6d1828529e

Scenario 1: Registering a new regex pattern enables retrieval of a matching model

Details:
  TestName: registerNewPatternEnablesRetrieval
  Description: Verifies that calling registerLlm with a previously unsupported regex pattern stores the factory so that a subsequent getLlm for a matching model name returns an instance created by that factory.

Execution:
  Arrange: Create a LlmFactory test double that returns a unique, identifiable BaseLlm stub for the provided model name. Choose a regex pattern such as "custom-.*" and a model name like "custom-123" that matches it.
  Act: Invoke registerLlm("custom-.*", factory), then call getLlm("custom-123").
  Assert: Use assertNotNull to verify the returned BaseLlm is not null, and use assertSame (or assertEquals on a known marker) to verify the object returned by getLlm is the exact instance produced by the factory for "custom-123".

Validation:
  This assertion verifies that registerLlm correctly inserts the mapping so that the registry can find and use the new factory. It demonstrates the core behavior of registering support for new model name patterns.

*/

// ********RoostGPT********

package com.google.adk.models;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.lang.reflect.Proxy;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class LlmRegistryRegisterLlmTest {

  private static Class<?> llmFactoryClass() {
    try {
      return Class.forName("com.google.adk.models.LlmFactory");
    } catch (ClassNotFoundException e) {
      throw new RuntimeException("LlmFactory class not found on classpath", e);
    }
  }

  private static Object newFactoryProxy(
      final String expectedModelName, final BaseLlm returned, final int[] callCount) {
    Class<?> factoryClazz = llmFactoryClass();
    return Proxy.newProxyInstance(
        factoryClazz.getClassLoader(),
        new Class<?>[] {factoryClazz},
        (proxy, method, args) -> {
          String name = method.getName();
          if ("create".equals(name) && args != null && args.length == 1) {
            callCount[0]++;
            return returned;
          }
          if ("toString".equals(name) && (args == null || args.length == 0)) {
            return "LlmFactoryProxy";
          }
          if ("hashCode".equals(name) && (args == null || args.length == 0)) {
            return System.identityHashCode(proxy);
          }
          if ("equals".equals(name) && args != null && args.length == 1) {
            return proxy == args[0];
          }
          throw new UnsupportedOperationException("Unexpected method: " + method);
        });
  }

  private static void invokeRegisterLlm(String pattern, Object factory) {
    try {
      Method m = LlmRegistry.class.getMethod("registerLlm", String.class, llmFactoryClass());
      m.invoke(null, pattern, factory);
    } catch (InvocationTargetException ite) {
      Throwable cause = ite.getCause();
      if (cause instanceof RuntimeException) {
        throw (RuntimeException) cause;
      }
      throw new RuntimeException(cause);
    } catch (Exception e) {
      throw new RuntimeException(e);
    }
  }

  private static void invokeRegisterTestLlm(String pattern, Object factory) {
    try {
      Method m = LlmRegistry.class.getMethod("registerTestLlm", String.class, llmFactoryClass());
      m.invoke(null, pattern, factory);
    } catch (InvocationTargetException ite) {
      Throwable cause = ite.getCause();
      if (cause instanceof RuntimeException) {
        throw (RuntimeException) cause;
      }
      throw new RuntimeException(cause);
    } catch (NoSuchMethodException nsme) {
      // If registerTestLlm is not available, this test may indicate a missing
      // enhancement in
      // business logic.
      throw new RuntimeException(
          "registerTestLlm(String, LlmFactory) not found. Consider adding this API to support test resets.",
          nsme);
    } catch (Exception e) {
      throw new RuntimeException(e);
    }
  }

  @Test
  @Tag("valid")
  public void testRegisterNewPatternEnablesRetrieval() {
    final String pattern = "^custom-.*$";
    final String modelName = "custom-123";
    BaseLlm expectedLlm = Mockito.mock(BaseLlm.class);
    final int[] calls = new int[] {0};
    Object factory = newFactoryProxy(modelName, expectedLlm, calls);
    invokeRegisterLlm(pattern, factory);
    BaseLlm actualLlm = LlmRegistry.getLlm(modelName);
    Assertions.assertNotNull((Object) actualLlm, "Expected non-null LLM instance");
    Assertions.assertSame(
        (Object) expectedLlm,
        (Object) actualLlm,
        "Registry should return instance produced by factory");
    Assertions.assertEquals(
        (Object) 1, (Object) calls[0], "Factory.create should be called exactly once");
  }

  @Test
  @Tag("valid")
  public void testCacheReturnsSameInstanceForRepeatedGetLlm() {
    final String pattern = "^cache-.*$";
    final String modelName = "cache-001";
    BaseLlm instance = Mockito.mock(BaseLlm.class);
    final int[] calls = new int[] {0};
    Object factory = newFactoryProxy(modelName, instance, calls);
    invokeRegisterLlm(pattern, factory);
    BaseLlm first = LlmRegistry.getLlm(modelName);
    BaseLlm second = LlmRegistry.getLlm(modelName);
    Assertions.assertNotNull((Object) first);
    Assertions.assertSame(
        (Object) first, (Object) second, "Cached instance should be returned on subsequent calls");
    Assertions.assertEquals(
        (Object) 1, (Object) calls[0], "Factory.create should be called only once due to caching");
  }

  @Test
  @Tag("invalid")
  public void testGetLlmThrowsForUnsupportedModel() {
    final String modelName = "unsupported-model-xyz";
    IllegalArgumentException ex =
        Assertions.assertThrows(
            IllegalArgumentException.class,
            () -> LlmRegistry.getLlm(modelName),
            "Unsupported model should throw IllegalArgumentException");
    Assertions.assertTrue(
        (boolean) ex.getMessage().contains(modelName),
        "Error message should reference the unsupported model");
  }

  @Test
  @Tag("invalid")
  public void testRegisterLlmNullKeyThrows() {
    BaseLlm dummy = Mockito.mock(BaseLlm.class);
    final int[] calls = new int[] {0};
    Object factory = newFactoryProxy("any", dummy, calls);
    Exception ex =
        Assertions.assertThrows(
            Exception.class,
            () -> invokeRegisterLlm(null, factory),
            "Null regex key should throw NullPointerException in ConcurrentHashMap");
    Throwable cause =
        (ex instanceof InvocationTargetException)
            ? ((InvocationTargetException) ex).getCause()
            : ex.getCause();
    Throwable target = (cause == null) ? ex : cause;
    Assertions.assertTrue(
        (boolean) (target instanceof NullPointerException),
        "Expected NullPointerException when key is null");
  }

  @Test
  @Tag("invalid")
  public void testRegisterLlmNullFactoryThrows() {
    final String pattern = "^null-factory-.*$";
    Exception ex =
        Assertions.assertThrows(
            Exception.class,
            () -> invokeRegisterLlm(pattern, null),
            "Null factory should throw NullPointerException in ConcurrentHashMap");
    Throwable cause =
        (ex instanceof InvocationTargetException)
            ? ((InvocationTargetException) ex).getCause()
            : ex.getCause();
    Throwable target = (cause == null) ? ex : cause;
    Assertions.assertTrue(
        (boolean) (target instanceof NullPointerException),
        "Expected NullPointerException when factory is null");
  }

  @Test
  @Tag("boundary")
  public void testInvalidRegexPatternCausesExceptionOnGet() {
    final String badPattern = "[";
    final String modelName = "bad-regex-001";
    BaseLlm instance = Mockito.mock(BaseLlm.class);
    final int[] calls = new int[] {0};
    Object factory = newFactoryProxy(modelName, instance, calls);
    invokeRegisterLlm(badPattern, factory);
    RuntimeException ex =
        Assertions.assertThrows(
            RuntimeException.class,
            () -> LlmRegistry.getLlm(modelName),
            "Invalid regex pattern should cause a runtime exception during matching");
    Assertions.assertNotNull((Object) ex, "Exception should not be null");
  }

  @Test
  @Tag("integration")
  public void testRegisterTestLlmClearsCachedInstancesForPattern() {
    final String pattern = "^reset-.*$";
    final String modelName = "reset-789";
    BaseLlm firstInstance = Mockito.mock(BaseLlm.class);
    final int[] calls1 = new int[] {0};
    Object factory = newFactoryProxy(modelName, firstInstance, calls1);
    invokeRegisterLlm(pattern, factory);
    BaseLlm initial = LlmRegistry.getLlm(modelName);
    Assertions.assertNotNull((Object) initial);
    Object newFactory;
    BaseLlm secondInstance = Mockito.mock(BaseLlm.class);
    final int[] calls2 = new int[] {0};
    newFactory = newFactoryProxy(modelName, secondInstance, calls2);
    invokeRegisterTestLlm(pattern, newFactory);
    BaseLlm afterReset = LlmRegistry.getLlm(modelName);
    Assertions.assertNotNull((Object) afterReset);
    Assertions.assertSame(
        (Object) secondInstance,
        (Object) afterReset,
        "After reset, registry should return instance from new factory");
    Assertions.assertEquals(
        (Object) 1, (Object) calls1[0], "Original factory should have been called exactly once");
    Assertions.assertEquals(
        (Object) 1,
        (Object) calls2[0],
        "New factory should have been called exactly once after reset");
  }

  @Test
  @Tag("integration")
  public void testConcurrentGetLlmCreatesSingleInstance() throws InterruptedException {
    final String pattern = "^concurrent-.*$";
    final String modelName = "concurrent-1";
    BaseLlm singleton = Mockito.mock(BaseLlm.class);
    final int[] calls = new int[] {0};
    Object factory = newFactoryProxy(modelName, singleton, calls);
    invokeRegisterLlm(pattern, factory);
    CountDownLatch start = new CountDownLatch(1);
    CountDownLatch done = new CountDownLatch(2);
    ExecutorService pool = Executors.newFixedThreadPool(2);
    Map<String, BaseLlm> results = new ConcurrentHashMap<>();
    Runnable task =
        () -> {
          try {
            start.await();
            BaseLlm llm = LlmRegistry.getLlm(modelName);
            results.put(Thread.currentThread().getName(), llm);
          } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
          } finally {
            done.countDown();
          }
        };
    pool.submit(task);
    pool.submit(task);
    start.countDown();
    done.await();
    pool.shutdown();
    BaseLlm r1 = results.values().stream().findFirst().orElse(null);
    BaseLlm r2 = results.values().stream().skip(1).findFirst().orElse(null);
    Assertions.assertNotNull((Object) r1);
    Assertions.assertNotNull((Object) r2);
    Assertions.assertSame(
        (Object) r1, (Object) r2, "Both threads should receive the same cached instance");
    Assertions.assertEquals(
        (Object) 1,
        (Object) calls[0],
        "Factory.create should be called exactly once across concurrent access");
  }
}
